### ISSUE TITLE
java.lang.NullPointerException: Attempt to read from field 'int com.android.okio.Segment.limit' on a null object reference

### ISSUE THREAD

**Issue by Yonghejiunian** [firebase/firebase-android-sdk#1006]
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'int com.android.okio.Segment.limit' on a null object reference
       at com.android.okio.OkBuffer.write + 574(OkBuffer.java:574)
       at com.android.okio.OkBuffer.read + 610(OkBuffer.java:610)
       at com.android.okio.RealBufferedSource.read + 56(RealBufferedSource.java:56)
       at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read + 469(HttpConnection.java:469)
       at com.android.okhttp.internal.Util.skipAll + 227(Util.java:227)
       at com.android.okhttp.internal.http.HttpConnection.discard + 239(HttpConnection.java:239)
       at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.close + 491(HttpConnection.java:491)
       at com.android.okio.RealBufferedSource.close + 204(RealBufferedSource.java:204)
       at com.android.okio.RealBufferedSource$1.close + 187(RealBufferedSource.java:187)
       at com.google.android.gms.internal.firebase_messaging.zzk.zza + 4(zzk.java:4)
       at com.google.firebase.messaging.zzd.close + 37(zzd.java:37)
       at com.google.firebase.messaging.zzc.zzas + 51(zzc.java:51)
       at com.google.firebase.messaging.FirebaseMessagingService.zzd + 59(FirebaseMessagingService.java:59)
       at com.google.firebase.iid.zzb.run + 2(zzb.java:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker + 1112(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run + 587(ThreadPoolExecutor.java:587)
       at com.google.android.gms.common.util.concurrent.zza.run + 6(zza.java:6)
       at java.lang.Thread.run + 818(Thread.java:818)

**Comment by samtstern** [comment]
Transferred this issue to the firebase-android-sdk repo since that's the best place for it.

cc @ashwinraghav

**Comment by Yonghejiunian** [comment]
hey , last month we use the CMPP protocol, no crash, but CMPP protocol not support Big Image, we have to use the  http protocol again (default protocol type), this issue come back again ,about 4%-5%, this is a so bad problem, why no one fix it？  i have to Dismantling the arr ,then add try catch or remove "final" in that bad method to override ,when i make ,i will reply again!

**Comment by Yonghejiunian** [comment]
> @Yonghejiunian sorry for my slow response here (I was on vacation) but can you give some more information on how to reproduce this issue?

I Dismantling the aar(firebase-messaging-18.0.0.aar) make it come to local(firebase-messaging-18.0.0_fixcrash.aar) , add "try  catch " and remove "final" in method "public void zzd(Intent var1) ", now is ok ,no crash ,i will make a ABTest, hope you fix this bug, many developers has such issue!

**Comment by deepak786** [comment]
My app also has the same issue from the last few months.
There are ~3500 crashes related to that and all are because of the image in the notification from Firebase console.

```
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'int com.android.okio.Segment.limit' on a null object reference
       at com.android.okio.OkBuffer.write(OkBuffer.java:574)
       at com.android.okio.OkBuffer.read(OkBuffer.java:610)
       at com.android.okio.RealBufferedSource.read(RealBufferedSource.java:56)
       at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:469)
       at com.android.okhttp.internal.Util.skipAll(Util.java:227)
       at com.android.okhttp.internal.http.HttpConnection.discard(HttpConnection.java:239)
       at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.close(HttpConnection.java:491)
       at com.android.okio.RealBufferedSource.close(RealBufferedSource.java:204)
       at com.android.okio.RealBufferedSource$1.close(RealBufferedSource.java:187)
       at f.d.a.b.c.f.j.a(com.google.firebase:firebase-messaging@@20.0.0:1)
       at com.google.firebase.messaging.n.close(com.google.firebase:firebase-messaging@@20.0.0:1)
       at com.google.firebase.messaging.h.a(com.google.firebase:firebase-messaging@@20.0.0:23)
       at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.0.0:42)
       at com.google.firebase.messaging.i.run(com.google.firebase:firebase-messaging@@20.0.0:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at com.google.android.gms.common.util.q.b.run(:2)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by waleedsarwar86** [comment]
I am also getting this issue on different devices.

<img width="1128" alt="Screenshot 2019-12-08 at 8 37 52 PM" src="https://user-images.githubusercontent.com/5875993/70391776-b3f64100-19fa-11ea-92e7-d07a4c72c1a8.png">

```
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'int com.android.okio.Segment.limit' on a null object reference
       at com.android.okio.OkBuffer.write + 574(OkBuffer.java:574)
       at com.android.okio.OkBuffer.read + 610(OkBuffer.java:610)
       at com.android.okio.RealBufferedSource.read + 53(RealBufferedSource.java:53)
       at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read + 446(HttpConnection.java:446)
       at com.android.okhttp.internal.Util.skipAll + 227(Util.java:227)
       at com.android.okhttp.internal.http.HttpConnection.discard + 216(HttpConnection.java:216)
       at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.close + 468(HttpConnection.java:468)
       at com.android.okio.RealBufferedSource.close + 198(RealBufferedSource.java:198)
       at com.android.okio.RealBufferedSource$1.close + 181(RealBufferedSource.java:181)
       at f.c.a.b.b.g.j.a + 1(com.google.firebase:firebase-messaging@@20.0.0:1)
       at com.google.firebase.messaging.l.close + 1(com.google.firebase:firebase-messaging@@20.0.0:1)
       at com.google.firebase.messaging.f.a + 22(com.google.firebase:firebase-messaging@@20.0.0:22)
       at com.google.firebase.messaging.FirebaseMessagingService.zzc + 42(com.google.firebase:firebase-messaging@@20.0.0:42)
       at com.google.firebase.messaging.g.run + 2(com.google.firebase:firebase-messaging@@20.0.0:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker + 1115(ThreadPoolExecutor.java:1115)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run + 590(ThreadPoolExecutor.java:590)
       at com.google.android.gms.common.util.q.d.run + 2(:2)
       at java.lang.Thread.run + 818(Thread.java:818)
```

**Comment by 50l3r** [comment]
Same problem

`Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'int com.android.okhttp.okio.Segment.limit' on a null object reference
       at com.android.okhttp.okio.Buffer.write(Buffer.java:1182)
       at com.android.okhttp.okio.Buffer.read(Buffer.java:1221)
       at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:55)
       at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:393)
       at com.android.okhttp.internal.Util.skipAll(Util.java:159)
       at com.android.okhttp.internal.Util.discard(Util.java:141)
       at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.close(Http1xStream.java:410)
       at com.android.okhttp.okio.RealBufferedSource.close(RealBufferedSource.java:396)
       at com.android.okhttp.okio.RealBufferedSource$1.close(RealBufferedSource.java:384)
       at com.google.android.gms.internal.firebase_messaging.zzk.zza(com.google.firebase:firebase-messaging@@20.0.0:4)
       at com.google.firebase.messaging.zzj.close(com.google.firebase:firebase-messaging@@20.0.0:38)
       at com.google.firebase.messaging.zzd.zza(com.google.firebase:firebase-messaging@@20.0.0:51)
       at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.0.0:60)
       at com.google.firebase.messaging.zze.run(com.google.firebase:firebase-messaging@@20.0.0:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.android.gms.common.util.concurrent.zza.run(:6)
       at java.lang.Thread.run(Thread.java:764)`

Coming from firebase messaging

**Comment by jgersindemir** [comment]
Same problem;
`Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'int com.android.okhttp.okio.Segment.limit' on a null object reference
       at com.android.okhttp.okio.Buffer.write(Buffer.java:1182)
       at com.android.okhttp.okio.Buffer.read(Buffer.java:1221)
       at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:65)
       at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:602)
       at com.android.okhttp.internal.Util.skipAll(Util.java:170)
       at com.android.okhttp.internal.Util.discard(Util.java:152)
       at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.close(Http1xStream.java:619)
       at com.android.okhttp.okio.RealBufferedSource.close(RealBufferedSource.java:421)
       at com.android.okhttp.okio.RealBufferedSource$1.close(RealBufferedSource.java:409)
       at com.google.android.gms.internal.firebase_messaging.zzk.zza(com.google.firebase:firebase-messaging@@20.0.0:4)
       at com.google.firebase.messaging.zzj.close(com.google.firebase:firebase-messaging@@20.0.0:38)
       at com.google.firebase.messaging.zzd.zza(com.google.firebase:firebase-messaging@@20.0.0:51)
       at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.0.0:60)
       at com.google.firebase.messaging.zze.run(com.google.firebase:firebase-messaging@@20.0.0:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at com.google.android.gms.common.util.concurrent.zza.run(:6)
       at java.lang.Thread.run(Thread.java:764)`

**Comment by samtstern** [comment]
Hey all, this has been fixed in the `firebase-messaging` SDK version `20.1.0` which was released recently, you can find the release notes here:
https://firebase.google.com/support/release-notes/android#messaging_v20-1-0

Thank you all for reporting and for your patience waiting for the fix!  If you upgrade to the new SDK and still see this crash, please file a new issue on this GitHub repo.
