### ISSUE TITLE
Firebase auth sdk -  Attempt to invoke virtual method 'int android.view.View.getVisibility()'

### ISSUE THREAD

**Issue by jerrymani33** [firebase/firebase-android-sdk#1055]
### Project setting
minSdkVersion 22
targetSdkVersion 29

###  Environment
 Android Studio 3.5.2
Build #AI-191.8026.42.35.5977832, built on October 31, 2019
JRE: 1.8.0_202-release-1483-b49-5587405 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.3.0-25-generic

  * Firebase Component: Firebase auth
  * Component version: 'com.google.firebase:firebase-auth:17.0.0'

**Logcat:**

2019-12-13 22:01:56.876 11385-11385/com.shady.book D/LoginFragment: onActivityResult() called with: requestCode = [12], resultCode = [-1], data = [Intent { (has extras) }]
2019-12-13 22:01:56.901 11385-11385/com.shady.book D/LoginFragment: face before call signin .........................
2019-12-13 22:01:56.919 11385-11385/com.shady.book W/BiChannelGoogleApi: [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzak@b0c0ee5
2019-12-13 22:01:56.922 11385-11385/com.shady.book D/ViewRootImpl@f90f4b3[InitialActivity]: stopped(false) old=false
2019-12-13 22:01:56.923 11385-11537/com.shady.book V/FA: Activity resumed, time: 32002430
2019-12-13 22:01:56.928 11385-11385/com.shady.book D/ViewRootImpl@f90f4b3[InitialActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
2019-12-13 22:01:56.929 11385-11385/com.shady.book D/InputMethodManager: prepareNavigationBarInfo() DecorView@17932d1[InitialActivity]
2019-12-13 22:01:56.929 11385-11385/com.shady.book D/InputMethodManager: getNavigationBarColor() -855310
2019-12-13 22:01:56.944 11385-11385/com.shady.book D/InputMethodManager: prepareNavigationBarInfo() DecorView@17932d1[InitialActivity]
2019-12-13 22:01:56.944 11385-11385/com.shady.book D/InputMethodManager: getNavigationBarColor() -855310
2019-12-13 22:01:56.944 11385-11385/com.shady.book V/InputMethodManager: Starting input: tba=com.shady.book ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
2019-12-13 22:01:56.944 11385-11385/com.shady.book D/InputMethodManager: startInputInner - Id : 0
2019-12-13 22:01:56.945 11385-11385/com.shady.book I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
2019-12-13 22:01:56.951 11385-11385/com.shady.book D/InputTransport: Input channel constructed: fd=111
2019-12-13 22:01:56.951 11385-11385/com.shady.book D/InputTransport: Input channel destroyed: fd=109
2019-12-13 22:01:56.952 11385-11385/com.shady.book D/ViewRootImpl@e6fca03[SignInHubActivity]: MSG_WINDOW_FOCUS_CHANGED 0 1
2019-12-13 22:01:56.952 11385-11385/com.shady.book D/InputMethodManager: prepareNavigationBarInfo() DecorView@228d17c[SignInHubActivity]
2019-12-13 22:01:56.952 11385-11385/com.shady.book D/InputMethodManager: getNavigationBarColor() -855310
2019-12-13 22:01:56.970 11385-11385/com.shady.book D/ViewRootImpl@e6fca03[SignInHubActivity]: stopped(true) old=false
2019-12-13 22:01:56.986 11385-11396/com.shady.book I/tricks.engaare: Background concurrent copying GC freed 22118(1485KB) AllocSpace objects, 19(888KB) LOS objects, 50% free, 4MB/8MB, paused 379us total 105.066ms
2019-12-13 22:01:56.992 11385-11537/com.shady.book D/FA: Logging event (FE): screen_view(_vs), Bundle[{ga_event_origin(_o)=auto, ga_previous_class(_pc)=SignInHubActivity, ga_previous_id(_pi)=-2744483265182652898, ga_screen_class(_sc)=InitialActivity, ga_screen_id(_si)=-2744483265182652900}]
2019-12-13 22:01:57.007 11385-11670/com.shady.book W/libEGL: EGLNativeWindowType 0xd00c1008 disconnect failed
2019-12-13 22:01:57.007 11385-11670/com.shady.book D/OpenGLRenderer: eglDestroySurface = 0xcf7ce8a0, 0xd00c1000
2019-12-13 22:01:57.007 11385-11385/com.shady.book D/ViewRootImpl@e6fca03[SignInHubActivity]: dispatchDetachedFromWindow
2019-12-13 22:01:57.024 11385-11385/com.shady.book D/InputTransport: Input channel destroyed: fd=106

> 2019-12-13 22:01:57.109 11385-11385/com.shady.book W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference
> 2019-12-13 22:01:57.110 11385-11385/com.shady.book W/System.err:     at android.view.ViewRootImpl.getHostVisibility(ViewRootImpl.java:1809)
> 2019-12-13 22:01:57.110 11385-11385/com.shady.book W/System.err:     at android.view.ViewRootImpl.handleAppVisibility(ViewRootImpl.java:1445)
> 2019-12-13 22:01:57.110 11385-11385/com.shady.book W/System.err:     at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4843)
> 2019-12-13 22:01:57.110 11385-11385/com.shady.book W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
> 2019-12-13 22:01:57.110 11385-11385/com.shady.book W/System.err:     at android.os.Looper.loop(Looper.java:214)
> 2019-12-13 22:01:57.110 11385-11385/com.shady.book W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7091)
> 2019-12-13 22:01:57.110 11385-11385/com.shady.book W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
> 2019-12-13 22:01:57.110 11385-11385/com.shady.book W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
> 2019-12-13 22:01:57.110 11385-11385/com.shady.book W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
> 

2019-12-13 22:01:58.081 11385-11398/com.shady.book D/FirebaseAuth: Notifying id token listeners about user ( DXqDi7CnMGTyeaBQmHK2VdHGhT72 ).
2019-12-13 22:01:58.082 11385-11398/com.shady.book D/FirebaseAuth: Notifying auth state listeners about user ( DXqDi7CnMGTyeaBQmHK2VdHGhT72 ).
2019-12-13 22:01:58.092 11385-11385/com.shady.book D/LoginFragment: face before on complete callback signin .........................

**Comment by aguatno** [comment]
Hi @jerrymani33 thank you for reporting the issue. Unfortunately, I'm not able to decipher what is going on. We need more information to debug this issue:

- How easy is it to reproduce this issue? Could you provide steps to replicate or reproduction sample?
- Is it device or OS specific?
- Frequency with which you are able to reproduce the issue (e.g. 3/5 times)
- Are there any specific steps that trigger the exception?

Also, I noticed that you're using an older SDK version of Firebase Auth. Could you try to update it to the latest version (19.2.0) and see if the issue persists? Thanks

**Comment by jerrymani33** [comment]
Hi @aguatno ,

Thank you for your response.

Now I'm on 19.2.0 I'm still getting the same issue and I get this issue on Samsung A10 version 9 pie.
Its easily reproduced on this particular device. I tried the same app with other devices and emulator its does not give the error.

**Comment by aguatno** [comment]
Hi @jerrymani33 could you let us know what steps you did to reproduce the log? If possible, please provide a minimal runnable code so we can easily replicate the issue. Thanks
