### ISSUE TITLE
[Firebase Cloud Messaging] Notification not received when app is killed with multiple Firebase projects

### ISSUE THREAD

**Issue by dabo248** [firebase/firebase-android-sdk#1059]
### Describe your environment

  * Android Studio version: 3.5.3
  * Firebase Component: FCM
  * Component version: 20.1.0

### Describe the problem

I have followed [this](https://firebase.google.com/docs/projects/multiprojects#support_multiple_environments_in_your_android_application) documentation and use multiple Firebase projects which are dynamically switched on login. As a result, I had to remove the google-services plugin and the google-services.json and set the configuration programmatically with FirebaseApp.initializeApp. Everything works great so far, but when the app is killed completely and receives a notification, there is an error and the notification is not received:

```
E/AndroidRuntime: FATAL EXCEPTION: Firebase-NotificationMessageHandler
    Process: com.example.app, PID: 8005
    java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.example.app. Make sure to call FirebaseApp.initializeApp(Context) first.
        at com.google.firebase.FirebaseApp.getInstance(com.google.firebase:firebase-common@@19.3.0:184)
        at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.0:120)
        at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.0:1)
        at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.1.0:50)
        at com.google.firebase.messaging.zze.run(com.google.firebase:firebase-messaging@@20.1.0:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
        at java.lang.Thread.run(Thread.java:764)
```

In all other situations I receive the notifications accordingly. With the google-services plugin and the google-services.json I can receive messages by FCM even when the app is killed, but that's not an option, because I can't switch Firebase projects dynamically using the google-services plugin.

I always initialize the FirebaseApp as the default app: FirebaseApp.initializeApp(context, configuration)

Any hints on how to solve this?

#### Steps to reproduce:

Setup an Android application supporting multiple Firebase projects without the `google-services` plugin like it is described [here](https://firebase.google.com/docs/projects/multiprojects#support_multiple_environments_in_your_android_application). Initialize one of these Firebase projects as the default app using `FirebaseApp.initializeApp(context, configuration)`, kill the app (swiping it away) or restart your device, send a notification through FCM and see the app crash.

**Comment by dabo248** [comment]
Using `data messages` instead of `notification messages` fixed the issue. I can now dynamically switch Firebase projects and receive notifications, even when the app was killed / closed.
