### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.google.firebase.database.snapshot.ChildKey.isPriorityChildName()' on a null object reference

### ISSUE THREAD

**Issue by ckilee** [firebase/firebase-android-sdk#1078]
I'm having a big problem with my app when trying to use realtime database, follows stacktrace:

2019-12-22 10:52:02.026 617-1508/apps.br.intelitempos E/NoopPersistenceManager: Caught Throwable.
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.google.firebase.database.snapshot.ChildKey.isPriorityChildName()' on a null object reference
        at com.google.firebase.database.snapshot.ChildrenNode.getImmediateChild(com.google.firebase:firebase-database@@19.2.0:234)
        at com.google.firebase.database.snapshot.ChildrenNode.hasChild(com.google.firebase:firebase-database@@19.2.0:95)
        at com.google.firebase.database.core.view.CacheNode.isCompleteForChild(com.google.firebase:firebase-database@@19.2.0:65)
        at com.google.firebase.database.core.view.ViewProcessor.cacheHasChild(com.google.firebase:firebase-database@@19.2.0:408)
        at com.google.firebase.database.core.view.ViewProcessor.applyUserMerge(com.google.firebase:firebase-database@@19.2.0:428)
        at com.google.firebase.database.core.view.ViewProcessor.applyOperation(com.google.firebase:firebase-database@@19.2.0:104)
        at com.google.firebase.database.core.view.View.applyOperation(com.google.firebase:firebase-database@@19.2.0:169)
        at com.google.firebase.database.core.SyncPoint.applyOperationToView(com.google.firebase:firebase-database@@19.2.0:76)
        at com.google.firebase.database.core.SyncPoint.applyOperation(com.google.firebase:firebase-database@@19.2.0:107)
        at com.google.firebase.database.core.SyncTree.applyOperationDescendantsHelper(com.google.firebase:firebase-database@@19.2.0:966)
        at com.google.firebase.database.core.SyncTree.applyOperationHelper(com.google.firebase:firebase-database@@19.2.0:897)
        at com.google.firebase.database.core.SyncTree.applyOperationHelper(com.google.firebase:firebase-database@@19.2.0:916)
        at com.google.firebase.database.core.SyncTree.applyOperationToSyncPoints(com.google.firebase:firebase-database@@19.2.0:883)
        at com.google.firebase.database.core.SyncTree.access$400(com.google.firebase:firebase-database@@19.2.0:76)
        at com.google.firebase.database.core.SyncTree$2.call(com.google.firebase:firebase-database@@19.2.0:222)
        at com.google.firebase.database.core.SyncTree$2.call(com.google.firebase:firebase-database@@19.2.0:214)
        at com.google.firebase.database.core.persistence.NoopPersistenceManager.runInTransaction(com.google.firebase:firebase-database@@19.2.0:126)
        at com.google.firebase.database.core.SyncTree.applyUserMerge(com.google.firebase:firebase-database@@19.2.0:213)
        at com.google.firebase.database.core.Repo.updateChildren(com.google.firebase:firebase-database@@19.2.0:487)
        at com.google.firebase.database.DatabaseReference$3.run(com.google.firebase:firebase-database@@19.2.0:422)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
2019-12-22 10:52:02.035 617-1508/apps.br.intelitempos E/RunLoop: Uncaught exception in Firebase Database runloop (19.2.0). If you are not already on the latest version of the Firebase SDKs, try updating your dependencies. Should this problem persist, please file a report at https://github.com/firebase/firebase-android-sdk
    java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.google.firebase.database.snapshot.ChildKey.isPriorityChildName()' on a null object reference
        at com.google.firebase.database.core.persistence.NoopPersistenceManager.runInTransaction(com.google.firebase:firebase-database@@19.2.0:131)
        at com.google.firebase.database.core.SyncTree.applyUserMerge(com.google.firebase:firebase-database@@19.2.0:213)
        at com.google.firebase.database.core.Repo.updateChildren(com.google.firebase:firebase-database@@19.2.0:487)
        at com.google.firebase.database.DatabaseReference$3.run(com.google.firebase:firebase-database@@19.2.0:422)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.google.firebase.database.snapshot.ChildKey.isPriorityChildName()' on a null object reference
        at com.google.firebase.database.snapshot.ChildrenNode.getImmediateChild(com.google.firebase:firebase-database@@19.2.0:234)
        at com.google.firebase.database.snapshot.ChildrenNode.hasChild(com.google.firebase:firebase-database@@19.2.0:95)
        at com.google.firebase.database.core.view.CacheNode.isCompleteForChild(com.google.firebase:firebase-database@@19.2.0:65)
        at com.google.firebase.database.core.view.ViewProcessor.cacheHasChild(com.google.firebase:firebase-database@@19.2.0:408)
        at com.google.firebase.database.core.view.ViewProcessor.applyUserMerge(com.google.firebase:firebase-database@@19.2.0:428)
        at com.google.firebase.database.core.view.ViewProcessor.applyOperation(com.google.firebase:firebase-database@@19.2.0:104)
        at com.google.firebase.database.core.view.View.applyOperation(com.google.firebase:firebase-database@@19.2.0:169)
        at com.google.firebase.database.core.SyncPoint.applyOperationToView(com.google.firebase:firebase-database@@19.2.0:76)
        at com.google.firebase.database.core.SyncPoint.applyOperation(com.google.firebase:firebase-database@@19.2.0:107)
        at com.google.firebase.database.core.SyncTree.applyOperationDescendantsHelper(com.google.firebase:firebase-database@@19.2.0:966)
        at com.google.firebase.database.core.SyncTree.applyOperationHelper(com.google.firebase:firebase-database@@19.2.0:897)
        at com.google.firebase.database.core.SyncTree.applyOperationHelper(com.google.firebase:firebase-database@@19.2.0:916)
        at com.google.firebase.database.core.SyncTree.applyOperationToSyncPoints(com.google.firebase:firebase-database@@19.2.0:883)
        at com.google.firebase.database.core.SyncTree.access$400(com.google.firebase:firebase-database@@19.2.0:76)
        at com.google.firebase.database.core.SyncTree$2.call(com.google.firebase:firebase-database@@19.2.0:222)
        at com.google.firebase.database.core.SyncTree$2.call(com.google.firebase:firebase-database@@19.2.0:214)
        at com.google.firebase.database.core.persistence.NoopPersistenceManager.runInTransaction(com.google.firebase:firebase-database@@19.2.0:126)
        at com.google.firebase.database.core.SyncTree.applyUserMerge(com.google.firebase:firebase-database@@19.2.0:213) 
        at com.google.firebase.database.core.Repo.updateChildren(com.google.firebase:firebase-database@@19.2.0:487) 
        at com.google.firebase.database.DatabaseReference$3.run(com.google.firebase:firebase-database@@19.2.0:422) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
2019-12-22 10:52:02.039 617-617/apps.br.intelitempos D/AndroidRuntime: Shutting down VM
2019-12-22 10:52:02.048 617-617/apps.br.intelitempos E/AndroidRuntime: FATAL EXCEPTION: main
    Process: apps.br.intelitempos, PID: 617
    java.lang.RuntimeException: Uncaught exception in Firebase Database runloop (19.2.0). If you are not already on the latest version of the Firebase SDKs, try updating your dependencies. Should this problem persist, please file a report at https://github.com/firebase/firebase-android-sdk
        at com.google.firebase.database.android.AndroidPlatform$1$1.run(com.google.firebase:firebase-database@@19.2.0:96)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6647)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
     Caused by: java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.google.firebase.database.snapshot.ChildKey.isPriorityChildName()' on a null object reference
        at com.google.firebase.database.core.persistence.NoopPersistenceManager.runInTransaction(com.google.firebase:firebase-database@@19.2.0:131)
        at com.google.firebase.database.core.SyncTree.applyUserMerge(com.google.firebase:firebase-database@@19.2.0:213)
        at com.google.firebase.database.core.Repo.updateChildren(com.google.firebase:firebase-database@@19.2.0:487)
        at com.google.firebase.database.DatabaseReference$3.run(com.google.firebase:firebase-database@@19.2.0:422)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.google.firebase.database.snapshot.ChildKey.isPriorityChildName()' on a null object reference
        at com.google.firebase.database.snapshot.ChildrenNode.getImmediateChild(com.google.firebase:firebase-database@@19.2.0:234)
        at com.google.firebase.database.snapshot.ChildrenNode.hasChild(com.google.firebase:firebase-database@@19.2.0:95)
        at com.google.firebase.database.core.view.CacheNode.isCompleteForChild(com.google.firebase:firebase-database@@19.2.0:65)
        at com.google.firebase.database.core.view.ViewProcessor.cacheHasChild(com.google.firebase:firebase-database@@19.2.0:408)
        at com.google.firebase.database.core.view.ViewProcessor.applyUserMerge(com.google.firebase:firebase-database@@19.2.0:428)
        at com.google.firebase.database.core.view.ViewProcessor.applyOperation(com.google.firebase:firebase-database@@19.2.0:104)
        at com.google.firebase.database.core.view.View.applyOperation(com.google.firebase:firebase-database@@19.2.0:169)
        at com.google.firebase.database.core.SyncPoint.applyOperationToView(com.google.firebase:firebase-database@@19.2.0:76)
        at com.google.firebase.database.core.SyncPoint.applyOperation(com.google.firebase:firebase-database@@19.2.0:107)
        at com.google.firebase.database.core.SyncTree.applyOperationDescendantsHelper(com.google.firebase:firebase-database@@19.2.0:966)
        at com.google.firebase.database.core.SyncTree.applyOperationHelper(com.google.firebase:firebase-database@@19.2.0:897)
        at com.google.firebase.database.core.SyncTree.applyOperationHelper(com.google.firebase:firebase-database@@19.2.0:916)
        at com.google.firebase.database.core.SyncTree.applyOperationToSyncPoints(com.google.firebase:firebase-database@@19.2.0:883)
        at com.google.firebase.database.core.SyncTree.access$400(com.google.firebase:firebase-database@@19.2.0:76)
        at com.google.firebase.database.core.SyncTree$2.call(com.google.firebase:firebase-database@@19.2.0:222)
2019-12-22 10:52:02.049 617-617/apps.br.intelitempos E/AndroidRuntime:     at com.google.firebase.database.core.SyncTree$2.call(com.google.firebase:firebase-database@@19.2.0:214)
        at com.google.firebase.database.core.persistence.NoopPersistenceManager.runInTransaction(com.google.firebase:firebase-database@@19.2.0:126)
        	... 9 more

If you need details of my source code, please just let me know.

**Comment by ckilee** [comment]
As per information, my app is already in production with realtimedatabase, but sometimes, about 1 per mounth, I have a complete crash and everything stop to work, so I have to clean entire database and It starts to work again

**Comment by aguatno** [comment]
Hi @ckilee for us to check if the issue you encounter is intended or could be related to your implementation, could you send us a [simple repro](https://stackoverflow.com/help/minimal-reproducible-example) that we could run locally without any other third party API dependencies. Additionally, we'll be needing the following details:

- Detailed steps taken that led to the error encountered (screenshot(s) would be great)
- Any particular pattern you notice that significantly contributes to the issue

Any other relevant information. Thanks

**Comment by ckilee** [comment]
sure. It will take sometime to prepare this sample for you. 

As soon as I finish to prepare these details, I will reply back.

**Comment by ckilee** [comment]
Just to let you know, I'm working on the sample. It will take some more days to finish.

**Comment by schmidt-sebastian** [comment]
@ckilee Thank you!

**Comment by ckilee** [comment]
Hi, I've finished the sample. This is a piece of code with isolated realtime database implementation.

[SampleProject.zip](https://github.com/firebase/firebase-android-sdk/files/4008549/SampleProject.zip)


**Steps to Run localy:**
1 - generate a new google-services.json in firebase console with your debug key hash.
2 - Add google-services.json in app folder: app/google-services.json

**Sample Description:**
This sample only have 2 activities and 1 DialogFragment:
1 - MainActivity.kt
2 - CreateOrJoinTicTacToeGameDialogFragment.kt
2 - TicTacToeActivity.kt

**Main flow:** Run this app in 2 or 3 devices. When the app starts, clicks on "Play TicTacToe" : Suddenly will appear "searching for oponent" dialog fragment. Do the same in another device. RealTime database will match the game with two opponents, and them It will start the TicTacToeActivity game.

**Error Scenario:** In some cases. more or less once a month. The realtime database stops to works and always throwing the exception: java.lang.NullPointerException: Attempt to invoke virtual method. As described above. Only way to fix this is completely clean the realtime database. Them, It starts to works fine again. Debbugging the issue, I know the crash happens on line: 147 of CreateOrJoinTicTacToeGameDialogFragment.kt in valueEventListener method.
line: 147 - game = it.getValue<TicTacToeGame>(TicTacToeGame::class.java)


If you need any other information or any help with source code, please let me know. We appreciatte your help.

**Comment by schmidt-sebastian** [comment]
Thank you for your repro. I will look at this by the end of the week (sorry, we are having a short week here!)

**Comment by schmidt-sebastian** [comment]
@ckilee Thank you for your sample. I am able to use your app without problems (for now). If you are able to reproduce this, would you mind running app with logging enabled: `      FirebaseDatabase.getInstance().setLogLevel(Logger.Level.DEBUG)`

I will also try to reproduce this with logging enabled.

**Comment by ckilee** [comment]
Sure, I'll reproduce with DEBUG. More over I'm goign to clone this source code, so I can try to help.

**Comment by ckilee** [comment]
As per my debug: 
1 - The DatabaseReference updateChildren task calls: repo.updateChildren.

2 - This flows goes to: ViewProcessor.java (applyUserMerge). Where getFront() is returning null: **writePath.getFront()** is null

**ViewProcessor.java**
```
    427  Path writePath = path.child(entry.getKey());
    428  if (ViewProcessor.cacheHasChild(viewCache, writePath.getFront())) {
```

3 - Because you have null there, them, a nullpointer exception happens on line: 234 of ChildrenNode.java:

**ChildrenNode.java**
>     232 public Node getImmediateChild(ChildKey name) {
>     233 // Hack to treat priority as a regular child
>     234 if (name.isPriorityChildName() && !this.priority.isEmpty()) { <-nullpointer

4 - As I've seen, Path getFront() returns null when Path object doesn't have any ChildKey. 


I didn't figure out yet why path.getFront() is returning null. 
BTW, do you think We could have a nullpointer threatment in ChildrenNode.java line: 234?

**Comment by schmidt-sebastian** [comment]
When we get to the nullptr in ChildrenNode, we likely already lost data. Unfortunately, the only way I see that we can resolve this issue is to find out why `path` does not have any elements.

**Comment by ckilee** [comment]
Hi Sebastian,

Thx for your reply. I think I fixed this issue in my project by replacing:

from:
```
val childUpdates = HashMap<String,Any>()
childUpdates.put("/"+game.id+"/",game)
databaseRef.updateChildren(childUpdates)
```
to:
`databaseRef.child(game.id).setValue(game)`


I thinks this was not the best solution, BTW, Til now It's working. I know that this issues happens with updateChildren method. Thats why I replaced to: child(id).setValue(game) And this is working.
See:
https://play.google.com/store/apps/details?id=apps.br.intelitempos
Play 'sequence of 5' game made with realtime database.

**Comment by schmidt-sebastian** [comment]
I am glad that you managed to find a way to unblock your app. Let's keep this issue open, as we should still find a way to fix this in the SDK codebase itself.

**Comment by ckilee** [comment]
Thx! I agree with you. Whether you need any help with this issue, let me know!

**Comment by HarshBarash** [comment]
Has someone solved this problem? At the slightest contact with Firebase, it pops up.. It is solved by deleting the database and creating a new one, but this option only masks the problem.

**Comment by lehcar09** [comment]
Hi @ckilee, sorry for the silence here. I revisited this issue and tried reproducing it in the latest SDK version, however, I wasn't able to encounter the issue. Are you still encountering this issue?
