### ISSUE TITLE
E/RunLoop: Uncaught exception in Firebase Database runloop (3.0.0)

### ISSUE THREAD

**Issue by rommansabbir** [firebase/firebase-android-sdk#1086]
2019-12-30 19:15:21.627 13751-14440/package E/RunLoop: Uncaught exception in Firebase Database runloop (3.0.0). Please report to firebase-database-client@google.com
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/FirebaseApp$IdTokenListener;
        at com.google.firebase.database.android.AndroidPlatform.newAuthTokenProvider(com.google.firebase:firebase-database@@16.1.0:112)
        at com.google.firebase.database.core.Context.ensureAuthTokenProvider(com.google.firebase:firebase-database@@16.1.0:246)
        at com.google.firebase.database.core.Context.initServices(com.google.firebase:firebase-database@@16.1.0:98)
        at com.google.firebase.database.core.Context.freeze(com.google.firebase:firebase-database@@16.1.0:77)
        at com.google.firebase.database.core.RepoManager.createLocalRepo(com.google.firebase:firebase-database@@16.1.0:92)
        at com.google.firebase.database.core.RepoManager.createRepo(com.google.firebase:firebase-database@@16.1.0:42)
        at com.google.firebase.database.FirebaseDatabase.ensureRepo(com.google.firebase:firebase-database@@16.1.0:357)
        at com.google.firebase.database.FirebaseDatabase.getReference(com.google.firebase:firebase-database@@16.1.0:188)
        at package.core.di.FirebaseModule.provideDatabaseReference$app_userDebug(FirebaseModule.kt:38)
        at package.core.di.FirebaseModule_ProvideDatabaseReference$app_userDebugFactory.provideDatabaseReference$app_userDebug(FirebaseModule_ProvideDatabaseReference$app_userDebugFactory.java:34)
        at package.core.di.FirebaseModule_ProvideDatabaseReference$app_userDebugFactory.get(FirebaseModule_ProvideDatabaseReference$app_userDebugFactory.java:25)
        at package.core.di.FirebaseModule_ProvideDatabaseReference$app_userDebugFactory.get(FirebaseModule_ProvideDatabaseReference$app_userDebugFactory.java:8)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at package.core.di.FirebaseModule_ProvideShieldObseverRepository$app_userDebugFactory.get(FirebaseModule_ProvideShieldObseverRepository$app_userDebugFactory.java:35)
        at package.core.di.FirebaseModule_ProvideShieldObseverRepository$app_userDebugFactory.get(FirebaseModule_ProvideShieldObseverRepository$app_userDebugFactory.java:10)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at package.features.home.ui.HomeViewModel_Factory.get(HomeViewModel_Factory.java:59)
        at package.features.home.ui.HomeViewModel_Factory.get(HomeViewModel_Factory.java:15)
        at package.core.di.viewmodel.ViewModelFactory.create(ViewModelFactory.kt:23)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:164)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:130)
        at package.features.home.ui.BaseHomeFragment.onCreate(BaseHomeFragment.kt:130)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2586)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:838)
        at androidx.fragment.app.FragmentManagerImpl.addAddedFragments(FragmentManagerImpl.java:2100)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1874)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1830)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2663)
        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2624)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:904)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
    	at androidx.fragment.app.FragmentManagerImpl.dispatchActi
2019-12-30 19:15:22.045 13751-13751/package E/AndroidRuntime: FATAL EXCEPTION: main
    Process: package, PID: 13751
    java.lang.RuntimeException: Uncaught exception in Firebase Database runloop (3.0.0). Please report to firebase-database-client@google.com
        at com.google.firebase.database.android.AndroidPlatform$1$1.run(com.google.firebase:firebase-database@@16.1.0:98)
        at android.os.Handler.handleCallback(Handler.java:874)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:198)
        at android.app.ActivityThread.main(ActivityThread.java:6729)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/FirebaseApp$IdTokenListener;
        at com.google.firebase.database.android.AndroidPlatform.newAuthTokenProvider(com.google.firebase:firebase-database@@16.1.0:112)
        at com.google.firebase.database.core.Context.ensureAuthTokenProvider(com.google.firebase:firebase-database@@16.1.0:246)
        at com.google.firebase.database.core.Context.initServices(com.google.firebase:firebase-database@@16.1.0:98)
        at com.google.firebase.database.core.Context.freeze(com.google.firebase:firebase-database@@16.1.0:77)
        at com.google.firebase.database.core.RepoManager.createLocalRepo(com.google.firebase:firebase-database@@16.1.0:92)
        at com.google.firebase.database.core.RepoManager.createRepo(com.google.firebase:firebase-database@@16.1.0:42)
        at com.google.firebase.database.FirebaseDatabase.ensureRepo(com.google.firebase:firebase-database@@16.1.0:357)
        at com.google.firebase.database.FirebaseDatabase.getReference(com.google.firebase:firebase-database@@16.1.0:188)
        at package.core.di.FirebaseModule.provideDatabaseReference$app_userDebug(FirebaseModule.kt:38)
        at package.core.di.FirebaseModule_ProvideDatabaseReference$app_userDebugFactory.provideDatabaseReference$app_userDebug(FirebaseModule_ProvideDatabaseReference$app_userDebugFactory.java:34)
        at package.core.di.FirebaseModule_ProvideDatabaseReference$app_userDebugFactory.get(FirebaseModule_ProvideDatabaseReference$app_userDebugFactory.java:25)
        at package.core.di.FirebaseModule_ProvideDatabaseReference$app_userDebugFactory.get(FirebaseModule_ProvideDatabaseReference$app_userDebugFactory.java:8)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at package.core.di.FirebaseModule_ProvideShieldObseverRepository$app_userDebugFactory.get(FirebaseModule_ProvideShieldObseverRepository$app_userDebugFactory.java:35)
        at package.core.di.FirebaseModule_ProvideShieldObseverRepository$app_userDebugFactory.get(FirebaseModule_ProvideShieldObseverRepository$app_userDebugFactory.java:10)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at package.features.home.ui.HomeViewModel_Factory.get(HomeViewModel_Factory.java:59)
        at package.features.home.ui.HomeViewModel_Factory.get(HomeViewModel_Factory.java:15)
        at package.core.di.viewmodel.ViewModelFactory.create(ViewModelFactory.kt:23)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:164)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:130)
        at package.features.home.ui.BaseHomeFragment.onCreate(BaseHomeFragment.kt:130)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2586)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:838)
        at androidx.fragment.app.FragmentManagerImpl.addAddedFragments(FragmentManagerImpl.java:2100)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1874)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1830)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
2019-12-30 19:15:22.056 13751-13751/package E/AndroidRuntime:     at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2663)
        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2624)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:904)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:246)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:542)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
        at package.features.home.ui.HomeActivity.onStart(HomeActivity.kt:146)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1392)
        at android.app.Activity.performStart(Activity.java:7157)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2952)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1823)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        	... 5 more
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.FirebaseApp$IdTokenListener" on path: DexPathList[[zip file "/data/app/package-OqUemc6wKy-rbCtyt--RWw==/base.apk"],nativeLibraryDirectories=[/data/app/package-OqUemc6wKy-rbCtyt--RWw==/lib/arm64, /data/app/package-OqUemc6wKy-rbCtyt--RWw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 54 more

**Comment by schmidt-sebastian** [comment]
@rommansabbir Thanks for filing this! This is caused by using an incompatible version of Firebase Auth and the Firebase Realtime Database SDK. Please update your dependency of Firebase Auth and Firebase Database to the latest version.
