### ISSUE TITLE
SQLiteBlobTooBigException

### ISSUE THREAD

**Issue by kimyow** [firebase/firebase-android-sdk#1090]
### [READ] Step 1: Are you in the right place?

Yes, This is about firestore related method's access to SQLite Database.

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 3.4.1
  * Firebase Component: 
    implementation 'com.google.firebase:firebase-auth:19.0.0'
    implementation 'com.google.firebase:firebase-firestore:21.1.1'
    implementation 'com.google.firebase:firebase-storage:19.0.1'
    implementation 'com.google.firebase:firebase-messaging:20.0.0'
    implementation 'com.google.firebase:firebase-core:17.2.0'
    implementation 'com.google.firebase:firebase-analytics:17.2.0'
    implementation 'com.google.firebase:firebase-ads:18.2.0'

    // Firebase UI
    implementation 'com.firebaseui:firebase-ui-firestore:4.2.1'
    implementation 'com.firebaseui:firebase-ui-storage:4.2.1'

  * com.android.tools.build:gradle:3.4.1
    com.google.gms:google-services:4.2.0
    compileSdkVersion 28
    buildToolsVersion '28.0.3'

#### Steps to reproduce:
I got below error on Android vitals on Play store running on Android 9. I got more than 300 crashes in the last 7 days.

#### Relevant Code:
Crashlytics Stack Trace
```
Fatal Exception: java.lang.RuntimeException: Internal error in Cloud Firestore (21.1.1).
       at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$3(com.google.firebase:firebase-firestore@@21.1.1:529)
       at com.google.firebase.firestore.util.AsyncQueue$$Lambda$3.run(:2)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6853)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)

Caused by android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=51939, totalRows=45651
       at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:862)
       at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:974)
       at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
       at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:157)
       at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:128)
       at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:237)
       at android.database.AbstractCursor.moveToNext(AbstractCursor.java:269)
       at com.google.firebase.firestore.local.SQLitePersistence$Query.forEach(com.google.firebase:firebase-firestore@@21.1.1:483)
       at com.google.firebase.firestore.local.SQLiteLruReferenceDelegate.removeOrphanedDocuments(com.google.firebase:firebase-firestore@@21.1.1:155)
       at com.google.firebase.firestore.local.LruGarbageCollector.removeOrphanedDocuments(com.google.firebase:firebase-firestore@@21.1.1:226)
       at com.google.firebase.firestore.local.LruGarbageCollector.runGarbageCollection(com.google.firebase:firebase-firestore@@21.1.1:270)
       at com.google.firebase.firestore.local.LruGarbageCollector.collect(com.google.firebase:firebase-firestore@@21.1.1:245)
       at com.google.firebase.firestore.local.LocalStore.lambda$collectGarbage$9(com.google.firebase:firebase-firestore@@21.1.1:670)
       at com.google.firebase.firestore.local.LocalStore$$Lambda$10.get(:4)
       at com.google.firebase.firestore.local.SQLitePersistence.runTransaction(com.google.firebase:firebase-firestore@@21.1.1:229)
       at com.google.firebase.firestore.local.LocalStore.collectGarbage(com.google.firebase:firebase-firestore@@21.1.1:670)
       at com.google.firebase.firestore.local.LruGarbageCollector$Scheduler.lambda$scheduleGC$0(com.google.firebase:firebase-firestore@@21.1.1:144)
       at com.google.firebase.firestore.local.LruGarbageCollector$Scheduler$$Lambda$1.run(:2)
       at com.google.firebase.firestore.util.AsyncQueue$DelayedTask.handleDelayElapsed(com.google.firebase:firebase-firestore@@21.1.1:134)
       at com.google.firebase.firestore.util.AsyncQueue$DelayedTask.access$lambda$0()
       at com.google.firebase.firestore.util.AsyncQueue$DelayedTask$$Lambda$1.run(:2)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(com.google.firebase:firebase-firestore@@21.1.1:224)
       at java.lang.Thread.run(Thread.java:764)
```

**Comment by wu-hui** [comment]
Hi kimyow,

This might be a know issue: #706. It is fixed in 21.2.0. Can you try to upgrade to newer Firestore version to see if the problem persist? 

Thanks
