### ISSUE TITLE
java.lang.NullPointerException: Attempt to read from field 'int com.android.okio.Segment.limit' on a null object reference

### ISSUE THREAD

**Issue by jgerdoganakgun** [firebase/firebase-android-sdk#1093]
Firebase messaging 20.0.0

We encountered this exception in the past. It was solved and did not occur for a long time but started to happen again in the last 4 days.

`Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'int com.android.okhttp.okio.Segment.limit' on a null object reference
       at com.android.okhttp.okio.Buffer.write(Buffer.java:1182)
       at com.android.okhttp.okio.Buffer.read(Buffer.java:1221)
       at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:65)
       at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:592)
       at com.android.okhttp.internal.Util.skipAll(Util.java:170)
       at com.android.okhttp.internal.Util.discard(Util.java:152)
       at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.close(Http1xStream.java:609)
       at com.android.okhttp.okio.RealBufferedSource.close(RealBufferedSource.java:421)
       at com.android.okhttp.okio.RealBufferedSource$1.close(RealBufferedSource.java:409)
       at com.google.android.gms.internal.firebase_messaging.zzk.zza(com.google.firebase:firebase-messaging@@20.0.0:4)
       at com.google.firebase.messaging.zzj.close(com.google.firebase:firebase-messaging@@20.0.0:38)
       at com.google.firebase.messaging.zzd.zza(com.google.firebase:firebase-messaging@@20.0.0:51)
       at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.0.0:60)
       at com.google.firebase.messaging.zze.run(com.google.firebase:firebase-messaging@@20.0.0:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at com.google.android.gms.common.util.concurrent.zza.run(:6)
       at java.lang.Thread.run(Thread.java:764)`

**Comment by aguatno** [comment]
Hi @sulemankhan44, thank you for taking time on filing this issue. I tried to reproduce, but wasn't able to replicate it. Could you provide a simple repro that we run locally & detailed steps to recreate this?

You may also considering using the latest version (20.1.0).
