### ISSUE TITLE
IncompatibleClassChangeError crash in Samsung devices with Android 5.x with firebase-config

### ISSUE THREAD

**Issue by gmerinojimenez** [firebase/firebase-android-sdk#1109]
### Describe your environment
  * Android Studio version: 3.5.1
  * Firebase Component: firebase-config
  * Component version: 16.5.0

### Describe the problem

We're receiving crashes related with reflection in Samsung devices with Android 5.X. 

The stacktrace is:
```
java.lang.IncompatibleClassChangeError: Couldn't find com.google.android.gms.internal.firebase_remote_config.zzcc.value
        at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:659)
        at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:641)
        at libcore.reflect.AnnotationAccess.getDeclaredAnnotation(AnnotationAccess.java:170)
        at java.lang.reflect.Field.getAnnotation(Field.java:242)
        at com.google.android.gms.internal.firebase_remote_config.zzbz.zza(zzbz:23)
        at com.google.android.gms.internal.firebase_remote_config.zzbr.<init>(zzbr:31)
        at com.google.android.gms.internal.firebase_remote_config.zzbr.zza(zzbr:8)
        at com.google.android.gms.internal.firebase_remote_config.zzby.<init>(zzby:7)
        at com.google.android.gms.internal.firebase_remote_config.zzw.<init>(zzw:1)
        at com.google.android.gms.internal.firebase_remote_config.zzf.<init>(zzf:2)
        at com.google.android.gms.internal.firebase_remote_config.zzn.<init>(zzn:7)
        at com.google.android.gms.internal.firebase_remote_config.zzdb.<init>(zzdb:1)
        at com.google.android.gms.internal.firebase_remote_config.zzdc.<init>(zzdc:1)
        at com.google.android.gms.internal.firebase_remote_config.zzcz.zza(zzcz:2)
        at com.google.android.gms.internal.firebase_remote_config.zzeq.zzb(zzeq:37)
        at com.google.android.gms.internal.firebase_remote_config.zzeq.zza(zzeq:23)
        at com.google.android.gms.internal.firebase_remote_config.zzeq.zza(zzeq:164)
        at com.google.android.gms.internal.firebase_remote_config.zzet.then(SourceFile:-1)
        at com.google.android.gms.tasks.zzf.run(zzf:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
```

About STR, according to our breadcrumbs, there is not a pattern. The user just starts the app and receives the remote config. At that point the app crashes.

[Researching](https://github.com/google/gson/issues/726#issuecomment-156152772), looks like it's a bug happening on Samsung devices. But it is becoming a top crash for us, so we would like to find a way to fix it.

Thanks in advance.

**Comment by aguatno** [comment]
Hi @gmerinojimenez thanks for filling this issue. It appears that you're using an old SDK version. Could you try using the latest version (19.1.0) and see if the issue persists? Otherwise, please send a runnable example so I could identify why this issue occurs. Thanks!

**Comment by gmerinojimenez** [comment]
Hello @aguatno. We will update the SDK in the next release, but we're not able to reproduce the issue at the office, so waiting for a release to verify will be very slow.

About the runnable example, I can send to you our distributed APK, but I'm not sure if that is going to be helpful

**Comment by aguatno** [comment]
I tried to find similar issues internally, but to no avail. You may try updating your Firebase SDK to the latest version as they have the latest updates and bug fixes.
