### ISSUE TITLE
Android Firestore error

### ISSUE THREAD

**Issue by ArcherEmiya05** [firebase/firebase-android-sdk#1117]
```
Fatal Exception: java.lang.RuntimeException: Internal error in Cloud Firestore (21.3.1).
       at com.google.firebase.firestore.q0.e.b(com.google.firebase:firebase-firestore@@21.3.1:529)
       at com.google.firebase.firestore.q0.d.run(:2)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:224)
       at android.app.ActivityThread.main(ActivityThread.java:7520)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)



Caused by android.database.CursorWindowAllocationException: Could not allocate CursorWindow '/data/user/0/com.bitwise.manilaaidandsafetyapp/databases/firestore.%5BDEFAULT%5D.manila-aid-and-safety-app-52.%28default%29' of size 2097152 due to error -12.
       at android.database.CursorWindow.nativeCreate(CursorWindow.java)
       at android.database.CursorWindow.<init>(CursorWindow.java:139)
       at android.database.CursorWindow.<init>(CursorWindow.java:120)
       at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:202)
       at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:149)
       at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:142)
       at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:232)
       at android.database.AbstractCursor.moveToNext(AbstractCursor.java:287)
       at com.google.firebase.firestore.m0.m1$d.b(com.google.firebase:firebase-firestore@@21.3.1:458)
       at com.google.firebase.firestore.m0.y1.a(com.google.firebase:firebase-firestore@@21.3.1:113)
       at com.google.firebase.firestore.m0.t.a(com.google.firebase:firebase-firestore@@21.3.1:381)
       at com.google.firebase.firestore.m0.p.get(:6)
       at com.google.firebase.firestore.m0.m1.a(com.google.firebase:firebase-firestore@@21.3.1:204)
       at com.google.firebase.firestore.m0.t.a(com.google.firebase:firebase-firestore@@21.3.1:337)
       at com.google.firebase.firestore.l0.l0.a(com.google.firebase:firebase-firestore@@21.3.1:329)
       at com.google.firebase.firestore.l0.z.a(com.google.firebase:firebase-firestore@@21.3.1:311)
       at com.google.firebase.firestore.p0.e0.a(com.google.firebase:firebase-firestore@@21.3.1:546)
       at com.google.firebase.firestore.p0.e0.a(com.google.firebase:firebase-firestore@@21.3.1:459)
       at com.google.firebase.firestore.p0.e0.a(com.google.firebase:firebase-firestore@@21.3.1:53)
       at com.google.firebase.firestore.p0.e0$a.a(com.google.firebase:firebase-firestore@@21.3.1:176)
       at com.google.firebase.firestore.p0.l0.a(com.google.firebase:firebase-firestore@@21.3.1:108)
       at com.google.firebase.firestore.p0.l0.a(com.google.firebase:firebase-firestore@@21.3.1:38)
       at com.google.firebase.firestore.p0.b$c.a(com.google.firebase:firebase-firestore@@21.3.1:119)
       at com.google.firebase.firestore.p0.d.run(:4)
       at com.google.firebase.firestore.p0.b$a.a(com.google.firebase:firebase-firestore@@21.3.1:67)
       at com.google.firebase.firestore.p0.b$c.b(com.google.firebase:firebase-firestore@@21.3.1:110)
       at com.google.firebase.firestore.p0.p$a.a(com.google.firebase:firebase-firestore@@21.3.1:124)
       at f.b.a0.a(ForwardingClientCallListener.java:33)
       at f.b.a0.a(ForwardingClientCallListener.java:33)
       at f.b.n1.q$d$b.a(ClientCallImpl.java:563)
       at f.b.n1.y.run(ContextRunnable.java:37)
       at f.b.n1.a2.run(SerializingExecutor.java:123)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.firebase.firestore.q0.e$c$b.run(com.google.firebase:firebase-firestore@@21.3.1:224)
       at java.lang.Thread.run(Thread.java:919)

According to Crashlytics

Redmi K20 Pro
Android 10
```

**Comment by aguatno** [comment]
Hi @ArcherEmiya05 Please use the issue template when filing an issue so that we can help you solve your problem.  I am going to close this issue but feel free to file a new one with all of the required information
