### ISSUE TITLE
UntaggedSocketViolation in Strict Mode

### ISSUE THREAD

**Issue by iamMehedi** [firebase/firebase-android-sdk#1133]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 3.5.3
  * Firebase Component: Remote Config
  * Component version: 19.1.0
  * Android OS: 9

### [REQUIRED] Step 3: Describe the problem
Getting this exception in StrictMode:
```
StrictMode: StrictMode policy violation: android.os.strictmode.UntaggedSocketViolation: Untagged socket detected; use TrafficStats.setThreadSocketTag() to track all network usage
        at android.os.StrictMode.onUntaggedSocket(StrictMode.java:2023)
        at com.android.server.NetworkManagementSocketTagger.tag(NetworkManagementSocketTagger.java:82)
        at libcore.io.BlockGuardOs.tagSocket(BlockGuardOs.java:50)
        at libcore.io.BlockGuardOs.socket(BlockGuardOs.java:313)
        at libcore.io.IoBridge.socket(IoBridge.java:640)
        at java.net.PlainSocketImpl.socketCreate(PlainSocketImpl.java:124)
        at java.net.AbstractPlainSocketImpl.create(AbstractPlainSocketImpl.java:128)
        at java.net.Socket.createImpl(Socket.java:489)
        at java.net.Socket.getImpl(Socket.java:552)
        at java.net.Socket.setSoTimeout(Socket.java:1180)
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:139)
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:258)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:26)
        at com.google.firebase.remoteconfig.internal.ConfigFetchHttpClient.setFetchRequestBody(com.google.firebase:firebase-config@@19.0.4:321)
        at com.google.firebase.remoteconfig.internal.ConfigFetchHttpClient.fetch(com.google.firebase:firebase-config@@19.0.4:182)
        at com.google.firebase.remoteconfig.internal.ConfigFetchHandler.fetchFromBackend(com.google.firebase:firebase-config@@19.0.4:278)
        at com.google.firebase.remoteconfig.internal.ConfigFetchHandler.fetchFromBackendAndCacheResponse(com.google.firebase:firebase-config@@19.0.4:251)
        at com.google.firebase.remoteconfig.internal.ConfigFetchHandler.fetchIfCacheExpiredAndNotThrottled(com.google.firebase:firebase-config@@19.0.4:191)
        at com.google.firebase.remoteconfig.internal.ConfigFetchHandler.lambda$fetch$0(com.google.firebase:firebase-config@@19.0.4:160)
        at com.google.firebase.remoteconfig.internal.ConfigFetchHandler$$Lambda$1.then(Unknown Source:4)
        at com.google.android.gms.tasks.zzf.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```
This most probably is related to [this](https://github.com/square/okhttp/issues/3537) but some workaround would be nice for the time being.

**Comment by aguatno** [comment]
Hi @iamMehedi do you have any details about the pattern of this error exception? Does this happen only on a particular Android version, or particular set of devices?

In any case, if you're able to reproduce the issue or provide more info, please let us know and we will try to track down what's going on. Thanks!

**Comment by iamMehedi** [comment]
@aguatno I encountered this on a OnePlus 5t device, might be a OkHttp issue (I am not sure if Firebase uses okhttp internally).

**Comment by aguatno** [comment]
Based on our [release note](https://firebase.google.com/support/release-notes/android?hl=it#remote-config_v19-0-3) this issue should be resolved. I'm not sure why this is still occurring, let me take a look.

**Comment by iamMehedi** [comment]
Thanks @aguatno

**Comment by clp93** [comment]
Hey @iamMehedi, I suspect this might be an underlying OkHttp issue. We use whatever default transport library your device uses for `HttpUrlConnection`[1]

We also run our E2E tests with strict mode turned on to ensure we catch any issues with StrictMode violations in our SDK [2]


[1] https://osscs.corp.google.com/firebase/firebase-android-sdk/+/master:firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHttpClient.java;l=136-137;drc=09eaa70417d9e9ca9f4e2b899e106a7cde85a168

[2] https://osscs.corp.google.com/firebase/firebase-android-sdk/+/master:firebase-config/bandwagoner/src/main/java/com/googletest/firebase/remoteconfig/bandwagoner/MainApplication.java;l=37-51;drc=48f2e89e8354e7a08cb1dce2d2aa98d8af0fa214
