### ISSUE TITLE
FirebaseRemoteConfig.getInstance() crash  Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference

### ISSUE THREAD

**Issue by vashisthg** [firebase/firebase-android-sdk#1166]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Getting crashes on public releases that are build via CI. 
  * Firebase Component: Firebase config 
  * Component version:  18.0.0

### [REQUIRED] Step 3: Describe the problem
Getting NullPointerException at FirebaseRemoteConfig.getInstance() for some users

#### Steps to reproduce:

Got this exception in crash reporting for a few live users. 

#### Relevant Code:

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
       at java.util.Formatter$Flags.parse(Formatter.java:4546)
       at java.util.Formatter$FormatSpecifier.flags(Formatter.java:2729)
       at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2801)
       at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2624)
       at java.util.Formatter.parse(Formatter.java:2557)
       at java.util.Formatter.format(Formatter.java:2504)
       at java.util.Formatter.format(Formatter.java:2458)
       at java.lang.String.format(String.java:2842)
       at com.google.firebase.remoteconfig.RemoteConfigComponent.zza(RemoteConfigComponent.java:45)
       at com.google.firebase.remoteconfig.RemoteConfigComponent.zzd(RemoteConfigComponent.java:43)
       at com.google.firebase.remoteconfig.RemoteConfigComponent.get(RemoteConfigComponent.java:18)
       at com.google.firebase.remoteconfig.FirebaseRemoteConfig.getInstance(FirebaseRemoteConfig.java:3)
       at com.google.firebase.remoteconfig.FirebaseRemoteConfig.getInstance(FirebaseRemoteConfig.java:1)
     
...

```
Looked into https://github.com/firebase/firebase-android-sdk/issues/976 but the crash log didn't  mention String.format so creating a new bug report.

**Comment by aguatno** [comment]
Hi @vashisthg thanks for filling this issue. I haven't seen this error before, let's isolate if this is a coding issue or bug with the Firebase SDKs. Could you provide the following information so that I can have a clearer view of your issue:

- Changes you've made before the issue occurred (if there's any)
- Detailed or step by step instructions to reproduce the issue
- A [minimal repro](https://stackoverflow.com/help/minimal-reproducible-example) that I can replicate on my end
- Any other relevant information

Also make sure to use the latest version of the Firebase SDK to have the latest updates and bug fixes.
