### ISSUE TITLE
Firebase messaging 20.1.0 Causes crash in RxBLE library

### ISSUE THREAD

**Issue by Doophie** [firebase/firebase-android-sdk#1242]
I've explained the problem in detail [here](https://stackoverflow.com/questions/60210651/updating-firebase-causes-rxble-crash).

And here is a repo where the issue can easily be reproduced: https://github.com/Doophie/TestAppCrash

Note that in the first commit on that repo the crash occurs (it uses firebase messaging 20.1.0) and in the second commit, where all i did was rollback to firebase messaging 20.0.0 the crash does not occur.

Here is what the crash log looks like:
```
2020-02-13 09:44:57.530 20760-20760/my.package.name E/AndroidRuntime: FATAL EXCEPTION: main
    Process: my.package.name, PID: 20760
    java.lang.NoSuchMethodError: No static method injectMembers(Ldagger/MembersInjector;Ljava/lang/Object;)Ljava/lang/Object; in class Ldagger/internal/MembersInjectors; or its super classes (declaration of 'dagger.internal.MembersInjectors' appears in /data/app/my.package.name-Nbmle9woVCiX-2v0teYwZw==/base.apk!classes3.dex)
        at com.polidea.rxandroidble.RxBleAdapterStateObservable_Factory.get(RxBleAdapterStateObservable_Factory.java:28)
        at com.polidea.rxandroidble.RxBleAdapterStateObservable_Factory.get(RxBleAdapterStateObservable_Factory.java:10)
        at com.polidea.rxandroidble.RxBleClientImpl_Factory.get(RxBleClientImpl_Factory.java:104)
        at com.polidea.rxandroidble.RxBleClientImpl_Factory.get(RxBleClientImpl_Factory.java:23)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.polidea.rxandroidble.DaggerClientComponent.rxBleClient(DaggerClientComponent.java:419)
        at com.polidea.rxandroidble.RxBleClient.create(RxBleClient.java:54)
        at my.package.name.Comm.RxBLEComm.<init>(RxBLEComm.java:109)  // These are the only
        at my.package.name.Comm.RxBLEComm.init(RxBLEComm.java:118)    // lines in my code which
        at my.package.name.RootApp.onCreate(RootApp.kt:63)            // are totally unrealted to firebase
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1155)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5928)
        at android.app.ActivityThread.access$1100(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6735)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2020-02-13 09:44:57.586 2989-3111/? E/NetworkController.MobileSignalController(2): showVoteIcon=false
```

**Comment by aguatno** [comment]
Hi @Doophie thanks for providing the mcve. I'm going to run the sample app, and I'll immediately let you know as soon as I get an update.

**Comment by aguatno** [comment]
Sorry for the delay. I was able to reproduce the issue. Let me consult this to the team. I'll get back to you once I got an update.

**Comment by aguatno** [comment]
Hi @Doophie it seems the you're using an old version of rxandroidble, have you tried using the latest vesion one(1.7.1), and see if the issue persists?

**Comment by Doophie** [comment]
@aguatno Looks like you're correct, updating the rxandroidble solves the issue

**Comment by aguatno** [comment]
Thank you and we shall now consider this request as resolved.

I am closing this issue for now. If you want to continue the discussion just leave a comment here and we are happy to re-open this.
