### ISSUE TITLE
FirebaseFirestore.getInstance() crashes on firebase-firestore:17.1.1+ due to a NullPointerException on FirebaseAuth

### ISSUE THREAD

**Issue by red42** [firebase/firebase-android-sdk#129]
* Android Studio version: 3.2.1
  * Firebase Component: Firestore
  * Component version: com.google.firebase:firebase-firestore:17.1.1+ (17.1.0 works)

FirebaseFirestore.getInstance() crashes when using firebase-firestore 17.1.1 or higher. It happens as my initial Activity starts:
```
protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        firestore = FirebaseFirestore.getInstance();
        //...
```

This is the stack trace:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: <REDACTED>, PID: 17358
    java.lang.RuntimeException: Unable to start activity ComponentInfo{<REDACTED>/<REDACTED>.HomeActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.firebase.auth.internal.zzab.zzf(int)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2340)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2402)
        at android.app.ActivityThread.access$900(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1318)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5271)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.firebase.auth.internal.zzab.zzf(int)' on a null object reference
        at com.google.firebase.auth.FirebaseAuth.addIdTokenListener(Unknown Source)
        at com.google.firebase.firestore.auth.FirebaseAuthCredentialsProvider.<init>(com.google.firebase:firebase-firestore@@17.1.3:76)
        at com.google.firebase.firestore.FirebaseFirestore.newInstance(com.google.firebase:firebase-firestore@@17.1.3:109)
        at com.google.firebase.firestore.FirestoreMultiDbComponent.get(com.google.firebase:firebase-firestore@@17.1.3:51)
        at com.google.firebase.firestore.FirebaseFirestore.getInstance(com.google.firebase:firebase-firestore@@17.1.3:87)
        at com.google.firebase.firestore.FirebaseFirestore.getInstance(com.google.firebase:firebase-firestore@@17.1.3:72)
        at <REDACTED>.LoggedInActivity.onCreate(LoggedInActivity.java:78)
        at <REDACTED>.HomeActivity.onCreate(HomeActivity.java:51)
        at android.app.Activity.performCreate(Activity.java:5990)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2293)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2402) 
        at android.app.ActivityThread.access$900(ActivityThread.java:151) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1318) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5271) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699) 
```

The null object seems to be this.zzel in the code below, from com.google.firebase.auth.FirebaseAuth.class (decompiled, since it's not open-sourced), which seems to be (or should be) an instance of IdTokenListenersCountChangedListener, judging from [similar, deprecated code found on FirebaseApp.java](https://github.com/firebase/firebase-android-sdk/blob/c9f213cac589595580a04a89784a44e0ff19c39b/firebase-common/src/main/java/com/google/firebase/FirebaseApp.java#L618)
```
    @KeepForSdk
    public void addIdTokenListener(@NonNull com.google.firebase.auth.internal.IdTokenListener var1) {
        Preconditions.checkNotNull(var1);
        this.zzed.add(var1);
        this.zzel.zzf(this.zzed.size());
    }
```
I was unable to create a minimal crashing project, however. I'll be happy to provide any other info necessary or look into the code when/if the auth portion becomes open-sourced. Again, 17.1.0 works so that could be a starting point for investigation.

Current dependencies:
```
dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation project(':openCVLibrary343')
    // base
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'com.google.android.material:material:1.0.0'
    implementation 'com.google.android.gms:play-services-auth:16.0.1'
    // Firebase Misc
    implementation 'com.google.firebase:firebase-core:16.0.5'
    implementation 'com.google.firebase:firebase-firestore:17.1.3'
    implementation 'com.google.firebase:firebase-config:16.1.0'
    implementation 'com.firebaseui:firebase-ui-firestore:4.1.0'
    implementation 'com.crashlytics.sdk.android:crashlytics:2.9.6'
    implementation 'com.google.firebase:firebase-messaging:17.3.4'
    implementation 'com.google.firebase:firebase-functions:16.1.2'
    implementation 'com.google.firebase:firebase-storage:16.0.4'
    // Authentication
    implementation 'com.firebaseui:firebase-ui-auth:4.0.0'
    implementation 'com.facebook.android:facebook-login:4.32.0'
    // MLKit
    implementation 'com.google.firebase:firebase-ml-vision:18.0.1'
    implementation 'com.google.firebase:firebase-ml-vision-image-label-model:17.0.2'
    implementation 'com.google.firebase:firebase-ml-model-interpreter:16.2.3'
    // Cameraview plus
    implementation 'com.asksira.android:cameraviewplus:0.9.4'
    // Glide
    implementation 'com.github.bumptech.glide:glide:4.7.1'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.7.1'
    // Volley
    implementation 'com.android.volley:volley:1.1.1'

    implementation 'androidx.annotation:annotation:1.0.0'
    implementation 'androidx.paging:paging-runtime:2.1.0-beta01'
    implementation 'commons-codec:commons-codec:1.11'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.0-alpha2'
    implementation 'com.google.code.gson:gson:2.8.5'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.0'
}
```

**Comment by red42** [comment]
The code change in FirebaseFirestore.java from 17.1.0 to 17.1.1+, which is causing the issue are the following lines (17.1.0 is obfuscated on decompilation, and it doesn't seem to be on github's history):

### 17.1.1+
```
    CredentialsProvider provider;
    if (authProvider == null) {
      Logger.debug(TAG, "Firebase Auth not available, falling back to unauthenticated usage.");
      provider = new EmptyCredentialsProvider();
    } else {
      provider = new FirebaseAuthCredentialsProvider(authProvider); // THIS LINE CRASHES
    }
```
### 17.1.0
```
com.google.firebase.firestore.a.zza var4 = new com.google.firebase.firestore.a.zza(var0);
```
var4 seems to implement CredentialsProvider, equivalent to provider on the 17.1.1+ code.

authProvider is and InternalAuthProvider with a null IdTokenListenersCountChangedListener, which is causing the exception.

**Comment by wilhuff** [comment]
Hi, your dependency listing doesn't include a version for firebase-auth. The error you're seeing is one that was present in firebase-auth around 16.0.2 but 16.0.5 is current.

Could you post your firebase-auth version and if it's not 16.0.5, could you retry with that version?

**Comment by red42** [comment]
@wilhuff Thanks for the feedback. Including firebase-auth 16.0.5 does indeed solve the issue!

I wonder why I've not been able to reproduce this in a different project, however.
