### ISSUE TITLE
Calling Firebase Cloud Function throwing 'INTERNAL' error

### ISSUE THREAD

**Issue by dawood-ilyas-confiz** [firebase/firebase-android-sdk#1312]
### Environment and Settings:

  * Android Studio version: 3.5.3
  * Firebase Component: Functions
  * Component version: 19.0.1

### Issue:

For Application monitoring, we are using SplunkMint and we are often seeing this issue reported that when we try to call our firebase function through the module. An 'INTERNAL' exception is thrown.

**Exception:**

`com.google.firebase.functions.FirebaseFunctionsException: INTERNAL
	at com.google.firebase.functions.FirebaseFunctions$2.onFailure(SourceFile:270)
	at cpc$a.execute(SourceFile:215)
	at okhttp3.internal.NamedRunnable.run(SourceFile:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.net.UnknownHostException: Unable to resolve host "<base_url(changed manually to maintain privacy)>cloudfunctions.net": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
	at okhttp3.Dns$1.lookup(SourceFile:40)
	at okhttp3.internal.connection.RouteSelector.a(SourceFile:185)
	at okhttp3.internal.connection.RouteSelector.b(SourceFile:149)
	at okhttp3.internal.connection.RouteSelector.next(SourceFile:84)
	at okhttp3.internal.connection.StreamAllocation.a(SourceFile:214)
	at okhttp3.internal.connection.StreamAllocation.a(SourceFile:135)
	at okhttp3.internal.connection.StreamAllocation.newStream(SourceFile:114)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(SourceFile:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(SourceFile:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(SourceFile:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(SourceFile:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:121)
	at cpc.e(SourceFile:254)
	at cpc$a.execute(SourceFile:200)
	... 4 more
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
	at libcore.io.Linux.android_getaddrinfo(Native Method)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:74)
	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:200)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:74)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
	... 26 more`

**Additional Information:**

- We saw on SplunkMint that the majority of this error occurred on Samsung devices with Android 10 installed.
- Average Wifi Strength: 39%
- Average Mobile Network Strength: 100%

#### Relevant Code:

This is how we are calling the function and we get the exception in "onFailure".
```
FirebaseFunctions.getInstance()
                .getHttpsCallable("functionName")
                .call(params)
                .addOnSuccessListener(new OnSuccessListener<Object>() {
                    @Override
                    public void onSuccess(Object o) {
                    }
                })
                .addOnFailureListener(new OnFailureListener() {
                    @Override
                    public void onFailure(@NonNull Exception e) {
                    }
                });
```

Kindly guide us if we are doing anything wrong or if its an issue in the module.

Regards,
Dawood Ilyas

**Comment by ashwinraghav** [comment]
Quoting [error handling dicumentation in the callables](https://firebase.google.com/docs/functions/callable#handle_errors)

_To ensure the client gets useful error details, return errors from a callable by throwing (or returning a Promise rejected with) an instance of functions.https.HttpsError. The error has a code attribute that can be one of the values listed at functions.https.HttpsError. The errors also have a string message, which defaults to an empty string. They can also have an optional details field with an arbitrary value. If an error other than HttpsError is thrown from your functions, your client instead receives an error with the message INTERNAL and the code internal_

I suspect your function is either throwing an exception other than HttpsError.
