### ISSUE TITLE
Service not registered: com.google.android.gms.common.internal.zzf@20fb92a

### ISSUE THREAD

**Issue by jecksonwang** [firebase/firebase-android-sdk#1348]
### Step 1: Describe your environment

  * Android device: Xiaomi MI 8 UD (equuleus)
  * Android OS version: 9.0
  * Google Play Services version: 17.0.0
  * Firebase/Play Services SDK version: 17.0.0
  
### Step 2: Describe the problem:

    app crash by the issue

#### Steps to reproduce:

Appears randomly and randomly during the process of using APP
  
#### Observed Results:

java.lang.IllegalArgumentException: 
  at android.app.LoadedApk.forgetServiceDispatcher (LoadedApk.java:1570)
  at android.app.ContextImpl.unbindService (ContextImpl.java:1702)
  at android.content.ContextWrapper.unbindService (ContextWrapper.java:727)
  at com.google.android.gms.common.stats.ConnectionTracker.unbindService (Unknown Source:25)
  at com.google.android.gms.common.internal.zzf.zzf (Unknown Source:41)
  at com.google.android.gms.common.internal.zze.handleMessage (Unknown Source:45)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at com.google.android.gms.internal.common.zze.dispatchMessage (Unknown Source:8)
  at android.os.Looper.loop (Looper.java:201)
  at android.app.ActivityThread.main (ActivityThread.java:6806)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:547)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:873)
  
#### Expected Results:

  no carsh
  
#### Relevant Code:

After integrating firebase in my project, I occasionally get the following error

Fatal Exception: java.lang.IllegalArgumentException: Service not registered: com.google.android.gms.common.internal.zzf@a87a29b
   at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1680)
   at android.app.ContextImpl.unbindService(ContextImpl.java:1781)
   at android.content.ContextWrapper.unbindService(ContextWrapper.java:730)
   at com.google.android.gms.common.stats.ConnectionTracker.unbindService(:25)
   at com.google.android.gms.common.internal.zzf.zzf(:41)
   at com.google.android.gms.common.internal.zze.handleMessage(:45)
   at android.os.Handler.dispatchMessage(Handler.java:102)
   at com.google.android.gms.internal.common.zze.dispatchMessage(:8)
   at android.os.Looper.loop(Looper.java:214)
   at android.app.ActivityThread.main(ActivityThread.java:7127)
   at java.lang.reflect.Method.invoke(Method.java)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)

I checked the related source code for zzf

  public final void zzf(String var1) {
    zze.zzb(this.zzec).removeMessages(1, this.zzeb);
    zze.zzd(this.zzec).unbindService(zze.zzc(this.zzec), this);
    this.zzea = false;
    this.mState = 2;
}

I would like to ask whether this service is bound by firebase, and when was it unbundled, why did this problem occur when unbundling?

**Comment by JoshLipan** [comment]
Same issue，please fix this.Here is a list of errors collected online.
![image](https://user-images.githubusercontent.com/16323137/79719665-a1c5d100-8311-11ea-902f-61bb6845d279.png)
![image](https://user-images.githubusercontent.com/16323137/79719686-aab6a280-8311-11ea-8583-1f1cfbbdf72c.png)

**Comment by JoshLipan** [comment]
Same issue，please fix this.
```java
implementation 'com.google.firebase:firebase-messaging:20.0.0'
implementation 'com.google.firebase:firebase-core:17.0.0'
...
apply plugin: 'com.google.gms.google-services'
```
![image](https://user-images.githubusercontent.com/16323137/79719735-c621ad80-8311-11ea-91d9-b7bf177660fc.png)
![image](https://user-images.githubusercontent.com/16323137/79719807-e6516c80-8311-11ea-87a0-77c3cc94fc37.png)

**Comment by TOPWN** [comment]
Same issue，please fix this
![image](https://user-images.githubusercontent.com/23627960/82559286-edce9480-9ba1-11ea-9eb1-9bae53dd18ce.png)
![image](https://user-images.githubusercontent.com/23627960/82559315-fcb54700-9ba1-11ea-9da0-f8763051d543.png)

**Comment by TOPWN** [comment]
> Same issue，please fix this
> ![image](https://user-images.githubusercontent.com/23627960/82559286-edce9480-9ba1-11ea-9eb1-9bae53dd18ce.png)
> ![image](https://user-images.githubusercontent.com/23627960/82559315-fcb54700-9ba1-11ea-9da0-f8763051d543.png)

This issue first happened in version 7.0.3 of my app, in version 7.0.3 I upgraded the version of Android gradle plugin (from 2.3.2 to 3.5.2) . Is there any incompatibility between the firebase SDK and version 3.5.2 of gradle plugin?

**Comment by ashwinraghav** [comment]
Thanks for your patience. Are you seeing the issue in specific locations and only on Xiaomi MI 8 UD  devices?

**Comment by jecksonwang** [comment]
> Thanks for your patience. Are you seeing the issue in specific locations and only on Xiaomi MI 8 UD devices?

![bug1](https://user-images.githubusercontent.com/30489677/83494656-2e56d800-a4e9-11ea-8645-8b4e9c147953.png)
![BUG2](https://user-images.githubusercontent.com/30489677/83494661-30209b80-a4e9-11ea-9c77-6b78393eebd1.png)
can find in huawei and samsung

**Comment by TOPWN** [comment]
> Firebase uses FirebaseInitProvider to obtain the Context without intrusion, and this Context is an instance of Application, so we can rewrite Application#unbindService(), and the unbindService() that is finally called will be captured here

`      @Override
    public void unbindService(ServiceConnection conn) {
        try {
            super.unbindService(conn);
        } catch (IllegalArgumentException e) {
            e.printStackTrace();
            // do something, ignore or report...
        }
    }
`

**Comment by TOPWN** [comment]
> Firebase uses FirebaseInitProvider to obtain the Context without intrusion, and this Context is an instance of Application, so we can rewrite Application#unbindService(), and the unbindService() that is finally called will be captured here
![Uploading image.png…]()

**Comment by CharlesTai** [comment]
same issue

**Comment by CharlesTai** [comment]
> > Firebase uses FirebaseInitProvider to obtain the Context without intrusion, and this Context is an instance of Application, so we can rewrite Application#unbindService(), and the unbindService() that is finally called will be captured here
> 
> ` @Override public void unbindService(ServiceConnection conn) { try { super.unbindService(conn); } catch (IllegalArgumentException e) { e.printStackTrace(); // do something, ignore or report... } }`

same issue and i add these code in my application but it not worked.

**Comment by riteshmaddala** [comment]
Getting similar issue .. Please update.

**Comment by NativeDevlopment** [comment]
Getting similar issue .. Please update.

**Comment by tochange** [comment]
Getting similar issue .. Please fix it.

**Comment by aguatno** [comment]
Hi @jecksonwang Sorry for the long wait here. I'd like to confirm if you're still seeing this issue? I'd recommend using the latest SDK version in your app to ensure old known bugs are fixed.

Thanks!

**Comment by CharlesTai** [comment]
> Hi @jecksonwang Sorry for the long wait here. I'd like to confirm if you're still seeing this issue? I'd recommend using the latest SDK version in your app to ensure old known bugs are fixed.
> 
> Thanks!

I'm using the latest sdk version,but bugs still exist.
