### ISSUE TITLE
INTERNAL ASSERTION FAILED: We are running on the wrong thread

### ISSUE THREAD

**Issue by MattSkala** [firebase/firebase-android-sdk#1372]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 3.6.1
  * Firebase Component: Firestore
  * Component version: 21.4.0

#### Steps to reproduce:

We started to see the following AssertionError crashes over the past few weeks, after updating to Firestore 21.4.0. We are not able to reproduce it. In Crashlytics, I can see that 100% of these crashes happen when the app is in the background.

```
Fatal Exception: java.lang.AssertionError: INTERNAL ASSERTION FAILED: We are running on the wrong thread. Expected to be on the AsyncQueue thread FirestoreWorker/13131 but was AsyncTask #4/13120
       at com.google.firebase.firestore.util.Assert.fail(Assert.java:46)
       at com.google.firebase.firestore.util.AsyncQueue.verifyIsCurrentThread(AsyncQueue.java:407)
       at com.google.firebase.firestore.util.AsyncQueue$DelayedTask.cancel(AsyncQueue.java:126)
       at com.google.firebase.firestore.remote.GrpcCallProvider.clearConnectivityAttemptTimer(GrpcCallProvider.java:274)
       at com.google.firebase.firestore.remote.GrpcCallProvider.onConnectivityStateChange(GrpcCallProvider.java:222)
       at com.google.firebase.firestore.remote.GrpcCallProvider.lambda$initChannelTask$5(GrpcCallProvider.java:257)
       at com.google.firebase.firestore.remote.GrpcCallProvider$$Lambda$5.call(GrpcCallProvider.java:2)
       at com.google.android.gms.tasks.zzv.run(zzv.java:2)
       at com.google.firebase.firestore.util.ThrottledForwardingExecutor.lambda$execute$0(ThrottledForwardingExecutor.java:54)
       at com.google.firebase.firestore.util.ThrottledForwardingExecutor$$Lambda$1.run(ThrottledForwardingExecutor.java:4)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```

**Comment by wu-hui** [comment]
This should be fixed in next release, possibly 3 weeks away.
