### ISSUE TITLE
Internal error in Firestore (0.6.6-dev) and Timestamp seconds out of range

### ISSUE THREAD

**Issue by Kinjanjain** [firebase/firebase-android-sdk#1384]
### [REQUIRED] : Eenvironment
Android Studio version: 3.6.1
Device : Vuzix M300 (6.0.1 OS)
Library :
implementation('com.google.firebase:firebase-core:16.0.3') {
        exclude group: 'com.android.support'
    }
implementation 'com.crashlytics.sdk.android:crashlytics:2.9.9'
implementation 'com.google.firebase:firebase-firestore:19.0.0

### [REQUIRED] : Describe the problem

When we use firestore it is crashing application. this is only happening in vuzix M300 device.

CRASH : which i got from firebase crashlytics.
Fatal Exception: java.lang.RuntimeException: Internal error in Firestore (0.6.6-dev).
       at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$5(com.google.firebase:firebase-firestore@@17.1.2:377)
       at com.google.firebase.firestore.util.AsyncQueue$$Lambda$5.run(com.google.firebase:firebase-firestore@@17.1.2)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by java.lang.RuntimeException: java.lang.IllegalArgumentException: Timestamp seconds out of range: 6805631756636681734
       at com.google.firebase.firestore.util.AsyncQueue.lambda$enqueue$3(com.google.firebase:firebase-firestore@@17.1.2:288)
       at com.google.firebase.firestore.util.AsyncQueue$$Lambda$3.run(com.google.firebase:firebase-firestore@@17.1.2)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at com.google.firebase.firestore.util.AsyncQueue$DelayedStartFactory.run(com.google.firebase:firebase-firestore@@17.1.2:203)
       at java.lang.Thread.run(Thread.java:818)

###
![Capture_firebase](https://user-images.githubusercontent.com/42671834/77398942-6bf30280-6dce-11ea-9e86-cc434d6586fb.PNG)
 Relevant Code:

documentName = System.currentTimeMillis() + "_" + documentName;
Map<String, Object> docParentMap = new HashMap<>();
Map<String, Object> documentMap = new HashMap<>();
documentMap.put(documentName, documentObject);
docParentMap.put(parent, documentMap);
mFireStoreDb.collection(mCollectionId)
        .document(mUserId)
        .set(docParentMap, SetOptions.merge())
        .addOnSuccessListener(aVoid ->
                LoggerConfig.eLog(TAG, "Document successfully written"))
        .addOnFailureListener(e ->
                LoggerConfig.eLog(TAG, "Error while writing document::" + e.getMessage()));

**Comment by rostopira** [comment]
Seems like it's the same issues as https://github.com/firebase/firebase-android-sdk/issues/1186 that was closed

**Comment by davidmotson** [comment]
Closing due to duplicate issue.
