### ISSUE TITLE
startActivityForSignInWithProvider::failure

### ISSUE THREAD

**Issue by AgustaRC** [firebase/firebase-android-sdk#1385]
### Describe your environment

  * Android Studio version: 3.6.1
  * Firebase Component: Auth
  * Component version: 19.2.0

### Describe the problem
https://firebase.google.com/docs/auth/android/apple
We have developed Sign in with Apple on Android and confirmed that it is working properly.
But, if API key restricted to Android in the Google Cloud Console, it does not work with the following error.

```java
    com.firebase.ui.auth.FirebaseUiException: An internal error has occurred. [ Requests from this Android client application <empty> are blocked. ]
        at com.google.firebase.auth.api.internal.zzdv.zza(com.google.firebase:firebase-auth@@19.2.0:18)
        at com.google.firebase.auth.internal.zzal.onReceive(com.google.firebase:firebase-auth@@19.2.0:32)
        at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
        at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7770)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)
```

```
An internal error has occurred. [ Requests from this Android client application <empty> are blocked. ]
```

If the API key is set to none, everything works properly.
Should API Key restrictions be lifted to apply OAuth authentication such as Apple?
Or is there something else I missed?

For your information, I found 403 error in the `Identitytoolkit.getProjects` API.

[Firebase Auth: Requests from this Android client application com.xxx are blocked](https://stackoverflow.com/questions/51925442/firebase-auth-requests-from-this-android-client-application-com-xxx-are-blocked)
I've seen above discussion many times. But it's not a solution because adding or deleting signature makes it API Key restrictions are lifted automatically.

I don't think it's not SHA-1 signature problem because other APIs that use the same API Key do not have problems.

And I tested it with a demo project at https://github.com/firebase/FirebaseUI-Android, but the same problem happens.

I have no idea how to get authenticate using Apple to work properly  when API Key is restricted to Android

**Comment by BSunk** [comment]
I have been working on adding apple sign in as well and am facing a similar issue and the same error message. There seems to be some permission issues with using the api key if it's restricted to just Android. When setting as no restrictions the apple sign in flow works as expected. 

` com.google.firebase.auth.FirebaseAuthWebException: There was an internal error in the web widget. [ {"code":"auth/internal-error","message":"{\"error\":{\"code\":403,\"message\":\"Requests from this Android client application <empty> are blocked.\",\"errors\":[{\"message\":\"Requests from this Android client application <empty> are blocked.\",\"domain\":\"global\",\"reason\":\"forbidden\"}],\"status\":\"PERMISSION_DENIED\"}}"} ]
        at com.google.firebase.auth.api.internal.zzeh.zza(com.google.firebase:firebase-auth@@19.3.1:36)
        at com.google.firebase.auth.internal.zzan.onReceive(com.google.firebase:firebase-auth@@19.3.1:32)
        at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
        at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6165)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)`

**Comment by malcolmdeck** [comment]
Hey folks, Malcolm from the Firebase team here! This is a result of how API key restrictions work. Because Apple Sign In uses a web-based flow on Android, the web part of the flow doesn't pass the restrictions placed. We're considering a couple of ways that would allow working around this, but that creates some other, more complicated security issues. This is being tracked internally in b/153007239 - if there is any resolution other than leaving as is I'll let you know. In the meantime, this is expected behavior. Sorry I can't be more helpful :/

**Comment by ashwinraghav** [comment]
Folks, it seems like the only current fix is to **not** enable Android only restrictions on API keys if you intend using the Apple sign in flow. We realize this is a regression on the security measures you are setting up. Please let us know if you are able to work around the errors by loosening these restrictions.
Fwiw, I've left a few comments on the really limited scope of setting up these restrictions in this thread https://github.com/firebase/firebase-android-sdk/issues/1583#issuecomment-634157338.
;tldr: The security benefits for keys used on iOS and Android apps are really marginal.
