### ISSUE TITLE
FirebaseMessagingService.java Push Notification crash

### ISSUE THREAD

**Issue by Discovery-Prachi** [firebase/firebase-android-sdk#1429]
Android Studio version: _____3.6
Firebase Component: _____ firebase-messaging
Component version: _____"20.1.0"

We are using firebase for push notifications. We have got this crash for few users, though we couldn't simulate, this is reported in crashlytics. Can you please help us fix this

Fatal Exception: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
       at android.os.Handler.<init>(Handler.java:209)
       at android.os.Handler.<init>(Handler.java:123)
       at android.widget.Toast$TN.<init>(Toast.java:350)
       at android.widget.Toast.<init>(Toast.java:106)
       at android.widget.Toast.makeText(Toast.java:264)
       at android.media.RingtoneManager.isRingtoneExist(RingtoneManager.java:1218)
       at android.app.NotificationManager.notify(NotificationManager.java:235)
       at com.google.firebase.messaging.zzd.zza(zzd.java:57)
       at com.google.firebase.messaging.FirebaseMessagingService.zzc(FirebaseMessagingService.java:69)
       at com.google.firebase.messaging.zze.run(zze.java:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at com.google.android.gms.common.util.concurrent.zza.run(zza.java:6)
       at java.lang.Thread.run(Thread.java:818)

**Comment by andirayo** [comment]
Note: Does not seem to be FIS related, but `v20.1.0` was the first version of IID to use FIS.

**Comment by pnkshir** [comment]
Hello @ciarand Could you please suggest further on this

**Comment by catman-19** [comment]
Hi @Discovery-Prachi, could you confirm if you're still seeing similar crash reports using the latest SDK version (https://firebase.google.com/support/release-notes/android)? If so, please provide us with the following information to isolate the issue:
- minimal code repro
- steps to reproduce the issue
- affected devices and OS version

Thanks!
