### ISSUE TITLE
java.lang.IllegalStateException: state: 6

### ISSUE THREAD

**Issue by pnkshir** [firebase/firebase-android-sdk#1451]
Android Studio version: _____3.6
Firebase Component: _____ firebase-messaging
Component version: _____"20.1.0"

We are using firebase for push notifications. We have got this crash for few users repetitively, though we couldn't simulate, this is reported in crashlytics. Can you please help us fix this

Android devices this is reproducing on : vivo 1920 OS 9,  Redmi Y2 OS 9,  Redmi Note 7S OS 9, HUAWEI OS 9, OPPO F9 OS 9. As it can be observed this crash is mainly on Android OS 9

Logs : 

Fatal Exception: java.lang.IllegalStateException: state: 6
       at com.android.okhttp.internal.http.Http1xStream$AbstractSource.endOfInput(Http1xStream.java:356)
       at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:401)
       at com.android.okhttp.internal.Util.skipAll(Util.java:159)
       at com.android.okhttp.internal.Util.discard(Util.java:141)
       at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.close(Http1xStream.java:410)
       at com.android.okhttp.okio.RealBufferedSource.close(RealBufferedSource.java:396)
       at com.android.okhttp.okio.RealBufferedSource$1.close(RealBufferedSource.java:384)
       at com.google.android.gms.internal.firebase_messaging.zzk.zza(zzk.java:4)
       at com.google.firebase.messaging.zzm.close(zzm.java:37)
       at com.google.firebase.messaging.zzd.zza(zzd.java:51)
       at com.google.firebase.messaging.FirebaseMessagingService.zzc(FirebaseMessagingService.java:69)
       at com.google.firebase.messaging.zze.run(zze.java:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.android.gms.common.util.concurrent.zza.run(zza.java:6)
       at java.lang.Thread.run(Thread.java:764)

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by pnkshir** [comment]
Hello @ciarand Could you please suggest on this
