### ISSUE TITLE
AssertionError: No NameTypeIndex match for SHORT_DAYLIGHT

### ISSUE THREAD

**Issue by ber4444** [firebase/firebase-android-sdk#1453]
### [READ] Step 1: Are you in the right place?

Yes

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.0 beta 4
  * Firebase Component: Instance ID
  * Component version: 20.0.2 (there is not any fix in newer versions of the sdk)

#### Steps to reproduce:

```
Fatal Exception: java.lang.AssertionError: No NameTypeIndex match for SHORT_DAYLIGHT
       at android.icu.impl.TimeZoneNamesImpl$ZNames.getNameTypeIndex(TimeZoneNamesImpl.java:724)
       at android.icu.impl.TimeZoneNamesImpl$ZNames.getName(TimeZoneNamesImpl.java:790)
       at android.icu.impl.TimeZoneNamesImpl.getTimeZoneDisplayName(TimeZoneNamesImpl.java:183)
       at android.icu.text.TimeZoneNames.getDisplayName(TimeZoneNames.java:261)
       at java.util.TimeZone.getDisplayName(TimeZone.java:405)
       at java.util.Date.toString(Date.java:1066)
       at java.util.Properties.store0(Properties.java:828)
       at java.util.Properties.store(Properties.java:817)
       at com.google.firebase.iid.zzq.zza(zzq.java:82)
       at com.google.firebase.iid.zzq.zzb(zzq.java:8)
       at com.google.firebase.iid.zzq.zza(zzq.java:5)
       at com.google.firebase.iid.zzat.zzb(zzat.java:48)
       at com.google.firebase.iid.FirebaseInstanceId.zzl(FirebaseInstanceId.java:48)
       at com.google.firebase.iid.FirebaseInstanceId.zza(FirebaseInstanceId.java:131)
```

#### Relevant Code:

Could be fixed by you like this: https://issuetracker.google.com/issues/110848122#comment18

**Comment by welishr** [comment]
Hi @ber4444 - the codepath causing the exception was removed in Instance ID version 20.1.0, so I would not expect to see that issue in any component with that version or above

**Comment by ashwinraghav** [comment]
Please let us know if that works out

**Comment by ber4444** [comment]
Which Firebase BoM version is that?

**Comment by chliangGoogle** [comment]
Instance ID version 20.1.0
