### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException [Performance Monitoring]

### ISSUE THREAD

**Issue by ashwini009** [firebase/firebase-android-sdk#1454]
Multiple crashes on production:

```
Fatal Exception: java.lang.IllegalStateException
       at com.google.firebase.iid.FirebaseInstanceId.h(com.google.firebase:firebase-iid@@20.1.0:12)
       at com.google.firebase.iid.FirebaseInstanceId.a(com.google.firebase:firebase-iid@@20.1.0:14)
       at e.j.c.r.b.f.a(com.google.firebase:firebase-perf@@19.0.5:63)
       at e.j.c.r.b.e.run(com.google.firebase:firebase-perf@@19.0.5:22)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
```

I am not able to reproduce the issue on the live setup. 
This is occurring on all supported Android OS (5 to 9). 

## Version: 19.0.5

I understand that `19.0.6` was released with an NPE fix. I am doubtful that upgrading to the latest will fix the issue.

**Comment by ramanpreetSinghKhinda** [comment]
Hi @ashwini009,

Thanks for reaching out~

This looks very similar to https://github.com/firebase/firebase-android-sdk/issues/1339. See if the suggestions in https://github.com/firebase/firebase-android-sdk/issues/1397#issuecomment-605842496 helps?

Can you also provide more information on what other Firebase SDKs (and there version) are you using in the app?

**Comment by ashwini009** [comment]
Hi @ramanpreetSinghKhinda ,

I saw the issue #1339 , where it suggested to use FiebaseInstanceId version `20.1.5`.
Note that, we never explicitly used the above dependency in our app.

Here are the firebase deps being used currently:
```
versions.firebase_messaging = '20.1.5'
versions.firebase_config = '19.1.3'
versions.firebase_perf = '19.0.6'
versions.firebase_analytics = '17.3.0' 
versions.firebase_dynamic_links = '19.1.0'
versions.firebase_vision = '24.0.2'
```

**Comment by andirayo** [comment]
You can upgrade `firebase_messaging` to `v20.1.5` and you will get FirebaseInstanceId version `20.1.5` implicitly. No need to add an explicit dependency.

**Comment by ashwini009** [comment]
Updating `firebase-messaging` to `20.1.5` fixed the issue.

**Comment by Gnzlt** [comment]
I still have the same issue with `20.1.5`
```
Fatal Exception: java.lang.IllegalStateException
       at com.google.firebase.iid.FirebaseInstanceId.zzl(FirebaseInstanceId.java:70)
       at com.google.firebase.iid.FirebaseInstanceId.getId(FirebaseInstanceId.java:48)
       at com.google.firebase.perf.internal.zzf.zzbv(zzf.java:181)
       at com.google.firebase.perf.internal.zzf.zzbu(zzf.java:44)
       at com.google.firebase.perf.internal.zzf.zzc(zzf.java:195)
       at com.google.firebase.perf.internal.zze.run(zze.java:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)
```

**Comment by ramanpreetSinghKhinda** [comment]
@Gnzlt Thanks for reaching out. You stack traces looks very similar to -> https://github.com/firebase/firebase-android-sdk/issues/1528

Can you followup there?

**Comment by ankitaj224** [comment]
@Gnzlt can you please attach the stack trace of all threads as seen in crashlytics reports?

**Comment by Gnzlt** [comment]
> @Gnzlt can you please attach the stack trace of all threads as seen in crashlytics reports?

Hope it helps!
[FirebaseInstanceId.log](https://github.com/firebase/firebase-android-sdk/files/4614062/FirebaseInstanceId.log)

**Comment by ankitaj224** [comment]
@Gnzlt Thanks for the logs.
