### ISSUE TITLE
Exception: java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by pnkshir** [firebase/firebase-android-sdk#1478]
Android Studio version: _____3.6
Firebase Component: _____ firebase-messaging
Component version: _____"20.1.0"

We are using firebase for push notifications. We have got this crash for few users repetitively, though we couldn't simulate, this is reported in crashlytics. Can you please help us fix this
ONEPLUS A6010 , Android OS 10

Fatal Exception: java.lang.IllegalArgumentException: byteCount < 0: -156
       at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:47)
       at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:395)
       at com.android.okhttp.internal.Util.skipAll(Util.java:165)
       at com.android.okhttp.internal.Util.discard(Util.java:147)
       at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.close(Http1xStream.java:412)
       at com.android.okhttp.okio.RealBufferedSource.close(RealBufferedSource.java:397)
       at com.android.okhttp.okio.RealBufferedSource$1.close(RealBufferedSource.java:385)
       at com.google.android.gms.internal.firebase_messaging.zzk.zza(zzk.java:4)
       at com.google.firebase.messaging.zzm.close(zzm.java:37)
       at com.google.firebase.messaging.zzd.zza(zzd.java:51)
       at com.google.firebase.messaging.FirebaseMessagingService.zzc(FirebaseMessagingService.java:69)
       at com.google.firebase.messaging.zze.run(zze.java:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.android.gms.common.util.concurrent.zza.run(zza.java:6)
       at java.lang.Thread.run(Thread.java:919)

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by pnkshir** [comment]
Hello @ciarand could you please suggest further on this

**Comment by ashwinraghav** [comment]
Thanks for the report.
Seems like a problem with the version of [okhttp on android](https://github.com/square/okhttp/issues/3104). This may be hard to systematically fix given that it requires an OS [update](https://android.googlesource.com/platform/external/okhttp/+/master).
Are you able to narrow down specific images in your payload that cause this?

**Comment by DrIllness** [comment]
Hello. I'm facing the same issue. 

Stacktrace from developer console:
`java.lang.IllegalArgumentException: 
  at com.android.okhttp.okio.RealBufferedSource.read (RealBufferedSource.java:52)
  at com.android.okhttp.internal.http.Http1xStream$ChunkedSource.read (Http1xStream.java:648)
  at com.android.okhttp.internal.Util.skipAll (Util.java:172)
  at com.android.okhttp.internal.Util.discard (Util.java:154)
  at com.android.okhttp.internal.http.Http1xStream$ChunkedSource.close (Http1xStream.java:681)
  at com.android.okhttp.okio.RealBufferedSource.close (RealBufferedSource.java:421)
  at com.android.okhttp.okio.RealBufferedSource.close (RealBufferedSource.java:421)
  at com.android.okhttp.okio.InflaterSource.close (InflaterSource.java:126)
  at com.android.okhttp.okio.GzipSource.close (GzipSource.java:182)
  at com.android.okhttp.okio.RealBufferedSource.close (RealBufferedSource.java:421)
  at com.android.okhttp.okio.RealBufferedSource$1.close (RealBufferedSource.java:409)
  at com.google.android.gms.internal.firebase_messaging.zzk.zza
  at com.google.firebase.messaging.zzq.close
  at com.google.firebase.messaging.zzc.zza
  at com.google.firebase.messaging.FirebaseMessagingService.zzc
  at com.google.firebase.messaging.zzh.run
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at com.google.android.gms.common.util.concurrent.zza.run (Unknown Source:6)
  at java.lang.Thread.run (Thread.java:764)`

My dependencies:
    implementation "com.google.firebase:firebase-core:17.4.1'"
    implementation "com.google.firebase:firebase-messaging:20.1.7"

Images that were attached to push notification are attached as well. Please, specify, if any other info is required.
[Image one](https://i.gifer.com/6mw.gif)
[Image two](https://i.gifer.com/8a9G.gif)
