### ISSUE TITLE
SQLiteException: Failed to change locale for db

### ISSUE THREAD

**Issue by methelas** [firebase/firebase-android-sdk#1499]
### Describe your environment

  * Android Studio version: 3.5
  * Firebase Components:
+> com.google.firebase:firebase-analytics:17.2.3
+> com.google.firebase:firebase-messaging:20.1.3
+> com.crashlytics.sdk.android:crashlytics:2.10.1

### Describe the problem

It's really a long shot, but it's the only place I found issues with similar stack trace. If by any chance it is related to it then maybe you will be able to help me figure it out, otherwise feel free to close the issue.

I've received the following crash report yesterday:
```
android.database.sqlite.SQLiteException: Failed to change locale for db '/data/user/0/[redacted]/databases/com.google.android.datatransport.events' to 'en_US'.
    at android.database.sqlite.SQLiteConnection.setLocaleFromConfiguration(SQLiteConnection.java:394)
    at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:219)
    at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:194)
    at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:493)
    at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:200)
    at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:192)
    at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:864)
    at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:849)
    at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:724)
    at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:714)
    at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:295)
    at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:238)
    at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore.com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore$$Lambda$1.produce(com.google.android.datatransport:transport-runtime@@2.2.0:3)
    at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore.runCriticalSection(com.google.android.datatransport:transport-runtime@@2.2.0:110)
    at com.google.android.datatransport.runtime.scheduling.jobscheduling.WorkInitializer$$Lambda$1.com.google.android.datatransport.runtime.scheduling.jobscheduling.WorkInitializer.lambda$ensureContextsScheduled$1(com.google.android.datatransport:transport-runtime@@2.2.0:3)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
    at java.lang.Thread.run(Thread.java:764)
```

The app thats affected does not create any databases by itself, lower in the stack you can see that the issue originated somewhere in `com.google.android.datatransport` which I assume is used by one of the components I listed above.

#### Steps to reproduce:
Didn't manage to reproduce the issue.
Although it did happen on a physical device:
**TECNO F1**
**Android 8.1**

**Comment by ashwinraghav** [comment]
Thank you for the report . @vkryachko possibly similar to this [SO](https://stackoverflow.com/questions/19491675/failed-to-change-locale-for-db-data-data-my-easymedi-controller-databases-easy)
post ?

**Comment by vkryachko** [comment]
@methelas Thanks for the report. Is this the full stacktrace? Looking at Android 8.1's source I can see that the exception is thrown with a [`cause`](https://github.com/aosp-mirror/platform_frameworks_base/blob/53a9ccaa926945149b4546c67b50ce1ae88ba777/core/java/android/database/sqlite/SQLiteConnection.java#L394)

If you have the rest of the stacktrace that would greatly help me investigate further, thanks

**Comment by methelas** [comment]
Hope this helps

```
Fatal Exception: android.database.sqlite.SQLiteException: Failed to change locale for db '/data/user/0/[redacted]/databases/com.google.android.datatransport.events' to 'en_US'.
       at android.database.sqlite.SQLiteConnection.setLocaleFromConfiguration(SQLiteConnection.java:394)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:219)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:194)
       at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:493)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:200)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:192)
       at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:864)
       at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:849)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:724)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:714)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:295)
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:238)
       at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore$$Lambda$1.produce(SQLiteEventStore.java:3)
       at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore.retryIfDbLocked(SQLiteEventStore.java:456)
       at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore.getDb(SQLiteEventStore.java:80)
       at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore.runCriticalSection(SQLiteEventStore.java:488)
       at com.google.android.datatransport.runtime.scheduling.jobscheduling.WorkInitializer.lambda$ensureContextsScheduled$1(WorkInitializer.java:54)
       at com.google.android.datatransport.runtime.scheduling.jobscheduling.WorkInitializer$$Lambda$1.run(WorkInitializer.java:3)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
```

```
Caused by android.database.sqlite.SQLiteDiskIOException: disk I/O error (code 1034)
       at android.database.sqlite.SQLiteConnection.nativeExecute(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:556)
       at android.database.sqlite.SQLiteConnection.setLocaleFromConfiguration(SQLiteConnection.java:372)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:219)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:194)
       at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:493)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:200)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:192)
       at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:864)
       at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:849)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:724)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:714)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:295)
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:238)
       at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore$$Lambda$1.produce(SQLiteEventStore.java:3)
       at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore.retryIfDbLocked(SQLiteEventStore.java:456)
       at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore.getDb(SQLiteEventStore.java:80)
       at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore.runCriticalSection(SQLiteEventStore.java:488)
       at com.google.android.datatransport.runtime.scheduling.jobscheduling.WorkInitializer.lambda$ensureContextsScheduled$1(WorkInitializer.java:54)
       at com.google.android.datatransport.runtime.scheduling.jobscheduling.WorkInitializer$$Lambda$1.run(WorkInitializer.java:3)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
```

**Comment by vkryachko** [comment]
Given the error code it looks like an fsync() issue, which can fail due to [various reasons](http://man7.org/linux/man-pages/man2/fsync.2.html#ERRORS), one of which is disk full.

Is it a one-off crash report, or are you seeing this happen regularly on multiple devices?

**Comment by methelas** [comment]
One time, one device. It's just a pretty fresh app, tested internally with less than a 100 users so far, so I'm trying to get to the bottom of each issue that pops up.
If fsync() is really the cause here then I guess theres nothing I can do about it now. 
Thanks a lot for checking :)
