### ISSUE TITLE
SQLiteException in firebase-crashlytics

### ISSUE THREAD

**Issue by b99202021** [firebase/firebase-android-sdk#1531]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 3.4.2
  * Firebase Component:  firebase-crashlytics
  * Component version: 
      FIREBASE_ANALYTICS = "17.4.0"
      FIREBASE_MESSAGING = "20.1.6"
      FIREBASE_CRASHLYTICS = "17.0.0"

### [REQUIRED] Step 3: Describe the problem

We have a significant number of crash reports in crashlytics with SQLiteException

`duplicate column name: extras (code 1 SQLITE_ERROR): , while compiling: ALTER TABLE transport_contexts ADD COLUMN extras BLOB
android.database.sqlite.SQLiteConnection.nativePrepareStatement
`

We upgraded from Fabric Crashlytics SDK to Firebase Crashlytics SDK in March and downgrade to Fabric Crashlytics SDK. When we upgrade from Fabric Crashlytics SDK to Firebase Crashlytics SDK this week, the crash happened.

Log
`
 Fatal Exception: android.database.sqlite.SQLiteException: duplicate column name: extras (code 1 SQLITE_ERROR): , while compiling: ALTER TABLE transport_contexts ADD COLUMN extras BLOB
       at android.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:903)
       at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:514)
       at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
       at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
       at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
       at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1770)
       at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1698)
       at com.google.android.datatransport.runtime.scheduling.persistence.SchemaManager.lambda$static$1(SchemaManager.java:97)
       at com.google.android.datatransport.runtime.scheduling.persistence.SchemaManager$$Lambda$2.upgrade(SchemaManager.java)
       at com.google.android.datatransport.runtime.scheduling.persistence.SchemaManager.upgrade(SchemaManager.java:182)
       at com.google.android.datatransport.runtime.scheduling.persistence.SchemaManager.onUpgrade(SchemaManager.java:152)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:398)
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:298)
       at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore$$Lambda$1.produce(SQLiteEventStore.java:2)
       at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore.retryIfDbLocked(SQLiteEventStore.java:517)
       at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore.getDb(SQLiteEventStore.java:82)
       at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore.runCriticalSection(SQLiteEventStore.java:549)
       at com.google.android.datatransport.runtime.scheduling.jobscheduling.WorkInitializer.lambda$ensureContextsScheduled$1(WorkInitializer.java:54)
       at com.google.android.datatransport.runtime.scheduling.jobscheduling.WorkInitializer$$Lambda$1.run(WorkInitializer.java:1054)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)
`
#### Steps to reproduce:
install version with firebase crashlytics SDK-> upgrade version to one without firebase crashlytics SDK-> upgrade version to one with firebase crashlytics SDK

**Comment by ashwinraghav** [comment]
@b95505017 I've not been able to repro the issue unfortunately. Just so I understand, your repro steps are
1) Install version of test app with `implementation 'com.google.firebase:firebase-crashlytics:17.0.0'`.
2) Remove  `implementation 'com.google.firebase:firebase-crashlytics:17.0.0'` from the test app.
3) Install test app
4) Re introduce `implementation 'com.google.firebase:firebase-crashlytics:17.0.0'`
5) Install
6) Expect crash ?

Also, our migrations are scoped into [this](https://github.com/firebase/firebase-android-sdk/blob/4498fccb497a897f2832599c8db42cb34abc5ce9/transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/SchemaManager.java) class. Please let us know if you see something that stands out.

**Comment by b95505017** [comment]
@ashwinraghav Sorry you tag the wrong person 😂

**Comment by ashwinraghav** [comment]
> @ashwinraghav Sorry you tag the wrong person 😂

Sry bout that
 cc @b99202021

**Comment by ashwinraghav** [comment]
cc @b99202021  I've tried to simulate some of the failures you describe in PR https://github.com/firebase/firebase-android-sdk/pull/1548. While it did reveal some other backward incompatibilities, I'm yet to put a finger on what could cause this. Can you share the exact versions of firebase crash you were using before the downgrade, and after the upgrade?

**Comment by b99202021** [comment]
@ashwinraghav I was using (1) firebase:firebase-crashlytics-gradle:2.0.0-beta02    (2) .firebase:firebase-analytics:17.2.3 (3) firebase-crashlytics:17.0.0-beta0 before downgrade        But only some of my user are facing the crash. And I cannot reproduce the crash everytime.

**Comment by b99202021** [comment]
I got 

`android.database.sqlite.SQLiteException:` table event_payloads already exists (code 1): , while compiling: CREATE TABLE event_payloads (sequence_num INTEGER NOT NULL, event_id INTEGER NOT NULL, bytes BLOB NOT NULL,FOREIGN KEY (event_id) REFERENCES events(_id) ON DELETE CASCADE,PRIMARY KEY (sequence_num, event_id))`

when I downgrade and upgrade again.
