### ISSUE TITLE
SocketTimeoutException after FirebaseInstanceId.getInstance().deleteInstanceId()

### ISSUE THREAD

**Issue by mt-lubov** [firebase/firebase-android-sdk#1578]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.0.0-beta05
  * Firebase Component: Firebase IID (via messaging)
  * Component version: 
```
FIREBASE_MESSAGING = "20.1.7"
FIREBASE_CRASHLYTICS = "17.0.0"
```

Firebase installations resolves to 16.3.0

### [REQUIRED] Step 3: Describe the problem

We have a stable crash after `deleteInstanceId()` during connection issues:
```
java.net.SocketTimeoutException: timeout
        at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:207)
        at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:250)
        at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
        at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
        at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
        at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
        at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191)
        at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
        at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:904)
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:788)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:439)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:384)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:497)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java)
        at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.deleteFirebaseInstallation(com.google.firebase:firebase-installations@@16.3.0:304)
        at com.google.firebase.installations.FirebaseInstallations.deleteFirebaseInstallationId(com.google.firebase:firebase-installations@@16.3.0:503)
        at com.google.firebase.installations.FirebaseInstallations.access$lambda$3(com.google.firebase:firebase-installations@@16.3.0)
        at com.google.firebase.installations.FirebaseInstallations$$Lambda$4.call(com.google.firebase:firebase-installations@@16.3.0)
        at com.google.android.gms.tasks.zzv.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
```

#### Steps to reproduce:

Calling FirebaseInstanceId.getInstance().deleteInstanceId() without connection cause SocketTimeoutException

#### Relevant Code:

```
firebaseInstanceId.deleteInstanceId()
```

**Comment by ankitaj224** [comment]
@mt-lubov

Thanks for reporting this issue. Firebase Android SDK [released after February 27](https://firebase.google.com/support/release-notes/android#2020-02-27)  introduced a new SDK: Firebase Installations. FirebaseInstanceId SDK also a new dependency on FirebaseInstallations SDK.

Since Feb 27, [`firebaseInstanceId.deleteInstanceId()`](https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceId#deleteInstanceId()) internally calls [`firebaseInstallations.delete()`](https://firebase.google.com/docs/reference/android/com/google/firebase/installations/FirebaseInstallations#public-taskvoid-delete) which requires network connectivity to complete the InstanceId deletion. 

There are 2 options to avoid app crashes: 

1. You can handle the `IOException` i.e thrown by [`firebaseInstanceId.deleteInstanceId()`](https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceId#deleteInstanceId()).
2. Integrate with Firebase Installations and directly call [`firebaseInstallations.delete()`](https://firebase.google.com/docs/reference/android/com/google/firebase/installations/FirebaseInstallations#public-taskvoid-delete)

Steps to integrate with  Firebase Installations:

- Add a dependency in your gradle file ` implementation 'com.google.firebase:firebase-installations:$latest_version'`.
- Code snippet for calling `firebaseInstallations.delete()`
```
 FirebaseInstallations.getInstance()
        .delete()
        .addOnCompleteListener(
            new OnCompleteListener<Void>() {
              @Override
              public void onComplete(@NonNull Task<Void> task) {
                if (!task.isSuccessful()) {
                  Log.w(TAG, "delete failed", task.getException());
                }

                Log.i(TAG, "Successfully deleted Instance Id and the associated data.");
              }
            });
```
Please let me know if these steps help.
