### ISSUE TITLE
java.lang.NullPointerException: FirebaseInstanceId.getInstance() return null 

### ISSUE THREAD

**Issue by NhatPham94** [firebase/firebase-android-sdk#1580]
Environment:
  * Android Studio version: 3.6.3
  * Firebase Component: Firebase Cloud Messaging
  * Component version: 20.1.7

### [REQUIRED] Step 3: Describe the problem
I recently got NPE crashes in Crashlytics report cause by FirebaseInstanceId.getInstance():

"Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.firebase.iid.FirebaseInstanceId.b()' on a null object reference"

```
FirebaseInstanceId.getInstance().getInstanceId().addOnSuccessListener(this, instanceIdResult->{});
```

**Comment by ashwinraghav** [comment]
Thanks for reporting. We need some help from you to triage this
1) Full stack trace from Crashlytics
2) Are the crashes happening on specific devices, android versions etc? 
3) Please share the dependencies you are using i.e relevant parts of your gradle file or `./gradlew :app:dependencies`.

**Comment by NhatPham94** [comment]
Sorry for late response.

Devices : itel P33, Samsung Note3, Infinix x572
Android : 5.0, 8.1.0
`com.google.firebase:firebase-messaging:20.1.7`
`com.google.firebase:firebase-installations:16.3.0`
`com.google.firebase:firebase-common:19.3.0`

We have more than 1 apps (>10) with the same source code, but some app doesn't have this issue.

Init in application class : `FirebaseApp.initializeApp(this);`

protected void initGCM() {
FirebaseInstanceId instanceId = FirebaseInstanceId.getInstance();
if (instanceId != null) {
            Task<InstanceIdResult> instanceIdResultTask = instanceId.getInstanceId();
           if (instanceIdResultTask != null) {
                instanceIdResultTask.addOnSuccessListener(this, instanceIdResult -> {
                    //
                });
            }
        }
}
At 1st, I though `instanceId.getInstanceId()` return null but it's not, it's actually from `FirebaseInstanceId.getInstance()` instead.

**Stack Trace**
`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.firebase.iid.FirebaseInstanceId.b()' on a null object reference
       at com.mingle.twine.activities.BaseLogOnActivity.initGCM(BaseLogOnActivity.java:100)
       at com.mingle.twine.activities.BaseLogOnActivity.lambda$afterAuthenticate$348(BaseLogOnActivity.java:148)
       at com.mingle.twine.activities.-$$Lambda$BaseLogOnActivity$alrBHkkSawwTfzeU5SCgr9alMDM.accept(-.java:6)
       at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
       at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
       at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6765)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:449)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)`

**Comment by andirayo** [comment]
I removed `firebase-installations` from Labels. \
I don't think that this is related to FIS. \
@ciarand : Please, feel free to reassign to us.!

**Comment by NhatPham94** [comment]
Any info about this issue? Thanks.

**Comment by aguatno** [comment]
Hi @NhatPham94 Sorry for the long wait here. I'd like to confirm if you're still seeing this issue? I'd recommend using the latest SDK version in your app to ensure old known bugs are fixed.

Thanks!
