### ISSUE TITLE
Fatal Exception: java.lang.AssertionError: No NameTypeIndex match for SHORT_STANDARD

### ISSUE THREAD

**Issue by pnkshir** [firebase/firebase-android-sdk#1581]
Android Studio version: _____3.6
Firebase Component: _____ firebase-messaging
Component version: _____"20.1.0"

We are using firebase for push notifications. We have got this crash for few users repetitively, though we couldn't simulate, this is reported in crashlytics. 

Can you please help us fix this. We got it around for 100 users and getting critical for us. OS Android 7, 8

**Logs :** 

Fatal Exception: java.lang.AssertionError: No NameTypeIndex match for SHORT_STANDARD
       at android.icu.impl.TimeZoneNamesImpl$ZNames.getNameTypeIndex(TimeZoneNamesImpl.java:724)
       at android.icu.impl.TimeZoneNamesImpl$ZNames.getName(TimeZoneNamesImpl.java:790)
       at android.icu.impl.TimeZoneNamesImpl.getTimeZoneDisplayName(TimeZoneNamesImpl.java:183)
       at android.icu.text.TimeZoneNames.getDisplayName(TimeZoneNames.java:261)
       at java.util.TimeZone.getDisplayName(TimeZone.java:405)
       at java.util.Date.toString(Date.java:1066)
       at java.util.Properties.store0(Properties.java:828)
       at java.util.Properties.store(Properties.java:817)
       at com.google.firebase.iid.zzq.zza(zzq.java:82)
       at com.google.firebase.iid.zzq.zzb(zzq.java:8)
       at com.google.firebase.iid.zzq.zza(zzq.java:5)
       at com.google.firebase.iid.zzat.zzb(zzat.java:48)
       at com.google.firebase.iid.FirebaseInstanceId.zzl(FirebaseInstanceId.java:48)
       at com.google.firebase.iid.FirebaseInstanceId.zza(FirebaseInstanceId.java:131)
       at com.google.firebase.iid.zzg.then(zzg.java:1)
       at com.google.android.gms.tasks.zzf.run(zzf.java:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

**Comment by welishr** [comment]
Hi @pnkshir, it looks like the issue is caused from a bug in an underlying library. The newer versions of the SDK remove the calls to the offending code, so upgrading should resolve your issue.

**Comment by pnkshir** [comment]
Hello @welishr Thanks for you reply..We are using following libs: 
"com.google.firebase:firebase-messaging:20.1.7”
"com.google.firebase:firebase-core:9.2.0”
 “com.google.firebase:firebase-perf:19.0.7”

Are you referring to upgrading - com.google.firebase:firebase-messaging:20.2.0 ?

**Comment by welishr** [comment]
Thanks! It looks like the code in question was removed in firebase-messaging: 20.1.1, so I would only expect to see this issue for the builds with 20.1.0 or below.
