### ISSUE TITLE
Firebase messaging method not found 

### ISSUE THREAD

**Issue by rameshwebo** [firebase/firebase-android-sdk#1587]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version:3.6.3
  * Firebase Component: Firebase Messaging
  * Component version:20.0.1

### [REQUIRED] Step 3: Describe the problem

I developed flutter based application which has implemented firestore and
found many crash related to Firebase messaging in firebase crashlytics console . 
crash report as: 

```
Fatal Exception: java.lang.NoSuchMethodError: No static method zza()Lcom/google/firebase/iid/zzaq; in class Lcom/google/firebase/iid/zzaq; or its super classes (declaration of 'com.google.firebase.iid.zzaq' appears in /data/app/com.trackify.app-7rmqxQlxcc918E3eoMoNOA==/base.apk!classes2.dex)
       at com.google.firebase.messaging.FirebaseMessagingService.zza(com.google.firebase:firebase-messaging@@20.0.1:7)
       at com.google.firebase.messaging.zzc.onStartCommand(com.google.firebase:firebase-messaging@@20.0.1:22)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3939)
       at android.app.ActivityThread.access$1800(ActivityThread.java:248)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1861)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7266)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975) 
```

#### Steps to reproduce:

I can't find this crash during debug time but i noted in firebase console

**Comment by ashwinraghav** [comment]
If I had to guess, you maybe using a combination firebase products other than firebase messaging and firestore, that lead to `firebase-iid` getting pinned to an incompatible version. Could you try bumping all firebase products you are using to the latest versions?

If not, are you able to share the versions of all Firebase products you are using?

**Comment by rameshwebo** [comment]
@ashwinraghav  thanks ! i updated all firebase dependencies to latest version . it seems no crash on latest release of my app  since last 2/3 days
