### ISSUE TITLE
Getting Repeated llegalStateException: Unable to obtain an upload URL

### ISSUE THREAD

**Issue by gitton** [firebase/firebase-android-sdk#1598]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category using one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    Google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 3.6.3
  * Firebase Component: com.google.firebase:firebase-storage:19.1.1
  * Component version: _____

### [REQUIRED] Step 3: Describe the problem
Getting Repeated llegalStateException: Unable to obtain an upload URL when trying to upload file with Exception: com.google.firebase.storage.j: The operation retry limit has been exceeded.

#### Steps to reproduce:

What happened? How can we make the problem occur?

Non-fatal Exception: com.google.firebase.storage.j: The operation retry limit has been exceeded.
       at com.google.firebase.storage.UploadTask.w(UploadTask.java:13)
       at com.google.firebase.storage.UploadTask.snapStateImpl(UploadTask.java)
       at com.google.firebase.storage.StorageTask.snapState(StorageTask.java:3)
       at com.google.firebase.storage.StorageTask.getFinalResult(StorageTask.java:17)
       at com.google.firebase.storage.StorageTask.addOnCanceledListener(StorageTask.java)

 Caused by java.lang.IllegalStateException: Unable to obtain an upload URL.
       at com.google.firebase.storage.UploadTask.shouldContinue(UploadTask.java:76)
       at com.google.firebase.storage.UploadTask.run(UploadTask.java:54)
       at com.google.firebase.storage.StorageTask.addOnCanceledListener(StorageTask.java)
       at com.google.firebase.storage.StorageTask$$Lambda$12.run(StorageTask.java:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)

#### Relevant Code:
sorageReference.putFile(uri,metadata)

**Comment by ashwinraghav** [comment]
Thanks for the question.
cc @schmidt-sebastian 
It seems like we throw this error when there is no network as well.
https://github.com/firebase/firebase-android-sdk/blob/29a1573ac1c6b7765aa6ed95ceafc95ec3b670f0/firebase-storage/src/main/java/com/google/firebase/storage/StorageException.java#L81-L82

I think this is a bit odd and we'll take a look. But hopefully it answers your question.

**Comment by gitton** [comment]
Thank you for the response. Using Firebase Realtime Database and Firebase Storage. Realtime database is syncing correctly, Firebase storage is giving this exception while uploading the file
