### ISSUE TITLE
ANRs after updating to Messaging 20.2.0

### ISSUE THREAD

**Issue by edenman** [firebase/firebase-android-sdk#1686]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.2 Canary 2
  * Firebase Components: Messaging, Auth
  * Component version: Messaging 20.2.0, Auth 6.2.0

### [REQUIRED] Step 3: Describe the problem

ANRs reported after updating messaging from 20.1.5 to 20.2.0

#### Steps to reproduce:

Haven't been able to reproduce myself.  Got several ANR reports through Sentry's ANR watchdog.

```
io.sentry.android.core.ApplicationNotResponding: Application Not Responding for at least 4000 ms.
    at android.os.Parcel.nativeWriteString(Parcel.java)
    at android.os.Parcel$ReadWriteHelper.writeString(Parcel.java:366)
    at android.os.Parcel.writeString(Parcel.java:704)
    at android.os.Parcel.writeValue(Parcel.java:1562)
    at android.os.Parcel.writeArrayMapInternal(Parcel.java:867)
    at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1579)
    at android.os.Bundle.writeToParcel(Bundle.java:1233)
    at android.os.Parcel.writeParcelable(Parcel.java:1675)
    at android.os.Parcel.writeParcelableArray(Parcel.java:2631)
    at android.os.Parcel.writeValue(Parcel.java:1625)
    at android.os.Parcel.writeArrayMapInternal(Parcel.java:867)
    at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1579)
    at android.os.Bundle.writeToParcel(Bundle.java:1233)
    at android.os.Parcel.writeBundle(Parcel.java:907)
    at android.app.Notification.writeToParcelImpl(Notification.java:2590)
    at android.app.Notification.writeToParcel(Notification.java:2483)
    at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:1552)
    at android.app.NotificationManager.notifyAsUser(NotificationManager.java:405)
    at android.app.NotificationManager.notify(NotificationManager.java:370)
    at android.app.NotificationManager.notify(NotificationManager.java:346)
    at chat.quill.android.push.QuillFirebaseMessagingService.doShowNotification(QuillFirebaseMessagingService.kt:119)
```
and
```
io.sentry.android.core.ApplicationNotResponding: Application Not Responding for at least 4000 ms.
    at java.util.ArrayDeque.<init>(ArrayDeque.java:171)
    at com.google.android.gms.tasks.zzr.zza
    at com.google.android.gms.tasks.zzu.addOnCompleteListener
    at com.google.firebase.messaging.zzf.onStartCommand(com.google.firebase:firebase-messaging@@20.1.5:30)
    at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3667)
    at android.app.ActivityThread.access$1600(ActivityThread.java:199)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1681)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6669)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
Let me know if there's any more information I can gather.  I'm not doing anything particularly notable in my firebase app setup, just using the `com.google.gms.google-services` plugin and a google services json file, with this in my android manifest:
```
    <service
        android:name=".push.QuillFirebaseMessagingService"
        android:exported="false">
      <intent-filter>
        <action android:name="com.google.firebase.MESSAGING_EVENT" />
      </intent-filter>
    </service>
```

**Comment by edenman** [comment]
Nevermind, I wasn't looking closely enough at the app version# on these ANR reports, does not seem related to the Messaging 20.2.0 update.
