### ISSUE TITLE
FirebaseInstallations: IndexOutOfBoundsException crash

### ISSUE THREAD

**Issue by mtrezza** [firebase/firebase-android-sdk#1695]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

 * Android Studio version: 3.6
  * Device: Moto G4 Play
  * Android Version 6.0
  * Firebase Components:
```
    implementation 'com.google.firebase:firebase-messaging:20.2.1'
    implementation 'com.google.firebase:firebase-analytics:17.4.3'
    implementation 'com.google.firebase:firebase-config:19.1.4'
    implementation 'com.google.firebase:firebase-perf:19.0.7'
    implementation 'com.google.firebase:firebase-crashlytics:17.1.0'
```

### [REQUIRED] Step 3: Describe the problem

App crashes in Firebase Test Lab for Android on that specific device, it did not crash on other devices.

#### Steps to reproduce:

Couldn't reproduce locally.

#### Relevant Code:

```
FATAL EXCEPTION: firebase-installations-executor-١
Process: com.myapp.myapp, PID: 15166
java.lang.IndexOutOfBoundsException: Invalid index 1, size is 1
	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
	at java.util.ArrayList.get(ArrayList.java:308)
	at androidx.test.tools.crawler.SignaturePatchingCallback$1.createFromParcel(SignaturePatchingCallback.java:4)
	at androidx.test.tools.crawler.SignaturePatchingCallback$1.createFromParcel(SignaturePatchingCallback.java:6)
	at android.os.Parcel.createTypedArray(Parcel.java:2167)
	at android.content.pm.PackageInfo.<init>(PackageInfo.java:365)
	at android.content.pm.PackageInfo.<init>(PackageInfo.java)
	at android.content.pm.PackageInfo$1.createFromParcel(PackageInfo.java:332)
	at android.content.pm.PackageInfo$1.createFromParcel(PackageInfo.java:331)
	at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:2166)
	at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:129)
	at com.google.android.gms.common.wrappers.PackageManagerWrapper.getPackageInfo(PackageManagerWrapper.java:5)
	at com.google.android.gms.common.util.AndroidUtilsLight.getPackageCertificateHashBytes(AndroidUtilsLight.java:3)
	at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.getFingerprintHashForPackage(FirebaseInstallationServiceClient.java:501)
	at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.openHttpURLConnection(FirebaseInstallationServiceClient.java:428)
	at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.createFirebaseInstallation(FirebaseInstallationServiceClient.java:152)
	at com.google.firebase.installations.FirebaseInstallations.registerFidWithServer(FirebaseInstallations.java:459)
	at com.google.firebase.installations.FirebaseInstallations.doNetworkCallIfNecessary(FirebaseInstallations.java:331)
	at com.google.firebase.installations.FirebaseInstallations.lambda$doGetId$1(FirebaseInstallations.java:296)
	at com.google.firebase.installations.FirebaseInstallations$$Lambda$3.run(FirebaseInstallations.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
```

**Comment by ankitaj224** [comment]
@mtrezza Thank you so much for reporting this issue. I want to understand if this is a consistent failure on that specific device?

**Comment by ankitaj224** [comment]
Also, could you please identify & confirm which version of `firebase-installations` is used in your app? You could pull it from your app - android dependencies. 

Thank you.

**Comment by mtrezza** [comment]
> Also, could you please identify & confirm which version of `firebase-installations` is used in your app? You could pull it from your app - android dependencies.

As understand it, firebase-installations is added as a transient dependency, so I don't now which version has been added. We are using these dependencies:

```
  implementation 'com.google.firebase:firebase-messaging:20.2.1'
    implementation 'com.google.firebase:firebase-analytics:17.4.3'
    implementation 'com.google.firebase:firebase-config:19.1.4'
    implementation 'com.google.firebase:firebase-perf:19.0.7'
    implementation 'com.google.firebase:firebase-crashlytics:17.1.0'
```

**Comment by ankitaj224** [comment]
Thanks for sharing the details. Your understanding of `firebase-installations` is correct.

I will close this issue as the does not occur anymore.
