### ISSUE TITLE
RuntimeException: WakeLock under-locked wake:com.google.firebase.messaging

### ISSUE THREAD

**Issue by rpattabi** [firebase/firebase-android-sdk#1696]
This bug is closed #1484 but I get the same crash with cloud messaging 20.2.0 (using Firebase BoM 25.4.1)

```
Fatal Exception: java.lang.RuntimeException: WakeLock under-locked wake:com.google.firebase.messaging
       at android.os.PowerManager$WakeLock.release(PowerManager.java:1619)
       at android.os.PowerManager$WakeLock.release(PowerManager.java:1589)
       at android.os.PowerManager$WakeLock$1.run(PowerManager.java:1484)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:101)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7529)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

Same device, same version as reported in #1484. I couldn't add this info to that issues, as it prevents to add any new comments. So submitting as new issue.

**Comment by ashwinraghav** [comment]
Thanks for raising. cc @ciarand
@rpattabi Are you seeing this with version 20.2.1 as well? I don't see a regression to the original fix at our end. Seems like there could be more than one case where this happens.
Are you able to share your dependencies graph? `./gradlew :ap:dependencies`

**Comment by rpattabi** [comment]
@ashwinraghav We'll release the next version of our app with 20.2.1 (or later). Then we'll know if this crash happens for our users. If so I'll update about it here.

Take a look at [this gist](https://gist.github.com/rpattabi/537017a6163ac1c72f11cd2ed809a2ba) for the dependency information, crash stack trace, and device info. This provides dependency graph for firebase in our app. I think this is what you need instead of the full graph.

**Comment by ashwinraghav** [comment]
Thanks for sharing that. Another thing we could use your help with is to confirm that these are indeed the versions that are used by the version of your app that is seeing these exceptions.
we've often found that devs migrate their local builds to higher versions, and attribute faults in their prod apps to versions they currently have. So, worth double checking.

**Comment by rpattabi** [comment]
@ashwinraghav I understand it is easy to get confused about actual version numbers in a complex setup. In this case, I'm pretty sure that this issue results in our production app using firebase cloud messaging 20.2.0 (through Firebase BoM 25.4.1). The dependency tree I shared corresponds to the commit we pushed to production.

As you mentioned, I looked into our app bundle (aab) published to Google Play. It has `base/root/firebase-messaging.properties` with the following contents:

```
version=20.2.0
client=firebase-messaging
firebase-messaging_client=20.2.0
```

Additionally, if it is accessible to you, here is the [crash report](https://console.firebase.google.com/project/shruti-box/crashlytics/app/android:org.kuyil.shrutibox/issues/8af14b7aaa7ca6f168a9570ed1b5302d?time=last-ninety-days&sessionId=5EECEB1003C1000113786FBC16218BEF_DNE_0_v2) in crashlytics.
