### ISSUE TITLE
 Class com.google.firebase.remoteconfig.ktx.FirebaseConfigKtxRegistrar is not an found.

### ISSUE THREAD

**Issue by sonusourav** [firebase/firebase-android-sdk#1697]
### Describe your environment

  * Android Studio version: 4.0
  * Firebase Component: Remote Config
  * Component version: 19.1.4

### Describe the problem
The issue is said to be closed by this [PR](https://github.com/firebase/firebase-android-sdk/pull/1209) but I am still facing the issue.

#### Logs
> 2020-06-22 20:21:34.203 15340-15340/network.matic.wallet.dev.debug W/ComponentDiscovery: Class com.google.firebase.remoteconfig.ktx.FirebaseConfigKtxRegistrar is not an found.
    java.lang.ClassNotFoundException: com.google.firebase.remoteconfig.ktx.FirebaseConfigKtxRegistrar
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:400)
        at java.lang.Class.forName(Class.java:326)
        at com.google.firebase.components.ComponentDiscovery.instantiate(com.google.firebase:firebase-components@@16.0.0:80)
        at com.google.firebase.components.ComponentDiscovery.discover(com.google.firebase:firebase-components@@16.0.0:73)
        at com.google.firebase.FirebaseApp.<init>(com.google.firebase:firebase-common@@19.3.0:404)
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:300)
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:268)
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:253)
        at com.google.firebase.provider.FirebaseInitProvider.onCreate(com.google.firebase:firebase-common@@19.3.0:51)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1761)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1736)
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(com.google.firebase:firebase-common@@19.3.0:45)
        at android.app.ActivityThread.installProvider(ActivityThread.java:5956)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5548)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5487)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6238)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.remoteconfig.ktx.FirebaseConfigKtxRegistrar" on path: DexPathList[[zip file "/data/app/network.matic.wallet.dev.debug-1/base.apk"],nativeLibraryDirectories=[/data/app/network.matic.wallet.dev.debug-1/lib/arm64, /data/app/network.matic.wallet.dev.debug-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:400) 
        at java.lang.Class.forName(Class.java:326) 
        at com.google.firebase.components.ComponentDiscovery.instantiate(com.google.firebase:firebase-components@@16.0.0:80) 
        at com.google.firebase.components.ComponentDiscovery.discover(com.google.firebase:firebase-components@@16.0.0:73) 
        at com.google.firebase.FirebaseApp.<init>(com.google.firebase:firebase-common@@19.3.0:404) 
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:300) 
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:268) 
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:253) 
        at com.google.firebase.provider.FirebaseInitProvider.onCreate(com.google.firebase:firebase-common@@19.3.0:51) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1761) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1736) 
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(com.google.firebase:firebase-common@@19.3.0:45) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:5956) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5548) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5487) 
        at android.app.ActivityThread.-wrap2(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:163) 
        at android.app.ActivityThread.main(ActivityThread.java:6238) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

**Comment by rlazo** [comment]
Hi @sonusourav Thank you for your report! This issue has been reported and fixed in #1209 A new release is coming in the first week of July with the fix included. Sorry for the delay!

**Comment by superdiazzz** [comment]
@rlazo i using     `implementation 'com.google.firebase:firebase-config-ktx:19.1.4` still got the issue. java.lang.ClassNotFoundException: com.google.firebase.remoteconfig.ktx.FirebaseConfigKtxRegistrar 
Any update?

**Comment by rlazo** [comment]
Hi @superdiazzz I should have being a bit more precise on my first comment. This will be fixed on `com.google.firebase:firebase-config-ktx:19.2.0` which will be released early next week (got delayed because of holidays). Thanks!

**Comment by bmc08gt** [comment]
Can confirm this is resolved on `19.2.0`
