### ISSUE TITLE
ANR During  Firebase crashlytics  uncaughtException

### ISSUE THREAD

**Issue by krissGit** [firebase/firebase-android-sdk#1741]
Hi Team,
I have migrated from fabric to Firebase Crashlytics version using version 17.0.0, As per doc 
https://firebase.google.com/docs/crashlytics/get-started?platform=android
To test throw new RuntimeException("Test Crash"); 
During testing Main thread is getting blocked leading towards **ANR.**
Below is ANR logs
**### "main" prio=5 tid=1 Blocked**
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x746c2a48 self=0x7e4697014c00
  | sysTid=9206 nice=-10 cgrp=default sched=0/0 handle=0x7e471c8fd548
  | state=S schedstat=( 8688225491 992173020 4523 ) utm=768 stm=100 core=2 HZ=100
  | stack=0x7ffc6f1e7000-0x7ffc6f1e9000 stackSize=8MB
  | held mutexes=
  at com.google.firebase.crashlytics.internal.common.CrashlyticsController.handleUncaughtException(com.google.firebase:firebase-crashlytics@@17.0.0:-1)
  **- waiting to lock <0x01bf0646> (a com.google.firebase.crashlytics.internal.common.CrashlyticsController) held by thread 21
  at** com.google.firebase.crashlytics.internal.common.CrashlyticsController$5.onUncaughtException(com.google.firebase:firebase-crashlytics@@17.0.0:365)
  at com.google.firebase.crashlytics.internal.common.CrashlyticsUncaughtExceptionHandler.uncaughtException(com.google.firebase:firebase-crashlytics@@17.0.0:54)
  at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
  at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
  at java.lang.Thread.dispatchUncaughtException(Thread.java:1955)

**### "com.google.firebase.crashlytics.startup1" prio=5 tid=21 Waiting**
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x15c414b0 self=0x7e468dc66400
  | sysTid=9245 nice=10 cgrp=default sched=0/0 handle=0x7e467d5f74f0
  | state=S schedstat=( 10660500 10578325 35 ) utm=1 stm=0 core=3 HZ=100
  | stack=0x7e467d4f4000-0x7e467d4f6000 stackSize=1041KB
  | held mutexes=
  at java.lang.Object.wait(Native method)
  - waiting on <0x01a2981e> (a java.lang.Object)
  at java.lang.Thread.parkFor$(Thread.java:2137)
  - locked <0x01a2981e> (a java.lang.Object)
  at sun.misc.Unsafe.park(Unsafe.java:358)
  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:868)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1021)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1328)
  at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:232)
  at com.google.firebase.crashlytics.internal.common.Utils.awaitEvenIfOnMainThread(com.google.firebase:firebase-crashlytics@@17.0.0:185)
  at com.google.firebase.crashlytics.internal.common.CrashlyticsController.handleUncaughtException(com.google.firebase:firebase-crashlytics@@17.0.0:447)
  - **locked <0x01bf0646>** (a com.google.firebase.crashlytics.internal.common.CrashlyticsController)
  at com.google.firebase.crashlytics.internal.common.CrashlyticsController$5.onUncaughtException(com.google.firebase:firebase-crashlytics@@17.0.0:365)
  at com.google.firebase.crashlytics.internal.common.CrashlyticsUncaughtExceptionHandler.uncaughtException(com.google.firebase:firebase-crashlytics@@17.0.0:54)
  at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
  at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
  at java.lang.Thread.dispatchUncaughtException(Thread.java:1955)

**### "com.google.firebase.crashlytics.startup1" prio=5 tid=21 Waiting**
 What is reason of putting lock on Object  <0x01bf0646>  by startup1 thread 
 
Thank you
Krishna

**Comment by mrwillis21** [comment]
Hi @krissGit this is definitely very strange. First things first, can you try out the latest version (17.1.0) of Firebase Crashlytics and see if you get the same behavior? Thanks!

**Comment by krissGit** [comment]
@mrwillis21  Thank you for your response.

  Tried with latest version 17.1.0 still facing same issue.
Can you verify what are things doing in **com.google.firebase.crashlytics.startup1**  thread ,why in this thread **uncaughtException** is getting called. 

    Other firebase Lib version used :
      firebase-abt:19.0.0
       firebase-analytics :17.4.2
       firebase-appindexing:19.1.0
       firebase-common:19.3.0
       firebase-components:16.0.0
       firebase-config:19.0.4
       firebase-core:17.4.2
       **firebase-crashlytics:17.1.0**
       firebase-datatransport:17.0.3
       firebase-encoder-json:16.1.0
       firebase-iid:20.2.0
       firebase-iid-interop:17.0.0
       firebase-installation:16.3.1
       firebase-installation-interop:17.0.0
       firebase-measurement-connector:18.0.0
       firebase-messaging:20.2.0
       firebase-ml-vision-24.0.3
       firebase-pref:19.0.7

Thank you.

**Comment by krissGit** [comment]
### Adding some more logs **FATAL EXCEPTION: com.google.firebase.crashlytics.startup1**

2020-07-02 17:57:06.982 30746-30795 E/AndroidRuntime: **FATAL EXCEPTION: com.google.firebase.crashlytics.startup1**
    Process:  PID: 30746
    java.lang.NoSuchMethodError: No virtual method callTimeout(JLjava/util/concurrent/TimeUnit;)Lokhttp3/OkHttpClient$Builder; in class Lokhttp3/OkHttpClient$Builder; or its super classes (declaration of 'okhttp3.OkHttpClient$Builder
        at com.google.firebase.crashlytics.internal.network.HttpRequest.<clinit>(HttpRequest.java:46)
        at com.google.firebase.crashlytics.internal.network.HttpRequestFactory.buildHttpRequest(HttpRequestFactory.java:43)
        at com.google.firebase.crashlytics.internal.common.AbstractSpiCall.getHttpRequest(AbstractSpiCall.java:113)
        at com.google.firebase.crashlytics.internal.settings.network.DefaultSettingsSpiCall.invoke(DefaultSettingsSpiCall.java:80)
        at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:200)
        at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:193)
        at com.google.android.gms.tasks.zzp.run(com.google.android.gms:play-services-tasks@@17.0.2:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:60)
        at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:27)
        at java.lang.Thread.run(Thread.java:764)
2020

**Comment by krissGit** [comment]
Above issue solved that is due to ok http version mismatch.

**Comment by mrwillis21** [comment]
@krissGit Glad this is sorted! Can you give me a little more information on what the issue was so we can make sure to be aware of it in the future?

**Comment by eyalsolodki** [comment]
Hi KrissGit,

Please - I need your help. the same you described happens to me - no Crashlytics are even shown in the Firebase Monitor.
what do you mean "Above issue solved that is due to ok http version mismatch"?

mismatch with what?

Thanks

Eyal

**Comment by eyalsolodki** [comment]
@krissGit - need your help - please look at the post above

**Comment by UvarovBoris** [comment]
Hello guys. Have same issue. After migrating to firebase-crashlytics  have many ANR's in google play console.

  at com.google.firebase.crashlytics.internal.common.Utils.awaitEvenIfOnMainThread (Utils.java:191)
  at com.google.firebase.crashlytics.internal.common.CrashlyticsController.handleUncaughtException (CrashlyticsController.java:448)
- locked <0x0dd0363e> (a com.google.firebase.crashlytics.c.g.j)
  at com.google.firebase.crashlytics.internal.common.CrashlyticsController$5.onUncaughtException (CrashlyticsController.java:365)
  at com.google.firebase.crashlytics.internal.common.CrashlyticsUncaughtExceptionHandler.uncaughtException (CrashlyticsUncaughtExceptionHandler.java:54)
  at com.facebook.ads.redexgen.X.IY.A03 (IY.java:29120)
  at com.facebook.ads.redexgen.X.IY.uncaughtException (IY.java:29143)
  at org.chromium.base.JavaExceptionReporter.uncaughtException (JavaExceptionReporter.java:6)
  at com.flurry.sdk.ew$a.uncaughtException (ew.java:2088)
  at com.soomla.traceback.i.x$2.uncaughtException (x.java:97)
  at java.lang.ThreadGroup.uncaughtException (ThreadGroup.java:1073)
  at java.lang.ThreadGroup.uncaughtException (ThreadGroup.java:1068)
  at java.lang.Thread.dispatchUncaughtException (Thread.java:2187)

What about "ok http version mismatch". What this mean ?

**Comment by eyalsoiforex** [comment]
Hi @UvarovBoris ,

I fixed the problem - in my case it meant that I use the OKHttp Network module in my app, for a seperate thread. Anyhow - it seems that the new Firebase uses also this module.
I needed to upgrade the OKHttp to the latest version, probably the same as in Firebase
