### ISSUE TITLE
Storage - Error while resuming upload

### ISSUE THREAD

**Issue by anshulg03** [firebase/firebase-android-sdk#1743]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: _____
  * Firebase Component: Storage (Database, Firestore, Storage, Functions, etc)
  * Component version: 19.1.1

### [REQUIRED] Step 3: Describe the problem
When resuming an upload after getting back network connectivity the following error shows up.

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
```
W/NetworkRequest: error sending network request POST null
    java.net.MalformedURLException: no protocol: null
        at java.net.URL.<init>(URL.java:601)
        at java.net.URL.<init>(URL.java:498)
        at java.net.URL.<init>(URL.java:447)
        at com.google.firebase.storage.network.NetworkRequest.createConnection(com.google.firebase:firebase-storage@@19.1.1:316)
        at com.google.firebase.storage.network.NetworkRequest.performRequestStart(com.google.firebase:firebase-storage@@19.1.1:246)
        at com.google.firebase.storage.network.NetworkRequest.performRequest(com.google.firebase:firebase-storage@@19.1.1:270)
        at com.google.firebase.storage.network.NetworkRequest.performRequest(com.google.firebase:firebase-storage@@19.1.1:286)
        at com.google.firebase.storage.internal.ExponentialBackoffSender.sendWithExponentialBackoff(com.google.firebase:firebase-storage@@19.1.1:103)
        at com.google.firebase.storage.internal.ExponentialBackoffSender.sendWithExponentialBackoff(com.google.firebase:firebase-storage@@19.1.1:62)
        at com.google.firebase.storage.UploadTask.sendWithRetry(com.google.firebase:firebase-storage@@19.1.1:467)
        at com.google.firebase.storage.UploadTask.recoverStatus(com.google.firebase:firebase-storage@@19.1.1:355)
        at com.google.firebase.storage.UploadTask.shouldContinue(com.google.firebase:firebase-storage@@19.1.1:317)
        at com.google.firebase.storage.UploadTask.run(com.google.firebase:firebase-storage@@19.1.1:221)
        at com.google.firebase.storage.StorageTask.lambda$getRunnable$7(com.google.firebase:firebase-storage@@19.1.1:1072)
        at com.google.firebase.storage.StorageTask$$Lambda$12.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
``````

**Comment by ashwinraghav** [comment]
Thanks for reporting @anshulg03 . Are you able to consistently repro the issue ? Is there a sample project you have that we can try out ?

**Comment by anshulg03** [comment]
Yes whenever I test the app for an unstable network by turning the data connectivity on and off while the upload is in progress, I am facing this issue.

The error keeps on appearing until I kill the app. 

I will try and write a short snippet to reproduce the issue.

**Comment by schmidt-sebastian** [comment]
@anshulg03 The Upload URL that is used to resume the upload is extracted from the HTTP header that was sent to us last: https://github.com/firebase/firebase-android-sdk/blob/e95f91e64c79206549302e9f37341534c29f58af/firebase-storage/src/main/java/com/google/firebase/storage/UploadTask.java#L273

Are you behind a Proxy that may adjust these values?

**Comment by anshulg03** [comment]
> @anshulg03 The Upload URL that is used to resume the upload is extracted from the HTTP header that was sent to us last:
> 
> https://github.com/firebase/firebase-android-sdk/blob/e95f91e64c79206549302e9f37341534c29f58af/firebase-storage/src/main/java/com/google/firebase/storage/UploadTask.java#L273
> 
> Are you behind a Proxy that may adjust these values?

Nope, there is no proxy.  @schmidt-sebastian

**Comment by lehcar09** [comment]
Hi @anshulg03, sorry for the silence here. Just bumping this thread. Are you still experiencing this issue in the latest Firebase SDK version (34.11.0)? 

I tried reproducing the issue using an emulator with "GSM" to "LTE" network type, but I wasn't able to encounter this error, instead I'm getting the error message below: 

```
Error sending network request POST https://firebasestorage.googleapis.com/v0/b/...
java.io.IOException: unexpected end of stream on com.android.okhttp.Address@5046580a
...
Caused by: java.io.EOFException: \n not found: size=0 content=...
...
app_time_stats: avg=15.11ms min=4.65ms max=37.44ms count=38
network unavailable, sleeping.
```
