### ISSUE TITLE
False failure of a batch update

### ISSUE THREAD

**Issue by maclir** [firebase/firebase-android-sdk#1789]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.0.1
  * Firebase Component: Firestore
  * Component version: ktx-21.5.0

### [REQUIRED] Step 3: Describe the problem

When doing a batch update I get an exception as follows:

```log
    com.google.firebase.firestore.FirebaseFirestoreException: PERMISSION_DENIED: Missing or insufficient permissions.
        at com.google.firebase.firestore.util.Util.exceptionFromStatus(Util.java:117)
        at com.google.firebase.firestore.core.SyncEngine.notifyUser(SyncEngine.java:521)
        at com.google.firebase.firestore.core.SyncEngine.handleRejectedWrite(SyncEngine.java:451)
        at com.google.firebase.firestore.core.MemoryComponentProvider$RemoteStoreCallback.handleRejectedWrite(MemoryComponentProvider.java:109)
        at com.google.firebase.firestore.remote.RemoteStore.handleWriteError(RemoteStore.java:709)
        at com.google.firebase.firestore.remote.RemoteStore.handleWriteStreamClose(RemoteStore.java:665)
        at com.google.firebase.firestore.remote.RemoteStore.access$600(RemoteStore.java:53)
        at com.google.firebase.firestore.remote.RemoteStore$2.onClose(RemoteStore.java:206)
        at com.google.firebase.firestore.remote.AbstractStream.close(AbstractStream.java:344)
        at com.google.firebase.firestore.remote.AbstractStream.handleServerClose(AbstractStream.java:398)
        at com.google.firebase.firestore.remote.AbstractStream$StreamObserver.lambda$onClose$3(AbstractStream.java:151)
        at com.google.firebase.firestore.remote.AbstractStream$StreamObserver$$Lambda$4.run(Unknown Source:4)
        at com.google.firebase.firestore.remote.AbstractStream$CloseGuardedRunner.run(AbstractStream.java:67)
        at com.google.firebase.firestore.remote.AbstractStream$StreamObserver.onClose(AbstractStream.java:137)
        at com.google.firebase.firestore.remote.FirestoreChannel$1.onClose(FirestoreChannel.java:135)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
        at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:689)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$900(ClientCallImpl.java:577)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:751)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:740)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:229)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: io.grpc.StatusException: PERMISSION_DENIED: Missing or insufficient permissions.
        at io.grpc.Status.asException(Status.java:541)
        at com.google.firebase.firestore.util.Util.exceptionFromStatus(Util.java:115)
        at com.google.firebase.firestore.core.SyncEngine.notifyUser(SyncEngine.java:521) 
        at com.google.firebase.firestore.core.SyncEngine.handleRejectedWrite(SyncEngine.java:451) 
        at com.google.firebase.firestore.core.MemoryComponentProvider$RemoteStoreCallback.handleRejectedWrite(MemoryComponentProvider.java:109) 
        at com.google.firebase.firestore.remote.RemoteStore.handleWriteError(RemoteStore.java:709) 
        at com.google.firebase.firestore.remote.RemoteStore.handleWriteStreamClose(RemoteStore.java:665) 
        at com.google.firebase.firestore.remote.RemoteStore.access$600(RemoteStore.java:53) 
        at com.google.firebase.firestore.remote.RemoteStore$2.onClose(RemoteStore.java:206) 
        at com.google.firebase.firestore.remote.AbstractStream.close(AbstractStream.java:344) 
        at com.google.firebase.firestore.remote.AbstractStream.handleServerClose(AbstractStream.java:398) 
        at com.google.firebase.firestore.remote.AbstractStream$StreamObserver.lambda$onClose$3(AbstractStream.java:151) 
        at com.google.firebase.firestore.remote.AbstractStream$StreamObserver$$Lambda$4.run(Unknown Source:4) 
        at com.google.firebase.firestore.remote.AbstractStream$CloseGuardedRunner.run(AbstractStream.java:67) 
        at com.google.firebase.firestore.remote.AbstractStream$StreamObserver.onClose(AbstractStream.java:137) 
        at com.google.firebase.firestore.remote.FirestoreChannel$1.onClose(FirestoreChannel.java:135) 
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426) 
        at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66) 
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:689) 
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$900(ClientCallImpl.java:577) 
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:751) 
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:740) 
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) 
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:229) 
        at java.lang.Thread.run(Thread.java:919) 

```

But the operation has actually been **successful**, and data is set on firestore and I can see it in the console.

Seems to be a false negative.

#### Relevant Code:

I am doing a simple batch update like: 
```kotlin
fs.runBatch { batch ->
            batch.set(newGameRef,
                    Game(
...
                    ))
            val userOpponentRef = fs.collection(Collection.USERS).document(user.id).collection(Collection.OPPONENTS).document(opponentId)
            batch.update(userOpponentRef, Opponent.FIELD_HAS_ONGOING_GAME, true)
            if (user.id != opponentId) {
                val opponentUserRef = fs.collection(Collection.USERS).document(opponentId).collection(Collection.OPPONENTS).document(user.id)
                batch.update(opponentUserRef, Opponent.FIELD_HAS_ONGOING_GAME, true)
            }
        }
                .addOnSuccessListener { Timber.d("$randomInt SUCCESS") }
                .addOnFailureListener { e -> Timber.e(e, "$randomInt Adding new game failed.") }
                .addOnCompleteListener { task -> Timber.d("$randomInt COMPLETE $task") }
```

**Comment by schmidt-sebastian** [comment]
Assigning to current on call.

**Comment by rafikhan** [comment]
@maclir - Can you please [enable logging in Firestore](https://gist.github.com/katowulf/0475fb7a5907ed757f687aab6ed15878) and re-run this query so we can better diagnose this? Thank you.

**Comment by maclir** [comment]
Will do in a few days.

**Comment by maclir** [comment]
Now I cannot reproduce it anymore. Has something been fixed/changed?

**Comment by wilhuff** [comment]
I'm not aware of any changes on our side, but there are quite a few systems involved in serving Firestore's backend that we don't directly control. If you are able to reproduce, we'll investigate futher.
