### ISSUE TITLE
Crash after updating to 20.2.3

### ISSUE THREAD

**Issue by nekohasekai** [firebase/firebase-android-sdk#1798]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.1
  * Firebase Component: Cloud Messaging, Crashlytics
  * Component version: 20.2.3

### [REQUIRED] Step 3: Describe the problem

```
Fatal Exception: java.lang.AbstractMethodError: abstract method "com.google.android.gms.tasks.Task com.google.firebase.iid.WithinAppServiceBinder$IntentHandler.zza(android.content.Intent)"
       at com.google.firebase.iid.WithinAppServiceBinder.zza(com.google.firebase:firebase-iid@@20.2.2:9)
       at com.google.firebase.iid.zzaw.zza(com.google.firebase:firebase-iid@@20.2.2:30)
       at com.google.firebase.iid.zzaw.onServiceConnected(com.google.firebase:firebase-iid@@20.2.2:59)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1738)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1770)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:201)
       at android.app.ActivityThread.main(ActivityThread.java:6861)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

![image](https://user-images.githubusercontent.com/56506714/88050122-d6ebf480-cb88-11ea-90a4-352c200fe424.png)

#### Steps to reproduce:

After updating the sdk to 20.2.3

#### Relevant Code:

idk

**Comment by ashwinraghav** [comment]
The stack trace seems to indicate that the version being used is [20.2.2](https://firebase.google.com/support/release-notes/android#iid_v20-2-3). We had some critical fixes go into [20.2.3.](https://firebase.google.com/support/release-notes/android#messaging_v20-2-3) Please upgrade to the latest versions.
