### ISSUE TITLE
FirebaseInAppMessagingDisplay WindowManager$BadTokenException

### ISSUE THREAD

**Issue by jakubzieba** [firebase/firebase-android-sdk#1808]
* Android Studio version: 4.0
  * Firebase Component: InAppMessaging
  * Component version: 19.0.7

Hi, I noticed in firebase crashlytics console a crash

Fatal Exception: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
       at android.view.ViewRootImpl.setView(ViewRootImpl.java:945)
       at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:387)
       at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:95)
       at com.google.firebase.inappmessaging.display.internal.FiamWindowManager.show(FiamWindowManager.java:62)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay$4$4.run(FirebaseInAppMessagingDisplay.java:418)
       at android.app.Activity.runOnUiThread(Activity.java:6912)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay$4.onSuccess(FirebaseInAppMessagingDisplay.java:414)
       at com.squareup.picasso.ImageViewAction.complete(ImageViewAction.java:52)
       at com.squareup.picasso.Picasso.deliverAction(Picasso.java:576)
       at com.squareup.picasso.Picasso.complete(Picasso.java:528)
       at com.squareup.picasso.Picasso$1.handleMessage(Picasso.java:122)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:241)
       at android.app.ActivityThread.main(ActivityThread.java:7617)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)

At this moment i see only one occurrence on  "motorola one vision" Android 10. Unfortunately I don't know how to recreate it :/

**Comment by jakubzieba** [comment]
I notice same crash on two additional devices
![image](https://user-images.githubusercontent.com/8668110/88905738-e50bd600-d256-11ea-83d6-b20ad7a2b228.png)
![image](https://user-images.githubusercontent.com/8668110/88905823-053b9500-d257-11ea-9003-5bb05a549a1c.png)

**Comment by mzgreen** [comment]
I'm also experiencing this on multiple devices.

**Comment by premacck** [comment]
I'm also experiencing this issue on multiple devices: Samsung, Xiaomi & Vivo, Android 6, 9 & 10

**Comment by stari4ek** [comment]
I'm also getting it:
```
Fatal Exception: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
       at android.view.ViewRootImpl.setView(ViewRootImpl.java:907)
       at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:387)
       at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:95)
       at com.google.firebase.inappmessaging.display.internal.FiamWindowManager.show(FiamWindowManager.java:62)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay$4$4.run(FirebaseInAppMessagingDisplay.java:412)
       at android.app.Activity.runOnUiThread(Activity.java:6919)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay$4.onSuccess(FirebaseInAppMessagingDisplay.java:408)
       at com.squareup.picasso.RequestCreator.into(RequestCreator.java:721)
       at com.google.firebase.inappmessaging.display.internal.FiamImageLoader$FiamImageRequestCreator.into(FiamImageLoader.java:65)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay.loadNullableImage(FirebaseInAppMessagingDisplay.java:490)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay.inflateBinding(FirebaseInAppMessagingDisplay.java:346)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay.access$000(FirebaseInAppMessagingDisplay.java:80)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay$1.run(FirebaseInAppMessagingDisplay.java:288)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7356)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

It looks like implementation schedules it for main thread but it does not check/track if activity is still alive, so it's :
```
66 | Thu Nov 26 2020 10:36:41 GMT+0300 (Moscow Standard Time) | main|T] MainMenuActivity: onPause() called
67 | Thu Nov 26 2020 10:36:41 GMT+0300 (Moscow Standard Time) | main|T] MainMenuActivity: onDestroy() called
68 | Thu Nov 26 2020 10:36:41 GMT+0300 (Moscow Standard Time) | main|E] UncaughtExceptionHandler: Uncaught exception android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running? 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:907) 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:387) 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:95) 	at d.e.e.t.c0.e$d.run(FirebaseInAppMessagingDisplay.java:24) 	at android.app.Activity.runOnUiThread(Activity.java:6919) 	at d.e.e.t.c0.e.a(FirebaseInAppMessagingDisplay.java:16) 	at d.i.c.w.b(RequestCreator.java:58) 	at d.e.e.t.c0.b$a.run(FirebaseInAppMessagingDisplay.java:59) 	at android.os.Handler.handleCallback(Handler.java:883) 	at android.os.Handler.dispatchMessage(Handler.java:100) 	at android.os.Looper.loop(Looper.java:214) 	at android.app.ActivityThread.main(ActivityThread.java:7356)
```

**Comment by zjamshidi** [comment]
I'm seeing the same crash on Firebase Crashlytics LG K11 Android 7.1.2

**Comment by PetkevichPavel** [comment]
@JasonAHeron This issue is duplicating mine BUG which I created earlier, please close it and we can continue in my thread (#1694). Thank you in advance! 

@jakubzieba you can continue follow all changes according to this BUG in this thread: #1694.
