### ISSUE TITLE
Firebase Installations getId Task has timed out

### ISSUE THREAD

**Issue by NayaneshGupte** [firebase/firebase-android-sdk#1826]
### [READ] Step 1: Are you in the right place?

Yes

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 3.6
  * Firebase Component: Installation /performance
  * Component version: (performance )19.0.7

### [REQUIRED] Step 3: Describe the problem
Fatal Exception: java.lang.IllegalThreadStateException
Firebase Installations getId Task has timed out.

Fatal Exception: java.lang.IllegalThreadStateException: Firebase Installations getId Task has timed out.
       at com.google.firebase.iid.FirebaseInstanceId.zzl(FirebaseInstanceId.java:83)
       at com.google.firebase.iid.FirebaseInstanceId.getId(FirebaseInstanceId.java:49)
       at com.google.firebase.perf.internal.zzd.zzbu(zzd.java:181)
       at com.google.firebase.perf.internal.zzd.zzbt(zzd.java:44)
       at com.google.firebase.perf.internal.zzd.zzc(zzd.java:195)
       at com.google.firebase.perf.internal.zzg.run(zzg.java:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)

#### Steps to reproduce:

Not able to reproduce but seeing lot of crashes in  firebase crashlytics.

**Comment by ankitaj224** [comment]
@NayaneshGupte Thanks for reporting this issue. Can you please upgrade to the latest version of Fireperf -19.0.8 and let us know if the issue persists.
