### ISSUE TITLE
Firebase Perf crashes on app startup and potentially causes ANRs

### ISSUE THREAD

**Issue by SUPERCILEX** [firebase/firebase-android-sdk#183]
### [REQUIRED] Step 2: Describe your environment

  * Firebase Component: Firebase Perf
  * Component version: 16.2.3

### [REQUIRED] Step 3: Describe the problem

Possibly related to #126

Stacktrace:

```
Fatal Exception: java.lang.ExceptionInInitializerError
       at com.google.android.gms.internal.firebase-perf.zzhy.<clinit>(zzhy.java:11)
       at com.google.android.gms.internal.firebase-perf.zzht.<clinit>(zzht.java:9)
       at com.google.android.gms.internal.firebase-perf.zzcy$zzb.<clinit>(zzcy.java:1)
       at com.google.android.gms.internal.firebase-perf.zzcy.zza(zzcy.java:103)
       at com.google.android.gms.internal.firebase-perf.zzeo.zzb(zzeo.java:10)
       at com.google.android.gms.internal.firebase-perf.zzfp.zzb(zzfp.java:11)
       at com.google.android.gms.internal.firebase-perf.zzfn.zzd(zzfn.java:10)
       at com.google.android.gms.internal.firebase-perf.zzgk.zze(zzgk.java:5)
       at com.google.android.gms.internal.firebase-perf.zzgk.zzn(zzgk.java:14)
       at com.google.android.gms.internal.firebase-perf.zzep$zza.zzhv(zzep.java:22)
       at com.google.android.gms.internal.firebase-perf.zzep$zza.zzhx(zzep.java:57)
       at com.google.android.gms.internal.firebase-perf.zzep$zza.zzhw(zzep.java:25)
       at com.google.android.gms.internal.firebase-perf.zzep$zza.zzhy(zzep.java:58)
       at com.google.firebase.perf.metrics.AppStartTrace.onActivityResumed(AppStartTrace.java:73)
       at android.app.Application.dispatchActivityResumed(Application.java:239)
       at android.app.Activity.onResume(Activity.java:1343)
       at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:514)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1412)
       at android.app.Activity.performResume(Activity.java:7300)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3777)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3817)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6680)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by java.lang.NullPointerException: throw with null exception
       at com.google.android.gms.internal.firebase-perf.zzdl.<clinit>(zzdl.java:3)
       at com.google.android.gms.internal.firebase-perf.zzhy.<clinit>(zzhy.java:11)
       at com.google.android.gms.internal.firebase-perf.zzht.<clinit>(zzht.java:9)
       at com.google.android.gms.internal.firebase-perf.zzcy$zzb.<clinit>(zzcy.java:1)
       at com.google.android.gms.internal.firebase-perf.zzcy.zza(zzcy.java:103)
       at com.google.android.gms.internal.firebase-perf.zzeo.zzb(zzeo.java:10)
       at com.google.android.gms.internal.firebase-perf.zzfp.zzb(zzfp.java:11)
       at com.google.android.gms.internal.firebase-perf.zzfn.zzd(zzfn.java:10)
       at com.google.android.gms.internal.firebase-perf.zzgk.zze(zzgk.java:5)
       at com.google.android.gms.internal.firebase-perf.zzgk.zzn(zzgk.java:14)
       at com.google.android.gms.internal.firebase-perf.zzep$zza.zzhv(zzep.java:22)
       at com.google.android.gms.internal.firebase-perf.zzep$zza.zzhx(zzep.java:57)
       at com.google.android.gms.internal.firebase-perf.zzep$zza.zzhw(zzep.java:25)
       at com.google.android.gms.internal.firebase-perf.zzep$zza.zzhy(zzep.java:58)
       at com.google.firebase.perf.metrics.AppStartTrace.onActivityResumed(AppStartTrace.java:73)
       at android.app.Application.dispatchActivityResumed(Application.java:239)
       at android.app.Activity.onResume(Activity.java:1343)
       at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:514)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1412)
       at android.app.Activity.performResume(Activity.java:7300)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3777)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3817)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6680)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by SUPERCILEX** [comment]
Nvm, it's R8: https://issuetracker.google.com/issues/120277396
