### ISSUE TITLE
FirebaseRemoteConfig.getInstance() causing Null pointer exception

### ISSUE THREAD

**Issue by iambaljeet** [firebase/firebase-android-sdk#1838]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.0.1
  * Firebase Component: Remote Config
  * Component version: firebase-bom:25.6.0

### [REQUIRED] Step 3: Describe the problem

I am getting this exception 
`Attempt to invoke virtual method 'com.google.firebase.remoteconfig.FirebaseRemoteConfig com.google.firebase.remoteconfig.RemoteConfigComponent.getDefault()' on a null object reference`
Everytime I try to initialize `RemoteConfig` for my project

#### Steps to reproduce:
I added Remote config in 'build.gradle'

    implementation platform('com.google.firebase:firebase-bom:25.6.0')
    implementation'com.google.firebase:firebase-messaging'
    implementation'com.google.firebase:firebase-firestore-ktx'
    implementation'com.google.firebase:firebase-storage-ktx'
    implementation'com.google.firebase:firebase-analytics-ktx'
    implementation'com.google.firebase:firebase-crashlytics'
    implementation'com.google.firebase:firebase-auth'
    implementation'com.google.firebase:firebase-config-ktx'

Everything else works fine just remote config crashes. I have even tried using

    implementation 'com.google.firebase:firebase-config'

But still getting the same error. I have tried adding below snippet for ktx version.

```
<meta-data
android:name="com.google.firebase.components:com.google.firebase.remoteconfig.ktx.FirebaseRemoteConfigKtxRegistrar"
                android:value="com.google.firebase.components.ComponentRegistrar" />
```

Also tried adding below snippet for a generic version of remote config

```
<meta-data
                android:name="com.google.firebase.components:com.google.firebase.remoteconfig.RemoteConfigRegistrar"
                android:value="com.google.firebase.components.ComponentRegistrar" />
```

What happened? How can we make the problem occur?

**Stack trace:**

```
2020-07-31 18:40:39.233 14078-14078/com.campus365.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.campus365.app, PID: 14078
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.campus365.app/home.ui.splash.SplashActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.firebase.remoteconfig.FirebaseRemoteConfig com.google.firebase.remoteconfig.RemoteConfigComponent.getDefault()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3374)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3513)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.firebase.remoteconfig.FirebaseRemoteConfig com.google.firebase.remoteconfig.RemoteConfigComponent.getDefault()' on a null object reference
        at com.google.firebase.remoteconfig.FirebaseRemoteConfig.getInstance(FirebaseRemoteConfig.java:87)
        at com.google.firebase.remoteconfig.FirebaseRemoteConfig.getInstance(FirebaseRemoteConfig.java:81)
        at home.utils.FirebaseUpdateCheck.checkUpdateAndProceed(FirebaseUpdateCheck.kt:16)
        at home.ui.splash.SplashActivity.onCreate(SplashActivity.kt:29)
        at android.app.Activity.performCreate(Activity.java:7815)
        at android.app.Activity.performCreate(Activity.java:7804)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1318)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3349)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3513) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7682) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) 
```

**Merged Manifest:** 

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.campus365.app"
    android:versionCode="33"
    android:versionName="5.8" >

    <uses-sdk
        android:minSdkVersion="21"
        android:targetSdkVersion="29" />

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.READ_CALENDAR" />
    <uses-permission android:name="android.permission.WRITE_CALENDAR" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.CALL_PHONE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.BIND_TELECOM_CONNECTION_SERVICE" />
    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.MANAGE_OWN_CALLS" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />

    <uses-feature
        android:glEsVersion="0x00020000"
        android:required="true" />
    <uses-feature
        android:name="android.hardware.camera"
        android:required="false" />
    <uses-feature
        android:name="android.hardware.camera.autofocus"
        android:required="false" />

    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" /> 
    <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
    <uses-permission android:name="com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE" />

    <uses-feature
        android:name="android.hardware.telephony"
        android:required="false" />
    <uses-feature
        android:name="android.hardware.bluetooth"
        android:required="false" />
    <uses-feature
        android:name="android.hardware.microphone"
        android:required="false" />

    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
    <uses-permission android:name="android.permission.BROADCAST_STICKY" />
    <uses-permission android:name="android.permission.REORDER_TASKS" />

    <application
        android:name="com.campus365.app.utils.MyApp"
        android:allowBackup="false"
        android:backupInForeground="false"
        android:debuggable="true"
        android:fullBackupContent="false"
        android:fullBackupOnly="false"
        android:icon="@drawable/campus_logo_light"
        android:label="@string/app_name_campus"
        android:largeHeap="true"
        android:requestLegacyExternalStorage="true"
        android:roundIcon="@drawable/campus_logo_light"
        android:supportsRtl="true"
        android:testOnly="true"
        android:theme="@style/AppTheme"
        android:usesCleartextTraffic="true" >
        <activity android:name="com.zipow.videobox.JoinByURLActivity" />
        <activity android:name="com.zipow.videobox.ConfActivityNormal" />
        <activity
            android:name="home.ui.studentselector.StudentSelectorActivity"
            android:screenOrientation="portrait" />
        <activity
            android:name="home.ui.downloadcenter.activity.DownloadCenterActivity"
            android:screenOrientation="portrait" />
        <activity android:name="home.ui.livevideo.LiveVideoActivity" />
        <activity android:name="org.jitsi.meet.sdk.JitsiMeetActivity" />
        <activity
            android:name="home.ui.splash.SplashActivity"
            android:screenOrientation="portrait"
            android:theme="@style/AppThemeSplash" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity android:name="home.ui.addreminder.activity.AddReminder" />
        <activity
            android:name="home.ui.feepayment.activity.FeeReceiptActivity"
            android:screenOrientation="portrait"
            android:theme="@style/PaymentTheme" />
        <activity
            android:name="home.utils.WebViewScreen"
            android:screenOrientation="portrait"
            android:theme="@style/App2Theme" />
        <activity
            android:name="home.ui.feepayment.activity.FeePaymentActivity"
            android:launchMode="singleTop"
            android:screenOrientation="portrait"
            android:theme="@style/PaymentTheme" />
        <activity android:name="home.ui.documentviewer.DocumentViewerWebViewActivity" />
        <activity
            android:name="home.ui.profile.activity.UpdateStatusActivity"
            android:screenOrientation="portrait"
            android:theme="@style/App2Theme"
            android:windowSoftInputMode="adjustResize" />
        <activity
            android:name="home.ui.login.activity.UpdateEmailActivity"
            android:screenOrientation="portrait"
            android:theme="@style/App2Theme"
            android:windowSoftInputMode="adjustResize|stateHidden" />
        <activity
            android:name="home.ui.login.activity.LoginActivity"
            android:screenOrientation="portrait"
            android:theme="@style/App2Theme"
            android:windowSoftInputMode="adjustPan" /> 
        <activity
            android:name="home.ui.fullscreenimageviewer.FullScreenImageViewerActivity"
            android:screenOrientation="portrait"
            android:theme="@style/AppTheme.Draggable" />
        <activity
            android:name="com.campus365.app.students.NotificationList"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.campus365.app.students.StudentOnlineExamQuestionsNew"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.campus365.app.students.StudentOnlineExamResult"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.campus365.app.students.StudentOnlineExam"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.campus365.app.payments.Payments"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.campus365.app.AboutSchool"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.campus365.app.students.StudentTimeline"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.campus365.app.students.StudentDocuments"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.campus365.app.SplashActivity"
            android:screenOrientation="portrait" />
        <activity
            android:name="home.view.HomeActivity"
            android:launchMode="singleTask"
            android:screenOrientation="portrait"
            android:windowSoftInputMode="adjustResize" />
        <activity
            android:name="home.ui.login.WelcomeActivity"
            android:launchMode="singleTask"
            android:noHistory="true"
            android:screenOrientation="portrait"
            android:theme="@style/App2Theme"
            android:windowSoftInputMode="adjustResize" />
        <activity
            android:name="com.campus365.app.Login"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.campus365.app.students.StudentProfile"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.campus365.app.students.StudentProfileNew"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.campus365.app.students.StudentProfileDetailsNew"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.campus365.app.students.StudentUploadHomework"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.campus365.app.ForgotPassword"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.campus365.app.BaseActivity"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.campus365.app.students.StudentFees"
            android:screenOrientation="portrait" >
            <intent-filter>
                <category android:name="android.intent.category.DEFAULT" />

                <action android:name="android.intent.action.VIEW" />

                <data android:scheme="student_fees" />
            </intent-filter>
        </activity>
        <activity
            android:name="com.campus365.app.students.StudentNoticeBoard"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.campus365.app.students.StudentSubject"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.campus365.app.students.StudentExaminationList"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.campus365.app.students.StudentReportCard_ExamListResult"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.campus365.app.students.StudentSubjectList"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.campus365.app.students.StudentChat"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.campus365.app.students.StudentTeachersList"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.campus365.app.students.StudentTransportRoutes"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.campus365.app.students.StudentDownloads"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.campus365.app.students.StudentAttendance"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.campus365.app.students.StudentReportCard_ExamList"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.campus365.app.students.StudentReportCard_ExamResult"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.campus365.app.students.StudentExamSchedule_ExamList"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.campus365.app.students.StudentExamSchedule"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.campus365.app.students.StudentHostel"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.campus365.app.students.StudentLibraryBook"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.campus365.app.students.StudentClassTimetable"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.campus365.app.students.StudentHomework"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.campus365.app.students.StudentHomeworkDetails"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.campus365.app.students.StudentLibraryBookIssued"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.campus365.app.students.StudentAppyLeave"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.campus365.app.students.StudentAddLeaveNew"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.campus365.app.students.StudentAddLeave"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.campus365.app.students.StudentEditLeave"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.campus365.app.TakeUrl"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.campus365.app.students.StudentDashboard"
            android:configChanges="orientation|keyboardHidden|screenSize"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.campus365.app.students.StudentTasks"
            android:screenOrientation="portrait" />

        <meta-data
            android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version" />

        <activity
            android:name="com.campus365.app.students.Payment"
            android:screenOrientation="portrait" />
        <activity
            android:name="home.ui.chatdocumentattachmentslist.activity.DocumentAttachmentActivity"
            android:screenOrientation="portrait" />
        <activity
            android:name="home.ui.chatimagesattachmentslist.activity.ImagesAttachmentActivity"
            android:screenOrientation="portrait" />
        <activity
            android:name="home.ui.members.MembersActivity"
            android:screenOrientation="portrait" />

        <service android:name="com.google.firebase.components.ComponentDiscoveryService" >
            <meta-data
                android:name="com.google.firebase.components:com.google.firebase.analytics.connector.internal.AnalyticsConnectorRegistrar"
                android:value="com.google.firebase.components.ComponentRegistrar" />
            <meta-data
                android:name="com.google.firebase.components:com.google.firebase.firestore.FirestoreRegistrar"
                android:value="com.google.firebase.components.ComponentRegistrar" />
            <meta-data
                android:name="com.google.firebase.components:com.google.firebase.iid.Registrar"
                android:value="com.google.firebase.components.ComponentRegistrar" />
            <meta-data
                android:name="com.google.firebase.components:com.google.firebase.storage.StorageRegistrar"
                android:value="com.google.firebase.components.ComponentRegistrar" />
            <meta-data
                android:name="com.google.firebase.components:com.google.firebase.messaging.FirebaseMessagingRegistrar"
                android:value="com.google.firebase.components.ComponentRegistrar" />
            <meta-data
                android:name="com.google.firebase.components:com.google.firebase.installations.FirebaseInstallationsRegistrar"
                android:value="com.google.firebase.components.ComponentRegistrar" />
            <meta-data
                android:name="com.google.firebase.components:com.google.firebase.datatransport.TransportRegistrar"
                android:value="com.google.firebase.components.ComponentRegistrar" />
            <meta-data
                android:name="com.google.firebase.components:com.google.firebase.crashlytics.CrashlyticsRegistrar"
                android:value="com.google.firebase.components.ComponentRegistrar" />
            <meta-data
                android:name="com.google.firebase.components:com.google.firebase.auth.FirebaseAuthRegistrar"
                android:value="com.google.firebase.components.ComponentRegistrar" />
            <meta-data
                android:name="com.google.firebase.components:com.google.firebase.remoteconfig.ktx.FirebaseRemoteConfigKtxRegistrar"
                android:value="com.google.firebase.components.ComponentRegistrar" />
        </service>
        
        
        
        
        
        <receiver
            android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver"
            android:exported="true"
            android:permission="com.google.android.c2dm.permission.SEND" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
            </intent-filter>
        </receiver>
        <meta-data
            android:name="com.google.firebase.messaging.default_notification_icon"
            android:resource="@drawable/ic_notification_icon" />
        <meta-data
            android:name="com.google.firebase.messaging.default_notification_color"
            android:resource="@color/colorPrimary" />
        <meta-data
            android:name="com.google.firebase.messaging.default_notification_channel_id"
            android:value="@string/default_notification_channel_id" />

        <service
            android:name="home.services.FirebasePushMessagingService"
            android:exported="false" >
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
        <service
            android:name="com.google.android.gms.measurement.AppMeasurementService"
            android:enabled="true"
            android:exported="false" />
        <service
            android:name="com.google.android.gms.measurement.AppMeasurementJobService"
            android:enabled="true"
            android:exported="false"
            android:permission="android.permission.BIND_JOB_SERVICE" />

        <receiver
            android:name="com.google.android.gms.measurement.AppMeasurementReceiver"
            android:enabled="true" >
            <intent-filter>
                <action android:name="com.google.android.gms.measurement.UPLOAD" />
            </intent-filter>
        </receiver>
        <receiver
            android:name="com.google.android.gms.analytics.AnalyticsReceiver"
            android:enabled="true" >
            <intent-filter>
                <action android:name="com.google.android.gms.analytics.ANALYTICS_DISPATCH" />
            </intent-filter>
        </receiver>

        <service
            android:name="com.google.android.gms.analytics.AnalyticsService"
            android:enabled="true"
            android:exported="false" />

        <provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="com.campus365.app.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true" >
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_provider_paths" />
        </provider>

        <activity
            android:name="com.mobikwik.mobikwikpglib.activities.MobiKwikPGLibActivity"
            android:screenOrientation="portrait" />

        <meta-data
            android:name="io.fabric.ApiKey"
            android:value="800d766e0b6154ea8cd3986476d92269b215abd9" />

        <activity android:name="com.mobikwik.mobikwikpglib.activities.PgWebViewActivity" />
        <activity
            android:name="com.gocashfree.cashfreesdk.CFPaymentActivity"
            android:theme="@style/Theme.AppCompat.Light.NoActionBar" />
        <activity android:name="com.gocashfree.cashfreesdk.CFUPIPaymentActivity" />
        <activity android:name="com.gocashfree.cashfreesdk.AmazonPayActivity" />
        <activity android:name="com.gocashfree.cashfreesdk.GooglePayActivity" />
    </application>

</manifest>

#### Relevant Code:
This line makes the crash. This one using ktx
```
val remoteConfig = Firebase.remoteConfig
```

This line makes the crash. This one without using ktx

```
val remoteConfig = FirebaseRemoteConfig.getInstance()
```

**Comment by iambaljeet** [comment]
Well, the issue is resolved. Due to some conflict between libraries some values from merged AndroidManifest get removed at Compile time.
Adding the following fields to manifest worked for me.
        <service android:name="com.google.firebase.components.ComponentDiscoveryService">
            <meta-data
                android:name="com.google.firebase.components:com.google.firebase.abt.component.AbtRegistrar"
                android:value="com.google.firebase.components.ComponentRegistrar" />
            <meta-data
                android:name="com.google.firebase.components:com.google.firebase.remoteconfig.RemoteConfigRegistrar"
                android:value="com.google.firebase.components.ComponentRegistrar" />
        </service>

**Comment by iambaljeet** [comment]
Well, the issue is resolved. Due to some conflict between libraries some values from merged AndroidManifest get removed at Compile time.
Adding below fields to manifest worked for me.
        ```
<service android:name="com.google.firebase.components.ComponentDiscoveryService">
            <meta-data
                android:name="com.google.firebase.components:com.google.firebase.abt.component.AbtRegistrar"
                android:value="com.google.firebase.components.ComponentRegistrar" />
            <meta-data
                android:name="com.google.firebase.components:com.google.firebase.remoteconfig.RemoteConfigRegistrar"
                android:value="com.google.firebase.components.ComponentRegistrar" />
        </service>
```

**Comment by iambaljeet** [comment]
```
<service android:name="com.google.firebase.components.ComponentDiscoveryService">
            <meta-data
                android:name="com.google.firebase.components:com.google.firebase.abt.component.AbtRegistrar"
                android:value="com.google.firebase.components.ComponentRegistrar" />
            <meta-data
                android:name="com.google.firebase.components:com.google.firebase.remoteconfig.RemoteConfigRegistrar"
                android:value="com.google.firebase.components.ComponentRegistrar" />
        </service>
```
