### ISSUE TITLE
FirebaseCrashlytics: Trust anchor for certification path not found.

### ISSUE THREAD

**Issue by VincentJoshuaET** [firebase/firebase-android-sdk#1849]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.0.1
  * Firebase Component: Crashlytics
  * Component version: 17.1.1

#### Steps to reproduce:

Follow this guide: https://firebase.google.com/docs/crashlytics/get-started?authuser=0&platform=android

#### Relevant Code:

```
Project build.gradle
dependencies {
        // ...

        // Check that you have the Google Services Gradle plugin v4.3.2 or later
        // (if not, add it).
        classpath 'com.google.gms:google-services:4.3.3'

        // Add the Crashlytics Gradle plugin.
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.2.0'
    }

Module build.gradle
apply plugin: 'com.google.firebase.crashlytics'
dependencies {
    // Recommended: Add the Firebase SDK for Google Analytics.
    implementation 'com.google.firebase:firebase-analytics-ktx:17.4.4'

    // Add the Firebase Crashlytics SDK.
    implementation 'com.google.firebase:firebase-crashlytics:17.1.1'
}
```

My device (Android 10) time is already set automatically. I also tried set the time manually, no changes.

Error on app start:
```
    E/FirebaseCrashlytics: Settings request failed.
        javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
            at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:231)
            at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:319)
            at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:283)
            at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:168)
            at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
            at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
            at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
            at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
            at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
            at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
            at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
            at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
            at okhttp3.RealCall.execute(RealCall.java:92)
            at com.google.firebase.crashlytics.internal.network.HttpRequest.execute(HttpRequest.java:129)
            at com.google.firebase.crashlytics.internal.settings.network.DefaultSettingsSpiCall.invoke(DefaultSettingsSpiCall.java:86)
            at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:200)
            at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:193)
            at com.google.android.gms.tasks.zzp.run(com.google.android.gms:play-services-tasks@@17.0.2:2)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
            at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:60)
            at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:27)
            at java.lang.Thread.run(Thread.java:919)
         Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
            at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:674)
            at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:551)
            at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:507)
            at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:426)
            at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:354)
            at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
            at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:89)
            at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:224)
            at com.android.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(ConscryptFileDescriptorSocket.java:407)
            at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
            at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:387)
```

**Comment by kevinkokomani** [comment]
It looks like this was answered on Stackoverflow: https://stackoverflow.com/questions/63240488/firebasecrashlytics-trust-anchor-for-certification-path-not-found/63253983#63253983

**Comment by kevinkokomani** [comment]
Are you behind some sort of proxy or firewall? And what is the exact device you've run into this on/have you tried reproducing on other devices?

**Comment by VincentJoshuaET** [comment]
No. I have a Redmi Note 7 running Android 10. Also tried it with the Android Studio emulator with Google Play. The stackoverflow solutions linked to https://stackoverflow.com/questions/42414958/android-java-security-cert-certpathvalidatorexception-trust-anchor-for-certific but I don't use any of that code, I don't use anything to setup the connection or the certificates. I just followed the Crashlytics guide: https://firebase.google.com/docs/crashlytics/get-started?authuser=0&platform=android

**Comment by mrwillis21** [comment]
Hi there, we haven't seen any other reports of this. Are you still seeing this issue?
