### ISSUE TITLE
Firebase causes crashes on app exit

### ISSUE THREAD

**Issue by extreamsd** [firebase/firebase-android-sdk#1878]
### [READ] Step 1: Are you in the right place?

I am asked by your support to file the issue here, so I guess so!

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.0.1
  * Firebase Component: Analytics / Installations

implementation 'com.google.firebase:firebase-core:17.4.4'
implementation 'com.google.firebase:firebase-messaging:20.2.3'
implementation 'com.google.android.gms:play-services-auth:18.1.0'

### [REQUIRED] Step 3: Describe the problem

For a number of users of our app, the app crashes when they leave the app. They all show the same stack trace:

Native trace = java.lang.RuntimeException: Crash in native code
at com.extreamsd.aeshared.Progress.nativeCrashed(Progress.java:539)
at java.util.regex.Matcher.openImpl(Matcher.java)
at java.util.regex.Matcher.usePattern(Matcher.java:238)
at java.util.regex.Matcher.<init>(Matcher.java:185)
at java.util.regex.Pattern.matcher(Pattern.java:1034)
at com.google.firebase.installations.Utils.isValidApiKeyFormat(Utils.java:54)
at com.google.firebase.installations.FirebaseInstallations.preConditionChecks(FirebaseInstallations.java:159)
at com.google.firebase.installations.FirebaseInstallations.getId(FirebaseInstallations.java:219)
at com.google.firebase.analytics.FirebaseAnalytics.getFirebaseInstanceId(FirebaseAnalytics.java:45)
at java.lang.reflect.Method.invoke(Method.java)
at com.google.android.gms.measurement.internal.zzes.zzai(zzes.java:226)
at com.google.android.gms.measurement.internal.zzes.zza(zzes.java:175)
at com.google.android.gms.measurement.internal.zzis.zza(zzis.java:294)
at com.google.android.gms.measurement.internal.zzis.zza(zzis.java:63)
at com.google.android.gms.measurement.internal.zzhh.zza(zzhh.java:313)
at com.google.android.gms.measurement.internal.zzhk.run(zzhk.java:2)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at com.google.android.gms.measurement.internal.zzga.run(zzga.java:21)

I see that firebase-core is no longer needed, so I have changed it to the analytics version, but core should include analytics, so that shouldn't matter either.

Firebase project ID is audio-evolution-mobile-android
Package name is  com.extreamsd.aemobile

I have searched my bug reports and found 7 of these occurrences, all on Android 10, but not specific to a certain Android device. They all seem to happen on leaving the app. Looking at the code, isValidApiKeyFormat can use a try/catch block and return false in the catch which would hopefully 'solve' this issue if there isn't a try/catch higher up. We have no idea what the input argument is to this method.

#### Relevant Code:

We don't have any code related to this.

**Comment by rlazo** [comment]
Hi @extreamsd sorry for the delay. Since it's being a while since you reported your issue, does it still happen with the latest versions of the SDKs? Thanks!

**Comment by extreamsd** [comment]
It still happened in com.google.firebase:firebase-analytics:17.5.0, but I have yet to release a version with 18.0.1. That will happen soon though.

**Comment by extreamsd** [comment]
Still happens with com.google.firebase:firebase-analytics:18.0.2

Native trace = java.lang.RuntimeException: Crash in native code
 at com.extreamsd.aeshared.Progress.nativeCrashed(Progress.java:539)
 at com.android.icu.util.regex.PatternNative.openMatcherImpl(PatternNative.java)
 at com.android.icu.util.regex.PatternNative.openMatcher(PatternNative.java:48)
 at com.android.icu.util.regex.MatcherNative.<init>(MatcherNative.java:37)
 at com.android.icu.util.regex.MatcherNative.create(MatcherNative.java:32)
 at java.util.regex.Matcher.usePattern(Matcher.java:214)
 at java.util.regex.Matcher.<init>(Matcher.java:166)
 at java.util.regex.Pattern.matcher(Pattern.java:1027)
 at com.google.firebase.installations.Utils.isValidApiKeyFormat(Utils.java:91)
 at com.google.firebase.installations.FirebaseInstallations.preConditionChecks(FirebaseInstallations.java:183)
 at com.google.firebase.installations.FirebaseInstallations.getId(FirebaseInstallations.java:240)
 at com.google.firebase.analytics.FirebaseAnalytics.getFirebaseInstanceId(FirebaseAnalytics.java:1)
 at java.lang.reflect.Method.invoke(Method.java)
 at com.google.android.gms.measurement.internal.zzea.zzh(zzea.java:47)
 at com.google.android.gms.measurement.internal.zzjb.zzS(zzjb.java:9)
 at com.google.android.gms.measurement.internal.zzjb.zzl(zzjb.java:7)
 at com.google.android.gms.measurement.internal.zzhn.zzu(zzhn.java:147)
 at com.google.android.gms.measurement.internal.zzgt.run(zzgt.java:1)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at com.google.android.gms.measurement.internal.zzfh.run(zzfh.java:6)
