### ISSUE TITLE
166508277: No Activity found to handle Intent in in-app message

### ISSUE THREAD

**Issue by deepak786** [firebase/firebase-android-sdk#1890]
`implementation 'com.google.firebase:firebase-inappmessaging-display:19.1.0'`

Created a campaign to show the in-app message in the app with the above SDK version.
This in-app message has an action URL. But Crashlytics reported a lot of crashes today from the click on In-app message.

```
Fatal Exception: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat= https://agendaboa.page.link/FQP2 (has extras) }
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2018)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1673)
       at android.app.Activity.startActivityForResult(Activity.java:4689)
       at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:675)
       at android.app.Activity.startActivityForResult(Activity.java:4647)
       at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:662)
       at android.app.Activity.startActivity(Activity.java:5008)
       at androidx.core.content.ContextCompat.startActivity(ContextCompat.java:251)
       at androidx.browser.customtabs.CustomTabsIntent.launchUrl(CustomTabsIntent.java:331)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay$3.onClick(FirebaseInAppMessagingDisplay.java:329)
       at android.view.View.performClick(View.java:7359)
       at android.widget.TextView.performClick(TextView.java:14230)
       at android.view.View.performClickInternal(View.java:7325)
       at android.view.View.access$3200(View.java:846)
       at android.view.View$PerformClick.run(View.java:27807)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7073)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)  
```

**Comment by deepak786** [comment]
@rlazo @JasonAHeron any update?

**Comment by deepak786** [comment]
is his solved in version 19.1.1?
<img width="826" alt="Screen Shot 2020-08-28 at 2 27 38 PM" src="https://user-images.githubusercontent.com/14223997/91542043-dcccb680-e93a-11ea-8c6d-9e5c9811bdfc.png">

**Comment by rlazo** [comment]
Hi @deepak786 sorry for the late reply. Yes, please test using the latest version and report back if it didn't fix it.

**Comment by rlazo** [comment]
For reference, we've updated how the browser intent is handled in #1781 which should fix this issue.
