### ISSUE TITLE
 java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.IllegalStateException: The Crashlytics build ID is missing. This occurs when Crashlytics tooling is absent from your app's build configuration. Please review Crashlytics onboarding instructions and ensure you have a valid Crashlytics account.

### ISSUE THREAD

**Issue by JasonLinkinBright** [firebase/firebase-android-sdk#1896]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in Crashlytics the code in this repository CrashlyticsCore. 

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: _9.0____
  * Firebase Component: __firebase-crashlytics___ (Database, Firestore, Storage, Functions, etc)
  * Component version: _17.2.1____

#### Steps to reproduce:

I remove all the Fabric related config and upgrade Firebase to 
'com.google.firebase:firebase-crashlytics:17.2.1'
'com.google.firebase:firebase-analytics:17.5.0'
with firebase-crashlytics-gradle plugin 
classpath 'com.google.firebase:firebase-crashlytics-gradle:2.2.0'

After gradle sync and launch app，it shows error：
java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.IllegalStateException: The Crashlytics build ID is missing. This occurs when Crashlytics tooling is absent from your app's build configuration. Please review Crashlytics onboarding instructions and ensure you have a valid Crashlytics account.
        at android.app.ActivityThread.installProvider(ActivityThread.java:6747)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6289)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6204)
        at android.app.ActivityThread.access$1200(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1785)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: java.lang.IllegalStateException: The Crashlytics build ID is missing. This occurs when Crashlytics tooling is absent from your app's build configuration. Please review Crashlytics onboarding instructions and ensure you have a valid Crashlytics account.
        at com.google.firebase.crashlytics.internal.common.CrashlyticsCore.onPreExecute(CrashlyticsCore.java:123)
        at com.google.firebase.crashlytics.FirebaseCrashlytics.init(FirebaseCrashlytics.java:165)
        at com.google.firebase.crashlytics.CrashlyticsRegistrar.buildCrashlytics(CrashlyticsRegistrar.java:54)
        at com.google.firebase.crashlytics.CrashlyticsRegistrar.access$lambda$0(Unknown Source:0)
        at com.google.firebase.crashlytics.CrashlyticsRegistrar$$Lambda$1.create(Unknown Source:2)
        at com.google.firebase.components.ComponentRuntime.lambda$new$0(com.google.firebase:firebase-components@@16.0.0:69)
        at com.google.firebase.components.ComponentRuntime$$Lambda$1.get(Unknown Source:4)
        at com.google.firebase.components.Lazy.get(com.google.firebase:firebase-components@@16.0.0:53)
        at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(com.google.firebase:firebase-components@@16.0.0:158)
        at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:583)
        at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:304)
        at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:268)
        at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:253)
        at com.google.firebase.provider.FirebaseInitProvider.onCreate(FirebaseInitProvider.java:51)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1940)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1915)
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(FirebaseInitProvider.java:45)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6742)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6289) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6204) 
        at android.app.ActivityThread.access$1200(ActivityThread.java:237) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1785) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7050) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965) 

#### Relevant Code:

I have no idea about what the build ID is, the google-services.json downloaded from Firebase console not contain it,
and the offical document didn't mention it .

**Comment by rlazo** [comment]
Hi @JasonLinkinBright the step the error message refers to is apply the crashlytics gradle plugin

```
// Apply the Crashlytics Gradle plugin
apply plugin: 'com.google.firebase.crashlytics'
```

It's the step 2.2 in https://firebase.google.com/docs/crashlytics/get-started?platform=android

**Comment by JasonLinkinBright** [comment]
Thank you for reply @rlazo 

this config I have already added before I make this issue.
It may not be the right solution.

it is my config below:
eg. 
apply plugin: 'com.android.application'
//apply plugin: 'io.fabric'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'

**Comment by danhantao** [comment]
put google-services.json in productFlavors path, debug and release。
not app root path。
https://medium.com/@dev.amanchugh/how-to-use-a-google-services-json-file-for-different-build-variant-or-flavors-in-android-7c8949514819

**Comment by danhantao** [comment]
@JasonLinkinBright 
不要将 google-services.json 放置到app/的根目录下。
新建productFlavors，然后新建debug和release目录，放入google-services.json，删除根目录下的google-services.json文件。
应该是插件的问题。
如果不这么做，拿不到com.crashlytics.android.build_id这个文件，导致crash

**Comment by JasonLinkinBright** [comment]
> @JasonLinkinBright
> 不要将 google-services.json 放置到app/的根目录下。
> 新建productFlavors，然后新建debug和release目录，放入google-services.json，删除根目录下的google-services.json文件。
> 应该是插件的问题。

我就是根据 productFlavors 来新建debug/release的。删除根目录后，直接报错。用的是新的，这个 com.google.firebase:firebase-crashlytics-gradle:2.2.0' 

> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location:

**Comment by JasonLinkinBright** [comment]
> 找不到google-services.json，放入的路径有问题。
> https://developers.google.com/android/guides/google-services-plugin
> 删除根目录下的json,然后在productFlavors下放入google-services.json，就可以解决问题。

@danhantao 我现在的配置就是这样的，是真的不行。你用的是com.google.firebase:firebase-crashlytics-gradle:2.2.0 这个plugin吗？

**Comment by rlazo** [comment]
@JasonLinkinBright could are you using different flavors as suggested by @danhantao ? Also, be aware that the comment about using different places for different flavors applies to the google services plugin above 2.2 and it's unrelated to the version of the crashlytics gradle plugin version.

**Comment by JasonLinkinBright** [comment]
@rlazo I have 2 build types（debug/release） and 3 flavors（flavor1/flavor2/flavor3）。
I have two test  two ways to put google-services.json,both failed.
1. src/debug/flavor1/google-service.json   src/release/flavor1/google-service.json
2. src/flavor1/debug/google-service.json   src/flavor1/release/google-service.json

**Comment by JasonLinkinBright** [comment]
In addition, my flavor  begin with uppercase letter.
is google service 4.3.3 not support uppercase letter?

**Comment by danhantao** [comment]
@JasonLinkinBright  大写字母有路径不正确等问题。
删除根目录下的google-service.json,使用src/flavor1/debug/google-service.json src/flavor1/release/google-service.json
可以试试。

**Comment by JasonLinkinBright** [comment]
是的，我做了尝试，4.2.0 +  大写字母（我的原有配置）是ok的，4.3.3+大写字母就不行。
google service 4.2.0 还支持大写字母的，4.3.3 就不支持大写字母了，有没有相关的文档或者release note？

**Comment by giejay** [comment]
I am having the exact same issue, applied the plugin, added the dependencies, updated the google-service.json for both flavors. But still facing the issue.

When I do a clean build, then build the apk, it works 50 percent of the times... Whenever I then do a debug session for example, its broken again.

**Comment by davidmotson** [comment]
@JasonLinkinBright 
If it doesn't effect the rest of your build, consider trying to have your flavor names start with a lower case letter, or at least putting the google-services.json into folders with lower case letter names.

It's also worth noting that the plugin does include in it's output where it _looked_ for the google-services.json file.

The reason for this is: the flavor information is not given directly to the plugin, but rather concatenated with the build type UsingCamelCase. 

in parsing this out, we assume it is meant to be lower case, since that is the convention.

**Comment by songzhangzhang** [comment]
I have the same issue. After upgrading gradle to 5.6.4, it's resolved.

I update the gradle-wrapper.properties like this:
`distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.4-all.zip`

**Comment by davidmotson** [comment]
I'll close this for now. Feel free to re-open if neither of the above suggestions work for you.
