### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by kyungsuksong** [firebase/firebase-android-sdk#1933]
Hi, I got this exception when I was switching between different fragment.
by the way, I am using the latest version of the firebase (19.4.0)

2020-09-03 02:29:21.187 4509-4509/com.myapps.app1 I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@e7c2fec time:44227401
2020-09-03 02:29:21.289 4509-4509/com.myapps.app1 I/SurfaceView: updateWindow -- onDetachedFromWindow, this = android.view.SurfaceView{99ccf62 V.E...... ........ 0,0-720,1136 #7f0801e7 app:id/mapSurfaceView}
2020-09-03 02:29:23.023 4509-4953/com.myapps.app1 W/DynamiteModule: Local module descriptor class for providerinstaller not found.
2020-09-03 02:29:23.031 4509-4953/com.myapps.app1 I/DynamiteModule: Considering local module providerinstaller:0 and remote module providerinstaller:0
2020-09-03 02:29:23.032 4509-4628/com.myapps.app1 W/PersistentConnection: pc_0 - Using an unspecified index. Your data will be downloaded and filtered on the client. Consider adding '".indexOn": "fType"' at taskRequests/sTtWyr6ysgU4uf4gMlhaDTjoBOJ2 to your security and Firebase Database rules for better performance
2020-09-03 02:29:23.033 4509-4953/com.myapps.app1 W/ProviderInstaller: Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.
2020-09-03 02:29:23.040 4509-4509/com.myapps.app1 I/TasksFrag: my tasks queried
2020-09-03 02:29:23.192 4509-4520/com.myapps.app1 I/art: Enter while loop.
2020-09-03 02:29:23.232 4509-4953/com.myapps.app1 I/ProviderInstaller: Installed default security provider GmsCore_OpenSSL
2020-09-03 02:29:25.924 4509-4628/com.myapps.app1 E/NoopPersistenceManager: Caught Throwable.
    java.lang.AssertionError: hardAssert failed: 
        at com.google.firebase.database.core.utilities.Utilities.hardAssert(Utilities.java:234)
        at com.google.firebase.database.core.utilities.Utilities.hardAssert(Utilities.java:229)
        at com.google.firebase.database.core.ZombieEventManager.unRecordEventRegistration(ZombieEventManager.java:94)
        at com.google.firebase.database.core.ZombieEventManager.onZombied(ZombieEventManager.java:155)
        at com.google.firebase.database.core.EventRegistration.zombify(EventRegistration.java:50)
        at com.google.firebase.database.core.view.View.removeEventRegistration(View.java:149)
        at com.google.firebase.database.core.SyncPoint.removeEventRegistration(SyncPoint.java:194)
        at com.google.firebase.database.core.SyncTree$12.call(SyncTree.java:603)
        at com.google.firebase.database.core.SyncTree$12.call(SyncTree.java:587)
        at com.google.firebase.database.core.persistence.NoopPersistenceManager.runInTransaction(NoopPersistenceManager.java:126)
        at com.google.firebase.database.core.SyncTree.removeEventRegistration(SyncTree.java:586)
        at com.google.firebase.database.core.SyncTree.removeEventRegistration(SyncTree.java:569)
        at com.google.firebase.database.core.Repo.removeEventCallback(Repo.java:536)
        at com.google.firebase.database.Query$2.run(Query.java:220)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
2020-09-03 02:29:25.925 4509-4628/com.myapps.app1 E/RunLoop: Uncaught exception in Firebase Database runloop (19.4.0). If you are not already on the latest version of the Firebase SDKs, try updating your dependencies. Should this problem persist, please file a report at https://github.com/firebase/firebase-android-sdk
    java.lang.RuntimeException: java.lang.AssertionError: hardAssert failed: 
        at com.google.firebase.database.core.persistence.NoopPersistenceManager.runInTransaction(NoopPersistenceManager.java:131)
        at com.google.firebase.database.core.SyncTree.removeEventRegistration(SyncTree.java:586)
        at com.google.firebase.database.core.SyncTree.removeEventRegistration(SyncTree.java:569)
        at com.google.firebase.database.core.Repo.removeEventCallback(Repo.java:536)
        at com.google.firebase.database.Query$2.run(Query.java:220)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.lang.AssertionError: hardAssert failed: 
        at com.google.firebase.database.core.utilities.Utilities.hardAssert(Utilities.java:234)
        at com.google.firebase.database.core.utilities.Utilities.hardAssert(Utilities.java:229)
        at com.google.firebase.database.core.ZombieEventManager.unRecordEventRegistration(ZombieEventManager.java:94)
        at com.google.firebase.database.core.ZombieEventManager.onZombied(ZombieEventManager.java:155)
        at com.google.firebase.database.core.EventRegistration.zombify(EventRegistration.java:50)
        at com.google.firebase.database.core.view.View.removeEventRegistration(View.java:149)
        at com.google.firebase.database.core.SyncPoint.removeEventRegistration(SyncPoint.java:194)
        at com.google.firebase.database.core.SyncTree$12.call(SyncTree.java:603)
        at com.google.firebase.database.core.SyncTree$12.call(SyncTree.java:587)
        at com.google.firebase.database.core.persistence.NoopPersistenceManager.runInTransaction(NoopPersistenceManager.java:126)
        at com.google.firebase.database.core.SyncTree.removeEventRegistration(SyncTree.java:586) 
        at com.google.firebase.database.core.SyncTree.removeEventRegistration(SyncTree.java:569) 
        at com.google.firebase.database.core.Repo.removeEventCallback(Repo.java:536) 
        at com.google.firebase.database.Query$2.run(Query.java:220) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) 
2020-09-03 02:29:25.984 4509-4509/com.myapps.app1 E/RecyclerView: No adapter attached; skipping layout
2020-09-03 02:29:25.999 4509-4509/com.myapps.app1 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.myapps.app1, PID: 4509
    java.lang.RuntimeException: Uncaught exception in Firebase Database runloop (19.4.0). If you are not already on the latest version of the Firebase SDKs, try updating your dependencies. Should this problem persist, please file a report at https://github.com/firebase/firebase-android-sdk
        at com.google.firebase.database.android.AndroidPlatform$1$1.run(AndroidPlatform.java:96)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6361)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
     Caused by: java.lang.RuntimeException: java.lang.AssertionError: hardAssert failed: 
        at com.google.firebase.database.core.persistence.NoopPersistenceManager.runInTransaction(NoopPersistenceManager.java:131)
        at com.google.firebase.database.core.SyncTree.removeEventRegistration(SyncTree.java:586)
        at com.google.firebase.database.core.SyncTree.removeEventRegistration(SyncTree.java:569)
        at com.google.firebase.database.core.Repo.removeEventCallback(Repo.java:536)
        at com.google.firebase.database.Query$2.run(Query.java:220)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.lang.AssertionError: hardAssert failed: 
        at com.google.firebase.database.core.utilities.Utilities.hardAssert(Utilities.java:234)
        at com.google.firebase.database.core.utilities.Utilities.hardAssert(Utilities.java:229)
        at com.google.firebase.database.core.ZombieEventManager.unRecordEventRegistration(ZombieEventManager.java:94)
        at com.google.firebase.database.core.ZombieEventManager.onZombied(ZombieEventManager.java:155)
        at com.google.firebase.database.core.EventRegistration.zombify(EventRegistration.java:50)
        at com.google.firebase.database.core.view.View.removeEventRegistration(View.java:149)
        at com.google.firebase.database.core.SyncPoint.removeEventRegistration(SyncPoint.java:194)
        at com.google.firebase.database.core.SyncTree$12.call(SyncTree.java:603)
        at com.google.firebase.database.core.SyncTree$12.call(SyncTree.java:587)
        at com.google.firebase.database.core.persistence.NoopPersistenceManager.runInTransaction(NoopPersistenceManager.java:126)
        at com.google.firebase.database.core.SyncTree.removeEventRegistration(SyncTree.java:586) 
        at com.google.firebase.database.core.SyncTree.removeEventRegistration(SyncTree.java:569) 
        at com.google.firebase.database.core.Repo.removeEventCallback(Repo.java:536) 
        at com.google.firebase.database.Query$2.run(Query.java:220) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) 
2020-09-03 02:29:31.718 4509-4520/com.myapps.app1 I/art: Enter while loop.

**Comment by araviindm** [comment]
I got the same one

**Comment by DrSteinmetz** [comment]
Got the same problem...

**Comment by NativeDevlopment** [comment]
i  got the  same problem.

**Comment by russjw** [comment]
this same problem just started today for me...it occurred after update Android Studio but i can't say it's related

**Comment by mussacharles60** [comment]
Also I got same problem.

**Comment by salima1947** [comment]
I got same problem.

**Comment by aguatno** [comment]
Hi @kyungsuksong  sorry for the late in response. I would like to check if you are still having issues? Have you tried the latest SDK version to see if the issue persists? Thanks
