### ISSUE TITLE
Firebasebase Crashlytics - Default FirebaseApp is not initialized in this process - SyncAdapter

### ISSUE THREAD

**Issue by wezley98** [firebase/firebase-android-sdk#1968]
### [READ] Step 1: Are you in the right place?

Yes

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.0.1
  * Firebase Component: Crashlytics
  * Component version:
 `classpath "com.google.firebase:firebase-crashlytics-gradle:2.2.0"`
`implementation "com.google.firebase:firebase-crashlytics-ktx:17.2.1`

#### Steps to reproduce:

Our app contains a sync adapter, after migrating to the non-fabric SDK, our app now crashes on some devices with the following stack:

```
2020-09-10 11:36:38.406 27298-27298/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.someapp.android:sync, PID: 27298
    java.lang.RuntimeException: Unable to create application com.someApp.android.SomeAppApplication: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.someapp.android:sync. Make sure to call FirebaseApp.initializeApp(Context) first.
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6065)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.someapp.android:sync. Make sure to call FirebaseApp.initializeApp(Context) first.
        at d.h.c.c.b(FirebaseApp.java:5)
        at d.h.c.i.d.a(FirebaseCrashlytics.java:1)
        at com.someapp.android.SomeAppApplication.onCreate(SomeAppApplication.java:32)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1125)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6062)
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6944) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
```
#### Relevant Code:

We have tried the following inside the sync adapters constructor, but still seeing the same crash, replicated on Samsung 7 (8.0) may effect other devices.

```
public AccountSyncAdapter(Context context, boolean autoInitialize, boolean allowParallelSyncs) {
        super(context, autoInitialize, allowParallelSyncs);
        if (FirebaseApp.getApps(context).isEmpty()) {
            FirebaseApp.initializeApp(context);
        }
        mContext = context;
        InjectHelper.getRootComponent().inject(this);
    }
```

**Comment by cvaghela** [comment]
Can you try to initialize Firebase according to our Docs without the syncAdapter just for troubleshooting purposes and see if that's working fine?

**Comment by wezley98** [comment]
@cvaghela Yes, tried that and the crash doesn't occur, it works fine. But we aren't in a position to migrate from SyncAdapter to WorkManager before the Crashlytics deadline.

**Comment by wezley98** [comment]
@cvaghela Do you have any other suggestions about how to workaround this issue, or if we need a fix on the Crashlytics SDK? The deadline for the migration is fast approaching (November 15, 2020)

**Comment by majhamza** [comment]
@wezley98 I had the same problem, updating google-services plugin to the latest version solved it for me

**Comment by CodyEddings** [comment]
I have this same issue in my app that doesn't run on a device with google play services.

**Comment by yangchuanosaurus** [comment]
I have the same issue in my app without google-services.
Does the google-services as the dependency by firebase-crashlytics?

**Comment by mrober** [comment]
This was a fabric migration issue so it's no longer relevant. However, Firebase Crashlytics has improved support for multi-process app several versions ago. Anyone experiencing issues with multi-process apps should open a new ticket if the problem still persists on the latest version of the SDK.
