### ISSUE TITLE
Performance monitoring crashes with a ClassNotFoundException

### ISSUE THREAD

**Issue by vinaysshenoy** [firebase/firebase-android-sdk#1997]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.0.1
  * Firebase Component: Performance Monitoring
  * Component version: 19.0.8

### [REQUIRED] Step 3: Describe the problem

Running an application with Firebase Performance Monitoring turned on crashes the app with the following stacktrace:

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/perf/network/FirebasePerfOkHttpClient;
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:46)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.internal.operators.single.SingleOnErrorReturn.subscribeActual(SingleOnErrorReturn.java:38)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.perf.network.FirebasePerfOkHttpClient" on path: DexPathList[[zip file "/data/app/org.simple.clinic.qa.debug-qhyBhK5-KT1OL05VevPSdw==/base.apk"],nativeLibraryDirectories=[/data/app/org.simple.clinic.qa.debug-qhyBhK5-KT1OL05VevPSdw==/lib/x86_64, /data/app/org.simple.clinic.qa.debug-qhyBhK5-KT1OL05VevPSdw==/base.apk!/lib/x86_64, /system/lib64, /system/product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:204) 
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:46) 
        at io.reactivex.Observable.subscribe(Observable.java:12284) 
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35) 
        at io.reactivex.Observable.subscribe(Observable.java:12284) 
        at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35) 
        at io.reactivex.Single.subscribe(Single.java:3666) 
        at com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43) 
        at io.reactivex.Single.subscribe(Single.java:3666) 
        at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34) 
        at io.reactivex.Single.subscribe(Single.java:3666) 
        at com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43) 
        at io.reactivex.Single.subscribe(Single.java:3666) 
        at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34) 
        at io.reactivex.Single.subscribe(Single.java:3666) 
        at com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43) 
        at io.reactivex.Single.subscribe(Single.java:3666) 
        at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34) 
        at io.reactivex.Single.subscribe(Single.java:3666) 
        at com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43) 
        at io.reactivex.Single.subscribe(Single.java:3666) 
        at io.reactivex.internal.operators.single.SingleOnErrorReturn.subscribeActual(SingleOnErrorReturn.java:38) 
        at io.reactivex.Single.subscribe(Single.java:3666) 
        at com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43) 
        at io.reactivex.Single.subscribe(Single.java:3666) 
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89) 
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578) 
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66) 
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919)
```

#### Steps to reproduce:

N/A

#### Relevant Code:

- I've integrated the library as per the official documentation.
- I've tried adding the multidex keep file, but it does not work as well.

```
com/google/firebase/perf/network/FirebasePerfOkHttpClient.class
```

**Comment by vinaysshenoy** [comment]
I am closing this issue since I discovered the problem, I had not added the `firebase-perf` client dependency and the build was passing because the classes are only being referenced at runtime.
