### ISSUE TITLE
Uncaught exception in Firebase Database runloop (19.4.0), Caused by: java.lang.NoSuchMethodError: JsonMapper

### ISSUE THREAD

**Issue by dharashahkenya** [firebase/firebase-android-sdk#2017]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.0
  * Firebase Component: Database (Database, Firestore, Storage, Functions, etc)
  * Component version: 19.4.0

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

When simply running the app that is using firebase-database, it crashes with the following log:

```
Process: package-name, PID: 24539
    java.lang.RuntimeException: Uncaught exception in Firebase Database runloop (19.4.0). If you are not already on the latest version of the Firebase SDKs, try updating your dependencies. Should this problem persist, please file a report at https://github.com/firebase/firebase-android-sdk
        at com.google.firebase.database.p.g$a$a.run(AndroidPlatform.java:1)
        at android.os.Handler.handleCallback(Handler.java:809)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7383)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
     Caused by: java.lang.NoSuchMethodError: No virtual method object()Lorg/json/d; in class Lorg/json/d; or its super classes (declaration of 'org.json.d' appears in /data/app/package-name-8bt8hVXDm1km0k_TwM2RGQ==/base.apk!classes4.dex)
        at com.google.firebase.database.q.b.a(JsonMapper.java:14)
        at com.google.firebase.database.q.b.a(JsonMapper.java:10)
        at com.google.firebase.database.q.b.a(JsonMapper.java:1)
        at com.google.firebase.database.connection.j.a(WebsocketConnection.java:20)
        at com.google.firebase.database.connection.Connection.b(Connection.java:29)
        at com.google.firebase.database.connection.Connection.a(Connection.java:12)
        at com.google.firebase.database.connection.PersistentConnectionImpl.a(PersistentConnectionImpl.java:176)
        at com.google.firebase.database.connection.PersistentConnectionImpl.a(PersistentConnectionImpl.java:170)
        at com.google.firebase.database.connection.PersistentConnectionImpl.c(PersistentConnectionImpl.java:7)
        at com.google.firebase.database.connection.PersistentConnectionImpl.m(PersistentConnectionImpl.java:7)
        at com.google.firebase.database.connection.PersistentConnectionImpl.a(PersistentConnectionImpl.java:13)
        at com.google.firebase.database.connection.Connection.a(Connection.java:39)
        at com.google.firebase.database.connection.Connection.d(Connection.java:7)
        at com.google.firebase.database.connection.Connection.b(Connection.java:13)
        at com.google.firebase.database.connection.Connection.a(Connection.java:19)
        at com.google.firebase.database.connection.j.a(WebsocketConnection.java:35)
        at com.google.firebase.database.connection.j.c(WebsocketConnection.java:7)
        at com.google.firebase.database.connection.j.a(WebsocketConnection.java:3)
        at com.google.firebase.database.connection.j$e$b.run(WebsocketConnection.java:1)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:784)
```

#### Relevant Code:
```
private DatabaseReference rootRef = FirebaseDatabase.getInstance().getReference();
rootRef.keepSynced(false);

DatabaseReference ref1 = rootRef.child("ref1");
DatabaseReference ref2 = rootRef.child("ref2");

Map<String, Object> obj1 = new HashMap<>();
Map<String, String> obj2 = new HashMap<>();

obj1.put("key1", obj2);

ref2.child("key_here").push().setValue(obj1);
```
:warning: For the purpose of privacy such names have been used. I first tried using firebase-database dependency but i also moved over to firebase-database-ktx, but both of these crash for me.

```
// TODO(you): code here to reproduce the problem
```

**Comment by rlazo** [comment]
Hi @dharashahkenya does this error still show in the latest version of database (19.5.0) ?

**Comment by dharashahkenya** [comment]
> Hi @dharashahkenya does this error still show in the latest version of database (19.5.0) ?

I haven't tried 19.5.0 .. when was this released? I could give it a try today and post in my results here.

**Comment by rlazo** [comment]
It was released yesterday 

https://firebase.google.com/support/release-notes/android#realtime-database_v19-5-0

**Comment by dharashahkenya** [comment]
```
Uncaught exception in Firebase Database runloop (19.5.0). If you are not already on the latest version of the Firebase SDKs, try updating your dependencies. Should this problem persist, please file a report at https://github.com/firebase/firebase-android-sdk
    java.lang.NoSuchMethodError: No virtual method object()Lorg/json/d; in class Lorg/json/d; or its super classes (declaration of 'org.json.d' appears in /data/app/package_name-xIqgkP_sFH2-agaGTx4a7w==/base.apk!classes4.dex)
        at com.google.firebase.database.q.b.a(JsonMapper.java:14)
        at com.google.firebase.database.q.b.a(JsonMapper.java:10)
        at com.google.firebase.database.q.b.a(JsonMapper.java:1)
        at com.google.firebase.database.connection.j.a(WebsocketConnection.java:20)
        at com.google.firebase.database.connection.Connection.b(Connection.java:29)
        at com.google.firebase.database.connection.Connection.a(Connection.java:12)
        at com.google.firebase.database.connection.PersistentConnectionImpl.a(PersistentConnectionImpl.java:176)
        at com.google.firebase.database.connection.PersistentConnectionImpl.a(PersistentConnectionImpl.java:170)
        at com.google.firebase.database.connection.PersistentConnectionImpl.c(PersistentConnectionImpl.java:7)
        at com.google.firebase.database.connection.PersistentConnectionImpl.m(PersistentConnectionImpl.java:7)
        at com.google.firebase.database.connection.PersistentConnectionImpl.a(PersistentConnectionImpl.java:13)
        at com.google.firebase.database.connection.Connection.a(Connection.java:39)
        at com.google.firebase.database.connection.Connection.d(Connection.java:7)
        at com.google.firebase.database.connection.Connection.b(Connection.java:13)
        at com.google.firebase.database.connection.Connection.a(Connection.java:19)
        at com.google.firebase.database.connection.j.a(WebsocketConnection.java:35)
        at com.google.firebase.database.connection.j.c(WebsocketConnection.java:7)
        at com.google.firebase.database.connection.j.a(WebsocketConnection.java:3)
        at com.google.firebase.database.connection.j$e$b.run(WebsocketConnection.java:1)
```

unfortunately with 19.5.0 too i get the same issue. Is the issue around not being able to convert the map to json or something of the sort?

**Comment by schmidt-sebastian** [comment]
@dharashahkenya Thanks for reporting this. These kinds of issue are nearly always caused by a dependency conflict in your module resolution. The offending package is org.json. We currently depend on version v20180813. Can you check what your dependency resolves to? The latest dependency version is v20200518 and we may need to upgrade our SDK to solve this incompatibility.

**Comment by dharashahkenya** [comment]
@schmidt-sebastian : Excuse my inability, but may I please know where to look for the org.json version? There is no specific external lib that we use for that. When i click on JsonMapper. -> JsonObject it leads me to android-28/org.json

**Comment by dharashahkenya** [comment]
@schmidt-sebastian hi.. headups. there is another dependency that seems to be using another version of org. json .. Do you think that might be a possible cause for the above? Can i exclude the org.json group from firebase-database dependency?

**Comment by schmidt-sebastian** [comment]
You should be able to exclude the dependency if another component includes it. If that doesn't work, it indicates that the JSON API had a non-compatible change in which case one of the two dependencies that relies on JSON needs to update its code to match. Usually that means that the we have to move to the latest version, which requires a code change on our end. 

Please do let us know if simply excluding the dependency does work.
