### ISSUE TITLE
Fire

### ISSUE THREAD

**Issue by jpg-developer** [firebase/firebase-android-sdk#2050]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.0.1
  * Firebase Component: Database
  * Component version: 19.5.0

### [REQUIRED] Step 3: Describe the problem

App crashes on startup when trying to write to realtime-database
Crash happens only on Release build, with minifyEnabled set to 'true'
Without minifyEnabled it works ok, but we can't release without obfuscation.

2020-10-07 22:01:58.342 V/FA: Activity paused, time: 19768090
2020-10-07 22:01:58.352 E/RunLoop: Uncaught exception in Firebase Database runloop (19.5.0). If you are not already on the latest version of the Firebase SDKs, try updating your dependencies. Should this problem persist, please file a report at https://github.com/firebase/firebase-android-sdk
    java.lang.NoSuchMethodError: No virtual method object()Ll/a/e; in class Ll/a/e; or its super classes (declaration of 'l.a.e' appears in /data/app/com.amstapps.my_app-U06UrfBZsEBzFN_CZYTI0Q==/base.apk)
        at com.google.firebase.database.util.JsonMapper.serializeJsonValue(JsonMapper.java:13)
        at com.google.firebase.database.util.JsonMapper.serializeJsonValue(JsonMapper.java:9)
        at com.google.firebase.database.util.JsonMapper.serializeJson(JsonMapper.java:1)
        at com.google.firebase.database.connection.WebsocketConnection.send(WebsocketConnection.java:2)
        at com.google.firebase.database.connection.Connection.sendData(Connection.java:5)
        at com.google.firebase.database.connection.Connection.sendRequest(Connection.java:4)
        at com.google.firebase.database.connection.PersistentConnectionImpl.sendSensitive(PersistentConnectionImpl.java:6)
        at com.google.firebase.database.connection.PersistentConnectionImpl.sendAction(PersistentConnectionImpl.java:1)
        at com.google.firebase.database.connection.PersistentConnectionImpl.sendStats(PersistentConnectionImpl.java:4)
        at com.google.firebase.database.connection.PersistentConnectionImpl.sendConnectStats(PersistentConnectionImpl.java:7)
        at com.google.firebase.database.connection.PersistentConnectionImpl.onReady(PersistentConnectionImpl.java:5)
        at com.google.firebase.database.connection.Connection.onConnectionReady(Connection.java:3)
        at com.google.firebase.database.connection.Connection.onHandshake(Connection.java:7)
        at com.google.firebase.database.connection.Connection.onControlMessage(Connection.java:11)
        at com.google.firebase.database.connection.Connection.onMessage(Connection.java:7)
        at com.google.firebase.database.connection.WebsocketConnection.appendFrame(WebsocketConnection.java:7)
        at com.google.firebase.database.connection.WebsocketConnection.handleIncomingFrame(WebsocketConnection.java:6)
        at com.google.firebase.database.connection.WebsocketConnection.access$500(WebsocketConnection.java:1)
        at com.google.firebase.database.connection.WebsocketConnection$WSClientTubesock$2.run(WebsocketConnection.java:1)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
2020-10-07 22:01:58.383 D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
2020-10-07 22:01:58.384 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.amstapps.my_app, PID: 12612
    java.lang.RuntimeException: Uncaught exception in Firebase Database runloop (19.5.0). If you are not already on the latest version of the Firebase SDKs, try updating your dependencies. Should this problem persist, please file a report at https://github.com/firebase/firebase-android-sdk
        at com.google.firebase.database.android.AndroidPlatform$1$1.run(AndroidPlatform.java:1)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:463)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.NoSuchMethodError: No virtual method object()Ll/a/e; in class Ll/a/e; or its super classes (declaration of 'l.a.e' appears in /data/app/com.amstapps.my_app-U06UrfBZsEBzFN_CZYTI0Q==/base.apk)
        at com.google.firebase.database.util.JsonMapper.serializeJsonValue(JsonMapper.java:13)
        at com.google.firebase.database.util.JsonMapper.serializeJsonValue(JsonMapper.java:9)
        at com.google.firebase.database.util.JsonMapper.serializeJson(JsonMapper.java:1)
        at com.google.firebase.database.connection.WebsocketConnection.send(WebsocketConnection.java:2)
        at com.google.firebase.database.connection.Connection.sendData(Connection.java:5)
        at com.google.firebase.database.connection.Connection.sendRequest(Connection.java:4)
        at com.google.firebase.database.connection.PersistentConnectionImpl.sendSensitive(PersistentConnectionImpl.java:6)
        at com.google.firebase.database.connection.PersistentConnectionImpl.sendAction(PersistentConnectionImpl.java:1)
        at com.google.firebase.database.connection.PersistentConnectionImpl.sendStats(PersistentConnectionImpl.java:4)
        at com.google.firebase.database.connection.PersistentConnectionImpl.sendConnectStats(PersistentConnectionImpl.java:7)
        at com.google.firebase.database.connection.PersistentConnectionImpl.onReady(PersistentConnectionImpl.java:5)
        at com.google.firebase.database.connection.Connection.onConnectionReady(Connection.java:3)
        at com.google.firebase.database.connection.Connection.onHandshake(Connection.java:7)
        at com.google.firebase.database.connection.Connection.onControlMessage(Connection.java:11)
        at com.google.firebase.database.connection.Connection.onMessage(Connection.java:7)
        at com.google.firebase.database.connection.WebsocketConnection.appendFrame(WebsocketConnection.java:7)
        at com.google.firebase.database.connection.WebsocketConnection.handleIncomingFrame(WebsocketConnection.java:6)
        at com.google.firebase.database.connection.WebsocketConnection.access$500(WebsocketConnection.java:1)
        at com.google.firebase.database.connection.WebsocketConnection$WSClientTubesock$2.run(WebsocketConnection.java:1)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
2020-10-07 22:01:58.462 I/zygote64: Deoptimizing com.google.firebase.encoders.json.JsonValueObjectEncoderContext com.google.firebase.encoders.json.JsonValueObjectEncoderContext.add(java.lang.Object, boolean) due to JIT inline cache
2020-10-07 22:02:13.379 W/EGL-MAIN: Could not dequeue buffer from native window
2020-10-07 22:02:13.379 A/OpenGLRenderer: Failed to set damage region on surface 0x75268131ce40, error=EGL_BAD_ACCESS
2020-10-07 22:02:13.795 A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 12757 (RenderThread), pid 12612 (oscamviewerdemo)

**Comment by jpg-developer** [comment]
I looked up the source code of Firebase function where the crash occurred, looking for a dependency that might become unable due to code shrinking/obfuscation, etc.
Turns out this was easy to find.

In order to avoid this crash, you need to exclude Json library code from shrinking/obfuscation by adding the following line to your proguard rules file:

-keep class org.json.* { *; }

**Comment by jpg-developer** [comment]
I looked up the source code of Firebase function where the crash occurred, looking for a dependency that might become unable due to code shrinking/obfuscation, etc.
Turns out this was easy to find.

In order to avoid this crash, you need to exclude Json library code from shrinking/obfuscation by adding the following line to your proguard rules file:

-keep class org.json.* { *; }
