### ISSUE TITLE
Firebase Realtime Database - Crash on Xiaomi Blackshark Device - Failed to gain exclusive lock to Firebase Database's offline persistence.

### ISSUE THREAD

**Issue by estiukamobi** [firebase/firebase-android-sdk#2051]
#### Environment

  * Android Studio version: 4.0.1
  * Firebase Component: Realtime Database
  * Component version: 1.3.1

#### Describe the problem

One of our users has frequent crashes when our app starts. This crash is only reported by this user on that particular device. According to the crash reports, it occurs when instantiating Firebase Database. 

#### Steps to reproduce:
Only on Xiaomi - Blackshark devices

- The application starts.
- In our Application onCreate we instantiate Firebase Database
- the application crashes

```
Fatal Exception: java.lang.RuntimeException
       at com.google.firebase.database.android.AndroidPlatform$1$1.run(AndroidPlatform.java:96)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6746)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:499)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by com.google.firebase.database.c: Failed to gain exclusive lock to Firebase Database's offline persistence. This generally means you are using Firebase Database from multiple processes in your app. Keep in mind that multi-process Android apps execute the code in your Application class in all processes, so you may need to avoid initializing FirebaseDatabase in your Application class. If you are intentionally using Firebase Database from multiple processes, you can only enable offline persistence (i.e. call setPersistenceEnabled(true)) in one of them.
       at com.google.firebase.database.android.SqlPersistenceStorageEngine.openDatabase(SqlPersistenceStorageEngine.java:830)
       at com.google.firebase.database.android.SqlPersistenceStorageEngine.<init>(SqlPersistenceStorageEngine.java:214)
       at com.google.firebase.database.android.AndroidPlatform.createPersistenceManager(AndroidPlatform.java:164)
       at com.google.firebase.database.core.Context.getPersistenceManager(Context.java:157)
       at com.google.firebase.database.core.Repo.deferredInitialization(Repo.java:132)
       at com.google.firebase.database.core.Repo.access$000(Repo.java:56)
       at com.google.firebase.database.core.Repo$1.run(Repo.java:95)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)
Caused by android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5 SQLITE_BUSY)
       at android.database.sqlite.SQLiteConnection.nativeExecute(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:569)
       at android.database.sqlite.SQLiteSession.beginTransactionUnchecked(SQLiteSession.java:323)
       at android.database.sqlite.SQLiteSession.beginTransaction(SQLiteSession.java:298)
       at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:549)
       at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:460)
       at com.google.firebase.database.android.SqlPersistenceStorageEngine.openDatabase(SqlPersistenceStorageEngine.java:813)
       at com.google.firebase.database.android.SqlPersistenceStorageEngine.<init>(SqlPersistenceStorageEngine.java:214)
       at com.google.firebase.database.android.AndroidPlatform.createPersistenceManager(AndroidPlatform.java:164)
       at com.google.firebase.database.core.Context.getPersistenceManager(Context.java:157)
       at com.google.firebase.database.core.Repo.deferredInitialization(Repo.java:132)
       at com.google.firebase.database.core.Repo.access$000(Repo.java:56)
       at com.google.firebase.database.core.Repo$1.run(Repo.java:95)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)
```

#### Relevant Code:
The code crashes in `SqlPersistenceStorageEngine.openDatabase(Context context, String cacheId)`
```
      SQLiteDatabase database = helper.getWritableDatabase();

      // Set locking mode to EXCLUSIVE since we don't support multi-process apps using
      // persistence.
      database.rawQuery("PRAGMA locking_mode = EXCLUSIVE", null).close();

      // Apparently the EXCLUSIVE lock is acquired lazily (on first read/write) but then held
      // indefinitely. So do a dummy exclusive transaction to actually acquire the lock.
      database.beginTransaction();
```

Could it be an issue with the PRAGMA query and somehow the app locks itself out from accessing the database? We don't have this issue in any other device, but I have seen some report of a similar issue with Firestore with the same device.

Please note:
- We do not have multiple processes in our application 
- The user has managed to save some data, so I assume it is not a consistent crash but it seems to happen pretty often

**Comment by schmidt-sebastian** [comment]
The device in question supports split screen mode, along with a feature call "Dual Apps". Would it be possible that the user is launching two instances of the same app? This won't work with Firebase's persistence layer, which requires an exclusive lock on its database.
