### ISSUE TITLE
Firebase FireStore collides with Google Cloud Translate, and makes an error.

### ISSUE THREAD

**Issue by tuxxon** [firebase/firebase-android-sdk#2054]
### [READ] Step 1: Are you in the right place?

 Yes. I have read.

Can you help me with the following errors?

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.0.1
  * Firebase Component:  FireStore 
  * Component version: 21.7.1

##### 1. Firestore collides with Google Cloud Translate when making a compile.
    package  =>   com.google.cloud:google-cloud-translate:1.95.2
1) collision 1 
```
Duplicate class com.google.api.Advice found in modules jetified-proto-google-common-protos-1.18.0.jar (com.google.api.grpc:proto-google-common-protos:1.18.0) and jetified-protolite-well-known-types-17.1.0-runtime.jar (com.google.firebase:protolite-well-known-types:17.1.0)
```

2) collision 1 
```
Duplicate class com.google.protobuf.AbstractMessageLite found in modules jetified-protobuf-java-3.12.4.jar (com.google.protobuf:protobuf-java:3.12.4) and jetified-protobuf-javalite-3.12.0.jar (com.google.protobuf:protobuf-javalite:3.12.0)
```

##### 2. Fatal errors occur on running.
  To remove collisions, if using the followings
```
  implementation.exclude(group: 'com.google.firebase', module: 'protolite-well-known-types')
  implementation.exclude(group: 'com.google.protobuf', module: 'protobuf-javalite')
```
I got the following errors
```
2020-10-09 11:28:48.853 23328-23328/com.touchizen.deepshadowing E/ACRA: ACRA caught a RuntimeException for com.touchizen.deepshadowing
    java.lang.RuntimeException: Internal error in Cloud Firestore (21.7.1).
        at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$3(AsyncQueue.java:534)
        at com.google.firebase.firestore.util.AsyncQueue$$Lambda$3.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.VerifyError: Verifier rejected class com.google.firestore.v1.WriteResponse: void com.google.firestore.v1.WriteResponse.mergeCommitTime(com.google.protobuf.Timestamp) failed to verify: void com.google.firestore.v1.WriteResponse.mergeCommitTime(com.google.protobuf.Timestamp): [0x13] register v3 has type Precise Reference: com.google.protobuf.Timestamp but expected Reference: com.google.protobuf.GeneratedMessageLite (declaration of 'com.google.firestore.v1.WriteResponse' appears in /data/app/com.touchizen.deepshadowing-ZoaMVJ8YiEb7uNQCDr1Bkg==/base.apk!classes3.dex)
        at com.google.firestore.v1.WriteResponse.getDefaultInstance(WriteResponse.java:898)
        at com.google.firestore.v1.FirestoreGrpc.getWriteMethod(FirestoreGrpc.java:368)
        at com.google.firebase.firestore.remote.WriteStream.<init>(WriteStream.java:74)
        at com.google.firebase.firestore.remote.Datastore.createWriteStream(Datastore.java:120)
        at com.google.firebase.firestore.remote.RemoteStore.<init>(RemoteStore.java:186)
        at com.google.firebase.firestore.core.MemoryComponentProvider.createRemoteStore(MemoryComponentProvider.java:72)
        at com.google.firebase.firestore.core.ComponentProvider.initialize(ComponentProvider.java:135)
        at com.google.firebase.firestore.core.FirestoreClient.initialize(FirestoreClient.java:249)
        at com.google.firebase.firestore.core.FirestoreClient.lambda$new$0(FirestoreClient.java:96)
        at com.google.firebase.firestore.core.FirestoreClient$$Lambda$1.run(Unknown Source:8)
        at com.google.firebase.firestore.util.AsyncQueue.lambda$enqueue$2(AsyncQueue.java:436)
        at com.google.firebase.firestore.util.AsyncQueue$$Lambda$2.call(Unknown Source:2)
        at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor.lambda$executeAndReportResult$1(AsyncQueue.java:322)
        at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$$Lambda$2.run(Unknown Source:4)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:229)
        at java.lang.Thread.run(Thread.java:764)
2020-10-09 11:28:49.140 1538-1538/? E/SELinux: avc:  denied  { find } for service=meminfo pid=23521 uid=10117 scontext=u:r:untrusted_app:s0:c117,c256,c512,c768 tcontext=u:object_r:meminfo_service:s0 tclass=service_manager permissive=0
```

#### Steps to reproduce:

I got the following errors
```
2020-10-09 11:28:48.853 23328-23328/com.touchizen.deepshadowing E/ACRA: ACRA caught a RuntimeException for com.touchizen.deepshadowing
    java.lang.RuntimeException: Internal error in Cloud Firestore (21.7.1).
        at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$3(AsyncQueue.java:534)
        at com.google.firebase.firestore.util.AsyncQueue$$Lambda$3.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.VerifyError: Verifier rejected class com.google.firestore.v1.WriteResponse: void com.google.firestore.v1.WriteResponse.mergeCommitTime(com.google.protobuf.Timestamp) failed to verify: void com.google.firestore.v1.WriteResponse.mergeCommitTime(com.google.protobuf.Timestamp): [0x13] register v3 has type Precise Reference: com.google.protobuf.Timestamp but expected Reference: com.google.protobuf.GeneratedMessageLite (declaration of 'com.google.firestore.v1.WriteResponse' appears in /data/app/com.touchizen.deepshadowing-ZoaMVJ8YiEb7uNQCDr1Bkg==/base.apk!classes3.dex)
        at com.google.firestore.v1.WriteResponse.getDefaultInstance(WriteResponse.java:898)
        at com.google.firestore.v1.FirestoreGrpc.getWriteMethod(FirestoreGrpc.java:368)
        at com.google.firebase.firestore.remote.WriteStream.<init>(WriteStream.java:74)
        at com.google.firebase.firestore.remote.Datastore.createWriteStream(Datastore.java:120)
        at com.google.firebase.firestore.remote.RemoteStore.<init>(RemoteStore.java:186)
        at com.google.firebase.firestore.core.MemoryComponentProvider.createRemoteStore(MemoryComponentProvider.java:72)
        at com.google.firebase.firestore.core.ComponentProvider.initialize(ComponentProvider.java:135)
        at com.google.firebase.firestore.core.FirestoreClient.initialize(FirestoreClient.java:249)
        at com.google.firebase.firestore.core.FirestoreClient.lambda$new$0(FirestoreClient.java:96)
        at com.google.firebase.firestore.core.FirestoreClient$$Lambda$1.run(Unknown Source:8)
        at com.google.firebase.firestore.util.AsyncQueue.lambda$enqueue$2(AsyncQueue.java:436)
        at com.google.firebase.firestore.util.AsyncQueue$$Lambda$2.call(Unknown Source:2)
        at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor.lambda$executeAndReportResult$1(AsyncQueue.java:322)
        at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$$Lambda$2.run(Unknown Source:4)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:229)
        at java.lang.Thread.run(Thread.java:764)
2020-10-09 11:28:49.140 1538-1538/? E/SELinux: avc:  denied  { find } for service=meminfo pid=23521 uid=10117 scontext=u:r:untrusted_app:s0:c117,c256,c512,c768 tcontext=u:object_r:meminfo_service:s0 tclass=service_manager permissive=0
```

#### Relevant Code:
```
            mRealtimeDatabase = FirebaseDatabase.getInstance().getReference().child(VIDEO_DETAIL_KEY);
            mFirestore = FirebaseFirestore.getInstance();
            mSubtitleDoc = mFirestore.collection("subtitles").document(getVideoId());
            mSubtitleDoc.get().addOnCompleteListener(this);
    /**
     * Events for OnCompleteListener<DocumentSnapshot>().
     */
    @Override
    public void onComplete(@NonNull Task<DocumentSnapshot> task) {
        if (task.isSuccessful()) {
            DocumentSnapshot document = task.getResult();
            if (document.exists()) {
                Log.d(TAG, "=========>DocumentSnapshot data: " + document.getData());
            } else {
                Log.d(TAG, "=========>No such document");
            }
        } else {
            Log.d(TAG, "get failed with ", task.getException());
        }
    }
```

Let me know how to solve this problem.

**Comment by tuxxon** [comment]
https://github.com/googleapis/java-translate/issues/300

**Comment by thebrianchen** [comment]
@tuxxon Thanks for filing an issue!

It appears that you are using the Server SDK's Google Translate with the Firestore Android Client SDK. In general, server SDKs should not be with a client SDK, since your server credentials could be exposed. Could you expand on your use case?

As for the error, the different versions of `protobuf` often have compatibility issues. I can look into some it more and post here again when I find out.

**Comment by tuxxon** [comment]
@thebrianchen  Thanks for your comment.

I will create an API for cloud-translation on server according to your advice.
