### ISSUE TITLE
Firebase Performance NPE During App Start

### ISSUE THREAD

**Issue by jdale38** [firebase/firebase-android-sdk#2055]
### [READ] Step 1: Are you in the right place?

Crash in production app.

### [REQUIRED] Step 2: Describe your environment

  * Firebase Component: Firebase Performance
  * Component version: 19.0.8

### [REQUIRED] Step 3: Describe the problem

NPE crash happening in production.  It appears to be during app start.  Below is the stacktrace:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
       at com.google.android.gms.internal.firebase-perf.zzce.zzu(zzce.java:12)
       at com.google.android.gms.internal.firebase-perf.zzce.zzb(zzce.java:43)
       at com.google.android.gms.internal.firebase-perf.zzce$zza.zzx(zzce.java:13)
       at com.google.firebase.perf.internal.zzf.zzbv(zzf.java:43)
       at com.google.firebase.perf.internal.zzf.zzc(zzf.java:215)
       at com.google.firebase.perf.internal.zze.run(zze.java:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
```

**Comment by vkryachko** [comment]
Does upgrading to the latest version fix the issue? Please re-open this issue if it does not.
