### ISSUE TITLE
SecurityException: Not allowed to bind to service

### ISSUE THREAD

**Issue by brunoescalona** [firebase/firebase-android-sdk#2062]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android studio 4.0
  * Firebase Component: Messaging (Database, Firestore, Storage, Functions, etc)
  * Component version: 20.2.4

#### Steps to reproduce:

I am not able to reproduce the issue, mainly WIKO devices are affected by that one.

![image](https://user-images.githubusercontent.com/23025266/95990621-0c247d80-0e2c-11eb-9d72-5c194feed5e1.png)

#### Relevant Code:

It seems that the Service cannot be bound due to security problems. 
I review my manifest permissions and I am including the `com.google.android.c2dm.permission.RECEIVE` permission, needed for the `com.google.android.c2dm.intent.REGISTER` intent.

```
Fatal Exception: java.lang.SecurityException: Not allowed to bind to service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms }
       at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1741)
       at android.app.ContextImpl.bindService(ContextImpl.java:1651)
       at android.content.ContextWrapper.bindService(ContextWrapper.java:705)
       at com.google.android.gms.common.stats.ConnectionTracker.zza$3e27c581(ConnectionTracker.java:41)
       at com.google.android.gms.common.stats.ConnectionTracker.zza(ConnectionTracker.java:10)
       at com.google.android.gms.common.stats.ConnectionTracker.bindService(ConnectionTracker.java:43)
       at com.google.firebase.iid.MessengerIpcClient$Connection.startConnection(MessengerIpcClient.java:25)
       at com.google.firebase.iid.MessengerIpcClient$Connection.enqueueRequest(MessengerIpcClient.java:9)
       at com.google.firebase.iid.MessengerIpcClient.sendRequest(MessengerIpcClient.java:20)
       at com.google.firebase.iid.MessengerIpcClient.sendOneWayRequest(MessengerIpcClient.java:14)
       at com.google.firebase.messaging.FirebaseMessagingService.ackMessage(FirebaseMessagingService.java:102)
       at com.google.firebase.messaging.FirebaseMessagingService.handleMessageIntent(FirebaseMessagingService.java:32)
       at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(FirebaseMessagingService.java:23)
       at com.google.firebase.messaging.EnhancedIntentService.lambda$processIntent$0$EnhancedIntentService(EnhancedIntentService.java:43)
       at com.google.firebase.messaging.EnhancedIntentService$$Lambda$0.run(EnhancedIntentService.java:2000)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.android.gms.common.util.concurrent.zza.run(zza.java:6)
       at java.lang.Thread.run(Thread.java:919)
```

**Comment by ciarand** [comment]
Hi @brunoescalona, and thanks for the bug report! We're actively looking into similar reports (internal ref b/168922691) that seem to be affecting that same slice of devices, and this gives us another data point indicating it may be something device-specific. We haven't settled on a solution just yet, but the team has proposed a couple of different ideas and hopefully we'll have something to share here soon.

**Comment by brunoescalona** [comment]
Thanks @ciarand! I will wait for the possible solution.

**Comment by cbeyls** [comment]
I noticed the same bug in an application I'm maintaining. So far it only occurred on Wiko View 4 devices running Android 10.

**Comment by IljaGnezdilov** [comment]
Hello. We have the same error too. 
Only three devices prduced this Exception: Wiko View4 Lite, General Mobile GM10, Wiko View4 with Android 10.

**Comment by awenger** [comment]
Hey @ciarand , are there any updates on this issue? Maybe there is already some plan for a mitigation? Or maybe some way to work around and prevent that crash? This problem is the cause of 50% of all crashes we are seeing within our app.

**Comment by awenger** [comment]
Hey @ciarand another 2 weeks passed, any updates? Anything that we could do to fix/work around/debug/help solving this issue? We are counting 50k crashes caused by this problem with our latest release.

**Comment by mateensheikh** [comment]
Hi, we are also facing the same issue.
Devices: 100% QMobile
OS: 100% Android 10

**Comment by brunoescalona** [comment]
Hi! @ciarand could you push a bit this issue? Is one of our main crashes right now.

**Comment by iskugor** [comment]
I also noticed this crash on Cat S42 devices.

**Comment by houssemzaier** [comment]
Hello,
We have the same problem in our app [https://play.google.com/store/apps/details?id=fr.francetv.francetvsport](url)
It crashes on  **Wiko View4** , **Wiko View4 Lite** and **Cat S42** and It is clear that your bug is still not fixed yet.  
Can you please fix it or just respond to us.
Many thanks !!

**Comment by shahabrauf18** [comment]
Hi, We are also facing the same issue on QMobile.
![image](https://user-images.githubusercontent.com/5953527/106705237-66ca2b00-660f-11eb-81c5-5ed8acc7564e.png)

**Comment by brunoescalona** [comment]
Is there any update on that issue?

**Comment by qtehfw** [comment]
Same

<img width="1398" alt="Screen Shot 2021-02-04 at 1 50 44 PM" src="https://user-images.githubusercontent.com/59625999/106838242-02cb6380-66f0-11eb-9a64-8330a5c7554b.png">

**Comment by Albul** [comment]
Same for me, crashed on **Wiko View4**

**Comment by tallior** [comment]
Same issue here. any workaround steps maybe? please update.

**Comment by Ruco** [comment]
Same issue seen on a **HUAWEI ART-L29** running Android 9.

**Comment by iliaskomp** [comment]
Same crash on **CAT S42** / Android 10 devices.

**Comment by goralm128** [comment]
Same crash on Cat S42, Android 10 device

**Comment by 19snow93** [comment]
Same crash on 100% TINNO SUGAR T20,,SUGAR T30, Android 10 device

**Comment by SaikCaskey** [comment]
Wow, I am also seeing this happen to our single **CAT S42 Android 10** user in our production app 😮

**Comment by khushwaqt** [comment]
Same issue.

![image](https://user-images.githubusercontent.com/15142925/113542470-ca67d900-95fd-11eb-91cf-ccace022e40e.png)

**Comment by alim1496** [comment]
getting 100% crash on Symphony android 10 devices

**Comment by sebastianharder** [comment]
Crashes on Cat S42 and Wiko View 4, both Android 10.

**Comment by asiljan** [comment]
Can confirm crashes on Cat S42 too
![Screenshot 2021-04-06 at 13 55 54](https://user-images.githubusercontent.com/17267485/113707235-e6dc4200-96df-11eb-9466-47427c138da6.png)

**Comment by joaquim-verges** [comment]
Hi there, we're seeing the exact same issue on our end, with 5k+ crashes in the pat week.
```
Fatal Exception: java.lang.SecurityException: Not allowed to bind to service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms }
       at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1741)
       at android.app.ContextImpl.bindService(ContextImpl.java:1651)
       at android.content.ContextWrapper.bindService(ContextWrapper.java:705)
       at com.google.android.gms.common.stats.ConnectionTracker.zza(ConnectionTracker.java:30)
       at com.google.android.gms.common.stats.ConnectionTracker.zza(ConnectionTracker.java:10)
       at com.google.android.gms.common.stats.ConnectionTracker.bindService(ConnectionTracker.java:39)
       at com.google.android.gms.cloudmessaging.zzf.zza(zzf.java:17)
       at com.google.android.gms.cloudmessaging.zze.zza(zze.java:18)
       at com.google.android.gms.cloudmessaging.zze.zza(zze.java:12)
       at com.google.android.gms.cloudmessaging.CloudMessagingReceiver.zzb(CloudMessagingReceiver.java:43)
       at com.google.android.gms.cloudmessaging.CloudMessagingReceiver.zza(CloudMessagingReceiver.java:59)
       at com.google.android.gms.cloudmessaging.zzd.run(zzd.java:10)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.android.gms.common.util.concurrent.zza.run(zza.java:6)
       at java.lang.Thread.run(Thread.java:919)
```

Also mainly on Wiko / Cat devices, all on Android 10:

![Screen Shot 2021-04-14 at 4 48 14 PM](https://user-images.githubusercontent.com/3353417/114794373-35718800-9d41-11eb-88b4-71c63e583881.png)

Any updates on this issue would be greatly appreciated

**Comment by adeeljavedch** [comment]
Facing same issue on QMobile devices

<img width="460" alt="Screenshot 2021-04-26 at 5 12 21 PM" src="https://user-images.githubusercontent.com/14270783/116080480-92aaf900-a6b2-11eb-83ca-b7b8ee35dbf3.png">

**Comment by JeremyR34** [comment]
Same issue here, 100% Android 10.

![image](https://user-images.githubusercontent.com/17052863/116555395-a053bf00-a8fc-11eb-985b-0f9f0c8cdadb.png)

**Comment by Mr-hntR** [comment]
Same problem for me during months... it happens on Cat and Wikos and Android only...

<img width="371" alt="wiko" src="https://user-images.githubusercontent.com/10188297/117290309-f03b0480-ae6d-11eb-845a-d045336d03d2.png">

**Comment by Uma1r** [comment]
I am seeing the same crash on one of my apps on only QMobile and WIKO devices on Android 10.
<img width="1101" alt="Screenshot 2021-05-08 at 4 17 58 AM" src="https://user-images.githubusercontent.com/6738304/117517150-824d2500-afb4-11eb-9429-a9743802eee6.png">

**Comment by hussein-yassine** [comment]
I'm seeing the same crash on WIKO View4 Lite, any updates?

**Comment by mattylase** [comment]
Not to pile on, but I'm also still seeing this crash - Wiko View4 Lite and Cat S42 devices.

**Comment by whoislxy** [comment]
I have this problem, how to solve it？

**Comment by JorisNext** [comment]
Same here, Wiko and Cat Android 10.
Could we get an update on the issue @ciarand?
Thank you

**Comment by prashant9934** [comment]
Have the same issue with the specific device - 
 batteryLevel : 42%
brand : lge
charging : false
cpuAbi :
[
  "arm64-v8a",
  "armeabi-v7a",
  "armeabi"
]
dpi : 280
emulator : false
freeDisk : 102.3 GB
freeMemory : 529.9 MB
id : 73aefaa2-3c29-416a-9466-9e933be2993c
jailbroken : false
locale : en_US
locationStatus : allowed
manufacturer : LGE
model : W41 (LM-K610IM)
networkAccess : cellular
orientation : portrait
osName : android
osVersion : 10
runtimeVersions : {
  "androidApiLevel": "29",
  "osBuild": "QP1A.190711.020 release-keys"
}
screenDensity : 1.75
screenResolution : 1442x720
time : 2021-06-17T18:45:19.884Z
totalMemory : 536.9 MB

**Comment by kapilsukhyani** [comment]
Facing the same issue on Wiko, sad to see there have been no activity or suggestion on this issue

**Comment by Jerome-Liger** [comment]
Same here (with View4 and View4 Lite)
It makes more than 10 month this is impacting a lot of us... any update please ?

We need answers to our customers... WE ALL ENCOUNTER PRODUCTION CRITICAL CRASHES !!!

Thanks

**Comment by Jerome-Liger** [comment]
(at least a workaround, or a manner to catch a managedException will be appreciated...)

**Comment by agonist** [comment]
Same here on Wiko View4 and View4 Lite. Android 10.

**Comment by eloisance** [comment]
Same here. 

Did anyone knows how to reproduce, we have a WIKO Lite Android 10 here but can't manage to reproduce it.

<img width="1520" alt="Screenshot 2021-07-26 at 09 41 09" src="https://user-images.githubusercontent.com/5332350/126951358-3645546f-6823-49b0-beea-75c296902526.png">

**Comment by mrana247** [comment]
![Screenshot 2021-08-09 at 11-42-43](https://user-images.githubusercontent.com/13695246/128664567-e2d7e899-0e28-4b33-a4d7-5e9cb103eb87.png)


> Fatal Exception: java.lang.SecurityException: Not allowed to bind to service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms }
       at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1741)
       at android.app.ContextImpl.bindService(ContextImpl.java:1651)
       at android.content.ContextWrapper.bindService(ContextWrapper.java:705)
       at com.google.android.gms.common.stats.ConnectionTracker.zzb(com.google.android.gms:play-services-basement@@17.6.0:11)
       at com.google.android.gms.common.stats.ConnectionTracker.bindService(com.google.android.gms:play-services-basement@@17.6.0:2)
       at com.google.android.gms.cloudmessaging.zzf.zza(com.google.android.gms:play-services-cloud-messaging@@16.0.0:17)
       at com.google.android.gms.cloudmessaging.zze.zza(com.google.android.gms:play-services-cloud-messaging@@16.0.0:18)
       at com.google.android.gms.cloudmessaging.zze.zza(com.google.android.gms:play-services-cloud-messaging@@16.0.0:12)
       at com.google.android.gms.cloudmessaging.CloudMessagingReceiver.zzb(com.google.android.gms:play-services-cloud-messaging@@16.0.0:43)
       at com.google.android.gms.cloudmessaging.CloudMessagingReceiver.zza(com.google.android.gms:play-services-cloud-messaging@@16.0.0:59)
       at com.google.android.gms.cloudmessaging.zzd.run(:10)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@17.6.0:2)
       at java.lang.Thread.run(Thread.java:919)

**Comment by dummy-amit** [comment]
![image](https://user-images.githubusercontent.com/49638809/132178606-df6a5c4b-9232-4f57-81c4-b7891c6174f8.png)

facing for LG devices. Any luck with solution so far?

**Comment by LogeshM-rupeek** [comment]
We are facing the same issue in LG W31 model. Any solution or workaround will be appreciated. Thanks

Fatal Exception: java.lang.SecurityException: Not allowed to bind to service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms }
       at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1741)
       at android.app.ContextImpl.bindService(ContextImpl.java:1651)
       at android.content.ContextWrapper.bindService(ContextWrapper.java:705)
       at com.google.android.gms.common.stats.ConnectionTracker.zza(com.google.android.gms:play-services-basement@@17.5.0:32)
       at com.google.android.gms.common.stats.ConnectionTracker.zza(com.google.android.gms:play-services-basement@@17.5.0:10)
       at com.google.android.gms.common.stats.ConnectionTracker.bindService(com.google.android.gms:play-services-basement@@17.5.0:41)
       at com.google.android.gms.cloudmessaging.zzf.zza(com.google.android.gms:play-services-cloud-messaging@@16.0.0:17)
       at com.google.android.gms.cloudmessaging.zze.zza(com.google.android.gms:play-services-cloud-messaging@@16.0.0:18)
       at com.google.android.gms.cloudmessaging.zze.zza(com.google.android.gms:play-services-cloud-messaging@@16.0.0:12)
       at com.google.android.gms.cloudmessaging.CloudMessagingReceiver.zzb(com.google.android.gms:play-services-cloud-messaging@@16.0.0:43)
       at com.google.android.gms.cloudmessaging.CloudMessagingReceiver.zza(com.google.android.gms:play-services-cloud-messaging@@16.0.0:59)
       at com.google.android.gms.cloudmessaging.zzd.run(:10)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@17.5.0:6)
       at java.lang.Thread.run(Thread.java:919)

**Comment by ciarand** [comment]
I'm no longer working at Google, but when I left this was on the team's radar. I think maybe @gsakakihara may be able to provide an update on the status of b/168922691

**Comment by androideveloper** [comment]
We see a huge spike of this crash from yesterday (Android 10, 96% Wiko devices). Any updates here?

**Comment by gsakakihara** [comment]
We've added a workaround that should stop it from crashing in version 17.0.0 of the play-services-cloud-messaging library. The next release of the FCM SDK should update to use that version of the library, including the workaround. You could try to add that version of the dependency directly, but I believe since the new version of the library contains a breaking change, you may run into incompatibilities with the current version of the FCM SDK and it may not build.

**Comment by yinyangwu** [comment]
![image](https://user-images.githubusercontent.com/7466810/136490759-50d88697-a9a2-4334-a874-e4eb58f76bf8.png)

**Comment by firemaples** [comment]
@gsakakihara Do you mean the version ```com.google.firebase:firebase-messaging:23.0.0``` that contains the workaround?

**Comment by gsakakihara** [comment]
Yes, version 23.0.0 should include the workaround.

**Comment by androideveloper** [comment]
Was there any update on this starting from Nov 13? We see a huge drop in number of crashes here, even without the latest library update (firebase-messaging:23.0.0).

**Comment by gsakakihara** [comment]
No, there isn't anything that I know of that could be changed remotely from our side that would cause the number of crashes to drop.

**Comment by androideveloper** [comment]
Weird. Now it's back again. Let's see if the latest version fixes it..
![Screenshot 2021-11-19 at 15 48 01](https://user-images.githubusercontent.com/1249919/142642125-d2d52eb7-c288-41b9-964a-720c10ae4596.png)
