### ISSUE TITLE
Uncaught exception in Firebase Database runloop (19.5.0)

### ISSUE THREAD

**Issue by imKarthikMuru** [firebase/firebase-android-sdk#2069]
After updating Android Studio 4.1 facing java.lang.RuntimeException: Uncaught exception in Firebase Database runloop (19.5.0). Tried many ways but no use.

#Firebase #1936

**Comment by mandeepsinghn** [comment]
I am getting the same error with the following debug Log:
E/Persistence: Caught Throwable.
    java.lang.AssertionError: hardAssert failed: 
        at com.google.firebase.database.core.utilities.Utilities.hardAssert(Utilities.java:234)
        at com.google.firebase.database.core.utilities.Utilities.hardAssert(Utilities.java:229)
        at com.google.firebase.database.snapshot.ChildrenNode.updateChild(ChildrenNode.java:293)
        at com.google.firebase.database.snapshot.ChildrenNode.updateChild(ChildrenNode.java:296)
        at com.google.firebase.database.snapshot.ChildrenNode.updateChild(ChildrenNode.java:296)
        at com.google.firebase.database.snapshot.ChildrenNode.updateChild(ChildrenNode.java:296)
        at com.google.firebase.database.android.SqlPersistenceStorageEngine.loadNested(SqlPersistenceStorageEngine.java:979)
        at com.google.firebase.database.android.SqlPersistenceStorageEngine.serverCache(SqlPersistenceStorageEngine.java:350)
        at com.google.firebase.database.core.persistence.DefaultPersistenceManager.serverCache(DefaultPersistenceManager.java:160)
        at com.google.firebase.database.core.SyncTree$11.call(SyncTree.java:513)
        at com.google.firebase.database.core.SyncTree$11.call(SyncTree.java:461)
        at com.google.firebase.database.core.persistence.DefaultPersistenceManager.runInTransaction(DefaultPersistenceManager.java:239)
        at com.google.firebase.database.core.SyncTree.addEventRegistration(SyncTree.java:460)
        at com.google.firebase.database.core.SyncTree.keepSynced(SyncTree.java:736)
        at com.google.firebase.database.core.Repo.keepSynced(Repo.java:647)
        at com.google.firebase.database.Query$4.run(Query.java:255)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
E/RunLoop: Uncaught exception in Firebase Database runloop (19.5.0). If you are not already on the latest version of the Firebase SDKs, try updating your dependencies. Should this problem persist, please file a report at https://github.com/firebase/firebase-android-sdk
    java.lang.RuntimeException: java.lang.AssertionError: hardAssert failed: 
        at com.google.firebase.database.core.persistence.DefaultPersistenceManager.runInTransaction(DefaultPersistenceManager.java:244)
        at com.google.firebase.database.core.SyncTree.addEventRegistration(SyncTree.java:460)
        at com.google.firebase.database.core.SyncTree.keepSynced(SyncTree.java:736)
        at com.google.firebase.database.core.Repo.keepSynced(Repo.java:647)
        at com.google.firebase.database.Query$4.run(Query.java:255)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.lang.AssertionError: hardAssert failed: 
        at com.google.firebase.database.core.utilities.Utilities.hardAssert(Utilities.java:234)
        at com.google.firebase.database.core.utilities.Utilities.hardAssert(Utilities.java:229)
        at com.google.firebase.database.snapshot.ChildrenNode.updateChild(ChildrenNode.java:293)
        at com.google.firebase.database.snapshot.ChildrenNode.updateChild(ChildrenNode.java:296)
        at com.google.firebase.database.snapshot.ChildrenNode.updateChild(ChildrenNode.java:296)
        at com.google.firebase.database.snapshot.ChildrenNode.updateChild(ChildrenNode.java:296)
        at com.google.firebase.database.android.SqlPersistenceStorageEngine.loadNested(SqlPersistenceStorageEngine.java:979)
        at com.google.firebase.database.android.SqlPersistenceStorageEngine.serverCache(SqlPersistenceStorageEngine.java:350)
        at com.google.firebase.database.core.persistence.DefaultPersistenceManager.serverCache(DefaultPersistenceManager.java:160)
        at com.google.firebase.database.core.SyncTree$11.call(SyncTree.java:513)
        at com.google.firebase.database.core.SyncTree$11.call(SyncTree.java:461)
        at com.google.firebase.database.core.persistence.DefaultPersistenceManager.runInTransaction(DefaultPersistenceManager.java:239)
        at com.google.firebase.database.core.SyncTree.addEventRegistration(SyncTree.java:460) 
        at com.google.firebase.database.core.SyncTree.keepSynced(SyncTree.java:736) 
        at com.google.firebase.database.core.Repo.keepSynced(Repo.java:647) 
        at com.google.firebase.database.Query$4.run(Query.java:255) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) 

All firebase sdk gradles are latest version:

    implementation 'com.google.firebase:firebase-core:17.5.1'
    implementation 'com.google.firebase:firebase-database:19.5.0'
    implementation 'com.google.firebase:firebase-auth:19.4.0'

**Comment by imKarthikMuru** [comment]
Having same issue.

**Comment by mandeepsinghn** [comment]
> Having the same issue.

@imKarthikMuru If you are using offline support then please comment on that code and try again. Because when I am commenting 

firebaseDatabase.setPersistenceEnabled(true);

In this line my code is working fine.

**Comment by imKarthikMuru** [comment]
Commented all offline capabilities but facing same error

**Comment by schmidt-sebastian** [comment]
Thanks for filing this. We recently got some pushback because we were using Java `assert` statements in our code, which are not used on Android. I updated the latest release to use asserts that may crash the client, and unfortunately, they do. 

As with all asserts, this specific case shouldn't happen and indicates corrupted data. Do either of you use Realtime Database Priorities or keys with the ".priority" name? Do you have data under a ".priority" prefix that is not a number or a string?

**Comment by mandeepsinghn** [comment]
@schmidt-sebastian We are not using ".priority" anywhere in our data. And we are not facing this issue every time but when it comes to the app, the app starts crashing every time, until we uninstall the app and reinstall. One more thing we noticed that if we are commenting firebaseDatabase.setPersistenceEnabled(true);  then it starts working fine.

**Comment by nkpodolyan** [comment]
I am facing same issue, firebaseDatabase.setPersistenceEnabled(true) does not help

java.lang.RuntimeException: Uncaught exception in Firebase Database runloop (19.5.0). If you are not already on the latest version of the Firebase SDKs, try updating your dependencies. Should this problem persist, please file a report at https://github.com/firebase/firebase-android-sdk
        at com.google.firebase.database.android.AndroidPlatform$1$1.run(AndroidPlatform.java:96)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.RuntimeException: java.lang.AssertionError: hardAssert failed: Can't have a merge that is an overwrite
        at com.google.firebase.database.core.persistence.DefaultPersistenceManager.runInTransaction(DefaultPersistenceManager.java:244)
        at com.google.firebase.database.core.SyncTree.applyUserMerge(SyncTree.java:213)
        at com.google.firebase.database.core.Repo.updateChildren(Repo.java:492)
        at com.google.firebase.database.DatabaseReference$3.run(DatabaseReference.java:422)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.AssertionError: hardAssert failed: Can't have a merge that is an overwrite
        at com.google.firebase.database.core.utilities.Utilities.hardAssert(Utilities.java:234)
        at com.google.firebase.database.core.view.ViewProcessor.applyUserMerge(ViewProcessor.java:429)
        at com.google.firebase.database.core.view.ViewProcessor.applyOperation(ViewProcessor.java:106)
        at com.google.firebase.database.core.view.View.applyOperation(View.java:173)
        at com.google.firebase.database.core.SyncPoint.applyOperationToView(SyncPoint.java:78)
        at com.google.firebase.database.core.SyncPoint.applyOperation(SyncPoint.java:109)
        at com.google.firebase.database.core.SyncTree.applyOperationDescendantsHelper(SyncTree.java:970)
        at com.google.firebase.database.core.SyncTree.applyOperationHelper(SyncTree.java:901)
        at com.google.firebase.database.core.SyncTree.applyOperationHelper(SyncTree.java:920)
        at com.google.firebase.database.core.SyncTree.applyOperationHelper(SyncTree.java:920)
        at com.google.firebase.database.core.SyncTree.applyOperationToSyncPoints(SyncTree.java:887)
        at com.google.firebase.database.core.SyncTree.access$400(SyncTree.java:76)
        at com.google.firebase.database.core.SyncTree$2.call(SyncTree.java:222)
        at com.google.firebase.database.core.SyncTree$2.call(SyncTree.java:214)
        at com.google.firebase.database.core.persistence.DefaultPersistenceManager.runInTransaction(DefaultPersistenceManager.java:239)
        at com.google.firebase.database.core.SyncTree.applyUserMerge(SyncTree.java:213) 
        at com.google.firebase.database.core.Repo.updateChildren(Repo.java:492) 
        at com.google.firebase.database.DatabaseReference$3.run(DatabaseReference.java:422) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919)

**Comment by schmidt-sebastian** [comment]
Please downgrade to 19.4.0 while we address this issue.

**Comment by imKarthikMuru** [comment]
> 
> 
> Please downgrade to 19.4.0 while we address this issue.

Tried facing the same.

**Comment by mandeepsinghn** [comment]
@schmidt-sebastian Still we are facing the same issue.

E/Persistence: Caught Throwable.
    java.lang.AssertionError
        at com.google.firebase.database.snapshot.ChildrenNode.updateChild(com.google.firebase:firebase-database@@19.2.1:291)
        at com.google.firebase.database.snapshot.ChildrenNode.updateChild(com.google.firebase:firebase-database@@19.2.1:294)
        at com.google.firebase.database.snapshot.ChildrenNode.updateChild(com.google.firebase:firebase-database@@19.2.1:294)
        at com.google.firebase.database.snapshot.ChildrenNode.updateChild(com.google.firebase:firebase-database@@19.2.1:294)
        at com.google.firebase.database.android.SqlPersistenceStorageEngine.loadNested(com.google.firebase:firebase-database@@19.2.1:978)
        at com.google.firebase.database.android.SqlPersistenceStorageEngine.serverCache(com.google.firebase:firebase-database@@19.2.1:349)
        at com.google.firebase.database.core.persistence.DefaultPersistenceManager.serverCache(com.google.firebase:firebase-database@@19.2.1:158)
        at com.google.firebase.database.core.SyncTree$11.call(com.google.firebase:firebase-database@@19.2.1:516)
        at com.google.firebase.database.core.SyncTree$11.call(com.google.firebase:firebase-database@@19.2.1:464)
        at com.google.firebase.database.core.persistence.DefaultPersistenceManager.runInTransaction(com.google.firebase:firebase-database@@19.2.1:235)
        at com.google.firebase.database.core.SyncTree.addEventRegistration(com.google.firebase:firebase-database@@19.2.1:463)
        at com.google.firebase.database.core.SyncTree.keepSynced(com.google.firebase:firebase-database@@19.2.1:738)
        at com.google.firebase.database.core.Repo.keepSynced(com.google.firebase:firebase-database@@19.2.1:647)
        at com.google.firebase.database.Query$4.run(com.google.firebase:firebase-database@@19.2.1:255)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
I/Choreographer: Skipped 79 frames!  The application may be doing too much work on its main thread.
E/RunLoop: Uncaught exception in Firebase Database runloop (19.2.1). If you are not already on the latest version of the Firebase SDKs, try updating your dependencies. Should this problem persist, please file a report at https://github.com/firebase/firebase-android-sdk
    java.lang.RuntimeException: java.lang.AssertionError
        at com.google.firebase.database.core.persistence.DefaultPersistenceManager.runInTransaction(com.google.firebase:firebase-database@@19.2.1:240)
        at com.google.firebase.database.core.SyncTree.addEventRegistration(com.google.firebase:firebase-database@@19.2.1:463)
        at com.google.firebase.database.core.SyncTree.keepSynced(com.google.firebase:firebase-database@@19.2.1:738)
        at com.google.firebase.database.core.Repo.keepSynced(com.google.firebase:firebase-database@@19.2.1:647)
        at com.google.firebase.database.Query$4.run(com.google.firebase:firebase-database@@19.2.1:255)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.AssertionError
        at com.google.firebase.database.snapshot.ChildrenNode.updateChild(com.google.firebase:firebase-database@@19.2.1:291)
        at com.google.firebase.database.snapshot.ChildrenNode.updateChild(com.google.firebase:firebase-database@@19.2.1:294)
        at com.google.firebase.database.snapshot.ChildrenNode.updateChild(com.google.firebase:firebase-database@@19.2.1:294)
        at com.google.firebase.database.snapshot.ChildrenNode.updateChild(com.google.firebase:firebase-database@@19.2.1:294)
        at com.google.firebase.database.android.SqlPersistenceStorageEngine.loadNested(com.google.firebase:firebase-database@@19.2.1:978)
        at com.google.firebase.database.android.SqlPersistenceStorageEngine.serverCache(com.google.firebase:firebase-database@@19.2.1:349)
        at com.google.firebase.database.core.persistence.DefaultPersistenceManager.serverCache(com.google.firebase:firebase-database@@19.2.1:158)
        at com.google.firebase.database.core.SyncTree$11.call(com.google.firebase:firebase-database@@19.2.1:516)
        at com.google.firebase.database.core.SyncTree$11.call(com.google.firebase:firebase-database@@19.2.1:464)
        at com.google.firebase.database.core.persistence.DefaultPersistenceManager.runInTransaction(com.google.firebase:firebase-database@@19.2.1:235)
        at com.google.firebase.database.core.SyncTree.addEventRegistration(com.google.firebase:firebase-database@@19.2.1:463) 
        at com.google.firebase.database.core.SyncTree.keepSynced(com.google.firebase:firebase-database@@19.2.1:738) 
        at com.google.firebase.database.core.Repo.keepSynced(com.google.firebase:firebase-database@@19.2.1:647) 
        at com.google.firebase.database.Query$4.run(com.google.firebase:firebase-database@@19.2.1:255) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.perceptive.Instadispatch.driver, PID: 27650
    java.lang.RuntimeException: Uncaught exception in Firebase Database runloop (19.2.1). If you are not already on the latest version of the Firebase SDKs, try updating your dependencies. Should this problem persist, please file a report at https://github.com/firebase/firebase-android-sdk
        at com.google.firebase.database.android.AndroidPlatform$1$1.run(com.google.firebase:firebase-database@@19.2.1:96)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.RuntimeException: java.lang.AssertionError
        at com.google.firebase.database.core.persistence.DefaultPersistenceManager.runInTransaction(com.google.firebase:firebase-database@@19.2.1:240)
        at com.google.firebase.database.core.SyncTree.addEventRegistration(com.google.firebase:firebase-database@@19.2.1:463)
        at com.google.firebase.database.core.SyncTree.keepSynced(com.google.firebase:firebase-database@@19.2.1:738)
        at com.google.firebase.database.core.Repo.keepSynced(com.google.firebase:firebase-database@@19.2.1:647)
        at com.google.firebase.database.Query$4.run(com.google.firebase:firebase-database@@19.2.1:255)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.AssertionError
        at com.google.firebase.database.snapshot.ChildrenNode.updateChild(com.google.firebase:firebase-database@@19.2.1:291)
        at com.google.firebase.database.snapshot.ChildrenNode.updateChild(com.google.firebase:firebase-database@@19.2.1:294)
        at com.google.firebase.database.snapshot.ChildrenNode.updateChild(com.google.firebase:firebase-database@@19.2.1:294)
        at com.google.firebase.database.snapshot.ChildrenNode.updateChild(com.google.firebase:firebase-database@@19.2.1:294)
        at com.google.firebase.database.android.SqlPersistenceStorageEngine.loadNested(com.google.firebase:firebase-database@@19.2.1:978)
        at com.google.firebase.database.android.SqlPersistenceStorageEngine.serverCache(com.google.firebase:firebase-database@@19.2.1:349)
        at com.google.firebase.database.core.persistence.DefaultPersistenceManager.serverCache(com.google.firebase:firebase-database@@19.2.1:158)
        at com.google.firebase.database.core.SyncTree$11.call(com.google.firebase:firebase-database@@19.2.1:516)
        at com.google.firebase.database.core.SyncTree$11.call(com.google.firebase:firebase-database@@19.2.1:464)
        at com.google.firebase.database.core.persistence.DefaultPersistenceManager.runInTransaction(com.google.firebase:firebase-database@@19.2.1:235)
        at com.google.firebase.database.core.SyncTree.addEventRegistration(com.google.firebase:firebase-database@@19.2.1:463) 
        at com.google.firebase.database.core.SyncTree.keepSynced(com.google.firebase:firebase-database@@19.2.1:738) 
        at com.google.firebase.database.core.Repo.keepSynced(com.google.firebase:firebase-database@@19.2.1:647) 
        at com.google.firebase.database.Query$4.run(com.google.firebase:firebase-database@@19.2.1:255) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923)

**Comment by nkpodolyan** [comment]
Can confirm that downgrade does not help. I catch this crash initially on 19.4.0 and **then** updated to 19.5.0

**Comment by mandeepsinghn** [comment]
> Can confirm that downgrade does not help. I catch this crash initially on 19.4.0 and **then** updated to 19.5.0

I am using version 19.2.1 but still the same issue. Not downgrade is fixing this issue.

**Comment by perceptive1** [comment]
Same issue here, really need some solution because its impacting a number of live users. 

Regards

**Comment by imKarthikMuru** [comment]
After downgrade Gradle version its working fine.

**Comment by schmidt-sebastian** [comment]
We have released v.19.5.1 of the RTDB SDK that includes #2079.
