### ISSUE TITLE
StrictMode DiskReadViolation at SDK initialization

### ISSUE THREAD

**Issue by carlonzo** [firebase/firebase-android-sdk#2090]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.1
  * Firebase Component: Firebase BOM 25.12.0
  * Components: RemoteConfig, Analytics, FCM, Performance

### [REQUIRED] Step 3: Describe the problem

Hello guys,
we are experiencing quite a few StrictMode policy violations during the Firebase initialization. Most of them are due to Firebase initializing/accessing SharedPreferences from main thread.
Is there anything you can do to lazily/async access the disk?

#### Steps to reproduce:

Here are a few of the logs from the policy violation. There are a few more but I didn't want to spam the thread. Please note that we do not initialize Firebase using the ContentProvider but we manually do it at Application.onCreate.

```
StrictMode policy violation; ~duration=395 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1556)
        at libcore.io.BlockGuardOs.access(BlockGuardOs.java:69)
        at libcore.io.ForwardingOs.access(ForwardingOs.java:73)
        at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:7600)
        at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:281)
        at java.io.File.exists(File.java:820)
        at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:657)
        at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:648)
        at android.app.ContextImpl.getPreferencesDir(ContextImpl.java:604)
        at android.app.ContextImpl.getSharedPreferencesPath(ContextImpl.java:799)
        at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:451)
        at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:178)
        at com.google.firebase.heartbeatinfo.HeartBeatInfoStorage.<init>(HeartBeatInfoStorage.java:37)
        at com.google.firebase.heartbeatinfo.HeartBeatInfoStorage.getInstance(HeartBeatInfoStorage.java:48)
        at com.google.firebase.heartbeatinfo.DefaultHeartBeatInfo.<init>(DefaultHeartBeatInfo.java:30)
        at com.google.firebase.heartbeatinfo.DefaultHeartBeatInfo.lambda$component$0(DefaultHeartBeatInfo.java:57)
        at com.google.firebase.heartbeatinfo.DefaultHeartBeatInfo$$Lambda$1.create(Unknown Source:0)
        at com.google.firebase.components.ComponentRuntime.lambda$new$0(com.google.firebase:firebase-components@@16.0.0:69)
        at com.google.firebase.components.ComponentRuntime$$Lambda$1.get(Unknown Source:4)
        at com.google.firebase.components.Lazy.get(com.google.firebase:firebase-components@@16.0.0:53)
        at com.google.firebase.components.AbstractComponentContainer.get(com.google.firebase:firebase-components@@16.0.0:27)
        at com.google.firebase.components.ComponentRuntime.get(com.google.firebase:firebase-components@@16.0.0:35)
        at com.google.firebase.components.RestrictedComponentContainer.get(com.google.firebase:firebase-components@@16.0.0:83)
        at com.google.firebase.installations.FirebaseInstallationsRegistrar.lambda$getComponents$0(FirebaseInstallationsRegistrar.java:44)
        at com.google.firebase.installations.FirebaseInstallationsRegistrar$$Lambda$1.create(Unknown Source:0)
        at com.google.firebase.components.ComponentRuntime.lambda$new$0(com.google.firebase:firebase-components@@16.0.0:69)
        at com.google.firebase.components.ComponentRuntime$$Lambda$1.get(Unknown Source:4)
        at com.google.firebase.components.Lazy.get(com.google.firebase:firebase-components@@16.0.0:53)
        at com.google.firebase.components.AbstractComponentContainer.get(com.google.firebase:firebase-components@@16.0.0:27)
        at com.google.firebase.components.ComponentRuntime.get(com.google.firebase:firebase-components@@16.0.0:35)
        at com.google.firebase.components.RestrictedComponentContainer.get(com.google.firebase:firebase-components@@16.0.0:83)
        at com.google.firebase.remoteconfig.RemoteConfigRegistrar.lambda$getComponents$0(RemoteConfigRegistrar.java:54)
        at com.google.firebase.remoteconfig.RemoteConfigRegistrar$$Lambda$1.create(Unknown Source:0)
        at com.google.firebase.components.ComponentRuntime.lambda$new$0(com.google.firebase:firebase-components@@16.0.0:69)
        at com.google.firebase.components.ComponentRuntime$$Lambda$1.get(Unknown Source:4)
        at com.google.firebase.components.Lazy.get(com.google.firebase:firebase-components@@16.0.0:53)
        at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(com.google.firebase:firebase-components@@16.0.0:158)
        at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:583)
        at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:304)
        at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:268)
        at com.careem.superapp.core.analytics.impl.firebase.FirebaseInitializer.initialize(FirebaseInitializer.kt:34)
        at com.careem.superapp.miniapp.initialization.BaseSuperApp.onCreate(BaseSuperApp.kt:57)
```

```
StrictMode policy violation; ~duration=393 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1556)
        at libcore.io.BlockGuardOs.access(BlockGuardOs.java:69)
        at libcore.io.ForwardingOs.access(ForwardingOs.java:73)
        at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:7600)
        at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:281)
        at java.io.File.exists(File.java:820)
        at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:657)
        at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:648)
        at android.app.ContextImpl.getFilesDir(ContextImpl.java:693)
        at android.content.ContextWrapper.getFilesDir(ContextWrapper.java:243)
        at com.google.firebase.installations.local.PersistedInstallation.<init>(PersistedInstallation.java:84)
        at com.google.firebase.installations.FirebaseInstallations.<init>(FirebaseInstallations.java:132)
        at com.google.firebase.installations.FirebaseInstallationsRegistrar.lambda$getComponents$0(FirebaseInstallationsRegistrar.java:44)
        at com.google.firebase.installations.FirebaseInstallationsRegistrar$$Lambda$1.create(Unknown Source:0)
        at com.google.firebase.components.ComponentRuntime.lambda$new$0(com.google.firebase:firebase-components@@16.0.0:69)
        at com.google.firebase.components.ComponentRuntime$$Lambda$1.get(Unknown Source:4)
        at com.google.firebase.components.Lazy.get(com.google.firebase:firebase-components@@16.0.0:53)
        at com.google.firebase.components.AbstractComponentContainer.get(com.google.firebase:firebase-components@@16.0.0:27)
        at com.google.firebase.components.ComponentRuntime.get(com.google.firebase:firebase-components@@16.0.0:35)
        at com.google.firebase.components.RestrictedComponentContainer.get(com.google.firebase:firebase-components@@16.0.0:83)
        at com.google.firebase.remoteconfig.RemoteConfigRegistrar.lambda$getComponents$0(RemoteConfigRegistrar.java:54)
        at com.google.firebase.remoteconfig.RemoteConfigRegistrar$$Lambda$1.create(Unknown Source:0)
        at com.google.firebase.components.ComponentRuntime.lambda$new$0(com.google.firebase:firebase-components@@16.0.0:69)
        at com.google.firebase.components.ComponentRuntime$$Lambda$1.get(Unknown Source:4)
        at com.google.firebase.components.Lazy.get(com.google.firebase:firebase-components@@16.0.0:53)
        at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(com.google.firebase:firebase-components@@16.0.0:158)
        at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:583)
        at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:304)
        at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:268)
        at com.careem.superapp.core.analytics.impl.firebase.FirebaseInitializer.initialize(FirebaseInitializer.kt:34)
        at com.careem.superapp.miniapp.initialization.BaseSuperApp.onCreate(BaseSuperApp.kt:57)
        at com.careem.superapp.FlavoredBaseSuperApp.onCreate(FlavoredBaseSuperApp.kt:21)
        at com.careem.superapp.SuperApp.onCreate(SuperApp.kt:40)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1197)

```

```
StrictMode policy violation; ~duration=392 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1556)
        at libcore.io.BlockGuardOs.access(BlockGuardOs.java:69)
        at libcore.io.ForwardingOs.access(ForwardingOs.java:73)
        at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:7600)
        at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:281)
        at java.io.File.exists(File.java:820)
        at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:657)
        at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:648)
        at android.app.ContextImpl.getPreferencesDir(ContextImpl.java:604)
        at android.app.ContextImpl.getSharedPreferencesPath(ContextImpl.java:799)
        at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:451)
        at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:178)
        at com.google.firebase.installations.local.IidStore.<init>(IidStore.java:61)
        at com.google.firebase.installations.FirebaseInstallations.<init>(FirebaseInstallations.java:132)
        at com.google.firebase.installations.FirebaseInstallationsRegistrar.lambda$getComponents$0(FirebaseInstallationsRegistrar.java:44)
        at com.google.firebase.installations.FirebaseInstallationsRegistrar$$Lambda$1.create(Unknown Source:0)
        at com.google.firebase.components.ComponentRuntime.lambda$new$0(com.google.firebase:firebase-components@@16.0.0:69)
        at com.google.firebase.components.ComponentRuntime$$Lambda$1.get(Unknown Source:4)
        at com.google.firebase.components.Lazy.get(com.google.firebase:firebase-components@@16.0.0:53)
        at com.google.firebase.components.AbstractComponentContainer.get(com.google.firebase:firebase-components@@16.0.0:27)
        at com.google.firebase.components.ComponentRuntime.get(com.google.firebase:firebase-components@@16.0.0:35)
        at com.google.firebase.components.RestrictedComponentContainer.get(com.google.firebase:firebase-components@@16.0.0:83)
        at com.google.firebase.remoteconfig.RemoteConfigRegistrar.lambda$getComponents$0(RemoteConfigRegistrar.java:54)
        at com.google.firebase.remoteconfig.RemoteConfigRegistrar$$Lambda$1.create(Unknown Source:0)
        at com.google.firebase.components.ComponentRuntime.lambda$new$0(com.google.firebase:firebase-components@@16.0.0:69)
        at com.google.firebase.components.ComponentRuntime$$Lambda$1.get(Unknown Source:4)
        at com.google.firebase.components.Lazy.get(com.google.firebase:firebase-components@@16.0.0:53)
        at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(com.google.firebase:firebase-components@@16.0.0:158)
        at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:583)
        at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:304)
        at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:268)
        at com.careem.superapp.core.analytics.impl.firebase.FirebaseInitializer.initialize(FirebaseInitializer.kt:34)
        at com.careem.superapp.miniapp.initialization.BaseSuperApp.onCreate(BaseSuperApp.kt:57)
        at com.careem.superapp.FlavoredBaseSuperApp.onCreate(FlavoredBaseSuperApp.kt:21)
        at com.careem.superapp.SuperApp.onCreate(SuperApp.kt:40)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1197)
```

```
StrictMode policy violation; ~duration=390 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1556)
        at libcore.io.BlockGuardOs.access(BlockGuardOs.java:69)
        at libcore.io.ForwardingOs.access(ForwardingOs.java:73)
        at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:7600)
        at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:281)
        at java.io.File.exists(File.java:820)
        at android.app.ContextImpl.getDataDir(ContextImpl.java:2374)
        at android.app.ContextImpl.getPreferencesDir(ContextImpl.java:602)
        at android.app.ContextImpl.getSharedPreferencesPath(ContextImpl.java:799)
        at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:451)
        at com.google.firebase.internal.DataCollectionConfigStorage.<init>(DataCollectionConfigStorage.java:45)
        at com.google.firebase.FirebaseApp.lambda$new$0(FirebaseApp.java:441)
        at com.google.firebase.FirebaseApp$$Lambda$1.get(Unknown Source:4)
        at com.google.firebase.components.Lazy.get(com.google.firebase:firebase-components@@16.0.0:53)
        at com.google.firebase.FirebaseApp.isDataCollectionDefaultEnabled(FirebaseApp.java:375)
        at com.google.firebase.analytics.connector.AnalyticsConnectorImpl.getInstance(com.google.android.gms:play-services-measurement-api@@17.6.0:17)
        at com.google.firebase.analytics.connector.internal.zzc.create(com.google.android.gms:play-services-measurement-api@@17.6.0:6)
        at com.google.firebase.components.ComponentRuntime.lambda$new$0(com.google.firebase:firebase-components@@16.0.0:69)
        at com.google.firebase.components.ComponentRuntime$$Lambda$1.get(Unknown Source:4)
        at com.google.firebase.components.Lazy.get(com.google.firebase:firebase-components@@16.0.0:53)
        at com.google.firebase.components.AbstractComponentContainer.get(com.google.firebase:firebase-components@@16.0.0:27)
        at com.google.firebase.components.ComponentRuntime.get(com.google.firebase:firebase-components@@16.0.0:35)
        at com.google.firebase.components.RestrictedComponentContainer.get(com.google.firebase:firebase-components@@16.0.0:83)
        at com.google.firebase.abt.component.AbtRegistrar.lambda$getComponents$0(AbtRegistrar.java:45)
        at com.google.firebase.abt.component.AbtRegistrar$$Lambda$1.create(Unknown Source:0)
        at com.google.firebase.components.ComponentRuntime.lambda$new$0(com.google.firebase:firebase-components@@16.0.0:69)
        at com.google.firebase.components.ComponentRuntime$$Lambda$1.get(Unknown Source:4)
        at com.google.firebase.components.Lazy.get(com.google.firebase:firebase-components@@16.0.0:53)
        at com.google.firebase.components.AbstractComponentContainer.get(com.google.firebase:firebase-components@@16.0.0:27)
        at com.google.firebase.components.ComponentRuntime.get(com.google.firebase:firebase-components@@16.0.0:35)
        at com.google.firebase.components.RestrictedComponentContainer.get(com.google.firebase:firebase-components@@16.0.0:83)
        at com.google.firebase.remoteconfig.RemoteConfigRegistrar.lambda$getComponents$0(RemoteConfigRegistrar.java:55)
        at com.google.firebase.remoteconfig.RemoteConfigRegistrar$$Lambda$1.create(Unknown Source:0)
        at com.google.firebase.components.ComponentRuntime.lambda$new$0(com.google.firebase:firebase-components@@16.0.0:69)
        at com.google.firebase.components.ComponentRuntime$$Lambda$1.get(Unknown Source:4)
        at com.google.firebase.components.Lazy.get(com.google.firebase:firebase-components@@16.0.0:53)
        at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(com.google.firebase:firebase-components@@16.0.0:158)
        at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:583)
        at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:304)
        at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:268)
        at com.careem.superapp.core.analytics.impl.firebase.FirebaseInitializer.initialize(FirebaseInitializer.kt:34)
        at com.careem.superapp.miniapp.initialization.BaseSuperApp.onCreate(BaseSuperApp.kt:57)
        at com.careem.superapp.FlavoredBaseSuperApp.onCreate(FlavoredBaseSuperApp.kt:21)
```

**Comment by vkryachko** [comment]
Looking at the code, the dependency has been `lazy` since https://github.com/firebase/firebase-android-sdk/pull/1925. so the issue should now be obsolete. Please re-open if you still experience this problem

**Comment by carlonzo** [comment]
Hi @vkryachko I just checked and I see different StrictMode rule violations using Firebase BoM 27.1.0:

```
2021-06-22 22:55:51.880 com.careem.acma.beta D/StrictMode: StrictMode policy violation; ~duration=545 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1596)
        at libcore.io.BlockGuardOs.access(BlockGuardOs.java:71)
        at libcore.io.ForwardingOs.access(ForwardingOs.java:72)
        at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:7858)
        at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:281)
        at java.io.File.exists(File.java:820)
        at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:692)
        at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:683)
        at android.app.ContextImpl.getFilesDir(ContextImpl.java:728)
        at android.content.ContextWrapper.getFilesDir(ContextWrapper.java:253)
        at com.google.firebase.installations.local.PersistedInstallation.<init>(PersistedInstallation.java:84)
        at com.google.firebase.installations.FirebaseInstallations.<init>(FirebaseInstallations.java:140)
        at com.google.firebase.installations.FirebaseInstallationsRegistrar.lambda$getComponents$0(FirebaseInstallationsRegistrar.java:44)
        at com.google.firebase.installations.FirebaseInstallationsRegistrar$$Lambda$1.create(Unknown Source:0)
        at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0(ComponentRuntime.java:132)
        at com.google.firebase.components.ComponentRuntime$$Lambda$1.get(Unknown Source:4)
        at com.google.firebase.components.Lazy.get(Lazy.java:53)
        at com.google.firebase.components.AbstractComponentContainer.get(AbstractComponentContainer.java:27)
        at com.google.firebase.components.ComponentRuntime.get(ComponentRuntime.java:45)
        at com.google.firebase.components.RestrictedComponentContainer.get(RestrictedComponentContainer.java:89)
        at com.google.firebase.iid.Registrar.lambda$getComponents$0$Registrar(com.google.firebase:firebase-iid@@21.1.0:5)
        at com.google.firebase.iid.Registrar$$Lambda$0.create(Unknown Source:0)
        at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0(ComponentRuntime.java:132)
        at com.google.firebase.components.ComponentRuntime$$Lambda$1.get(Unknown Source:4)
        at com.google.firebase.components.Lazy.get(Lazy.java:53)
        at com.google.firebase.components.AbstractComponentContainer.get(AbstractComponentContainer.java:27)
        at com.google.firebase.components.ComponentRuntime.get(ComponentRuntime.java:45)
        at com.google.firebase.components.RestrictedComponentContainer.get(RestrictedComponentContainer.java:89)
        at com.google.firebase.iid.Registrar.lambda$getComponents$1$Registrar(com.google.firebase:firebase-iid@@21.1.0:1)
        at com.google.firebase.iid.Registrar$$Lambda$1.create(Unknown Source:0)
        at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0(ComponentRuntime.java:132)
        at com.google.firebase.components.ComponentRuntime$$Lambda$1.get(Unknown Source:4)
        at com.google.firebase.components.Lazy.get(Lazy.java:53)
        at com.google.firebase.components.AbstractComponentContainer.get(AbstractComponentContainer.java:27)
        at com.google.firebase.components.ComponentRuntime.get(ComponentRuntime.java:45)
        at com.google.firebase.components.RestrictedComponentContainer.get(RestrictedComponentContainer.java:89)
        at com.google.firebase.messaging.FirebaseMessagingRegistrar.lambda$getComponents$0$FirebaseMessagingRegistrar(com.google.firebase:firebase-messaging@@21.1.0:3)
        at com.google.firebase.messaging.FirebaseMessagingRegistrar$$Lambda$0.create(Unknown Source:0)
        at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0(ComponentRuntime.java:132)
        at com.google.firebase.components.ComponentRuntime$$Lambda$1.get(Unknown Source:4)
        at com.google.firebase.components.Lazy.get(Lazy.java:53)
        at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents(ComponentRuntime.java:291)
        at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(ComponentRuntime.java:281)
        at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:584)
2021-06-22 22:55:51.881 com.careem.acma.beta D/StrictMode:     at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:303)
        at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:267)
        at com.careem.superapp.core.analytics.impl.firebase.FirebaseInitializer.initialize(FirebaseInitializer.kt:28)
        at com.careem.superapp.miniapp.initialization.BaseSuperApp.initializeFirebase(BaseSuperApp.kt:93)
        at com.careem.superapp.miniapp.initialization.BaseSuperApp.onCreate(BaseSuperApp.kt:75)
        at com.careem.superapp.FlavoredBaseSuperApp.onCreate(FlavoredBaseSuperApp.kt:33)
        at com.careem.superapp.SuperApp.onCreate(SuperApp.kt:15)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1208)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6986)
        at android.app.ActivityThread.access$1700(ActivityThread.java:274)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2093)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:233)
```

```
2021-06-22 22:55:51.881 com.careem.acma.beta D/StrictMode: StrictMode policy violation; ~duration=544 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1596)
        at libcore.io.BlockGuardOs.access(BlockGuardOs.java:71)
        at libcore.io.ForwardingOs.access(ForwardingOs.java:72)
        at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:7858)
        at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:281)
        at java.io.File.exists(File.java:820)
        at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:692)
        at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:683)
        at android.app.ContextImpl.getPreferencesDir(ContextImpl.java:639)
        at android.app.ContextImpl.getSharedPreferencesPath(ContextImpl.java:864)
        at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:486)
        at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:188)
        at com.google.firebase.installations.local.IidStore.<init>(IidStore.java:61)
        at com.google.firebase.installations.FirebaseInstallations.<init>(FirebaseInstallations.java:142)
        at com.google.firebase.installations.FirebaseInstallationsRegistrar.lambda$getComponents$0(FirebaseInstallationsRegistrar.java:44)
        at com.google.firebase.installations.FirebaseInstallationsRegistrar$$Lambda$1.create(Unknown Source:0)
        at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0(ComponentRuntime.java:132)
        at com.google.firebase.components.ComponentRuntime$$Lambda$1.get(Unknown Source:4)
        at com.google.firebase.components.Lazy.get(Lazy.java:53)
        at com.google.firebase.components.AbstractComponentContainer.get(AbstractComponentContainer.java:27)
        at com.google.firebase.components.ComponentRuntime.get(ComponentRuntime.java:45)
        at com.google.firebase.components.RestrictedComponentContainer.get(RestrictedComponentContainer.java:89)
        at com.google.firebase.iid.Registrar.lambda$getComponents$0$Registrar(com.google.firebase:firebase-iid@@21.1.0:5)
        at com.google.firebase.iid.Registrar$$Lambda$0.create(Unknown Source:0)
        at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0(ComponentRuntime.java:132)
        at com.google.firebase.components.ComponentRuntime$$Lambda$1.get(Unknown Source:4)
        at com.google.firebase.components.Lazy.get(Lazy.java:53)
        at com.google.firebase.components.AbstractComponentContainer.get(AbstractComponentContainer.java:27)
        at com.google.firebase.components.ComponentRuntime.get(ComponentRuntime.java:45)
        at com.google.firebase.components.RestrictedComponentContainer.get(RestrictedComponentContainer.java:89)
        at com.google.firebase.iid.Registrar.lambda$getComponents$1$Registrar(com.google.firebase:firebase-iid@@21.1.0:1)
        at com.google.firebase.iid.Registrar$$Lambda$1.create(Unknown Source:0)
        at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0(ComponentRuntime.java:132)
        at com.google.firebase.components.ComponentRuntime$$Lambda$1.get(Unknown Source:4)
        at com.google.firebase.components.Lazy.get(Lazy.java:53)
        at com.google.firebase.components.AbstractComponentContainer.get(AbstractComponentContainer.java:27)
        at com.google.firebase.components.ComponentRuntime.get(ComponentRuntime.java:45)
        at com.google.firebase.components.RestrictedComponentContainer.get(RestrictedComponentContainer.java:89)
        at com.google.firebase.messaging.FirebaseMessagingRegistrar.lambda$getComponents$0$FirebaseMessagingRegistrar(com.google.firebase:firebase-messaging@@21.1.0:3)
        at com.google.firebase.messaging.FirebaseMessagingRegistrar$$Lambda$0.create(Unknown Source:0)
        at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0(ComponentRuntime.java:132)
        at com.google.firebase.components.ComponentRuntime$$Lambda$1.get(Unknown Source:4)
        at com.google.firebase.components.Lazy.get(Lazy.java:53)
        at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents(ComponentRuntime.java:291)
2021-06-22 22:55:51.882 com.careem.acma.beta D/StrictMode:     at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(ComponentRuntime.java:281)
        at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:584)
        at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:303)
        at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:267)
        at com.careem.superapp.core.analytics.impl.firebase.FirebaseInitializer.initialize(FirebaseInitializer.kt:28)
        at com.careem.superapp.miniapp.initialization.BaseSuperApp.initializeFirebase(BaseSuperApp.kt:93)
        at com.careem.superapp.miniapp.initialization.BaseSuperApp.onCreate(BaseSuperApp.kt:75)
        at com.careem.superapp.FlavoredBaseSuperApp.onCreate(FlavoredBaseSuperApp.kt:33)
        at com.careem.superapp.SuperApp.onCreate(SuperApp.kt:15)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1208)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6986)
        at android.app.ActivityThread.access$1700(ActivityThread.java:274)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2093)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:233)
```

```
2021-06-22 22:55:51.882 com.careem.acma.beta D/StrictMode: StrictMode policy violation; ~duration=542 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1596)
        at libcore.io.BlockGuardOs.access(BlockGuardOs.java:71)
        at libcore.io.ForwardingOs.access(ForwardingOs.java:72)
        at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:7858)
        at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:281)
        at java.io.File.exists(File.java:820)
        at android.app.ContextImpl.getDataDir(ContextImpl.java:2556)
        at android.app.ContextImpl.getNoBackupFilesDir(ContextImpl.java:754)
        at android.content.ContextWrapper.getNoBackupFilesDir(ContextWrapper.java:268)
        at androidx.core.content.ContextCompat$Api21Impl.getNoBackupFilesDir(ContextCompat.java:867)
        at androidx.core.content.ContextCompat.getNoBackupFilesDir(ContextCompat.java:574)
        at com.google.firebase.iid.Store.checkForRestore(com.google.firebase:firebase-iid@@21.1.0:1)
        at com.google.firebase.iid.Store.<init>(com.google.firebase:firebase-iid@@21.1.0:3)
        at com.google.firebase.iid.FirebaseInstanceId.<init>(com.google.firebase:firebase-iid@@21.1.0:4)
        at com.google.firebase.iid.FirebaseInstanceId.<init>(com.google.firebase:firebase-iid@@21.1.0:11)
        at com.google.firebase.iid.Registrar.lambda$getComponents$0$Registrar(com.google.firebase:firebase-iid@@21.1.0:5)
        at com.google.firebase.iid.Registrar$$Lambda$0.create(Unknown Source:0)
        at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0(ComponentRuntime.java:132)
        at com.google.firebase.components.ComponentRuntime$$Lambda$1.get(Unknown Source:4)
        at com.google.firebase.components.Lazy.get(Lazy.java:53)
        at com.google.firebase.components.AbstractComponentContainer.get(AbstractComponentContainer.java:27)
        at com.google.firebase.components.ComponentRuntime.get(ComponentRuntime.java:45)
        at com.google.firebase.components.RestrictedComponentContainer.get(RestrictedComponentContainer.java:89)
        at com.google.firebase.iid.Registrar.lambda$getComponents$1$Registrar(com.google.firebase:firebase-iid@@21.1.0:1)
        at com.google.firebase.iid.Registrar$$Lambda$1.create(Unknown Source:0)
        at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0(ComponentRuntime.java:132)
        at com.google.firebase.components.ComponentRuntime$$Lambda$1.get(Unknown Source:4)
        at com.google.firebase.components.Lazy.get(Lazy.java:53)
        at com.google.firebase.components.AbstractComponentContainer.get(AbstractComponentContainer.java:27)
        at com.google.firebase.components.ComponentRuntime.get(ComponentRuntime.java:45)
        at com.google.firebase.components.RestrictedComponentContainer.get(RestrictedComponentContainer.java:89)
        at com.google.firebase.messaging.FirebaseMessagingRegistrar.lambda$getComponents$0$FirebaseMessagingRegistrar(com.google.firebase:firebase-messaging@@21.1.0:3)
        at com.google.firebase.messaging.FirebaseMessagingRegistrar$$Lambda$0.create(Unknown Source:0)
        at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0(ComponentRuntime.java:132)
        at com.google.firebase.components.ComponentRuntime$$Lambda$1.get(Unknown Source:4)
        at com.google.firebase.components.Lazy.get(Lazy.java:53)
        at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents(ComponentRuntime.java:291)
        at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(ComponentRuntime.java:281)
        at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:584)
        at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:303)
        at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:267)
        at com.careem.superapp.core.analytics.impl.firebase.FirebaseInitializer.initialize(FirebaseInitializer.kt:28)
        at com.careem.superapp.miniapp.initialization.BaseSuperApp.initializeFirebase(BaseSuperApp.kt:93)
        at com.careem.superapp.miniapp.initialization.BaseSuperApp.onCreate(BaseSuperApp.kt:75)
        at com.careem.superapp.FlavoredBaseSuperApp.onCreate(FlavoredBaseSuperApp.kt:33)
2021-06-22 22:55:51.882 com.careem.acma.beta D/StrictMode:     at com.careem.superapp.SuperApp.onCreate(SuperApp.kt:15)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1208)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6986)
        at android.app.ActivityThread.access$1700(ActivityThread.java:274)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2093)
        at android.os.Handler.dispatchMessage(Handler.java:106)
```

**Comment by vkryachko** [comment]
Hi @carlonzo , the latest bom version is `28.1.0` as per https://firebase.google.com/support/release-notes/android . Please upgrade to it
