### ISSUE TITLE
RealCall.kt line 144 okhttp3.RealCall$AsyncCall.run

### ISSUE THREAD

**Issue by bsahana12345** [firebase/firebase-android-sdk#2096]
* Android Studio version: 4.0 
 * Firebase Component: Performance Monitoring
  * Component version: com.google.firebase:firebase-perf:19.0.8
  * Component version: 'com.google.firebase:perf-plugin:1.3.1

### [REQUIRED] Step 3: Describe the problem
Fatal Exception: java.lang.NullPointerException: at index 0
       at com.google.android.gms.internal.firebase-perf.zzq.zza(com.google.firebase:firebase-perf@@19.0.8:17)
       at com.google.android.gms.internal.firebase-perf.zzbm.zzbq(com.google.firebase:firebase-perf@@19.0.8:118)
       at com.google.firebase.perf.network.zzg.zza(com.google.firebase:firebase-perf@@19.0.8:16)
       at com.google.firebase.perf.network.zzh.onFailure(com.google.firebase:firebase-perf@@19.0.8:17)
       at okhttp3.RealCall$AsyncCall.run(RealCall.kt:144)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)

**Comment by raymondlam** [comment]
Created internal tracking ticket b/171730176

**Comment by raymondlam** [comment]
Hi @bsahana12345,

Can you describe when this issue occurs and whether this still occurs in version 19.0.9?
Also, do you have steps to reproduce this issue?

**Comment by bsahana12345** [comment]
Hi,

It occured in  android os version 10
Model:Samsung Galaxy Tab A (8.0", 2019).
I am sorry. There are no steps to reproduce this issue.
I haven't updated to the 19.0.9 version yet. I am using 19.0.8

**Comment by raymondlam** [comment]
I identified and fixed a possible race condition which may have caused the NPE and added a defensive null check as well.

I'll add a followup post once I know which release we plan to include the fix in.

**Comment by raymondlam** [comment]
The fix should be included in the next Firebase Performance release (19.0.10). When it is available, please give it a try.

In the meantime, I'll mark this issue as closed.

**Comment by bsahana12345** [comment]
Thank you.
