### ISSUE TITLE
Firebase Auth crash when R8 full mode obfuscation enabled

### ISSUE THREAD

**Issue by audkar** [firebase/firebase-android-sdk#2124]
### [READ] Step 1: Are you in the right place?

Y

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.0
  * Firebase Component: Auth
  * Component version: 20.0.0

#### Steps to reproduce:

If application is build with `android.enableR8.fullMode=true` then crash happens during login using google Sign-in.
With setting  `android.enableR8.fullMode=false` app runs fine.

Stacktrace:
```
Fatal Exception: com.google.firebase.FirebaseException: An internal error has occurred. [ Instantiation of JsonResponse failed! class com.google.android.gms.internal.firebase-auth-api.zzok ]
       at com.google.firebase.auth.api.internal.zzem.zza(com.google.firebase:firebase-auth@@20.0.0:29)
       at com.google.firebase.auth.api.internal.zzfx.zza(com.google.firebase:firebase-auth@@20.0.0:14)
       at com.google.firebase.auth.api.internal.zzfs.zza(com.google.firebase:firebase-auth@@20.0.0:44)
       at com.google.firebase.auth.api.internal.zzel.zza(com.google.firebase:firebase-auth@@20.0.0:10)
       at com.google.firebase.auth.api.internal.zzac.zza(com.google.firebase:firebase-auth@@20.0.0:2)
       at com.google.android.gms.common.util.DeviceProperties.zza(com.google.android.gms:play-services-basement@@17.1.1:131)
       at com.google.firebase.auth.api.internal.zzfn.zza(com.google.firebase:firebase-auth@@20.0.0:10)
       at com.google.firebase.auth.api.internal.zzep.zza(com.google.firebase:firebase-auth@@20.0.0:53)
       at com.google.firebase.auth.api.internal.zzda.accept(com.google.firebase:firebase-auth@@20.0.0:9)
       at com.google.android.gms.common.api.internal.zaf.zac(com.google.android.gms:play-services-base@@17.1.0:6)
       at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zac(com.google.android.gms:play-services-base@@17.1.0:2)
       at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zab(com.google.android.gms:play-services-base@@17.1.0:5)
       at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zaa(com.google.android.gms:play-services-base@@17.1.0:5)
       at com.google.android.gms.common.api.internal.GoogleApiManager.handleMessage(com.google.android.gms:play-services-base@@17.1.0:113)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at com.google.android.gms.internal.base.zar.dispatchMessage(com.google.android.gms:play-services-base@@17.1.0:1)
       at android.os.Looper.loop(Looper.java:223)
       at android.os.HandlerThread.run(HandlerThread.java:67)
```

#### Relevant Code:

```
val task = GoogleSignIn.getSignedInAccountFromIntent(result.data)
val account = task.getResult(ApiException::class.java)
val auth = FirebaseAuth.getInstance()
val credential = GoogleAuthProvider.getCredential(account.idToken, null)
val firebaseUser = auth.signInWithCredential(credential).await()
```

**Comment by malcolmdeck** [comment]
Hey there! I've filed b/172259754 to track this internally :)

**Comment by malcolmdeck** [comment]
Ok, it appears that this only happens when you use `android.enableR8.fullMode=true` and not `android.enableR8=true`. That's a reasonable workaround while I figure out if there's a way to fix this.

To be noted: I think the root cause is a use of reflection at the network layer of the SDK. I don't yet know how to protect classes when using enableR8, so it's gonna take me a bit to see if this is a fixable problem via something like proguard rules or if I have to see if it's possible to fix the underlying issue itself.

**Comment by b95505017** [comment]
@malcolmdeck  Any update? I don't want to turn off full mode of R8 just because upgrading firebase sdk.

**Comment by devaniumesh** [comment]
same problem here. in firebase latest sdk. When using android.enableR8.fullMode=true . it's release version not working

**Comment by valentynsmetanin** [comment]
It's still reproducing with using
`android.enableR8.fullMode=true`
`com.google.firebase:firebase-bom:26.2.0`
`com.google.firebase:firebase-auth-ktx`

**Comment by benjaminojanne** [comment]
Hello!
I found a solution to the problem. 
Go to proguard-rules.pro file and add this:

-keep class com.google.android.gms.internal.** { *; }

Something is going wrong when the app is being obfuscated.

**Comment by b95505017** [comment]
@benjaminojanne Thanks but I think that will keep so many redundant thinks.

**Comment by b95505017** [comment]
@benjaminojanne It seems that you could specify to the path within auth library 
`-keep class com.google.android.gms.internal.firebase-auth-api.** { *; }`

**Comment by nuhkoca** [comment]
Any update on this without requiring a path?

**Comment by TeGlobal** [comment]
Make sure you have these lines:

`-keep public class com.google.firebase.** {*;}
-keep class com.google.android.gms.internal.** {*;}
-keepclasseswithmembers class com.google.firebase.FirebaseException`

**Comment by ronsivan1** [comment]
> 

Didn't solve it for me

**Comment by iammannan** [comment]
> Make sure you have these lines:
> 
> `-keep public class com.google.firebase.** {*;}` `-keep class com.google.android.gms.internal.** {*;}` `-keepclasseswithmembers class com.google.firebase.FirebaseException`
> 
> Thanks [#2124 (comment)](https://github.com/firebase/firebase-android-sdk/issues/2124#issuecomment-759074412)

thanks, it works

**Comment by ArcherEmiya05** [comment]
> Make sure you have these lines:
> 
> `-keep public class com.google.firebase.** {*;}` `-keep class com.google.android.gms.internal.** {*;}` `-keepclasseswithmembers class com.google.firebase.FirebaseException`
> 
> Thanks [#2124 (comment)](https://github.com/firebase/firebase-android-sdk/issues/2124#issuecomment-759074412)

Is the other rule really necessary? Currently even with this line only in rule seems to solve the issue already.
`-keep class com.google.android.gms.internal.** { *; }`

**Comment by svenjacobs** [comment]
Now that [Android Studio Flamingo](https://android-developers.googleblog.com/2023/04/android-studio-flamingo-is-stable.html) with AGP 8.0 enabled [R8 full mode](https://r8.googlesource.com/r8/+/refs/heads/master/compatibility-faq.md#r8-full-mode) by default, I'm facing the same issue.

Is there any chance the auth library could provide R8 consumer rules in its artifact?

**Comment by tekinarslan** [comment]
@svenjacobs you can add these lines into proguard and it works.

-keep public class com.google.firebase.** {*;}
-keep class com.google.android.gms.internal.** {*;}
-keepclasseswithmembers class com.google.firebase.FirebaseException

**Comment by svenjacobs** [comment]
> @svenjacobs you can add these lines into proguard and it works.
> 
> -keep public class com.google.firebase.** {_;} -keep class com.google.android.gms.internal.** {_;} -keepclasseswithmembers class com.google.firebase.FirebaseException

@tekinarslan I only added this line to my R8 rules as mentioned [here](https://github.com/firebase/firebase-android-sdk/issues/2124#issuecomment-759074412) and it works for me.

```
-keep class com.google.android.gms.internal.** { *; }
```

**Comment by martinbonnin** [comment]
In case a reproducer is needed, this is happening [joreilly/Confetti](https://github.com/joreilly/Confetti) ([Pull Request to keep classes](https://github.com/joreilly/Confetti/pull/647)). 
Same conditions as others: happened after bumping AGP to 8.

**Comment by LeandroLCD** [comment]
> `-keep public class com.google.firebase.** {*;}`
> `-keep class com.google.android.gms.internal.** {*;}`
> `-keepclasseswithmembers class com.google.firebase.FirebaseException`

el problema me persiste al modificar el archivo proguar: 
![image](https://github.com/firebase/firebase-android-sdk/assets/89696212/729632ce-919d-4eac-b253-77341ee6b121)

**Comment by argz777** [comment]
Hi @LeandroLCD, not sure if you're experiencing the same issue here. Could you open a new ticket with details from our template regarding your issue so we can investigate it further? Thanks!

**Comment by argzdev** [comment]
Hi @LeandroLCD, not sure if this is the same issue. Could you file a new ticket with details from our template regarding your issue? Thanks!

**Comment by LouisCAD** [comment]
Hello, this is a particularly sneaky bug, a not nice at all pitfall that Google left on the path of developers AND users.

How close is this to be fixed on Firebase side?

**Comment by LouisCAD** [comment]
I mean, it was reported back in 2020, and despite reports, part of Google itself pulled the trigger to make R8 full mode default in STABLE Android Gradle Plugin, and other part of Google still hasn't reacted…

The consequences aren't great, please, prioritize this show-stopper.

**Comment by prameshj** [comment]
This has been fixed in https://firebase.google.com/support/release-notes/android#auth_v22-1-0
