### ISSUE TITLE
FATAL EXCEPTION: Firebase-Messaging-Intent-Handle  - NoClassDefFoundError: aewt - appearing in Play Store pre-launch reports

### ISSUE THREAD

**Issue by julianD77** [firebase/firebase-android-sdk#2161]
* Android Studio version: 4.1
  * Firebase Component: Messaging 
  * Component version: 20.3.0

### [REQUIRED] Step 3: Describe the problem

The Play Store automated pre-launch reports are highlighting the following issue:

> java.lang.NoClassDefFoundError: aewt
> FATAL EXCEPTION: Firebase-Messaging-Intent-Handle
> Process: com.google.android.youtube, PID: 20760
> java.lang.NoClassDefFoundError: aewt

Other users have also reported this [here](https://stackoverflow.com/questions/64706041/fatal-exception-firebase-messaging-intent-handle-java-lang-noclassdeffounder)

#### Steps to reproduce:

Unsure how to reproduce - the Play store pre-launch report is highlighting the crash affecting the following devices in our cases when the Play stored automated testing takes place for a new release. Presumably this is happening on applicaton launch.

Nothing related to Firebase has changed in this release. The crash was not flagged in earlier pre-launch reports for the previous release.

Nokia 1 - Android 8.1 (SDK 27)
Huawei P8 - Android 5.0 (SDK 21)

#### Relevant Code:

Unclear which code is triggering it but it may just be on launching the App and initialising Firebase.

Please also see related issue raised in the Firebase Unity project [here](https://github.com/firebase/quickstart-unity/issues/861)

Relevant section of `build.gradle` showing Firebase component versions:

```
implementation ('com.google.firebase:firebase-crashlytics:17.2.2')
implementation ('com.google.firebase:firebase-crashlytics-ndk:17.2.2')
implementation 'com.google.firebase:firebase-perf:19.0.9'
implementation 'com.google.firebase:firebase-core:17.5.1'
implementation 'com.google.firebase:firebase-messaging:20.3.0'
```

**Comment by grolschie** [comment]
Issue also raised here:
[https://github.com/firebase/quickstart-unity/issues/861](https://github.com/firebase/quickstart-unity/issues/861)

and
[https://stackoverflow.com/questions/64706041/fatal-exception-firebase-messaging-intent-handle-java-lang-noclassdeffounder](https://stackoverflow.com/questions/64706041/fatal-exception-firebase-messaging-intent-handle-java-lang-noclassdeffounder)

**Comment by julianD77** [comment]
Is it possible that this is an issue affecting the pre-launch reports only and may not occur for production users once the App is released via the Play Store?

**Comment by obendevski** [comment]
Have the same problem.

**Comment by omoflex** [comment]
Exactly same issue am having. I am currently using Xamarin, the weird thing is i get same error in my play store report when i create a blank project using Xamarin on vs 2019, so i am quite certain the problem is not from my code.

**Comment by 8tbl** [comment]
I am facing the same issue, it happened on Nokia 1 when passing Google Play beta-version testing process, by the way, I still have testing results from Nokia 1 with screen video and on the video my app is working fine.

**Comment by gutpela** [comment]
Also started seeing this error on Nov 6th on my google pre launch report.

**Comment by julianD77** [comment]
See comment [here](https://github.com/firebase/quickstart-unity/issues/861#issuecomment-72568685) in the unity sdk repo for essentially the same issue 

> Hi all, sorry that you are experiencing this issue and we are actively looking into what's going on and how to fix this. Please stay tuned.

**Comment by 8tbl** [comment]
@julianD77 I am not sure that it is somehow connected to unity, because I use LibGDX for my projects and still have the same issue, and I hope that this is related only to pre-launch reports and will not affect real users

**Comment by AliaksandrHuryn98** [comment]
Hello all, 

in my case it was related to using of
com.google.android.gms.ads.MobileAds;
com.google.android.gms.ads.initialization.InitializationStatus;
com.google.android.gms.ads.initialization.OnInitializationCompleteListener;

**Comment by mosalex** [comment]
I am facing this issues on pre-launch reports. My question is, do you run ads into your application? I have a feeling that this is related to that. when it want's to run a video ad, then this error appears.

**Comment by AliaksandrHuryn98** [comment]
> d
Check my comment above

**Comment by AliaksandrHuryn98** [comment]
> I am facing this issues on pre-launch reports. My question is, do you run ads into your application? I have a feeling that this is related to that. when it want's to run a video ad, then this error appears.

Check my comment above

**Comment by williamgurzoni** [comment]
> I am facing this issues on pre-launch reports. My question is, do you run ads into your application? I have a feeling that this is related to that. when it want's to run a video ad, then this error appears.

I don't use ads. I think it's related with Google/Firebase authentication.

**Comment by maykon-oliveira** [comment]
I am facing same issue. I use ads and Google/Firebase authentication

```
FATAL EXCEPTION: Firebase-Messaging-Intent-Handle
Process: com.google.android.youtube, PID: 16246
java.lang.NoClassDefFoundError: aewt
	at aewu.b(PG:1)
	at duc.a(PG:230)
	at duc.get(PG:247)
	at aevw.b(PG:1)
	at dud.al(PG:5)
	at dud.aw(PG:4)
	at dud.bg(PG:8)
	at duc.a(PG:232)
	at duc.get(PG:247)
	at afke.a(PG:1)
	at aeri.b(PG:1)
	at dud.fv(PG:4)
	at duc.c(PG:269)
	at duc.get(PG:247)
	at amfk.a(PG:1)
	at eiu.K(PG:5)
	at dud.fV(PG:7)
	at duc.d(PG:334)
	at duc.get(PG:247)
	at com.google.android.apps.youtube.app.common.notification.FcmMessageListenerService.b(PG:1)
	at com.google.firebase.messaging.FirebaseMessagingService.g(PG:53)
	at avgp.run(Unknown Source:7)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at usj.run(PG:2)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ExceptionInInitializerError
	at aewu.b(PG:1)
	at duc.a(PG:230)
	at duc.get(PG:247)
	at aevw.b(PG:1)
	at dud.al(PG:5)
	at duc.a(PG:174)
	at duc.get(PG:247)
	at aeqv.a(PG:6)
	at acpw.b(PG:2)
	at dxe.a(PG:8)
	at dus.onCreate(PG:41)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5767)
	at android.app.ActivityThread.-wrap1(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1680)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6523)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
Caused by: dkp: libelements.so
	at dks.c(PG:52)
	at dkq.a(PG:6)
	at duv.a(Unknown Source:8)
	at avlz.f(PG:8)
	at avlz.e(PG:5)
	at avlz.a(PG:1)
	at wqq.a(PG:1)
	at aewt.<clinit>(PG:1)
	... 21 more
```

**Comment by mosalex** [comment]
My app went live with this error in pre-launch tests. So it must be something from google side. I'll if I catch this in production. Maybe I would have a better stack trace and find a better solution.

**Comment by jonathanm-tkf** [comment]
Same problem here, any solution?

**Comment by FireRiver** [comment]
I have just submitted an enquiry on this FORMALLY to Play Console Support. Let's see what will be their reply.
![submit1](https://user-images.githubusercontent.com/4425173/99162361-1e9a1b80-2738-11eb-9ea6-97621afd0a84.jpg)

**Comment by XanderZehcnas** [comment]
Having the same issue here. If anyone gets a solution or workaround please report it.

**Comment by zjamshidi** [comment]
I'm seeing the same crash in pre-launch report. My app is Android Native, and I have just updated firebase dependencies.

**Comment by zjamshidi** [comment]
Are you all getting this crash after updating Firebase dependencies?

**Comment by FireRiver** [comment]
Hi Zjamshidi,

For your information, I have made a further debugging step:
1. create a barebone app which only display a few lines of text and NO OTHER FUNCTIONS, then submit to Google Play Console.
2. and then the Google Play Console displays "FATAL EXCEPTION: Firebase-Messaging-Intent-Handle Process: com.google.android.youtube" too for Huawei H8 and Nokia 1 too.

Hence, it is quite clear that the problem is NOT code-related, and I belive this is a false alarm on the pre-launch report.

**Comment by julianD77** [comment]
Yes I agree with the @FireRiver above - it seems to be a false alarm. We are not seeing this same issue occur for real users in Crashlytics after releasing the version for which this error was flagged in a Pre-launch report

**Comment by tulundgren** [comment]
My app is also getting this error, and I am not using ads nor analytics nor firebase actually, but I do use google play services for location.
I tend to think this is some problem on Google testing side, and the real problem is that Googles algorithms do not think likewise, so our apps will be penalized in the marketplace.

**Comment by kraazie** [comment]
I am also getting the same error in my pre launch report. It started after Nov 6 submission.
Any leads what to do about this ?

**Comment by samadd** [comment]
I have a game in review that has this same issue. The crash itself only "occurs" on the Huawei P8 device for me, resulting in a stability error, although the video on the report shows the game running with no visible issue. I am using no ads or any services at all - it's a simple Love2D game. Since it's my first attempt at publishing an app to the Play Store, I'm left lingering in review purgatory with no indication as to what is happening. I contacted Google Play support a few days ago to seek clarification as to whether what seems like a false alarm will prevent my app from being published, but as yet no response.

**Comment by paulonteri** [comment]
I can't seem to replicate this problem.
Very strange.

**Comment by 123dma** [comment]
O mesmo Aqui. Acompanhando...

**Comment by ahmedmoussa8** [comment]
The same here on Samsung Note 4, Android SDK 23 
implementation 'com.google.firebase:firebase-messaging:21.0.0'

**Comment by diegoporfirio** [comment]
same error

**Comment by mohamedelshmnhory** [comment]
let minSdkVersion 28 👶

**Comment by adrianoOliveiraRocha** [comment]
I received this error:

FATAL EXCEPTION: Firebase-Messaging-Intent-Handle
Process: com.google.android.youtube, PID: 26385
java.lang.NoClassDefFoundError: aewt
	at aewu.b(PG:1)
	at duc.a(PG:230)
	at duc.get(PG:247)
	at aevw.b(PG:1)
	at dud.al(PG:5)
	at dud.aw(PG:4)
	at dud.bg(PG:8)
	at duc.a(PG:232)
	at duc.get(PG:247)
	at afke.a(PG:1)
	at aeri.b(PG:1)
	at dud.fv(PG:4)
	at duc.c(PG:269)
	at duc.get(PG:247)
	at amfk.a(PG:1)
	at eiu.K(PG:5)
	at dud.fV(PG:7)
	at duc.d(PG:334)
	at duc.get(PG:247)
	at com.google.android.apps.youtube.app.common.notification.FcmMessageListenerService.b(PG:1)
	at com.google.firebase.messaging.FirebaseMessagingService.g(PG:53)
	at avgp.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at usj.run(PG:2)
	at java.lang.Thread.run(Thread.java:831)

Just in this device: 
Huawei P8 青春版, 720x1280, Android 5.0 (SDK 21) 

I am not using firebase. This problem is not in my code. I used react-native with expo.

**Comment by libourel06** [comment]
Hello all,

I also have the same issue, and as i checked on the web I could see out of this page that other people too.
FireRiver did you get answer from Google ?
Because for my two last tickets I submitted to them (not on this same topic) I did not get any answer.

For my app, the error on google play pre-launch report is similar to the previously posted:

FATAL EXCEPTION: Firebase-Messaging-Intent-Handle
Process: com.google.android.youtube, PID: 28146
java.lang.NoClassDefFoundError: aewt
	at aewu.b(PG:1)
	at duc.a(PG:230)
	at duc.get(PG:247)
	at aevw.b(PG:1)
	at dud.al(PG:5)
	at dud.aw(PG:4)
	at dud.bg(PG:8)
	at duc.a(PG:232)
	at duc.get(PG:247)
	at afke.a(PG:1)
	at aeri.b(PG:1)
	at dud.fv(PG:4)
	at duc.c(PG:269)
	at duc.get(PG:247)
	at amfk.a(PG:1)
	at eiu.K(PG:5)
	at dud.fV(PG:7)
	at duc.d(PG:334)
	at duc.get(PG:247)
	at com.google.android.apps.youtube.app.common.notification.FcmMessageListenerService.b(PG:1)
	at com.google.firebase.messaging.FirebaseMessagingService.g(PG:53)
	at avgp.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at usj.run(PG:2)
	at java.lang.Thread.run(Thread.java:831)

I don't use FireBase explicitly in my specific app code, thus I guess this error is raised by a dependency or an api used in the app.
However the trace does not give me a clue where this can happen in my app to reproduce it.

Does anybody have an idea to track this ?

**Comment by libourel06** [comment]
for me it was on device:
Huawei P8 青春版
720x1280
Android 5.0 (SDK 21)
2 048 Mo
ARM64_V8
es_ES

**Comment by salvadorcoronel** [comment]
Same error

FATAL EXCEPTION: Firebase-Messaging-Intent-Handle
Process: com.google.android.youtube, PID: 16402
java.lang.NoClassDefFoundError: aewt

Using targetSdkVersion 29

**Comment by njdullea** [comment]
React Native, TargetSdk 29 and only use firebase dependency for push notifications.

I don't know if it is entirely related, but the minimum target android SDK for playstore was increased to 29 on Nov. 2, right around the time people started experiencing these issues.

**Comment by williamgurzoni** [comment]
> React Native, TargetSdk 29 and only use firebase dependency for push notifications, and have the same error.
> 
> I don't know if it is entirely related, but the minimum target android SDK for playstore was increased to 29 on Nov. 2, right around the time people started experiencing these issues.

Very good point @njdullea, I was thinking the same.

**Comment by pratyesh** [comment]
**Getting Same crash:-**

FATAL EXCEPTION: Firebase-Messaging-Intent-Handle
Process: com.google.android.youtube, PID: 29669
java.lang.NoClassDefFoundError: aewt

Using targetSdkVersion 29

**Device Details:-**
Nokia Nokia 1             480x854        Android 8.1 (SDK 27)       1,024 MB           ARM_V7


Huawei P8 青春版      720x1280     Android 5.0 (SDK 21)    2,048 MB           ARM64_V8

**Comment by libourel06** [comment]
Hello all,

Yesterday my app passed the test on the google play console by putting the following settings in the gradle
        minSdkVersion 26
        targetSdkVersion 29

Before I had minSdkVersion 21 and it got to the error.
However it restricts a lot the number of devices the app can be distributed to.
Thus i will try if any lower minSdkVersion is possible.
Hope this information can help you.

**Comment by libourel06** [comment]
Also I excluded the Huawei P8 device and the Nokia 1 for witch the error was detected for may app in the device catalog in google play menu. However, I think the minSdkVersion is the parameter that solved the issue.

**Comment by libourel06** [comment]
I have to rectify the app passed the test with: Yesterday my app passed the test on the google play console by putting the following settings in the gradle
minSdkVersion 28 (and not 26)
targetSdkVersion 29

By now I had not found other solution.

**Comment by grolschie** [comment]
That is not a solution. You'll lose many potential and existing users don't that.

**Comment by libourel06** [comment]
I know and I agree.
However, I read that developpers have their app deployed despite of this error.
On top of that, the video on google play console for this error does not show any error message or app trouble during the test.

For me I had required a new version with this error on 15 of November but it is still on review as well as the other version i tried to deploy afterward.

I assume that the 7 days of delay for reviewing app start on last version required to deploy.  Thus I don't try to deploy any other version now and way for my last one to exceed the 7 days.
I hope that it will work.

Did you try to deploy your app on production with this unique error ?

**Comment by grolschie** [comment]
My app is in production. It's not a new app, it's an existing app that received this error when uploading a new version. The update with the pre-launch report error is in production (only took an hour or a few hours).

**Comment by libourel06** [comment]
Ok, but the version with the error, did you try to promote it to production or you did not try ?

**Comment by libourel06** [comment]
I you tried i assume you have like me that the app is in review ?
For how long ?

**Comment by grolschie** [comment]
Usually under 3 hours.

**Comment by libourel06** [comment]
You are lucky with your app because mine is not promoted with the error : it remains on review for many days by now. 
I tried to contact the google support on google play and i did not get answer either (despite the 2 business days of answer delay are exceeded).
I guess that if your app is available for your users in production, even with this error,  you don't need to worry since it does not cause error on your app use.

**Comment by tulundgren** [comment]
I excluded Huawei P8 from the list of devices my app targets, then uploaded a new release.
The exception on the Huawei P8 is _still_ reported.

**Comment by libourel06** [comment]
I did the same but tests are performed on this device anyway.
However this error is not preventing your app to be deplaoyed to production (even if this is longer since the process reviww can last some days).

**Comment by team-TLABS** [comment]
> Is it possible that this is an issue affecting the pre-launch reports only and may not occur for production users once the App is released via the Play Store?

I tested my app on different device and I got no error and I decided to release same app for production user. Its about a week and crashlytics haven't reported any issue yet.

**Comment by rh-id** [comment]
Same case with my app, i think it is caused by `com.google.firebase:firebase-ads:19.1.0` my other apps using ads with dependency `com.google.android.gms:play-services-ads:19.5.0` seemed to be fine

**Comment by peterhav** [comment]
> Same case with my app, i think it is caused by `com.google.firebase:firebase-ads:19.1.0` my other apps using ads with dependency `com.google.android.gms:play-services-ads:19.5.0` seemed to be fine

Not for me, I'm still getting this when using version 19.6.0: `implementation 'com.google.android.gms:play-services-ads-lite:19.6.0'`

**Comment by jblancoh** [comment]
As it is solved by removing the strict mode of the API, does anyone know how to do it?

https://issuetracker.google.com/issues/160907013#comment17

**Comment by rh-id** [comment]
> > Same case with my app, i think it is caused by `com.google.firebase:firebase-ads:19.1.0` my other apps using ads with dependency `com.google.android.gms:play-services-ads:19.5.0` seemed to be fine
> 
> Not for me, I'm still getting this when using version 19.6.0: `implementation 'com.google.android.gms:play-services-ads-lite:19.6.0'`

Maybe you should check if there is any firebase dependency. My other app didn't have firebase dependency, and after replacing firebase-ads it doesnt have any issue.

**Comment by khanhpt19** [comment]
Same issue on Nokia 1 and Huawei P8
Anyone pass the review and release app success?

**Comment by team-TLABS** [comment]
@khanhpt19 if your report hasn't any other issue and release passed by google then ignore this issue and rollout your app for production users

**Comment by tulundgren** [comment]
@khanhpt19 I have. The question is, will your apps presence in the play store be the same as if it had zero issues? We dont know that, but I would guess that apps with more issues must be less favoured than apps with fewer issues.

**Comment by khanhpt19** [comment]
@team-TLABS @tulundgren Thanks for your response

**Comment by Chinakangliang** [comment]
FATAL EXCEPTION: Firebase-Messaging-Intent-Handle
Process: com.google.android.youtube, PID: 28391
java.lang.NoClassDefFoundError: aewt
 at aewu.b(PG:1)
 at duc.a(PG:230)
 at duc.get(PG:247)
 at aevw.b(PG:1)
 at dud.al(PG:5)
 at dud.aw(PG:4)
 at dud.bg(PG:8)
 at duc.a(PG:232)
 at duc.get(PG:247)
 at afke.a(PG:1)
 at aeri.b(PG:1)
 at dud.fv(PG:4)
 at duc.c(PG:269)
 at duc.get(PG:247)
 at amfk.a(PG:1)
 at eiu.K(PG:5)
 at dud.fV(PG:7)
 at duc.d(PG:334)
 at duc.get(PG:247)
 at com.google.android.apps.youtube.app.common.notification.FcmMessageListenerService.b(PG:1)
 at com.google.firebase.messaging.FirebaseMessagingService.g(PG:53)
 at avgp.run(Unknown Source)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
 at usj.run(PG:2)
 at java.lang.Thread.run(Thread.java:831)
 华为P8。 该错误不影响程序正常运行，可发布线上版本

**Comment by Mubark-p** [comment]
when add  android.bundle.enableUncompressedNativeLibs=false   in gradle.properties   with minsdk =22 
The error disappeared, but 4warnings appeared as follows:
1- Landroid/util/LongArray;->get(I)J
2- Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J
3- Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray;
4- Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J

**Comment by dlutfrank** [comment]
same error

**Comment by fmiguelmmartins** [comment]
I am having the same issue here too and got no help from google. I am using R8 but I am not using anything to do with firebase. Is there a way to disable this firebase? Min SDK is 21 but I refuse to go a version higher as most tablets use SDK 21.

Huawei P8

`java.lang.NoClassDefFoundError: aewt`

```
FATAL EXCEPTION: Firebase-Messaging-Intent-Handle
Process: com.google.android.youtube, PID: 28287
java.lang.NoClassDefFoundError: aewt
	at aewu.b(PG:1)
	at duc.a(PG:230)
	at duc.get(PG:247)
	at aevw.b(PG:1)
	at dud.al(PG:5)
	at dud.aw(PG:4)
	at dud.bg(PG:8)
	at duc.a(PG:232)
	at duc.get(PG:247)
	at afke.a(PG:1)
	at aeri.b(PG:1)
	at dud.fv(PG:4)
	at duc.c(PG:269)
	at duc.get(PG:247)
	at amfk.a(PG:1)
	at eiu.K(PG:5)
	at dud.fV(PG:7)
	at duc.d(PG:334)
	at duc.get(PG:247)
	at com.google.android.apps.youtube.app.common.notification.FcmMessageListenerService.b(PG:1)
	at com.google.firebase.messaging.FirebaseMessagingService.g(PG:53)
	at avgp.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at usj.run(PG:2)
	at java.lang.Thread.run(Thread.java:831)
```

**Comment by kmadisa** [comment]
I had the same issue and after migrating my flutter project to Android embedding v2 and downgrading the `location` package from `3.2.1` -> `3.0.2` the error was gone. Thought this might be useful.

`flutter doctor -v`

```
[✓] Flutter (Channel stable, 1.22.2, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.2 at /home/developer/flutter
    • Framework revision 84f3d28555 (3 months ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/developer/Android/Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_SDK_ROOT = /home/developer/Android/Sdk
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-0ubuntu1~20.04-b01)
    • All Android licenses accepted.
```

**Comment by mvapldrn** [comment]
Don't know if this is helpful but what happened with me several times is the pre-launch initially mails that everything is ok, but on the website (developer console) shows as failed with exactly the same stacktraces (i.e. the Firebase-Messaging-Intent-Handle etc.) and the process gets stuck in review.

To force, I uploaded a new version of the app in closed testing.. go the same result, then a new version on an alpha track (same result) then went back from targetSDK and compileSDK from 30 to 29 and uploaded directly to production (..sorry..)

Now I received a pre-launch email that there were no errors and my app is in production (super-seeding all the ones in review). Strange thing is, there is no pre-launch report on the developer console website to be found of my latest release (but I do have the email with the results?). Looks like Google is doing something.....

**Comment by larssn** [comment]
@mvapldrn Couldn't you verify by uploading target 29 to one of the testing branches?

**Comment by mvapldrn** [comment]
@larssn As I understand it, if I upload to production (which was number 230), and it is a higher number than whatever is uploaded in beta (had a 229 here), alpha (had a 227 here), internal (something else here), and they were all in review, due to the Firebase bug, then it superceeds all of them and review is finished instantely of all. Which is what happened (or looked like what happened).

What is still strange is that I have a prelaunch report in de mail from 230 (the one that succeeded) butg I cannot find it in the developer console.

Since then I just uploaded 232 in production and got almost an instant publication and pre-launch mail and in the developer console the review can be found.

I hope I have 'reset' something :-)

**Comment by execptionerror** [comment]
[[Already Solved] FATAL EXCEPTION: Firebase-Messaging-Intent-Handle — java.lang.NoClassDefFoundError](https://exerror.com/fatal-exception-firebase-messaging-intent-handle-java-lang-noclassdeffounder/)
