### ISSUE TITLE
java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by appsapiconsole** [firebase/firebase-android-sdk#2170]
Hi,

* Android Studio version: 4.1.1
  * Firebase Component: Crashlytics
  * Component version: 17.2.2

implementation 'com.google.firebase:firebase-ads:19.5.0'
    implementation 'com.google.firebase:firebase-config:20.0.0'
    implementation 'com.google.firebase:firebase-ml-vision:24.1.0'
    implementation 'com.google.firebase:firebase-messaging:21.0.0'
    implementation 'com.google.firebase:firebase-analytics:18.0.0'
    implementation 'com.google.firebase:firebase-crashlytics:17.2.2'

//retrofit
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'
    implementation 'com.squareup.retrofit2:converter-scalars:2.9.0'

Android Version 4.3, 4.2.2, 4.4.4

Fatal Exception: java.lang.ExceptionInInitializerError
       at okhttp3.internal.platform.Platform.get(Platform.java:4)
       at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:4)
       at okhttp3.OkHttpClient.<init>(OkHttpClient.java:4)
       at okhttp3.OkHttpClient.<init>(OkHttpClient.java:1)
       at com.google.firebase.crashlytics.internal.network.HttpRequest.<clinit>(HttpRequest.java:1)
       at com.google.firebase.crashlytics.internal.network.HttpRequestFactory.buildHttpRequest(HttpRequestFactory.java:2)
       at com.google.firebase.crashlytics.internal.common.AbstractSpiCall.getHttpRequest(AbstractSpiCall.java:2)
       at com.google.firebase.crashlytics.internal.settings.network.DefaultSettingsSpiCall.invoke(DefaultSettingsSpiCall.java:5)
       at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:5)
       at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:5)
       at com.google.android.gms.tasks.zzo.run(zzo.java:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java)
       at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java)
       at java.lang.Thread.run(Thread.java:841)

Caused by java.lang.IllegalStateException: Expected Android API level 21+ but was 19
       at okhttp3.internal.platform.AndroidPlatform.buildIfSupported(AndroidPlatform.java:3)
       at okhttp3.internal.platform.Platform.findAndroidPlatform(Platform.java:3)
       at okhttp3.internal.platform.Platform.findPlatform(Platform.java:3)
       at okhttp3.internal.platform.Platform.<clinit>(Platform.java:3)
       at okhttp3.internal.platform.Platform.get(Platform.java:4)
       at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:4)
       at okhttp3.OkHttpClient.<init>(OkHttpClient.java:4)
       at okhttp3.OkHttpClient.<init>(OkHttpClient.java:1)
       at com.google.firebase.crashlytics.internal.network.HttpRequest.<clinit>(HttpRequest.java:1)
       at com.google.firebase.crashlytics.internal.network.HttpRequestFactory.buildHttpRequest(HttpRequestFactory.java:2)
       at com.google.firebase.crashlytics.internal.common.AbstractSpiCall.getHttpRequest(AbstractSpiCall.java:2)
       at com.google.firebase.crashlytics.internal.settings.network.DefaultSettingsSpiCall.invoke(DefaultSettingsSpiCall.java:5)
       at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:5)
       at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:5)
       at com.google.android.gms.tasks.zzo.run(zzo.java:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java)
       at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java)
       at java.lang.Thread.run(Thread.java:841)

Caused by java.lang.NullPointerException: No platform found on Android
       at okhttp3.internal.platform.Platform.findAndroidPlatform(Platform.java:4)
       at okhttp3.internal.platform.Platform.get(Platform.java:4)
       at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:4)
       at okhttp3.OkHttpClient.<init>(OkHttpClient.java:4)
       at okhttp3.OkHttpClient.<init>(OkHttpClient.java:1)
       at com.google.firebase.crashlytics.internal.network.HttpRequest.<clinit>(HttpRequest.java:1)
       at com.google.firebase.crashlytics.internal.network.HttpRequestFactory.buildHttpRequest(HttpRequestFactory.java:2)
       at com.google.firebase.crashlytics.internal.common.AbstractSpiCall.getHttpRequest(AbstractSpiCall.java:2)
       at com.google.firebase.crashlytics.internal.settings.network.DefaultSettingsSpiCall.invoke(DefaultSettingsSpiCall.java:5)
       at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:5)
       at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:5)
       at com.google.android.gms.tasks.zzo.run(zzo.java:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java)
       at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java)
       at java.lang.Thread.run(Thread.java:841)

**Comment by mrwillis21** [comment]
Thanks for reporting this! We'll look into it and let you know what we find. :)

**Comment by prashant-angelbroking** [comment]
Hi,

Facing similar issue

Android Studio : 4.1.1
Firebase crashlytics : 17.3.0
Android api version issue observed on : 28, 29, 30

Stacktrace : 

AndroidRuntime: FATAL EXCEPTION: com.google.firebase.crashlytics.startup1
    Process: com.angelbroking.angelwealth.debug, PID: 5102
    java.lang.ExceptionInInitializerError
        at com.google.firebase.crashlytics.internal.network.HttpRequestFactory.buildHttpRequest(HttpRequestFactory.java:43)
        at com.google.firebase.crashlytics.internal.common.AbstractSpiCall.getHttpRequest(AbstractSpiCall.java:113)
        at com.google.firebase.crashlytics.internal.settings.network.DefaultSettingsSpiCall.invoke(DefaultSettingsSpiCall.java:80)
        at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:200)
        at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:193)
        at com.google.android.gms.tasks.zzo.run(com.google.android.gms:play-services-tasks@@17.2.0:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:64)
        at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:27)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter builder
        at okhttp3.OkHttpClient.<init>(Unknown Source:2)
        at okhttp3.OkHttpClient$Builder.build(OkHttpClient.kt:1069)
        at com.google.firebase.crashlytics.internal.network.HttpRequest.<clinit>(HttpRequest.java:47)
        at com.google.firebase.crashlytics.internal.network.HttpRequestFactory.buildHttpRequest(HttpRequestFactory.java:43) 
        at com.google.firebase.crashlytics.internal.common.AbstractSpiCall.getHttpRequest(AbstractSpiCall.java:113) 
        at com.google.firebase.crashlytics.internal.settings.network.DefaultSettingsSpiCall.invoke(DefaultSettingsSpiCall.java:80) 
        at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:200) 
        at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:193) 
        at com.google.android.gms.tasks.zzo.run(com.google.android.gms:play-services-tasks@@17.2.0:2) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:64) 
        at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:27) 
        at java.lang.Thread.run(Thread.java:923)

**Comment by mrwillis21** [comment]
Hi folks, thanks for the reports. We're currently working on prioritizing updates that should eliminate this problem in the future. Stay tuned.

**Comment by mrwillis21** [comment]
This should be resolved as of Crashlytics version 17.3.1. Please try that out and let us know if you're still having issues. Thanks!
