### ISSUE TITLE
Firebase auth verifyPasswordResetCode fail with internal error

### ISSUE THREAD

**Issue by lcdsmao** [firebase/firebase-android-sdk#2176]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 11
  * Firebase Component: Authentication
  * Component version: 20.0.1

### [REQUIRED] Step 3: Describe the problem

An internal exception occurs when calling `verifyPasswordResetCode`

```
W/AppError$Companion: com.google.firebase.FirebaseException: An internal error has occurred.
        at com.google.android.gms.internal.firebase-auth-api.zzte.zza(com.google.firebase:firebase-auth@@20.0.1:4)
        at com.google.android.gms.internal.firebase-auth-api.zzum.zza(com.google.firebase:firebase-auth@@20.0.1:9)
        at com.google.android.gms.internal.firebase-auth-api.zzun.zzk(com.google.firebase:firebase-auth@@20.0.1:1)
        at com.google.android.gms.internal.firebase-auth-api.zzsv.zzc(com.google.firebase:firebase-auth@@20.0.1:2)
        at com.google.android.gms.internal.firebase-auth-api.zzun.zzl(Unknown Source:0)
        at com.google.android.gms.internal.firebase-auth-api.zzuk.zzg(com.google.firebase:firebase-auth@@20.0.1:2)
        at com.google.android.gms.internal.firebase-auth-api.zztb.zzd(com.google.firebase:firebase-auth@@20.0.1:1)
        at com.google.android.gms.internal.firebase-auth-api.zzob.zzb(Unknown Source:4)
        at com.google.android.gms.internal.firebase-auth-api.zzur.zza(com.google.firebase:firebase-auth@@20.0.1:22)
        at com.google.android.gms.internal.firebase-auth-api.zzub.zzg(com.google.firebase:firebase-auth@@20.0.1:4)
        at com.google.android.gms.internal.firebase-auth-api.zzpj.zzo(com.google.firebase:firebase-auth@@20.0.1:4)
        at com.google.android.gms.internal.firebase-auth-api.zztf.zzr(com.google.firebase:firebase-auth@@20.0.1:6)
        at com.google.android.gms.internal.firebase-auth-api.zzsv.zzd(Unknown Source:15)
        at com.google.android.gms.internal.firebase-auth-api.zzsu.accept(Unknown Source:6)
        at com.google.android.gms.common.api.internal.zacj.doExecute(com.google.android.gms:play-services-base@@17.5.0:2)
        at com.google.android.gms.common.api.internal.zah.zaa(com.google.android.gms:play-services-base@@17.5.0:9)
        at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zac(com.google.android.gms:play-services-base@@17.5.0:193)
        at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zab(com.google.android.gms:play-services-base@@17.5.0:158)
        at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zaa(com.google.android.gms:play-services-base@@17.5.0:126)
        at com.google.android.gms.common.api.internal.GoogleApiManager.handleMessage(com.google.android.gms:play-services-base@@17.5.0:164)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

Authentication version 19.4.0 has no problem. 

#### Relevant Code:

```
val firebaseAuth = FirebaseAuth.getInstance()
suspend fun test(oobCode: String?) {
  firebaseAuth.verifyPasswordResetCode(oobCode).await()
}
```

**Comment by mobee-bill** [comment]
I am also experiencing this issue on my project today.

**Comment by malcolmdeck** [comment]
I was able to reproduce this. I filed b/173637348. You can expect to see this fixed in 20.0.2 whenever that releases

**Comment by atulbhardwaj0900** [comment]
This issue is in 20.0.1 
**Authentication version 19.4.0 is working fine.**
Use  implementation platform('com.google.firebase:firebase-bom:25.11.0') in .gradle. Avoid 20.0.1 till 20.0.2 is released

**Comment by davidmotson** [comment]
Closing as fixed, feel free to re-open if necessary.
