### ISSUE TITLE
Firebase Auth - GetTokenResult.getExpirationTimestamp throws ClassCastException internally

### ISSUE THREAD

**Issue by icarovirtual** [firebase/firebase-android-sdk#2188]
### Describe your environment

  * Android Studio version: 
Android Studio 4.1
Build #AI-201.8743.12.41.6858069, built on September 23, 2020
Runtime version: 1.8.0_242-release-1644-b3-6222593 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: ide.new.welcome.screen.force=true

  * Firebase Component: Auth
  * Component version: `platform('com.google.firebase:firebase-bom:26.0.0')`

### Describe the problem
I'm trying to get the expiration date of an "Id Token" of a Firebase user but whenever I call the method, it throws a `ClassCastException` instead of returning a value.

Here's a sample code of the steps:
```java
// Please consider the case of an existing logged in user with a valid "Id Token"
FirebaseAuth.getInstance().getCurrentUser().getIdToken(false).addOnCompleteListener(new OnCompleteListener<GetTokenResult>() {
    @Override
    public void onComplete(@NonNull Task<GetTokenResult> task) {
        GetTokenResult idTokenInstance = task.getResult();
        String idTokenString = idTokenInstance.getToken();
        // This line crashes
        long expiration = idTokenInstance.getExpirationTimestamp()
    }
});
```

Also the stacktrace:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: br.com.muambator.android, PID: 2694
    java.lang.RuntimeException: Unable to create application br.com.muambator.android.ui.application.MuambatorApplication: java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Integer
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4702)
        at android.app.ActivityThread.access$1500(ActivityThread.java:162)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1409)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5421)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)
     Caused by: java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Integer
        at com.google.firebase.auth.GetTokenResult.zza(com.google.firebase:firebase-auth-interop@@19.0.0:18)
        at com.google.firebase.auth.GetTokenResult.getExpirationTimestamp(com.google.firebase:firebase-auth-interop@@19.0.0:6)
        at br.com.muambator.android.model.User.isIdTokenExpired(User.java:56)
        at io.bode.social.AuthUtil.updateFirebaseIdToken(AuthUtil.java:90)
        at br.com.muambator.android.ui.application.MuambatorApplication.onCreate(MuambatorApplication.java:150)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4699)
        at android.app.ActivityThread.access$1500(ActivityThread.java:162) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1409) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5421) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707) 

```

And a screenshot of the evaluation:
![Screen Shot 2020-11-19 at 18 30 23](https://user-images.githubusercontent.com/1833584/99726611-723c9a00-2a95-11eb-8ad4-7d9cbdfb255e.png)

**Comment by strom2357** [comment]
Thanks for reporting - we're tracking this internally and will follow up if we need more information.

**Comment by PratikBorhade302** [comment]
Hey @icarovirtual , @strom2357 
I would like to work on this issue , could you please help me to get started .

**Comment by icarovirtual** [comment]
As a workaround, you can get the expiration timestamp using the code below:
```java
GetTokenResult idToken = task.getResult();
// Expiration timestamp
long expiration = ((Double) idToken.getClaims().get("exp")).longValue()

// If you want to compare with the current time
// From `import java.util.Calendar;`
long now = Calendar.getInstance().getTimeInMillis() / 1000;
boolean hasExpired = expiration < now;
```

**Comment by malcolmdeck** [comment]
Hey @icarovirtual , I'm failing to reproduce this bug. My JWT bodies (from `GetTokenResult#getToken()`) parse as follows:

```
{
  "provider_id": "anonymous",
  "iss": "https://securetoken.google.com/REDACTED",
  "aud": "REDACTED",
  "auth_time": 1606848941,
  "user_id": "7fWStZtXmDZkFc8e8Gqle88oYs83",
  "sub": "7fWStZtXmDZkFc8e8Gqle88oYs83",
  "iat": 1606848941,
  "exp": 1606852541,
  "firebase": {
    "identities": {},
    "sign_in_provider": "anonymous"
  }
}
```

The `exp` claim is an int, and the library parses it as such. 

A few questions to help me debug this better:

- Can you post either the JWT value of an anonymous account for your project or the parsed body as I have for when you're seeing the failure? I'm curious what the token format looks like on your end, and why we would be getting different token formats from the same server. You can use [JWT.io](https://jwt.io/) to quickly see the result. 
- What provider are you using when you see this error?
- Does this error persist when using 26.1.0?

**Comment by icarovirtual** [comment]
> Hey @icarovirtual , I'm failing to reproduce this bug. My JWT bodies (from `GetTokenResult#getToken()`) parse as follows:
> 
> ```
> {
>   "provider_id": "anonymous",
>   "iss": "https://securetoken.google.com/REDACTED",
>   "aud": "REDACTED",
>   "auth_time": 1606848941,
>   "user_id": "7fWStZtXmDZkFc8e8Gqle88oYs83",
>   "sub": "7fWStZtXmDZkFc8e8Gqle88oYs83",
>   "iat": 1606848941,
>   "exp": 1606852541,
>   "firebase": {
>     "identities": {},
>     "sign_in_provider": "anonymous"
>   }
> }
> ```
> 
> The `exp` claim is an int, and the library parses it as such.
> 
> A few questions to help me debug this better:
> 
> * Can you post either the JWT value of an anonymous account for your project or the parsed body as I have for when you're seeing the failure? I'm curious what the token format looks like on your end, and why we would be getting different token formats from the same server. You can use [JWT.io](https://jwt.io/) to quickly see the result.
> * What provider are you using when you see this error?
> * Does this error persist when using 26.1.0?

Hi @malcolmdeck , thank you for the reply.

Today I was testing again and noticed the behavior you mentioned so it appears everything is fine now.

Maybe I did some Cleaning, Syncing and Rebuilding that removed the previous version which had the problem? 🤔

I can now that using the dependencies below, the functions work as expected:
```groovy
implementation platform('com.google.firebase:firebase-bom:26.1.0')
implementation 'com.google.firebase:firebase-auth'
```
The functions used:
```java
long expirationTimestamp = getTokenResult.getExpirationTimestamp();
```

Thank you for the support!
