### ISSUE TITLE
error loading optionnal module com.google.android.gms.version.ocr

### ISSUE THREAD

**Issue by yuanyang1991** [firebase/firebase-android-sdk#2194]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.0.1
  * Firebase Component: ml text recognize
  * Component version: com.google.firebase:firebase-ml-vision:24.0.3

### [REQUIRED] Step 3: Describe the problem
on some device(redmi 5 pluys(android 8.1.0), Vivo Z3(android 8.1), meizu 6T(andrioid 7.0)),text recognize not work。
stack trace:

2020-11-16 09:21:18.516 13118-13152/? E/TextRecognizerCreator: Error loading optional module com.google.android.gms.vision.ocr
    hb: No acceptable module found. Local version is 0 and remote version is 0.
        at he.d(:com.google.android.gms.dynamite_dynamitemodulesa@204215050@20.42.15 (040406-0):84)
        at com.google.android.gms.vision.text.ChimeraNativeTextRecognizerCreator.c(:com.google.android.gms.dynamite_dynamitemodulesa@204215050@20.42.15 (040406-0):2)
        at com.google.android.gms.vision.text.ChimeraNativeBaseTextRecognizerCreator.b(:com.google.android.gms.dynamite_dynamitemodulesa@204215050@20.42.15 (040406-0):3)
        at kx.u(:com.google.android.gms.dynamite_dynamitemodulesa@204215050@20.42.15 (040406-0):4)
        at am.onTransact(:com.google.android.gms.dynamite_dynamitemodulesa@204215050@20.42.15 (040406-0):4)
        at android.os.Binder.transact(Binder.java:508)
        at com.google.android.gms.internal.vision.zza.a(Unknown Source)
        at com.google.android.gms.internal.vision.zzad.a(Unknown Source)
        at com.google.android.gms.internal.vision.zzak.a(Unknown Source)
        at com.google.android.gms.internal.vision.zzm.d(Unknown Source)
        at com.google.android.gms.internal.vision.zzm.a(Unknown Source)
        at com.google.android.gms.vision.text.TextRecognizer.b(Unknown Source)
        at com.google.android.gms.internal.firebase_ml.zzra.zzd(Unknown Source)
        at com.google.android.gms.internal.firebase_ml.zzra.zza(Unknown Source)
        at com.google.android.gms.internal.firebase_ml.zznt.call(Unknown Source)
        at com.google.android.gms.internal.firebase_ml.zznn.zza(Unknown Source)
        at com.google.android.gms.internal.firebase_ml.zznq.run(Unknown Source)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at com.google.android.gms.internal.firebase_ml.zzf.dispatchMessage(Unknown Source)
        at android.os.Looper.loop(Looper.java:203)
        at android.os.HandlerThread.run(HandlerThread.java:61)

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by rlazo** [comment]
Hi @yuanyang1991 MLKit has updated and now it hosted as a separated product. Take a look at [the migration guide](https://developers.google.com/ml-kit/migration) to get started. Also, if you find issues with it, please report them to the [ml kit repo](https://github.com/googlesamples/mlkit).

Thanks!
