### ISSUE TITLE
Auth UI crash: ActivityNotFoundException: No Activity found to handle null

### ISSUE THREAD

**Issue by edenman** [firebase/firebase-android-sdk#2197]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio 4.2 Canary 15
  * Firebase Component: Auth 6.2.0, Messaging 20.2.3

#### Steps to reproduce:

I haven't repro'd this myself, it came in via Sentry.  There's none of my code in the stacktrace.

#### Relevant Code:

Breadcrumbs before the crash:
```
onActivityDestroyed class com.firebase.ui.auth.KickoffActivity 42604145 
ui.lifecycle state: stopped screen: MainActivity
ui.lifecycle state: saveInstanceState screen: MainActivity
ui.lifecycle state: stopped screen: KickoffActivity
ui.lifecycle state: saveInstanceState screen: KickoffActivity
ui.lifecycle state: paused screen: AuthMethodPickerActivity
onActivityPaused class com.firebase.ui.auth.ui.idp.AuthMethodPickerActivity 19992921 
ui.lifecycle state: created screen: EmailActivity
onActivityCreated class com.firebase.ui.auth.ui.email.EmailActivity 189888988 
ui.lifecycle state: started screen: EmailActivity
```
Stacktrace
```
android.content.ActivityNotFoundException: No Activity found to handle null
    at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2058)
    at android.app.Activity.startIntentSenderForResultInner(Activity.java:5473)
    at android.app.Activity.startIntentSenderForResult(Activity.java:5439)
    at androidx.activity.ComponentActivity.startIntentSenderForResult(ComponentActivity.java:602)
    at androidx.core.app.ActivityCompat.startIntentSenderForResult(ActivityCompat.java:274)
    at androidx.activity.ComponentActivity$2.onLaunch(ComponentActivity.java:200)
    at androidx.activity.result.ActivityResultRegistry$4.launch(ActivityResultRegistry.java:198)
    at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.java:42)
    at androidx.fragment.app.FragmentManager.launchStartIntentSenderForResult(FragmentManager.java:3012)
    at androidx.fragment.app.Fragment.startIntentSenderForResult(Fragment.java:1448)
    at com.firebase.ui.auth.util.ui.FlowUtils.startIntentSenderForResult(FlowUtils.java:64)
    at com.firebase.ui.auth.util.ui.FlowUtils.unhandled(FlowUtils.java:42)
    at com.firebase.ui.auth.viewmodel.ResourceObserver.onChanged(ResourceObserver.java:76)
    at com.firebase.ui.auth.viewmodel.ResourceObserver.onChanged(ResourceObserver.java:19)
    at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
    at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:146)
    at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:468)
    at androidx.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:425)
    at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
    at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:265)
    at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:307)
    at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
    at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
    at androidx.fragment.app.Fragment.performStart(Fragment.java:2998)
    at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:606)
    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:308)
    at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
    at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1632)
    at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3109)
    at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:3060)
    at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:262)
    at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:482)
    at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1432)
    at android.app.Activity.performStart(Activity.java:7847)
    at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3294)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7356)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```

**Comment by edenman** [comment]
Nevermind, didn't realize auth UI had its own repo, filed over there instead: https://github.com/firebase/FirebaseUI-Android/issues/1873
