### ISSUE TITLE
Android crash on Receiver not registered: com.google.firebase.iid.SyncTask$ConnectivityChangeReceiver@8afefb4

### ISSUE THREAD

**Issue by ratar0005** [firebase/firebase-android-sdk#2202]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2018.4.22f1
  * Firebase Unity SDK version: 6.16.1
  * Source you installed the SDK: Unity Package Manager)
  * Problematic Firebase Component: Messaging, Crashlytics (not sure which one but crashlytics seems to working)
  * Other Firebase Components in use: Messaging, Crashlytics
  * Additional SDKs you are using: Facebook, Adjust, Google Play 
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:
I recently released an update to google play store and got this error.
In this new version, I updated ...
- com.google.firebase.app             from 6.15.2 to 6.16.1
- com.google.firebase.messaging  from 6.15.2 to 6.16.1
- com.google.play.common           from 1.2.0   to 1.3.0
- com.google.play.core                  from 1.2.0   to 1.3.0
- com.google.external-dependency-manager from 1.2.159 to 1.2.161
And I installed 
- com.google.firebase.crashlytics   6.16.1

This is stack trace copy from Crashlytics

> Caused by java.lang.RuntimeException
> Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4200010 (has extras) } in com.google.firebase.iid.SyncTask$ConnectivityChangeReceiver@8afefb4
> android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args
> Caused by java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4200010 (has extras) } in com.google.firebase.iid.SyncTask$ConnectivityChangeReceiver@8afefb4
>        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1566)
>        at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(:2)
>        at android.os.Handler.handleCallback(Handler.java:883)
>        at android.os.Handler.dispatchMessage(Handler.java:100)
>        at android.os.Looper.loop(Looper.java:224)
>        at android.app.ActivityThread.main(ActivityThread.java:7561)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
> 
> Caused by java.lang.IllegalArgumentException
> Receiver not registered: com.google.firebase.iid.SyncTask$ConnectivityChangeReceiver@8afefb4
> android.app.LoadedApk.forgetReceiverDispatcher
> Caused by java.lang.IllegalArgumentException: Receiver not registered: com.google.firebase.iid.SyncTask$ConnectivityChangeReceiver@8afefb4
>        at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1433)
>        at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1554)
>        at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:674)
>        at com.google.firebase.iid.SyncTask$ConnectivityChangeReceiver.onReceive(com.google.firebase:firebase-iid@@20.2.3:6)
>        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1556)
>        at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(:2)
>        at android.os.Handler.handleCallback(Handler.java:883)
>        at android.os.Handler.dispatchMessage(Handler.java:100)
>        at android.os.Looper.loop(Looper.java:224)
>        at android.app.ActivityThread.main(ActivityThread.java:7561)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)

I can't reproduce on my end. I haven't receive any feedback about users getting crash or anything. I only saw crashes from Google Play console and Crashlytics report.
It seems to happen on various devices; samsung, xiaomi, huawei, etc and on various android versions; 5.1, 8, 9, 10.

And it seems to related to this https://github.com/firebase/firebase-android-sdk/issues/956

**Comment by chkuang-g** [comment]
Dear Android team,

This seems to be an issue in IID when the user is using Messaging and Crashlytics, which have similar behavior to #956

To safe your time, Firebase Unity SDK `6.16.1` depends on Android SDK

-  'com.google.android.gms:play-services-base:17.4.0' 
-  'com.google.firebase:firebase-common:19.3.1' 
-  'com.google.firebase:firebase-crashlytics:17.2.2' 
-  'com.google.firebase:firebase-messaging:20.2.4' 

Is this an issue under your radar?  Is it a wont-fix since IID is deprecated?

Thanks,
Shawn
