### ISSUE TITLE
StrictMode UNTAGGED_SOCKET in FirebaseInstallationServiceClient

### ISSUE THREAD

**Issue by regisd** [firebase/firebase-android-sdk#2227]
### [READ] Step 1: Are you in the right place?

yes. Issue in [FirebaseInstallationServiceClient](https://github.com/firebase/firebase-android-sdk/blob/e568cc0fd1b5b62826acd29ac084e27be983a7ce/firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java)

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: N/A
  * Firebase Component: __firebase-installations__
  * Component version: __f30152eae2932bb2a540a95ffe81ec4d566b35da__ (HEAD [cl/336921685](http://cl/336921685))

#### Steps to reproduce:

1. Enable Strictmode
2. Start app that depends on firebase-installations

#### Relevant Code:

N/A

#### Logcat

```
java.lang.Throwable: Untagged socket detected; use TrafficStats.setThreadSocketTag() to track all network usage
at android.os.StrictMode.onUntaggedSocket(StrictMode.java:2010)
at com.android.server.NetworkManagementSocketTagger.tag(NetworkManagementSocketTagger.java:78)
at libcore.io.BlockGuardOs.tagSocket(BlockGuardOs.java:47)
at libcore.io.BlockGuardOs.socket(BlockGuardOs.java:310)
at libcore.io.IoBridge.socket(IoBridge.java:667)
at java.net.PlainSocketImpl.socketCreate(PlainSocketImpl.java:116)
at java.net.AbstractPlainSocketImpl.create(AbstractPlainSocketImpl.java:98)
at java.net.Socket.createImpl(Socket.java:484)
at java.net.Socket.getImpl(Socket.java:547)
at java.net.Socket.setSoTimeout(Socket.java:1175)
at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:139)
at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:258)
at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(Unknown Source:0)
at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.writeRequestBodyToOutputStream(FirebaseInstallationServiceClient.java:226)
at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.writeFIDCreateRequestBodyToOutputStream(FirebaseInstallationServiceClient.java:208)
at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.createFirebaseInstallation(FirebaseInstallationServiceClient.java:167)
at com.google.firebase.installations.FirebaseInstallations.registerFidWithServer(FirebaseInstallations.java:490)
at com.google.firebase.installations.FirebaseInstallations.doNetworkCallIfNecessary(FirebaseInstallations.java:361)
at com.google.firebase.installations.FirebaseInstallations.lambda$doRegistrationOrRefresh$2$FirebaseInstallations(FirebaseInstallations.java:351)
at com.google.firebase.installations.FirebaseInstallations$$Lambda$3.run(Unknown Source:4)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)
```

**Comment by regisd** [comment]
Googlers only: (b/173995661)[https://b.corp.google.com/issues/173995661)

**Comment by ankitaj224** [comment]
This is an underlying OkHttp library issue. FirebaseInstallations SDK uses the default transport library for HttpUrlConnection. The untagged socket issue has no side effects other than the warning  and will not be fixed for time being in the [Okhttp library](https://github.com/square/okhttp/issues/3537).

Thanks, Ankita

**Comment by regisd** [comment]
OKHttp doesn't spontaneously issue HTTP requests cannot know what is the content it transports. The tagging should be done by GMS. Please reopen.

**Comment by regisd** [comment]
Related to / Possible duplicate of #1133
