### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException Serializing com.google.firebase.perf.v1.PerfMetric to a byte array threw an IOException (should never happen).

### ISSUE THREAD

**Issue by cjohnrajan** [firebase/firebase-android-sdk#2268]
* Android Studio version: 
  3.6.2
  * Firebase Component: 
   implementation 'com.google.firebase:firebase-perf:19.0.9'
    implementation 'com.google.firebase:firebase-analytics:18.0.0'
    com.google.firebase:firebase-messaging:21.0.0
   
 

### [ISSUE] 

Application randomly crashes with the below crash logs from Firebase Performance library

#### Steps to reproduce:

No steps to reporoduce as we see this happen randomly once in a while.

Logs: 
Fatal Exception: java.lang.RuntimeException: Serializing com.google.firebase.perf.v1.PerfMetric to a byte array threw an IOException (should never happen).
       at o.getRemoteInputs.toByteArray(:75)
       at com.google.firebase.perf.internal.FirebasePerfClearcutLogger.syncLog(:338)
       at com.google.firebase.perf.internal.FirebasePerfClearcutLogger.syncLog(:439)
       at com.google.firebase.perf.internal.FirebasePerfClearcutLogger.access$200(:62)
       at com.google.firebase.perf.internal.FirebasePerfClearcutLogger$3.run(:216)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)
       
Caused by com.google.protobuf.CodedOutputStream$OutOfSpaceException: CodedOutputStream was writing to a flat byte array and ran out of space.: Pos: 233, limit: 232, len: 1
       at com.google.protobuf.CodedOutputStream$cancel.writeUInt32NoTag(:1378)
       at com.google.protobuf.CodedOutputStream$cancel.writeTag(:1174)
       at com.google.protobuf.CodedOutputStream$cancel.INotificationSideChannel(:1280)
       at o.getDeleteIntent.writeMessage(:154)
       at o.getDeleteIntent.writeMessageList(:560)
       at o.attachInfo.writeMessageList(:304)
       at o.getEnabledListenerPackages.cancel(:2709)
       at o.getEnabledListenerPackages.writeTo(:2535)
       at com.google.protobuf.CodedOutputStream$cancel.INotificationSideChannel(:1282)
       at o.getDeleteIntent.writeMessage(:154)
       at o.getEnabledListenerPackages.cancel(:2628)
       at o.getEnabledListenerPackages.writeTo(:2535)
       at o.setTicker.writeTo(:268)
       at o.getRemoteInputs.toByteArray(:71)
       at com.google.firebase.perf.internal.FirebasePerfClearcutLogger.syncLog(:338)
       at com.google.firebase.perf.internal.FirebasePerfClearcutLogger.syncLog(:439)
       at com.google.firebase.perf.internal.FirebasePerfClearcutLogger.access$200(:62)
       at com.google.firebase.perf.internal.FirebasePerfClearcutLogger$3.run(:216)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)

Caused by java.lang.ArrayIndexOutOfBoundsException: length=232; index=232
       at com.google.protobuf.CodedOutputStream$cancel.writeUInt32NoTag(:1369)
       at com.google.protobuf.CodedOutputStream$cancel.writeTag(:1174)
       at com.google.protobuf.CodedOutputStream$cancel.INotificationSideChannel(:1280)
       at o.getDeleteIntent.writeMessage(:154)
       at o.getDeleteIntent.writeMessageList(:560)
       at o.attachInfo.writeMessageList(:304)
       at o.getEnabledListenerPackages.cancel(:2709)
       at o.getEnabledListenerPackages.writeTo(:2535)
       at com.google.protobuf.CodedOutputStream$cancel.INotificationSideChannel(:1282)
       at o.getDeleteIntent.writeMessage(:154)
       at o.getEnabledListenerPackages.cancel(:2628)
       at o.getEnabledListenerPackages.writeTo(:2535)
       at o.setTicker.writeTo(:268)
       at o.getRemoteInputs.toByteArray(:71)
       at com.google.firebase.perf.internal.FirebasePerfClearcutLogger.syncLog(:338)
       at com.google.firebase.perf.internal.FirebasePerfClearcutLogger.syncLog(:439)
       at com.google.firebase.perf.internal.FirebasePerfClearcutLogger.access$200(:62)
       at com.google.firebase.perf.internal.FirebasePerfClearcutLogger$3.run(:216)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)

**Comment by visumickey** [comment]
We tried reproducing this issue and it definitely do not seem to be something trivially happening.

Just to try few other options - Can you provide us the version of protobuf package that was used to see if that could be a cause of the concern?

In the meanwhile, we will try to investigate on this more.
