### ISSUE TITLE
Android Text-recognition Image Processing - Crash

### ISSUE THREAD

**Issue by BalajiVasu-Rntbci** [firebase/firebase-android-sdk#2269]
### [READ] Step 1: Fatal Exception: java.lang.IllegalArgumentException: x + width must be <= bitmap.width()

As per the documentation we used the below code to get the image from camera source.

val image = InputImage.fromMediaImage(mediaImage, rotation)
Doing so causing crash in some devices. 

Source: https://developers.google.com/ml-kit/vision/text-recognition/android

Note: Camera layout is set to device width.

### [REQUIRED] Step 2: Describe your environment
  
CAMERAX VERSION 1.0.0-beta07
MLkit-text-recognition Version: 16.1.1

CAMERA APPLICATION NAME AND VERSION: (Settings > Apps > (app name) > version)

ANDROID OS BUILD NUMBER: (Settings > About > Build number) Android 11,10, 9

Devices Occurred:
Almost all Huawei devices
Some Xiomi and Motorola devices.

#### Steps to reproduce:

Crash Log:
Fatal Exception: java.lang.IllegalArgumentException: x + width must be <= bitmap.width()
       at android.graphics.Bitmap.createBitmap(Bitmap.java:891)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:858)
       at com.google.mlkit.vision.common.internal.ImageConvertUtils.zza(ImageConvertUtils.java:162)
       at com.google.mlkit.vision.common.internal.ImageConvertUtils.convertJpegToUpRightBitmap(ImageConvertUtils.java:115)
       at com.google.mlkit.vision.common.InputImage.fromMediaImage(InputImage.java:30)
       at org.service.view.OcrCameraActivityV21$captureImage$1.onCaptureSuccess(OcrCameraActivityV21.java:182)
       at androidx.camera.core.ImageCapture$ImageCaptureRequest.lambda$dispatchImage$0(ImageCapture.java:2006)
       at androidx.camera.core.-$$Lambda$ImageCapture$ImageCaptureRequest$E13UUGhRx8PID5WbaCuwcGP87BA.run(-.java)
       at android.os.Handler.handleCallback(Handler.java:761)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:156)
       at android.app.ActivityThread.main(ActivityThread.java:6523)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

#### Relevant Code:
val image = InputImage.fromMediaImage(mediaImage, rotation)

**Comment by rlazo** [comment]
Hi @BalajiVasu-Rntbci  MLKit has updated and now it hosted as a separated product. Take a look at [the migration guide](https://developers.google.com/ml-kit/migration) to get started. Also, if you find issues with it, please report them to the [ml kit repo](https://github.com/googlesamples/mlkit).

Thanks!
