### ISSUE TITLE
java.lang.IllegalArgumentException: Service not registered: lu@894daed

### ISSUE THREAD

**Issue by promikhail** [firebase/firebase-android-sdk#2280]
Android Studio version: 4.1.1.

**build.gradle**
```
dependencies {
        classpath 'com.android.tools.build:gradle:4.1.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.21"
        classpath "com.google.gms:google-services:4.3.4"
        classpath "com.google.firebase:firebase-crashlytics-gradle:2.4.1"
    }
...
apply plugin: "com.google.gms.google-services"
apply plugin: "com.google.firebase.crashlytics"
```
Used libs:
```
implementation platform("com.google.firebase:firebase-bom:25.13.0")
implementation "com.google.firebase:firebase-messaging-ktx"
implementation "com.google.firebase:firebase-analytics-ktx"
implementation "com.google.firebase:firebase-crashlytics-ktx"
implementation "com.google.android.gms:play-services-basement:17.5.0"
```

**Problem:**
Implemented service class inherited from FirebaseMessagingService.
On Android API 21 I receive the notification message sended from FCM, but on API 29 I getting exception:
```
V/FA: Connecting to remote service
V/FA: Connection attempt already in progress
D/FA: Connected to remote service
V/FA: Processing queued up service tasks: 2
V/FA: Inactivity, disconnecting from the service
W/ConnectionTracker: Exception thrown while unbinding
    java.lang.IllegalArgumentException: Service not registered: lu@894daed
        at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1751)
        at android.app.ContextImpl.unbindService(ContextImpl.java:1776)
        at android.content.ContextWrapper.unbindService(ContextWrapper.java:741)
        at ci.f(:com.google.android.gms.dynamite_measurementdynamite@204516084@20.45.16 (120700-0):1)
        at ci.d(:com.google.android.gms.dynamite_measurementdynamite@204516084@20.45.16 (120700-0):2)
        at lv.E(:com.google.android.gms.dynamite_measurementdynamite@204516084@20.45.16 (120700-0):9)
        at lf.a(:com.google.android.gms.dynamite_measurementdynamite@204516084@20.45.16 (120700-0):3)
        at ef.run(:com.google.android.gms.dynamite_measurementdynamite@204516084@20.45.16 (120700-0):3)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at iy.run(:com.google.android.gms.dynamite_measurementdynamite@204516084@20.45.16 (120700-0):5)
```
at this point FirebaseMessagingService.onMessageReceived is fired.

Plz help to solve it!

**Comment by flutteresbolivia** [comment]
there are many with the same problem, I include myself, when that error happens, flutter crakes me and Hot Reload and Restart does not work

> Versión de Android Studio: 4.1.1.
> 
> **build.gradle**
> 
> ```
> dependencies {
>         classpath 'com.android.tools.build:gradle:4.1.1'
>         classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.21"
>         classpath "com.google.gms:google-services:4.3.4"
>         classpath "com.google.firebase:firebase-crashlytics-gradle:2.4.1"
>     }
> ...
> apply plugin: "com.google.gms.google-services"
> apply plugin: "com.google.firebase.crashlytics"
> ```
> 
> Libs usados:
> 
> ```
> implementation platform("com.google.firebase:firebase-bom:25.13.0")
> implementation "com.google.firebase:firebase-messaging-ktx"
> implementation "com.google.firebase:firebase-analytics-ktx"
> implementation "com.google.firebase:firebase-crashlytics-ktx"
> implementation "com.google.android.gms:play-services-basement:17.5.0"
> ```
> 
> **Problema:**
> clase de servicio implementada heredada de FirebaseMessagingService.
> En la API 21 de Android, recibo el mensaje de notificación enviado desde FCM, pero en la API 29 recibo una excepción:
> 
> ```
> V/FA: Connecting to remote service
> V/FA: Connection attempt already in progress
> D/FA: Connected to remote service
> V/FA: Processing queued up service tasks: 2
> V/FA: Inactivity, disconnecting from the service
> W/ConnectionTracker: Exception thrown while unbinding
>     java.lang.IllegalArgumentException: Service not registered: lu@894daed
>         at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1751)
>         at android.app.ContextImpl.unbindService(ContextImpl.java:1776)
>         at android.content.ContextWrapper.unbindService(ContextWrapper.java:741)
>         at ci.f(:com.google.android.gms.dynamite_measurementdynamite@204516084@20.45.16 (120700-0):1)
>         at ci.d(:com.google.android.gms.dynamite_measurementdynamite@204516084@20.45.16 (120700-0):2)
>         at lv.E(:com.google.android.gms.dynamite_measurementdynamite@204516084@20.45.16 (120700-0):9)
>         at lf.a(:com.google.android.gms.dynamite_measurementdynamite@204516084@20.45.16 (120700-0):3)
>         at ef.run(:com.google.android.gms.dynamite_measurementdynamite@204516084@20.45.16 (120700-0):3)
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at iy.run(:com.google.android.gms.dynamite_measurementdynamite@204516084@20.45.16 (120700-0):5)
> ```
> 
> en este punto, se activa FirebaseMessagingService.onMessageReceived.
> 
> ¡Por favor ayuda a resolverlo!

there are many with the same problem, I include myself, when that error happens, flutter crakes me and Hot Reload and Restart does not work

**Comment by Amanullahgit** [comment]
Solved by changing this:
`implementation 'com.google.firebase:firebase-analytics-ktx'`
TO
`implementation 'com.google.firebase:firebase-analytics-ktx:18.0.0'`

**Comment by remoteshell** [comment]
I have this problem too

**Comment by taku-ka** [comment]
**I have the same problem in Xamarin** 

I am using the following
    `<PackageReference Include="Xamarin.Firebase.Messaging">
          <Version>121.0.1</Version>
        </PackageReference>`
     `  <PackageReference Include="Xamarin.Firebase.Core">
          <Version>118.0.0</Version>
        </PackageReference>`
        `<PackageReference Include="Xamarin.GooglePlayServices.Analytics">
          <Version>117.0.0</Version>
        </PackageReference>`

`[ConnectionTracker] Exception thrown while unbinding`
`[ConnectionTracker] java.lang.IllegalArgumentException: Service not registered: ls@50f4c04`
`[ConnectionTracker] 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1751)`
`[ConnectionTracker] 	a01-21 17:16:43.391 W/ConnectionTracker(13847): 	at android.app.ContextImpl.unbindService(ContextImpl.java:1776)`
`[ConnectionTracker] 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:741)`
`[ConnectionTracker] 	at ci.f(:com.google.android.gms.dynamite_measurementdynamite@204714084@20.47.14 (120700-0):1)`
`[ConnectionTracker] 	at ci.d(:com.google.android.gms.dynamite_measurementdynamite@204714084@20.47.14 (120700-0):2)`
`[ConnectionTracker] 	at lt.E(:com.google.android.gms.dynamite_measurementdynamite@204714084@20.47.14 (120700-0):9)`
`[ConnectionTracker] 	at ef.run(:com.google.android.gms.dynamite_measurementdynamite@204714084@20.47.14 (120700-0):3)`
`[ConnectionTracker] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)`
`[ConnectionTracker] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)`
`[ConnectionTracker] 	at iy.run(:com.google.android.gms.dynamite_measurementdynamite@204714084@20.47.14 (120700-0):5)`

**Comment by ytheekshana** [comment]
same here

**Comment by ytheekshana** [comment]
#1662

**Comment by ytheekshana** [comment]
@vkryachko Hi. Its now halfway throught february, When will the fix rolled out as you said in #1662 
It looks still the problem is not fixed.

**Comment by aguatno** [comment]
Hi @promikhail sorry for the long wait. I think it's safe to say that it should be fixed already provided on this GitHub [post](https://github.com/firebase/firebase-android-sdk/issues/1662#issuecomment-756917362). It says that no action is required on your end, the fix will apply to google play services itself and existing apps will stop generating the warning.

If the issue persists please let me know. Thanks
