### ISSUE TITLE
App crashes in background when processing push notification with SecurityException

### ISSUE THREAD

**Issue by shaileshmota** [firebase/firebase-android-sdk#2283]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 
Android Studio 4.1
Build #AI-201.8743.12.41.6858069, built on September 23, 2020
Runtime version: 1.8.0_242-release-1644-b3-6222593 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 2988M
Cores: 12
Registry: ide.new.welcome.screen.force=true, debugger.watches.in.variables=false
Non-Bundled Plugins: siosio.kodkod, com.phraseapp.androidstudio, wu.seal.tool.jsontokotlin
  * Firebase Component: firebase-messaging
  * Component version: 21.0.0

### [REQUIRED] Step 3: Describe the problem
We have a top crash which is majorly (85%) noticed on Huawei devices. The crash report is attached below. This crash happens on post Oreo Android version while the  app is in  background (100% times). In all the crash traces two threads : `Firebase-Messaging-Topics-Io` and `Firebase-Messaging-Init` are in park state. So our guess, is that  the crash happens when application is  in background and a push notification is received by our app. It seems like Firebase messaging uses JobIntentService to execute some task in background thread, which crashes.

This seems to be a know issue with the usage of JobIntentService => [https://issuetracker.google.com/issues/63622293](https://issuetracker.google.com/issues/63622293), and google dev propose to migrate to using WorkManager instead. 

This crash only has decimated our crash stats and it is seen by 100-120 users per day.  If we measure it monthly the numbers are in thousands 😭 .

#### Steps to reproduce:

What happened? 
- Huawei devices(Oreo and above) and App running in background
- App crashes in background when receiving push

#### Relevant Code:

I don't  have a code to reproduce the problem. However, I can share the entire trace that we receive on FirebaseCrashlytics

```
Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:365)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
       at java.util.concurrent.FutureTask.run(FutureTask.java:271)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:784)

Caused by java.lang.SecurityException: Caller no longer running, last stopped +3m45s218ms because: cancelled due to doze
       at android.os.Parcel.readException(Parcel.java:2016)
       at android.os.Parcel.readException(Parcel.java:1962)
       at android.app.job.IJobCallback$Stub$Proxy.completeWork(IJobCallback.java:218)
       at android.app.job.JobParameters.completeWork(JobParameters.java:232)
       at androidx.core.app.JobIntentService$JobServiceEngineImpl$WrapperWorkItem.complete(JobIntentService.java:268)
       at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:394)
       at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
       at android.os.AsyncTask$2.call(AsyncTask.java:345)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:784)
```

**Comment by shaileshmota** [comment]
Another piece of information => 
We have noticed that the frequency of these crashes is lesser( still substantial ) when downgrading firebase dependencies to older version: 

From : 
```
depVersion.firebase_analytics = '18.0.0'
depVersion.firebase_config = '20.0.1'
depVersion.firebase_perf = '19.0.10'
depVersion.firebase_messaging = '21.0.0'
depVersion.firebase_crashlytics = '17.3.0'
```

To : 
```
depVersion.firebase_analytics = '17.5.0'
depVersion.firebase_config = '19.2.0'
depVersion.firebase_perf = '19.0.8'
depVersion.firebase_messaging = '20.2.4'
depVersion.firebase_crashlytics = '17.2.2'
```

**Comment by windows7lake** [comment]
No one push this issue?

**Comment by amir-glassboxdigital** [comment]
https://github.com/kmansoft/jobintentservicex

**Comment by windows7lake** [comment]
@davidmotson Does this issue being assigned to someone? Or have anyone help to fix?

**Comment by gsakakihara** [comment]
Firebase Messaging does not use JobIntentService, but there could be a few ways that it might be used. How are you including the firebase-messaging library in your app. Is it directly through the gradle Java dependency? Also, have you enabled setDeliveryMetricsExportToBigQuery?

**Comment by shaileshmota** [comment]
Sorry for the late reply. 

Hello @gsakakihara,
We are using BOM to maintain the messaging dependency version. Currently, we are on BOM version `28.4.2`  with which we are experiencing way more `Parcel` crashes

and,

Yes we have set the export to BQ to `true` : 
```kotlin
FirebaseMessaging.getInstance().setDeliveryMetricsExportToBigQuery(true)
```

**Comment by gsakakihara** [comment]
The logging library that FCM uses to log the delivery metrics uses JobIntentService, so it's possible that's where this is coming from. Another team works on that, so I've filed an internal bug for them to take a look at it (reference 205177181).

**Comment by shaileshmota** [comment]
Thanks for the reactivity @gsakakihara 🙌
Not sure if its the same but we do see a API call to 
```
https://firebaselogging-pa.googleapis.com
```
when putting app in the background 👀

**Comment by mota-shailesh-vc** [comment]
@gsakakihara @vkryachko are there any updates on investigating this issue ?

**Comment by mota-shailesh-vc** [comment]
Hey guys ! Any updates on this one @gsakakihara / @vkryachko  ?

**Comment by shaileshmota** [comment]
Hey guys 👋  

I am going to close this issue as we identified the root cause of this issue coming from a 3rd party library using `JobIntentService`.  

If it helps anyone, in our scenario  [Algolia insight](https://github.com/algolia/instantsearch-android-insights/tree/develop) 2.0.0 is using com.evernote:android-job as job scheduler. This library is based JobIntentService which was causing the crash. Bumping to Algolia insight 3.0.0 is bringing WorkManager instead and this resolved the crash for us.

**Comment by OrhanTozan** [comment]
> I am going to close this issue as we identified the root cause of this issue coming from a 3rd party library using JobIntentService.

@shaileshmota do you mean Firebase has this 3rd party library as a dependency? (Firebase -> 3rd party library -> JobIntentService)

If the above is true => doesn't that mean that this issue will still be open until Firebase resolved this issue with it's dependency?
If the above is false => does it mean that this issue could still occur on a project that removes Firebase as a dependency?

**Comment by shaileshmota** [comment]
> @shaileshmota do you mean Firebase has this 3rd party library as a dependency? (Firebase -> 3rd party library -> JobIntentService)

It was another dependency causing the issue. Not related to firebase
