### ISSUE TITLE
Firebase app not initialized

### ISSUE THREAD

**Issue by fayaz07** [firebase/firebase-android-sdk#229]
Even after writing  FirebaseApp.initializeApp(getApplicationContext()); line of code, this is stopping the app

2019-02-02 20:35:14.606 17973-17973/com.digitattendance E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.digitattendance, PID: 17973
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.digitattendance/com.digitattendance.Main.MainActivity}: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.digitattendance. Make sure to call FirebaseApp.initializeApp(Context) first.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.digitattendance. Make sure to call FirebaseApp.initializeApp(Context) first.
        at com.google.firebase.FirebaseApp.getInstance(Unknown Source:55)
        at com.google.firebase.auth.FirebaseAuth.getInstance(Unknown Source:0)
        at com.digitattendance.Main.MainActivity.onCreate(MainActivity.java:78)
        at android.app.Activity.performCreate(Activity.java:7183)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6944) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by syslogic** [comment]
you need to use `getContext()` instead of `getApplicationContext()`.

**Comment by samtstern** [comment]
@fayaz07 sorry we never got to this.  Since @syslogic has provided a potential solution and it's been a long time, I assume you probably solved this elsewhere.  Closing this issue, please let us know if it's still happening and we can re-open it.
