### ISSUE TITLE
java.lang.ExceptionInInitializerError on Android 11

### ISSUE THREAD

**Issue by CharlesTai** [firebase/firebase-android-sdk#2339]
### [READ] Step 1: Are you in the right place?
yeah

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.1.1
  * Firebase Component: crashlytics
  * Component version: firebase-bom:26.2.0
  * Android platform: Android 11
  * Deivce: oppo,vivo,pixel2,3,3XL
  * Detail Sdk version:
  // Import the Firebase BoM
implementation platform('com.google.firebase:firebase-bom:26.1.0')
// When using the BoM, you don't specify versions in Firebase library dependencies
implementation 'com.google.firebase:firebase-analytics' // firebase analytics
implementation 'com.google.firebase:firebase-messaging' // firebase 推送
implementation 'com.google.firebase:firebase-crashlytics' // firebase crashlytics
implementation 'com.google.firebase:firebase-perf' // firebase performance

#### Steps to reproduce:

Fatal Exception: java.lang.ExceptionInInitializerError
at okhttp3.internal.http2.Hpack$Writer.writeByteString(Hpack.java:552)
at okhttp3.internal.http2.Hpack$Writer.writeHeaders(Hpack.java:520)
at okhttp3.internal.http2.Http2Writer.headers(Http2Writer.java:299)
at okhttp3.internal.http2.Http2Writer.synStream(Http2Writer.java:126)
at okhttp3.internal.http2.Http2Connection.newStream(Http2Connection.java:259)
at okhttp3.internal.http2.Http2Connection.newStream(Http2Connection.java:231)
at okhttp3.internal.http2.Http2Codec.writeRequestHeaders(Http2Codec.java:117)
at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:50)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
at okhttp3.RealCall.execute(RealCall.java:92)
at com.google.firebase.crashlytics.internal.network.HttpRequest.execute(HttpRequest.java:129)
at com.google.firebase.crashlytics.internal.settings.network.DefaultSettingsSpiCall.invoke(DefaultSettingsSpiCall.java:86)
at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:200)
at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:193)
at com.google.android.gms.tasks.zzo.run(zzo.java:2)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:64)
at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:27)
at java.lang.Thread.run(Thread.java:923)

Caused by java.lang.IllegalStateException: invalid dictionary: prefix not unique
at okhttp3.internal.http2.Huffman.addCode(Huffman.java:180)
at okhttp3.internal.http2.Huffman.buildTree(Huffman.java:168)
at okhttp3.internal.http2.Huffman.(Huffman.java:88)
at okhttp3.internal.http2.Huffman.(Huffman.java:79)
at okhttp3.internal.http2.Hpack$Writer.writeByteString(Hpack.java:552)
at okhttp3.internal.http2.Hpack$Writer.writeHeaders(Hpack.java:520)
at okhttp3.internal.http2.Http2Writer.headers(Http2Writer.java:299)
at okhttp3.internal.http2.Http2Writer.synStream(Http2Writer.java:126)
at okhttp3.internal.http2.Http2Connection.newStream(Http2Connection.java:259)
at okhttp3.internal.http2.Http2Connection.newStream(Http2Connection.java:231)
at okhttp3.internal.http2.Http2Codec.writeRequestHeaders(Http2Codec.java:117)
at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:50)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
at okhttp3.RealCall.execute(RealCall.java:92)
at com.google.firebase.crashlytics.internal.network.HttpRequest.execute(HttpRequest.java:129)
at com.google.firebase.crashlytics.internal.settings.network.DefaultSettingsSpiCall.invoke(DefaultSettingsSpiCall.java:86)
at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:200)
at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:193)
at com.google.android.gms.tasks.zzo.run(zzo.java:2)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:64)
at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:27)
at java.lang.Thread.run(Thread.java:923)

okhttp version:
implementation 'com.squareup.retrofit2:retrofit:2.4.0'
implementation 'com.squareup.retrofit2:converter-gson:2.4.0'
implementation 'com.squareup.retrofit2:adapter-rxjava2:2.4.0'
implementation 'com.squareup.okhttp3:logging-interceptor:3.12.12'

![image](https://user-images.githubusercontent.com/13956257/104980150-e5846d00-5a40-11eb-9ce3-410835b27b97.png)

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by Alexspriet** [comment]
Hi,

Same issue for our App. Do you find any solution?

**Comment by CharlesTai** [comment]
> Hi,
> 
> Same issue for our App. Do you find any solution?

I had report to Android OS team and receive:

Response from engineering team:
============================
Crashlytics is removing its dependency on okhttp in an upcoming release, which should resolve this bug at that point.

**Comment by CharlesTai** [comment]
> Hi,
> 
> Same issue for our App. Do you find any solution?

I read the firebase documentation, they have removed okhttp in Crashlytics version 17.3.1

https://firebase.google.com/support/release-notes/android?authuser=0#crashlytics_v17-3-1 

The Google team replay：
https://issuetracker.google.com/issues/177812696#comment6

**Comment by rlazo** [comment]
@CharlesTai yes, it should be solved now. Thanks!
