### ISSUE TITLE
Exception near ActionCodeSettings.Builder after upgrading to Auth-Ktx 20.0.2

### ISSUE THREAD

**Issue by es0329** [firebase/firebase-android-sdk#2351]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.1.1
  * Firebase Component: Auth-Ktx
  * Component version: 20.0.2

### [REQUIRED] Step 3: Describe the problem
CompilationException in Gradle Task :app:compileDevDebugKotlin after upgrading from version 20.0.1.

#### Steps to reproduce:
Attempt to run a project that has implemented passwordless authentication.

#### Relevant Code:
```
private fun requestEmailLinkAuth(emailAddress: String) {
    val actionCodeSettings = actionCodeSettings {
        url = "https://e.com/finishSignUp"
        handleCodeInApp = true
        setAndroidPackageName(
            APPLICATION_ID,
            INSTALL_IF_NOT_AVAILABLE,
            BuildConfig.VERSION_NAME
        )
    }

    Firebase.auth.sendSignInLinkToEmail(emailAddress, actionCodeSettings)
        .addOnSuccessListener {
            viewBinding.loginProgressBar.visibility = View.GONE

            val intent = Intent(Intent.ACTION_MAIN).apply {
                addCategory(Intent.CATEGORY_APP_EMAIL)
            }

            showToast(getString(R.string.login_linkAuth_sent))
            requireActivity().startActivity(intent)
        }
        .addOnFailureListener {
            viewBinding.loginProgressBar.visibility = View.GONE
            Timber.w(it.localizedMessage)
        }
}
```

Relevant Console Output:
```
> Task :app:compileDevDebugKotlin
e: org.jetbrains.kotlin.codegen.CompilationException: Back-end (JVM) Internal error: Couldn't inline method call 'actionCodeSettings' into
private final fun requestEmailLinkAuth(emailAddress: kotlin.String): kotlin.Unit defined in com.e.android.ui.LoginFragment
private fun requestEmailLinkAuth(emailAddress: String) {
        val actionCodeSettings = actionCodeSettings {
            url = "https://e.com/finishSignUp"
            handleCodeInApp = true
            setAndroidPackageName(
                APPLICATION_ID,
                INSTALL_IF_NOT_AVAILABLE,
                BuildConfig.VERSION_NAME
            )
        }

        Firebase.auth.sendSignInLinkToEmail(emailAddress, actionCodeSettings)
            .addOnSuccessListener {
                viewBinding.loginProgressBar.visibility = View.GONE

                val intent = Intent(Intent.ACTION_MAIN).apply {
                    addCategory(Intent.CATEGORY_APP_EMAIL)
                }

                showToast(getString(R.string.login_linkAuth_sent))
                requireActivity().startActivity(intent)
            }
            .addOnFailureListener {
                viewBinding.loginProgressBar.visibility = View.GONE
                Timber.w(it.localizedMessage)
            }
    }
File being compiled: (107,34) in ~/Projects/e/app/src/main/kotlin/com/e/android/ui/LoginFragment.kt
The root cause org.jetbrains.kotlin.codegen.inline.InlineException was thrown at: org.jetbrains.kotlin.codegen.inline.MethodInliner.wrapException(MethodInliner.kt:926)
	at org.jetbrains.kotlin.codegen.inline.InlineCodegen.throwCompilationException(InlineCodegen.kt:104)
	at org.jetbrains.kotlin.codegen.inline.InlineCodegen.performInline(InlineCodegen.kt:147)
	at org.jetbrains.kotlin.codegen.inline.PsiInlineCodegen.genCallInner(PsiInlineCodegen.kt:67)
	at org.jetbrains.kotlin.codegen.CallGenerator$DefaultImpls.genCall(CallGenerator.kt:115)
	at org.jetbrains.kotlin.codegen.inline.PsiInlineCodegen.genCall(PsiInlineCodegen.kt:33)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.invokeMethodWithArguments(ExpressionCodegen.java:2738)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.invokeMethodWithArguments(ExpressionCodegen.java:2680)
	at org.jetbrains.kotlin.codegen.Callable$invokeMethodWithArguments$1.invoke(Callable.kt:42)
	at org.jetbrains.kotlin.codegen.Callable$invokeMethodWithArguments$1.invoke(Callable.kt:14)
	at org.jetbrains.kotlin.codegen.OperationStackValue.putSelector(StackValue.kt:79)
	at org.jetbrains.kotlin.codegen.StackValue.put(StackValue.java:125)
	at org.jetbrains.kotlin.codegen.StackValue.put(StackValue.java:118)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.initializeLocalVariable(ExpressionCodegen.java:4613)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.visitProperty(ExpressionCodegen.java:4481)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.visitProperty(ExpressionCodegen.java:115)
	at org.jetbrains.kotlin.psi.KtProperty.accept(KtProperty.java:58)
	at org.jetbrains.kotlin.codegen.CodegenStatementVisitor.visitKtElement(CodegenStatementVisitor.java:31)
	at org.jetbrains.kotlin.codegen.CodegenStatementVisitor.visitKtElement(CodegenStatementVisitor.java:22)
	at org.jetbrains.kotlin.psi.KtVisitor.visitExpression(KtVisitor.java:182)
	at org.jetbrains.kotlin.psi.KtVisitor.visitDeclaration(KtVisitor.java:29)
	at org.jetbrains.kotlin.psi.KtVisitor.visitNamedDeclaration(KtVisitor.java:398)
	at org.jetbrains.kotlin.psi.KtVisitor.visitProperty(KtVisitor.java:57)
	at org.jetbrains.kotlin.psi.KtProperty.accept(KtProperty.java:58)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.genQualified(ExpressionCodegen.java:312)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.genStatement(ExpressionCodegen.java:461)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.generateBlock(ExpressionCodegen.java:1338)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.generateBlock(ExpressionCodegen.java:1283)
	at org.jetbrains.kotlin.codegen.CodegenStatementVisitor.visitBlockExpression(CodegenStatementVisitor.java:56)
	at org.jetbrains.kotlin.codegen.CodegenStatementVisitor.visitBlockExpression(CodegenStatementVisitor.java:22)
	at org.jetbrains.kotlin.psi.KtBlockExpression.accept(KtBlockExpression.java:79)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.genQualified(ExpressionCodegen.java:312)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.genStatement(ExpressionCodegen.java:461)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.gen(ExpressionCodegen.java:418)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.returnExpression(ExpressionCodegen.java:1841)
	at org.jetbrains.kotlin.codegen.FunctionGenerationStrategy$FunctionDefault.doGenerateBody(FunctionGenerationStrategy.java:64)
	at org.jetbrains.kotlin.codegen.FunctionGenerationStrategy$CodegenBased.generateBody(FunctionGenerationStrategy.java:86)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethodBody(FunctionCodegen.java:648)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethodBody(FunctionCodegen.java:483)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethod(FunctionCodegen.java:259)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethod(FunctionCodegen.java:164)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.gen(FunctionCodegen.java:135)
	at org.jetbrains.kotlin.codegen.MemberCodegen.genSimpleMember(MemberCodegen.java:197)
	at org.jetbrains.kotlin.codegen.ClassBodyCodegen.generateDeclaration(ClassBodyCodegen.java:168)
	at org.jetbrains.kotlin.codegen.ClassBodyCodegen.generateBody(ClassBodyCodegen.java:88)
	at org.jetbrains.kotlin.codegen.MemberCodegen.generate(MemberCodegen.java:129)
	at org.jetbrains.kotlin.codegen.MemberCodegen.genClassOrObject(MemberCodegen.java:302)
	at org.jetbrains.kotlin.codegen.MemberCodegen.genClassOrObject(MemberCodegen.java:286)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generateClassesAndObjectsInFile(PackageCodegenImpl.java:119)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generateFile(PackageCodegenImpl.java:138)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generate(PackageCodegenImpl.java:70)
	at org.jetbrains.kotlin.codegen.DefaultCodegenFactory.generatePackage(CodegenFactory.kt:88)
	at org.jetbrains.kotlin.codegen.DefaultCodegenFactory.generateModule(CodegenFactory.kt:67)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.compileCorrectFiles(KotlinCodegenFacade.java:35)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.generate(KotlinToJVMBytecodeCompiler.kt:647)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:210)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:162)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:169)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
e: org.jetbrains.kotlin.codegen.CompilationException: Back-end (JVM) Internal error: Couldn't inline method call 'actionCodeSettings' into

	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:88)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:371)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:105)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally(IncrementalCompilerRunner.kt:249)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.access$compileIncrementally(IncrementalCompilerRunner.kt:38)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner$compile$2.invoke(IncrementalCompilerRunner.kt:80)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:92)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:602)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execIncrementalCompiler(CompileServiceImpl.kt:93)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1644)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.jetbrains.kotlin.codegen.inline.InlineException: Method inlining actionCodeSettings {
            url = "https://e.com/finishSignUp"
            handleCodeInApp = true
            setAndroidPackageName(
                APPLICATION_ID,
                INSTALL_IF_NOT_AVAILABLE,
                BuildConfig.VERSION_NAME
            )
        }: couldn't inline method call
Cause: actionCodeSettings (Lkotlin/jvm/functions/Function1;)Lcom/google/firebase/auth/ActionCodeSettings;:
  @Lorg/jetbrains/annotations/NotNull;() // invisible
    @Lorg/jetbrains/annotations/NotNull;() // invisible, parameter 0
   L0
    LINENUMBER 159 L0
    INVOKESTATIC com/google/firebase/auth/ActionCodeSettings.newBuilder ()Lcom/google/firebase/auth/ActionCodeSettings$Builder;
    ASTORE 1
    ALOAD 1
    LDC "ActionCodeSettings.newBuilder()"
    INVOKESTATIC kotlin/jvm/internal/Intrinsics.checkNotNullExpressionValue (Ljava/lang/Object;Ljava/lang/String;)V
    ALOAD 1
   L1
    LINENUMBER 160 L1
    CHECKCAST com/google/firebase/auth/ActionCodeSettings$Builder
    ASTORE 2
    INVOKESTATIC kotlin/jvm/internal/InlineMarker.beforeInlineCall ()V
   L2
    ICONST_0
    ISTORE 3
   L3
   L4
    LINENUMBER 108 L4
    ALOAD 2
    LDC "https://e.com/finishSignUp"
    INVOKEVIRTUAL com/google/firebase/auth/ActionCodeSettings$Builder.setUrl (Ljava/lang/String;)Lcom/google/firebase/auth/ActionCodeSettings$Builder;
    POP
   L5
    LINENUMBER 109 L5
    ALOAD 2
    ICONST_1
    INVOKEVIRTUAL com/google/firebase/auth/ActionCodeSettings$Builder.setHandleCodeInApp (Z)Lcom/google/firebase/auth/ActionCodeSettings$Builder;
    POP
   L6
    LINENUMBER 110 L6
    ALOAD 2
   L7
    LINENUMBER 111 L7
    LDC "com.e.android.dev"
   L8
    LINENUMBER 112 L8
    ICONST_0
   L9
    LINENUMBER 113 L9
    LDC "0.0.0-dev"
   L10
    LINENUMBER 110 L10
    INVOKEVIRTUAL com/google/firebase/auth/ActionCodeSettings$Builder.setAndroidPackageName (Ljava/lang/String;ZLjava/lang/String;)Lcom/google/firebase/auth/ActionCodeSettings$Builder;
    POP
   L11
    LINENUMBER 115 L11
    NOP
    GOTO L12
   L13
   L14
   L12
    GETSTATIC kotlin/Unit.INSTANCE : Lkotlin/Unit;
Caused by: org.jetbrains.kotlin.codegen.inline.InlineException: Method inlining actionCodeSettings {

    INVOKESTATIC kotlin/jvm/internal/InlineMarker.afterInlineCall ()V
    POP
    ALOAD 1
   L15
    LINENUMBER 161 L15
    INVOKEVIRTUAL com/google/firebase/auth/ActionCodeSettings$Builder.build ()Lcom/google/firebase/auth/ActionCodeSettings;
    ASTORE 0
    LDC "builder.build()"
    INVOKESTATIC kotlin/jvm/internal/Intrinsics.checkNotNullExpressionValue (Ljava/lang/Object;Ljava/lang/String;)V
    ARETURN
    LOCALVARIABLE $this$actionCodeSettings Lcom/google/firebase/auth/ActionCodeSettings$Builder; L2 L14 2
    LOCALVARIABLE $i$a$-actionCodeSettings-LoginFragment$requestEmailLinkAuth$actionCodeSettings$1 I L3 L14 3
    MAXSTACK = 4
    MAXLOCALS = 4

	at org.jetbrains.kotlin.codegen.inline.MethodInliner.wrapException(MethodInliner.kt:926)
	at org.jetbrains.kotlin.codegen.inline.MethodInliner.doInline(MethodInliner.kt:129)
	at org.jetbrains.kotlin.codegen.inline.MethodInliner.doInline(MethodInliner.kt:77)
	at org.jetbrains.kotlin.codegen.inline.InlineCodegen.inlineCall(InlineCodegen.kt:248)
	at org.jetbrains.kotlin.codegen.inline.InlineCodegen.performInline(InlineCodegen.kt:143)
	... 85 more
Caused by: java.lang.RuntimeException: Trying to access skipped parameter: Lkotlin/jvm/functions/Function1; at 0
	at org.jetbrains.kotlin.codegen.inline.LocalVarRemapper.remap(LocalVarRemapper.kt:77)
	at org.jetbrains.kotlin.codegen.inline.LocalVarRemapper.visitVarInsn(LocalVarRemapper.kt:99)
	at org.jetbrains.kotlin.codegen.inline.RemapVisitor.visitVarInsn(RemapVisitor.java:52)
	at org.jetbrains.org.objectweb.asm.MethodVisitor.visitVarInsn(MethodVisitor.java:348)
	at org.jetbrains.org.objectweb.asm.tree.VarInsnNode.accept(VarInsnNode.java:74)
	at org.jetbrains.org.objectweb.asm.tree.InsnList.accept(InsnList.java:144)
	at org.jetbrains.org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:792)
	at org.jetbrains.kotlin.codegen.inline.MethodInliner.doInline(MethodInliner.kt:122)
	... 88 more

Caused by: java.lang.RuntimeException: Trying to access skipped parameter: Lkotlin/jvm/functions/Function1; at 0


> Task :app:compileDevDebugKotlin FAILED

```

**Comment by rlazo** [comment]
Hi @es0329 this is caused by a bug in Kotlin itself. We reported it to the kotlin team a week ago, and you can track it in https://youtrack.jetbrains.com/issue/KT-44375
