### ISSUE TITLE
Firebase Perf crash in API level 30

### ISSUE THREAD

**Issue by tdrp** [firebase/firebase-android-sdk#2407]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.1.2
  * Firebase Component: Firebase Perf (Database, Firestore, Storage, Functions, etc)
  * Component version: com.google.firebase:firebase-perf-ktx:19.1.0

#### Steps to reproduce:

Only in Android SDK level 30, not in 29 or below.

java.lang.NoSuchMethodError: No static method registerDefaultInstance(Ljava/lang/Class;Lcom/google/protobuf/GeneratedMessageLite;)V in class Lcom/google/protobuf/GeneratedMessageLite; or its super classes (declaration of 'com.google.protobuf.GeneratedMessageLite' appears in /data/app/~~KW7Dy-Kn3GGHCMIPkF66_Q==/com.REDACTED.REDACTED.test-I6zPQPdPsbD3ChwlgaE0iQ==/base.apk)
        at com.google.firebase.perf.v1.ApplicationInfo.<clinit>(ApplicationInfo.java:1351)
        at com.google.firebase.perf.v1.ApplicationInfo.newBuilder(ApplicationInfo.java:660)
        at com.google.firebase.perf.transport.TransportManager.<init>(TransportManager.java:139)
        at com.google.firebase.perf.transport.TransportManager.<clinit>(TransportManager.java:91)
        at com.google.firebase.perf.transport.TransportManager.getInstance(TransportManager.java:149)
        at com.google.firebase.perf.internal.AppStateMonitor.getInstance(AppStateMonitor.java:64)
        at com.google.firebase.perf.provider.FirebasePerfProvider.attachInfo(FirebasePerfProvider.java:65)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7239)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6780)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6697)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```
Works fine on 29 and below. Upping the Android version to 30 required the build.gradle changes below. Crashes as soon as Firebase Perf is invoked.

androidTestImplementation 'androidx.test:rules:1.3.1-alpha03'
    androidTestImplementation 'androidx.test:runner:1.3.1-alpha03'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0-alpha03'
    androidTestImplementation 'androidx.test.espresso:espresso-contrib:3.4.0-alpha03'
    androidTestUtil 'androidx.test:orchestrator:1.3.1-alpha03'
implementation 'com.google.firebase:firebase-perf-ktx:19.1.0'

**Comment by yalunqin** [comment]
We tried our test app with the same gradle dependencies and SDKs but couldn't reproduce the issue.  Can you provide the versions of Android gradle plugin and Fireperf gradle plugin? It would be also helpful if you could provide all the build configuration files (including build.gradle and gradle.properties) with PII removed, or preferably a sample app that has the issue with those files.

Meanwhile we are actively investigating this issue.

**Comment by yalunqin** [comment]
Hi, can you also run the command `./gradlew app:dependencies` and send us the output?
