### ISSUE TITLE
We meet a crash in Firebase Cloud Messaging

### ISSUE THREAD

**Issue by TaoZang** [firebase/firebase-android-sdk#2424]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: __4.1.1___
  * Firebase Component: _CloudMessaging____ (Database, Firestore, Storage, Functions, etc)
  * Component version: _____

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
Fatal Exception: java.lang.IllegalArgumentException: width and height must be > 0
       at android.graphics.Bitmap.createBitmap(Bitmap.java:1044)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:1011)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:961)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:882)
       at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:752)
       at android.graphics.drawable.Icon.scaleDownIfNecessary(Icon.java:822)
       at android.graphics.drawable.Icon.scaleDownIfNecessary(Icon.java:841)
       at android.app.Notification.reduceImageSizes(Notification.java:5363)
       at android.app.Notification$Builder.build(Notification.java:5133)
       at androidx.core.app.NotificationCompatBuilder.buildInternal(NotificationCompatBuilder.java:339)
       at androidx.core.app.NotificationCompatBuilder.build(NotificationCompatBuilder.java:253)
       at androidx.core.app.NotificationCompat$Builder.build(NotificationCompat.java:1677)
       at com.google.firebase.messaging.DisplayNotification.showNotification(com.google.firebase:firebase-messaging@@21.0.0:59)
       at com.google.firebase.messaging.DisplayNotification.handleNotification(com.google.firebase:firebase-messaging@@21.0.0:29)
       at com.google.firebase.messaging.FirebaseMessagingService.dispatchMessage(com.google.firebase:firebase-messaging@@21.0.0:55)
       at com.google.firebase.messaging.FirebaseMessagingService.passMessageIntentToSdk(com.google.firebase:firebase-messaging@@21.0.0:34)
       at com.google.firebase.messaging.FirebaseMessagingService.handleMessageIntent(com.google.firebase:firebase-messaging@@21.0.0:27)
       at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(com.google.firebase:firebase-messaging@@21.0.0:17)
       at com.google.firebase.messaging.EnhancedIntentService.lambda$processIntent$0$EnhancedIntentService(com.google.firebase:firebase-messaging@@21.0.0:43)
       at com.google.firebase.messaging.EnhancedIntentService$$Lambda$0.run(:6)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@17.2.1:6)
       at java.lang.Thread.run(Thread.java:764)
```

**Comment by gitByEOS** [comment]
We also meet the crash liked this

java.lang.IllegalStateException: 
  at com.google.firebase.FirebaseApp.getInstance (FirebaseApp.java:182)
  at com.google.firebase.messaging.MessagingAnalytics.logToScion
  at com.google.firebase.messaging.MessagingAnalytics.logNotificationReceived
  at com.google.firebase.messaging.FirebaseMessagingService.passMessageIntentToSdk
  at com.google.firebase.messaging.FirebaseMessagingService.handleMessageIntent
  at com.google.firebase.messaging.FirebaseMessagingService.handleIntent
  at com.google.firebase.messaging.EnhancedIntentService.lambda$processIntent$0$EnhancedIntentService
  at com.google.firebase.messaging.EnhancedIntentService$$Lambda$0.run (Unknown Source:6)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1162)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:636)
  at com.google.android.gms.common.util.concurrent.zza.run
  at java.lang.Thread.run (Thread.java:784)

**Comment by ciarand** [comment]
Hi @TaoZang, thanks for the report! Was this a notification with an image attached? Are you able to share the image? From the stack trace it looks like the system is trying to scale the image to a size that can be shown in the notification but the scaling process is turning at least one of the dimensions to 0. If you can share the image that triggered this we can add some checks to prevent it from happening in the future.

@gitByEOS based on the stack trace that looks like a separate issue, seems like it might be something to do with not being able to instantiate the default FirebaseApp. Can I ask you to file a separate issue for that?
