### ISSUE TITLE
'The input TextAnnotation can not be null' during cloud OCR

### ISSUE THREAD

**Issue by wosiu** [firebase/firebase-android-sdk#249]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 3.3.1
  * Firebase Component: com.google.firebase.ml.vision.text.FirebaseVisionTextRecognizer
  * Component version: firebase-ml-vision:19.0.2

### [REQUIRED] Step 3: Describe the problem
```
 Caused by: com.google.firebase.ml.common.FirebaseMLException: Internal error has occurred when executing Firebase ML tasks
        at com.google.android.gms.internal.firebase_ml.zzmy.zza(Unknown Source)
        at com.google.android.gms.internal.firebase_ml.zzmz.run(Unknown Source)
        at android.os.Handler.handleCallback(Handler.java:761)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at com.google.android.gms.internal.firebase_ml.zze.dispatchMessage(Unknown Source)
        at android.os.Looper.loop(Looper.java:156)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: java.lang.NullPointerException: The input TextAnnotation can not be null
        at com.google.android.gms.common.internal.Preconditions.checkNotNull(Unknown Source)
        at com.google.android.gms.internal.firebase_ml.zzpj.zzb(Unknown Source)
        at com.google.android.gms.internal.firebase_ml.zzpf.zza(Unknown Source)
        at com.google.android.gms.internal.firebase_ml.zzoo.zza(Unknown Source)
        at com.google.android.gms.internal.firebase_ml.zznd.call(Unknown Source)
        at com.google.android.gms.internal.firebase_ml.zzmy.zza(Unknown Source)
```

Exactly the same problem by someone else: https://stackoverflow.com/questions/54468442/firebase-cloud-text-recognition

#### Steps to reproduce:
```
        FirebaseVisionCloudTextRecognizerOptions options =
                (new FirebaseVisionCloudTextRecognizerOptions.Builder())
                        .setLanguageHints(Arrays.asList("pl"))
                        .setModelType(DENSE_MODEL)
                        .build();
        firebaseDetector = FirebaseVision.getInstance().getCloudTextRecognizer(options);

        FirebaseVisionImage image = FirebaseVisionImage.fromBitmap(section);
        Task<FirebaseVisionText> result =
                firebaseDetector.processImage(image)
                        .addOnSuccessListener(new OnSuccessListener<FirebaseVisionText>() {
                            @Override
                            public void onSuccess(FirebaseVisionText firebaseVisionText) {
                                Log.e(TAG, "====================OCR SUCC =======================");
                            }
                        })
                        .addOnFailureListener(
                                new OnFailureListener() {
                                    @Override
                                    public void onFailure(@NonNull Exception e) {
                                        Log.e(TAG, "onFailure: ocr failure", e);
                                    }
                                });
        while (!result.isComplete()) {
            try {
                Thread.sleep(100); // that was for on-device OCR, here probably irrelevant
            } catch (InterruptedException e) {
                e.printStackTrace();
                break;
            }
        }
        return result.getResult().getText();  // EXCEPTION IS THROWN FROM THIS LINE
```

On-device OCR works though.

Firebase's API and billing is turned on.

**Comment by teer-hossain** [comment]
I was facing the same problem, but what I found is 

- onSuccess is called when I am processing image which contain English language.
- onFailure is called when I am trying to process image that contains regional language.

**Comment by aguatno** [comment]
Hi @teer-hossain sorry for the late in response. I'd like to know if you're still experiencing this issue? If so, is there any changes with the steps provided?
