### ISSUE TITLE
Twitter login of firebase authentication with TwitterKit crashes on gradle plugin 4.1.2 and proguard is enabled

### ISSUE THREAD

**Issue by justoneplanet** [firebase/firebase-android-sdk#2503]
### Describe your environment

  * Android Studio version: 4.1.2
  * Firebase Component: Authentication
  * Component version: firebase-ui-auth:4.3.2, firebase-auth:20.0.3, twitter-core:3.3.0

#### Steps to reproduce:

1. Upgrade the gradle plugin to 4.1.2.
2. Push twitter button to login Twitter with firebase authentication and TwitterKit.
3. Crash with NullPointerException as follows.

```txt
5089-5089/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: info.justoneplanet.android.inputmethod.japanese, PID: 5089
    java.lang.NullPointerException: uriString
        at android.net.Uri$StringUri.<init>(Uri.java:496)
        at android.net.Uri$StringUri.<init>(Uri.java:486)
        at android.net.Uri.parse(Uri.java:458)
        at c.d.a.a.i.b.k$b$a.d(SourceFile:3)
        at c.j.a.a.a.c.b(SourceFile:4)
        at l.b.run(SourceFile:3)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:368)
        at android.app.ActivityThread.main(ActivityThread.java:7710)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
```

This crash occurs when the project satisfies the following conditions.

- Gradle plugin version == 4.1.2.
- minifyEnabled is true.
- TwitterKit is used.

#### Relevant Code:

4.0.2 works correctly, but 4.1.2 does not work.

```diff
     dependencies {
-        classpath 'com.android.tools.build:gradle:4.0.2'
+        classpath 'com.android.tools.build:gradle:4.1.2'
         classpath 'com.google.gms:google-services:4.3.5'
     }
```

**Comment by yuchenshi** [comment]
Would you mind creating a minimal repro app (say in a GitHub repository) of the issue? We'd love to dig more into this if we have a sample app.
