### ISSUE TITLE
Internal error in Cloud Firestore (21.4.3) - IllegalArgumentException: Timestamp seconds out of range

### ISSUE THREAD

**Issue by strictlad** [firebase/firebase-android-sdk#2505]
I have a problem when I run build signed apk release. The release apk runs on some devices occurred **Internal error in Cloud Firestore (21.4.3) - IllegalArgumentException: Timestamp seconds out of range**
```
java.lang.RuntimeException: Internal error in Cloud Firestore (21.4.3).
        at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$3(com.google.firebase:firebase-firestore@@21.4.3:5)
        at com.google.firebase.firestore.util.AsyncQueue$$Lambda$3.run(com.google.firebase:firebase-firestore@@21.4.3)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5305)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.IllegalArgumentException: Timestamp seconds out of range: 6935991169516148536
        at com.google.firebase.firestore.util.Preconditions.checkArgument(com.google.firebase:firebase-firestore@@21.4.3:1)
        at com.google.firebase.Timestamp.validateRange(com.google.firebase:firebase-firestore@@21.4.3:4)
        at com.google.firebase.Timestamp.<init>(com.google.firebase:firebase-firestore@@21.4.3:2)
        at com.google.firebase.firestore.remote.RemoteSerializer.decodeTimestamp(com.google.firebase:firebase-firestore@@21.4.3:1)
        at com.google.firebase.firestore.remote.RemoteSerializer.decodeVersion(com.google.firebase:firebase-firestore@@21.4.3:3)
        at com.google.firebase.firestore.remote.RemoteSerializer.decodeWatchChange(com.google.firebase:firebase-firestore@@21.4.3:22)
        at com.google.firebase.firestore.remote.WatchStream.onNext(com.google.firebase:firebase-firestore@@21.4.3:3)
        at com.google.firebase.firestore.remote.WatchStream.onNext(com.google.firebase:firebase-firestore@@21.4.3:1)
        at com.google.firebase.firestore.remote.AbstractStream$StreamObserver.lambda$onNext$1(com.google.firebase:firebase-firestore@@21.4.3:6)
        at com.google.firebase.firestore.remote.AbstractStream$StreamObserver$$Lambda$2.run(com.google.firebase:firebase-firestore@@21.4.3)
        at com.google.firebase.firestore.remote.AbstractStream$CloseGuardedRunner.run(com.google.firebase:firebase-firestore@@21.4.3:3)
        at com.google.firebase.firestore.remote.AbstractStream$StreamObserver.onNext(com.google.firebase:firebase-firestore@@21.4.3:1)
        at com.google.firebase.firestore.remote.FirestoreChannel$1.onMessage(com.google.firebase:firebase-firestore@@21.4.3:1)
        at o.b.b0.onMessage(ForwardingClientCallListener.java:1)
        at o.b.b0.onMessage(ForwardingClientCallListener.java:1)
        at o.b.m2.s$d$b.a(ClientCallImpl.java:5)
        at o.b.m2.a0.run(ContextRunnable.java:2)
        at o.b.m2.f2.run(SerializingExecutor.java:2)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(com.google.firebase:firebase-firestore@@21.4.3:3)
        at java.lang.Thread.run(Thread.java:818)
```
In this code I only run query
```
FirebaseFirestore db = FirebaseFirestore.getInstance();
CollectionReference colRef = db.collection("my_collection");
colRef.whereEqualTo("sdk", android.os.Build.VERSION.SDK_INT)
          .whereGreaterThan("version_code", BuildConfig.VERSION_CODE)
          .orderBy("version_code")
          .get();
```
How can I fix it? Thanks.

**Comment by schmidt-sebastian** [comment]
@strictlad Thanks for filing this. This looks like the issue https://github.com/firebase/firebase-android-sdk/issues/1186. Unfortunately, we were never able to get to the bottom of this. Are you able to reproduce this issue on your end? How often have you seen this crash?
