### ISSUE TITLE
Why do I get this error? 

### ISSUE THREAD

**Issue by ooniku1224** [firebase/firebase-android-sdk#2513]
### Describe your environment

  * Android Studio version: 4.1.2
  * Firebase Component: firebase-auth-ktx (Database, Firestore, Storage, Functions, etc)
  * Component version: Latest Version

#### Steps to reproduce:

When I try to authenticate with Twitter, I get the following error:

log: 
```
W/MyPackageName: Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
    Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
    Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
W/MyPackageName: Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
W/MyPackageName: Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
    Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
W/MyPackageName: Accessing hidden method Llibcore/io/Memory;->pokeByte(JB)V (greylist, reflection, allowed)
    Accessing hidden method Llibcore/io/Memory;->peekByte(J)B (greylist, reflection, allowed)
    Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, reflection, allowed)
    Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, reflection, allowed)
    Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, reflection, allowed)
    Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, reflection, allowed)
    Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, reflection, allowed)
    Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, reflection, allowed)
    Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, reflection, allowed)
W/MyPackageName: Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
    Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/zzdt: encountered a potentially transient KeyStore error, will wait and retry
    javax.crypto.AEADBadTagException
        at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:517)
        at javax.crypto.Cipher.doFinal(Cipher.java:2113)
        at com.google.android.gms.internal.firebase-auth-api.zzdt.zzd(com.google.firebase:firebase-auth@@20.0.2:7)
        at com.google.android.gms.internal.firebase-auth-api.zzdt.zzb(com.google.firebase:firebase-auth@@20.0.2:1)
        at com.google.android.gms.internal.firebase-auth-api.zzau.zzi(com.google.firebase:firebase-auth@@20.0.2:5)
        at com.google.android.gms.internal.firebase-auth-api.zzdr.zzi(com.google.firebase:firebase-auth@@20.0.2:1)
        at com.google.android.gms.internal.firebase-auth-api.zzdr.zzd(com.google.firebase:firebase-auth@@20.0.2:2)
        at com.google.firebase.auth.internal.zzk.<init>(com.google.firebase:firebase-auth@@20.0.2:7)
        at com.google.firebase.auth.internal.zzk.zza(com.google.firebase:firebase-auth@@20.0.2:3)
        at com.google.firebase.auth.internal.GenericIdpActivity.zzg(com.google.firebase:firebase-auth@@20.0.2:23)
        at com.google.firebase.auth.internal.GenericIdpActivity.zzd(com.google.firebase:firebase-auth@@20.0.2:3)
        at com.google.android.gms.internal.firebase-auth-api.zztw.<init>(com.google.firebase:firebase-auth@@20.0.2:13)
        at com.google.firebase.auth.internal.GenericIdpActivity.onResume(com.google.firebase:firebase-auth@@20.0.2:53)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1454)
        at android.app.Activity.performResume(Activity.java:7939)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4207)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4249)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2022)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:359)
        at android.app.ActivityThread.main(ActivityThread.java:7418)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
     Caused by: android.security.KeyStoreException: Signature/MAC verification failed
        at android.security.KeyStore.getKeyStoreException(KeyStore.java:1303)
        at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:224)
        at android.security.keystore.AndroidKeyStoreAuthenticatedAESCipherSpi$BufferAllOutputUntilDoFinalStreamer.doFinal(AndroidKeyStoreAuthenticatedAESCipherSpi.java:373)
        at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)
        at javax.crypto.Cipher.doFinal(Cipher.java:2113) 
        at com.google.android.gms.internal.firebase-auth-api.zzdt.zzd(com.google.firebase:firebase-auth@@20.0.2:7) 
        at com.google.android.gms.internal.firebase-auth-api.zzdt.zzb(com.google.firebase:firebase-auth@@20.0.2:1) 
        at com.google.android.gms.internal.firebase-auth-api.zzau.zzi(com.google.firebase:firebase-auth@@20.0.2:5) 
        at com.google.android.gms.internal.firebase-auth-api.zzdr.zzi(com.google.firebase:firebase-auth@@20.0.2:1) 
        at com.google.android.gms.internal.firebase-auth-api.zzdr.zzd(com.google.firebase:firebase-auth@@20.0.2:2) 
        at com.google.firebase.auth.internal.zzk.<init>(com.google.firebase:firebase-auth@@20.0.2:7) 
        at com.google.firebase.auth.internal.zzk.zza(com.google.firebase:firebase-auth@@20.0.2:3) 
        at com.google.firebase.auth.internal.GenericIdpActivity.zzg(com.google.firebase:firebase-auth@@20.0.2:23) 
        at com.google.firebase.auth.internal.GenericIdpActivity.zzd(com.google.firebase:firebase-auth@@20.0.2:3) 
        at com.google.android.gms.internal.firebase-auth-api.zztw.<init>(com.google.firebase:firebase-auth@@20.0.2:13) 
        at com.google.firebase.auth.internal.GenericIdpActivity.onResume(com.google.firebase:firebase-auth@@20.0.2:53) 
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1454) 
        at android.app.Activity.performResume(Activity.java:7939) 
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4207) 
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4249) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2022) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:359) 
        at android.app.ActivityThread.main(ActivityThread.java:7418) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935) 
W/zzds: cannot decrypt keyset: 
    javax.crypto.AEADBadTagException
        at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:517)
        at javax.crypto.Cipher.doFinal(Cipher.java:2113)
        at com.google.android.gms.internal.firebase-auth-api.zzdt.zzd(com.google.firebase:firebase-auth@@20.0.2:7)
        at com.google.android.gms.internal.firebase-auth-api.zzdt.zzb(com.google.firebase:firebase-auth@@20.0.2:4)
        at com.google.android.gms.internal.firebase-auth-api.zzau.zzi(com.google.firebase:firebase-auth@@20.0.2:5)
        at com.google.android.gms.internal.firebase-auth-api.zzdr.zzi(com.google.firebase:firebase-auth@@20.0.2:1)
        at com.google.android.gms.internal.firebase-auth-api.zzdr.zzd(com.google.firebase:firebase-auth@@20.0.2:2)
        at com.google.firebase.auth.internal.zzk.<init>(com.google.firebase:firebase-auth@@20.0.2:7)
        at com.google.firebase.auth.internal.zzk.zza(com.google.firebase:firebase-auth@@20.0.2:3)
        at com.google.firebase.auth.internal.GenericIdpActivity.zzg(com.google.firebase:firebase-auth@@20.0.2:23)
        at com.google.firebase.auth.internal.GenericIdpActivity.zzd(com.google.firebase:firebase-auth@@20.0.2:3)
        at com.google.android.gms.internal.firebase-auth-api.zztw.<init>(com.google.firebase:firebase-auth@@20.0.2:13)
        at com.google.firebase.auth.internal.GenericIdpActivity.onResume(com.google.firebase:firebase-auth@@20.0.2:53)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1454)
        at android.app.Activity.performResume(Activity.java:7939)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4207)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4249)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2022)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:359)
        at android.app.ActivityThread.main(ActivityThread.java:7418)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
     Caused by: android.security.KeyStoreException: Signature/MAC verification failed
        at android.security.KeyStore.getKeyStoreException(KeyStore.java:1303)
        at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:224)
        at android.security.keystore.AndroidKeyStoreAuthenticatedAESCipherSpi$BufferAllOutputUntilDoFinalStreamer.doFinal(AndroidKeyStoreAuthenticatedAESCipherSpi.java:373)
        at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)
        at javax.crypto.Cipher.doFinal(Cipher.java:2113) 
        at com.google.android.gms.internal.firebase-auth-api.zzdt.zzd(com.google.firebase:firebase-auth@@20.0.2:7) 
        at com.google.android.gms.internal.firebase-auth-api.zzdt.zzb(com.google.firebase:firebase-auth@@20.0.2:4) 
        at com.google.android.gms.internal.firebase-auth-api.zzau.zzi(com.google.firebase:firebase-auth@@20.0.2:5) 
        at com.google.android.gms.internal.firebase-auth-api.zzdr.zzi(com.google.firebase:firebase-auth@@20.0.2:1) 
        at com.google.android.gms.internal.firebase-auth-api.zzdr.zzd(com.google.firebase:firebase-auth@@20.0.2:2) 
        at com.google.firebase.auth.internal.zzk.<init>(com.google.firebase:firebase-auth@@20.0.2:7) 
        at com.google.firebase.auth.internal.zzk.zza(com.google.firebase:firebase-auth@@20.0.2:3) 
        at com.google.firebase.auth.internal.GenericIdpActivity.zzg(com.google.firebase:firebase-auth@@20.0.2:23) 
        at com.google.firebase.auth.internal.GenericIdpActivity.zzd(com.google.firebase:firebase-auth@@20.0.2:3) 
        at com.google.android.gms.internal.firebase-auth-api.zztw.<init>(com.google.firebase:firebase-auth@@20.0.2:13) 
        at com.google.firebase.auth.internal.GenericIdpActivity.onResume(com.google.firebase:firebase-auth@@20.0.2:53) 
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1454) 
        at android.app.Activity.performResume(Activity.java:7939) 
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4207) 
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4249) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2022) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:359) 
        at android.app.ActivityThread.main(ActivityThread.java:7418) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935) 
E/FirebearCryptoHelper: Exception encountered during crypto setup:
    Protocol message contained an invalid tag (zero).
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: MyPackageName, PID: 11360
    java.lang.RuntimeException: Unable to resume activity {MyPackageName/com.google.firebase.auth.internal.GenericIdpActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.internal.firebase-auth-api.zzau com.google.android.gms.internal.firebase-auth-api.zzds.zza()' on a null object reference
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4217)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4249)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2022)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:359)
        at android.app.ActivityThread.main(ActivityThread.java:7418)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.internal.firebase-auth-api.zzau com.google.android.gms.internal.firebase-auth-api.zzds.zza()' on a null object reference
        at com.google.firebase.auth.internal.zzk.zzb(com.google.firebase:firebase-auth@@20.0.2:2)
        at com.google.firebase.auth.internal.GenericIdpActivity.zzg(com.google.firebase:firebase-auth@@20.0.2:24)
        at com.google.firebase.auth.internal.GenericIdpActivity.zzd(com.google.firebase:firebase-auth@@20.0.2:3)
        at com.google.android.gms.internal.firebase-auth-api.zztw.<init>(com.google.firebase:firebase-auth@@20.0.2:13)
        at com.google.firebase.auth.internal.GenericIdpActivity.onResume(com.google.firebase:firebase-auth@@20.0.2:53)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1454)
        at android.app.Activity.performResume(Activity.java:7939)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4207)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4249) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2022) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:359) 
        at android.app.ActivityThread.main(ActivityThread.java:7418) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935) 
```

When I turned off backup to Google Drive, this issue was temporarily resolved. But after a while, I get this error again. I don't know the complete solution for this error.

#### Relevant Code:
```
val pendingResultTask: Task<AuthResult>? = Firebase.auth.pendingAuthResult
        pendingResultTask?.also {
            pendingResultTask
                .addOnSuccessListener { authResult ->
                    Log.d(TAG, "checkPending:onSuccess:$authResult")
                }
                .addOnFailureListener { error ->
                    Log.w(TAG, "checkPending:onFailure", error)
                }
        } ?: kotlin.run {
            val provider: OAuthProvider.Builder = OAuthProvider.newBuilder("twitter.com")
            currentUser.startActivityForLinkWithProvider(this, provider.build())
                .addOnSuccessListener { authResult ->
                    Log.d(TAG, "checkPending:onSuccess:$authResult")
                }
                .addOnFailureListener { error ->
                    Log.w(TAG, "checkPending:onFailure", error)
                }
        }
```

**Comment by aguatno** [comment]
The behavior you reported seems odd as I'm unable to reproduce this issue locally using our quickstart app. Could you try replicating this behavior in the [quickstart](https://github.com/firebase/quickstart-android/tree/master/auth)? If it works without issues, you could use it as a guide to compare it with your setup.

**Comment by ooniku1224** [comment]
Thank you for your response.
When I tried to reproduce the problem using the quickstart app, it worked fine without any problems. So it may only be a problem with my app.

**Comment by aguatno** [comment]
Hi @ooniku1224 you can use our quickstart as a reference and compare with your project.  It is a validated implementation of our products, so any issues with that project could indicate that there's a bug in the SDK.

 In case the issue persists, feel free to re-open this issue and provide the latest steps to reproduce and a sample code that demonstrates the issue.
