### ISSUE TITLE
PhoneAuthProvider.verifyPhoneNumber crash my app

### ISSUE THREAD

**Issue by ValeraSetrakov** [firebase/firebase-android-sdk#2530]
### [READ] Step 1: Are you in the right place?
Issues filed here should be about bugs in the code in this repository.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

For general technical questions, post a question on StackOverflow
with the firebase tag.
For general Firebase discussion, use the firebase-talk
google group.
For help troubleshooting your application that does not fall under one
of the above categories, reach out to the personalized
Firebase support channel.

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.1.1
  * Firebase Component: Authentication
  * Component version: 20.0.3

### [REQUIRED] Step 3: Describe the problem
I have problem with phone authentication, after start authentication my app is crash

it happens only for release build type

#### Steps to reproduce:

I just called PhoneAuthProvider.verifyPhoneNumber(options)
log with error
```
java.lang.RuntimeException: Unable to resume activity {com.wiby.android.app/com.google.firebase.auth.internal.RecaptchaActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.internal.firebase-auth-api.zzau com.google.android.gms.internal.firebase-auth-api.zzds.zza()' on a null object reference
 at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4270)
 at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4302)
 at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
 at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
 at android.os.Handler.dispatchMessage(Handler.java:107)
 at android.os.Looper.loop(Looper.java:224)
 at android.app.ActivityThread.main(ActivityThread.java:7562)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.internal.firebase-auth-api.zzau com.google.android.gms.internal.firebase-auth-api.zzds.zza()' on a null object reference
 at com.google.firebase.auth.internal.zzk.zzb(com.google.firebase:firebase-auth@@20.0.3:2)
 at com.google.firebase.auth.internal.RecaptchaActivity.zzd(com.google.firebase:firebase-auth@@20.0.3:10)
 at com.google.android.gms.internal.firebase-auth-api.zztw.<init>(com.google.firebase:firebase-auth@@20.0.3:13)
 at com.google.firebase.auth.internal.RecaptchaActivity.onResume(com.google.firebase:firebase-auth@@20.0.3:43)
 at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1454)
 at android.app.Activity.performResume(Activity.java:8050)
 at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4260)
```

#### Relevant Code:
my method
```
private fun requestCode(phoneNumber: String) {
        viewModel.startLoading()
        val options = PhoneAuthOptions.newBuilder(Firebase.auth)
            .setPhoneNumber(phoneNumber)
            .setTimeout(screenArgs?.timer?.second?.toLong() ?: 0, TimeUnit.SECONDS)
            .setActivity(requireActivity())
            .setCallbacks(WibyOnVerificationStateChangedCallbacks())
            .build()
        PhoneAuthProvider.verifyPhoneNumber(options)
    }
```
my release build type
```
release {
            minifyEnabled false
            signingConfig signingConfigs.release
}
```

my dependencies
```
implementation "androidx.browser:browser:1.3.0"
implementation platform("com.google.firebase:firebase-bom:26.7.0")
implementation 'com.google.firebase:firebase-auth-ktx'

```

**Comment by malcolmdeck** [comment]
Looks like a problem with the usage of AndroidKeysetManager in the SDK. I'll figure out what's going on

**Comment by malcolmdeck** [comment]
I think I've found and fixed the culprit. I've filed b/183415315 internally, and it should come out in the next release.

**Comment by ValeraSetrakov** [comment]
@malcolmdeck thanks!) Can you suggest an approximate release date?

**Comment by aguatno** [comment]
Hi @ValeraSetrakov it seems the fix has been released in the new version of Firebase Auth SDK 20.0.4, see [release notes ](https://firebase.google.com/support/release-notes/android#auth_v20-0-4). 

Can you try to upgrade to a newer Auth version to see if the problem persists?

Thanks

**Comment by ValeraSetrakov** [comment]
Hello, i will check it soon, thx for helping!
