### ISSUE TITLE
ANR in JobInfoSchedulerService + Crash in ViewRootImpl.doTraversal

### ISSUE THREAD

**Issue by kikogassen** [firebase/firebase-android-sdk#2566]
### Environment

  * Android Studio version: 4.1.3
  * Firebase Component: transport-runtime
  * Component version: 2.2.6

### Problem

Hi! I'm using a few firebase artifacts in my Android project and recently the project app is getting a few crashes and ANR related about the `JobInfoSchedulerService` class, present in `com.google.android.datatransport.runtime.scheduling.jobscheduling:transport-runtime@2.2.6`.

The curious part is that this problemas occured very few times in old versions of the app, but in a recent version it's occuring so many times.

The crash stack is:

```
Fatal Exception: java.lang.IllegalStateException: The specified message queue synchronization  barrier token has not been posted or has already been removed.
       at android.os.MessageQueue.removeSyncBarrier(MessageQueue.java:527)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2198)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9003)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:996)
       at android.view.Choreographer.doCallbacks(Choreographer.java:794)
       at android.view.Choreographer.doFrame(Choreographer.java:729)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:981)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7948)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```

The ANR is `executing service JobInfoSchedulerService` and the main thread stack is:

```
at android.os.MessageQueue.enqueueMessage (MessageQueue.java:581)
  at android.os.Handler.enqueueMessage (Handler.java:754)
  at android.os.Handler.sendMessageAtTime (Handler.java:703)
  at android.view.ViewRootImpl$ViewRootHandler.sendMessageAtTime (ViewRootImpl.java:5213)
  at android.os.Handler.sendMessageDelayed (Handler.java:673)
  at android.os.Handler.post (Handler.java:403)
  at android.view.View.post (View.java:19511)
  at android.widget.Editor$2.onDraw (Editor.java:272)
  at android.view.ViewTreeObserver.dispatchOnDraw (ViewTreeObserver.java:1141)
  at android.view.ViewRootImpl.draw (ViewRootImpl.java:4194)
  at android.view.ViewRootImpl.performDraw (ViewRootImpl.java:4047)
  at android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:3320)
  at android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:2200)
  at android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:9065)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:999)
  at android.view.Choreographer.doCallbacks (Choreographer.java:797)
  at android.view.Choreographer.doFrame (Choreographer.java:732)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:984)
  at android.os.Handler.handleCallback (Handler.java:883)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at android.os.Looper.loop (Looper.java:237)
  at android.app.ActivityThread.main (ActivityThread.java:8016)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:496)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1087)
```

#### Relevant Code:

The firebase artifacts versions present in app is
```
implementation 'com.google.firebase:firebase-auth:20.0.3'
implementation 'com.google.firebase:firebase-messaging:21.0.1'
implementation 'com.google.firebase:firebase-core:18.0.2'
implementation 'com.google.firebase:firebase-perf:19.1.1'
implementation 'com.google.firebase:firebase-analytics:18.0.2'
implementation 'com.google.firebase:firebase-crashlytics:17.4.0'
implementation platform('com.google.firebase:firebase-bom:26.0.0')
```

**Comment by aguatno** [comment]
Hi @kikogassen thanks for reporting. Can you provide some more details about how and when you're hitting this error? Having a small repro app would be very helpful here. Thanks

**Comment by kikogassen** [comment]
Hi @aguatno ! Thanks for your response. The problem was a lot of `TextView.text = "someString"` in a background thread. It didn't show ANR or crash while development, so, we didn't see any problem before publishing the app. We forced this `TextView` updates to perform in main thread and the problem is gone.
