### ISSUE TITLE
ImageViewAction.java line 52 com.squareup.picasso.ImageViewAction.complete

### ISSUE THREAD

**Issue by JobGetabu** [firebase/firebase-android-sdk#2568]
### [REQUIRED] Step 2: Describe your environment

Brand:TECNO
Model:SPARK
Orientation: Portrait
RAM free: 220.48 MB
Disk free: 4.06 GB
Android Version:7.0

#### Steps to reproduce:

ImageViewAction.java line 52
com.squareup.picasso.ImageViewAction.complete

#### Relevant Code:

```
Fatal Exception: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
       at android.view.ViewRootImpl.setView(ViewRootImpl.java:797)
       at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:351)
       at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
       at com.google.firebase.inappmessaging.display.internal.FiamWindowManager.show(FiamWindowManager.java:62)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay$4$4.run(FirebaseInAppMessagingDisplay.java:412)
       at android.app.Activity.runOnUiThread(Activity.java:5855)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay$4.onSuccess(FirebaseInAppMessagingDisplay.java:408)
       at com.squareup.picasso.ImageViewAction.complete(ImageViewAction.java:52)
       at com.squareup.picasso.Picasso.deliverAction(Picasso.java:576)
       at com.squareup.picasso.Picasso.complete(Picasso.java:528)
       at com.squareup.picasso.Picasso$1.handleMessage(Picasso.java:122)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6251)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
```

**Comment by aguatno** [comment]
Hi @JobGetabu. I’m finding it quite difficult replicating your issue without an [mcve](https://stackoverflow.com/help/minimal-reproducible-example), could you able to provide a minimal runnable repro of your app so I can also test this one locally? Thanks
