### ISSUE TITLE
PhoneAuthProvider.verifyPhoneNumber(options); crashing app

### ISSUE THREAD

**Issue by mozadevelopment** [firebase/firebase-android-sdk#2572]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio 4.1.3
  * Firebase Component: Auth
  * Component version: implementation platform('com.google.firebase:firebase-bom:26.8.0'

#### Steps to reproduce:

Hello. I am trying to authenticate users with a phone number, but my app crashes when trying to launch the Verify activity. I have implementation 'androidx.browser:browser:1.2.0' in my dependencies. SHA1 keys are in Firebase and Google Cloud Platform is set up. Tested on emulator and my phone, both with same result.

2021-04-08 10:23:48.735 12990-12990/com.[app company].[app name] E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.[app company].[app name], PID: 12990
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.[app company].[app name]/com.[app company].[app name].VerifyPhoneActivity}: java.lang.NullPointerException: null reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.NullPointerException: null reference
        at com.google.android.gms.common.internal.Preconditions.checkNotNull(com.google.android.gms:play-services-basement@@17.1.0:2)
        at com.google.firebase.auth.PhoneAuthOptions$Builder.<init>(com.google.firebase:firebase-auth@@20.0.3:1)
        at com.google.firebase.auth.PhoneAuthOptions.newBuilder(com.google.firebase:firebase-auth@@20.0.3:2)
        at com.[app company].[app name].VerifyPhoneActivity.sendVerificationCode(VerifyPhoneActivity.java:43)
        at com.[app company].[app name].VerifyPhoneActivity.onCreate(VerifyPhoneActivity.java:37)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 

#### Relevant Code:

@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_verify_phone);

        codeByUser = findViewById(R.id.editTextCode);

        String phoneNumber = getIntent().getStringExtra("phone");
        
        sendVerificationCode(phoneNumber);

    }

    public PhoneAuthProvider.OnVerificationStateChangedCallbacks mCallbacks =
            new PhoneAuthProvider.OnVerificationStateChangedCallbacks() {

                @Override
                public void onCodeSent(@NonNull String s, @NonNull PhoneAuthProvider.ForceResendingToken forceResendingToken) {
                    super.onCodeSent(s, forceResendingToken);
                    codeBySystem = s;
                }

                @Override
                public void onVerificationCompleted(@NonNull PhoneAuthCredential phoneAuthCredential) {
                    String code = phoneAuthCredential.getSmsCode();

                    if(code != null){
                        codeByUser.setText(code);
                        verifyCode(code);
                    }
                }

                @Override
                public void onVerificationFailed(@NonNull FirebaseException e) {
                    Toast.makeText(VerifyPhoneActivity.this, e.getMessage(), Toast.LENGTH_LONG).show();
                }
            };

    public void sendVerificationCode(String phoneNumber) {
        PhoneAuthOptions options =
                PhoneAuthOptions.newBuilder(mAuth)
                        .setPhoneNumber(phoneNumber)       // Phone number to verify
                        .setTimeout(60L, TimeUnit.SECONDS) // Timeout and unit
                        .setActivity(this)              // Activity (for callback binding)
                        .setCallbacks(mCallbacks)   // OnVerificationStateChangedCallbacks
                        .build();
        PhoneAuthProvider.verifyPhoneNumber(options);
    }

**Comment by aguatno** [comment]
Hi @mozadevelopment to verify if there's an issue, I've tried running our Firebase Auth Quickstart for Android [here](https://github.com/firebase/quickstart-android/tree/master/auth), but I wasn’t able to encounter the error message you’ve reported. With this, could you also try our sample code on your end, and see if you'll still encounter any issues. You may use this as a baseline for troubleshooting.

Also check if the Google Play Services of your device/emulator is updated. In case the issue persists, do let me know and provide a minimal reproduction of the issue (please make it minimal so I can easily reproduce the issue on my end).
