### ISSUE TITLE
Failed to get document because the client is offline

### ISSUE THREAD

**Issue by SzyQ** [firebase/firebase-android-sdk#2575]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: _____ 4.1.3
  * Firebase Component: _____ Firestore
  * Component version: _____ BOM 26.3.0

### [REQUIRED] Step 3: Describe the problem
When network is not available, library is crashing.
```
Fatal Exception: q.i.c.t.l: Failed to get document because the client is offline.
       at com.google.firebase.firestore.DocumentReference.lambda$getViaSnapshotListener$1(DocumentReference.java:6)
       at com.google.firebase.firestore.DocumentReference$$Lambda$2.onEvent(DocumentReference.java:6)
       at com.google.firebase.firestore.DocumentReference.lambda$addSnapshotListenerInternal$2(DocumentReference.java:16)
       at com.google.firebase.firestore.DocumentReference$$Lambda$3.onEvent(DocumentReference.java:16)
       at com.google.firebase.firestore.core.AsyncEventListener.lambda$onEvent$0(AsyncEventListener.java:1)
       at com.google.firebase.firestore.core.AsyncEventListener$$Lambda$1.run(AsyncEventListener.java:1)
       at com.google.firebase.firestore.util.Executors$$Lambda$1.execute(Executors.java)
       at com.google.firebase.firestore.core.AsyncEventListener.onEvent(AsyncEventListener.java:2)
       at com.google.firebase.firestore.core.QueryListener.raiseInitialEvent(QueryListener.java:14)
       at com.google.firebase.firestore.core.QueryListener.onViewSnapshot(QueryListener.java:15)
       at com.google.firebase.firestore.core.EventManager.onViewSnapshots(EventManager.java:4)
       at com.google.firebase.firestore.core.SyncEngine.listen(SyncEngine.java:31)
       at com.google.firebase.firestore.core.EventManager.addQueryListener(EventManager.java:31)
       at com.google.firebase.firestore.core.FirestoreClient.lambda$listen$6(FirestoreClient.java:31)
       at com.google.firebase.firestore.core.FirestoreClient$$Lambda$6.run(FirestoreClient.java:31)
       at com.google.firebase.firestore.util.AsyncQueue.lambda$enqueue$2(AsyncQueue.java:1)
       at com.google.firebase.firestore.util.AsyncQueue$$Lambda$2.call(AsyncQueue.java:1)
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor.lambda$executeAndReportResult$1(AsyncQueue.java:1)
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$$Lambda$2.run(AsyncQueue.java:1)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:15)
       at java.lang.Thread.run(Thread.java:919)
```

DocumentReference class has even a TODO in a place exception is thrown:
 _// TODO: Reconsider how to raise missing documents when offline.
                  // If we're online and the document doesn't exist then we set the result
                  // of the Task with a document with document.exists set to false. If we're
                  // offline however, we set the Exception on the Task. Two options:
                  //
                  // 1)  Cache the negative response from the server so we can deliver that
                  //     even when you're offline.
                  // 2)  Actually set the Exception of the Task if the document doesn't
                  //     exist when you are offline._
#### Steps to reproduce:

It's really hard to reproduce. Common root cause of the issue is problem with a network or DNS resolution.

#### Relevant Code:
Simple read of firestore snapshot e.g.
```
internal suspend fun readDocument(
        id1: String,
        id2: String
    ) = firestore.collection("somepath").document(id1).collection("collectionpath")
        .document(id2)
        .get()
        .await()
        .takeIf { it.exists() }
```

**Comment by dconeybe** [comment]
Hi @SzyQ. I'm sorry that you are experiencing this crash. Are you able to provide any additional context to the crash? For example, do you have a full logcat that you could attach? Are you able to enable Firestore debug logging by calling `FirebaseFirestore.setLoggingEnabled(true)` https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/FirebaseFirestore#setLoggingEnabled(boolean) prior to reproducing the crash?

**Comment by SzyQ** [comment]
Hi @dconeybe, unfortunately I'm unable to reproduce this myself. I see this crash in Crashlytics as top 2 occurring issue. The only hint basing on log I see in crashlytics is that prior to that crash a document was deleted by user.

**Comment by dconeybe** [comment]
Is there any additional info from the crashlytics reports that you could provide, even if it seems unrelated?

**Comment by SzyQ** [comment]
<img width="448" alt="Screenshot 2021-04-09 at 22 08 35" src="https://user-images.githubusercontent.com/2025046/114235214-2628be00-9980-11eb-859e-71357024efc6.png">
Doesn't seem relevant, but at least that I can share

**Comment by dconeybe** [comment]
Are you by any chance able to de-minify `q.i.c.t.l`, the type of exception that was thrown? Is it `FirebaseFirestoreException`? If so, I can't figure out where the exception is being thrown because it should just be setting the exception as the result of a task. I'm going to need to dig into this further next week. Sorry that I don't have any immediate assistance to provide.

**Comment by SzyQ** [comment]
That's right: com.google.firebase.firestore.FirebaseFirestoreException -> v.i.c.u.l:

**Comment by SzyQ** [comment]
@dconeybe I'm sorry. You are totally right! I've found places where exceptions are unhandled, and they need to because I'm using await(). I will close that issue, however if you have any idea how to avoid falling into this problem(firestore should work offline, right?), please let me know.

**Comment by dconeybe** [comment]
That's great news! I'm glad you were able to fix the crash.

The "Failed to get document because the client is offline" error occurs when you attempt to retrieve a *single document*, you are offline, and the requested document is absent from the local cache. In this case, the client has no information about the document and does not know if it exists on the backend. There is no way to know if the document exists until a network connection is re-established. So to avoid incorrectly reporting that a document does not exist, this error is produced.

This situation can largely be avoided by getting the document while in an online state so that it is present in the local cache. Note, however, that the local cache is a *cache*, and "stale" entries may be evicted from the cache to make room for other data. If the data in the document does not change frequently, you could also instead register a snapshot listener via `addSnapshotListener()` and keep the listener alive to ensure that the document remains in the local cache.

I hope this helps!

**Comment by svenjacobs** [comment]
@dconeybe Thanks for the detailed explanation of this issue. We're facing the same exception in our app since 2018 😮

We added `try ... catch` around all `get().await()` calls however this exception still occurs for `addSnapshotListener()`. The stack trace is as follows:

```
com.google.firebase.firestore.FirebaseFirestoreException: Failed to get document because the client is offline.
       at com.google.firebase.firestore.DocumentReference.lambda$getViaSnapshotListener$1(DocumentReference.java:331)
       at com.google.firebase.firestore.DocumentReference$$Lambda$2.onEvent(DocumentReference.java:8)
       at com.google.firebase.firestore.DocumentReference.lambda$addSnapshotListenerInternal$2(DocumentReference.java:504)
       at com.google.firebase.firestore.DocumentReference$$Lambda$3.onEvent(DocumentReference.java:16)
       at com.google.firebase.firestore.core.AsyncEventListener.lambda$onEvent$0(AsyncEventListener.java:42)
       at com.google.firebase.firestore.core.AsyncEventListener$$Lambda$1.run(AsyncEventListener.java:2)
       at com.google.firebase.firestore.util.Executors$$Lambda$1.execute(Executors.java)
       at com.google.firebase.firestore.core.AsyncEventListener.onEvent(AsyncEventListener.java:39)
       at com.google.firebase.firestore.core.QueryListener.raiseInitialEvent(QueryListener.java:176)
       at com.google.firebase.firestore.core.QueryListener.onViewSnapshot(QueryListener.java:95)
       at com.google.firebase.firestore.core.EventManager.addQueryListener(EventManager.java:97)
       at com.google.firebase.firestore.core.FirestoreClient.lambda$listen$6(FirestoreClient.java:160)
       at com.google.firebase.firestore.core.FirestoreClient$$Lambda$6.run(FirestoreClient.java:12)
       at com.google.firebase.firestore.util.AsyncQueue.lambda$enqueue$2(AsyncQueue.java:436)
       at com.google.firebase.firestore.util.AsyncQueue$$Lambda$2.call(AsyncQueue.java:1)
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor.lambda$executeAndReportResult$1(AsyncQueue.java:322)
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$$Lambda$2.run(AsyncQueue.java:1)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:229)
       at java.lang.Thread.run(Thread.java:919)
```

Shouldn't a snapshot listener only fire when there is actual data to be fetched? In which scenario can this exception happen inside a snapshot listener and how can it be handled on our side?

Firestore version 22.1.2.

**Comment by dconeybe** [comment]
@svenjacobs Do you still have an issue to discuss? If so, could you open a new issue and tag me?

**Comment by svenjacobs** [comment]
> @svenjacobs Do you still have an issue to discuss? If so, could you open a new issue and tag me?

No, thank you! Now that we added `try...catch` there should be an improvement in stability.
