### ISSUE TITLE
StrictMode(30621): A resource was acquired at attached stack trace but never released

### ISSUE THREAD

**Issue by EGecius** [firebase/firebase-android-sdk#2581]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.01
  * Firebase Component: com.google.firebase:firebase-auth-ktx
  * Component version: 20.0.3

### [REQUIRED] Step 3: Describe the problem

It's not easy to reproduce. Some have observed it to happen more often when disconnecting from the network.

StrictMode keep sterminaing the app with this stractrace:

04-12 10:06:14.591 E/StrictMode(30621): A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
04-12 10:06:14.591 E/StrictMode(30621): java.lang.Throwable: Explicit termination method 'close' not called
04-12 10:06:14.591 E/StrictMode(30621): 	at dalvik.system.CloseGuard.open(CloseGuard.java:180)
04-12 10:06:14.591 E/StrictMode(30621): 	at java.net.AbstractPlainSocketImpl.create(AbstractPlainSocketImpl.java:103)
04-12 10:06:14.591 E/StrictMode(30621): 	at java.net.Socket.createImpl(Socket.java:470)
04-12 10:06:14.591 E/StrictMode(30621): 	at java.net.Socket.getImpl(Socket.java:536)
04-12 10:06:14.591 E/StrictMode(30621): 	at java.net.Socket.setSoTimeout(Socket.java:1134)
04-12 10:06:14.591 E/StrictMode(30621): 	at com.android.okhttp.Connection.connectSocket(Connection.java:195)
04-12 10:06:14.591 E/StrictMode(30621): 	at com.android.okhttp.Connection.connect(Connection.java:172)
04-12 10:06:14.591 E/StrictMode(30621): 	at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
04-12 10:06:14.591 E/StrictMode(30621): 	at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
04-12 10:06:14.591 E/StrictMode(30621): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
04-12 10:06:14.591 E/StrictMode(30621): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:247)
04-12 10:06:14.591 E/StrictMode(30621): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
04-12 10:06:14.591 E/StrictMode(30621): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:126)
04-12 10:06:14.591 E/StrictMode(30621): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:257)
04-12 10:06:14.591 E/StrictMode(30621): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
04-12 10:06:14.591 E/StrictMode(30621): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java)
04-12 10:06:14.591 E/StrictMode(30621): 	at com.google.android.gms.internal.firebase-auth-api.zzvg.zza(com.google.firebase:firebase-auth@@20.0.3:10)
04-12 10:06:14.591 E/StrictMode(30621): 	at com.google.android.gms.internal.firebase-auth-api.zzuq.zzb(com.google.firebase:firebase-auth@@20.0.3:4)
04-12 10:06:14.591 E/StrictMode(30621): 	at com.google.android.gms.internal.firebase-auth-api.zzpy.zza(com.google.firebase:firebase-auth@@20.0.3:4)
04-12 10:06:14.591 E/StrictMode(30621): 	at com.google.android.gms.internal.firebase-auth-api.zztu.zzb(com.google.firebase:firebase-auth@@20.0.3:5)
04-12 10:06:14.591 E/StrictMode(30621): 	at com.google.android.gms.internal.firebase-auth-api.zzqw.zzd(com.google.firebase:firebase-auth@@20.0.3:3)
04-12 10:06:14.591 E/StrictMode(30621): 	at com.google.android.gms.internal.firebase-auth-api.zzqv.accept(com.google.firebase:firebase-auth@@20.0.3)
04-12 10:06:14.591 E/StrictMode(30621): 	at com.google.android.gms.common.api.internal.zacj.doExecute(com.google.android.gms:play-services-base@@17.1.0:2)
04-12 10:06:14.591 E/StrictMode(30621): 	at com.google.android.gms.common.api.internal.zaf.zac(com.google.android.gms:play-services-base@@17.1.0:6)
04-12 10:06:14.591 E/StrictMode(30621): 	at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zac(com.google.android.gms:play-services-base@@17.1.0:167)
04-12 10:06:14.591 E/StrictMode(30621): 	at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zab(com.google.android.gms:play-services-base@@17.1.0:139)
04-12 10:06:14.591 E/StrictMode(30621): 	at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zabg(com.google.android.gms:play-services-base@@17.1.0:99)
04-12 10:06:14.591 E/StrictMode(30621): 	at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zabe(com.google.android.gms:play-services-base@@17.1.0:40)
04-12 10:06:14.591 E/StrictMode(30621): 	at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.onConnected(com.google.android.gms:play-services-base@@17.1.0:19)
04-12 10:06:14.591 E/StrictMode(30621): 	at com.google.android.gms.common.internal.zaf.onConnected(com.google.android.gms:play-services-base@@17.1.0:2)
04-12 10:06:14.591 E/StrictMode(30621): 	at com.google.android.gms.common.internal.BaseGmsClient$zzg.zzj(com.google.android.gms:play-services-basement@@17.1.0:24)
04-12 10:06:14.591 E/StrictMode(30621): 	at com.google.android.gms.common.internal.BaseGmsClient$zza.zza(com.google.android.gms:play-services-basement@@17.1.0:12)
04-12 10:06:14.591 E/StrictMode(30621): 	at com.google.android.gms.common.internal.BaseGmsClient$zzb.zzo(com.google.android.gms:play-services-basement@@17.1.0:11)
04-12 10:06:14.591 E/StrictMode(30621): 	at com.google.android.gms.common.internal.BaseGmsClient$zzc.handleMessage(com.google.android.gms:play-services-basement@@17.1.0:49)
04-12 10:06:14.591 E/StrictMode(30621): 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-12 10:06:14.591 E/StrictMode(30621): 	at com.google.android.gms.internal.common.zzi.dispatchMessage(com.google.android.gms:play-services-basement@@17.1.0:8)
04-12 10:06:14.591 E/StrictMode(30621): 	at android.os.Looper.loop(Looper.java:154)
04-12 10:06:14.591 E/StrictMode(30621): 	at android.os.HandlerThread.run(HandlerThread.java:61)
04-12 10:06:14.591 W/System.err(30621): StrictMode VmPolicy violation with POLICY_DEATH; shutting down.

**Comment by aguatno** [comment]
Hi @EGecius I found a[ community post ](https://stackoverflow.com/questions/25544021/a-resource-was-acquired-at-attached-stack-trace-but-never-released-see-java-io)that talks about an issue similar to yours, and you can try the troubleshooting steps in that post to see if the issue has been resolved. Also, I'd like you to try out our [quickstart for Android](https://github.com/firebase/quickstart-android). With this, you can use it as a reference and compare with your project or make incremental changes to see where issues occur.

 

If none of these worked, I'd like you to provide a minimal, reproducible example of your project along with the steps needed to replicate your issue. This way, the cause of the issue can be identified.

**Comment by malcolmdeck** [comment]
This is almost certainly a missing #close() statement in the Auth SDK. I've filed b/185793197 for internal tracking

**Comment by EGecius** [comment]
thank you for filing an internal bug 👍

**Comment by lehcar09** [comment]
Hi everyone, per checking the internal bug this issue has been released. I'll be closing this issue now. Please do let us know if there's any misunderstanding or the issue persists. Thanks!
