### ISSUE TITLE
Fatal Exception: ScionFrontendApi on upgrading firebase versions together with gms

### ISSUE THREAD

**Issue by jayshah123** [firebase/firebase-android-sdk#2620]
Observing the following crash:
```
2021-04-24 17:34:21.486 9619-9642/in.mycompany.myapp E/AndroidRuntime: FATAL EXCEPTION: ScionFrontendApi
    Process: in.mycompany.myapp, PID: 9619
    java.lang.VerifyError: Verifier rejected class com.google.android.gms.measurement.internal.zzfp: void com.google.android.gms.measurement.internal.zzfp.zzN(java.lang.String, int, java.lang.Throwable, byte[], java.util.Map) failed to verify: void com.google.android.gms.measurement.internal.zzfp.zzN(java.lang.String, int, java.lang.Throwable, byte[], java.util.Map): [0x37] 'this' arg must be initialized (declaration of 'com.google.android.gms.measurement.internal.zzfp' appears in /data/app/in.mycompany.myapp-zfkLQ-CtTDdM7bRGUt2Hog==/base.apk)
        at com.google.android.gms.measurement.internal.zzfp.zzC(Unknown Source:0)
        at com.google.android.gms.measurement.internal.AppMeasurementDynamiteService.initialize(com.google.android.gms:play-services-measurement-sdk@@18.0.3:2)
        at com.google.android.gms.internal.measurement.zzal.zza(com.google.android.gms:play-services-measurement-sdk-api@@18.0.3:12)
        at com.google.android.gms.internal.measurement.zzbh.run(com.google.android.gms:play-services-measurement-sdk-api@@18.0.3:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.1.1
  * Firebase Component: mentioned in the dependencies :`implementation platform('com.google.firebase:firebase-bom:27.0.0')`: Firebase Messaging, analytics and remote config.
* GMS services used: `gms:play-services-base`, `gms:play-services-maps`, `gms:play-services-tagmanager`
  * Component version: mentioned in the dependencies
 ```
implementation jscFlavor
implementation fileTree(include: ['*.jar'], dir: 'libs')
implementation('com.google.android.material:material:1.0.0') {
    force = true;
}
implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.0.0"

implementation 'androidx.multidex:multidex:2.0.1'
implementation platform('com.google.firebase:firebase-bom:27.0.0')
implementation 'com.google.firebase:firebase-messaging'
implementation 'com.google.firebase:firebase-core'
implementation 'com.google.firebase:firebase-config'
implementation 'com.google.firebase:firebase-analytics'

implementation 'com.google.code.gson:gson:2.7'
implementation 'com.squareup.retrofit2:converter-gson:2.1.0'
implementation 'com.squareup.retrofit2:retrofit:2.4.0'
implementation ('com.squareup.okhttp3:okhttp:3.11.0'){
    force = true;
}
implementation 'com.google.android.gms:play-services-tagmanager:17.0.0'
implementation 'com.facebook.fresco:fresco:1.13.0'
implementation 'com.facebook.fresco:animated-gif:1.13.0'
implementation(project(':react-native-maps'))
implementation('com.google.android.gms:play-services-base:17.6.0')
implementation('com.google.android.gms:play-services-maps:17.0.0')
implementation 'com.newrelic.agent.android:android-agent:5.19.1'

implementation 'com.facebook.stetho:stetho:1.5.1'
implementation 'com.facebook.stetho:stetho-okhttp3:1.5.1'
implementation 'com.facebook.stetho:stetho-js-rhino:1.5.1'
androidTestImplementation('com.wix:detox:+')
  ```

Contents of the root build.gradle:
```
buildscript {
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.3'
        classpath 'com.google.gms:google-services:4.3.5'
        classpath "com.newrelic.agent.android:agent-gradle-plugin:5.19.1"
        classpath 'com.google.android.gms:strict-version-matcher-plugin:1.2.2'
    }
}

subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                buildToolsVersion '29.0.3'
                defaultConfig {
                    minSdkVersion 18
                    targetSdkVersion 29
                }
            }
        }
    }
}

allprojects {
    repositories {
        google()
        maven { url "https://www.jitpack.io" }
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        jcenter()
        maven { url 'https://www.jitpack.io' }
        maven {
            url "$rootDir/../node_modules/detox/Detox-android"
        }
    }
}

```

### [REQUIRED] Step 3: Describe the problem
App crashes on launch

#### Steps to reproduce:

```
2021-04-24 17:34:21.486 9619-9642/in.mycompany.myapp E/AndroidRuntime: FATAL EXCEPTION: ScionFrontendApi
    Process: in.mycompany.myapp, PID: 9619
    java.lang.VerifyError: Verifier rejected class com.google.android.gms.measurement.internal.zzfp: void com.google.android.gms.measurement.internal.zzfp.zzN(java.lang.String, int, java.lang.Throwable, byte[], java.util.Map) failed to verify: void com.google.android.gms.measurement.internal.zzfp.zzN(java.lang.String, int, java.lang.Throwable, byte[], java.util.Map): [0x37] 'this' arg must be initialized (declaration of 'com.google.android.gms.measurement.internal.zzfp' appears in /data/app/in.mycompany.myapp-zfkLQ-CtTDdM7bRGUt2Hog==/base.apk)
        at com.google.android.gms.measurement.internal.zzfp.zzC(Unknown Source:0)
        at com.google.android.gms.measurement.internal.AppMeasurementDynamiteService.initialize(com.google.android.gms:play-services-measurement-sdk@@18.0.3:2)
        at com.google.android.gms.internal.measurement.zzal.zza(com.google.android.gms:play-services-measurement-sdk-api@@18.0.3:12)
        at com.google.android.gms.internal.measurement.zzbh.run(com.google.android.gms:play-services-measurement-sdk-api@@18.0.3:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

#### Relevant Code:

```
Usage of firebase messaging, and firebase config as per the docs.
```

**Comment by jayshah123** [comment]
There really needs to be a compatibility list about which versions of play services will work correctly with which versions of firebase/bom.

**Comment by jayshah123** [comment]
fixed as per https://stackoverflow.com/questions/67242786/fatal-exception-sciofrontendapi-when-upgrading-google-play-services-with-fireba/67250331#67250331
