### ISSUE TITLE
[Firebase Crashlytics] AssertionError: No NameTypeIndex match for SHORT_DAYLIGHT

### ISSUE THREAD

**Issue by juliemovify** [firebase/firebase-android-sdk#2622]
### Environment

  * Android Studio version: **4.1.3**
  * Firebase Component: **Crashlytics**
  * Component version: **17.3.1**
  * **Crash reports on Android 8 / old devices**

#### Steps to reproduce:

Crash happens at app start. 

#### Relevant Code:

```
Fatal Exception: java.lang.AssertionError: No NameTypeIndex match for SHORT_DAYLIGHT
       at android.icu.impl.TimeZoneNamesImpl$ZNames.getNameTypeIndex(TimeZoneNamesImpl.java:724)
       at android.icu.impl.TimeZoneNamesImpl$ZNames.getName(TimeZoneNamesImpl.java:790)
       at android.icu.impl.TimeZoneNamesImpl.getTimeZoneDisplayName(TimeZoneNamesImpl.java:183)
       at android.icu.text.TimeZoneNames.getDisplayName(TimeZoneNames.java:261)
       at java.text.SimpleDateFormat.subFormat(SimpleDateFormat.java:1296)
       at java.text.SimpleDateFormat.format(SimpleDateFormat.java:1004)
       at java.text.SimpleDateFormat.format(SimpleDateFormat.java:974)
       at java.text.DateFormat.format(DateFormat.java:341)
       at com.google.firebase.heartbeatinfo.HeartBeatInfoStorage.isSameDateUtc(HeartBeatInfoStorage.java:133)
       at com.google.firebase.heartbeatinfo.HeartBeatInfoStorage.shouldSendSdkHeartBeat(HeartBeatInfoStorage.java:143)
       at com.google.firebase.heartbeatinfo.DefaultHeartBeatInfo.getHeartBeatCode(DefaultHeartBeatInfo.java:71)
       at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.openHttpURLConnection(FirebaseInstallationServiceClient.java:473)
       at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.generateAuthToken(FirebaseInstallationServiceClient.java:393)
       at com.google.firebase.installations.FirebaseInstallations.fetchAuthTokenFromServer(FirebaseInstallations.java:566)
       at com.google.firebase.installations.FirebaseInstallations.doNetworkCallIfNecessary(FirebaseInstallations.java:390)
       at com.google.firebase.installations.FirebaseInstallations.lambda$doRegistrationOrRefresh$2(FirebaseInstallations.java:377)
       at com.google.firebase.installations.FirebaseInstallations$$Lambda$4.run(FirebaseInstallations.java:4)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
```

**Comment by aguatno** [comment]
Hi @juliemovify I can't tell for sure what seems to be the issue. We are not receiving any similar cases at the moment so it's likely that the issue is isolated to your project.

I've searched for relevant issues and what I've found so far is that the issue was at a time relevant to [Facebook SDK](https://stackoverflow.com/questions/51453091/android-facebook-sdk-internal-utility-java-lang-assertionerror). This might be a long shot but please try tracing all of your methods handling time/date management.

If the issue persists, please provide a sample app to reproduce and the steps to replicate the issue, I'll be able to borrow some time from our engineers to check it out.

**Comment by juliemovify** [comment]
Hello @aguatno,

This is a crash reported by Crashlytics for around 80 users (a low percentage of our userbase). We couldn't reproduce locally.
Looking at the stack trace, it is originating directly from Firebase SDK; it doesn't expose any of our methods. We don't have any reported issues that relate to our date/time management.

**Comment by ber4444** [comment]
I have the same crash too in https://github.com/firebase/firebase-android-sdk/blob/ac3276ce7d5f5181b1c419731495eb88a98537af/firebase-common/src/main/java/com/google/firebase/heartbeatinfo/HeartBeatInfoStorage.java#L133

Android 8, device is a Palm (https://palm.com).

**Comment by sgjesse** [comment]
This is most likely caused by a bug in the Android platform, see https://issuetracker.google.com/110848122#comment17.

**Comment by argzdev** [comment]
Just bumping this thread, is anyone still experiencing this behavior on the latest version of the SDK?
