### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException java.lang.NullPointerException: Null backendName android.app.job.JobService$JobHandler.handleMessage

### ISSUE THREAD

**Issue by changjiashuai** [firebase/firebase-android-sdk#2648]
Fatal Exception: java.lang.RuntimeException: java.lang.NullPointerException: Null backendName
       at android.app.job.JobService$JobHandler.handleMessage(JobService.java:130)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5452)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:762)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)

Caused by java.lang.NullPointerException: Null backendName
       at java.util.Objects.requireNonNull(Objects.java:109)
       at com.google.android.datatransport.runtime.AutoValue_TransportContext$Builder.setBackendName(AutoValue_TransportContext.java:80)
       at com.google.android.datatransport.runtime.scheduling.jobscheduling.JobInfoSchedulerService.onStartJob(JobInfoSchedulerService.java:40)
       at android.app.job.JobService$JobHandler.handleMessage(JobService.java:126)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5452)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:762)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)

设备
品牌：MIONE
型号：Mione Hot 8
屏幕方向： 纵向
可用 RAM： 429.38 MB
可用磁盘空间： 3.92 GB

操作系统
版本：6.0
屏幕方向： 纵向
是否已取得 root 权限：否

崩溃
日期：2021年5月4日 下午2:30:04
应用版本：5.0.9 (103)

**Comment by aguatno** [comment]
Hi @changjiashuai It seems that your inquiry doesn't follow the template. With this, I'll be closing this ticket for now.

In order for me to get a better understanding of this issue, you may file another ticket that uses the issue template.

Thanks
