### ISSUE TITLE
javax.net.ssl.SSLException: Unable to create application data

### ISSUE THREAD

**Issue by weizheng-nathan** [firebase/firebase-android-sdk#2660]
I met several crashes related to FirebaseInstallation, this only happen on Zebra TC51 with Android 8, this crash is reported by Firebase Crashlytics, and based on the trace, it crashed when the app is starting, so there's no clear reproduce steps .
Fatal Exception: java.lang.RuntimeException: javax.net.ssl.SSLException: Unable to create application data
       at com.android.org.conscrypt.ConscryptFileDescriptorSocket.newSsl(ConscryptFileDescriptorSocket.java:161)
       at com.android.org.conscrypt.ConscryptFileDescriptorSocket.<init>(ConscryptFileDescriptorSocket.java:152)
       at com.android.org.conscrypt.OpenSSLSocketFactoryImpl.createSocket(OpenSSLSocketFactoryImpl.java:149)
       at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:181)
       at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
       at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
       at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
       at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
       at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:258)
       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java)
       at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.writeRequestBodyToOutputStream(FirebaseInstallationServiceClient.java:226)
       at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.writeGenerateAuthTokenRequestBodyToOutputStream(FirebaseInstallationServiceClient.java:267)
       at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.generateAuthToken(FirebaseInstallationServiceClient.java:399)
       at com.google.firebase.installations.FirebaseInstallations.fetchAuthTokenFromServer(FirebaseInstallations.java:566)
       at com.google.firebase.installations.FirebaseInstallations.doNetworkCallIfNecessary(FirebaseInstallations.java:390)
       at com.google.firebase.installations.FirebaseInstallations.lambda$doRegistrationOrRefresh$2(FirebaseInstallations.java:377)
       at com.google.firebase.installations.FirebaseInstallations$$Lambda$4.run(FirebaseInstallations.java:4)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

**Comment by aguatno** [comment]
Hi @weizheng-nathan It seems that your inquiry doesn't follow the template. With this, I'll be closing this ticket for now.

In order for me to get a better understanding of this issue, you may file another ticket that uses the issue template.

Thanks

**Comment by weizheng-nathan** [comment]
Hi, 
I state clearly, I see this from Firebase crashlytics on Zebra TC51 with Android 8, and that's all I have.
So you just don't want to look into the code to at least give a clue why this crash happens, and give some hint on how to reproduce?
