### ISSUE TITLE
Unable to resume activity {com.google.firebase.auth.internal.RecaptchaActivity}: java.lang.NullPointerException: uriString

### ISSUE THREAD

**Issue by erikjhordan-rey** [firebase/firebase-android-sdk#2666]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: `4.1.3`
  * Firebase Component: [Firebase Auth ](https://firebase.google.com/docs/auth/android/phone-auth)
  * Component version: `20.0.4`

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

Since we updated to `20.0.4` version our app starts to crash, we don't get the specific scenario to reproduce it but it's related to `RecaptchaActivity`, and web views missing or not support all browsers won't work in `opera, firefox` 

#### Relevant Code:

 **Unable to resume activity {com.google.firebase.auth.internal.RecaptchaActivity}: java.lang.NullPointerException: uriString**

```
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {com.google.firebase.auth.internal.RecaptchaActivity}: java.lang.NullPointerException: uriString
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4864)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4901)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8512)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Missing Webview**

```
Fatal Exception: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://proyect.firebaseapp.com/... flg=0x50000000 (has extras) }
```

**Comment by aguatno** [comment]
Hi @erikjhordan-rey thanks for reporting.

There was an update to allow devices without Google Play services to use Firebase Auth ([click here](https://firebase.googleblog.com/2020/10/firebase-auth-android-non-gms.html) for more details). Now, it looks like one additional requirement for that is to enable the SafetyNet API ([click here](https://firebase.google.com/docs/auth/android/phone-auth#enable-app-verification) for more details), otherwise the flow will require solving a reCaptcha. Enabling SafetyNet requires the following:

* Enable the Android DeviceCheck API in the [GCP Console](https://console.cloud.google.com/apis/library/androidcheck.googleapis.com) 
* Add the app's SHA-256 fingerprint in the Firebase Console

Let me know if that works for you, otherwise please provide sample runnable app so we test it locally. Thanks

**Comment by chokokatana** [comment]
During this weekend I experienced similar stack traces in crashes:
```
Fatal Exception: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://wave-v1.firebaseapp.com/... flg=0x50000000 (has extras) }
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2114)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1757)
       at android.app.Activity.startActivityForResult(Activity.java:4803)
       at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:675)
       at android.app.Activity.startActivityForResult(Activity.java:4743)
       at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:662)
       at android.app.Activity.startActivity(Activity.java:5164)
       at android.app.Activity.startActivity(Activity.java:5132)
       at com.google.firebase.auth.internal.RecaptchaActivity.zza(RecaptchaActivity.java:12)
       at com.google.android.gms.internal.firebase-auth-api.zztw.zzb(zztw.java:7)
       at com.google.android.gms.internal.firebase-auth-api.zztw.onPostExecute(zztw.java:2)
       at android.os.AsyncTask.finish(AsyncTask.java:696)
       at android.os.AsyncTask.access$600(AsyncTask.java:180)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:713)
       at android.os.Handler.dispatchMessage(Handler.java:112)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```
This happened using a firebase BOM of 27.1.0, and the crashes were restricted to a single user with a HUAWEI Y6 2019 with Android 9. Any other device works fine, the closest device I have is a Huawei P Smart Plus 2019 (POT-LX1T) and there the login/authentication works fine, so I can't replicate the crashes.

I see there's a new BOM of 28.0.1 so I'll try that and see if the crashes appear again.
