### ISSUE TITLE
FirebaseCrashlytics: Settings request failed.

### ISSUE THREAD

**Issue by pokerfaceCmy** [firebase/firebase-android-sdk#2678]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.2.1
  * Firebase Component: Crashlytics (Database, Firestore, Storage, Functions, etc)
  * Component version: 18.0.0

#### Steps to reproduce:

2021-05-20 19:01:52.912 7516-7516/com.wetech.aus.tennis.app I/FirebaseCrashlytics: Initializing Firebase Crashlytics 18.0.0 for com.wetech.aus.tennis.app
2021-05-20 19:01:52.915 7516-7516/com.wetech.aus.tennis.app D/FirebaseCrashlytics: Crashlytics automatic data collection ENABLED by global Firebase setting.
2021-05-20 19:01:52.917 7516-7516/com.wetech.aus.tennis.app D/FirebaseCrashlytics: Registered Firebase Analytics listener.
2021-05-20 19:01:52.918 7516-7516/com.wetech.aus.tennis.app D/FirebaseCrashlytics: Mapping file ID is: 00000000000000000000000000000000
2021-05-20 19:01:52.921 7516-7516/com.wetech.aus.tennis.app D/FirebaseCrashlytics: Checking for cached settings...
2021-05-20 19:01:52.921 7516-7516/com.wetech.aus.tennis.app D/FirebaseCrashlytics: No cached settings data found.
2021-05-20 19:01:52.930 7516-7516/com.wetech.aus.tennis.app D/FirebaseCrashlytics: Successfully configured exception handler.
2021-05-20 19:01:52.932 7516-7563/com.wetech.aus.tennis.app D/FirebaseCrashlytics: Crashlytics automatic data collection ENABLED by global Firebase setting.
2021-05-20 19:01:52.937 7516-7563/com.wetech.aus.tennis.app D/FirebaseCrashlytics: Opening a new session with ID 60A641A003A200011D5C238052D4A223
2021-05-20 19:01:52.948 7516-7563/com.wetech.aus.tennis.app D/FirebaseCrashlytics: Registered Firebase Analytics event receiver for breadcrumbs
2021-05-20 19:01:52.950 7516-7563/com.wetech.aus.tennis.app D/FirebaseCrashlytics: Crashlytics automatic data collection ENABLED by global Firebase setting.
2021-05-20 19:01:52.950 7516-7563/com.wetech.aus.tennis.app D/FirebaseCrashlytics: Automatic data collection is enabled. Allowing upload.
2021-05-20 19:01:53.645 7516-7611/com.wetech.aus.tennis.app D/FirebaseCrashlytics: Handling uncaught exception "java.lang.RuntimeException: Test Crash" from thread DefaultDispatcher-worker-1
2021-05-20 19:01:53.674 7516-7568/com.wetech.aus.tennis.app D/FirebaseCrashlytics: Requesting settings from https://firebase-settings.crashlytics.com/spi/v2/platforms/android/gmp/1:8664796276:android:ae76c8a1d2957b9fad1521/settings
2021-05-20 19:01:53.716 7516-7563/com.wetech.aus.tennis.app D/FirebaseCrashlytics: Opening a new session with ID 60A641A102CC00021D5C238052D4A223
2021-05-20 19:01:53.719 7516-7568/com.wetech.aus.tennis.app E/FirebaseCrashlytics: Settings request failed.
    javax.net.ssl.SSLHandshakeException: Connection closed by peer
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:387)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:226)
        at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:196)
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
        at com.google.firebase.crashlytics.internal.network.HttpGetRequest.execute(HttpGetRequest.java:76)
        at com.google.firebase.crashlytics.internal.settings.network.DefaultSettingsSpiCall.invoke(DefaultSettingsSpiCall.java:113)
        at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:199)
        at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:192)
        at com.google.android.gms.tasks.zzo.run(com.google.android.gms:play-services-tasks@@17.2.0:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:64)
        at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:27)
        at java.lang.Thread.run(Thread.java:919)
2021-05-20 19:01:53.719 7516-7563/com.wetech.aus.tennis.app D/FirebaseCrashlytics: Crashlytics automatic data collection ENABLED by global Firebase setting.

**Comment by aguatno** [comment]
Hi @pokerfaceCmy thanks for reporting. This seems to be an issue with certificate, Adblocker or an antivirus. Could you try the following steps that might help in fixing this issue:


- Try to temporarily disable any network blocking applications like Anti-virus or adblockers then try again
- Connect to another network to check if it's network related
- I've also found this [StackOverflow](https://stackoverflow.com/questions/63240488/firebasecrashlytics-trust-anchor-for-certification-path-not-found) post which you can try
- Use our [quickstart](https://github.com/firebase/quickstart-android/tree/master/crash) with your configurations and try to replicate the issue
 

However, if the provided troubleshooting steps didn't work for you, please provide the following information so I can see what's possibly causing the issue:

- Sample code that exhibits the issue so I can properly replicate your issue
- Any information you think that might be helpful
