### ISSUE TITLE
Serialization and de-serialization of certain objects does not work as expected

### ISSUE THREAD

**Issue by MarceloMaia2** [firebase/firebase-android-sdk#2681]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.1.3
  * Firebase Component: inappmessaging
  * Component version: 20.0.0

#### Steps to reproduce:

**The problem**
`
java.lang.ClassNotFoundException: com.google.android.gms.org.conscrypt.OpenSSLRSAPrivateCrtKey
at java.lang.Class.classForName(Native Method)
at java.lang.Class.forName(Class.java:453)
at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:628)
at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1615)
at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1520)
at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1776)
at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2002)
at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1926)
at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1803)
at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
`

Without SDK of Firebase InApp Messaging (FIAM), de-serialization and serialization works as expected.  Adding the firebase-inappmessaging-display dependency to the project, causes this completely separate part to throw an exception.

#### Relevant Code:

To generate RSA:
```
public static KeyPair generateRSAKeyPair() {
        KeyPairGenerator keyGen = null;
        KeyPair keyPair = null;
        try {
            keyGen = KeyPairGenerator.getInstance("RSA");
            keyGen.initialize(1024);
            keyPair = keyGen.genKeyPair();
        } catch (NoSuchAlgorithmException | NoSuchProviderException e) {
            e.printStackTrace();
        }
        return keyPair;
    }
```

To serialize:
```
public static byte[] serializeClientKeyPair(KeyPair clientKeyPair) {
        ByteArrayOutputStream b = new ByteArrayOutputStream();
        ObjectOutputStream o;
        try {
            o = new ObjectOutputStream(b);
            o.writeObject(clientKeyPair);
        } catch (IOException e) {
            e.printStackTrace();
        }
        byte[] res = b.toByteArray();
        return res;
    }
```

And to de-serialize:
```
public static KeyPair deserializeKeyPair(byte[] serializedKeyPair) {
        ByteArrayInputStream bi = new ByteArrayInputStream(serializedKeyPair);
        ObjectInputStream oi;
        Object obj = null;
        try {
            oi = new ObjectInputStream(bi);
            obj = oi.readObject();
        } catch (StreamCorruptedException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
        return ((KeyPair) obj);
    }
```
When including FIAM SDK to the project, with an Android >=9,  exception is thrown at ```obj = oi.readObject();``` when doing the steps:
```
                KeyPair keyPair = generateRSAKeyPair();
                byte[] serialized = serializeClientKeyPair(keyPair);
                KeyPair deserializeKeyPair = deserializeKeyPair(serialized);```

**Comment by eldhosembabu** [comment]
Could you please provide a sample project with detailed steps to reproduce this issue?

**Comment by MarceloMaia2** [comment]
https://github.com/MarceloMaia2/FIAM

> Could you please provide a sample project with detailed steps to reproduce this issue?

Hello, you can use this sample project https://github.com/MarceloMaia2/FIAM

**Comment by MarceloMaia2** [comment]
Hello @eldhosembabu , there is any kind of update? 
Best regards,

**Comment by eldhosembabu** [comment]
hi @MarceloMaia2 , 

thanks for providing the sample app and it helps!

I was able to reproduce the issue and we are looking into it. Will keep you posted.

Let me know if you are experiencing this issue related with any other firebase SDKs other than FIAM SDK

**Comment by victorlopesjg** [comment]
Hi @eldhosembabu  ,

Is there any way to solve this problem?

**Comment by eldhosembabu** [comment]
I think it has to do with the fact that fiam uses(as it should) https://github.com/firebase/firebase-android-sdk/blob/master/firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/ProviderInstaller.java#L34
this ensures that old devices have secure tls connections.

So our suggestion is to use some modern serialization mechanism like json, protobuf, etc

**Comment by victorlopesjg** [comment]
The problem was solved. It was necessary to use `KeyPairGenerator`

**Comment by eldhosembabu** [comment]
Hi @victorlopesjg ,

Glad to hear the problem was resolved. Would be great if you can mention how the resolution here so that it could benefit others with same issue.
