### ISSUE TITLE
IllegalArgumentException in FirebaseInstallationServiceClient.generateAuthToken

### ISSUE THREAD

**Issue by tejus** [firebase/firebase-android-sdk#2711]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.2
  * Firebase Component: Installations
  * Component version: 16.3.5

#### Steps to reproduce:

We have received Crashlytics reports of 8700+ crashes so far for two of our users (out of 1M+ users), from May 21st till date:

```
Fatal Exception: java.lang.IllegalArgumentException: Unexpected char 0x00 at 40 in header value: FIS_v2 <redacted_refresh_token>
       at com.android.okhttp.Headers$Builder.checkNameAndValue(Headers.java:314)
       at com.android.okhttp.Headers$Builder.add(Headers.java:245)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.addRequestProperty(HttpURLConnectionImpl.java:596)
       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.addRequestProperty(DelegatingHttpsURLConnection.java:186)
       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.addRequestProperty(HttpsURLConnectionImpl.java:26)
       at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.generateAuthToken(FirebaseInstallationServiceClient.java:373)
       at com.google.firebase.installations.FirebaseInstallations.fetchAuthTokenFromServer(FirebaseInstallations.java:522)
       at com.google.firebase.installations.FirebaseInstallations.doNetworkCallIfNecessary(FirebaseInstallations.java:362)
       at com.google.firebase.installations.FirebaseInstallations.lambda$doRegistrationOrRefresh$2(FirebaseInstallations.java:350)
       at com.google.firebase.installations.FirebaseInstallations$$Lambda$4.run(:4)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)
```

#### Relevant Code:

Relevant code is internal to this library.

But this might be relevant to a fix:
https://stackoverflow.com/questions/43026163/unexpected-char-0x0a-in-header-value-when-using-okhttp-client-in-android

**Comment by aguatno** [comment]
Hi @tejus I can't find any similar reports, but I would like to troubleshoot them to confirm if it's caused by any of the Firebase SDKs. To do that, could you provide the following details:

- Runnable app that I can run locally
- Steps to reproduce them

**Comment by tejus** [comment]
@aguatno I can look into this for you, but I'll need to figure out how to run the code from this repo in a sample app, and specifially how to run the method at the following line with a refreshToken of my choosing from the sample app:

https://github.com/firebase/firebase-android-sdk/blob/c81640411f301f5e3fef0f246f0b5be9fa7a10c2/firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java#L391

If that method is possible to call from the app context, I'll try and give you such a sample app as soon as I can. It might take more time than your bot gives us before auto closing issues though.
