### ISSUE TITLE
FirebaseInstanceId.getInstanceId().deleteInstanceId() is failing with SERVICE_NOT_AVAILABLE on Android 4.4

### ISSUE THREAD

**Issue by longkeng** [firebase/firebase-android-sdk#273]
###  Describe your environment

  * Android Studio version: 3.1.3
  * Firebase Component:Firebase Core & Cloud Messaging
  * Component version: 
   ```
    implementation 'com.google.android.gms:play-services-gcm:11.6.0'
    implementation 'com.google.firebase:firebase-messaging:11.6.0'
    implementation 'com.google.firebase:firebase-core:11.6.0'
    implementation 'com.google.gms:google-services:3.0.0'
```

#### Steps to reproduce:

On Android version 4.4 (KitKat) started getting  SERVICE_NOT_AVAILABLE errors when calling 
FirebaseInstanceId.getInstanceId().deleteInstanceId(). The exact exception is:  
```
java.io.IOException: SERVICE_NOT_AVAILABLE
        at com.google.firebase.iid.zzi.zzb(Unknown Source)
        at com.google.firebase.iid.zzi.zza(Unknown Source)
        at com.google.firebase.iid.FirebaseInstanceId.deleteInstanceId(Unknown Source)
        at java.lang.Thread.run(Thread.java:841)
03-12 19:03:12.725 17135-17149/? E/FirebaseInstanceId: Token retrieval failed: SERVICE_NOT_AVAILABLE
```
This bug haven't occurred on Android 5.x above. Does Firebase work on Android 4.4 ?

#### Relevant Code:

```
 (new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    FirebaseInstanceId instanceId = FirebaseInstanceId.getInstance();
                    // Bug is occurring at here.
                    instanceId.deleteInstanceId();
                    { 
                        instanceId.getId();
                        instanceId.getToken();
                    }
                    INSTANCE.preferences.setFirstBoot();
                } catch (IOException e) {
                    ErrorHandler.send(e);
                }
            }
        })).start();
```
And implementation library in gradle file.
```
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    testImplementation 'junit:junit:4.12'
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:support-v4:28.0.0'
    implementation 'com.android.support:recyclerview-v7:28.0.0'
    implementation 'com.android.support:design:28.0.0'
    implementation 'com.google.android.gms:play-services-gcm:11.6.0'
    implementation 'com.google.firebase:firebase-messaging:11.6.0'
    implementation 'com.google.firebase:firebase-core:11.6.0'
    implementation 'com.google.gms:google-services:3.0.0'
```

**Comment by samtstern** [comment]
@longkeng I am not sure what the issue is here but I want to mention a few things:

You should not have both of these dependencies in the same app:
```
    implementation 'com.google.android.gms:play-services-gcm:11.6.0' // remove this one
    implementation 'com.google.firebase:firebase-messaging:11.6.0'      // upgrade this one to a later version
```

This dependency is a plugin, it should't be included here:
```
    implementation 'com.google.gms:google-services:3.0.0'
```

Instead you want to do this:

```
dependencies {
   // ..
}

apply plugin: 'com.google.gms:google-services'
```

The dependency should be declared in the `classpath `dependencies of your root (not app-level) `build.gradle` file.

**Comment by longkeng** [comment]
@samtstern Thanks for your helping. 
After changed implementation code in gradle file based on the above, it's work well.
