### ISSUE TITLE
Fatal Exception: Uncaught exception in Firebase Database runloop (20.0.0)

### ISSUE THREAD

**Issue by SeanBlahovici** [firebase/firebase-android-sdk#2731]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: _____4.2.1
  * Firebase Component: _____ Firebase Database
  * Component version: _____ Firebase BOM 28.0.1 AND BOM 28.1.0

### [REQUIRED] Step 3: Describe the problem

We are getting a crash in production, not quite sure why it is happening. We first got it in BoM 28.0.1 and now it is still occuring in 28.1.0. We are thus forced to downgrade to a previous BoM version.

`Caused by java.lang.AssertionError: hardAssert failed: Expected connection state disconnected, but was GettingToken
       at com.google.firebase.database.connection.ConnectionUtils.hardAssert(ConnectionUtils.java:67)
       at com.google.firebase.database.connection.PersistentConnectionImpl.lambda$tryScheduleReconnect$0(PersistentConnectionImpl.java:766)
       at com.google.firebase.database.connection.PersistentConnectionImpl.lambda$tryScheduleReconnect$0$PersistentConnectionImpl(PersistentConnectionImpl.java:38)
       at com.google.firebase.database.connection.-$$Lambda$PersistentConnectionImpl$N2fhKkJD4F2daDVJHVfjsGPcofI.onSuccess(-.java:38)
       at com.google.android.gms.tasks.zzm.run(zzm.java:5)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)`

**Comment by aguatno** [comment]
Hi @SeanBlahovici thanks for reporting this. These kinds of issue are nearly always caused by a dependency conflict in your module resolution. You may try our quickstart to discard a problem with the service, the quickstart its a good tool to compare your code/environment to see if something is missing. You may also try to replicate the error you are getting.

If the issue persists, please, share with me a sample runnable app that can reproduce the issue. This will bring us a better understanding of what is happening. Thanks

**Comment by gipsey** [comment]
Same issue happened also on my side, but of course, by using an unusual approach:
```kotlin
    private val databaseReference: DatabaseReference
        get() =
            FirebaseDatabase.getInstance()
                .apply {
                    // https://github.com/firebase/firebase-android-sdk/issues/1258#issuecomment-634151944
                    goOffline()
                    goOnline()
                }
                .reference
```

Most probably the crash happened, because multiple coroutines accessed `databaseReference` in parallel. Or, while an execution already was active, goOffline/goOnline was invoked.

To avoid the crash, synchronization helped (using `@Synchronized` and avoiding goOffline/goOnline while an execution was active).
