### ISSUE TITLE
Apps lagg and system ui isn't responding on firebase messaging 

### ISSUE THREAD

**Issue by hafiz013** [firebase/firebase-android-sdk#2732]
`implementation 'com.google.firebase:firebase-core:19.0.0'
    implementation 'com.google.firebase:firebase-analytics:19.0.0'
    implementation 'com.google.firebase:firebase-messaging:22.0.0'
    implementation 'com.google.firebase:firebase-crashlytics:18.0.1'`

in class messaging : 

```kotlin
    override fun onMessageReceived(remoteMessage: RemoteMessage) {
        // [START_EXCLUDE]
        // There are two types of messages data messages and notification messages. Data messages are handled
        // here in onMessageReceived whether the app is in the foreground or background. Data messages are the type
        // traditionally used with GCM. Notification messages are only received here in onMessageReceived when the app
        // is in the foreground. When the app is in the background an automatically generated notification is displayed.
        // When the user taps on the notification they are returned to the app. Messages containing both notification
        // and data payloads are treated as notification messages. The Firebase console always sends notification
        // messages. For more see: https://firebase.google.com/docs/cloud-messaging/concept-options
        // [END_EXCLUDE]

        // TODO(developer): Handle FCM messages here.
        // Not getting messages here? See why this may be: https://goo.gl/39bRNJ
        //Log.e(TAG, "From: ${remoteMessage.from}")

        if(remoteMessage.data.isNotEmpty()){
            //Log.e(TAG, "Message data payload: ${remoteMessage.data}")
            val thread: Thread = object : Thread() {
                override fun run() {
                    Looper.prepare()

                    val handler = Handler(Looper.myLooper()!!)

                    handler.post {
                       // Toast.makeText(applicationContext, "Output:${remoteMessage.data}", Toast.LENGTH_SHORT).show()
                        sessionManager = SessionManager(applicationContext)

                        if (sessionManager.getAccessToken().isNotEmpty()) {
                            sendNotification(remoteMessage)
                        }
                    }
                    Looper.loop()
                }
            }
            thread.start()
        }

        // Check if message contains a notification payload.
        /*remoteMessage.notification?.let {
            Log.e(TAG, "Message Notification Body: ${it.body}")
        }*/
     }

    private fun sendNotification(remoteMessage: RemoteMessage) {
        //Log.e("Output:", remoteMessage.data.toString())
        if (remoteMessage.data.containsKey("id")
            && remoteMessage.data.containsKey("title") && remoteMessage.data.containsKey("msg") && remoteMessage.data.containsKey("img")){

            val intent = Intent(this, MainActivity::class.java).apply {
                flags = Intent.FLAG_ACTIVITY_CLEAR_TOP
                remoteMessage.data["id"]?.let {
                    putExtra("idPost", it.toInt())
                }
            }

            val pendingIntent = PendingIntent.getActivity(this, 0 /* Request code */, intent,
                PendingIntent.FLAG_ONE_SHOT)

            val channelId = getString(R.string.default_notification_channel_id)
            val defaultSoundUri = RingtoneManager.getDefaultUri(RingtoneManager.TYPE_NOTIFICATION)

            /*var futureTarget:FutureTarget<Bitmap> = Glide.with(applicationContext)
                .asBitmap()
                .load(remoteMessage.data["img"])
                .submit(100, 100)

            var bitmap:Bitmap = futureTarget.get();
            var circleBitmap:Bitmap = getCircleBitmap(bitmap)

            // Do something with the Bitmap and then when you're done with it:
            Glide.with(applicationContext).clear(futureTarget)*/

            val notificationBuilder = NotificationCompat.Builder(this, channelId)
                .setSmallIcon(R.mipmap.ic_launcher_round)
                .setContentTitle(remoteMessage.data["title"])
                //.setLargeIcon(circleBitmap)
                .setContentText(remoteMessage.data["msg"])
                .setAutoCancel(true)
                .setSound(defaultSoundUri)
                .setContentIntent(pendingIntent)

            val notificationManager = getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager

            // Since android Oreo notification channel is needed.
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                val channel = NotificationChannel(channelId,
                    "Muslimah Pro Channel",
                    NotificationManager.IMPORTANCE_DEFAULT)
                notificationManager.createNotificationChannel(channel)
            }
            var idMsg:Int = 0

            remoteMessage.data["id"]?.let {
                idMsg = it.toInt()
            }
            notificationManager.notify(idMsg, notificationBuilder.build())
        }
    }
```

Why the latest library got bugs and lagging as compared previous version?

**Comment by hafiz013** [comment]
trace log:

`Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[zip file "/system/framework/hwkeystore.jar", zip file "/system/framework/hccm.jar", zip file "/system/framework/hwpay_hccm_lib.jar", zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.huawei.hwid-EoExBj4OrqoLc-5LnYchIw==/base.apk"],nativeLibraryDirectories=[/data/app/com.huawei.hwid-EoExBj4OrqoLc-5LnYchIw==/lib/arm64, /data/app/com.huawei.hwid-EoExBj4OrqoLc-5LnYchIw==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.LoadedApk.createAppFactory(LoadedApk.java:257)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:805)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:884)
        at android.app.LoadedApk.getResources(LoadedApk.java:1135)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2623)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6595)
        at android.app.ActivityThread.access$2000(ActivityThread.java:273)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2020)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)`

**Comment by hafiz013** [comment]
another log 

`PackageUtils: isInstalledPackage 
    android.content.pm.PackageManager$NameNotFoundException: com.miui.cleaner
        at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:194)
        at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:161)
        at c.c.f.o.x.k(Unknown Source:5)
        at com.miui.cleanmaster.i.a(Unknown Source:8)
        at com.miui.securitycenter.utils.j.a(Unknown Source:11)
        at com.miui.securitycenter.utils.j.a(Unknown Source:40)
        at com.miui.securitycenter.Application$b.onCreate(Unknown Source:304)
        at miui.external.Application.onCreate(Unknown Source:9)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6609)
        at android.app.ActivityThread.access$1400(ActivityThread.java:229)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1901)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:226)
        at android.app.ActivityThread.main(ActivityThread.java:7592)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)`

**Comment by hafiz013** [comment]
another log

`Exception occurred while getting SettingsStore instance.
    java.util.concurrent.ExecutionException: com.google.android.gms.auth.UserRecoverableAuthException: BadAuthentication
        at java.util.concurrent.FutureTask.report(FutureTask.java:123)
        at java.util.concurrent.FutureTask.get(FutureTask.java:207)
        at bcqa.c(:com.google.android.gms@211816037@21.18.16 (120400-374723149):3)
        at bcqa.a(:com.google.android.gms@211816037@21.18.16 (120400-374723149):1)
        at bclk.a(:com.google.android.gms@211816037@21.18.16 (120400-374723149):5)
        at bclk.gr(:com.google.android.gms@211816037@21.18.16 (120400-374723149):12)
        at adpb.run(:com.google.android.gms@211816037@21.18.16 (120400-374723149):17)
        at bvls.run(:com.google.android.gms@211816037@21.18.16 (120400-374723149):2)
        at vpc.c(:com.google.android.gms@211816037@21.18.16 (120400-374723149):6)
        at vpc.run(:com.google.android.gms@211816037@21.18.16 (120400-374723149):7)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at vuz.run(:com.google.android.gms@211816037@21.18.16 (120400-374723149):0)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: com.google.android.gms.auth.UserRecoverableAuthException: BadAuthentication
        at hiw.t(:com.google.android.gms@211816037@21.18.16 (120400-374723149):3)
        at hiq.a(Unknown Source:6)
        at hiw.A(:com.google.android.gms@211816037@21.18.16 (120400-374723149):4)
        at hiw.r(:com.google.android.gms@211816037@21.18.16 (120400-374723149):15)
        at hiw.q(:com.google.android.gms@211816037@21.18.16 (120400-374723149):0)
        at hiw.o(:com.google.android.gms@211816037@21.18.16 (120400-374723149):0)
        at hiw.y(:com.google.android.gms@211816037@21.18.16 (120400-374723149):0)
        at bcqn.call(Unknown Source:3)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at vpc.c(:com.google.android.gms@211816037@21.18.16 (120400-374723149):6) 
        at vpc.run(:com.google.android.gms@211816037@21.18.16 (120400-374723149):7) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at vuz.run(:com.google.android.gms@211816037@21.18.16 (120400-374723149):0) 
        at java.lang.Thread.run(Thread.java:919) `

**Comment by hafiz013** [comment]
another log :
`AuthPII: Message is Long live credential not available.
    uqc: Long live credential not available.
        at hnu.a(:com.google.android.gms@211816037@21.18.16 (120400-374723149):13)
        at hnx.e(:com.google.android.gms@211816037@21.18.16 (120400-374723149):1)
        at hmj.l(:com.google.android.gms@211816037@21.18.16 (120400-374723149):44)
        at dwq.g(:com.google.android.gms@211816037@21.18.16 (120400-374723149):32)
        at dwq.k(:com.google.android.gms@211816037@21.18.16 (120400-374723149):4)
        at dwq.c(:com.google.android.gms@211816037@21.18.16 (120400-374723149):62)
        at hiq.a(Unknown Source:4)
        at hiw.A(:com.google.android.gms@211816037@21.18.16 (120400-374723149):4)
        at hiw.r(:com.google.android.gms@211816037@21.18.16 (120400-374723149):15)
        at hiw.q(:com.google.android.gms@211816037@21.18.16 (120400-374723149):0)
        at hiw.o(:com.google.android.gms@211816037@21.18.16 (120400-374723149):0)
        at hiw.y(:com.google.android.gms@211816037@21.18.16 (120400-374723149):0)
        at bcqn.call(Unknown Source:3)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at vpc.c(:com.google.android.gms@211816037@21.18.16 (120400-374723149):6)
        at vpc.run(:com.google.android.gms@211816037@21.18.16 (120400-374723149):7)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at vuz.run(:com.google.android.gms@211816037@21.18.16 (120400-374723149):0)
        at java.lang.Thread.run(Thread.java:919)`

**Comment by hafiz013** [comment]
another log

`AuthPII: [GoogleAccountDataServiceImpl] getToken() -> BAD_AUTHENTICATION. Account: Account {name=@@ContextManagerNullAccount@@, type=com.google}, App: com.google.android.gms, Service: ^^_account_id_^^
    uqc: Long live credential not available.
        at hnu.a(:com.google.android.gms@211816037@21.18.16 (120400-374723149):13)
        at hnx.e(:com.google.android.gms@211816037@21.18.16 (120400-374723149):1)
        at hmj.l(:com.google.android.gms@211816037@21.18.16 (120400-374723149):44)
        at dwq.g(:com.google.android.gms@211816037@21.18.16 (120400-374723149):32)
        at dwq.k(:com.google.android.gms@211816037@21.18.16 (120400-374723149):4)
        at dwq.c(:com.google.android.gms@211816037@21.18.16 (120400-374723149):62)
        at hiq.a(Unknown Source:4)
        at hiw.A(:com.google.android.gms@211816037@21.18.16 (120400-374723149):4)
        at hiw.r(:com.google.android.gms@211816037@21.18.16 (120400-374723149):15)
        at hiw.q(:com.google.android.gms@211816037@21.18.16 (120400-374723149):0)
        at hiw.o(:com.google.android.gms@211816037@21.18.16 (120400-374723149):0)
        at hiw.y(:com.google.android.gms@211816037@21.18.16 (120400-374723149):0)
        at bcqn.call(Unknown Source:3)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at vpc.c(:com.google.android.gms@211816037@21.18.16 (120400-374723149):6)
        at vpc.run(:com.google.android.gms@211816037@21.18.16 (120400-374723149):7)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at vuz.run(:com.google.android.gms@211816037@21.18.16 (120400-374723149):0)
        at java.lang.Thread.run(Thread.java:919)`

**Comment by hafiz013** [comment]
another log:

`ctxmgr: [UpdateGeofencesOperation] add geofences [Geofence[CIRCLE id:9da66dee-5e7d-48ce-b445-8ec616f9a1a8 transitions:3 51.913949, 0.927293 1m, resp=300s, dwell=-1ms, @-1]] [CONTEXT service_id=47 ]
    uhf: 1000: 
        at umx.b(:com.google.android.gms@211816037@21.18.16 (120400-374723149):2)
        at aiwg.b(:com.google.android.gms@211816037@21.18.16 (120400-374723149):2)
        at aiyq.d(:com.google.android.gms@211816037@21.18.16 (120400-374723149):0)
        at aiyq.a(:com.google.android.gms@211816037@21.18.16 (120400-374723149):0)
        at bpkm.a(:com.google.android.gms@211816037@21.18.16 (120400-374723149):4)
        at bpkw.b(:com.google.android.gms@211816037@21.18.16 (120400-374723149):0)
        at bpli.j(:com.google.android.gms@211816037@21.18.16 (120400-374723149):4)
        at bpml.handleMessage(:com.google.android.gms@211816037@21.18.16 (120400-374723149):11)
        at bpml.handleMessage(:com.google.android.gms@211816037@21.18.16 (120400-374723149):3)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at aiol.ji(:com.google.android.gms@211816037@21.18.16 (120400-374723149):0)
        at aiol.dispatchMessage(:com.google.android.gms@211816037@21.18.16 (120400-374723149):10)
        at android.os.Looper.loop(Looper.java:226)
        at android.os.HandlerThread.run(HandlerThread.java:67)`

**Comment by aguatno** [comment]
Hi @hafiz013 thanks for reporting this. I think this issue is going to be a little too broad to tackle. We'll need to do some work here to isolate the cause. If I could reproduce the problem here, I can have a better look into it, so let’s start there. To do that, I will need you to provide some more details in order to troubleshoot your issue. 

- MCV example that I can run locally - please remove any third party libraries to isolate the issue
- Percentage of your affected users running into this crash

Additionally, please try to use our Messaging [quickstart](https://github.com/firebase/quickstart-android) app with the latest SDK version to see if you're able to reproduce the issue. If not, then it's likely just an implementation error, and I would recommend that you cross-check your code implementation with the quickstart app to verify if anything is missing in your configuration.

**Comment by hafiz013** [comment]
@aguatno hi from what i see u use 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.10' but mine instead use 1.4.32. The reason is because kotlin 1.5.10 has bugs on my apps cannot parameterized class type. However, i found out this error logcat appear Didn't find class "androidx.core.app.CoreComponentFactory" and some error log run m: Unknown bits set in runtime_flags:0x48000.

MCV u request quite difficult to do coz my classess a lot and about percentage is 100% come from firebase messaging coming make my apps lagging. If u want apk let me know for u test.

below here my latest gradle

plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'com.google.gms.google-services'
    id 'com.google.firebase.crashlytics'
   // id 'com.onesignal.androidsdk.onesignal-gradle-plugin'
}

android {
    compileSdkVersion 30
    buildToolsVersion "30.0.3"

    defaultConfig {
        applicationId "secret"
        minSdkVersion 21
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"
        multiDexEnabled = true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.3.1'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.3.1'
    //implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    //implementation files('libs/YouTubeAndroidPlayerApi.jar')
    //implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    def room_version = "2.3.0"  //room data

    //implementation 'androidx.activity:activity-ktx:1.3.0-alpha08'
    //implementation "androidx.fragment:fragment-ktx:1.4.0-alpha01"
    //implementation "org.jetbrains.kotlin:kotlin-stdlib:1.4.32"
    implementation 'androidx.annotation:annotation:1.2.0'
    implementation "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
    implementation 'androidx.core:core-ktx:1.5.0'
    implementation 'androidx.appcompat:appcompat:1.3.0'
    implementation 'com.google.android.material:material:1.3.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    implementation("androidx.multidex:multidex:2.0.1")
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
    implementation 'com.google.code.gson:gson:2.8.7'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:5.0.0-alpha.2'
    implementation "androidx.room:room-runtime:$room_version"
    annotationProcessor "androidx.room:room-compiler:$room_version"
    implementation 'me.relex:circleindicator:2.1.6'
    implementation 'com.facebook.android:facebook-android-sdk:11.0.0'
    implementation 'com.facebook.android:facebook-login:11.0.0'
    implementation 'com.google.android.gms:play-services-auth:19.0.0'
    implementation platform('com.google.firebase:firebase-bom:28.0.1')
    implementation 'com.google.firebase:firebase-messaging-ktx'
    implementation 'com.pierfrancescosoffritti.androidyoutubeplayer:core:10.0.5'
    //implementation 'com.google.firebase:firebase-core:19.0.0'
    //implementation 'com.google.firebase:firebase-analytics:19.0.0'
    //implementation 'com.google.firebase:firebase-messaging:22.0.0'
    //implementation 'com.google.firebase:firebase-crashlytics:18.0.1'
    implementation 'com.google.firebase:firebase-crashlytics-ktx'
    implementation 'com.google.firebase:firebase-analytics-ktx'
    implementation 'com.google.firebase:firebase-installations-ktx:17.0.0'
    implementation 'com.github.bumptech.glide:glide:4.12.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.12.0'
    implementation 'com.tuyenmonkey:mkloader:1.4.0'
    //implementation('io.coil-kt:coil:1.2.0')
    implementation project(path: ':WheelPicker')
    implementation project(path: ':slimadapter')
    implementation 'com.github.andrefrsousa:SuperBottomSheet:2.0.0'
    implementation 'com.nabinbhandari.android:permissions:3.8'
    //implementation 'com.onesignal:OneSignal:4.4.0'
    implementation 'com.github.chrisbanes:PhotoView:2.3.0'
    implementation 'com.facebook.fresco:fresco:2.5.0'
//implementation 'androidx.exifinterface:exifinterface:28.0.0'
    //implementation 'com.github.chrisbanes:PhotoView:2.3.0'
    //implementation("commons-io:commons-io:2.6") //extension file
    //implementation 'org.greenrobot:eventbus:3.2.0'
    //implementation project(path: ':android-slidr')
    //implementation 'com.github.kizitonwose:CalendarView:1.1.5'
}

// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {  ///1.4.31  '1.5.10'
    ext.kotlin_version = '1.4.32'
    repositories {
        mavenLocal()
        google()
        //mavenCentral()
        //gradlePluginPortal()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.2.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.8'
        classpath 'com.novoda:bintray-release:0.8.0'
        classpath 'com.github.dcendents:android-maven-gradle-plugin:1.5'
        classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.7.3'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.7.0'
        //classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:0.12.10'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        //mavenCentral()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by ciarand** [comment]
Hi @hafiz013, I've quoted some of the stacks along with some notes below:

```
Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[zip file "/system/framework/hwkeystore.jar", zip file "/system/framework/hccm.jar", zip file "/system/framework/hwpay_hccm_lib.jar", zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.huawei.hwid-EoExBj4OrqoLc-5LnYchIw==/base.apk"],nativeLibraryDirectories=[/data/app/com.huawei.hwid-EoExBj4OrqoLc-5LnYchIw==/lib/arm64, /data/app/com.huawei.hwid-EoExBj4OrqoLc-5LnYchIw==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
  // ...
```

This seems to indicate the app is missing one of the dependencies (maybe related to the jetification process? I see the androidx deps listed in your gradle). Can you check that the proguard rules you're using aren't interfering with this one?

```
PackageUtils: isInstalledPackage 
    android.content.pm.PackageManager$NameNotFoundException: com.miui.cleaner
        at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:194)
        at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:161)
        at c.c.f.o.x.k(Unknown Source:5)
        at com.miui.cleanmaster.i.a(Unknown Source:8)
        at com.miui.securitycenter.utils.j.a(Unknown Source:11)
        at com.miui.securitycenter.utils.j.a(Unknown Source:40)
        at com.miui.securitycenter.Application$b.onCreate(Unknown Source:304)
        at miui.external.Application.onCreate(Unknown Source:9)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6609)
        at android.app.ActivityThread.access$1400(ActivityThread.java:229)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1901)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:226)
        at android.app.ActivityThread.main(ActivityThread.java:7592)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

Can you retrace this? It's hard to know what's going on as it is.

```
Exception occurred while getting SettingsStore instance.
    java.util.concurrent.ExecutionException: com.google.android.gms.auth.UserRecoverableAuthException: BadAuthentication
        at java.util.concurrent.FutureTask.report(FutureTask.java:123)
        at java.util.concurrent.FutureTask.get(FutureTask.java:207)
        at bcqa.c(:com.google.android.gms@211816037@21.18.16 (120400-374723149):3)
        at bcqa.a(:com.google.android.gms@211816037@21.18.16 (120400-374723149):1)
        at bclk.a(:com.google.android.gms@211816037@21.18.16 (120400-374723149):5)
        at bclk.gr(:com.google.android.gms@211816037@21.18.16 (120400-374723149):12)
        at adpb.run(:com.google.android.gms@211816037@21.18.16 (120400-374723149):17)
        at bvls.run(:com.google.android.gms@211816037@21.18.16 (120400-374723149):2)
        at vpc.c(:com.google.android.gms@211816037@21.18.16 (120400-374723149):6)
        at vpc.run(:com.google.android.gms@211816037@21.18.16 (120400-374723149):7)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at vuz.run(:com.google.android.gms@211816037@21.18.16 (120400-374723149):0)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: com.google.android.gms.auth.UserRecoverableAuthException: BadAuthentication
        at hiw.t(:com.google.android.gms@211816037@21.18.16 (120400-374723149):3)
        at hiq.a(Unknown Source:6)
        at hiw.A(:com.google.android.gms@211816037@21.18.16 (120400-374723149):4)
        at hiw.r(:com.google.android.gms@211816037@21.18.16 (120400-374723149):15)
        at hiw.q(:com.google.android.gms@211816037@21.18.16 (120400-374723149):0)
        at hiw.o(:com.google.android.gms@211816037@21.18.16 (120400-374723149):0)
        at hiw.y(:com.google.android.gms@211816037@21.18.16 (120400-374723149):0)
        at bcqn.call(Unknown Source:3)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at vpc.c(:com.google.android.gms@211816037@21.18.16 (120400-374723149):6) 
        at vpc.run(:com.google.android.gms@211816037@21.18.16 (120400-374723149):7) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at vuz.run(:com.google.android.gms@211816037@21.18.16 (120400-374723149):0) 
        at java.lang.Thread.run(Thread.java:919)
```

I can't speak to exactly why the authentication is bad, but this seems not to be a messaging issue. I'll add the appropriate label. The other stack traces also seem auth related.

There's a lot going on in this thread and I'm not sure I see the link to messaging. Can you post specific repro instructions? Under what circumstances are you seeing lag / jank?

**Comment by hafiz013** [comment]
Ok guys u can close this. The problem i face is because i set small icon on NotificationCompat.Builder  to drawable high pixel (1000px above) + high size (1mb above). So i hope can solve other problem who has facing like me.

**Comment by aguatno** [comment]
Thanks for letting us know @hafiz013.
