### ISSUE TITLE
Fatal Exception: java.lang.AssertionError: No NameTypeIndex match for SHORT_STANDARD 

### ISSUE THREAD

**Issue by NivaKaur29** [firebase/firebase-android-sdk#2740]
Android Studio version: _____4.1.1
Firebase Component: _____ firebase-bom
Component version: _____"26.5.0"

We are using firebase for push notifications. We have got this crash for few users repetitively, though we couldn't simulate, this is reported in crashlytics.

**Logs :**

Fatal Exception: java.lang.AssertionError: No NameTypeIndex match for SHORT_STANDARD
at android.icu.impl.TimeZoneNamesImpl$ZNames.getNameTypeIndex(TimeZoneNamesImpl.java:724)
at android.icu.impl.TimeZoneNamesImpl$ZNames.getName(TimeZoneNamesImpl.java:790)
at android.icu.impl.TimeZoneNamesImpl.getTimeZoneDisplayName(TimeZoneNamesImpl.java:183)
at android.icu.text.TimeZoneNames.getDisplayName(TimeZoneNames.java:261)
at java.util.TimeZone.getDisplayName(TimeZone.java:405)
at java.util.Date.toString(Date.java:1066)
at java.util.Properties.store0(Properties.java:828)
at java.util.Properties.store(Properties.java:817)
at com.google.firebase.iid.zzq.zza(zzq.java:82)
at com.google.firebase.iid.zzq.zzb(zzq.java:8)
at com.google.firebase.iid.zzq.zza(zzq.java:5)
at com.google.firebase.iid.zzat.zzb(zzat.java:48)
at com.google.firebase.iid.FirebaseInstanceId.zzl(FirebaseInstanceId.java:48)
at com.google.firebase.iid.FirebaseInstanceId.zza(FirebaseInstanceId.java:131)
at com.google.firebase.iid.zzg.then(zzg.java:1)
at com.google.android.gms.tasks.zzf.run(zzf.java:2)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)

**Note:** - There is an old issue created for this - https://github.com/firebase/firebase-android-sdk/issues/1581

**Comment by aguatno** [comment]
Hi @NivaKaur29 Thanks for reporting this. I think this issue is going to be a little too broad to tackle with just the error logs. In order to identify what's causing the issue, I'd like you to provide a minimal, reproducible example of your project and the complete steps you've taken before facing this issue. Also try using the latest version of Firebase Boom (28.1.0). Thanks.

**Comment by ciarand** [comment]
Hi @NivaKaur29, the code referencing that property file should have been removed last year (see last comment in https://github.com/firebase/firebase-android-sdk/issues/1581). This shouldn't be happening with the latest version of the SDK - can you try updating and see if it still repros?

**Comment by NivaKaur29** [comment]
Hello @ciarand & @aguatno Thanks for your reply.
We don't have reproducible step now, Since this issue is occurring on these devices **Redmi 5 os(8.1.0)** and **Vivo** ,  which we got from crashlytics.
We are using blueshift(blueshiftVersion = "3.2.0") in our app, so after using of updated version of firebase bom(28.1.0), we are getting class not found exception "**FirebaseInstanceId**".

**Comment by aguatno** [comment]
@NivaKaur29 sorry that it's taking this long. I did some research on the error exception, it looks like this is causing a crash of some devices while attempting to log out sync information due to timezone data issues. 

I will share this with the team, but it will be tough to investigate with a little stack trace. If you could gather any other info related to this crash and MCVE, please keep us posted so that we can update our team while they investigate this. Thanks
