### ISSUE TITLE
Exception: java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by NivaKaur29** [firebase/firebase-android-sdk#2752]
Android Studio version: _____4.1.1
Firebase Component: _____ firebase-bom
Component version: _____"26.5.0"

We are using firebase for push notifications. We have got this crash for few users repetitively, though we couldn't simulate, this is reported in crashlytics. Can you please help us fix this
ONEPLUS A6010 , Android OS 10

**Logs:**
Fatal Exception: java.lang.IllegalArgumentException: byteCount < 0: -156
       at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:47)
       at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:395)
       at com.android.okhttp.internal.Util.skipAll(Util.java:165)
       at com.android.okhttp.internal.Util.discard(Util.java:147)
       at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.close(Http1xStream.java:412)
       at com.android.okhttp.okio.RealBufferedSource.close(RealBufferedSource.java:397)
       at com.android.okhttp.okio.RealBufferedSource$1.close(RealBufferedSource.java:385)
       at com.google.android.gms.internal.firebase_messaging.zzk.zza(zzk.java:4)
       at com.google.firebase.messaging.zzm.close(zzm.java:37)
       at com.google.firebase.messaging.zzd.zza(zzd.java:51)
       at com.google.firebase.messaging.FirebaseMessagingService.zzc(FirebaseMessagingService.java:69)
       at com.google.firebase.messaging.zze.run(zze.java:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.android.gms.common.util.concurrent.zza.run(zza.java:6)
       at java.lang.Thread.run(Thread.java:919)

**Note:** - There is an old issue created for this - https://github.com/firebase/firebase-android-sdk/issues/1478

**Comment by aguatno** [comment]
Hi @NivaKaur29 thanks for reporting. I checked our system and found no similar issue reported. Are you able to reproduce this with the sample[ quickstart app](https://github.com/firebase/quickstart-android) and the most recent version of Firebase? If so, please provide a sample project where the issue is reproducible so we can help with debugging and fixing it.
