### ISSUE TITLE
Uncaught exception in Firebase Database runloop (20.0.1) - hardAssert failed: Expected connection state disconnected, but was GettingToken

### ISSUE THREAD

**Issue by ebhsgit** [firebase/firebase-android-sdk#2914]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 2020.3.1
  * Firebase Component: Issue with Database, (also using the following Firestore, Functions, RemoteConfig, FCM, Crashlytics, Analytics)
  * Component version: BoM 28.3.0

### [REQUIRED] Step 3: Describe the problem

Seeing the following issues in Crashlytics

```
Fatal Exception: java.lang.RuntimeException: Uncaught exception in Firebase Database runloop (20.0.1). If you are not already on the latest version of the Firebase SDKs, try updating your dependencies. Should this problem persist, please file a report at https://github.com/firebase/firebase-android-sdk
       at com.google.firebase.database.android.AndroidPlatform$1$1.run(AndroidPlatform.java:96)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7948)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```

```
Caused by java.lang.AssertionError: hardAssert failed: Expected connection state disconnected, but was GettingToken
       at com.google.firebase.database.connection.ConnectionUtils.hardAssert(ConnectionUtils.java:67)
       at com.google.firebase.database.connection.PersistentConnectionImpl.lambda$tryScheduleReconnect$0(PersistentConnectionImpl.java:767)
       at com.google.firebase.database.connection.PersistentConnectionImpl.lambda$tryScheduleReconnect$0$PersistentConnectionImpl(PersistentConnectionImpl.java)
       at com.google.firebase.database.connection.-$$Lambda$PersistentConnectionImpl$N2fhKkJD4F2daDVJHVfjsGPcofI.onSuccess(-.java:11)
       at com.google.android.gms.tasks.zzm.run(zzm.java:4)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

The issue seems to be occasional. Because not every user is experiencing it, and does not seem to be repeating for the same user.

This issue only started happening in the new version of my app (update went live on 16-8-21).
The new version only has 3 changes related to Firebase Database.

1. Updated component version and started using BoM
2. Using the Firebase Database SDK with periodic `CoroutineWorker`
3. Enabled persistence

#### Relevant Code:

There are many places in the app that uses `Firebase Database`, but they were not changed in this update.

Only a new Worker was added that utilises Firebase Database. 
I believe the Worker is relevant for this issue, because the `getData()` is also occasionally getting `Client is offline` at similar times to this issue. The stack trace for `Client is offline` error is noted below.

Both issues only occur in background. And only this Worker is scheduled to run periodically in the background (every 30 mins).

Below is a simplified version of the `Worker` code

```
class Worker(context: Context, workerParams: WorkerParameters) : CoroutineWorker(context, workerParams) {
   override suspend fun doWork(): Result {
      val data= try {
           getData()
        } catch (e: Exception) {
            val errMsg = "Error message"
            Log.e(TAG, errMsg, e)
            FirebaseCrashlytics.getInstance().recordException(IllegalStateException(errMsg, e));      //  <------ This line also getting "Client is offline" exception
            return Result.retry()
        }
   }

   private suspend fun getData() = withContext(Dispatchers.IO) {
      Rtdb.instance.getReference("path\to\data")
              .get()
              .await()
              .getValue<Map<String, String>>()
   }
}

object Rtdb {
    private val defaultInstance: FirebaseDatabase = Firebase.database

    init {
        defaultInstance.setPersistenceEnabled(true)
    }

    @JvmStatic
    val instance: FirebaseDatabase
        get() = this.defaultInstance
}
```

Stack trace for `Client is offline` error.
The line for the `IllegalStateException` is noted as comment in the above code.

```
Non-fatal Exception: java.lang.IllegalStateException
      ....[My app's stack trace]
      ....

Caused by java.lang.Exception: Client is offline
       at com.google.firebase.database.connection.PersistentConnectionImpl$2.run(PersistentConnectionImpl.java:445)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```

**Comment by ebhsgit** [comment]
The `Client is offline` error has occurred a few times on a dev device.
The dev device **definitely** always has internet connectivity.

**Comment by aguatno** [comment]
@ebhsgit thanks for reporting. I know that this kind of exception is really annoying, but it will probably be difficult to track down without a way to repro. If you can share a simple project demonstrating the issue this will bring us a better understanding of what is happening. Thanks.

**Comment by ebhsgit** [comment]
@aguatno 

Thanks for replying.

I will see if I can build a simple project that can reproduce it.
If the cause is because of the worker, then the probability is less than 1 in 20000 executions.

----

Are there settings I can turn on to help debug where this issue is coming from?

The stack trace does not relate to anything in my codebase
AND
All there was no stack info on other threads in Crashlytics related to my code.

----

Can you provide some info about what this error means?
ie: What type of actions could cause this issue

**Comment by ebhsgit** [comment]
I found that in production, something strange is happening.

Every app client is connecting and disconnecting repeatedly every 2 mins (~120_000 ms), without doing anything in between.

I think this is the cause of connection state issue. Because I only have a Worker that runs every 30 minutes. These connection open/closes in between the workers without any loop (How is this even possible?). And maybe every once in a while Android OS prematurely kill the thread they are running on.

@aguatno 
Any ideas what could be causing this?

Example snippet (of 1 client out of many) from `firebase database:profile` of production

```
{"pendingTime":0,"client":{"remoteAddress":{"address":"[same-client-ip]"},"userAgent":{"browser":"firebase","os":"android","platform":"native","userAgentString":"Firebase/5/20.0.1/28/Android","version":"20_0_1"}},"name":"concurrent-disconnect","timestamp":1631063531765}
{"pendingTime":1,"client":{"remoteAddress":{"address":"[same-client-ip]"},"userAgent":{"browser":"firebase","os":"android","platform":"native","userAgentString":"Firebase/5/20.0.1/28/Android","version":"20_0_1"}},"name":"concurrent-connect","timestamp":1631063532627}
{"pendingTime":1,"client":{"remoteAddress":{"address":"[same-client-ip]"},"userAgent":{"browser":"firebase","os":"android","platform":"native","userAgentString":"Firebase/5/20.0.1/28/Android","version":"20_0_1"}},"name":"concurrent-disconnect","timestamp":1631063652824}
{"pendingTime":0,"client":{"remoteAddress":{"address":"[same-client-ip]"},"userAgent":{"browser":"firebase","os":"android","platform":"native","userAgentString":"Firebase/5/20.0.1/28/Android","version":"20_0_1"}},"name":"concurrent-connect","timestamp":1631063653727}
{"pendingTime":1,"client":{"remoteAddress":{"address":"[same-client-ip]"},"userAgent":{"browser":"firebase","os":"android","platform":"native","userAgentString":"Firebase/5/20.0.1/28/Android","version":"20_0_1"}},"name":"concurrent-disconnect","timestamp":1631063773965}
{"pendingTime":0,"client":{"remoteAddress":{"address":"[same-client-ip]"},"userAgent":{"browser":"firebase","os":"android","platform":"native","userAgentString":"Firebase/5/20.0.1/28/Android","version":"20_0_1"}},"name":"concurrent-connect","timestamp":1631063774833}
{"pendingTime":0,"client":{"remoteAddress":{"address":"[same-client-ip]"},"userAgent":{"browser":"firebase","os":"android","platform":"native","userAgentString":"Firebase/5/20.0.1/28/Android","version":"20_0_1"}},"name":"concurrent-disconnect","timestamp":1631063895016}
{"pendingTime":0,"client":{"remoteAddress":{"address":"[same-client-ip]"},"userAgent":{"browser":"firebase","os":"android","platform":"native","userAgentString":"Firebase/5/20.0.1/28/Android","version":"20_0_1"}},"name":"concurrent-connect","timestamp":1631063895995}
{"pendingTime":0,"client":{"remoteAddress":{"address":"[same-client-ip]"},"userAgent":{"browser":"firebase","os":"android","platform":"native","userAgentString":"Firebase/5/20.0.1/28/Android","version":"20_0_1"}},"name":"concurrent-disconnect","timestamp":1631064016221}
{"pendingTime":0,"client":{"remoteAddress":{"address":"[same-client-ip]"},"userAgent":{"browser":"firebase","os":"android","platform":"native","userAgentString":"Firebase/5/20.0.1/28/Android","version":"20_0_1"}},"name":"concurrent-connect","timestamp":1631064017128}
{"pendingTime":0,"client":{"remoteAddress":{"address":"[same-client-ip]"},"userAgent":{"browser":"firebase","os":"android","platform":"native","userAgentString":"Firebase/5/20.0.1/28/Android","version":"20_0_1"}},"name":"concurrent-disconnect","timestamp":1631064137299}
{"pendingTime":0,"client":{"remoteAddress":{"address":"[same-client-ip]"},"userAgent":{"browser":"firebase","os":"android","platform":"native","userAgentString":"Firebase/5/20.0.1/28/Android","version":"20_0_1"}},"name":"concurrent-connect","timestamp":1631064138536}
{"pendingTime":0,"client":{"remoteAddress":{"address":"[same-client-ip]"},"userAgent":{"browser":"firebase","os":"android","platform":"native","userAgentString":"Firebase/5/20.0.1/28/Android","version":"20_0_1"}},"name":"concurrent-disconnect","timestamp":1631064258699}
{"pendingTime":0,"client":{"remoteAddress":{"address":"[same-client-ip]"},"userAgent":{"browser":"firebase","os":"android","platform":"native","userAgentString":"Firebase/5/20.0.1/28/Android","version":"20_0_1"}},"name":"concurrent-connect","timestamp":1631064259584}
{"pendingTime":0,"client":{"remoteAddress":{"address":"[same-client-ip]"},"userAgent":{"browser":"firebase","os":"android","platform":"native","userAgentString":"Firebase/5/20.0.1/28/Android","version":"20_0_1"}},"name":"concurrent-disconnect","timestamp":1631064379768}
{"pendingTime":0,"client":{"remoteAddress":{"address":"[same-client-ip]"},"userAgent":{"browser":"firebase","os":"android","platform":"native","userAgentString":"Firebase/5/20.0.1/28/Android","version":"20_0_1"}},"name":"concurrent-connect","timestamp":1631064380580}
```

**Comment by aguatno** [comment]
@ebhsgit let me take a look regarding the connection issue. In the meantime if you have any updates on Runloop issue feel free to leave a comment. Thanks
