### ISSUE TITLE
Realtime Database - "cannot rollback" Crash

### ISSUE THREAD

**Issue by kashi1982** [firebase/firebase-android-sdk#2974]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: _____2020.3.1 for Mac
  * Firebase Component: _____ Realtime Database
  * Component version: _____27.1.0

### [REQUIRED] Step 3: Describe the problem
When using Realtime Database on Android, on first initialization of Firebase, we get the crash.
Caused by android.database.sqlite.SQLiteException: cannot rollback - no transaction is active (code 1)
       at android.database.sqlite.SQLiteConnection.nativeExecute(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:562)
       at android.database.sqlite.SQLiteSession.endTransactionUnchecked(SQLiteSession.java:439)
       at android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:401)
       at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:555)
       at com.google.firebase.database.android.SqlPersistenceStorageEngine.endTransaction(SqlPersistenceStorageEngine.java:810)
       at com.google.firebase.database.core.persistence.DefaultPersistenceManager.runInTransaction(DefaultPersistenceManager.java:246)
       at com.google.firebase.database.core.SyncTree.setQueryInactive(SyncTree.java:472)
       at com.google.firebase.database.core.Repo$8$1.onComplete(Repo.java:535)
       at com.google.android.gms.tasks.zzj.run(zzj.java:4)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

#### Steps to reproduce:
WHen our mobile app is using the RealtimeDatabase for the first time, this crash errors on certain devices lik Shark, LG Stylo 4

**Comment by aguatno** [comment]
Hi @kashi1982 The error logs seem caused by Android API. You can also check this entry in [Stackoverflow](
https://stackoverflow.com/a/61907620) about a similar issue. Also, a good option is to check the Firebase Android [quickstart](https://github.com/firebase/quickstart-android/tree/master/storage), there is an example on how to implement the service. This project has been already tested and you can use it to test and compare your own implementation.

Feel free to leave a comment If the issue persists using our native SDK .
