### ISSUE TITLE
Error when launching my application: java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by gabriel-rossi-2021** [firebase/firebase-android-sdk#3060]
<!-- DO NOT DELETE 
validate_template=true
template_path=.github/ISSUE_TEMPLATE/bug.md

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 2020.3.1
  * Firebase Component: Realtime Database
  * Component version: last

### [REQUIRED] Step 3: Describe the problem
What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.ckeckresto, PID: 4327
    java.lang.ExceptionInInitializerError
        at com.example.ckeckresto.RestoRepository.updateData(RestoRepository.kt:23)
        at com.example.ckeckresto.MainActivity.onCreate(MainActivity.kt:16)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: com.google.firebase.database.DatabaseException: Failed to get FirebaseDatabase instance: Specify DatabaseURL within FirebaseApp or from your getInstance() call.
        at com.google.firebase.database.FirebaseDatabase.getInstance(com.google.firebase:firebase-database@@19.2.1:97)
        at com.google.firebase.database.FirebaseDatabase.getInstance(com.google.firebase:firebase-database@@19.2.1:57)
        at com.example.ckeckresto.RestoRepository$Singleton.<clinit>(RestoRepository.kt:15)
        at com.example.ckeckresto.RestoRepository.updateData(RestoRepository.kt:23) 
        at com.example.ckeckresto.MainActivity.onCreate(MainActivity.kt:16) 
        at android.app.Activity.performCreate(Activity.java:7136) 
        at android.app.Activity.performCreate(Activity.java:7127) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
<img width="243" alt="keepStopping" src="https://user-images.githubusercontent.com/81309938/137443737-b2bf5ded-40e2-4eb0-8b3b-d4f54756b814.png">
<img width="601" alt="MainActivity" src="https://user-images.githubusercontent.com/81309938/137443738-a4847be8-91be-4ad2-9343-de25201f5d4d.png">
<img width="637" alt="RestoRepository" src="https://user-images.githubusercontent.com/81309938/137443739-7c9e57b9-730d-44dc-a95a-2eeba7ac2ebe.png">

**Comment by aguatno** [comment]
Hi @gabriel-rossi-2021 . We're happy to help, but It seems that your inquiry doesn't follow the template. With this, I'll be closing this ticket for now.

In order for me to get a better understanding of this issue, you may file another ticket that uses the issue template.

Thanks

**Comment by gabriel-rossi-2021** [comment]
Okay, New ticket #3061
