### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException: Uncaught exception in Firebase Database runloop (20.0.2)

### ISSUE THREAD

**Issue by cpferschy** [firebase/firebase-android-sdk#3074]
### Environment

  * Android Studio version: Arctic Fox 2020.3.1 Patch 3
  * Firebase Component: Database
  * Component version: 20.0.2

```
implementation platform("com.google.firebase:firebase-bom:28.4.2")
implementation "com.google.firebase:firebase-analytics"
implementation "com.google.firebase:firebase-config"
implementation "com.google.firebase:firebase-database"
implementation "com.google.firebase:firebase-auth"
implementation "com.google.firebase:firebase-appindexing"
implementation "com.google.firebase:firebase-dynamic-links"
implementation "com.google.firebase:firebase-crashlytics"

implementation "com.firebaseui:firebase-ui-auth:8.0.0"
```

### Problem

After updating firebase realtime database dependency from 19.3.1 to 20.0.2 a lot of crashes are getting reported. Not really changed anything else with the latest release. It affects around 15% of active users. Anyone experiencing the same issue? Any help is highly appreciated!

```
Fatal Exception: java.lang.RuntimeException: Uncaught exception in Firebase Database runloop (20.0.2). If you are not already on the latest version of the Firebase SDKs, try updating your dependencies. Should this problem persist, please file a report at https://github.com/firebase/firebase-android-sdk
       at com.google.firebase.database.android.AndroidPlatform$1$1.run(AndroidPlatform.java:96)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8633)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

Caused by java.lang.AssertionError: hardAssert failed: Expected connection state disconnected, but was GettingToken
       at com.google.firebase.database.connection.ConnectionUtils.hardAssert(ConnectionUtils.java:67)
       at com.google.firebase.database.connection.PersistentConnectionImpl.lambda$tryScheduleReconnect$2(PersistentConnectionImpl.java:771)
       at com.google.firebase.database.connection.PersistentConnectionImpl.$r8$lambda$TPmxS5Ul3aIZupJNWDNIbn3GMUQ(PersistentConnectionImpl.java)
       at com.google.firebase.database.connection.PersistentConnectionImpl$$InternalSyntheticLambda$0$f57df02977d75c35b83110250a87e74eafeeceab6f42dcc20508ee097d4a2331$0.onSuccess(PersistentConnectionImpl.java:11)
       at com.google.android.gms.tasks.zzm.run(zzm.java:1)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
```

**Comment by argzdev** [comment]
Hi @cpferschy, I'm unable to replicate the issue with a quickstart as well, this could be difficult to investigate without a repro. If you're able to create an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example), that'll help us alot. 

As for your active users whom encountered this issue, is there any similarity that you've noticed from the crashes? Like same device type, version level, or anything that stands out.

**Comment by SteveBurkert** [comment]
Same here. Same configuration. Looked up for similarities. Only similarity is that 99% of users are in background.

**Comment by PeaceAllen** [comment]
I have the same issue.   100% samsung  and 100% background.
----------------
Fatal Exception: java.lang.RuntimeException: Uncaught exception in Firebase Database runloop (20.0.2). If you are not already on the latest version of the Firebase SDKs, try updating your dependencies. Should this problem persist, please file a report at https://github.com/firebase/firebase-android-sdk
       at com.google.firebase.database.android.AndroidPlatform$1$1.run(AndroidPlatform.java:6)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8595)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

----

Caused by java.lang.AssertionError: hardAssert failed: Expected connection state disconnected, but was GettingToken
       at com.google.firebase.database.connection.ConnectionUtils.hardAssert(ConnectionUtils.java:26)
       at com.google.firebase.database.connection.PersistentConnectionImpl.lambda$tryScheduleReconnect$2(PersistentConnectionImpl.java:52)
       at com.google.firebase.database.connection.PersistentConnectionImpl.$r8$lambda$TPmxS5Ul3aIZupJNWDNIbn3GMUQ(PersistentConnectionImpl.java)
       at com.google.firebase.database.connection.PersistentConnectionImpl$$InternalSyntheticLambda$1$f57df02977d75c35b83110250a87e74eafeeceab6f42dcc20508ee097d4a2331$0.onSuccess(PersistentConnectionImpl.java:11)
       at com.google.android.gms.tasks.zzm.run(zzm.java:27)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)

**Comment by chip2n** [comment]
Also getting this issue - only 38% background though. This is using Firebase BoM version 28.4.2.

**Android versions**
Android 12
Android 11
Android 9

**Devices**
Galaxy Note20 Ultra 5G
Galaxy S8
Xperia 10 II 
Pixel 6

**Comment by cpferschy** [comment]
Thanks @argzdev, @SteveBurkert, @PeaceAllen and @chip2n for also reporting this crash. 

I tried using Firebase BoM 28.0.0, 28.4.2 and 29.0.0 but all with the same crash.

88% Samsung
81% Android 11
97% In background

<img width="1267" alt="screenshot" src="https://user-images.githubusercontent.com/16591576/140718541-04c16dd2-0db1-4d3d-b90e-b7a48bdc3251.png">

Unfortunately I'm not able to reproduce the error. It is a repetitive crash and happens 5 times per user on average.

Any help is highly appreciated!

**Comment by OscarGonzalezLesaga** [comment]
Thanks, folks for reporting this bug.

We have received the same crash in crashlytics. We are using the Firebase-Bom version 28.4.2, we can upgrade to 29.0.0 but the internal database version (20.0.2) will not change or upgrade.

This crash is happening to us to these devices:

<img width="1288" alt="Captura de pantalla 2021-11-09 a las 11 52 26" src="https://user-images.githubusercontent.com/26376335/140911210-e9ef5076-5320-4e50-91e2-d2237af91845.png">

And we are receiving this logs in Firebase Crashlytics:

<img width="1284" alt="Captura de pantalla 2021-11-09 a las 11 53 17" src="https://user-images.githubusercontent.com/26376335/140911324-4c5c1469-fc6f-4ab4-bd1b-4f1ee38688df.png">

Any new regarding this bug? 

The only change that I just realized compared with the other responses is that we don't have this bug in the background, only 2%.

Thanks for the support.

**Comment by spencerwhyte** [comment]
We are also now seeing this issue. 57% background. Non BOM.
`
    implementation("com.google.firebase:firebase-messaging:22.0.0")
    implementation("com.google.firebase:firebase-inappmessaging-display:20.1.0")
    implementation("com.google.firebase:firebase-auth:21.0.1")
    implementation("com.google.firebase:firebase-database:20.0.1")
    implementation("com.google.firebase:firebase-storage:20.0.0")
    implementation("com.google.firebase:firebase-perf:20.0.2")
    implementation("com.google.firebase:firebase-invites:17.0.0")
    implementation("com.google.firebase:firebase-config:21.0.1")
    implementation("com.google.firebase:firebase-firestore:23.0.3")
    implementation("com.google.firebase:firebase-crashlytics:18.2.1")
    implementation("com.google.firebase:firebase-analytics:19.0.1")
    implementation("com.google.firebase:firebase-config:21.0.1")
`

**Comment by argzdev** [comment]
Hi all, we're still investigate this, but thanks for the inputs as this might lead to clues to what's going on.

**Comment by schmidt-sebastian** [comment]
I will take a look at this.

**Comment by PeaceAllen** [comment]
when to release a new version firebase-database with fixed?

**Comment by schmidt-sebastian** [comment]
This will be part of our next release. We are already working on verifying this release.
