### ISSUE TITLE
I'm getting the same crash:

### ISSUE THREAD

**Issue by chanti0407** [firebase/firebase-android-sdk#3135]
I'm getting the same crash:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.isEmpty()' on a null object reference
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay.supportsCustomTabs(FirebaseInAppMessagingDisplay.java)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay.launchUriIntent(FirebaseInAppMessagingDisplay.java)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay.access$300(FirebaseInAppMessagingDisplay.java)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay$3.onClick(FirebaseInAppMessagingDisplay.java)
       at android.view.View.performClick(View.java:5267)
       at android.view.View$PerformClick.run(View.java:21536)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5728)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
```

**Device** LAVA  iris 820 Android v6.0 
**Using flutter sdk** ``` firebase_in_app_messaging: ^0.2.1```

_Originally posted by @zjamshidi in https://github.com/firebase/firebase-android-sdk/issues/2128#issuecomment-735138892_

**Comment by argzdev** [comment]
Hi, we would love to investigate this further, however please open a new ticket following our template so we can get some basic information to check out the issue. With that said, I'll be closing this ticket.
