### ISSUE TITLE
Occasional crash with BadTokenException when trying to display FIAM 

### ISSUE THREAD

**Issue by stari4ek** [firebase/firebase-android-sdk#3183]
### [READ] Step 1: Are you in the right place?

yep

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: `2020.3.1 Patch 3`
  * Firebase Component: FIAM
  * Component version:  20.1.0 (comes from `com.google.firebase:firebase-bom:28.4.2`)

#### Steps to reproduce:

No steps. I am seeing occasional crashes in crashlytics, when there is active FIAM campaign
```
Fatal Exception: java.lang.RuntimeException: Unable to pause activity {by.stari4ek.tvirl/by.stari4ek.iptv4atv.ui.setup.SetupGatewayActivity}: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
       at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4032)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3987)
       at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3939)
       at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6680)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
       at android.view.ViewRootImpl.setView(ViewRootImpl.java:795)
       at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:356)
       at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
       at com.google.firebase.inappmessaging.display.internal.FiamWindowManager.show(FiamWindowManager.java:67)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay$4$4.run(FirebaseInAppMessagingDisplay.java:411)
       at android.app.Activity.runOnUiThread(Activity.java:6282)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay$4.onSuccess(FirebaseInAppMessagingDisplay.java:407)
       at com.google.firebase.inappmessaging.display.internal.FiamImageLoader$Callback.onLoadCleared(FiamImageLoader.java:164)
       at com.bumptech.glide.request.SingleRequest.clear(SingleRequest.java:319)
       at com.bumptech.glide.manager.RequestTracker.clearAndRemove(RequestTracker.java:72)
       at com.bumptech.glide.RequestManager.untrack(RequestManager.java:663)
       at com.bumptech.glide.RequestManager.untrackOrDelegate(RequestManager.java:631)
       at com.bumptech.glide.RequestManager.clear(RequestManager.java:627)
       at com.google.firebase.inappmessaging.display.internal.FiamImageLoader.cancelTag(FiamImageLoader.java:70)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay.unbindFiamFromActivity(FirebaseInAppMessagingDisplay.java:227)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay.onActivityPaused(FirebaseInAppMessagingDisplay.java:188)
       at android.app.Application.dispatchActivityPaused(Application.java:248)
       at android.app.Activity.onPause(Activity.java:1731)
       at androidx.fragment.app.FragmentActivity.onPause(FragmentActivity.java:388)
       at com.trello.rxlifecycle3.components.support.RxFragmentActivity.onPause(RxFragmentActivity.java:95)
       at android.app.Activity.performPause(Activity.java:7337)
       at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1465)
       at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4022)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3987)
       at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3939)
       at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6680)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by stari4ek** [comment]
Same issue with different callstack happens, when FIAM image is downloaded after Activity is destroyed:

```
259 | Fri Nov 26 2021 19:58:21 GMT+0300 (Moscow Standard Time) | main|T] MainMenuActivity: onDestroy() called
260 | Fri Nov 26 2021 19:58:22 GMT+0300 (Moscow Standard Time) | main|E] UncaughtExceptionHandler: Uncaught exception com.bumptech.glide.load.engine.CallbackException: Unexpected exception thrown by non-Glide code 	at b.c.a.k.r.l$b.run(EngineJob.java:17) 	at android.os.Handler.handleCallback(Handler.java:873) 	at android.os.Handler.dispatchMessage(Handler.java:99) 	at android.os.Looper.loop(Looper.java:193) 	at android.app.ActivityThread.main(ActivityThread.java:6680) 	at java.lang.reflect.Method.invoke(Native Method) 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) Caused by: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running? 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:798) 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:356) 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93) 	at b.f.e.z.f0.f$d.run(FirebaseInAppMessagingDisplay.java:26) 	at android.app.Activity.runOnUiThread(Activity.java:6282) 	at b.f.e.z.f0.f.l(FirebaseInAppMessagingDisplay.java:16) 	at b.f.e.z.f0.k.f$a.b(FiamImageLoader.java:5) 	at b.c.a.o.g.o(SingleRequest.java:18) 	at b.c.a.o.g.n(SingleRequest.java:14) 	at b.c.a.k.r.l$b.run(EngineJob.java:15) 	at android.os.Handler.handleCallback(Handler.java:873) 	at android.os.Handler.dispatchMessage(Handler.java:99)
```

```
Fatal Exception: com.bumptech.glide.load.engine.CallbackException: Unexpected exception thrown by non-Glide code
       at com.bumptech.glide.load.engine.EngineJob.callCallbackOnResourceReady(EngineJob.java:160)
       at com.bumptech.glide.load.engine.EngineJob$CallResourceReady.run(EngineJob.java:424)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6680)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
       at android.view.ViewRootImpl.setView(ViewRootImpl.java:798)
       at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:356)
       at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
       at com.google.firebase.inappmessaging.display.internal.FiamWindowManager.show(FiamWindowManager.java:67)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay$4$4.run(FirebaseInAppMessagingDisplay.java:411)
       at android.app.Activity.runOnUiThread(Activity.java:6282)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay$4.onSuccess(FirebaseInAppMessagingDisplay.java:407)
       at com.google.firebase.inappmessaging.display.internal.FiamImageLoader$Callback.onResourceReady(FiamImageLoader.java:157)
       at com.google.firebase.inappmessaging.display.internal.FiamImageLoader$Callback.onResourceReady(FiamImageLoader.java:135)
       at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:631)
       at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:575)
       at com.bumptech.glide.load.engine.EngineJob.callCallbackOnResourceReady(EngineJob.java:158)
       at com.bumptech.glide.load.engine.EngineJob$CallResourceReady.run(EngineJob.java:424)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6680)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by argzdev** [comment]
Hi @stari4ek, thank you for reporting. I'll try to investigate this and see what I can find. In the meantime, may I ask for the 2nd scenario, any chance that you're able to repro this issue?

**Comment by stari4ek** [comment]
I did not try to reproduce it locally. But it looks straightforward. Activity which was active when FIAM triggered is replaced with another activity, while FIAM's image is still downloading

**Comment by argzdev** [comment]
May I ask did you encounter this on previous versions or on the latest version of BoM (29.0.0)?

**Comment by stari4ek** [comment]
I do not run FIAM campaigns that often. Will update this issue, when upgrade to new BOM and have new campaign.

**Comment by argzdev** [comment]
Sure, I'll wait for your update, thanks!
