### ISSUE TITLE
Updating FirebaseBOM 28.3.1 to 28.4.0 breaks the app

### ISSUE THREAD

**Issue by Kurisasa** [firebase/firebase-android-sdk#3184]
### [READ] Step 1: Are you in the right place?

Yes

### [REQUIRED] Step 2: Describe your environment

-     Android Studio version: Arctic Fox | 2020.3.1 Patch 1
-     Firebase Component: InAppMessagingDisplay
-     Component version: 20.1.0 (comes from com.google.firebase:firebase-bom:28.4.0)
-     Firebase InAppMessagingDisplay 20.1.0
-     Other firebase libs we use outside of BOM
-     Dagger version - 2.40.2
-     Glide version - 4.12.0
-     Compile sdk version - 31
-     Build tools version - 31.0.0
-     Min sdk version -  21
-     Target sdk version - 31

### [REQUIRED] Step 3: Describe the problem

We are injecting the AppGlideModule into our app using Dagger.
It works until we update the FirebaseBOM from 28.3.1 to 28.4.0. 
Could this be a conflict of Glide lib?
Updating dagger to the latest without updating the FirebaseBOM, doesn't break the app.
Updating FirebaseBOM from 28.3.1 to 28.4.0 gives us the `java.lang.RuntimeException: Unable to get provider` error.

#### Steps to reproduce:

What happened? How can we make the problem occur?

update FirebaseBOM 28.3.1 to 28.4.0

java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.NullPointerException: Attempt to invoke interface method 'void com.superbalist.android.module.ApplicationComponent.inject(com.superbalist.android.util.image.GlideConfiguration)' on a null object reference
        at android.app.ActivityThread.installProvider(ActivityThread.java:6988)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6528)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6445)
        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.superbalist.android.module.ApplicationComponent.inject(com.superbalist.android.util.image.GlideConfiguration)' on a null object reference
        at com.superbalist.android.util.image.GlideConfiguration.registerComponents(GlideConfiguration.java:54)
        at com.bumptech.glide.GeneratedAppGlideModuleImpl.registerComponents(GeneratedAppGlideModuleImpl.java:32)
        at com.bumptech.glide.Glide.initializeGlide(Glide.java:329)
        at com.bumptech.glide.Glide.initializeGlide(Glide.java:266)
        at com.bumptech.glide.Glide.checkAndInitializeGlide(Glide.java:210)
        at com.bumptech.glide.Glide.get(Glide.java:191)
        at com.bumptech.glide.Glide.getRetriever(Glide.java:774)
        at com.bumptech.glide.Glide.with(Glide.java:801)
        at com.google.firebase.inappmessaging.display.internal.injection.modules.GlideModule.providesGlideRequestManager(GlideModule.java:32)
        at com.google.firebase.inappmessaging.display.internal.injection.modules.GlideModule_ProvidesGlideRequestManagerFactory.providesGlideRequestManager(GlideModule_ProvidesGlideRequestManagerFactory.java:43)
        at com.google.firebase.inappmessaging.display.internal.injection.modules.GlideModule_ProvidesGlideRequestManagerFactory.get(GlideModule_ProvidesGlideRequestManagerFactory.java:32)
        at com.google.firebase.inappmessaging.display.internal.injection.modules.GlideModule_ProvidesGlideRequestManagerFactory.get(GlideModule_ProvidesGlideRequestManagerFactory.java:11)
        at com.google.firebase.inappmessaging.display.dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.google.firebase.inappmessaging.display.internal.FiamImageLoader_Factory.get(FiamImageLoader_Factory.java:21)
        at com.google.firebase.inappmessaging.display.internal.FiamImageLoader_Factory.get(FiamImageLoader_Factory.java:8)
        at com.google.firebase.inappmessaging.display.dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay_Factory.get(FirebaseInAppMessagingDisplay_Factory.java:61)
        at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay_Factory.get(FirebaseInAppMessagingDisplay_Factory.java:16)
        at com.google.firebase.inappmessaging.display.dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.google.firebase.inappmessaging.display.internal.injection.components.DaggerAppComponent.providesFirebaseInAppMessagingUI(DaggerAppComponent.java:80)
        at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplayRegistrar.buildFirebaseInAppMessagingUI(FirebaseInAppMessagingDisplayRegistrar.java:72)
        at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplayRegistrar.$r8$lambda$mFT7XCE3YJXhnGdhKohfXnpd5DM(Unknown Source:0)
2021-11-29 08:55:08.735 12777-12777/com.superbalist.android.beta E/AndroidRuntime:     at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplayRegistrar$$ExternalSyntheticLambda0.create(Unknown Source:2)
        at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0$com-google-firebase-components-ComponentRuntime(ComponentRuntime.java:132)
        at com.google.firebase.components.ComponentRuntime$$ExternalSyntheticLambda1.get(Unknown Source:4)
        at com.google.firebase.components.Lazy.get(Lazy.java:53)
        at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents(ComponentRuntime.java:291)
        at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(ComponentRuntime.java:281)
        at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:584)
        at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:303)
        at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:267)
        at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:252)
        at com.google.firebase.provider.FirebaseInitProvider.onCreate(FirebaseInitProvider.java:51)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2092)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2066)
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(FirebaseInitProvider.java:45)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6983)
        	... 10 more

#### Relevant Code:

> 
>   @Override
>     public void registerComponents(@NonNull Context context,
>                                    @NonNull Glide glide,
>                                    @NonNull Registry registry) {
>         super.registerComponents(context, glide, registry);
>         SuperbApp.getComponent(context).inject(this);
>         internalClient = new OkHttpClient.Builder().addInterceptor(new UserAgentInterceptor()).build();
>         registry.append(GlideUrl.class, InputStream.class,
>                 new OkHttpUrlLoader.Factory(internalClient));
>     }

**Comment by argzdev** [comment]
Hi @Kurisasa, thanks for reporting. I'll try to investigate and see what I can find. In the meantime, may I ask if you're also able to encounter this issue when using our latest BoM version 29.0.0

**Comment by Kurisasa** [comment]
@argzdev  Thanks for replying, yes I can reproduce the issue on the latest BOM 29.0.0 as well. I will try and see if I can do the MCVE for you.

**Comment by Kurisasa** [comment]
@argzdev  here you go

https://github.com/Kurisasa/My_Application/tree/master

**Comment by argzdev** [comment]
Hi @Kurisasa, thanks for the MCVE. I was able to repro the issue. With that said, I'll notify an engineer about this. Thanks!

**Comment by eldhosembabu** [comment]
Hi @Kurisasa ,

I did a look into this issue and we could see that with Firebase BOM version 28.4.0, we have migrated to using Glide library for downloading images in InappMessaging which could be the reason why you are seeing the issue from this version onwards and the issue could be because of how inappmessaging uses glide dependency and your app uses glide dependency (Basically the dagger injection).

I went through the sample app provided and was able to resolve the issue there by commenting the following lines : 

https://github.com/Kurisasa/My_Application/blob/master/app/src/main/java/com/example/myapplication/GlideConfiguration.java#L36 => "//        MyApp.getComponent(context).inject(this);" and 

https://github.com/Kurisasa/My_Application/blob/master/app/src/main/java/com/example/myapplication/ApplicationComponent.java#L12 => "//    void inject(GlideConfiguration glideConfiguration);"

I'm not sure why we need to inject the GlideConfiguration above, may be i could be wrong. Let me know whether this resolves your issue. Thanks!

**Comment by Panzenbaby** [comment]
I'm facing the same problem. We need to inject an instance of OkHttpClient inside of our GlideModule. To do so we need to prepare dagger in our application first.

As far as I can see FirebaseInAppMessagingDisplay uses Glide and because of FirebaseInitProvider is initialized before the Application calls onCreate, the provider will initialize Glide. Which will lead into a crash because the application is not created and the injection call end up in a NPE.

**Comment by Panzenbaby** [comment]
java.lang.NullPointerException: Attempt to invoke interface method 'void com.superbalist.android.module.ApplicationComponent.inject(com.superbalist.android.util.image.GlideConfiguration)' on a null object reference

@eldhosembabu commenting out the line which is causing the NPE is not the same as fixing the problem :)

**Comment by eldhosembabu** [comment]
If your real problem is adding an OkHttpClient, you can do that inside registerComponents method I don't see the need for injecting the GlideConfiguration as mentioned above.


For reference: 

    `    @Override
    public void registerComponents(@NonNull Context context,
                                   @NonNull Glide glide,
                                   @NonNull Registry registry) {

        Log.d("GlideConfiguration", ">>>>>>> registerComponents");
        super.registerComponents(context, glide, registry);
       //MyApp.getComponent(context).inject(this);

       // Register your OKHttpClient as below:
        OkHttpClient client = new OkHttpClient.Builder().build();
        OkHttpUrlLoader.Factory factory = new OkHttpUrlLoader.Factory(client);
        glide.getRegistry().replace(GlideUrl.class, InputStream.class, factory);
    }`

**Comment by Panzenbaby** [comment]
Creating a new instance of OkHttpClient is not an option. There are reasons why I need the same instance as I use for Retrofit.

A dirty work around would be to create the component from inside of the GlideConfiguration if it hasn't been created at this point. I would like to use an other fix but there is no chance. I tried to use androidx.startup but the InitializationProvider will be called after FirebaseInitProvider and there is no chance to change the initialization order. Changing initOrder of the provider tag in manifest to change that causes an other crash.

```
    @Override
    public void registerComponents(@NonNull Context context, @NonNull Glide glide, @NonNull Registry registry) {
        super.registerComponents(context, glide, registry);

        if (context.getApplicationContext() instanceof MyApp) {
            ((MyApp) context.getApplicationContext()).createComponentIfNecessary();
        }
        MyApp.getComponent(context).inject(this);
    }
```
