### ISSUE TITLE
Crash when writeRequestBodyToOutputStream

### ISSUE THREAD

**Issue by edtslib** [firebase/firebase-android-sdk#3251]
### Discussed in https://github.com/firebase/firebase-android-sdk/discussions/3250

<div type='discussions-op-text'>

<sup>Originally posted by **edtslib** December 20, 2021</sup>
i got 2 crash on Crashlytics Dashboard. Here is a log

Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=8192; index=8192
       at com.android.okhttp.okio.Buffer.writeByte(Buffer.java:973)
       at com.android.okhttp.internal.Platform.concatLengthPrefixed(Platform.java:212)
       at com.android.okhttp.internal.Platform.configureTlsExtensions(Platform.java:116)
       at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:187)
       at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
       at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
       at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
       at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
       at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:258)
       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:26)
       at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.writeRequestBodyToOutputStream(FirebaseInstallationServiceClient.java:239)
       at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.writeGenerateAuthTokenRequestBodyToOutputStream(FirebaseInstallationServiceClient.java:280)
       at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.generateAuthToken(FirebaseInstallationServiceClient.java:415)
       at com.google.firebase.installations.FirebaseInstallations.fetchAuthTokenFromServer(FirebaseInstallations.java:566)
       at com.google.firebase.installations.FirebaseInstallations.doNetworkCallIfNecessary(FirebaseInstallations.java:390)
       at com.google.firebase.installations.FirebaseInstallations.lambda$doRegistrationOrRefresh$2(FirebaseInstallations.java:377)
       at com.google.firebase.installations.FirebaseInstallations$$InternalSyntheticLambda$0$8f6250a76dc84afdee54bd79d6c6b27858a3db00ee2f9ff4dae9d6825fe4cbe4$0.run$bridge(FirebaseInstallations.java:16)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)

Can anyone help me?

my application is https://play.google.com/store/apps/details?id=mypoin.indomaret.android&hl=en&gl=US</div>

**Comment by argzdev** [comment]
Hi @edtslib, please follow our template when filing a bug so we can properly address your issue. With that said, I'll be closing this case, thanks!

**Comment by edtslib** [comment]
now, crash happend on 20 users. solve bug more important than your template. :)

**Comment by argzdev** [comment]
Hey @edtslib, I apologize for the misunderstanding. We would certainly like to address and solve your issue, and what we do is we usually ask for our developers to follow the template so that we can gather the basic necessary information for us to conduct an initial investigation. This will help us identify what we can try to narrow down the issue, and help our engineers to produce a fix. We hope you understand, thanks!
