### ISSUE TITLE
Firestore toObject() occasionally throws a NullPointerException exception.

### ISSUE THREAD

**Issue by pistolcaffe** [firebase/firebase-android-sdk#3283]
[REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.1.1
  * Firebase Component: Firestore
  * Component version: 23.0.4

```
implementation platform('com.google.firebase:firebase-bom:28.4.2')
implementation 'com.google.firebase:firebase-firestore-ktx'
```

[REQUIRED] Step 3: Describe the problem

Steps to reproduce:

I am running a reading log app.
The app provides functions that allow users to store and manage the books they have read, and to write and manage memos.

The problematic part is:

1. Firestore has a collection of `Memos`.
2. When the app is launched, the user's `Memos` data is retrieved.
3. Deserialize the `Memo` object using `toObject()`.

**The Memo object looks like this:**
```
data class Memo(
        val bookId: String = "",
        var contents: String = "",
        var createDate: Date = Date(),
        val userUid: String = "",
        var memoId: String = "",
        var bookImage: String? = null,
        var bookName: String = ""
) : Serializable 
```

However, in Crashlytics of our project, the following log is intermittently reported in the `toObject()` step.
```
Caused by java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter <set-?>
       at com.studiobustle.bookjuk.model.Memo.setCreateDate(:2)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.google.firebase.firestore.util.ApiUtil.invoke(ApiUtil.java:61)
       at com.google.firebase.firestore.util.CustomClassMapper$BeanMapper.deserialize(CustomClassMapper.java:772)
       at com.google.firebase.firestore.util.CustomClassMapper$BeanMapper.deserialize(CustomClassMapper.java:741)
       at com.google.firebase.firestore.util.CustomClassMapper.convertBean(CustomClassMapper.java:542)
       at com.google.firebase.firestore.util.CustomClassMapper.deserializeToClass(CustomClassMapper.java:253)
       at com.google.firebase.firestore.util.CustomClassMapper.convertToCustomClass(CustomClassMapper.java:100)
       at com.google.firebase.firestore.DocumentSnapshot.toObject(DocumentSnapshot.java:183)
       at com.google.firebase.firestore.QueryDocumentSnapshot.toObject(QueryDocumentSnapshot.java:116)
       at com.google.firebase.firestore.DocumentSnapshot.toObject(DocumentSnapshot.java:161)
       at com.google.firebase.firestore.QueryDocumentSnapshot.toObject(QueryDocumentSnapshot.java:97)
       at com.studiobustle.bookjuk.data.repository.UserRepository$requestUserMemos$1.onComplete(UserRepository.kt:258)
       at com.google.android.gms.tasks.zzj.run(com.google.android.gms:play-services-tasks@@17.2.0:4)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8633)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

In fact, this problem occurs even though the value stored in the `createDate` field is not null.
(The createDate field type is timestamp.)

I am not finding any solution at all.
It is not an issue that occurs to a specific user, and it is difficult to analyze because the frequency of occurrence is too low.
I would be grateful if anyone could advise me.

Relevant Code:
 ```
db.collection(COLLECTION_MEMOS).whereEqualTo(FIELD_USER_UID, uid).whereEqualTo(FIELD_BOOK_ID, bookId).orderBy(FIELD_CREATE_DATE, Query.Direction.DESCENDING).get().addOnCompleteListener {
            it.result?.documents?.let { docs ->
                val memoList = mutableListOf<Memo>()
                docs.forEach { doc ->
                    doc.toObject(Memo::class.java)?.let { memoObj -> memoList.add(Memo.newMemoWithId(doc.id, memoObj)) }
                }
            }
        }
```

**Comment by argzdev** [comment]
Hi @pistolcaffe, thanks for your report. We'll try to investigate this and see what we can find.

**Comment by argzdev** [comment]
Hi @pistolcaffe, I created a clean project with your relevant code and I was able to repro the issue, however, this issue isn't directly related to Firebase per se, but rather, when you supply a null value to `createdDate`. 

Here's what I tried:
- Test querying objects with no `createdDate`, this works properly
- Test querying objects with `createdDate` = null, this throws the NPE error

<img width="245" alt="Screen Shot 2022-01-03 at 10 30 42 PM" src="https://user-images.githubusercontent.com/93124282/147942506-f222803b-e55e-4831-b96f-78b0949f905f.png">

Perhaps the reason for the low occurence is due to only some of your memo have `createdDate` = null.
Could you check if this is the issue in your case?

**Comment by pistolcaffe** [comment]
Hi. @argzdev  Thanks for checking.
I initially assumed that when the issue was reported by `Crashlytics`, as you said, the `createDate` value was stored as a `null` for some reason, which caused the issue.

However, I tried tracking the corresponding `memoId` in `Crashlytics` to figure out the detailed cause, and `createDate` was not null.
(`createDate` of all memo data reported to `Crashlytics` was not null )

Here is the memo Document reported to `Crashlytics`:
![스크린샷 2022-01-05 오후 2 52 31](https://user-images.githubusercontent.com/16452048/148167375-14b9b209-3997-4568-9607-23218656d2af.png)

Currently, there is a difficulty because the frequency of occurrence of this issue is too low.

I have one question.
When saving notes, the following code.

```
val memoDocRef = db.collection(COLLECTION_MEMOS).document()
val newMemoParams = hashMapOf(
        FIELD_BOOK_ID to bookId,
        FIELD_USER_UID to uid,
        FIELD_CREATE_DATE to FieldValue.serverTimestamp(),
        FIELD_CONTENTS to contents
)

memoDocRef.set(newMemoParams)
```

If I saved the `createDate` field using `FieldValue.serverTimestamp()` and immediately called the `createDate` value, could this be the cause of the issue?

**Comment by thebrianchen** [comment]
@pistolcaffe 
> If I saved the createDate field using FieldValue.serverTimestamp() and immediately called the createDate value, could this be the cause of the issue?

In this case, Firestore would return the cached value of the last connection time. This seems WAI from Firestore, so I'm going to close the issue. Feel free to ask any other questions you may have though!
