### ISSUE TITLE
Crash in Android 7 with FirebaseInstallations

### ISSUE THREAD

**Issue by charlie1081** [firebase/firebase-android-sdk#3299]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Arctic Fox | 2020.3.1 Patch 4
  * Firebase Component: analytics crashlytics messaging
  * Component version: 18.0.0 17.3.0 17.3.4

### [REQUIRED] Step 3: Describe the problem

Getting a crash in Android 7 with the following message in crashlytics:

``
java.lang.NullPointerException: Attempt to get length of null array
``

#### Relevant Code:

```
java.lang.NullPointerException: Attempt to get length of null array
	at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:187)
	at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:156)
	at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:98)
	at com.android.okhttp.internal.http.HttpEngine.createNextConnection(HttpEngine.java:345)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:328)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:246)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:126)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:257)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java)
	at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.t(FirebaseInstallationServiceClient.java:1)
	at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.s(FirebaseInstallationServiceClient.java:2)
	at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.f(FirebaseInstallationServiceClient.java:8)
	at com.google.firebase.installations.FirebaseInstallations.j(FirebaseInstallations.java:6)
	at com.google.firebase.installations.FirebaseInstallations.h(FirebaseInstallations.java:4)
	at com.google.firebase.installations.FirebaseInstallations.u(FirebaseInstallations.java:1)
	at com.google.firebase.installations.FirebaseInstallations$$Lambda$4.run(FirebaseInstallations.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
```

**Comment by argzdev** [comment]
Hi @charlie1081, thanks for reporting. I noticed that you're using old versions of our SDK, could you try the latest versions (see below) and check if that resolves your issue? If that doesn't help, any chance that you're able to repro this issue? If you could provide us an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example), this will help speed up our investigation. Thanks!

- Analytics - 20.0.2
- Crashlytics - 18.2.6
- Cloud Messaging - 23.0.0
