### ISSUE TITLE
CodedOutputStream indexOutOfBounds exception

### ISSUE THREAD

**Issue by ilandbt** [firebase/firebase-android-sdk#3317]
### Environment

  * Android Studio version: Android Studio Arctic Fox | 2020.3.1 Patch 4
  * Firebase Component: perf
  * Component version: 20.0.1

### The problem
app crashes randomly for users

#### Steps to reproduce:
No steps to reproduce

#### Exception log - 
1. 
Fatal Exception: java.lang.RuntimeException: Serializing com.google.firebase.perf.v1.PerfMetric to a byte array threw an IOException (should never happen).
       at com.google.protobuf.AbstractMessageLite.toByteArray(AbstractMessageLite.java:75)
       at com.google.firebase.perf.transport.-$$Lambda$Itu3_v5Z-Xtk9hzoqKGtXZ9cnAw.apply(-.java:2)
       at com.google.android.datatransport.runtime.SendRequest.getPayload(SendRequest.java:35)
       at com.google.android.datatransport.runtime.TransportRuntime.convert(TransportRuntime.java:162)
       at com.google.android.datatransport.runtime.TransportRuntime.send(TransportRuntime.java:153)
       at com.google.android.datatransport.runtime.TransportImpl.schedule(TransportImpl.java:50)
       at com.google.android.datatransport.runtime.TransportImpl.send(TransportImpl.java:45)
       at com.google.firebase.perf.transport.FlgTransport.log(FlgTransport.java:56)
       at com.google.firebase.perf.transport.TransportManager.dispatchLog(TransportManager.java:471)
       at com.google.firebase.perf.transport.TransportManager.syncLog(TransportManager.java:378)
       at com.google.firebase.perf.transport.TransportManager.lambda$log$3(TransportManager.java:326)
       at com.google.firebase.perf.transport.-$$Lambda$TransportManager$awKHZGKIuVSDXVmPbj2QeFlqz3U.run(-.java:6)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:929)

2. 
Caused by com.google.protobuf.CodedOutputStream$OutOfSpaceException: CodedOutputStream was writing to a flat byte array and ran out of space.: Pos: 261, limit: 260, len: 1
       at com.google.protobuf.CodedOutputStream$ArrayEncoder.writeUInt32NoTag(CodedOutputStream.java:1378)
       at com.google.protobuf.CodedOutputStream$ArrayEncoder.writeTag(CodedOutputStream.java:1174)
       at com.google.protobuf.CodedOutputStream$ArrayEncoder.writeMessage(CodedOutputStream.java:1280)
       at com.google.protobuf.CodedOutputStreamWriter.writeMessage(CodedOutputStreamWriter.java:154)
       at com.google.protobuf.CodedOutputStreamWriter.writeMessageList(CodedOutputStreamWriter.java:560)
       at com.google.protobuf.SchemaUtil.writeMessageList(SchemaUtil.java:304)
       at com.google.protobuf.MessageSchema.writeFieldsInAscendingOrderProto2(MessageSchema.java:2722)
       at com.google.protobuf.MessageSchema.writeTo(MessageSchema.java:2548)
       at com.google.protobuf.CodedOutputStream$ArrayEncoder.writeMessage(CodedOutputStream.java:1282)
       at com.google.protobuf.CodedOutputStreamWriter.writeMessage(CodedOutputStreamWriter.java:154)
       at com.google.protobuf.MessageSchema.writeFieldsInAscendingOrderProto2(MessageSchema.java:2641)
       at com.google.protobuf.MessageSchema.writeTo(MessageSchema.java:2548)
       at com.google.protobuf.GeneratedMessageLite.writeTo(GeneratedMessageLite.java:272)
       at com.google.protobuf.AbstractMessageLite.toByteArray(AbstractMessageLite.java:71)
       at com.google.firebase.perf.transport.-$$Lambda$Itu3_v5Z-Xtk9hzoqKGtXZ9cnAw.apply(-.java:2)
       at com.google.android.datatransport.runtime.SendRequest.getPayload(SendRequest.java:35)
       at com.google.android.datatransport.runtime.TransportRuntime.convert(TransportRuntime.java:162)
       at com.google.android.datatransport.runtime.TransportRuntime.send(TransportRuntime.java:153)
       at com.google.android.datatransport.runtime.TransportImpl.schedule(TransportImpl.java:50)
       at com.google.android.datatransport.runtime.TransportImpl.send(TransportImpl.java:45)
       at com.google.firebase.perf.transport.FlgTransport.log(FlgTransport.java:56)
       at com.google.firebase.perf.transport.TransportManager.dispatchLog(TransportManager.java:471)
       at com.google.firebase.perf.transport.TransportManager.syncLog(TransportManager.java:378)
       at com.google.firebase.perf.transport.TransportManager.lambda$log$3(TransportManager.java:326)
       at com.google.firebase.perf.transport.-$$Lambda$TransportManager$awKHZGKIuVSDXVmPbj2QeFlqz3U.run(-.java:6)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:929)

3. 

Caused by java.lang.ArrayIndexOutOfBoundsException: length=260; index=260
       at com.google.protobuf.CodedOutputStream$ArrayEncoder.writeUInt32NoTag(CodedOutputStream.java:1369)
       at com.google.protobuf.CodedOutputStream$ArrayEncoder.writeTag(CodedOutputStream.java:1174)
       at com.google.protobuf.CodedOutputStream$ArrayEncoder.writeMessage(CodedOutputStream.java:1280)
       at com.google.protobuf.CodedOutputStreamWriter.writeMessage(CodedOutputStreamWriter.java:154)
       at com.google.protobuf.CodedOutputStreamWriter.writeMessageList(CodedOutputStreamWriter.java:560)
       at com.google.protobuf.SchemaUtil.writeMessageList(SchemaUtil.java:304)
       at com.google.protobuf.MessageSchema.writeFieldsInAscendingOrderProto2(MessageSchema.java:2722)
       at com.google.protobuf.MessageSchema.writeTo(MessageSchema.java:2548)
       at com.google.protobuf.CodedOutputStream$ArrayEncoder.writeMessage(CodedOutputStream.java:1282)
       at com.google.protobuf.CodedOutputStreamWriter.writeMessage(CodedOutputStreamWriter.java:154)
       at com.google.protobuf.MessageSchema.writeFieldsInAscendingOrderProto2(MessageSchema.java:2641)
       at com.google.protobuf.MessageSchema.writeTo(MessageSchema.java:2548)
       at com.google.protobuf.GeneratedMessageLite.writeTo(GeneratedMessageLite.java:272)
       at com.google.protobuf.AbstractMessageLite.toByteArray(AbstractMessageLite.java:71)
       at com.google.firebase.perf.transport.-$$Lambda$Itu3_v5Z-Xtk9hzoqKGtXZ9cnAw.apply(-.java:2)
       at com.google.android.datatransport.runtime.SendRequest.getPayload(SendRequest.java:35)
       at com.google.android.datatransport.runtime.TransportRuntime.convert(TransportRuntime.java:162)
       at com.google.android.datatransport.runtime.TransportRuntime.send(TransportRuntime.java:153)
       at com.google.android.datatransport.runtime.TransportImpl.schedule(TransportImpl.java:50)
       at com.google.android.datatransport.runtime.TransportImpl.send(TransportImpl.java:45)
       at com.google.firebase.perf.transport.FlgTransport.log(FlgTransport.java:56)
       at com.google.firebase.perf.transport.TransportManager.dispatchLog(TransportManager.java:471)
       at com.google.firebase.perf.transport.TransportManager.syncLog(TransportManager.java:378)
       at com.google.firebase.perf.transport.TransportManager.lambda$log$3(TransportManager.java:326)
       at com.google.firebase.perf.transport.-$$Lambda$TransportManager$awKHZGKIuVSDXVmPbj2QeFlqz3U.run(-.java:6)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:929)

**Comment by argzdev** [comment]
Hi @ilandbt, thanks for reporting. I'm guessing this might have similarities with the previous issue you've shared, however since both issues have different error messages, then let's treat it as such. With that said, may I ask if you added any code snippets of Firebase Performance such as custom monitoring for specific code or network requests? If so, could you share us any code snippets? Thanks

**Comment by visumickey** [comment]
@ilandbt Thanks for reporting this issue. Looking at the stack trace, there seem to be some dependencies on Protobuf that could be a part of the reason for the crash. Can you please provide me the version number of Protobuf that was used? That could be a useful information.

In addition to that can you provide a bit more details about the crash?
1. Are there any log statements just before or after this crash?
2. Was this crash happening when a specific type of action occurred? (Eg: Network request, app launch, backgrounding or likes)
3. Can you share how often are you seeing this crash?

At this time, the stack trace is not really helping us to understand this issue further. Any more details would help us debug this better.

**Comment by ilandbt** [comment]
I cant reproduce the crash i can only see it in Crashlytics.

Portbuf version 3.14.0

It happens ~100 in 30 days.
91% of the crashes are happening in the background.

I see this might be an issue with a 3rd party library we are using for network, ill investigate more in our side and will update.

**Comment by visumickey** [comment]
@ilandbt Thanks for the details. We will attempt on investigating this at our end. But given the challenges in reproducing this issue, we will stay hold until we learn that this is an issue with Firebase Performance. Will wait on your investigations on the third party library before we dive deeper.
