### ISSUE TITLE
CodedOutputStream NullPointerException

### ISSUE THREAD

**Issue by ilandbt** [firebase/firebase-android-sdk#3318]
### Environment

  * Android Studio version: Android Studio Arctic Fox | 2020.3.1 Patch 4
  * Firebase Component: perf
  * Component version: 20.0.1

### The problem
app crashes randomly for users

#### Steps to reproduce:
No steps to reproduce

#### Exception log - 

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.google.protobuf.AbstractMessageLite.getSerializedSize(com.google.protobuf.q0)' on a null object reference
       at com.google.protobuf.CodedOutputStream.computeMessageSizeNoTag(CodedOutputStream.java:882)
       at com.google.protobuf.SchemaUtil.computeSizeMessageList(SchemaUtil.java:704)
       at com.google.protobuf.MessageSchema.getSerializedSizeProto2(MessageSchema.java:1603)
       at com.google.protobuf.MessageSchema.getSerializedSize(MessageSchema.java:1422)
       at com.google.protobuf.AbstractMessageLite.getSerializedSize(AbstractMessageLite.java:113)
       at com.google.protobuf.CodedOutputStream.computeMessageSizeNoTag(CodedOutputStream.java:882)
       at com.google.protobuf.CodedOutputStream.computeMessageSize(CodedOutputStream.java:670)
       at com.google.protobuf.SchemaUtil.computeSizeMessage(SchemaUtil.java:672)
       at com.google.protobuf.MessageSchema.getSerializedSizeProto2(MessageSchema.java:1509)
       at com.google.protobuf.MessageSchema.getSerializedSize(MessageSchema.java:1422)
       at com.google.protobuf.GeneratedMessageLite.getSerializedSize(GeneratedMessageLite.java:277)
       at com.google.protobuf.AbstractMessageLite.toByteArray(AbstractMessageLite.java:69)
       at com.google.firebase.perf.transport.-$$Lambda$Itu3_v5Z-Xtk9hzoqKGtXZ9cnAw.apply(-.java:2)
       at com.google.android.datatransport.runtime.SendRequest.getPayload(SendRequest.java:35)
       at com.google.android.datatransport.runtime.TransportRuntime.convert(TransportRuntime.java:162)
       at com.google.android.datatransport.runtime.TransportRuntime.send(TransportRuntime.java:153)
       at com.google.android.datatransport.runtime.TransportImpl.schedule(TransportImpl.java:50)
       at com.google.android.datatransport.runtime.TransportImpl.send(TransportImpl.java:45)
       at com.google.firebase.perf.transport.FlgTransport.log(FlgTransport.java:56)
       at com.google.firebase.perf.transport.TransportManager.dispatchLog(TransportManager.java:471)
       at com.google.firebase.perf.transport.TransportManager.syncLog(TransportManager.java:378)
       at com.google.firebase.perf.transport.TransportManager.lambda$log$3(TransportManager.java:326)
       at com.google.firebase.perf.transport.-$$Lambda$TransportManager$awKHZGKIuVSDXVmPbj2QeFlqz3U.run(-.java:6)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

**Comment by visumickey** [comment]
@ilandbt Thanks for reporting this issue. Looking at the stack trace, there seem to be some dependencies on Protobuf that could be a part of the reason for the crash. Can you please provide me the version number of Protobuf that was used? That could be a useful information.

In addition to that can you provide a bit more details about the crash?
1. Are there any log statements just before or after this crash?
2. Was this crash happening when a specific type of action occurred? (Eg: Network request, app launch, backgrounding or likes)
3. Can you share how often are you seeing this crash?

At this time, the stack trace is not really helping us to understand this issue further. Any more details would help us debug this better.
