### ISSUE TITLE
NullPointerException when attaching success listener to reference delete task

### ISSUE THREAD

**Issue by ffrenchm** [firebase/firebase-android-sdk#3375]
I was deleting a storage document and listening for success using the following code:

```
fun ImageManager.deleteImage(...) {
    ...

    ref.delete().addOnSuccessListener {
        println("on success")
    }
}
```

The document is deleted, but the app crashes with the following error:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: <bundle>, PID: 2912
    java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter it
        at <bundle>.utils.image_manager.ImageManager.deleteImage$lambda-7(Unknown Source:7)
        at <bundle>.utils.image_manager.ImageManager.$r8$lambda$yoX7Vx3dxK-4lKHvoC4JHSR8zx8(Unknown Source:0)
        at <bundle>.utils.image_manager.ImageManager$$ExternalSyntheticLambda5.onSuccess(Unknown Source:4)
        at com.google.android.gms.tasks.zzm.run(com.google.android.gms:play-services-tasks@@18.0.0:1)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7397)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```

However, when I add a complete listener instead of a success listener, there is no crash.

This leads me to believe there is a bug with the success listener.

Here's my app.gradle

```
implementation 'com.google.firebase:firebase-core:19.0.0'
implementation 'com.google.firebase:firebase-storage:20.0.0'
```

**Comment by argzdev** [comment]
Hi @ffrenchm, thanks for the report. I created a clean project with the relevant code you've provided but I'm unable to reproduce this issue. Could you provide a [minimal repro](https://stackoverflow.com/help/minimal-reproducible-example) of the issue for me to investigate this further? Thanks!
