### ISSUE TITLE
Crashlytics  specific directory creation fails, causing app to crash at launch

### ISSUE THREAD

**Issue by sarinregmi** [firebase/firebase-android-sdk#3452]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 2020.3.1.Patch 2_____
  * Firebase Component: Crashlytics_____
  * Component version: 18.2.5_____

### [REQUIRED] Step 3: 

After the update from 18.2.3 to 18.2.5, app fails to launch at start and a crash is observed. 

The release notes for 18.2.5 mention 

- Fixed a bug that prevented some Crashlytics session files from being removed after the session ended. All session-specific files are now properly cleaned up.
- Internal improvements to Crashlytics file management, to ensure consistent creation and removal of intermediate Crashlytics files.
- 

Looking at the logs this is what we get on a Xiaomi Mi A2
```
[8754][AndroidRuntime] FATAL EXCEPTION: main
    Process: com.mypackage:logger, PID: 8754
    java.lang.RuntimeException: Unable to create application com.myPackage.MyApplication: java.lang.IllegalStateException: Could not create Crashlytics-specific directory: /data/user/0/com.mypackage/files/.com.google.firebase.crashlytics.files.v1
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5750)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6501)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.IllegalStateException: Could not create Crashlytics-specific directory: /data/user/0/com.mypackage/files/.com.google.firebase.crashlytics.files.v1
        at com.google.firebase.crashlytics.internal.persistence.FileStore.prepareBaseDir(SourceFile:9)
        at com.google.firebase.crashlytics.internal.persistence.FileStore.<init>(SourceFile:2)
        at com.google.firebase.crashlytics.FirebaseCrashlytics.init(SourceFile:6)
        at com.google.firebase.crashlytics.CrashlyticsRegistrar.buildCrashlytics(SourceFile:7)
        at com.google.firebase.crashlytics.CrashlyticsRegistrar.a(Unknown Source:0)
        at com.google.firebase.crashlytics.d.a(Unknown Source:2)
        at com.google.firebase.components.q.q(SourceFile:2)
        at com.google.firebase.components.q.g(Unknown Source:0)
        at com.google.firebase.components.o.get(Unknown Source:4)
        at com.google.firebase.components.w.get(SourceFile:5)
        at com.google.firebase.components.q.m(SourceFile:5)
        at com.google.firebase.components.q.o(SourceFile:5)
        at com.google.firebase.d.u(SourceFile:7)
        at com.google.firebase.d.y(SourceFile:13)
        at com.google.firebase.d.x(SourceFile:1)
        at com.google.firebase.d.w(SourceFile:7)
        at com.myApplication.onCreate(SourceFile:6)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1120)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5747)
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6501) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
```

On other devices tested, the app does not crash, but we see the following log saying the log file is missing.

```
02-02 12:53:26.162 14451 14471 E [FMA-myPackage]: [14499][FirebaseCrashlytics] Could not open log file: /data/user/0/myPackage/files/.com.google.firebase.crashlytics.files.v1/open-sessions/61FA2DF203C6000138731EC843AF6BC4/userlog
02-02 12:53:26.162 14451 14471 E [FMA-myPackage]: java.io.FileNotFoundException: /data/user/0/myPackage/files/.com.google.firebase.crashlytics.files.v1/open-sessions/61FA2DF203C6000138731EC843AF6BC4/userlog.tmp: open failed: ENOENT (No such file or directory)
02-02 12:53:26.162 14451 14471 E [FMA-myPackage]: 	at libcore.io.IoBridge.open(IoBridge.java:492)
02-02 12:53:26.162 14451 14471 E [FMA-myPackage]: 	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:289)
02-02 12:53:26.162 14451 14471 E [FMA-myPackage]: 	at com.google.firebase.crashlytics.internal.metadata.QueueFile.open(SourceFile:1)
02-02 12:53:26.162 14451 14471 E [FMA-myPackage]: 	at com.google.firebase.crashlytics.internal.metadata.QueueFile.initialize(SourceFile:2)
02-02 12:53:26.162 14451 14471 E [FMA-myPackage]: 	at com.google.firebase.crashlytics.internal.metadata.QueueFile.<init>(SourceFile:4)
02-02 12:53:26.162 14451 14471 E [FMA-myPackage]: 	at com.google.firebase.crashlytics.internal.metadata.QueueFileLogStore.openLogFile(SourceFile:2)
02-02 12:53:26.162 14451 14471 E [FMA-myPackage]: 	at com.google.firebase.crashlytics.internal.metadata.QueueFileLogStore.writeToLog(SourceFile:1)
02-02 12:53:26.162 14451 14471 E [FMA-myPackage]: 	at com.google.firebase.crashlytics.internal.metadata.LogFileManager.writeToLog(SourceFile:1)
02-02 12:53:26.162 14451 14471 E [FMA-myPackage]: 	at com.google.firebase.crashlytics.internal.common.CrashlyticsController$5.call(SourceFile:3)
02-02 12:53:26.162 14451 14471 E [FMA-myPackage]: 	at com.google.firebase.crashlytics.internal.common.CrashlyticsController$5.call(SourceFile:1)
02-02 12:53:26.162 14451 14471 E [FMA-myPackage]: 	at com.google.firebase.crashlytics.internal.common.CrashlyticsBackgroundWorker$3.then(SourceFile:1)
02-02 12:53:26.162 14451 14471 E [FMA-myPackage]: 	at com.google.android.gms.tasks.w.run(SourceFile:3)
02-02 12:53:26.162 14451 14471 E [FMA-myPackage]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
02-02 12:53:26.162 14451 14471 E [FMA-myPackage]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
02-02 12:53:26.162 14451 14471 E [FMA-myPackage]: 	at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(SourceFile:1)
02-02 12:53:26.162 14451 14471 E [FMA-myPackage]: 	at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(SourceFile:2)
02-02 12:53:26.162 14451 14471 E [FMA-myPackage]: 	at java.lang.Thread.run(Thread.java:923)
02-02 12:53:26.162 14451 14471 E [FMA-myPackage]: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
02-02 12:53:26.162 14451 14471 E [FMA-myPackage]: 	at libcore.io.Linux.open(Native Method)
02-02 12:53:26.162 14451 14471 E [FMA-myPackage]: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
02-02 12:53:26.162 14451 14471 E [FMA-myPackage]: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
02-02 12:53:26.162 14451 14471 E [FMA-myPackage]: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
02-02 12:53:26.162 14451 14471 E [FMA-myPackage]: 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7542)
02-02 12:53:26.162 14451 14471 E [FMA-myPackage]: 	at libcore.io.IoBridge.open(IoBridge.java:478)
02-02 12:53:26.162 14451 14471 E [FMA-myPackage]: 	... 16 more
02-02 12:53:26.169  1460  1493 D EventSequenceValidator: Transition from ACTIVITY_LAUNCHED to ACTIVITY_FINISHED
```

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

Test with Crashlytics version 18.2.5 and higher on a Xiaomi device or any other device.

Firebase is setup to run in more than one process. 

#### Relevant Code:
Logs are attached above.

```
Initialize Firebase using FirebaseApp.initializeApp(this); in the application OnCreate

```

**Comment by argzdev** [comment]
Hi @sarinregmi, thanks for the report and sorry for the late response. I tried reproducing this issue using a clean project with Kotlin, however I'm unable to encounter the same result. Is this issue always reproducible? Could you share an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example)? It'll greatly help our investigation. Thanks!
