### ISSUE TITLE
Your client does not have permission to get URL - signupNewUser

### ISSUE THREAD

**Issue by Monabr** [firebase/firebase-android-sdk#3529]
### Describe your environment

  * Android Studio version: Android Studio Bumblebee | 2021.1.1 Patch 2
  * Firebase Component: Firebase Auth
  * Component version: 21.0.1

### Describe the problem

On some devises after calling method `Firebase.auth.signInAnonymously()` the users get the error: `Your client does not have permission to get URL /identitytoolkit/v3/relyingparty/signupNewUser from this server. `

#### Steps to reproduce:

Call `Firebase.auth.signInAnonymously()`

Output log:

```
Non-fatal Exception: dr0: An internal error has occurred. [ Json conversion failed! Failed to parse error for string [<!DOCTYPE html><html lang=en>  <meta charset=utf-8>  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">  <title>Error 403 (Forbidden)!!1</title>  <style>    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}  </style>  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>  <p><b>403.</b> <ins>That’s an error.</ins>  <p>Your client does not have permission to get URL <code>/identitytoolkit/v3/relyingparty/signupNewUser</code> from this server.  <ins>That’s all we know.</ins>] ]
       at com.google.android.gms.internal.firebase-auth-api.zzto.zza(zzto.java:151)
       at com.google.android.gms.internal.firebase-auth-api.zzuw.zza(zzuw.java:88)
       at com.google.android.gms.internal.firebase-auth-api.zzux.zzl(zzux.java:8)
       at com.google.android.gms.internal.firebase-auth-api.zzuu.zzk(zzuu.java:196)
       at com.google.android.gms.internal.firebase-auth-api.zztl.zzh(zztl.java:2)
       at com.google.android.gms.internal.firebase-auth-api.zzpn.zza(zzpn.java:6)
       at com.google.android.gms.internal.firebase-auth-api.zzvb.zza(zzvb.java:173)
       at com.google.android.gms.internal.firebase-auth-api.zzul.zzn(zzul.java:20)
       at com.google.android.gms.internal.firebase-auth-api.zzpt.zzz(zzpt.java:15)
       at com.google.android.gms.internal.firebase-auth-api.zztp.zzu(zztp.java:19)
       at com.google.android.gms.internal.firebase-auth-api.zzrz.zzd(zzrz.java:15)
       at com.google.android.gms.internal.firebase-auth-api.zzry.accept(zzry.java:6)
       at com.google.android.gms.common.api.internal.zacv.doExecute(zacv.java:6)
       at com.google.android.gms.common.api.internal.zag.zaf(zag.java:8)
       at com.google.android.gms.common.api.internal.zabq.zaJ(zabq.java:9)
       at com.google.android.gms.common.api.internal.zabq.zaL(zabq.java:22)
       at com.google.android.gms.common.api.internal.zabq.zap(zabq.java:17)
       at com.google.android.gms.common.api.internal.GoogleApiManager.handleMessage(GoogleApiManager.java:664)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:246)
       at android.os.HandlerThread.run(HandlerThread.java:67)
```

#### Relevant Code:

```
Firebase.auth.signInAnonymously()
```

**Comment by argzdev** [comment]
Hi @Monabr, thanks for reporting. Could you answer some of our questions:
1. Is this issue only experienced on specific devices or Android versions?
2. Could you provide some device brand that experiences this issue? 
3. Is this issue consistent on every run?

These details will help us investigate this issue deeper, thanks!

**Comment by argzdev** [comment]
Hi @Monabr, thanks for the extra details. Is your R8 enabled? This issue looks similar to #2124. Could you try the solution provided there and see if that works? Thanks!

**Comment by argzdev** [comment]
Since this issue has been stale for quite a while, I'll be closing this for now. Feel free to reopen if you have further information about the case. Thanks!
