### ISSUE TITLE
RuntimeException: Uncaught exception in Firebase Database runloop (20.0.2)

### ISSUE THREAD

**Issue by devduttnetsutra** [firebase/firebase-android-sdk#3530]
Already updated Firebase , Kotlin , Gradle visions.

Fatal Exception: java.lang.RuntimeException: Uncaught exception in Firebase Database runloop (20.0.2). If you are not already on the latest version of the Firebase SDKs, try updating your dependencies. Should this problem persist, please file a report at https://github.com/firebase/firebase-android-sdk
       at com.google.firebase.database.android.AndroidPlatform$1$1.run(AndroidPlatform.java:96)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8633)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

Caused by java.lang.NoSuchMethodError: No virtual method object()Lorg/json/e; in class Lorg/json/e; or its super classes (declaration of 'org.json.e' appears in base.apk)
       at com.google.firebase.database.util.JsonMapper.serializeJsonValue(JsonMapper.java:69)
       at com.google.firebase.database.util.JsonMapper.serializeJsonValue(JsonMapper.java:58)
       at com.google.firebase.database.util.JsonMapper.serializeJson(JsonMapper.java:38)
       at com.google.firebase.database.connection.WebsocketConnection.send(WebsocketConnection.java:234)
       at com.google.firebase.database.connection.Connection.sendData(Connection.java:246)
       at com.google.firebase.database.connection.Connection.sendRequest(Connection.java:120)
       at com.google.firebase.database.connection.PersistentConnectionImpl.sendSensitive(PersistentConnectionImpl.java:1450)
       at com.google.firebase.database.connection.PersistentConnectionImpl.sendAction(PersistentConnectionImpl.java:1437)
       at com.google.firebase.database.connection.PersistentConnectionImpl.sendStats(PersistentConnectionImpl.java:1389)
       at com.google.firebase.database.connection.PersistentConnectionImpl.sendConnectStats(PersistentConnectionImpl.java:1432)
       at com.google.firebase.database.connection.PersistentConnectionImpl.onReady(PersistentConnectionImpl.java:366)
       at com.google.firebase.database.connection.Connection.onConnectionReady(Connection.java:220)
       at com.google.firebase.database.connection.Connection.onHandshake(Connection.java:213)
       at com.google.firebase.database.connection.Connection.onControlMessage(Connection.java:185)
       at com.google.firebase.database.connection.Connection.onMessage(Connection.java:135)
       at com.google.firebase.database.connection.WebsocketConnection.appendFrame(WebsocketConnection.java:259)
       at com.google.firebase.database.connection.WebsocketConnection.handleIncomingFrame(WebsocketConnection.java:306)
       at com.google.firebase.database.connection.WebsocketConnection.access$500(WebsocketConnection.java:34)
       at com.google.firebase.database.connection.WebsocketConnection$WSClientTubesock$2.run(WebsocketConnection.java:86)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)

**Comment by argzdev** [comment]
Hi @davideast, thanks for reporting. Could you open a new issue with the necessary details in the template? The template contains the details such as what Firebase products did you use, and what steps did you do to encounter the issue. This is so that we can investigate or simulate the issue properly. That being said, I'll be closing this now. Thanks!
