### ISSUE TITLE
IPC(InterProcess Communication) Injection protection

### ISSUE THREAD

**Issue by klightshadow** [firebase/firebase-android-sdk#3538]
### Describe your environment

  * Android Studio version:  Android Studio Bumblebee | 2021.1.1 Patch 2
  * Firebase Component: messaging
  * Component version: firebase-bom:29.2.0
  * Android version: Android 10 below
  * Jetpack compose

### Describe the problem
RuntimeException: Parcelable encountered ClassNotFoundException reading a Serializable object

#### Steps to reproduce:

I tried to use IntentFuzzer(https://github.com/MindMac/IntentFuzzer) to test my app's IPC injection protection.
I got a RuntimeException after IntentFuzzer click Serialize Fuzz All, and the log shows something like below

`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.cathaysiteonline/androidx.compose.ui.tooling.PreviewActivity}: java.lang.RuntimeException: Parcelable encountered ClassNotFoundException reading a Serializable object (name = com.android.intentfuzzer.util.SerializableTest)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.RuntimeException: Parcelable encountered ClassNotFoundException reading a Serializable object (name = com.android.intentfuzzer.util.SerializableTest)
        at android.os.Parcel.readSerializable(Parcel.java:3140)
        at android.os.Parcel.readValue(Parcel.java:2917)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3244)
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
        at android.os.BaseBundle.unparcel(BaseBundle.java:236)
        at android.os.Bundle.getBundle(Bundle.java:924)
        **at com.google.firebase.messaging.FcmLifecycleCallbacks.logNotificationOpen(FcmLifecycleCallbacks.java:79)**
        at com.google.firebase.messaging.FcmLifecycleCallbacks.onActivityCreated(FcmLifecycleCallbacks.java:49)
        at android.app.Application.dispatchActivityCreated(Application.java:373)
        at android.app.Activity.dispatchActivityCreated(Activity.java:1202)
        at android.app.Activity.onCreate(Activity.java:1475)
        at androidx.core.app.ComponentActivity.onCreate(ComponentActivity.java:85)
        at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:314)
        at androidx.compose.ui.tooling.PreviewActivity.onCreate(PreviewActivity.kt:51)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) `

**Comment by gsakakihara** [comment]
This doesn't look like it's related to https://github.com/firebase/firebase-android-sdk/issues/3526, it's looks like it may be due to the update to handle Android S's notification trampoline restrictions added in version 22.0.0.

**Comment by argzdev** [comment]
Thanks for confirming, @gsakakihara. Since this issue has now been merged, I'll be closing this issue now. 

Feel free to add any follow up questions you might have, @klightshadow. I can't promise a timeline when that is, but you may keep an eye out on our [release notes](https://firebase.google.com/support/releases) and [official blog](https://firebase.googleblog.com/) from time to time to check out the latest features and bug fixes. Thanks!
