### ISSUE TITLE
Adding a Uri to the database fails with a non-descriptive message

### ISSUE THREAD

**Issue by paulsmithkc** [firebase/firebase-android-sdk#3611]
#### My environment

  * Android Studio version: 2020.3.1 Patch 4
  * Firebase Component: Firestore
  * Component version: com.google.firebase:firebase-bom:29.1.0

#### Steps to reproduce:

The following code results in a non-helpful message because `com.google.firebase.firestore.util.CustomClassMapper.BeanMapper.serialize()` is unable to serialize `Uri` objects.

```java
FirebaseFirestore db = FirebaseFirestore.getInstance();
FirebaseUser user = FirebaseAuth.getInstance().getCurrentUser();

HashMap<String, Object> data = new HashMap<>();
data.put("profileImage", user.getPhotoUrl());  // user.getPhotoUrl() returns a Uri object

db.collection("users").document(user.getUid()).set(data, SetOptions.merge());
```

The resulting stack trace is as shown below. The stack trace would indicate that the mapper is also getting into an infinite loop here. Instead of this error, I would expect it to simply call `.toString()` on the Uri and store it in the database as a string.

#### Relevant Code:

```java
FirebaseFirestore db = FirebaseFirestore.getInstance();
FirebaseUser user = FirebaseAuth.getInstance().getCurrentUser();

HashMap<String, Object> data = new HashMap<>();
data.put("profileImage", user.getPhotoUrl());  // user.getPhotoUrl() returns a Uri object

db.collection("users").document(user.getUid()).set(data, SetOptions.merge());
```

#### Stack Trace

```
...
        at com.google.firebase.firestore.util.CustomClassMapper$BeanMapper.serialize(CustomClassMapper.java:902)
        at com.google.firebase.firestore.util.CustomClassMapper.serialize(CustomClassMapper.java:178)
        at com.google.firebase.firestore.util.CustomClassMapper.access$400(CustomClassMapper.java:54)
        at com.google.firebase.firestore.util.CustomClassMapper$BeanMapper.serialize(CustomClassMapper.java:902)
        at com.google.firebase.firestore.util.CustomClassMapper.serialize(CustomClassMapper.java:178)
        at com.google.firebase.firestore.util.CustomClassMapper.access$400(CustomClassMapper.java:54)
        at com.google.firebase.firestore.util.CustomClassMapper$BeanMapper.serialize(CustomClassMapper.java:902)
        at com.google.firebase.firestore.util.CustomClassMapper.serialize(CustomClassMapper.java:178)
        at com.google.firebase.firestore.util.CustomClassMapper.access$400(CustomClassMapper.java:54)
        at com.google.firebase.firestore.util.CustomClassMapper$BeanMapper.serialize(CustomClassMapper.java:902)
        at com.google.firebase.firestore.util.CustomClassMapper.serialize(CustomClassMapper.java:178)
        at com.google.firebase.firestore.util.CustomClassMapper.access$400(CustomClassMapper.java:54)
        at com.google.firebase.firestore.util.CustomClassMapper$BeanMapper.serialize(CustomClassMapper.java:902)
        at com.google.firebase.firestore.util.CustomClassMapper.serialize(CustomClassMapper.java:178)
        at com.google.firebase.firestore.util.CustomClassMapper.access$400(CustomClassMapper.java:54)
        at com.google.firebase.firestore.util.CustomClassMapper$BeanMapper.serialize(CustomClassMapper.java:902)
        at com.google.firebase.firestore.util.CustomClassMapper.serialize(CustomClassMapper.java:178)
        at com.google.firebase.firestore.util.CustomClassMapper.access$400(CustomClassMapper.java:54)
        at com.google.firebase.firestore.util.CustomClassMapper$BeanMapper.serialize(CustomClassMapper.java:902)
        at com.google.firebase.firestore.util.CustomClassMapper.serialize(CustomClassMapper.java:178)
        at com.google.firebase.firestore.util.CustomClassMapper.access$400(CustomClassMapper.java:54)
        at com.google.firebase.firestore.util.CustomClassMapper$BeanMapper.serialize(CustomClassMapper.java:902)
        at com.google.firebase.firestore.util.CustomClassMapper.serialize(CustomClassMapper.java:178)
        at com.google.firebase.firestore.util.CustomClassMapper.access$400(CustomClassMapper.java:54)
        at com.google.firebase.firestore.util.CustomClassMapper$BeanMapper.serialize(CustomClassMapper.java:902)
        at com.google.firebase.firestore.util.CustomClassMapper.serialize(CustomClassMapper.java:178)
        at com.google.firebase.firestore.util.CustomClassMapper.access$400(CustomClassMapper.java:54)
        at com.google.firebase.firestore.util.CustomClassMapper$BeanMapper.serialize(CustomClassMapper.java:902)
        at com.google.firebase.firestore.util.CustomClassMapper.serialize(CustomClassMapper.java:178)
        at com.google.firebase.firestore.util.CustomClassMapper.access$400(CustomClassMapper.java:54)
        at com.google.firebase.firestore.util.CustomClassMapper$BeanMapper.serialize(CustomClassMapper.java:902)
        at com.google.firebase.firestore.util.CustomClassMapper.serialize(CustomClassMapper.java:178)
        at com.google.firebase.firestore.util.CustomClassMapper.access$400(CustomClassMapper.java:54)
        at com.google.firebase.firestore.util.CustomClassMapper$BeanMapper.serialize(CustomClassMapper.java:902)
        at com.google.firebase.firestore.util.CustomClassMapper.serialize(CustomClassMapper.java:178)
        at com.google.firebase.firestore.util.CustomClassMapper.access$400(CustomClassMapper.java:54)
        at com.google.firebase.firestore.util.CustomClassMapper$BeanMapper.serialize(CustomClassMapper.java:902)
        at com.google.firebase.firestore.util.CustomClassMapper.serialize(CustomClassMapper.java:178)
        at com.google.firebase.firestore.util.CustomClassMapper.access$400(CustomClassMapper.java:54)
        at com.google.firebase.firestore.util.CustomClassMapper$BeanMapper.serialize(CustomClassMapper.java:902)
...
```

**Comment by argzdev** [comment]
Hi @paulsmithkc, thanks for reporting and for the pull request! I was able to repro the issue. That being said, I'll notify an engineer about your fix.

**Comment by schmidt-sebastian** [comment]
This will get released with our next release.
