### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException when firebase installations invoking HttpsURLConnectionImpl.getOutputStream

### ISSUE THREAD

**Issue by ZhuHaiyang127** [firebase/firebase-android-sdk#3615]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.2.2
  * Firebase Component:  crashlytics, analytics
  * Component version: firebase-crashlytics-ktx:18.2.9, firebase-analytics-ktx:20.0.2

### [REQUIRED] Step 3: Describe the problem
a crash happened in our app on one of our user's device [ VIVO X20A  - android 7.1.1 ] and the log is the same as 
issue [https://github.com/firebase/firebase-android-sdk/issues/3251](url) 
since i noticed that you just close issue#3251 without giving any advices or solutions to fix the issue, i do wanna know
if you have  located the problem or produce a fix.

#### Steps to reproduce:

part of the crash log at the time when crash happened below:

04-02 13:08:35.596 22459 30962 E DEBUG   : encryptLog: false, zipCrashLog: false
04-02 13:08:35.596 22459 30962 E DEBUG   : begin to generate java report
04-02 13:08:35.601 22459 30962 E DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-02 13:08:35.605 22459 30962 E DEBUG   : Basic Information: 'pid: 22459/tid: 30962/time: 20220402130835'
04-02 13:08:35.605 22459 30962 E DEBUG   : Cpu Information: 'abi: arm64-v8a,armeabi-v7a,armeabi/processor: AArch64 Processor rev 2 (aarch64)/hardware: Qualcomm Technologies, Inc SDM660'
04-02 13:08:35.605 22459 30962 E DEBUG   : Mobile Information: 'model: vivo X20A/version: 7.1.1/sdk: 25'
04-02 13:08:35.606 22459 30962 E DEBUG   : Build fingerprint: 'vivo/PD1709/PD1709:7.1.1/NMF26X/compil01151136:user/release-keys'
04-02 13:08:35.606 22459 30962 E DEBUG   : Runtime Information: 'start: 20220402125839/maxheap: 536870912/primaryabi: arm64-v8a/ground: fg'
04-02 13:08:35.606 22459 30962 E DEBUG   : Application Information: 'version: 1.9.4/subversion: release/buildseq: 203571df/versioncode: 1174'
04-02 13:08:35.606 22459 30962 E DEBUG   : CrashSDK Information: 'version: 3.2.0.4/nativeseq: 210105150455/javaseq: 210105150455/arch: arm64-v8a/target: release'
04-02 13:08:35.606 22459 30962 E DEBUG   : Report Name: 609295f653b6726499e9c19e_1.9.4_203571df_vivo-X20A_7.1.1_164887551997411298_20220402130835_fg_java.log
04-02 13:08:35.609 22459 30962 E DEBUG   : UUID: 302f0d53-19ba-4bd6-9374-980bd37b5d77
04-02 13:08:35.610 22459 30962 E DEBUG   : Log Type: java
04-02 13:08:35.610 22459 30962 E DEBUG   : Activity: com.legan.browser/.MainActivity
04-02 13:08:35.610 22459 30962 E DEBUG   : --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
04-02 13:08:35.610 22459 30962 E DEBUG   : um_app_key: 609295f653b6726499e9c19e
04-02 13:08:35.610 22459 30962 E DEBUG   : um_app_channel: vivo
04-02 13:08:35.610 22459 30962 E DEBUG   : um_os: android
04-02 13:08:35.610 22459 30962 E DEBUG   : um_crash_sdk_version: 1.3.1
04-02 13:08:35.610 22459 30962 E DEBUG   : um_umid_header: b84fdba06d2ffd727dfcf0ffae403d66
04-02 13:08:35.610 22459 30962 E DEBUG   : um_app_carrier: 
04-02 13:08:35.610 22459 30962 E DEBUG   : um_access: wifi
04-02 13:08:35.610 22459 30962 E DEBUG   : um_network_type: 0
04-02 13:08:35.610 22459 30962 E DEBUG   : --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
04-02 13:08:35.610 22459 30962 E DEBUG   : Process Name: 'com.legan.browser'
04-02 13:08:35.611 22459 30962 E DEBUG   : Thread Name: 'firebase-installations-executor-7'
04-02 13:08:35.611 22459 30962 E DEBUG   : Back traces starts.
04-02 13:08:35.611 22459 30962 E DEBUG   : java.lang.ArrayIndexOutOfBoundsException: length=8192; index=8192
04-02 13:08:35.612 22459 30962 E DEBUG   : 	at com.android.okhttp.okio.Buffer.writeByte(Buffer.java:973)
04-02 13:08:35.612 22459 30962 E DEBUG   : 	at com.android.okhttp.internal.Platform.concatLengthPrefixed(Platform.java:130)
04-02 13:08:35.612 22459 30962 E DEBUG   : 	at com.android.okhttp.internal.Platform.configureTlsExtensions(Platform.java:84)
04-02 13:08:35.612 22459 30962 E DEBUG   : 	at com.android.okhttp.Connection.connectTls(Connection.java:230)
04-02 13:08:35.612 22459 30962 E DEBUG   : 	at com.android.okhttp.Connection.connectSocket(Connection.java:199)
04-02 13:08:35.612 22459 30962 E DEBUG   : 	at com.android.okhttp.Connection.connect(Connection.java:172)
04-02 13:08:35.612 22459 30962 E DEBUG   : 	at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
04-02 13:08:35.613 22459 30962 E DEBUG   : 	at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
04-02 13:08:35.613 22459 30962 E DEBUG   : 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
04-02 13:08:35.613 22459 30962 E DEBUG   : 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:247)
04-02 13:08:35.613 22459 30962 E DEBUG   : 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
04-02 13:08:35.613 22459 30962 E DEBUG   : 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:126)
04-02 13:08:35.613 22459 30962 E DEBUG   : 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:257)
04-02 13:08:35.613 22459 30962 E DEBUG   : 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
04-02 13:08:35.613 22459 30962 E DEBUG   : 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java)
04-02 13:08:35.613 22459 30962 E DEBUG   : 	at com.google.firebase.installations.m.c.s(SourceFile:1)
04-02 13:08:35.614 22459 30962 E DEBUG   : 	at com.google.firebase.installations.m.c.q(SourceFile:2)
04-02 13:08:35.614 22459 30962 E DEBUG   : 	at com.google.firebase.installations.m.c.d(SourceFile:9)
04-02 13:08:35.614 22459 30962 E DEBUG   : 	at com.google.firebase.installations.e.u(SourceFile:9)
04-02 13:08:35.614 22459 30962 E DEBUG   : 	at com.google.firebase.installations.e.c(SourceFile:5)
04-02 13:08:35.614 22459 30962 E DEBUG   : 	at com.google.firebase.installations.e.o(SourceFile:1)
04-02 13:08:35.614 22459 30962 E DEBUG   : 	at com.google.firebase.installations.e.p(SourceFile)
04-02 13:08:35.614 22459 30962 E DEBUG   : 	at com.google.firebase.installations.a.run(SourceFile)
04-02 13:08:35.614 22459 30962 E DEBUG   : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
04-02 13:08:35.614 22459 30962 E DEBUG   : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
04-02 13:08:35.615 22459 30962 E DEBUG   : 	at java.lang.Thread.run(Thread.java:762)
04-02 13:08:35.615 22459 30962 E DEBUG   : Back traces ends.
04-02 13:08:35.615 22459 30962 E DEBUG   : --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
04-02 13:08:35.615 22459 30962 E DEBUG   : meminfo:
04-02 13:08:35.615 22459 30962 E DEBUG   : MemTotal:        3823368 kB
04-02 13:08:35.615 22459 30962 E DEBUG   : MemFree:          144916 kB
04-02 13:08:35.615 22459 30962 E DEBUG   : MemAvailable:    1244340 kB
04-02 13:08:35.615 22459 30962 E DEBUG   : Buffers:           40240 kB
04-02 13:08:35.615 22459 30962 E DEBUG   : Cached:          1112636 kB
04-02 13:08:35.615 22459 30962 E DEBUG   : SwapCached:         6572 kB
04-02 13:08:35.615 22459 30962 E DEBUG   : Active:          1318872 kB
04-02 13:08:35.615 22459 30962 E DEBUG   : Inactive:        1382644 kB
04-02 13:08:35.615 22459 30962 E DEBUG   : Active(anon):     730040 kB
04-02 13:08:35.615 22459 30962 E DEBUG   : Inactive(anon):   832884 kB
04-02 13:08:35.615 22459 30962 E DEBUG   : Active(file):     588832 kB
04-02 13:08:35.615 22459 30962 E DEBUG   : Inactive(file):   549760 kB
04-02 13:08:35.615 22459 30962 E DEBUG   : Unevictable:         124 kB
04-02 13:08:35.615 22459 30962 E DEBUG   : Mlocked:             124 kB
04-02 13:08:35.615 22459 30962 E DEBUG   : SwapTotal:        524284 kB
04-02 13:08:35.615 22459 30962 E DEBUG   : SwapFree:          98656 kB
04-02 13:08:35.615 22459 30962 E DEBUG   : Dirty:               320 kB
04-02 13:08:35.615 22459 30962 E DEBUG   : Writeback:             0 kB
04-02 13:08:35.615 22459 30962 E DEBUG   : AnonPages:       1543072 kB
04-02 13:08:35.615 22459 30962 E DEBUG   : Mapped:           459160 kB
04-02 13:08:35.615 22459 30962 E DEBUG   : Shmem:             14272 kB
04-02 13:08:35.615 22459 30962 E DEBUG   : Slab:             219180 kB
04-02 13:08:35.615 22459 30962 E DEBUG   : SReclaimable:      67596 kB
04-02 13:08:35.615 22459 30962 E DEBUG   : SUnreclaim:       151584 kB
04-02 13:08:35.615 22459 30962 E DEBUG   : KernelStack:       54960 kB
04-02 13:08:35.615 22459 30962 E DEBUG   : PageTables:        75164 kB
04-02 13:08:35.615 22459 30962 E DEBUG   : NFS_Unstable:          0 kB
04-02 13:08:35.615 22459 30962 E DEBUG   : Bounce:                0 kB
04-02 13:08:35.615 22459 30962 E DEBUG   : WritebackTmp:          0 kB
04-02 13:08:35.615 22459 30962 E DEBUG   : CommitLimit:     2435968 kB
04-02 13:08:35.615 22459 30962 E DEBUG   : Committed_AS:   124811024 kB
04-02 13:08:35.615 22459 30962 E DEBUG   : VmallocTotal:   258867136 kB
04-02 13:08:35.615 22459 30962 E DEBUG   : VmallocUsed:           0 kB
04-02 13:08:35.615 22459 30962 E DEBUG   : VmallocChunk:          0 kB
04-02 13:08:35.615 22459 30962 E DEBUG   : CmaTotal:         176128 kB
04-02 13:08:35.615 22459 30962 E DEBUG   : CmaFree:             440 kB
04-02 13:08:35.616 22459 30962 E DEBUG   : --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
04-02 13:08:35.616 22459 30962 E DEBUG   : status:
04-02 13:08:35.616 22459 30962 E DEBUG   : Name:	m.legan.browser
04-02 13:08:35.616 22459 30962 E DEBUG   : State:	S (sleeping)
04-02 13:08:35.616 22459 30962 E DEBUG   : Tgid:	22459
04-02 13:08:35.616 22459 30962 E DEBUG   : Pid:	22459
04-02 13:08:35.616 22459 30962 E DEBUG   : PPid:	912
04-02 13:08:35.616 22459 30962 E DEBUG   : TracerPid:	0
04-02 13:08:35.616 22459 30962 E DEBUG   : Uid:	12781	12781	12781	12781
04-02 13:08:35.616 22459 30962 E DEBUG   : Gid:	12781	12781	12781	12781
04-02 13:08:35.616 22459 30962 E DEBUG   : Ngid:	0
04-02 13:08:35.616 22459 30962 E DEBUG   : FDSize:	512
04-02 13:08:35.616 22459 30962 E DEBUG   : Groups:	3003 9997 52781 99909997 
04-02 13:08:35.616 22459 30962 E DEBUG   : VmPeak:	11254312 kB
04-02 13:08:35.616 22459 30962 E DEBUG   : VmSize:	 7112536 kB
04-02 13:08:35.616 22459 30962 E DEBUG   : VmLck:	       0 kB
04-02 13:08:35.616 22459 30962 E DEBUG   : VmPin:	       0 kB
04-02 13:08:35.616 22459 30962 E DEBUG   : VmHWM:	  476008 kB
04-02 13:08:35.616 22459 30962 E DEBUG   : VmRSS:	  349228 kB
04-02 13:08:35.616 22459 30962 E DEBUG   : VmData:	 4675812 kB
04-02 13:08:35.616 22459 30962 E DEBUG   : VmStk:	    8196 kB
04-02 13:08:35.616 22459 30962 E DEBUG   : VmExe:	      20 kB
04-02 13:08:35.616 22459 30962 E DEBUG   : VmLib:	  260148 kB
04-02 13:08:35.616 22459 30962 E DEBUG   : VmPTE:	    2360 kB
04-02 13:08:35.616 22459 30962 E DEBUG   : VmPMD:	      36 kB
04-02 13:08:35.616 22459 30962 E DEBUG   : VmSwap:	   12552 kB
04-02 13:08:35.616 22459 30962 E DEBUG   : Threads:	133
04-02 13:08:35.616 22459 30962 E DEBUG   : SigQ:	0/14077
04-02 13:08:35.616 22459 30962 E DEBUG   : SigPnd:	0000000000000000
04-02 13:08:35.616 22459 30962 E DEBUG   : ShdPnd:	0000000000000000
04-02 13:08:35.616 22459 30962 E DEBUG   : SigBlk:	0000000000001200
04-02 13:08:35.616 22459 30962 E DEBUG   : SigIgn:	0000000000000000
04-02 13:08:35.616 22459 30962 E DEBUG   : SigCgt:	200000024000dcfe
04-02 13:08:35.616 22459 30962 E DEBUG   : CapInh:	0000000000000000
04-02 13:08:35.616 22459 30962 E DEBUG   : CapPrm:	0000000000000000
04-02 13:08:35.616 22459 30962 E DEBUG   : CapEff:	0000000000000000
04-02 13:08:35.616 22459 30962 E DEBUG   : CapBnd:	0000000000000000
04-02 13:08:35.616 22459 30962 E DEBUG   : CapAmb:	0000000000000000
04-02 13:08:35.616 22459 30962 E DEBUG   : Seccomp:	0
04-02 13:08:35.616 22459 30962 E DEBUG   : Cpus_allowed:	ff
04-02 13:08:35.616 22459 30962 E DEBUG   : Cpus_allowed_list:	0-7
04-02 13:08:35.616 22459 30962 E DEBUG   : Mems_allowed:	1
04-02 13:08:35.616 22459 30962 E DEBUG   : Mems_allowed_list:	0
04-02 13:08:35.616 22459 30962 E DEBUG   : voluntary_ctxt_switches:	64187
04-02 13:08:35.616 22459 30962 E DEBUG   : nonvoluntary_ctxt_switches:	35884
04-02 13:08:35.616 22459 30962 E DEBUG   : --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
04-02 13:08:35.617 22459 30962 E DEBUG   : memory info:
04-02 13:08:35.617 22459 30962 E DEBUG   : JavaMax:    524288 kB
04-02 13:08:35.617 22459 30962 E DEBUG   : JavaTotal:  23884 kB
04-02 13:08:35.617 22459 30962 E DEBUG   : JavaFree:   7690 kB
04-02 13:08:35.617 22459 30962 E DEBUG   : NativeHeap: 153600 kB
04-02 13:08:35.617 22459 30962 E DEBUG   : NativeAllocated: 95887 kB
04-02 13:08:35.617 22459 30962 E DEBUG   : NativeFree: 57712 kB
04-02 13:08:35.617 22459 30962 E DEBUG   : availMem:   1257548 kB
04-02 13:08:35.617 22459 30962 E DEBUG   : threshold:  221184 kB
04-02 13:08:35.617 22459 30962 E DEBUG   : lowMemory:  false
04-02 13:08:35.618 22459 30962 E DEBUG   : --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
04-02 13:08:35.618 22459 30962 E DEBUG   : recent status:
04-02 13:08:35.618 22459 30962 E DEBUG   : last version: '1.9.4/release/203571df'
04-02 13:08:35.618 22459 30962 E DEBUG   : dumping all threads: false
04-02 13:08:35.618 22459 30962 E DEBUG   : --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
04-02 13:08:35.618 22459 30962 E DEBUG   : logcat:
04-02 13:08:35.686   698   816 W SurfaceFlinger: eventControl: set enabled=0
04-02 13:08:35.695 22459 30962 E DEBUG   : --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
04-02 13:08:35.695 22459 30962 E DEBUG   : battery info:
04-02 13:08:35.695 22459 30962 E DEBUG   : level: 52
04-02 13:08:35.695 22459 30962 E DEBUG   : scale: 100
04-02 13:08:35.695 22459 30962 E DEBUG   : health: 2 (Good)
04-02 13:08:35.695 22459 30962 E DEBUG   : pluged: 2 (USB port)
04-02 13:08:35.695 22459 30962 E DEBUG   : status: 2 (Charging)
04-02 13:08:35.695 22459 30962 E DEBUG   : voltage: 3933
04-02 13:08:35.695 22459 30962 E DEBUG   : temperature: 300
04-02 13:08:35.695 22459 30962 E DEBUG   : technology: Li-ion
04-02 13:08:35.695 22459 30962 E DEBUG   : battery low: false
04-02 13:08:35.695 22459 30962 E DEBUG   : --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
04-02 13:08:35.695 22459 30962 E DEBUG   : disk info:
04-02 13:08:35.696  8766  9119 D MockGpsService: set mock continue
04-02 13:08:35.697  1807  1848 I LocationManagerService: --handleMessage 1
04-02 13:08:35.697 22459 30962 E DEBUG   : /data/data/com.legan.browser:
04-02 13:08:35.697 22459 30962 E DEBUG   :   total:      53833160 kB
04-02 13:08:35.697  1807  1848 I LocationManagerService: handleLocationChanged location:Location[network 27.489230,109.896225 acc=2 et=+52m49s603ms alt=55.0 bear=1.0 mock {Bundle[mParcelledData.dataSize=40]}] passive:false
04-02 13:08:35.698 22459 30962 E DEBUG   :   available:  18520032 kB
04-02 13:08:35.698 22459 30962 E DEBUG   :   free:       18536416 kB
04-02 13:08:35.698 22459 30962 E DEBUG   :   block size: 4096 B
04-02 13:08:35.698 22459 30962 E DEBUG   : 
04-02 13:08:35.698 22459 30962 E DEBUG   : --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
04-02 13:08:35.698  1807  1848 D LocationManagerService: incoming location: Location[network 27.489230,109.896225 acc=2 et=+52m49s603ms alt=55.0 bear=1.0 mock {Bundle[mParcelledData.dataSize=40]}] passive:false
04-02 13:08:35.698 22459 30962 E DEBUG   : device status:
04-02 13:08:35.698  1807  1848 I LocationManagerService: --handleMessage 1
04-02 13:08:35.698 22459 30962 E DEBUG   : has root: false
04-02 13:08:35.698 22459 30962 E DEBUG   : build tags: release-keys
04-02 13:08:35.698 22459 30962 E DEBUG   : --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---

#### Relevant Code:

i can't not offer much relevant code about this, since i only import crashlytics, analytics libs and then adding some logs with the code: firebaseCrashlytics.log(msg). then i publish our app to some users, then i saw the crash log on Crashlytics platform.

hope you can't help me with this issue and looking forward to your reply.

**Comment by ZhuHaiyang127** [comment]
> 

1.  i can't reproduce this issue on my 3 devices,  and it's not consistently reproducible. i just found it in crashlytics dashboard. 
2.  yes,  only reported on android 7.1.1 devices
3.  yes,  i only import Crashlytics and Analytics for crash and error tracing
4.  it's the first time we're using Crashlytics, and it's the 1st version of our app published  with Crashlytics inside

plz know, thx and looks forward to your reply.

**Comment by argzdev** [comment]
Thanks for the details, @ZhuHaiyang127. Upon investigating, it looks like the issue is being thrown within [here](https://github.com/firebase/firebase-android-sdk/blob/1f258016757ef6040de24ef89764252a6afb3549/firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java#L273-L277) - Firebase Installations when `writeRequestBodyToOutputStream` is being called from `writeGenerateAuthTokenRequestBodyToOutputStream`. I'm guessing this method is called during generation of the auth token. 

Unfortunately, I'm unable to reproduce this issue as well. For now, let's keep this issue open in case our engineers might have an idea how to fix this.

**Comment by lisajian** [comment]
Hi, thanks for filing this issue! We are unable to promise any timeline for this, but if others also have this issue, adding a +1 on this issue can help us prioritize adding this to the roadmap.

(Googler-only internal tracking bug: [b/228976978](https://b.corp.google.com/issues/228976978))

**Comment by lehcar09** [comment]
Hi @ZhuHaiyang127, sorry for the silence here. Just wanted to check if you're still observing this issue in the latest Firebase SDK version?
