### ISSUE TITLE
Firebase Auth crashes with NullPointerException on at least Android 12

### ISSUE THREAD

**Issue by hnljp** [firebase/firebase-android-sdk#3626]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version:
Android Studio Bumblebee | 2021.1.1 Patch 2
Build #AI-211.7628.21.2111.8193401, built on February 17, 2022
Runtime version: 11.0.11+0-b60-7590822 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: wu.seal.tool.jsontokotlin (3.7.2), com.thoughtworks.gauge (211.6693.111), org.jetbrains.kotlin (211-1.6.20-release-275-AS7442.40), org.intellij.plugins.markdown (211.7142.37)

  * Firebase Component: Auth
  * Component version: 21.0.3
Using BoM: 29.3.0

### [REQUIRED] Step 3: Describe the problem
I am getting the following crashes, once in a while.
It is most likely related to https://github.com/firebase/firebase-android-sdk/issues/3617 is it is about half/half if it is the NullPointerException or the OutOfMemoryError that is happening.

I have so far only tested it on a Pixel 5 with Android 12 (S3B1.220218.004).

It is happening either while getting a fresh token or signing in anonymously. I hope that you are able to get more information from the crash, that I am able to get.

Fatal Exception: java.lang.NullPointerException: Attempt to get length of null array
       at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:248)
       at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:241)
       at java.util.ArrayList.add(ArrayList.java:467)
       at com.google.firebase.auth.internal.zzx.zzc(com.google.firebase:firebase-auth@@21.0.3:10)
       at com.google.firebase.auth.FirebaseAuth.zzH(com.google.firebase:firebase-auth@@21.0.3:8)
       at com.google.firebase.auth.zzo.zza(com.google.firebase:firebase-auth@@21.0.3:1)
       at com.google.android.gms.internal.firebase-auth-api.zzrv.zzb(com.google.firebase:firebase-auth@@21.0.3:3)
       at com.google.android.gms.internal.firebase-auth-api.zzuh.zzj(com.google.firebase:firebase-auth@@21.0.3:1)
       at com.google.android.gms.internal.firebase-auth-api.zzue.zzn(com.google.firebase:firebase-auth@@21.0.3:2)
       at com.google.android.gms.internal.firebase-auth-api.zztg.zzn(com.google.firebase:firebase-auth@@21.0.3:1)
       at com.google.android.gms.internal.firebase-auth-api.zzqe.zzb(com.google.firebase:firebase-auth@@21.0.3:2)
       at com.google.android.gms.internal.firebase-auth-api.zzup.zza(com.google.firebase:firebase-auth@@21.0.3:24)
       at com.google.android.gms.internal.firebase-auth-api.zztv.zzf(com.google.firebase:firebase-auth@@21.0.3:4)
       at com.google.android.gms.internal.firebase-auth-api.zzrl.zzp(com.google.firebase:firebase-auth@@21.0.3:4)
       at com.google.android.gms.internal.firebase-auth-api.zzth.zzj(com.google.firebase:firebase-auth@@21.0.3:5)
       at com.google.android.gms.internal.firebase-auth-api.zzrv.zzc(com.google.firebase:firebase-auth@@21.0.3:1)
       at com.google.android.gms.internal.firebase-auth-api.zzui.run(com.google.firebase:firebase-auth@@21.0.3:1)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:920)

Just as an information, at the same time, Firebase Auth in running this in another thread:
pool-16-thread-5
       at java.util.ArrayList.add(ArrayList.java:467)
       at com.google.firebase.auth.internal.zzx.zzc(com.google.firebase:firebase-auth@@21.0.3:10)
       at com.google.firebase.auth.FirebaseAuth.zzH(com.google.firebase:firebase-auth@@21.0.3:8)
       at com.google.firebase.auth.zzo.zza(com.google.firebase:firebase-auth@@21.0.3:1)
       at com.google.android.gms.internal.firebase-auth-api.zzrv.zzb(com.google.firebase:firebase-auth@@21.0.3:3)
       at com.google.android.gms.internal.firebase-auth-api.zzuh.zzj(com.google.firebase:firebase-auth@@21.0.3:1)
       at com.google.android.gms.internal.firebase-auth-api.zzue.zzn(com.google.firebase:firebase-auth@@21.0.3:2)
       at com.google.android.gms.internal.firebase-auth-api.zztg.zzn(com.google.firebase:firebase-auth@@21.0.3:1)
       at com.google.android.gms.internal.firebase-auth-api.zzqe.zzb(com.google.firebase:firebase-auth@@21.0.3:2)
       at com.google.android.gms.internal.firebase-auth-api.zzup.zza(com.google.firebase:firebase-auth@@21.0.3:24)
       at com.google.android.gms.internal.firebase-auth-api.zztv.zzf(com.google.firebase:firebase-auth@@21.0.3:4)
       at com.google.android.gms.internal.firebase-auth-api.zzrl.zzp(com.google.firebase:firebase-auth@@21.0.3:4)
       at com.google.android.gms.internal.firebase-auth-api.zzth.zzj(com.google.firebase:firebase-auth@@21.0.3:5)
       at com.google.android.gms.internal.firebase-auth-api.zzrv.zzc(com.google.firebase:firebase-auth@@21.0.3:1)
       at com.google.android.gms.internal.firebase-auth-api.zzui.run(com.google.firebase:firebase-auth@@21.0.3:1)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:920)

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

I am not able to reproduce it, except that it happens either while getting a fresh token or signing in anonymously.

#### Relevant Code:

Either happening when:
`Firebase.auth.signInAnonymously().await()`

Or when getting the token:
`Firebase.auth.currentUser?.getIdToken(true)?.await()?.token`

I have both tried with the standard Firebase async way and using kotlinx-coroutines-play-services (have tried with both 1.6.0 and 1.6.1) with the same result.

The crashes are happening internally, where I am not able to catch the exceptions.

```
// TODO(you): code here to reproduce the problem
```

**Comment by argzdev** [comment]
Hi @hnljp, thanks for reporting. Yes, I believe this is the same issue as 3617. That being said, I'll close this issue so we can avoid duplications. Feel free to continue your report on the 3617. Also, could you give 3617 a thumbs up? This is so that our engineers can prioritize what to fix based on its demand and severity. Thanks!
