### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException: Uncaught exception in Firebase Database runloop (20.0.4).

### ISSUE THREAD

**Issue by RufenKhokhar** [firebase/firebase-android-sdk#3643]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other categories use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    Google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 2020.3.1 patch4
  * Firebase Component: Database
  * Component version: 20.0.4

### [REQUIRED] Step 3: Describe the problem
The works find on debug mode but when I generate the signed app for the play store, it crashes with a blow error

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
Fatal Exception: java.lang.RuntimeException: Uncaught exception in Firebase Database runloop (20.0.4). If you are not already on the latest version of the Firebase SDKs, try updating your dependencies. Should this problem persist, please file a report at https://github.com/firebase/firebase-android-sdk
       at com.google.firebase.database.android.AndroidPlatform$1$1.run(AndroidPlatform.java:96)
       at android.os.Handler.handleCallback(Handler.java:795)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:6861)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:450)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by argzdev** [comment]
Hi @RufenKhokhar, thanks for reporting. Unfortunately, there's not enough details here for me to make an investigation. 

Could you provide more information like the following:
1. Any code snippet where this issue is experienced?
2. Steps to reproduce this issue
3. Is this issue consistently reproducible? 
4. Are there any specific Android brands or version?

If you could also provide a minimal repro, that would greatly help us in our investigation.

**Comment by Mercandj** [comment]
Hi,

Same issue when minification enabled on debug build.
(Thank you for the great tool that is firebase 💪, I hope my message will help you @argzdev)

Here is my setup:
- Reproduced in debug build
- `android.buildTypes.getByName("debug").isMinifyEnabled = true`, does not crash when isMinifyEnabled is `false`
- Crash when I'm calling `FirebaseDatabase.getInstance().getReference("challenges")` on the `getReference` call.
- Dependency: `implementation("com.google.firebase:firebase-database:20.0.4")` and `implementation("com.google.firebase:firebase-database-ktx:20.0.4")` with plugin `classpath("com.google.gms:google-services:4.3.10")`
- Other dependencies are up-to-date **even if should not be related to the issue**:
   - Kotlin 1.6.20
   - build tools "com.android.tools.build:gradle:7.1.3"
   - distributionUrl=https\://services.gradle.org/distributions/gradle-7.4.2-bin.zip
- Using R8
- Proguard Rules like adviced [here](https://firebase.google.com/docs/database/android/start#proguard): `-keepattributes Signature` (no POJO used) and also `-repackageclasses 'defpackage'`
- Reproduced on Android 12, Pixel 6, crash 100% reproductible
- Stacktrace

```
2022-04-21 23:08:38.743 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mercandalli.android.apps.sampler, PID: 11865
    java.lang.RuntimeException: Uncaught exception in Firebase Database runloop (20.0.4). If you are not already on the latest version of the Firebase SDKs, try updating your dependencies. Should this problem persist, please file a report at https://github.com/firebase/firebase-android-sdk
        at j4.n$a$a.run(:96)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7870)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.lang.NoSuchMethodError: No virtual method object()Lb9/g; in class Lb9/g; or its super classes (declaration of 'b9.g' appears in /data/app/~~MDSz81k4B6uCZgrZsQ9zyQ==/com.mercandalli.android.apps.sampler-66tdqwTq1qJ-KDvS2fRLdw==/base.apk)
        at w4.b.e(:69)
        at w4.b.d(:58)
        at w4.b.c(:38)
        at l4.p.v(:234)
        at l4.b.l(:246)
        at l4.b.m(:120)
        at l4.m.v0(:1427)
        at l4.m.m0(:1414)
        at l4.m.w0(:1366)
        at l4.m.q0(:1409)
        at l4.m.c(:365)
        at l4.b.e(:220)
        at l4.b.i(:213)
        at l4.b.g(:185)
        at l4.b.a(:135)
        at l4.p.j(:259)
        at l4.p.o(:306)
        at l4.p.f(:34)
        at l4.p$e$b.run(:86)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
```

Have a nice day,
Jon

**Comment by argzdev** [comment]
Hi @Mercandj, thanks for the detailed information. I tried creating a clean project with your setup. However, after installing the debug/release build of the app, I do not encounter any issue at all. The only difference in your setup with mine is that I used a higher version of Kotlin `1.7.0` and build tools `7.2`. 

Could you provide a minimal repro of your issue? Please do not include your `google-services.json` in the repro, thanks!

**Comment by Mercandj** [comment]
Sure @argzdev. That was not easy to do, but I think I managed to do it and isolate the issue : https://github.com/Mercandj/firebase-android-sdk-database-issue-3643#firebase-android-issue

The stacktrace is talking about class missing. With the mapping, I found that the class missing was `org.json.JSONStringer` *(at least for me, not sure it the same reason for you @RufenKhokhar)*.

`org.json` is part of Android but indeed I'm also using my own java library that are included `org.json` dependency. So, I the sample above, I added the [dependency](https://github.com/Mercandj/firebase-android-sdk-database-issue-3643/blob/main/app/build.gradle.kts#L67) and managed to reproduce the issue.

Like you adviced, I didn't versionned my `google-services.json` for security reason, so, in order to re-use my sample, you will need to add a new json.

I suppose that it is pretty rare to do that, but `org.json` is very usefull.

I hope I'm not missing something and that will help =)

**Comment by argzdev** [comment]
Hi @Mercandj, amazing investigation! I was able to reproduce the same behavior that you're experiencing with your repro. I'll notify an engineer to see what we can do here. Thanks!

**Comment by Mercandj** [comment]
Hi @argzdev, sure, done on the #3688. Thanks for the follow up. Have a nice day.
