### ISSUE TITLE
BadTokenException when showing FIAM

### ISSUE THREAD

**Issue by trmi1012** [firebase/firebase-android-sdk#3667]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 

> Android Studio Arctic Fox | 2020.3.1 Patch 4
> Build #AI-203.7717.56.2031.7935034, built on November 21, 2021
> Runtime version: 11.0.10+0-b96-7249189 aarch64

  * Firebase Component: Firebase In App Messaging
  * Component version: Bom version `29.3.0`

### [REQUIRED] Step 3: Describe the problem

This crash began to occur when we started to send Fiam notifications. 
According to (https://github.com/firebase/firebase-android-sdk/issues/1694) this should already be fixed in the version we're using but it's still happening.

> Caused by: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:783)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:359)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
	at qc.d$d.run(SourceFile:26)
	at android.app.Activity.runOnUiThread(Activity.java:6188)
	at qc.d.h(SourceFile:16)
	at sc.f$a.g(SourceFile:4)
	at b6.g.clear(SourceFile:10)
	at y5.n.a(SourceFile:3)
	at com.bumptech.glide.h.j(SourceFile:3)
	at com.bumptech.glide.h.h(SourceFile:1)
	at qc.a.onActivityPaused(SourceFile:13)
	at android.app.Application.dispatchActivityPaused(Application.java:225)
	at android.app.Activity.onPause(Activity.java:1675)
	at androidx.fragment.app.p.onPause(SourceFile:1)
	at car.pace.drive.app.MainActivity.onPause(SourceFile:1)
	at android.app.Activity.performPause(Activity.java:7157)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1408)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3928)
	... 11 more

**Comment by argzdev** [comment]
Hi @trmi1012, thanks for reporting. Could you answer a few questions below to help us investigate this:
1. Can you provide steps how to reproduce this issue?
2. Is it also the same scenario as #1694?
3. Are you using any listeners upon receiving in app campaigns?
4. Is the issue consistent? If yes, can you provide us a minimal repro of the issue?

Thanks in advance!
