### ISSUE TITLE
FirebaseApp was deleted

### ISSUE THREAD

**Issue by weitinsun** [firebase/firebase-android-sdk#368]
com.google.firebase:firebase-core: 16.0.7
com.google.android.gms:play-services-vision: 17.0.2

We sometimes encountered this issue when our app started.
From firebase crashlytics console we found.

Fatal Exception: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 (has extras) } in com.google.firebase.iid.zzaz@6c33184
       at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_53442(LoadedApk.java:1367)
       at android.app.-$Lambda$FilBqgnXJrN9Mgyks1XHeAxzSTk.$m$0(-.java:4)
       at android.app.-$Lambda$FilBqgnXJrN9Mgyks1XHeAxzSTk.run(-.java)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:180)
       at android.app.ActivityThread.main(ActivityThread.java:6950)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:835)

Caused by java.lang.IllegalStateException: FirebaseApp was deleted
       at com.google.android.gms.common.internal.Preconditions.checkState(Preconditions.java:29)
       at com.google.firebase.FirebaseApp.zzc(FirebaseApp.java:566)
       at com.google.firebase.FirebaseApp.getApplicationContext(FirebaseApp.java:180)
       at com.google.firebase.iid.zzay.getContext(zzay.java:54)
       at com.google.firebase.iid.zzay.zzao(zzay.java:55)
       at com.google.firebase.iid.zzaz.onReceive(zzaz.java:11)
       at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_53442(LoadedApk.java:1348)
       at android.app.-$Lambda$FilBqgnXJrN9Mgyks1XHeAxzSTk.$m$0(-.java:4)
       at android.app.-$Lambda$FilBqgnXJrN9Mgyks1XHeAxzSTk.run(-.java)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:180)
       at android.app.ActivityThread.main(ActivityThread.java:6950)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:835)

Does this mean FirebaseApp is not existed?
Any help will be appreciated.

**Comment by aguatno** [comment]
Hi @weitinsun sorry for the delay. This is the first time I hear about this issue, I was wondering if you have numbers to show how frequent this crash is? 

You may also consider upgrading your[ SDK to the latest version](https://firebase.google.com/docs/android/setup), and see if the persists from there.

Thanks!
