### ISSUE TITLE
Firebase Remote Config fetch fail

### ISSUE THREAD

**Issue by vancuong0429** [firebase/firebase-android-sdk#3710]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: android studio bumblebee path 1
  * Firebase Component: Remote Config
  * Component version: com.google.firebase:firebase-bom:28.4.2

### [REQUIRED] Step 3: Describe the problem

**Remote config fetchAndActivate return fail**
This is log error:

Non-fatal Exception: cx1: Firebase Installations failed to get installation auth token for fetch.
       at com.google.firebase.remoteconfig.internal.ConfigFetchHandler.lambda$fetchIfCacheExpiredAndNotThrottled$1(ConfigFetchHandler.java:210)
       at com.google.firebase.remoteconfig.internal.ConfigFetchHandler.lambda$fetchIfCacheExpiredAndNotThrottled$1$ConfigFetchHandler(ConfigFetchHandler.java:8)
       at com.google.firebase.remoteconfig.internal.-$$Lambda$ConfigFetchHandler$PAoFtfQiOtbXSTeK4H2aFJ-JNJI.then(-.java:8)
       at com.google.android.gms.tasks.zzg.run(zzg.java:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
**And:**
Caused by pt1: Firebase Installations Service is unavailable. Please try again later.
       at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.generateAuthToken(FirebaseInstallationServiceClient.java:452)
       at com.google.firebase.installations.FirebaseInstallations.fetchAuthTokenFromServer(FirebaseInstallations.java:566)
       at com.google.firebase.installations.FirebaseInstallations.doNetworkCallIfNecessary(FirebaseInstallations.java:390)
       at com.google.firebase.installations.FirebaseInstallations.lambda$doRegistrationOrRefresh$2(FirebaseInstallations.java:377)
       at com.google.firebase.installations.FirebaseInstallations.lambda$doRegistrationOrRefresh$2$FirebaseInstallations(FirebaseInstallations.java:13)
       at com.google.firebase.installations.-$$Lambda$FirebaseInstallations$VZq1h0TBcWNH8Y5yY86ujrFFyLo.run(-.java:13)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)

**Comment by vancuong0429** [comment]
I have log event "remote_config_load" to firebase, Rating load fail is very high
![Screen Shot 2022-05-09 at 17 57 35](https://user-images.githubusercontent.com/12462346/167396534-eaa31272-0b59-46c4-8ea6-44378cda41f9.png)
