### ISSUE TITLE
NullPointerException at updateFidListener

### ISSUE THREAD

**Issue by mj-hd** [firebase/firebase-android-sdk#3760]
* Android Studio version: Android Studio Arctic Fox | 2020.3.1 Patch 3
  * Firebase Component: Installations (Database, Firestore, Storage, Functions, etc)
  * Component version: 29.0.4

#### Steps to reproduce:

No repro, but a thousand users report this error:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
    at com.google.firebase.installations.FirebaseInstallations.updateFidListener(FirebaseInstallations.java:425)
    at com.google.firebase.installations.FirebaseInstallations.doNetworkCallIfNecessary(FirebaseInstallations.java:401)
    at com.google.firebase.installations.FirebaseInstallations.lambda$doRegistrationOrRefresh$2(FirebaseInstallations.java:374)
    at com.google.firebase.installations.FirebaseInstallations.$r8$lambda$VZq1h0TBcWNH8Y5yY86ujrFFyLo(FirebaseInstallations.java:0)
    at com.google.firebase.installations.FirebaseInstallations$$InternalSyntheticLambda$1$b9fc2c28ef307c94a05f9f2ca9baa5bd46434e43c62d588972a9d84cceb0aed2$0.run(R8$$SyntheticClass:0)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    at java.lang.Thread.run(Thread.java:761)
```

#### Relevant Code:

`getFirebaseInstallationId` is marked as `Nullable`:
https://github.com/firebase/firebase-android-sdk/blob/4f53170b26e74363ec50bf370a516154f654dc20/firebase-installations/src/main/java/com/google/firebase/installations/local/PersistedInstallationEntry.java#L32

So a null check should be here?
https://github.com/firebase/firebase-android-sdk/blob/4f53170b26e74363ec50bf370a516154f654dc20/firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java#L425

**Comment by argzdev** [comment]
Thanks for reporting, @mj-hd. May I ask what Firebase products are you using? Also could you try using our latest BoM version (30.1.0) and see if that helps? Thanks!

**Comment by argzdev** [comment]
Thanks for the extra details, @mj-hd. We usually suggest upgrading to the latest version as a first step to avoid issues that's already been fixed before troubleshooting. 

But in this case, l believe you're right, adding a null checker should resolve the case. I'll create a pull request and see notify an engineer to see if it's good to merge or if changes are needed. Thanks!
