### ISSUE TITLE
Crashlytics report could not be enqueued to DataTransport - Log tag "TRuntime.SQLiteEventStore" exceeds limit of 23 characters

### ISSUE THREAD

**Issue by eriksquare** [firebase/firebase-android-sdk#3823]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Chipmunk | 2021.2.1 Patch 1
  * Firebase Component: Crashlytics
  * Component version: 18.2.11

### [REQUIRED] Step 3: Describe the problem

My app is collecting crashes but it fails to send them. This happens on every build type (debug, release) and with and without proguard. In analytics i see affected users but there are no crashlogs

```
2022-06-17 13:00:19.623 D/FirebaseCrashlytics: Opening a new session with ID 62AC5EC3025A00013BC89C3E6FCF8E24
2022-06-17 13:00:19.625 I/FirebaseInitProvider: FirebaseApp initialization successful
2022-06-17 13:00:19.634 D/FirebaseCrashlytics: Registered Firebase Analytics event receiver for breadcrumbs
2022-06-17 13:00:19.636 D/FirebaseCrashlytics: Crashlytics automatic data collection ENABLED by API.
2022-06-17 13:00:19.636 D/FirebaseCrashlytics: Automatic data collection is enabled. Allowing upload.
2022-06-17 13:00:19.816 D/FirebaseCrashlytics: Sending cached crash reports...
2022-06-17 13:00:19.822 D/FirebaseCrashlytics: Sending report through Google DataTransport: 62AC542603D900011F0B9C3E6FCF8E24
2022-06-17 13:00:19.836 W/FirebaseCrashlytics: Crashlytics report could not be enqueued to DataTransport
    java.lang.IllegalArgumentException: Log tag "TRuntime.SQLiteEventStore" exceeds limit of 23 characters
    
        at android.util.Log.isLoggable(Native Method)
        at com.google.android.datatransport.runtime.logging.Logging.d(Logging.java:64)
        at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore.persist(SQLiteEventStore.java:104)
        at com.google.android.datatransport.runtime.scheduling.DefaultScheduler.lambda$schedule$0$com-google-android-datatransport-runtime-scheduling-DefaultScheduler(DefaultScheduler.java:83)
        at com.google.android.datatransport.runtime.scheduling.DefaultScheduler$$ExternalSyntheticLambda0.execute(D8$$SyntheticClass)
        at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore.runCriticalSection(SQLiteEventStore.java:754)
        at com.google.android.datatransport.runtime.scheduling.DefaultScheduler.lambda$schedule$1$com-google-android-datatransport-runtime-scheduling-DefaultScheduler(DefaultScheduler.java:81)
        at com.google.android.datatransport.runtime.scheduling.DefaultScheduler$$ExternalSyntheticLambda1.run(D8$$SyntheticClass)
        at com.google.android.datatransport.runtime.SafeLoggingExecutor$SafeLoggingRunnable.run(SafeLoggingExecutor.java:47)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
```

no other related logs are visible after

#### Steps to reproduce:
-

#### Relevant Code:
-

**Comment by argzdev** [comment]
Hi @eriksquare, thanks for reporting this. I've created a PR for this: #3822. This fix will be included in the next release. I can't provide any specific timeline when this fix will be available, but you may keep an eye out on our [release notes](https://firebase.google.com/support/releases) from time to time to check out the latest features and bug fixes.

**Comment by argzdev** [comment]
Since this has been merged, I'll close this now. Thanks!

**Comment by Amanvein** [comment]
any update on this issue.

**Comment by argzdev** [comment]
Hi @Amanvein, we expect this fix to be in a release that is targeted for next week.

**Comment by otaviogaiao** [comment]
Waiting for it too.

**Comment by kaidotarma** [comment]
Also waiting a fix for this. @argzdev Do you know what's the ETA for the release?

**Comment by kaidotarma** [comment]
Or is there a workaround until it gets released?

**Comment by jnorkus** [comment]
Still not working. Latest release did not include a fix. No workarounds @argzdev ?

**Comment by argzdev** [comment]
Sorry for the delayed response. It seems that the release including the fix has been delayed. There are 2 workarounds I can think of:
Option 1:
- Downgrade Crashlytics to `com.google.firebase:firebase-crashlytics:18.2.9`

Option 2:
- [Publish](https://github.com/firebase/firebase-android-sdk#publishing) your own local copy of the Firebase sdk, and then reference the snapshot version of the sdk to your app.

**Comment by kaidotarma** [comment]
@argzdev Thanks, version 18.2.9 seems to work!

To others:
If you have "com.google.firebase:firebase-bom" in the dependencies, you should probably disable it for now, otherwise selecting the specific crashlytics library version would not change anything, as BoM would actively overwrite it. For example I commented out this line:
// implementation platform('com.google.firebase:firebase-bom:30.2.0')

**Comment by G-Steve-E** [comment]
I have same issue when downgrading Crashlytics to 18.2.9.
commented out:
// implementation platform('com.google.firebase:firebase-bom:30.2.0')
as noted above.

**Comment by jnorkus** [comment]
`implementation platform('com.google.firebase:firebase-bom:29.3.1')` seems to do the job as it includes Crashlytics 18.2.9

**Comment by G-Steve-E** [comment]
That works.  Thanks!

**Comment by eduardob737** [comment]
@jnorkus Thanks man!
