### ISSUE TITLE
Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.IllegalStateException: GeneratedAppGlideModuleImpl is implemented incorrectly.

### ISSUE THREAD

**Issue by jpainam** [firebase/firebase-android-sdk#3894]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: _2021.2.1____
  * Firebase Component: __in app messaging
  * Component version: _____

### [REQUIRED] Step 3: Describe the problem
```kotlin
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xxx.xxxxxxx, PID: 9101
    java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.IllegalStateException: GeneratedAppGlideModuleImpl is implemented incorrectly. If you've manually implemented this class, remove your implementation. The Annotation processor will generate a correct implementation.
        at android.app.ActivityThread.installProvider(ActivityThread.java:6747)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6289)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6204)
        at android.app.ActivityThread.access$1200(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1785)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: java.lang.IllegalStateException: GeneratedAppGlideModuleImpl is implemented incorrectly. If you've manually implemented this class, remove your implementation. The Annotation processor will generate a correct implementation.
        at com.bumptech.glide.Glide.throwIncorrectGlideModule(Glide.java:344)
        at com.bumptech.glide.Glide.getAnnotationGeneratedGlideModules(Glide.java:336)
        at com.bumptech.glide.Glide.get(Glide.java:179)
        at com.bumptech.glide.Glide.getRetriever(Glide.java:749)
        at com.bumptech.glide.Glide.with(Glide.java:776)
        at com.google.firebase.inappmessaging.display.internal.injection.modules.GlideModule.providesGlideRequestManager(GlideModule.java:32)
        at com.google.firebase.inappmessaging.display.internal.injection.modules.GlideModule_ProvidesGlideRequestManagerFactory.providesGlideRequestManager(GlideModule_ProvidesGlideRequestManagerFactory.java:43)
        at com.google.firebase.inappmessaging.display.internal.injection.modules.GlideModule_ProvidesGlideRequestManagerFactory.get(GlideModule_ProvidesGlideRequestManagerFactory.java:32)
        at com.google.firebase.inappmessaging.display.internal.injection.modules.GlideModule_ProvidesGlideRequestManagerFactory.get(GlideModule_ProvidesGlideRequestManagerFactory.java:11)
        at com.google.firebase.inappmessaging.display.dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.google.firebase.inappmessaging.display.internal.FiamImageLoader_Factory.get(FiamImageLoader_Factory.java:21)
        at com.google.firebase.inappmessaging.display.internal.FiamImageLoader_Factory.get(FiamImageLoader_Factory.java:8)
        at com.google.firebase.inappmessaging.display.dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay_Factory.get(FirebaseInAppMessagingDisplay_Factory.java:61)
        at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay_Factory.get(FirebaseInAppMessagingDisplay_Factory.java:16)
        at com.google.firebase.inappmessaging.display.dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.google.firebase.inappmessaging.display.internal.injection.components.DaggerAppComponent.providesFirebaseInAppMessagingUI(DaggerAppComponent.java:80)
        at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplayRegistrar.buildFirebaseInAppMessagingUI(FirebaseInAppMessagingDisplayRegistrar.java:72)
        at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplayRegistrar.lambda$mFT7XCE3YJXhnGdhKohfXnpd5DM(Unknown Source:0)
        at com.google.firebase.inappmessaging.display.-$$Lambda$FirebaseInAppMessagingDisplayRegistrar$mFT7XCE3YJXhnGdhKohfXnpd5DM.create(Unknown Source:2)
        at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0$ComponentRuntime(ComponentRuntime.java:132)
E/AndroidRuntime:     at com.google.firebase.components.-$$Lambda$ComponentRuntime$4FqOW9eOQsvFYo-HpMfxCOnPQr0.get(Unknown Source:4)
        at com.google.firebase.components.Lazy.get(Lazy.java:53)
        at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents(ComponentRuntime.java:291)
        at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(ComponentRuntime.java:281)
        at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:584)
        at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:303)
        at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:267)
        at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:252)
        at com.google.firebase.provider.FirebaseInitProvider.onCreate(FirebaseInitProvider.java:51)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1940)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1915)
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(FirebaseInitProvider.java:45)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6742)
        	... 10 more
     Caused by: java.lang.NoSuchMethodException: com.bumptech.glide.GeneratedAppGlideModuleImpl.<init> [class android.content.Context]
        at java.lang.Class.getConstructor0(Class.java:2328)
        at java.lang.Class.getDeclaredConstructor(Class.java:2167)
        at com.bumptech.glide.Glide.getAnnotationGeneratedGlideModules(Glide.java:320)
        	... 42 more

```
#### Steps to reproduce:
By just adding 
```kotlin
 implementation platform('com.google.firebase:firebase-bom:28.4.2')
    implementation 'com.google.firebase:firebase-firestore-ktx'
    implementation 'com.google.firebase:firebase-crashlytics-ktx'
    implementation 'com.google.firebase:firebase-inappmessaging-display-ktx'
```
What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by argzdev** [comment]
Thanks for reporting, @jpainam. I'm unable to reproduce the issue you're experiencing. Are you able to reproduce the behavior consistently? If so, could you provide a minimal repro so I can investigate this further?

Also looking at the stacktrace, _"GeneratedAppGlideModuleImpl is implemented incorrectly. If you've manually implemented this class, remove your implementation. The Annotation processor will generate a correct implementation."_ Did you perhaps changed the implementation manually?

**Comment by jpainam** [comment]
Hi @argzdev  I didn't change `Glide` implementation. However, I've added an implementation in ` app gradle`.
```kotlin
//Glide
    implementation 'com.github.bumptech.glide:glide:4.9.0'
    kapt 'com.github.bumptech.glide:compiler:4.9.0'
```
`proguard-pro`
```kotlin
# Glide
-keep public class * implements com.bumptech.glide.module.GlideModule
-keep public class * extends com.bumptech.glide.module.AppGlideModule
-keep public enum com.bumptech.glide.load.ImageHeaderParser$** {
  **[] $VALUES;
  public *;
}
```
And a `Glide module` to register `Firebase storage ImageLoader`
```kotlin
@GlideModule
class MyGlideModule : AppGlideModule() {
    override fun registerComponents(context: Context, glide: Glide, registry: Registry) {
        // Register FirebaseImageLoader to handle StorageReference
        super.registerComponents(context, glide, registry)
        registry.append(StorageReference::class.java, InputStream::class.java, FirebaseImageLoader.Factory())
    }
}
```

 It looks like `app-messaging` is important its own `Glide`, which conflicts with mine?

**Comment by argzdev** [comment]
Thanks for recommending the updated version, @thatfiredev! I was able to reproduce the issue on version `4.9.0`, and it looks like using the latest version `4.11.0` fixes this issue. Could you try that and confirm on your end, @jpainam.

**Comment by jpainam** [comment]
Hi, this is a minimal code to reproduce https://github.com/jpainam/inappmessagingtest.git

Removing `implementation 'com.google.firebase:firebase-crashlytics-buildtools:2.8.1'` and keeping version `4.9.0` solved the error.

Using version `4.11.0` also solved the problem. 

Thanks
