### ISSUE TITLE
FCM getToken() returns an error  AUTHENTICATION_FAILED under SDK31+

### ISSUE THREAD

**Issue by SiarheiBaltrukevich** [firebase/firebase-android-sdk#3898]
### Environment

  * Android Studio version: chipmunk 2021.2.1
  * Firebase Component: Messaging
  * Component version: 23.0.6

### Describtion of the problem
I set up small project to check out the FCM work. After I started the app under different Android OS 8,9,10,11,12,13
App data:
compileSDK.      : 33
minSDK.              : 26
target.                 : 33
Java                     : 11
google-services:4.3.13

I followed all steps from the guide. And reach a working application. But I can get messages under OS 8-11 only, when I start the app on an emulator under OS 12, 12L, 13, I receive the error: `java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: AUTHENTICATION_FAILED`

The same issue I can get for FCM versions: 21.1.0 - 23.0.6, I did not check versions less that these ones.

#### Steps to reproduce:

Set up FCM.
Run your app under Android 12+

#### Relevant Code:

The code below returns an error for devices on Android 12+
         ` java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: AUTHENTICATION_FAILED`
and token for devices on Android 11-
```
private fun checkFCMToken() {
           FirebaseMessaging.getInstance().token.addOnCompleteListener {
                if(it.isSuccessful) {
                    println("->> token: ${it.result}")
                } else {
                    println("->> error: ${it.exception}")
                    getToken()
                }
            }
}
```
full code [here](https://github.com/SiarheiBaltrukevich/LearnMultiplying/tree/master/app/src/main)

### Stack trace:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.boltic28.learnmultiplying, PID: 19415
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:558)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
     Caused by: java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: AUTHENTICATION_FAILED
        at com.google.firebase.messaging.FirebaseMessaging.blockingGetToken(FirebaseMessaging.java:625)
        at com.google.firebase.messaging.FirebaseMessaging.lambda$getToken$4$com-google-firebase-messaging-FirebaseMessaging(FirebaseMessaging.java:392)
        at com.google.firebase.messaging.FirebaseMessaging$$ExternalSyntheticLambda1.run(Unknown Source:4)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@18.0.0:2)
        at java.lang.Thread.run(Thread.java:920)
     Caused by: java.util.concurrent.ExecutionException: java.io.IOException: AUTHENTICATION_FAILED
        at com.google.android.gms.tasks.Tasks.zza(com.google.android.gms:play-services-tasks@@18.0.1:5)
        at com.google.android.gms.tasks.Tasks.await(com.google.android.gms:play-services-tasks@@18.0.1:8)
        at com.google.firebase.messaging.FirebaseMessaging.blockingGetToken(FirebaseMessaging.java:623)
        at com.google.firebase.messaging.FirebaseMessaging.lambda$getToken$4$com-google-firebase-messaging-FirebaseMessaging(FirebaseMessaging.java:392) 
        at com.google.firebase.messaging.FirebaseMessaging$$ExternalSyntheticLambda1.run(Unknown Source:4) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@18.0.0:2) 
        at java.lang.Thread.run(Thread.java:920) 
     Caused by: java.io.IOException: AUTHENTICATION_FAILED
        at com.google.firebase.messaging.GmsRpc.handleResponse(GmsRpc.java:309)
        at com.google.firebase.messaging.GmsRpc.lambda$extractResponseWhenComplete$0$com-google-firebase-messaging-GmsRpc(GmsRpc.java:320)
        at com.google.firebase.messaging.GmsRpc$$ExternalSyntheticLambda0.then(Unknown Source:2)
        at com.google.android.gms.tasks.zzc.run(com.google.android.gms:play-services-tasks@@18.0.1:3)
        at com.google.firebase.messaging.EnhancedIntentService$$ExternalSyntheticLambda2.execute(Unknown Source:0)
        at com.google.android.gms.tasks.zzd.zzd(com.google.android.gms:play-services-tasks@@18.0.1:1)
        at com.google.android.gms.tasks.zzr.zzb(com.google.android.gms:play-services-tasks@@18.0.1:5)
        at com.google.android.gms.tasks.zzw.zzb(com.google.android.gms:play-services-tasks@@18.0.1:3)
        at com.google.android.gms.tasks.zzc.run(com.google.android.gms:play-services-tasks@@18.0.1:8)
        at com.google.android.gms.cloudmessaging.zzz.execute(Unknown Source:0)
        at com.google.android.gms.tasks.zzd.zzd(com.google.android.gms:play-services-tasks@@18.0.1:1)
        at com.google.android.gms.tasks.zzr.zzb(com.google.android.gms:play-services-tasks@@18.0.1:5)
        at com.google.android.gms.tasks.zzw.zzb(com.google.android.gms:play-services-tasks@@18.0.1:3)
        at com.google.android.gms.tasks.TaskCompletionSource.setResult(com.google.android.gms:play-services-tasks@@18.0.1:1)
        at com.google.android.gms.cloudmessaging.zzp.zzd(com.google.android.gms:play-services-cloud-messaging@@17.0.0:3)
        at com.google.android.gms.cloudmessaging.zzr.zza(com.google.android.gms:play-services-cloud-messaging@@17.0.0:2)
        at com.google.android.gms.cloudmessaging.zzf.handleMessage(com.google.android.gms:play-services-cloud-messaging@@17.0.0:14)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by SiarheiBaltrukevich** [comment]
this is the stack trace for my current project (FCM: 21.1.0) started under Android 12
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.someproject.dev, PID: 27474
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:558)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
     Caused by: java.io.IOException: AUTHENTICATION_FAILED
        at com.google.firebase.iid.GmsRpc.handleResponse(com.google.firebase:firebase-iid@@21.1.0:7)
        at com.google.firebase.iid.GmsRpc.lambda$extractResponseWhenComplete$0$GmsRpc(com.google.firebase:firebase-iid@@21.1.0:1)
        at com.google.firebase.iid.GmsRpc$$Lambda$0.then(Unknown Source:6)
        at com.google.android.gms.tasks.zzc.run(com.google.android.gms:play-services-tasks@@18.0.1:3)
        at com.google.firebase.iid.FirebaseIidExecutors$$Lambda$0.execute(Unknown Source:4)
        at com.google.android.gms.tasks.zzd.zzd(com.google.android.gms:play-services-tasks@@18.0.1:1)
        at com.google.android.gms.tasks.zzr.zzb(com.google.android.gms:play-services-tasks@@18.0.1:5)
        at com.google.android.gms.tasks.zzw.zzb(com.google.android.gms:play-services-tasks@@18.0.1:3)
        at com.google.android.gms.tasks.zzc.run(com.google.android.gms:play-services-tasks@@18.0.1:8)
        at com.google.android.gms.cloudmessaging.zzz.execute(Unknown Source:4)
        at com.google.android.gms.tasks.zzd.zzd(com.google.android.gms:play-services-tasks@@18.0.1:1)
        at com.google.android.gms.tasks.zzr.zzb(com.google.android.gms:play-services-tasks@@18.0.1:5)
        at com.google.android.gms.tasks.zzw.zzb(com.google.android.gms:play-services-tasks@@18.0.1:3)
        at com.google.android.gms.tasks.TaskCompletionSource.setResult(com.google.android.gms:play-services-tasks@@18.0.1:1)
        at com.google.android.gms.cloudmessaging.zzq.zza(com.google.android.gms:play-services-cloud-messaging@@16.0.0:9)
        at com.google.android.gms.cloudmessaging.zzs.zza(com.google.android.gms:play-services-cloud-messaging@@16.0.0:7)
        at com.google.android.gms.cloudmessaging.zzf.zza(com.google.android.gms:play-services-cloud-messaging@@16.0.0:45)
        at com.google.android.gms.cloudmessaging.zzi.handleMessage(Unknown Source:6)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
```

**Comment by SiarheiBaltrukevich** [comment]
response:
```
W/Firebase-Installations: Error when communicating with the Firebase Installations server API. HTTP response: [403 Forbidden: {
      "error": {
        "code": 403,
        "message": "Requests from this Android client application com.someproject.dev are blocked.",
        "status": "PERMISSION_DENIED",
        "details": [
          {
            "@type": "type.googleapis.com/google.rpc.ErrorInfo",
            "reason": "API_KEY_ANDROID_APP_BLOCKED",
            "domain": "googleapis.com",
            "metadata": {
              "service": "firebaseinstallations.googleapis.com",
              "consumer": "projects/20******8111"
            }
          }
        ]
      }
    }
    ]
```

**Comment by argzdev** [comment]
Hi @SiarheiBaltrukevich, our engineers tested this and it looks like the issue is only appearing on emulator devices, it might be due to the emulator not containing Google Play Service. Could you try on a physical device to see if this is the case?

**Comment by argzdev** [comment]
Furthermore, I've tried testing this on an emulator Android 12 with Google APIs, and it seems to work. Could you verify this as well? Thanks

**Comment by SiarheiBaltrukevich** [comment]
I use emulator with google api as well 
![Screen Shot 2022-07-15 at 12 37 06](https://user-images.githubusercontent.com/85740020/179197233-cfff4c51-65c3-46a0-b959-509d01203401.png)

**Comment by argzdev** [comment]
Awesome, that's good to hear!
