### ISSUE TITLE
Null pointer exception, due to null modelHash been passed to logger

### ISSUE THREAD

**Issue by kabeer-uber** [firebase/firebase-android-sdk#3940]
### [READ] Step 1: Are you in the right place?

YES

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version:  Any
  * Firebase Component: firebase-ml-modeldownloader 
  * Component version: 24.0.2

#### Steps to reproduce:
```

We are seeing failure reports with the following stack trace, although this will still result in a failure, we would like to do the proper errorCode tracking.

java.lang.NullPointerException: Null hash
 at com.google.firebase.ml.modeldownloader.internal.AutoValue_FirebaseMlLogEvent_ModelDownloadLogEvent_ModelOptions_ModelInfo$Builder.setHash(AutoValue_FirebaseMlLogEvent_ModelDownloadLogEvent_ModelOptions_ModelInfo.java:95)
 at com.google.firebase.ml.modeldownloader.internal.FirebaseMlLogger.logDownloadEvent(FirebaseMlLogger.java:202)
 at com.google.firebase.ml.modeldownloader.internal.FirebaseMlLogger.logDownloadFailureWithReason(FirebaseMlLogger.java:140)
 at com.google.firebase.ml.modeldownloader.internal.CustomModelDownloadService.getCustomModelDetails(CustomModelDownloadService.java:178)
 at com.google.firebase.ml.modeldownloader.internal.CustomModelDownloadService.lambda$getCustomModelDetails$0(CustomModelDownloadService.java:178)
 at ml.-$$Lambda$h$euUsgmxMCjdxKk4V8c7CBL0ZmSU3.then(-.java:10)
 at com.google.android.gms.tasks.zzg.run(zzg.java:2)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 at java.lang.Thread.run(Thread.java:923)
```
#### Relevant Code:

ModelHash needs to be non-null here https://github.com/firebase/firebase-android-sdk/blob/81d4d3df94f5c537357f24cb0ed70d5e4741e7bc/firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/CustomModelDownloadService.java#L179

But null is passed here
https://github.com/firebase/firebase-android-sdk/blob/0784d9cc6dac1056f7afd42ab39cf2381af5aafa/firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/FirebaseModelDownloader.java#L266

and here
https://github.com/firebase/firebase-android-sdk/blob/0784d9cc6dac1056f7afd42ab39cf2381af5aafa/firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/FirebaseModelDownloader.java#L253

**Comment by argzdev** [comment]
Hi @kabeer-uber, thanks for creating another pull request. This is highly appreciated! I'll let our engineers know about this.

**Comment by kabeer-uber** [comment]
Thank you @argzdev
