### ISSUE TITLE
RuntimeExecutionException

### ISSUE THREAD

**Issue by Shahriyar13** [firebase/firebase-android-sdk#3989]
**It was worked in last week, but I saw this issues in this week without any changes.**

com.google.firebase.installations.FirebaseInstallationsException: Firebase Installations Service is unavailable. Please try again later.

com.google.firebase.installations.FirebaseInstallationsException: Firebase Installations Service is unavailable. Please try again later.
    at com.google.firebase.installations.a.j(FirebaseInstallations.java:75)
    at za.b.run(R8$$SyntheticClass:15)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:920)
com.google.android.gms.tasks.RuntimeExecutionException: com.google.firebase.installations.FirebaseInstallationsException: Firebase Installations Service is unavailable. Please try again later.
    at com.google.android.gms.tasks.zzw.getResult(com.google.android.gms:play-services-tasks@@18.0.1:6)
    at [packageName].ui.main.MainViewModel$init$1$1.invokeSuspend(MainViewModel.kt:7)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.i0.run(DispatchedTask.kt:18)
    at kotlinx.coroutines.internal.g.run(LimitedDispatcher.kt:2)
    at ze.h.run(Tasks.kt:1)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$b.run(CoroutineScheduler.kt:14)

EVENTS
1.3k

USERS
124

**Comment by argzdev** [comment]
Thanks for reporting, @Shahriyar13. I'm not really sure what issue you're having right now. Could you open a new issue and follow our template? This is so that I can gather the basic necessary information to investigate and help you with your concern. I'll close this post now. Thanks!
