### ISSUE TITLE
Multiple cases of network issues

### ISSUE THREAD

**Issue by pistolcaffe** [firebase/firebase-android-sdk#4010]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Chipmunk | 2021.2.1 Patch 1
                                             Build #AI-212.5712.43.2112.8609683, built on May 19, 2022
  * Firebase Component: RemoteConfig, Authentication
  * Component version: com.google.firebase:firebase-bom:30.3.0

### [REQUIRED] Step 3: Describe the problem

We are running an app with about 10,000 DAUs.

Since a certain point, a number of error reports have been reported in `Crashlytics` as a Network issue in Firebase.

`FirebaseNetworkException` in `firebase-auth` and `FirebaseRemoteConfigClientException` in `RemoteConfig`.

### Log (FirebaseRemoteConfigClientException)
```
Fatal Exception: com.google.firebase.remoteconfig.FirebaseRemoteConfigClientException: The client had an error while calling the backend!
       at com.google.firebase.remoteconfig.internal.ConfigFetchHttpClient.fetch(ConfigFetchHttpClient.java:208)
       at com.google.firebase.remoteconfig.internal.ConfigFetchHandler.fetchFromBackend(ConfigFetchHandler.java:312)
       at com.google.firebase.remoteconfig.internal.ConfigFetchHandler.fetchFromBackendAndCacheResponse(ConfigFetchHandler.java:283)
       at com.google.firebase.remoteconfig.internal.ConfigFetchHandler.lambda$fetchIfCacheExpiredAndNotThrottled$1$com-google-firebase-remoteconfig-internal-ConfigFetchHandler(ConfigFetchHandler.java:220)
       at com.google.firebase.remoteconfig.internal.ConfigFetchHandler$$ExternalSyntheticLambda1.then(:8)
       at com.google.android.gms.tasks.zze.run(com.google.android.gms:play-services-tasks@@18.0.1:1)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:920)
Caused by java.net.UnknownHostException: Unable to resolve host "firebaseremoteconfig.googleapis.com": No address associated with hostname
       at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
       at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
       at java.net.InetAddress.getAllByName(InetAddress.java:1152)
       at com.android.okhttp.Dns$1.lookup(Dns.java:41)
       at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:178)
       at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:144)
       at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:86)
       at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:176)
       at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
       at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:219)
       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:30)
       at com.google.firebase.remoteconfig.internal.ConfigFetchHttpClient.setFetchRequestBody(ConfigFetchHttpClient.java:366)
       at com.google.firebase.remoteconfig.internal.ConfigFetchHttpClient.fetch(ConfigFetchHttpClient.java:196)
       at com.google.firebase.remoteconfig.internal.ConfigFetchHandler.fetchFromBackend(ConfigFetchHandler.java:312)
       at com.google.firebase.remoteconfig.internal.ConfigFetchHandler.fetchFromBackendAndCacheResponse(ConfigFetchHandler.java:283)
       at com.google.firebase.remoteconfig.internal.ConfigFetchHandler.lambda$fetchIfCacheExpiredAndNotThrottled$1$com-google-firebase-remoteconfig-internal-ConfigFetchHandler(ConfigFetchHandler.java:220)
       at com.google.firebase.remoteconfig.internal.ConfigFetchHandler$$ExternalSyntheticLambda1.then(:8)
       at com.google.android.gms.tasks.zze.run(com.google.android.gms:play-services-tasks@@18.0.1:1)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:920)
Caused by android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
       at libcore.io.Linux.android_getaddrinfo(Linux.java)
       at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:136)
       at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:221)
       at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:136)
       at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
       at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
       at java.net.InetAddress.getAllByName(InetAddress.java:1152)
       at com.android.okhttp.Dns$1.lookup(Dns.java:41)
       at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:178)
       at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:144)
       at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:86)
       at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:176)
       at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
       at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:219)
       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:30)
       at com.google.firebase.remoteconfig.internal.ConfigFetchHttpClient.setFetchRequestBody(ConfigFetchHttpClient.java:366)
       at com.google.firebase.remoteconfig.internal.ConfigFetchHttpClient.fetch(ConfigFetchHttpClient.java:196)
       at com.google.firebase.remoteconfig.internal.ConfigFetchHandler.fetchFromBackend(ConfigFetchHandler.java:312)
       at com.google.firebase.remoteconfig.internal.ConfigFetchHandler.fetchFromBackendAndCacheResponse(ConfigFetchHandler.java:283)
       at com.google.firebase.remoteconfig.internal.ConfigFetchHandler.lambda$fetchIfCacheExpiredAndNotThrottled$1$com-google-firebase-remoteconfig-internal-ConfigFetchHandler(ConfigFetchHandler.java:220)
       at com.google.firebase.remoteconfig.internal.ConfigFetchHandler$$ExternalSyntheticLambda1.then(:8)
       at com.google.android.gms.tasks.zze.run(com.google.android.gms:play-services-tasks@@18.0.1:1)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:920)
```

#### Relevant Code:

```
1. remoteConfig.fetchAndActivate()
2. auth.signInWithEmailAndPassword()
3. auth.createUserWithEmailAndPassword()
4. auth.getIdToken()
etc..
```

In general, it is possible to prevent exceptions by checking the user's network status. But it's strange that there are so many more reports than ever before.

<img width="678" alt="스크린샷 2022-08-19 오후 3 00 48" src="https://user-images.githubusercontent.com/16452048/185553523-6388e3f8-eae7-4310-a4a3-a38af6a183da.png">

### Questions
Q1. What is the criteria for judging a Network error in Firebase in a piece of code?
Q2. It is not known exactly whether the code that the developer directly checks the network status meets the criteria for using Firebase. Can't Firebase directly determine the network status and support APIs such as `isNetworkAvailable()` or `isServiceAvailable()`? Alternatively, consider adding a `FirebaseOptions` such as setting a timeout.

**Comment by argzdev** [comment]
Hi @pistolcaffe, thanks for reporting. I think if this happened during updates to the Firebase product dependency versions. Then it might be an issue related to the SDK. If not, then it might've been a zonal or regional outage of the remote config service.

> What is the criteria for judging a Network error in Firebase in a piece of code?

We don't necessarily have any complex way of judging a network error. It is just checking whether the request returns a response (HTTP 200) or a failure. We do have exponential backoff timer on the retry mechanism during failures.

> Can't Firebase directly determine the network status and support APIs such as isNetworkAvailable() or isServiceAvailable()? Alternatively, consider adding a FirebaseOptions such as setting a timeout.

As of the moment, the SDK doesn't do this. If I'm not mistaken, you can set timeouts via `setFetchTimeoutInSeconds` in Remote Config. Or are you pertaining to that what you want is that setting a `FirebaseOptions` timeout would be applied to all Firebase products? I think we can consider that as a feature request.


I've noticed a similar issue: #1776, where it was resolved when removing `fetchAndActivate` from the Application class.
> For everyone having this issue as well. We found the "problem" in our particular case.
We were calling fetchAndActivate from the onCreate lifecycle method of our Application class. As far as I always saw, there's no mention of this being an issue in Firebase documentation (maybe I missed it?) but after we removed that, all the problems we were having (crashlytics was not working, remote config failing incredibly a lot, analytics giving strange results) got fixed.

Let me know if this helps. Thanks!

**Comment by pistolcaffe** [comment]
@argzdev We are not calling `fetchAndActivate()` from our `Application` class.
However, a long analysis reveals the cause. This is because the sudden number of Network Issue logs to `Crashlytics` was exposed to the risk of Failure as it was changed from the method using `Function.addSuccessListener` and `Function.addFailureListener` to `Function.await()`.
It seems to be possible to fix it with `try-catch `. Thanks for your help.

**Comment by argzdev** [comment]
I see. I'm glad you were able to resolve your issue.
