### ISSUE TITLE
Fatal IllegalArgumentException: port out of range

### ISSUE THREAD

**Issue by vkomysh-vicman** [firebase/firebase-android-sdk#4011]
### Step 2: Describe your environment

  * Firebase Component: Firebase Installations (dependency for Messaging,...)
  * Component version: 17.0.1 (firebase-bom: 30.0.2)

#### Steps to reproduce:

Multiple crash reports in Crashlytics (Android 10, 11, 12)
The problem is described: https://github.com/square/okhttp/issues/7153
 
```
Fatal Exception: java.lang.IllegalArgumentException: port out of range:917187393
       at java.net.InetSocketAddress.checkPort(InetSocketAddress.java:144)
       at java.net.InetSocketAddress.createUnresolved(InetSocketAddress.java:269)
       at sun.net.spi.DefaultProxySelector$1.run(DefaultProxySelector.java:315)
       at sun.net.spi.DefaultProxySelector$1.run(DefaultProxySelector.java:219)
       at java.security.AccessController.doPrivileged(AccessController.java:43)
       at sun.net.spi.DefaultProxySelector.select(DefaultProxySelector.java:218)
       at com.android.okhttp.internal.http.RouteSelector.resetNextProxy(RouteSelector.java:123)
       at com.android.okhttp.internal.http.RouteSelector.<init>(RouteSelector.java:63)
       at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:172)
       at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
       at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:302)
       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:245)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:219)
       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:30)
       at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.writeRequestBodyToOutputStream(FirebaseInstallationServiceClient.java:234)
       at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.writeGenerateAuthTokenRequestBodyToOutputStream(FirebaseInstallationServiceClient.java:275)
       at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.generateAuthToken(FirebaseInstallationServiceClient.java:410)
       at com.google.firebase.installations.FirebaseInstallations.fetchAuthTokenFromServer(FirebaseInstallations.java:563)
       at com.google.firebase.installations.FirebaseInstallations.doNetworkCallIfNecessary(FirebaseInstallations.java:387)
       at com.google.firebase.installations.FirebaseInstallations.lambda$doRegistrationOrRefresh$2(FirebaseInstallations.java:374)
       at com.google.firebase.installations.FirebaseInstallations.lambda$doRegistrationOrRefresh$2$FirebaseInstallations(FirebaseInstallations.java:13)
       at com.google.firebase.installations.-$$Lambda$FirebaseInstallations$VZq1h0TBcWNH8Y5yY86ujrFFyLo.run(lambda:13)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
```

**Comment by argzdev** [comment]
Thanks for reporting, @vkomysh-vicman. Could you share any steps to reproduce this behavior? Or an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) would help us a lot investigating this. Thanks

**Comment by vkomysh-vicman** [comment]
I can't reproduce this crash. Trace from crashlytics. Here are some details:

- This issue has 1384 crash events affecting 33 users (last month)
- <1second (This crash event happened in the first second of the user’s session.)
- 90% background

**Comment by argzdev** [comment]
Looking around the conversation:
> This is a combination of a bug/poor handling of bad proxy config in DefaultProxySelector.select, and obviously the bad proxy config with a dodgy port.
> I don't think we can fix this in OkHttp, apart from maybe making it an IOException. But really the best workaround is probably for you to detect a bad proxy config in your app and override the proxy manually.

We should probably change the way we handle the proxy config. I'll let our engineers know about these finds and see what we can do here. Thanks

**Comment by yoyomyo** [comment]
@vkomysh-vicman Thank you for surfacing this crash cluster. We have been aware of it for a while. 
There are two courses of actions:
1. Catch the IllegalArgumentException in our SDK and convert it to IOException
2. Leave the crash as is, as we see in a similar report https://github.com/square/okhttp/issues/7153

We have discussed internally and we believe that it is the best we leave the crash as is without suppressing it. The crash is happening on a background thread so it is not user visible. When the crash do happen during an auth token refresh, a FirebaseInstallationsException will be thrown and clients should be able to recover from that by retrying, at most 7 days later.
