### ISSUE TITLE
Crash for Play Store Base

### ISSUE THREAD

**Issue by atk1993** [firebase/firebase-android-sdk#4063]
### java.lang.IllegalStateException: Task is not yet complete
    at e90.n.l(com.google.android.gms:play-services-basement@@18.1.0:1)
    at ja0.h0.j(com.google.android.gms:play-services-tasks@@18.0.2:2)
    at jj.f.b(R8$$SyntheticClass:6)
    at ja0.v.run(com.google.android.gms:play-services-tasks@@18.0.2:5)
    at android.os.Handler.handleCallback(Handler.java:790)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6543)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)

**Comment by 88rogikl88** [comment]
--
Sent from myMail for Android Wednesday, 07 September 2022, 07:44AM +03:00 from Google Open Source Bot  ***@***.*** :

**Comment by argzdev** [comment]
Hi @atk1993, thanks for reporting. Could you open a new issue with the required information? This is needed in order for us to do an initial investigation. Thanks!

I'll close this issue now.
