### ISSUE TITLE
Unhandled exception in ML Model Downloader 

### ISSUE THREAD

**Issue by sandeep5193** [firebase/firebase-android-sdk#4203]
### Step 2: Describe your environment

  * Android Studio version: Dolphin 2021.3.1
  * Firebase Component: ML Model Downloader
  * Component version: BOM 30.5.0

#### Steps to reproduce:

This is captured by Crashlytics, we have not encountered this in our dev env.

minSdkVersion: 19
compileSdkVersion: 31
targetSdkVersion: 31

Brand:Xiaomi
Model:Redmi Note 11E
Orientation: Portrait
RAM free: 1.12 GB
Disk free: 65.15 GB
Version:Android 12
Orientation: Portrait
Rooted:No

#### Relevant Code:

```
FirebaseModelDownloader.getInstance(FirebaseApp.getInstance())
        .getModel(modelName, DownloadType.LOCAL_MODEL, new CustomModelDownloadConditions.Builder().build())
        .addOnSuccessListener(model -> {
            ...
        })
.addOnFailureListener(new OnFailureListener() {
    @Override
    public void onFailure(@NonNull Exception e) {
        ...
    }
});
```

#### Stacktrace:
```
java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.DOWNLOAD_COMPLETE flg=0x10 pkg=com.example.test (has extras) } in com.google.firebase.ml.modeldownloader.internal.ModelFileDownloadService$DownloadBroadcastReceiver@e8b576e
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1726)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8291)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
Caused by: java.lang.IllegalArgumentException: column local_filename is not allowed in queries
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:481)
	at android.content.ContentResolver.query(ContentResolver.java:1219)
	at android.content.ContentResolver.query(ContentResolver.java:1151)
	at android.content.ContentResolver.query(ContentResolver.java:1107)
	at android.app.DownloadManager$Query.runQuery(DownloadManager.java:1506)
	at android.app.DownloadManager.query(DownloadManager.java:1736)
	at android.app.DownloadManager.query(DownloadManager.java:1718)
	at com.google.firebase.ml.modeldownloader.internal.ModelFileDownloadService.getDownloadingModelStatusCode(SourceFile:30)
	at com.google.firebase.ml.modeldownloader.internal.ModelFileDownloadService$DownloadBroadcastReceiver.onReceive(SourceFile:40)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$<truncated: 67 chars>
```

**Comment by argzdev** [comment]
Hi @sandeep5193, thanks for reporting. I'm also unable to reproduce this behavior. Is this impacting a lot of users or does it only happen occasionally?

Just adding notes:
https://github.com/firebase/firebase-android-sdk/blob/dc5f291b8b6fb10d478972ec64928e345b6c70b6/firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/ModelFileDownloadService.java#L315

**Comment by sandeep5193** [comment]
Very very rarely. This is the only instance amongst thousands.

**Comment by argzdev** [comment]
Thanks for the extra details, @sandeep5193. Upon investigating, it seems that the main issue is somewhere within the native Android OS retrieving the `COLUMN_LOCAL_FILENAME` in `DownloadManager`. I did also notice that `COLUMN_LOCAL_FILENAME` is now deprecated.

That said, there's not much our SDK can do to avoid this issue, since we are not using `COLUMN_LOCAL_FILENAME` directly, and this is the default way of filtering by Id e.g. `setFilterById(downloadingId)`.

I'll close this issue now since the issue is not specifically in the SDK. Feel free to ask this to be reopened if you think this is a mistake. Thanks!

**Comment by sandeep5193** [comment]
Thanks for the update, @argzdev.
