### ISSUE TITLE
FirebaseFirestoreException: Failed to get document because the client is offline

### ISSUE THREAD

**Issue by MattSkala** [firebase/firebase-android-sdk#4243]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 2021.3.1
  * Firebase Component: Firestore
  * Component version: BOM 30.5.0

#### Steps to reproduce:

We started receiving the following error in Crashlytics: "FirebaseFirestoreException: Failed to get document because the client is offline.". While is has now become the most frequently reported crash for us, we are not able to reproduce the issue manually. From Crashlytics, I can see the issue is independent on Android version (Android 6-13 is affected). In 90%, the app crashes while it is in background. The issue first started to occur after updating from BOM 30.4.0 to 30.5.0.

#### Relevant Code:

```
Fatal Exception: com.google.firebase.firestore.FirebaseFirestoreException: Failed to get document because the client is offline.
       at com.google.firebase.firestore.DocumentReference.lambda$getViaSnapshotListener$1(DocumentReference.java:331)
       at com.google.firebase.firestore.DocumentReference.$r8$lambda$JLiNJSy6zGpjGmq5sIYGMxAaE1Q(DocumentReference.java)
       at com.google.firebase.firestore.DocumentReference$$InternalSyntheticLambda$2$deeb9cef11aaf51a672f73933ebf08e363410d4a63d1e8bcbab67d2a2479940b$0.onEvent(DocumentReference.java:8)
       at com.google.firebase.firestore.DocumentReference.lambda$addSnapshotListenerInternal$2(DocumentReference.java:504)
       at com.google.firebase.firestore.DocumentReference.$r8$lambda$GF131yLOtm0PQYErAZvV1mYKmvw(DocumentReference.java)
       at com.google.firebase.firestore.DocumentReference$$InternalSyntheticLambda$2$feddb62145f7d990036014571ac6591ce8b0a89d966901867b31905c367143a2$0.onEvent(DocumentReference.java:6)
       at com.google.firebase.firestore.core.AsyncEventListener.lambda$onEvent$0(AsyncEventListener.java:42)
       at com.google.firebase.firestore.core.AsyncEventListener.$r8$lambda$DNkggu2LY54oguDvcp-QtRg6Sfg(AsyncEventListener.java)
       at com.google.firebase.firestore.core.AsyncEventListener$$InternalSyntheticLambda$3$f393f672ebf20f7ef590d3940e8d44c2309180762ff06e3ce8b88b62d96fcbd3$0.run(AsyncEventListener.java:6)
       at androidx.profileinstaller.ProfileInstallReceiver$$InternalSyntheticLambda$1$badc508ffeba965baff33caef0f9caaa937087f4a11941b2d227a4d43e062ce8$0.execute(ProfileInstallReceiver.java)
       at com.google.firebase.firestore.core.AsyncEventListener.onEvent(AsyncEventListener.java:39)
       at com.google.firebase.firestore.core.QueryListener.raiseInitialEvent(QueryListener.java:176)
       at com.google.firebase.firestore.core.QueryListener.onOnlineStateChanged(QueryListener.java:116)
       at com.google.firebase.firestore.core.EventManager.handleOnlineStateChange(EventManager.java:178)
       at com.google.firebase.firestore.core.SyncEngine.handleOnlineStateChange(SyncEngine.java:376)
       at com.google.firebase.firestore.core.MemoryComponentProvider$RemoteStoreCallback.handleOnlineStateChange(MemoryComponentProvider.java:119)
       at com.google.firebase.firestore.remote.RemoteStore$$InternalSyntheticLambda$2$c3674617d9104a8f7bb0cb997b18ee75c709d2de5f865108a115ea1e44414c83$0.handleOnlineStateChange(RemoteStore.java:2)
       at com.google.firebase.firestore.remote.OnlineStateTracker.setAndBroadcastState(OnlineStateTracker.java:181)
       at com.google.firebase.firestore.remote.OnlineStateTracker.lambda$handleWatchStreamStart$0(OnlineStateTracker.java:121)
       at com.google.firebase.firestore.remote.OnlineStateTracker.$r8$lambda$Z_inAPSt-dbOU9F23LrnrNMwSCw(OnlineStateTracker.java)
       at com.google.firebase.firestore.remote.OnlineStateTracker$$InternalSyntheticLambda$3$c1c3533a8f2ff9cbf5c26a58056a997916a66e4f977752e7fc824270b6d12eb2$0.run(OnlineStateTracker.java:2)
       at com.google.firebase.firestore.util.AsyncQueue$DelayedTask.handleDelayElapsed(AsyncQueue.java:144)
       at com.google.firebase.firestore.util.AsyncQueue$DelayedTask.$r8$lambda$9BXioagktdupZWFTAaXUZGAu7Gk(AsyncQueue.java)
       at com.google.firebase.firestore.util.AsyncQueue$DelayedTask$$InternalSyntheticLambda$3$679041c538a9a57a389a9f0ff666389095eea255d0fe580d3365bb9dde02243d$0.run(AsyncQueue.java:2)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:234)
       at java.lang.Thread.run(Thread.java:919)
```

**Comment by argzdev** [comment]
Hi @MattSkala, thanks for reporting. Upon checking the [release notes](https://firebase.google.com/support/release-notes/android#firestore_v24-3-1), it looks like the only change from BoM version 30.4.0 (Firestore version 24.3.0) to 30.5.0 (Firestore version 24.3.1) is the update of dependency of io.grpc.* to its latest version (v1.48.1), so It's possible that the issue came from the grpc dependency. I'll notify our team and ask if this is the case.

**Comment by MattSkala** [comment]
@argzdev We'll try to downgrade grpc in the next release to see if it helps.

I don't think the SO link is relevant, as it crashes in the Firestore internal code and `onCompleteListener`/`onFailureListener` is not called at all.

**Comment by argzdev** [comment]
Hi @MattSkala, checking the source code for `getViaSnapshotListener`. The listener captures this type of error. You should be able to receive the exception in `onFailureListener`, so instead of using `onCompleteListener`, you can use `OnSuccessListener` and `OnFailureListener` separately.

https://github.com/firebase/firebase-android-sdk/blob/a0fcca1b629e3fc2333a452aa847d8c30caa3ea8/firebase-firestore/src/main/java/com/google/firebase/firestore/DocumentReference.java#L302-L309

https://github.com/firebase/firebase-android-sdk/blob/a0fcca1b629e3fc2333a452aa847d8c30caa3ea8/firebase-firestore/src/main/java/com/google/firebase/firestore/DocumentReference.java#L331-L334
