### ISSUE TITLE
Remote Config Failure ANR

### ISSUE THREAD

**Issue by onkarmonks** [firebase/firebase-android-sdk#4267]
We can see an ANR in our crashlytics report inside 'addOnFailureListener' function for remote config.

Please find our code implementation below - 

`remoteConfig.fetchAndActivate()
                .addOnCompleteListener(this) { task ->
                    if (task.isSuccessful) {
                        //success code
                    } else {
                        resumeApp()
                    }
                }
                .addOnFailureListener {
                    resumeApp()
                }
                .addOnCanceledListener {
                    resumeApp()
                }`

Please find the logs below

 at com.google.android.gms.tasks.zzl.<init>(zzl.java)
       at com.google.android.gms.tasks.zzw.addOnFailureListener(zzw.java:6)
       at com.google.android.gms.tasks.zzw.addOnFailureListener(zzw.java:5)
       at com.tatadigital.tcp.registration.ui.activity.SplashActivity.useRemoteConfig(SplashActivity.java:241)
       at com.tatadigital.tcp.registration.ui.activity.SplashActivity.branchReferralInitListener$lambda-5(SplashActivity.java:207)
       at com.tatadigital.tcp.registration.ui.activity.SplashActivity.$r8$lambda$8uIby_EAy83rMKa0oWwZohFbBDQ(SplashActivity.java:10241)
       at com.tatadigital.tcp.registration.ui.activity.SplashActivity$$ExternalSyntheticLambda6.onInitFinished(SplashActivity.java)
       at io.branch.referral.ServerRequestRegisterInstall.onRequestSucceeded(ServerRequestRegisterInstall.java:92)
       at io.branch.referral.BranchPostTask.onRequestSuccess(BranchPostTask.java:160)
       at io.branch.referral.BranchPostTask.onPostExecuteInner(BranchPostTask.java:80)
       at io.branch.referral.BranchPostTask.onPostExecute(BranchPostTask.java:64)
       at io.branch.referral.BranchPostTask.onPostExecute(BranchPostTask.java:21)
       at android.os.AsyncTask.finish(AsyncTask.java:771)
       at android.os.AsyncTask.access$900(AsyncTask.java:199)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:263)
       at android.app.ActivityThread.main(ActivityThread.java:8292)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)

**Comment by argzdev** [comment]
Hi @onkarmonks, thanks for reporting. What version of remote config are you using? If it's not the latest version `21.2.0`, could try using the latest version and see if that works? We usually recommend this to avoid bugs/issues that have been previously resolved in the most recent versions.

Also any chance you could share a [MCVE](https://stackoverflow.com/help/minimal-reproducible-example)?
