### ISSUE TITLE
Firestore instance creation getting crashed in direct boot mode in android

### ISSUE THREAD

**Issue by jayakrishna-zebra** [firebase/firebase-android-sdk#4295]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel] (https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

While initializing the fire-store in direct boot mode in android, app getting crashed.

Steps : 
          1. In A13 device setup pin lock from setting 
          2. BootCompleteReceiver is directBootAware and listen for the LOCKED_BOOT_COMPLETED event.
           
        <receiver
            android:name="a.b.c.BootCompleteReceiver"
            android:directBootAware="true"
            android:enabled="true"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
                <action android:name="android.intent.action.LOCKED_BOOT_COMPLETED" />
            </intent-filter>
        </receiver>
       3. trying to create the firestore instance 
  
  * Android Studio version: Android Studio Chipmunk | 2021.2.1 Patch 1
  * Firebase Component: com.google.firebase:firebase-firestore:22.1.2
  * Component version: _____

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

App getting crash while initialising the firestore in direct boot mode. with below crash 

Caused by: java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user is unlocked
        at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:572)
        at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:557)
        at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:217)
        at com.google.firebase.auth.internal.zzbi.<init>(com.google.firebase:firebase-auth@@20.0.0:6)
        at com.google.firebase.auth.FirebaseAuth.<init>(com.google.firebase:firebase-auth@@20.0.0:12)
        at com.google.firebase.auth.internal.zzv.<init>(com.google.firebase:firebase-auth@@20.0.0:1)
        at com.google.firebase.auth.zzs.create(com.google.firebase:firebase-auth@@20.0.0:3)
        at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0(ComponentRuntime.java:132)
        at com.google.firebase.components.ComponentRuntime$$Lambda$1.get(Unknown Source:4)
        at com.google.firebase.components.Lazy.get(Lazy.java:53)
        at com.google.firebase.firestore.auth.FirebaseAuthCredentialsProvider.lambda$new$1(FirebaseAuthCredentialsProvider.java:81)
        at com.google.firebase.firestore.auth.FirebaseAuthCredentialsProvider$$Lambda$2.handle(Unknown Source:2)
        at com.google.firebase.components.OptionalProvider.whenAvailable(OptionalProvider.java:77)
        at com.google.firebase.firestore.auth.FirebaseAuthCredentialsProvider.<init>(FirebaseAuthCredentialsProvider.java:78)
        at com.google.firebase.firestore.FirebaseFirestore.newInstance(FirebaseFirestore.java:132)
        at com.google.firebase.firestore.FirestoreMultiDbComponent.get(FirestoreMultiDbComponent.java:65)
        at com.google.firebase.firestore.FirebaseFirestore.getInstance(FirebaseFirestore.java:113)
        at com.google.firebase.firestore.FirebaseFirestore.getInstance(FirebaseFirestore.java:104)

```
// TODO(you): code here to reproduce the problem
```

**Comment by ehsannas** [comment]
@avolkovi It seems that this is because of auth trying to access shared preferences. Can you route this to the right person to take a look?

**Comment by vkryachko** [comment]
fwiw, if auth was not present in the app, Firestore itself would cause the crash, since it would not have been able to access its sqlite db on disk.

As a whole, the only Firebase product that supports direct boot mode is firebase-messaging-directboot, no other product works in direct boot mode.

**Comment by ehsannas** [comment]
Yes, Thanks for confirming this @vkryachko . There is currently no plan to support direct boot mode. I will close this issue as it's being tracked internally. Googlers see b/258629617.
