### ISSUE TITLE
FirebaseRemoteConfigClientException: The client had an error while calling the backend!

### ISSUE THREAD

**Issue by kolesnikov-pasha** [firebase/firebase-android-sdk#4334]
#### Environment

  * Android Studio version: Android Studio Dolphin | 2021.3.1 Beta 2 (Build #AI-213.7172.25.2113.8622536, built on May 20, 2022)
  * Firebase Component: Firebase remote config (Database, Firestore, Storage, Functions, etc)
  * Component version: firebaseBom = "30.1.0", 

#### Steps to reproduce:
```
Fatal Exception: com.google.firebase.remoteconfig.FirebaseRemoteConfigClientException: The client had an error while calling the backend!
       at com.google.firebase.remoteconfig.internal.ConfigFetchHttpClient.fetch(ConfigFetchHttpClient.java:208)
       at com.google.firebase.remoteconfig.internal.ConfigFetchHandler.fetchFromBackend(ConfigFetchHandler.java:312)
       at com.google.firebase.remoteconfig.internal.ConfigFetchHandler.fetchFromBackendAndCacheResponse(ConfigFetchHandler.java:283)
       at com.google.firebase.remoteconfig.internal.ConfigFetchHandler.lambda$fetchIfCacheExpiredAndNotThrottled$1$com-google-firebase-remoteconfig-internal-ConfigFetchHandler(ConfigFetchHandler.java:220)
       at com.google.firebase.remoteconfig.internal.ConfigFetchHandler$$ExternalSyntheticLambda1.then(:8)
       at com.google.android.gms.tasks.zze.run(com.google.android.gms:play-services-tasks@@18.0.1:1)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:920)
Caused by java.net.UnknownHostException: Unable to resolve host "firebaseremoteconfig.googleapis.com": No address associated with hostname
       at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
       at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
       at java.net.InetAddress.getAllByName(InetAddress.java:1152)
       at com.android.okhttp.Dns$1.lookup(Dns.java:41)
       at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:178)
       at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:144)
       at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:86)
       at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:176)
       at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
       at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:219)
       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:30)
       at com.google.firebase.remoteconfig.internal.ConfigFetchHttpClient.setFetchRequestBody(ConfigFetchHttpClient.java:364)
       at com.google.firebase.remoteconfig.internal.ConfigFetchHttpClient.fetch(ConfigFetchHttpClient.java:196)
       at com.google.firebase.remoteconfig.internal.ConfigFetchHandler.fetchFromBackend(ConfigFetchHandler.java:312)
       at com.google.firebase.remoteconfig.internal.ConfigFetchHandler.fetchFromBackendAndCacheResponse(ConfigFetchHandler.java:283)
       at com.google.firebase.remoteconfig.internal.ConfigFetchHandler.lambda$fetchIfCacheExpiredAndNotThrottled$1$com-google-firebase-remoteconfig-internal-ConfigFetchHandler(ConfigFetchHandler.java:220)
       at com.google.firebase.remoteconfig.internal.ConfigFetchHandler$$ExternalSyntheticLambda1.then(:8)
       at com.google.android.gms.tasks.zze.run(com.google.android.gms:play-services-tasks@@18.0.1:1)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:920)
Caused by android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
       at libcore.io.Linux.android_getaddrinfo(Linux.java)
       at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:136)
       at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:221)
       at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:136)
       at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
       at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
       at java.net.InetAddress.getAllByName(InetAddress.java:1152)
       at com.android.okhttp.Dns$1.lookup(Dns.java:41)
       at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:178)
       at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:144)
       at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:86)
       at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:176)
       at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
       at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:219)
       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:30)
       at com.google.firebase.remoteconfig.internal.ConfigFetchHttpClient.setFetchRequestBody(ConfigFetchHttpClient.java:364)
       at com.google.firebase.remoteconfig.internal.ConfigFetchHttpClient.fetch(ConfigFetchHttpClient.java:196)
       at com.google.firebase.remoteconfig.internal.ConfigFetchHandler.fetchFromBackend(ConfigFetchHandler.java:312)
       at com.google.firebase.remoteconfig.internal.ConfigFetchHandler.fetchFromBackendAndCacheResponse(ConfigFetchHandler.java:283)
       at com.google.firebase.remoteconfig.internal.ConfigFetchHandler.lambda$fetchIfCacheExpiredAndNotThrottled$1$com-google-firebase-remoteconfig-internal-ConfigFetchHandler(ConfigFetchHandler.java:220)
       at com.google.firebase.remoteconfig.internal.ConfigFetchHandler$$ExternalSyntheticLambda1.then(:8)
       at com.google.android.gms.tasks.zze.run(com.google.android.gms:play-services-tasks@@18.0.1:1)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:920)
```

**Comment by kolesnikov-pasha** [comment]
Unfortunately, I don't know how to reproduce this. The log is from crashlytics. 

Code snippet:
```
FirebaseRemoteConfigFeatureToggleManager(
    firebaseRemoteConfig = FirebaseRemoteConfig.getInstance(),
    localStorage = storage("features", StorageType.PERSISTENT)
)
```

```
import android.util.Log
import com.google.firebase.remoteconfig.FirebaseRemoteConfig
import com.mynalabs.system.storage.Storage
import kotlinx.coroutines.*
import kotlinx.coroutines.tasks.await

class FirebaseRemoteConfigFeatureToggleManager(
    private val firebaseRemoteConfig: FirebaseRemoteConfig,
    private val localStorage: Storage<FeaturesWrapper> // its a wrapper for shared prefs
) : FeatureToggleManager {

    private var prepared = false

    init {
        GlobalScope.launch(Dispatchers.Default) {
            val isActivated = firebaseRemoteConfig.fetchAndActivate().await()
            prepared = true
            Log.d("FeatureToggleManager", "prepareIfNecessary: isActivated $isActivated")
        }
    }

    override fun set(key: String, value: Boolean) {
        runBlocking {
            val updatedLocal = localStorage.getOrNull()?.features.orEmpty().toMutableMap().apply {
                set(key, value)
            }

            localStorage.update(FeaturesWrapper(updatedLocal))
        }
    }

    override fun isUserAffected(key: String, defaultValue: Boolean): Boolean {
        val local = runBlocking(Dispatchers.Default) { getLocalValueOrNull(key) }
        val remote = getRemoteValueOrNull(key)
        val result = local ?: remote ?: defaultValue
        Log.d("FeatureToggleManager", "isUserAffected: local $local remote $remote defaultValue $defaultValue prepared $prepared")
        return result
    }

    private suspend fun getLocalValueOrNull(key: String): Boolean? {
        return localStorage.getOrNull()?.features?.get(key)
    }

    private fun getRemoteValueOrNull(key: String): Boolean? {
        return firebaseRemoteConfig.getValue(key)
            .takeIf { it.source == FirebaseRemoteConfig.VALUE_SOURCE_REMOTE }
            ?.asBoolean()
    }

}
```

**Comment by argzdev** [comment]
Thanks for the extra details, @kolesnikov-pasha. I saw a [similar](https://github.com/firebase/firebase-android-sdk/issues/4010#issuecomment-1221229236) case before, I'm wondering if this has the same impact on your case where the usage of `Function.await()` is causing these type of issues.

> However, a long analysis reveals the cause. This is because the sudden number of Network Issue logs to Crashlytics was exposed to the risk of Failure as it was changed from the method using `Function.addSuccessListener` and `Function.addFailureListener` to `Function.await()`.
It seems to be possible to fix it with try-catch . Thanks for your help.

Could you try the solution provided in the post and see if that helps with your issue?
A. Change `await()` to `addFailureListener` or `addSuccessListener`
B. Using a try-catch

**Comment by kolesnikov-pasha** [comment]
Okay! Thank you for idea! we'll publish a hotfix and go back here with results

**Comment by argzdev** [comment]
Sure, let me know what happens with the results. I'll add a `needs-info` tag for now while waiting. Don't worry if this closes due to stale, we can always reopen this once we have further information.

**Comment by kolesnikov-pasha** [comment]
@argzdev Looks like it solved the issue! Thank you:)
