### ISSUE TITLE
zzee.java line 1 com.google.android.gms.internal.measurement.zzee.zzg

### ISSUE THREAD

**Issue by mohanK22** [firebase/firebase-android-sdk#4438]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Dolphin | 2021.3.1 Patch 1 (Build #AI-213.7172.25.2113.9123335, built on September 30, 2022)
  * Firebase Component: com.google.firebase:firebase-analytics-ktx, 
  * Component version: 21.2.0

### [REQUIRED] Step 3: Describe the problem
Hi,
we are getting the root blocking ANR issue on the release build, reported on the Firebase Crashlytics Dashboard.

#### Steps to reproduce: -- unable to reproduce the issue.
Please find the below logs and other details.
```
main (runnable):tid=1 systid=31432 
       at com.google.android.gms.internal.measurement.zzee.zzg(zzee.java:1)
       at com.google.firebase.analytics.connector.AnalyticsConnectorImpl.getInstance(AnalyticsConnectorImpl.java:12)
       at com.google.firebase.analytics.connector.internal.AnalyticsConnectorRegistrar.lambda$getComponents$0(AnalyticsConnectorRegistrar.java:4)
       at com.google.firebase.analytics.connector.internal.zzb.create(zzb.java)
       at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0$com-google-firebase-components-ComponentRuntime(ComponentRuntime.java:132)
       at com.google.firebase.components.ComponentRuntime$$ExternalSyntheticLambda1.get(ComponentRuntime.java:1132)
       at com.google.firebase.components.Lazy.get(Lazy.java:53)
       at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents(ComponentRuntime.java:291)
       at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(ComponentRuntime.java:281)
       at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:594)
       at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:305)
       at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:269)
       at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:254)
       at com.google.firebase.provider.FirebaseInitProvider.onCreate(FirebaseInitProvider.java:51)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2388)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2358)
       at com.google.firebase.provider.FirebaseInitProvider.attachInfo(FirebaseInitProvider.java:45)
       at android.app.ActivityThread.installProvider(ActivityThread.java:7841)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:7371)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7279)
       at android.app.ActivityThread.access$1700(ActivityThread.java:299)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2184)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:264)
       at android.app.ActivityThread.main(ActivityThread.java:8312)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
```
<img width="417" alt="Screenshot 2022-12-09 at 12 43 36 PM" src="https://user-images.githubusercontent.com/58304180/206646439-18032d26-7620-4eef-b1d3-f97dbfc3fc11.png"> <img width="408" alt="Screenshot 2022-12-09 at 12 43 56 PM" src="https://user-images.githubusercontent.com/58304180/206646477-5f2e4bb6-9360-4af3-ad90-51ff801eb315.png"> <img width="403" alt="Screenshot 2022-12-09 at 12 44 04 PM" src="https://user-images.githubusercontent.com/58304180/206646495-b9beab18-6347-4139-9e23-0ca0ae6297a1.png">

**Comment by argzdev** [comment]
Thanks for reporting, @mohanK22. Any code snippets you can share that's related to Firebase Analytics? It might give us a hint to what's causing the issue.

**Comment by mohanK22** [comment]
we are initializing the Firebase in the application class on the `onCreate()` function in the following way.

`FirebaseApp.initializeApp(this)`


For Firebase Analytics, we have created a common class.

```
import android.os.Bundle
import com.google.firebase.analytics.FirebaseAnalytics
import com.google.firebase.analytics.ktx.analytics
import com.google.firebase.ktx.Firebase

object FirebaseAnalyticsManager {

    private var firebaseAnalytics: FirebaseAnalytics? = null

    init {
        firebaseAnalytics = Firebase.analytics
    }

    fun trackFirebaseEvents(eventName: String, bundleData: Bundle?){
        firebaseAnalytics?.logEvent(eventName, bundleData)
    }

    fun setFirebaseAnalyticsUserId(userId: String) {
        firebaseAnalytics?.setUserId(userId)
    }
}
```

**Comment by argzdev** [comment]
Thanks for the code snippet, @mohanK22. From what I can tell with your code snippet it shouldn't cause any issues. While I investigate this, may I ask if you also observed this issue on a previous version of Analytics?

**Comment by mohanK22** [comment]
This ANR started causing issues from the analytics version "21.1.0". so we updated the library version "21.2.0". Now it is also causing in the latest build.

 fyi -- Earlier we were using "20.1.2" which was completely working fine with no ANR and no crash.

**Comment by argzdev** [comment]
Thanks for the extra details, @mohanK22. Checking our [release notes](https://firebase.google.com/support/release-notes/android#analytics_v21-0-0), I noticed that there are 2 changes before your ANR started.

- `21.0.0` - BREAKING CHANGE: Removed deprecated ecommerce constants. Learn more about [measuring ecommerce](https://firebase.google.com/docs/analytics/measure-ecommerce) with Google Analytics 4.
- `21.1.0` - Improved [session measurement with user ID](https://support.google.com/analytics/answer/9213390).

Are you using any of the following deprecated ecommerce constants? If not, then most likely the changes for `21.1.0` is causing the issue.

The following constants were removed from FirebaseAnalytics.Event:
- CHECKOUT_PROGRESS
- ECOMMERCE_PURCHASE
- PRESENT_OFFER
- PURCHASE_REFUND
- SET_CHECKOUT_OPTION

The following constants were removed from FirebaseAnalytics.Param:
- CHECKOUT_OPTION
- CHECKOUT_STEP
- ITEM_LIST
- ITEM_LOCATION_ID
- SIGN_UP_METHOD

**Comment by mohanK22** [comment]
Hi @argzdev,
we are not consuming any of the above constants from the analytics SDK. we have created our own constant and consume it.

**Comment by argzdev** [comment]
Then the issue might be with `21.1.0` - Improved [session measurement with user ID](https://support.google.com/analytics/answer/9213390). Let me consult with our engineers, and get back to you once I get some updates.

**Comment by argzdev** [comment]
Hi @mohanK22, sorry for the long wait. May I know which Firebase Crashlytics version are you using? Upon our investigation, it seems that the issue might be related to #4345. This is currently being worked out, so let's leave this issue open for now and see if this gets resolved once the fix for Crashlytics is out.

**Comment by argzdev** [comment]
Hey @mohanK22. Just bumping this thread, it seems that there has been updates with out libraries for sometime now. Can you try using our latest version and see if it helps? `21.2.2`
