### ISSUE TITLE
Null pointer exceptions in firebase auth

### ISSUE THREAD

**Issue by souragar1988** [firebase/firebase-android-sdk#4454]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android 12
  * Firebase Component: Firebase Auth
  * Component version: 30.5.0 bom version

### [REQUIRED] Step 3: Describe the problem
Some of the users on android 12 is getting these null pointer exception crashes 
com.google.android.gms.internal.firebase-auth-api.zzqx: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String ub.t0.j1()' on a null object reference
        at com.google.firebase.auth.internal.zzbg.zzd(com.google.firebase:firebase-auth@@21.1.0:32)
        at com.google.firebase.auth.FirebaseAuth.zzH(com.google.firebase:firebase-auth@@21.1.0:13)
        at com.google.firebase.auth.zzn.zza(com.google.firebase:firebase-auth@@21.1.0:1)
        at com.google.android.gms.internal.firebase-auth-api.zzvp.zzb(com.google.firebase:firebase-auth@@21.1.0:3)
        at com.google.android.gms.internal.firebase-auth-api.zzyb.zzj(com.google.firebase:firebase-auth@@21.1.0:1)
        at com.google.android.gms.internal.firebase-auth-api.zzxy.zzn(com.google.firebase:firebase-auth@@21.1.0:2)
        at com.google.android.gms.internal.firebase-auth-api.zzxa.zzn(com.google.firebase:firebase-auth@@21.1.0:1)
        at com.google.android.gms.internal.firebase-auth-api.zzty.zzb(com.google.firebase:firebase-auth@@21.1.0:2)
        at com.google.android.gms.internal.firebase-auth-api.zzyj.zzb(com.google.firebase:firebase-auth@@21.1.0:12)
        at com.google.android.gms.internal.firebase-auth-api.zzyj.zza(com.google.firebase:firebase-auth@@21.1.0:14)
        at com.google.android.gms.internal.firebase-auth-api.zzxp.zzf(com.google.firebase:firebase-auth@@21.1.0:4)
        at com.google.android.gms.internal.firebase-auth-api.zzvf.zzp(com.google.firebase:firebase-auth@@21.1.0:4)
        at com.google.android.gms.internal.firebase-auth-api.zzxb.zzj(com.google.firebase:firebase-auth@@21.1.0:5)
        at com.google.android.gms.internal.firebase-auth-api.zzvp.zzc(com.google.firebase:firebase-auth@@21.1.0:1)
        at com.google.android.gms.internal.firebase-auth-api.zzyc.run(com.google.firebase:firebase-auth@@21.1.0:1)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784)

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String ub.t0.j1()' on a null object reference
        at com.google.firebase.auth.internal.zzbg.zzd(com.google.firebase:firebase-auth@@21.1.0:16)
        at com.google.firebase.auth.FirebaseAuth.zzH(com.google.firebase:firebase-auth@@21.1.0:13)
        at com.google.firebase.auth.zzn.zza(com.google.firebase:firebase-auth@@21.1.0:1)
        at com.google.android.gms.internal.firebase-auth-api.zzvp.zzb(com.google.firebase:firebase-auth@@21.1.0:3)
        at com.google.android.gms.internal.firebase-auth-api.zzyb.zzj(com.google.firebase:firebase-auth@@21.1.0:1)
        at com.google.android.gms.internal.firebase-auth-api.zzxy.zzn(com.google.firebase:firebase-auth@@21.1.0:2)
        at com.google.android.gms.internal.firebase-auth-api.zzxa.zzn(com.google.firebase:firebase-auth@@21.1.0:1)
        at com.google.android.gms.internal.firebase-auth-api.zzty.zzb(com.google.firebase:firebase-auth@@21.1.0:2)
        at com.google.android.gms.internal.firebase-auth-api.zzyj.zzb(com.google.firebase:firebase-auth@@21.1.0:12)
        at com.google.android.gms.internal.firebase-auth-api.zzyj.zza(com.google.firebase:firebase-auth@@21.1.0:14)
        at com.google.android.gms.internal.firebase-auth-api.zzxp.zzf(com.google.firebase:firebase-auth@@21.1.0:4)
        at com.google.android.gms.internal.firebase-auth-api.zzvf.zzp(com.google.firebase:firebase-auth@@21.1.0:4)
        at com.google.android.gms.internal.firebase-auth-api.zzxb.zzj(com.google.firebase:firebase-auth@@21.1.0:5)
        at com.google.android.gms.internal.firebase-auth-api.zzvp.zzc(com.google.firebase:firebase-auth@@21.1.0:1)
        at com.google.android.gms.internal.firebase-auth-api.zzyc.run(com.google.firebase:firebase-auth@@21.1.0:1)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784)
#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.
This is happening randomly
#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by argzdev** [comment]
Hi @souragar1988, thanks for reporting. It looks like BoM `30.5.0` is using Firebase Auth `21.0.8` and the latest version for BoM is `31.1.1` which has the equivalent Firebase Auth version `21.1.0`. Can you try using the latest version and see if this works?

I'm assuming you're unable to reproduce this behavior on your side, that said can you provide code snippets where you've used Firebase Auth? Maybe that'll give us a hint where the issue is occuring.
