### ISSUE TITLE
 Receiver not registered: com.google.firebase.messaging.SyncTask$ConnectivityChangeReceiver@4a2009e

### ISSUE THREAD

**Issue by xianjuren** [firebase/firebase-android-sdk#4481]
Android Studio version: 2021.3.1 Patch 1
  Firebase Component:
 "com.google.firebase:firebase-bom:31.0.1"
"com.google.firebase:firebase-messaging-ktx"
"com.google.firebase:firebase-analytics-ktx"
"com.google.firebase:firebase-crashlytics-ktx"
"com.google.firebase:firebase-perf"

Fatal Exception: java.lang.Error
FATAL EXCEPTION [main] Unity version : 2021.2.0f1 Device model : samsung SM-T225 Device fingerprint: samsung/gta7litexx/gta7lite:11/RP1A.200720.012/T225XXU1AUL1:user/release-keys Build Type : Release Scripting Backend : IL2CPP ABI : arm64-v8a Strip Engine Code : true

Fatal Exception: java.lang.Error: FATAL EXCEPTION [main]
Unity version     : 2021.2.0f1
Device model      : samsung SM-T225
Device fingerprint: samsung/gta7litexx/gta7lite:11/RP1A.200720.012/T225XXU1AUL1:user/release-keys
Build Type        : Release
Scripting Backend : IL2CPP
ABI               : arm64-v8a
Strip Engine Code : true

Caused by java.lang.RuntimeException
Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4200010 (has extras) } in com.google.firebase.messaging.SyncTask$ConnectivityChangeReceiver@4a2009e

Caused by java.lang.IllegalArgumentException
Receiver not registered: com.google.firebase.messaging.SyncTask$ConnectivityChangeReceiver@4a2009e

Caused by java.lang.IllegalArgumentException: Receiver not registered: com.google.firebase.messaging.SyncTask$ConnectivityChangeReceiver@4a2009e
       at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1523)
       at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1712)
       at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:733)
       at com.google.firebase.messaging.SyncTask$ConnectivityChangeReceiver.onReceive(SyncTask.java:192)
       at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1666)
       at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(:2)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8653)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by argzdev** [comment]
Hi @xianjuren, thanks for reporting. Are you able to reproduce this behavior locally? Any chance you could share a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) or code snippet when using Firebase Messaging?
