### ISSUE TITLE
App crashes due to IN APP MESSAGING on Main Screen 

### ISSUE THREAD

**Issue by mohit-Kalagato** [firebase/firebase-android-sdk#4499]
*  Android studio dolphin 
  * Firebase In-app messaging displays the latest BOM 31.1.1

`Fatal Exception: android.view.WindowManager$BadTokenException: Unable to add window -- token null for displayid = 0 is not valid; is your activity running?
       at android.view.ViewRootImpl.setView(ViewRootImpl.java:908)
       at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:372)
       at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:129)
       at com.google.firebase.inappmessaging.display.internal.FiamWindowManager.show(FiamWindowManager.java:67)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay$4$4.run(FirebaseInAppMessagingDisplay.java:410)
       at android.app.Activity.runOnUiThread(Activity.java:6507)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay$4.onSuccess(FirebaseInAppMessagingDisplay.java:406)
       at com.google.firebase.inappmessaging.display.internal.FiamImageLoader$Callback.onResourceReady(FiamImageLoader.java:157)
       at com.google.firebase.inappmessaging.display.internal.FiamImageLoader$Callback.onResourceReady(FiamImageLoader.java:135)
       at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:657)
       at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:596)
       at com.bumptech.glide.load.engine.Engine.load(Engine.java:220)
       at com.bumptech.glide.request.SingleRequest.onSizeReady(SingleRequest.java:468)
       at com.bumptech.glide.request.target.CustomTarget.getSize(CustomTarget.java:107)
       at com.bumptech.glide.request.SingleRequest.begin(SingleRequest.java:258)
       at com.bumptech.glide.manager.RequestTracker.runRequest(RequestTracker.java:41)
       at com.bumptech.glide.RequestManager.track(RequestManager.java:671)
       at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:813)
       at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:780)
       at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:771)
       at com.google.firebase.inappmessaging.display.internal.FiamImageLoader$FiamImageRequestCreator.into(FiamImageLoader.java:129)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay.loadNullableImage(FirebaseInAppMessagingDisplay.java:491)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay.inflateBinding(FirebaseInAppMessagingDisplay.java:344)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay.access$000(FirebaseInAppMessagingDisplay.java:79)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay$1.run(FirebaseInAppMessagingDisplay.java:286)
       at android.os.Handler.handleCallback(Handler.java:809)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7555)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)`

After initiating IN-APP Messaging Card type campaign I got this crash in firebase crashlytics on a very large number of users.
Please solved this issue maybe this is happening because of loading card image URL using glide.

**Comment by argzdev** [comment]
Hi @mohit-Kalagato, thanks for reporting. From my investigation, the issue might not be because of the glide library, but the culprit is that supplied URL is unable to load the images. I think there's 2 possible situations where this can happen:
1. There is a surge of requests to your image URL and your server cannot accommodate all the requests, which will eventually result to request failures.
2. Your server that is supplying the image URL have a long latency period which is causing the crash.

Perhaps you could try uploading images instead to avoid these issues. Let me know if that works. Thanks!

**Comment by mohit-Kalagato** [comment]
@argzdev Thanks for your reply I think you already described what is going wrong maybe we need to host the image URL on Firebase so that they can fetch easily.
