### ISSUE TITLE
WakeLock under-locked wake:com.google.firebase.messaging on HUAWAI

### ISSUE THREAD

**Issue by SteveBurkert** [firebase/firebase-android-sdk#4501]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Dolphin | 2021.3.1 Patch 1 Build #AI-213.7172.25.2113.9123335, built on September 30
  * Firebase Component: firebase-messaging
  * Component version: bom:31.1.1 -> com.google.firebase:firebase-messaging-ktx: 23.1.1

### [REQUIRED] Step 3: Describe the problem
```
Fatal Exception: java.lang.RuntimeException: WakeLock under-locked wake:com.google.firebase.messaging
       at android.os.PowerManager$WakeLock.release(PowerManager.java:1619)
       at android.os.PowerManager$WakeLock.release(PowerManager.java:1589)
       at android.os.PowerManager$WakeLock$1.run(PowerManager.java:1484)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:101)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7529)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
 ```      
 
Although this should be fixed in `20.1.6`, the bug is still occurring. 
Please see:
https://github.com/firebase/firebase-android-sdk/issues/1484

#### Steps to reproduce:

See Step 3

#### Relevant Code:

No relevant code

**Comment by argzdev** [comment]
Hi @SteveBurkert, thanks for bringing this up and checking on the latest version. I'll let our engineers know and see what we can do here.

**Comment by lehcar09** [comment]
Hi @SteveBurkert, are you still experiencing this issue in the latest Firebase SDK version? I tried reproducing it, however, I wasn't able to replicate the the issue.
