### ISSUE TITLE
Firebase Installations Strict Mode Violation: Explicit termination method 'end' not called

### ISSUE THREAD

**Issue by eygraber** [firebase/firebase-android-sdk#4583]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Flamingo Beta 1
  * Firebase Component: Installations
  * Component version: BOM 31.1.1

### [REQUIRED] Step 3: Describe the problem

I'm getting a Strict Mode violation on Android 33

#### Steps to reproduce:

I call `FirebaseInstallations.delete`

Here are the logs:

```
android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                 	at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1986)
                 	at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:336)
                 	at java.util.zip.Inflater.finalize(Inflater.java:407)
                 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:319)
                 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:306)
                 	at java.lang.Daemons$Daemon.run(Daemons.java:140)
                 	at java.lang.Thread.run(Thread.java:1012)
                 Caused by: java.lang.Throwable: Explicit termination method 'end' not called
                 	at dalvik.system.CloseGuard.openWithCallSite(CloseGuard.java:288)
                 	at dalvik.system.CloseGuard.open(CloseGuard.java:257)
                 	at java.util.zip.Inflater.<init>(Inflater.java:122)
                 	at com.android.okhttp.okio.GzipSource.<init>(GzipSource.java:64)
                 	at com.android.okhttp.internal.http.HttpEngine.unzip(HttpEngine.java:484)
                 	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:661)
                 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
                 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
                 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
                 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
                 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
                 	at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.deleteFirebaseInstallation(FirebaseInstallationServiceClient.java:326)
                 	at com.google.firebase.installations.FirebaseInstallations.deleteFirebaseInstallationId(FirebaseInstallations.java:604)
                 	at com.google.firebase.installations.FirebaseInstallations.$r8$lambda$ukIZcZ_XlkiT9OCDxQIhblgD6_Y(Unknown Source:0)
                 	at com.google.firebase.installations.FirebaseInstallations$$ExternalSyntheticLambda1.call(Unknown Source:2)
                 	at com.google.android.gms.tasks.zzz.run(com.google.android.gms:play-services-tasks@@18.0.2:1)
                 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                 	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by argzdev** [comment]
Thanks for reporting, @eygraber. I was able to reproduce the same behavior, I'll notify our engineers.

**Comment by WonderCsabo** [comment]
I can also reproduce this problem. @argzdev

**Comment by lehcar09** [comment]
Hi folks! I tried reproducing this issue and I wasn’t encountering the issue anymore. 

I’ll be closing this issue now. Let us know if there’s any misunderstanding so we can re-open the issue. Or, Please feel free to open a new issue if this still occurs. Thanks!
