### ISSUE TITLE
Getting crash with Firebase in-app messaging without secondary action

### ISSUE THREAD

**Issue by sscatch20** [firebase/firebase-android-sdk#4625]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Electric Eel 2022.1.1
  * Firebase Component: Firebase in-app messaging
  * Component version: 20.2.0 (Bom 31.0.2)

### [REQUIRED] Step 3: Describe the problem

Getting crash with Firebase in-app messaging when specify campaign need to show
The log show secondary action must be null or have a button
But the issue happened when it trigger a specify campaign, and the campaign has 2 buttons.
However, copy the campaign, or create same new campaign, can't reproduce the issue.

10:25:03.088  E  FATAL EXCEPTION: main
                 Process: com.catchplay.asiaplay, PID: 32750
                 io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.IllegalArgumentException: Card model secondary action must be null or have a button
                 	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
                 	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
                 	at io.reactivex.internal.subscribers.LambdaSubscriber.onError(LambdaSubscriber.java:79)
                 	at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.checkTerminated(FlowableObserveOn.java:209)
                 	at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:399)
                 	at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
                 	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
                 	at android.os.Handler.handleCallback(Handler.java:938)
                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                 	at android.os.Looper.loopOnce(Looper.java:226)
                 	at android.os.Looper.loop(Looper.java:313)
                 	at android.app.ActivityThread.main(ActivityThread.java:8663)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
                 Caused by: java.lang.IllegalArgumentException: Card model secondary action must be null or have a button
                 	at com.google.firebase.inappmessaging.model.CardMessage$Builder.build(CardMessage.java:249)
                 	at com.google.firebase.inappmessaging.model.ProtoMarshallerClient.decode(ProtoMarshallerClient.java:231)
                 	at com.google.firebase.inappmessaging.internal.InAppMessageStreamManager.triggeredInAppMessage(InAppMessageStreamManager.java:365)
                 	at com.google.firebase.inappmessaging.internal.InAppMessageStreamManager.lambda$getTriggeredInAppMessageMaybe$27(InAppMessageStreamManager.java:341)
                 	at com.google.firebase.inappmessaging.internal.InAppMessageStreamManager.$r8$lambda$w4tUspl0-bTh48AvRyCAZ0a1mSM(Unknown Source:0)
                 	at com.google.firebase.inappmessaging.internal.InAppMessageStreamManager$$ExternalSyntheticLambda16.apply(Unknown Source:6)
                 	at io.reactivex.internal.operators.maybe.MaybeFlatten$FlatMapMaybeObserver.onSuccess(MaybeFlatten.java:88)
                 	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onNext(FlowableElementAtMaybe.java:80)
                 	at io.reactivex.internal.operators.flowable.FlowableFlattenIterable$FlattenIterableSubscriber.drain(FlowableFlattenIterable.java:312)
                 	at io.reactivex.internal.operators.flowable.FlowableFlattenIterable$FlattenIterableSubscriber.onNext(FlowableFlattenIterable.java:174)
                 	at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:56)
                 	at io.reactivex.internal.subscriptions.DeferredScalarSubscription.complete(DeferredScalarSubscription.java:117)
                 	at io.reactivex.internal.operators.flowable.FlowableToList$ToListSubscriber.onComplete(FlowableToList.java:84)
                 	at io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber.drainLoop(FlowableFlatMapMaybe.java:327)
                 	at io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber.drain(FlowableFlatMapMaybe.java:280)
                 	at io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber.onComplete(FlowableFlatMapMaybe.java:152)
                 	at io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber.drainLoop(FlowableFlatMapMaybe.java:327)
                 	at io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber.drain(FlowableFlatMapMaybe.java:280)
10:25:03.089  E  	at io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber.onComplete(FlowableFlatMapMaybe.java:152)
                 	at io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber.drainLoop(FlowableFlatMapMaybe.java:327)
                 	at io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber.drain(FlowableFlatMapMaybe.java:280)
                 	at io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber.onComplete(FlowableFlatMapMaybe.java:152)
                 	at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onComplete(BasicFuseableSubscriber.java:120)
                 	at io.reactivex.internal.subscribers.BasicFuseableConditionalSubscriber.onComplete(BasicFuseableConditionalSubscriber.java:119)
                 	at io.reactivex.internal.operators.flowable.FlowableFromIterable$IteratorConditionalSubscription.fastPath(FlowableFromIterable.java:333)
                 	at io.reactivex.internal.operators.flowable.FlowableFromIterable$BaseRangeSubscription.request(FlowableFromIterable.java:122)
                 	at io.reactivex.internal.subscribers.BasicFuseableConditionalSubscriber.request(BasicFuseableConditionalSubscriber.java:152)
                 	at io.reactivex.internal.subscribers.BasicFuseableSubscriber.request(BasicFuseableSubscriber.java:153)
                 	at io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber.onSubscribe(FlowableFlatMapMaybe.java:107)
                 	at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onSubscribe(BasicFuseableSubscriber.java:67)
                 	at io.reactivex.internal.subscribers.BasicFuseableConditionalSubscriber.onSubscribe(BasicFuseableConditionalSubscriber.java:66)
                 	at io.reactivex.internal.operators.flowable.FlowableFromIterable.subscribe(FlowableFromIterable.java:66)
                 	at io.reactivex.internal.operators.flowable.FlowableFromIterable.subscribeActual(FlowableFromIterable.java:47)
                 	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
                 	at io.reactivex.internal.operators.flowable.FlowableFilter.subscribeActual(FlowableFilter.java:34)
                 	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
                 	at io.reactivex.internal.operators.flowable.FlowableFilter.subscribeActual(FlowableFilter.java:37)
                 	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
                 	at io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe.subscribeActual(FlowableFlatMapMaybe.java:54)
                 	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
                 	at io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe.subscribeActual(FlowableFlatMapMaybe.java:54)
                 	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
                 	at io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe.subscribeActual(FlowableFlatMapMaybe.java:54)
                 	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
                 	at io.reactivex.internal.operators.flowable.FlowableToList.subscribeActual(FlowableToList.java:44)
                 	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
                 	at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:37)
                 	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
                 	at io.reactivex.internal.operators.flowable.FlowableFlattenIterable.subscribeActual(FlowableFlattenIterable.java:81)
                 	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
                 	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
                 	at io.reactivex.Maybe.subscribe(Maybe.java:4262)
                 	at io.reactivex.internal.operators.maybe.MaybeFlatten.subscribeActual(MaybeFlatten.java:42)
                 	at io.reactivex.Maybe.subscribe(Maybe.java:4262)
                 	at io.reactivex.internal.operators.maybe.MaybeFlatten$FlatMapMaybeObserver.onSuccess(MaybeFlatten.java:96)
                 	at io.reactivex.internal.operators.maybe.MaybeSwitchIfEmpty$SwitchIfEmptyMaybeObserver.onSuccess(MaybeSwitchIfEmpty.java:75)
                 	at io.reactivex.internal.operators.maybe.MaybeOnErrorNext$OnErrorNextMaybeObserver.onSuccess(MaybeOnErrorNext.java:88)
                 	at io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onSuccess(MaybePeek.java:122)
10:25:03.089  E  	at io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onSuccess(MaybePeek.java:122)
                 	at io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onSuccess(MaybePeek.java:122)
                 	at io.reactivex.internal.operators.maybe.MaybeFilter$FilterMaybeObserver.onSuccess(MaybeFilter.java:89)
                 	at io.reactivex.internal.operators.maybe.MaybeSwitchIfEmpty$SwitchIfEmptyMaybeObserver$OtherMaybeObserver.onSuccess(MaybeSwitchIfEmpty.java:110)
                 	at io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onSuccess(MaybePeek.java:122)
                 	at io.reactivex.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:61)
                 	at io.reactivex.Maybe.subscribe(Maybe.java:4262)
                 	at io.reactivex.internal.operators.maybe.MaybePeek.subscribeActual(MaybePeek.java:56)
                 	at io.reactivex.Maybe.subscribe(Maybe.java:4262)
                 	at io.reactivex.internal.operators.maybe.MaybeSwitchIfEmpty$SwitchIfEmptyMaybeObserver.onComplete(MaybeSwitchIfEmpty.java:88)
                 	at io.reactivex.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:59)
                 	at io.reactivex.Maybe.subscribe(Maybe.java:4262)
                 	at io.reactivex.internal.operators.maybe.MaybeSwitchIfEmpty.subscribeActual(MaybeSwitchIfEmpty.java:38)
                 	at io.reactivex.Maybe.subscribe(Maybe.java:4262)
                 	at io.reactivex.internal.operators.maybe.MaybeFilter.subscribeActual(MaybeFilter.java:39)
                 	at io.reactivex.Maybe.subscribe(Maybe.java:4262)
                 	at io.reactivex.internal.operators.maybe.MaybePeek.subscribeActual(MaybePeek.java:56)
                 	at io.reactivex.Maybe.subscribe(Maybe.java:4262)
                 	at io.reactivex.internal.operators.maybe.MaybePeek.subscribeActual(MaybePeek.java:56)
                 	at io.reactivex.Maybe.subscribe(Maybe.java:4262)
                 	at io.reactivex.internal.operators.maybe.MaybePeek.subscribeActual(MaybePeek.java:56)
                 	at io.reactivex.Maybe.subscribe(Maybe.java:4262)
                 	at io.reactivex.internal.operators.maybe.MaybeOnErrorNext.subscribeActual(MaybeOnErrorNext.java:46)
                 	at io.reactivex.Maybe.subscribe(Maybe.java:4262)
                 	at io.reactivex.internal.operators.maybe.MaybeSwitchIfEmpty.subscribeActual(MaybeSwitchIfEmpty.java:38)
                 	at io.reactivex.Maybe.subscribe(Maybe.java:4262)
                 	at io.reactivex.internal.operators.maybe.MaybeFlatten.subscribeActual(MaybeFlatten.java:42)
                 	at io.reactivex.Maybe.subscribe(Maybe.java:4262)
                 	at io.reactivex.internal.operators.maybe.MaybeToFlowable.subscribeActual(MaybeToFlowable.java:45)
                 	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
                 	at io.reactivex.Flowable.subscribe(Flowable.java:14752)
                 	at io.reactivex.internal.operators.flowable.FlowableConcatMap$ConcatMapImmediate.drain(FlowableConcatMap.java:340)
                 	at io.reactivex.internal.operators.flowable.FlowableConcatMap$BaseConcatMapSubscriber.onNext(FlowableConcatMap.java:159)
                 	at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runBackfused(FlowableObserveOn.java:448)
                 	at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:172)
                 	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
                 	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
                 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
                 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
                 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                 	at java.lang.Thread.run(Thread.java:1012)

#### Steps to reproduce:
The issue happened when it trigger a specify campaign, and the campaign has 2 buttons.
However, copy the campaign, or create same new campaign, can't reproduce the issue.

#### Relevant Code:

```
else if (this.secondaryAction != null && this.secondaryAction.getButton() == null) {
throw new IllegalArgumentException("Card model secondary action must be null or have a button");
}
```

**Comment by argzdev** [comment]
Thanks for reporting, @sscatch20. Might be related to #4214 which I think is being caused by a race condition. Are you running multiple campaigns? Or just one campaign?

**Comment by sscatch20** [comment]
There are multiple campaigns, only when show the specify campaign will trigger the issue.
Campaign ID: 2630176140336433549

13:38:55.902 FIAM.Headless            I  Already impressed campaign Campaign C (copy from Campaign 2630176140336433549)  ? : true
13:38:55.903 FIAM.Headless            I  Already impressed campaign Campaign A ? : true
13:38:55.903 FIAM.Headless            I  Already impressed campaign Campaign 2630176140336433549 ? : false

**Comment by argzdev** [comment]
That's interesting, so just to confirm, other campaigns do not trigger this issue. Only one specific campaign does? Can you share some details or steps how you created your campaign, so I can try reproducing this on my end? Kindly remove any personally identifiable information when sharing. Thanks!

**Comment by sscatch20** [comment]
[The campaign setting](https://photos.google.com/share/AF1QipMXsz0PjQYacg8Ygexm4ghNsIcmGmMpjPZTjfSgbXURidbBK3E-v0M9nnTKN3Ah9A?key=S2U1bXZncndWSU4tX3VLUUdJUHdSZG1iZklXWW1R)
It's no end time, once a day, and fired when to main foreground campaign.
