### ISSUE TITLE
OutOfMemory when Crashlytics tries to gather information about a native crash

### ISSUE THREAD

**Issue by rwqwr** [firebase/firebase-android-sdk#4667]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: N/A
  * Firebase Component: Android Firebase SDK
  * Component version: com.google.firebase:firebase-bom:29.3.1

### [REQUIRED] Step 3: Describe the problem

OutOfMemory when Crashlytics tries to gather information about a native crash (e.g., a minidump).

Stacktrace:
``` txt
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 428016144 byte allocation with 25165824 free bytes and 127MB until OOM, target footprint 428079136, growth limit 536870912
       at java.lang.StringFactory.newStringFromBytes(StringFactory.java:234)
       at java.lang.StringFactory.newStringFromBytes(StringFactory.java:65)
       at android.util.Base64.encodeToString(Base64.java:458)
       at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.add(JsonValueObjectEncoderContext.java:221)
       at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.add(JsonValueObjectEncoderContext.java:245)
       at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.internalAddIgnoreNullValues(JsonValueObjectEncoderContext.java:380)
       at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.add(JsonValueObjectEncoderContext.java:69)
       at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.add(JsonValueObjectEncoderContext.java:110)
       at com.google.firebase.crashlytics.internal.model.AutoCrashlyticsReportEncoder$CrashlyticsReportFilesPayloadFileEncoder.encode(AutoCrashlyticsReportEncoder.java:540)
       at com.google.firebase.crashlytics.internal.model.AutoCrashlyticsReportEncoder$CrashlyticsReportFilesPayloadFileEncoder.encode(AutoCrashlyticsReportEncoder.java:529)
       at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.doEncode(JsonValueObjectEncoderContext.java:330)
       at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.add(JsonValueObjectEncoderContext.java:309)
       at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.add(JsonValueObjectEncoderContext.java:282)
       at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.internalAddIgnoreNullValues(JsonValueObjectEncoderContext.java:380)
       at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.add(JsonValueObjectEncoderContext.java:69)
       at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.add(JsonValueObjectEncoderContext.java:110)
       at com.google.firebase.crashlytics.internal.model.AutoCrashlyticsReportEncoder$CrashlyticsReportFilesPayloadEncoder.encode(AutoCrashlyticsReportEncoder.java:524)
       at com.google.firebase.crashlytics.internal.model.AutoCrashlyticsReportEncoder$CrashlyticsReportFilesPayloadEncoder.encode(AutoCrashlyticsReportEncoder.java:514)
       at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.doEncode(JsonValueObjectEncoderContext.java:330)
       at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.add(JsonValueObjectEncoderContext.java:309)
       at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.internalAddIgnoreNullValues(JsonValueObjectEncoderContext.java:380)
       at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.add(JsonValueObjectEncoderContext.java:69)
       at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.add(JsonValueObjectEncoderContext.java:110)
       at com.google.firebase.crashlytics.internal.model.AutoCrashlyticsReportEncoder$CrashlyticsReportEncoder.encode(AutoCrashlyticsReportEncoder.java:93)
       at com.google.firebase.crashlytics.internal.model.AutoCrashlyticsReportEncoder$CrashlyticsReportEncoder.encode(AutoCrashlyticsReportEncoder.java:65)
       at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.doEncode(JsonValueObjectEncoderContext.java:330)
       at com.google.firebase.encoders.json.JsonValueObjectEncoderContext.add(JsonValueObjectEncoderContext.java:309)
       at com.google.firebase.encoders.json.JsonDataEncoderBuilder$1.encode(JsonDataEncoderBuilder.java:121)
       at com.google.firebase.encoders.json.JsonDataEncoderBuilder$1.encode(JsonDataEncoderBuilder.java:129)
       at com.google.firebase.crashlytics.internal.model.serialization.CrashlyticsReportJsonTransform.reportToJson(CrashlyticsReportJsonTransform.java:42)
       at com.google.firebase.crashlytics.internal.persistence.CrashlyticsReportPersistence.synthesizeNativeReportFile(CrashlyticsReportPersistence.java:329)
       at com.google.firebase.crashlytics.internal.persistence.CrashlyticsReportPersistence.finalizeSessionWithNativeEvent(CrashlyticsReportPersistence.java:203)
       at com.google.firebase.crashlytics.internal.common.SessionReportingCoordinator.finalizeSessionWithNativeEvent(SessionReportingCoordinator.java:174)
       at com.google.firebase.crashlytics.internal.common.CrashlyticsController.finalizePreviousNativeSession(CrashlyticsController.java:619)
       at com.google.firebase.crashlytics.internal.common.CrashlyticsController.doCloseSessions(CrashlyticsController.java:570)
       at com.google.firebase.crashlytics.internal.common.CrashlyticsController.finalizeSessions(CrashlyticsController.java:502)
       at com.google.firebase.crashlytics.internal.common.CrashlyticsCore.doBackgroundInitialization(CrashlyticsCore.java:232)
       at com.google.firebase.crashlytics.internal.common.CrashlyticsCore.access$000(CrashlyticsCore.java:48)
       at com.google.firebase.crashlytics.internal.common.CrashlyticsCore$1.call(CrashlyticsCore.java:4)
       at com.google.firebase.crashlytics.internal.common.Utils$1.run(Utils.java:80)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:64)
       at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:27)
       at java.lang.Thread.run(Thread.java:923)
```

I checked the latest version of Crashlytics, but did not find any updates to the ndk package related to dump collection.

**Comment by argzdev** [comment]
Thanks for reporting, @rwqwr. You're correct, the Crashlytics NDK package haven't had any significant changes over a period of time, however the Crashlytics SDK for Java/Kotlin did. That said, since it is a direct dependency for the NDK library, it would still be best to update to the latest version so we can avoid issues that might've been fixed in the previous versions.

So currently the mapping is:
- BoM version `29.3.1` = com.google.firebase:firebase-crashlytics-ndk version is `18.2.9`
- BoM verison `31.2.1` = com.google.firebase:firebase-crashlytics-ndk version is `18.3.4`

Let me know if updating to the latest version helps. Thanks!
