### ISSUE TITLE
NullPointerException - InAppMessaging crash spontaneously started

### ISSUE THREAD

**Issue by jeremysullivan192** [firebase/firebase-android-sdk#4668]
I've been using the same IAM lib for months but a crash started happening Feb 8th spontaneously with users.

This is the crash log, it is affecting a lot of users all of a sudden. 

Using Firebase BOM version: com.google.firebase:firebase-bom:29.0.4

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
       at com.google.firebase.inappmessaging.ClientAppInfo.setFirebaseInstanceId(ClientAppInfo.java:172)
       at com.google.firebase.inappmessaging.ClientAppInfo.access$400(ClientAppInfo.java:13)
       at com.google.firebase.inappmessaging.ClientAppInfo$Builder.setFirebaseInstanceId(ClientAppInfo.java:454)
       at com.google.firebase.inappmessaging.internal.MetricsLoggerClient.createCampaignAnalyticsBuilder(MetricsLoggerClient.java:196)
       at com.google.firebase.inappmessaging.internal.MetricsLoggerClient.createEventEntry(MetricsLoggerClient.java:170)
       at com.google.firebase.inappmessaging.internal.MetricsLoggerClient.lambda$logImpression$0$com-google-firebase-inappmessaging-internal-MetricsLoggerClient(MetricsLoggerClient.java:106)
       at com.google.firebase.inappmessaging.internal.MetricsLoggerClient$$ExternalSyntheticLambda0.onSuccess(:6)
       at com.google.android.gms.tasks.zzm.run(com.google.android.gms:play-services-tasks@@18.0.1:1)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8741)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by argzdev** [comment]
Hey @jeremysullivan192, thanks for reporting. Could you please file a new issue following our template? It is necessary so that we can gather the basic information to conduct an initial investigation. Thanks!
