### ISSUE TITLE
NullPointerException - InAppMessaging crash spontaneously started

### ISSUE THREAD

**Issue by jeremysullivan192** [firebase/firebase-android-sdk#4669]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 2022.1.1 Patch 1
  * Firebase Component: In App Messaging
  * Component version: com.google.firebase:firebase-bom:29.0.4

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

I've been using the same IAM lib for months but a crash started happening Feb 8th spontaneously with users.

This is the crash log, it is affecting a lot of users all of a sudden.

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
       at com.google.firebase.inappmessaging.ClientAppInfo.setFirebaseInstanceId(ClientAppInfo.java:172)
       at com.google.firebase.inappmessaging.ClientAppInfo.access$400(ClientAppInfo.java:13)
       at com.google.firebase.inappmessaging.ClientAppInfo$Builder.setFirebaseInstanceId(ClientAppInfo.java:454)
       at com.google.firebase.inappmessaging.internal.MetricsLoggerClient.createCampaignAnalyticsBuilder(MetricsLoggerClient.java:196)
       at com.google.firebase.inappmessaging.internal.MetricsLoggerClient.createEventEntry(MetricsLoggerClient.java:170)
       at com.google.firebase.inappmessaging.internal.MetricsLoggerClient.lambda$logImpression$0$com-google-firebase-inappmessaging-internal-MetricsLoggerClient(MetricsLoggerClient.java:106)
       at com.google.firebase.inappmessaging.internal.MetricsLoggerClient$$ExternalSyntheticLambda0.onSuccess(:6)
       at com.google.android.gms.tasks.zzm.run(com.google.android.gms:play-services-tasks@@18.0.1:1)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8741)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

#### Relevant Code:

It is happening deep in the firebase library code, I do not have relevant code or reproduction steps

**Comment by argzdev** [comment]
Thanks for reporting again, @jeremysullivan192. As you've mentioned, since you haven't had any changes to the usage of FIAM, then the culprit might be related to the backend. I noticed that you're using an older version of FIAM. Currently, your BoM version `29.0.4` maps FIAM to version `20.1.1`, and the latest version of BoM `31.2.1` maps to `20.3.0`. There might have been some changes on how the SDK handling received messages. Could you try updating your BoM version to `31.2.1`, and see if that works?

Also did you create any new campaign during the time when the crashes began happening? If so, could you share the setup of your campaign. Please do remove any PII (personal identifiable information) if needed. This might give us an idea what's causing the issue. Thanks!

**Comment by jeremysullivan192** [comment]
This issue is happening in production and I haven't been able to reproduce yet so I can't verify if changing the BoM will fix the issues until I'm ready to release again. 

But your question about the campaign was spot on. It appears a new campaign was started right when the crashes began. I'm sure it's not a coincidence.

Campaign details:
- In app message 
- Title uses this emoji: 💘
- image - public url 
- button action -  https://www.instagram.com/
- scheduled from 2/9/2023 - 2/13/2023
- target was all users of the app
- the day before this campaign started, these crashes started. which is inline with how FIAM pre-loads content for campaigns so something in the backend must've not been able to handle one of these details.

There have been previous campaigns with similar content that haven't had any issues

**Comment by argzdev** [comment]
Thanks for the extra details, @jeremysullivan192. Sorry for the delayed response.

In this case, there's not much we can do on the SDK side, since you've verified that the issue started without any changes to the FIAM library version. That said, I believe the culprit is definitely something being triggered from the backend.

Could you file an issue to our [Firebase support](https://firebase.google.com/support)? Since they have visibility on your project setup, they'll be able to assist you better. You may also share project details, campaign ID, configurations, etc. 

I'll close this issue for now. Feel free to come back here if you think this is a mistake or if you have any further information that you can share with us to help investigate the issue further from the SDK side. Thanks!
