### ISSUE TITLE
Random crash with firestore: SQLITE_READONLY_DBMOVED

### ISSUE THREAD

**Issue by pratiked** [firebase/firebase-android-sdk#467]
Environment

  * Android Studio version: 3.4.1
  * Firebase Component: Firestore
  * Component version: 19.0.0

The problem

java.lang.RuntimeException: Internal error in Firestore (19.0.0).
        at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$5(com.google.firebase:firebase-firestore@@19.0.0:379)
        at com.google.firebase.firestore.util.AsyncQueue$$Lambda$5.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:7036)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
     Caused by: android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)
    #################################################################
    Error Code : 1032 (SQLITE_READONLY_DBMOVED)
    Caused By : Database or Journal file have been removed.
    	(attempt to write a readonly database (code 1032))
    #################################################################
        at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:938)
        at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
        at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
        at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:2215)
        at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:2192)
        at com.google.firebase.firestore.local.SQLitePersistence.execute(com.google.firebase:firebase-firestore@@19.0.0:316)
        at com.google.firebase.firestore.local.SQLiteMutationQueue.writeMutationQueueMetadata(com.google.firebase:firebase-firestore@@19.0.0:172)
        at com.google.firebase.firestore.local.SQLiteMutationQueue.acknowledgeBatch(com.google.firebase:firebase-firestore@@19.0.0:157)
        at com.google.firebase.firestore.local.LocalStore.lambda$acknowledgeBatch$2(com.google.firebase:firebase-firestore@@19.0.0:265)
        at com.google.firebase.firestore.local.LocalStore$$Lambda$3.get(Unknown Source:4)
        at com.google.firebase.firestore.local.SQLitePersistence.runTransaction(com.google.firebase:firebase-firestore@@19.0.0:195)
        at com.google.firebase.firestore.local.LocalStore.acknowledgeBatch(com.google.firebase:firebase-firestore@@19.0.0:261)
        at com.google.firebase.firestore.core.SyncEngine.handleSuccessfulWrite(com.google.firebase:firebase-firestore@@19.0.0:413)
        at com.google.firebase.firestore.core.FirestoreClient.handleSuccessfulWrite(com.google.firebase:firebase-firestore@@19.0.0:270)
        at com.google.firebase.firestore.remote.RemoteStore.handleWriteStreamMutationResults(com.google.firebase:firebase-firestore@@19.0.0:644)
        at com.google.firebase.firestore.remote.RemoteStore.access$500(com.google.firebase:firebase-firestore@@19.0.0:53)
        at com.google.firebase.firestore.remote.RemoteStore$2.onWriteResponse(com.google.firebase:firebase-firestore@@19.0.0:201)
        at com.google.firebase.firestore.remote.WriteStream.onNext(com.google.firebase:firebase-firestore@@19.0.0:185)
        at com.google.firebase.firestore.remote.WriteStream.onNext(com.google.firebase:firebase-firestore@@19.0.0:50)
        at com.google.firebase.firestore.remote.AbstractStream$StreamObserver.lambda$onNext$1(com.google.firebase:firebase-firestore@@19.0.0:119)
        at com.google.firebase.firestore.remote.AbstractStream$StreamObserver$$Lambda$2.run(Unknown Source:4)
        at com.google.firebase.firestore.remote.AbstractStream$CloseGuardedRunner.run(com.google.firebase:firebase-firestore@@19.0.0:67)
        at com.google.firebase.firestore.remote.AbstractStream$StreamObserver.onNext(com.google.firebase:firebase-firestore@@19.0.0:110)
        at com.google.firebase.firestore.util.FirestoreChannel$1.onMessage(com.google.firebase:firebase-firestore@@19.0.0:150)

Code:

FirebaseFirestore.getInstance().collection("actions").add(mapAction)
                        .addOnSuccessListener(documentReference -> Log.i(TAG, "onSuccess: action added"))
                        .addOnFailureListener(e -> Log.i(TAG, "onFailure: failed to add action", e));

**Comment by schmidt-sebastian** [comment]
@pratiked Thanks for reporting this issue. This is indeed somewhat random - we open the database in [readmode mode](https://github.com/firebase/firebase-android-sdk/blob/master/firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLitePersistence.java#L125). There is also no code to move database files in the SDK.

Is this issue reproducible for you? Do you also see this on end user devices and if so, is this a common crash? Did you do anything special to your app installation before you executed the three lines of code you posted above? Thank you for helping us track this down!

**Comment by pratiked** [comment]
@schmidt-sebastian Thanks for your reply. Not all end user is facing this. I am able to reproduce it on Samsung Galaxy M30 phone only. This is not happening other phones like Motorola, OnePlus.

Here is what I have observed:
When a user logs out from the app, I first call above code I posted and then call logout function which just clears SharedPreferences, cache and local database (realm) and directs the user to the login page. 

One more random behavior I have observed. If this crash doesn't happen on logout, it occurs on login where I have the same code which I have posted. But most of the times it happens on logout.

Hope I have answered all the questions.

Happy to help.

P.S. App has Java 8 support

**Comment by aguatno** [comment]
Hi @pratiked it has been quite a long time. I would like to check if you are still having issues? Have you tried the latest SDK version to see if the issue persists? Thanks

**Comment by pratiked** [comment]
The project has been handed over to another developer. Let me check with him. @akshay-kapase

**Comment by aguatno** [comment]
Thanks.
