### ISSUE TITLE
I met the same problem, mainly on Android12 devices, HONOR & SAMSUNG:

### ISSUE THREAD

**Issue by BarretWu** [firebase/firebase-android-sdk#4679]
I met the same problem, mainly on Android12 devices, HONOR & SAMSUNG:

```
Fatal Exception: java.lang.SecurityException: addOnPermissionsChangeListener: Neither user 10200 nor current process has android.permission.OBSERVE_GRANT_REVOKE_PERMISSIONS.
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2437)
       at android.os.Parcel.createException(Parcel.java:2421)
       at android.os.Parcel.readException(Parcel.java:2404)
       at android.os.Parcel.readException(Parcel.java:2346)
       at com.google.android.gms.common.internal.IGmsServiceBroker$Stub$zza.getService(IGmsServiceBroker.java:14)
       at com.google.android.gms.common.internal.BaseGmsClient.getRemoteService(BaseGmsClient.java:263)
       at com.google.android.gms.common.internal.BaseGmsClient$LegacyClientCallbackAdapter.onReportServiceBinding(BaseGmsClient.java:3)
       at com.google.android.gms.common.internal.BaseGmsClient$zzg.zza(BaseGmsClient.java:10)
       at com.google.android.gms.common.internal.BaseGmsClient$zza.zza(BaseGmsClient.java:12)
       at com.google.android.gms.common.internal.BaseGmsClient$zzc.zzc(BaseGmsClient.java:11)
       at com.google.android.gms.common.internal.BaseGmsClient$zzb.handleMessage(BaseGmsClient.java:49)
       at android.os.Handler.dispatchMessage(Handler.java:109)
       at com.google.android.gms.internal.common.zzi.dispatchMessage(zzi.java:8)
       at android.os.Looper.loopOnce(Looper.java:206)
       at android.os.Looper.loop(Looper.java:296)
       at android.app.ActivityThread.main(ActivityThread.java:8971)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:569)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:976)

```

Library version used:

`classpath 'com.google.gms:google-services:4.3.10'`
`classpath 'com.google.gms:google-services:4.3.14'`
`implementation platform('com.google.firebase:firebase-bom:31.1.0')`

I'm generating a lot of crashes, which seriously affects the crash rate

_Originally posted by @HanteIsHante in https://github.com/firebase/firebase-android-sdk/issues/4140#issuecomment-1370568983_

same to me, same devices , most at HONOR

**Comment by argzdev** [comment]
Hi @BarretWu, can you share with us what Firebase products are you using? Also could you share some code snippets related to those products? It might give us a clue where the issue lies. Thanks!
