### ISSUE TITLE
Firestore crash in Motorola & Infinix devices on Android 11

### ISSUE THREAD

**Issue by kurosaki-tisak** [firebase/firebase-android-sdk#4698]
### [REQUIRED] Step 2: Describe your environment

 Versions:
 
```
classpath 'com.android.tools.build:gradle:7.1.3'
classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.20'

implementation 'com.google.firebase:firebase-bom:31.2.0'
```

### [REQUIRED] Step 3: Describe the problem

<img width="468" alt="Screenshot 2566-02-18 at 11 54 22" src="https://user-images.githubusercontent.com/25000465/219840474-e5743218-63b6-474d-a718-ef46ebba78a1.png">

We faced this issue 7 days ago, and the crash count is insanely high, as you can see above. 
It seems this issue exists only on Android 11 or maybe just on 2 models, as shown in the image below:

<img width="410" alt="Screenshot 2566-02-18 at 11 54 58" src="https://user-images.githubusercontent.com/25000465/219840232-61f5611a-422d-496c-9013-e731cc53559d.png">
<img width="408" alt="Screenshot 2566-02-18 at 11 55 09" src="https://user-images.githubusercontent.com/25000465/219840252-dd8ad305-fa56-402c-8f40-beea4b7975e2.png">

From crashlytics:

```
Fatal Exception: java.lang.RuntimeException: Internal error in Cloud Firestore (24.4.2).
       at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$3(AsyncQueue.java:545)
       at com.google.firebase.firestore.util.AsyncQueue$$ExternalSyntheticLambda3.run(:2)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:250)
       at android.app.ActivityThread.main(ActivityThread.java:7806)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

Caused by java.lang.RuntimeException: android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/data/user/0/com.tdcm.trueidapp/databases/firestore.%5BDEFAULT%5D.trueid-v3-production-c68dc.%28default%29': File /data/user/0/com.tdcm.trueidapp/databases/firestore.%5BDEFAULT%5D.trueid-v3-production-c68dc.%28default%29 doesn't exist
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor.lambda$executeAndReportResult$1(AsyncQueue.java:333)
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$$ExternalSyntheticLambda0.run(:4)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:235)
       at java.lang.Thread.run(Thread.java:923)

Caused by android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/data/user/0/com.tdcm.trueidapp/databases/firestore.%5BDEFAULT%5D.trueid-v3-production-c68dc.%28default%29': File /data/user/0/com.tdcm.trueidapp/databases/firestore.%5BDEFAULT%5D.trueid-v3-production-c68dc.%28default%29 doesn't exist
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:252)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:205)
       at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:505)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:198)
       at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:918)
       at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:898)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:762)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:751)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:373)
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
       at com.google.firebase.firestore.local.SQLitePersistence.start(SQLitePersistence.java:138)
       at com.google.firebase.firestore.core.ComponentProvider.initialize(ComponentProvider.java:150)
       at com.google.firebase.firestore.core.FirestoreClient.initialize(FirestoreClient.java:292)
       at com.google.firebase.firestore.core.FirestoreClient.lambda$new$0$com-google-firebase-firestore-core-FirestoreClient(FirestoreClient.java:111)
       at com.google.firebase.firestore.core.FirestoreClient$$ExternalSyntheticLambda22.run(:8)
       at com.google.firebase.firestore.util.AsyncQueue.lambda$enqueue$2(AsyncQueue.java:444)
       at com.google.firebase.firestore.util.AsyncQueue$$ExternalSyntheticLambda6.call(:2)
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor.lambda$executeAndReportResult$1(AsyncQueue.java:330)
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$$ExternalSyntheticLambda0.run(:4)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:235)
       at java.lang.Thread.run(Thread.java:923)

Caused by android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14 SQLITE_CANTOPEN): Could not open database
       at android.database.sqlite.SQLiteConnection.nativeOpen(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:224)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:205)
       at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:505)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:198)
       at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:918)
       at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:898)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:762)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:751)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:373)
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
       at com.google.firebase.firestore.local.SQLitePersistence.start(SQLitePersistence.java:138)
       at com.google.firebase.firestore.core.ComponentProvider.initialize(ComponentProvider.java:150)
       at com.google.firebase.firestore.core.FirestoreClient.initialize(FirestoreClient.java:292)
       at com.google.firebase.firestore.core.FirestoreClient.lambda$new$0$com-google-firebase-firestore-core-FirestoreClient(FirestoreClient.java:111)
       at com.google.firebase.firestore.core.FirestoreClient$$ExternalSyntheticLambda22.run(:8)
       at com.google.firebase.firestore.util.AsyncQueue.lambda$enqueue$2(AsyncQueue.java:444)
       at com.google.firebase.firestore.util.AsyncQueue$$ExternalSyntheticLambda6.call(:2)
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor.lambda$executeAndReportResult$1(AsyncQueue.java:330)
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$$ExternalSyntheticLambda0.run(:4)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:235)
       at java.lang.Thread.run(Thread.java:923)
```

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by ehsannas** [comment]
Firestore uses SQLite for local caching on Android. The error suggests that Firestore is not able to access SQLite on disk. It could be because the OS is not granting access to disk.

Does your app have access to disk?

Asking for permission for write access _may_ resolve this issue. 

For example, try adding
```
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
```
to your project's `AndroidManifest.xml` file in the `manifest` tag.
