### ISSUE TITLE
Crash in FirebaseCrashlytics init

### ISSUE THREAD

**Issue by himanshuoyo** [firebase/firebase-android-sdk#4701]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Electric Eel | 2022.1.1 Patch 1
  * Firebase Component: Crashlytics 
  * Component version: 31.1.1

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
Exception java.lang.ExceptionInInitializerError:
  at com.oyo.consumer.ExternalSdkInitializerWrapper.initExternalSDK (ExternalSdkInitializerWrapper.kt:38)
  at com.oyo.consumer.ExternalSdkInitializer.init (ExternalSdkInitializer.kt:29)
  at com.oyo.consumer.AppController.onCreate (AppController.java:89)
  at android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1189)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:6683)
  at android.app.ActivityThread.access$1500 (ActivityThread.java:236)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1928)
  at android.os.Handler.dispatchMessage (Handler.java:107)
  at android.os.Looper.loop (Looper.java:264)
  at android.app.ActivityThread.main (ActivityThread.java:7593)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:492)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:980)
Caused by java.lang.NullPointerException: FirebaseCrashlytics component is not present.
  at com.google.firebase.crashlytics.FirebaseCrashlytics.getInstance (FirebaseCrashlytics.java:186)
  at com.oyo.consumer.analytics.crashlytics.CrashlyticsEnvImp.<clinit> (CrashlyticsEnvImp.kt:7)
```

**Comment by argzdev** [comment]
Hi @himanshuoyo, thanks for reporting. Could you share steps how you were able reproduce this behavior? Or any chance you could share with us a minimal repro of your issue? It'll help us a lot, thanks!

**Comment by himanshuoyo** [comment]
Hi,

I don't have any repro step.I got above stack trace from play store vitals.

**Comment by argzdev** [comment]
Relevant code:

https://github.com/firebase/firebase-android-sdk/blob/7e2bec1b80e8e7fb3ca2db6e52f71f957ea60f45/firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.java#L198-L205

It seems that the exception is triggering when retrieving the `getInstance()` of Firebase Crashlytics. That said, I think the issue might lie on how you're initializing your project or Firebase Crashlytics. Can you share some code snippets how you're initializing your FirebaseApp or Crashlytics? Thanks.

**Comment by argzdev** [comment]
FWIW, it looks like your current version is `31.1.1` and the latest version is now at `31.2.2`. Could you try updating to the latest version and see if this fixes the issue? Thanks!

**Comment by himanshuoyo** [comment]
` 
In Application Class----

@Override
    public void onCreate() {
        long initalTimeStamp = System.currentTimeMillis();
        if (MissingSplitsManagerFactory.create(this).disableAppIfMissingRequiredSplits()) {
            return;
        }
        new PreOnCreateInitializers().init(this);
        ContextManager.INSTANCE.setApplication(this);
        super.onCreate();

In PreOnCreateInitializers Class:

override fun init(app: Application) {
        AppCompatDelegate.setCompatVectorFromResourcesEnabled(true)
        FirebaseApp.initializeApp(app)
`

**Comment by argzdev** [comment]
Thanks for the code snippet, @himanshuoyo. Can you help shed some light on the following questions below:
1. From the looks of your code, are you perhaps initializing multiple Firebase projects?
2. Did you change your Crashlytics version before experiencing this issue? Can you share what version were you previously using?

**Comment by mwshubham** [comment]
Possible someone is initializing it



```
Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.example.app. Make sure to call FirebaseApp.initializeApp(Context) first.
                                                             	at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:179)
                                                             	at com.google.firebase.perf.config.RemoteConfigManager.getInitialStartupMillis(RemoteConfigManager.java:91)
                                                             	at com.google.firebase.perf.config.RemoteConfigManager.<init>(RemoteConfigManager.java:85)
                                                             	at com.google.firebase.perf.config.RemoteConfigManager.<clinit>(RemoteConfigManager.java:52)
                                                             	at com.google.firebase.perf.config.RemoteConfigManager.getInstance(RemoteConfigManager.java:119) 
                                                             	at com.google.firebase.perf.config.ConfigResolver.<init>(ConfigResolver.java:78) 
                                                             	at com.google.firebase.perf.config.ConfigResolver.getInstance(ConfigResolver.java:86) 
                                                             	at com.google.firebase.perf.application.AppStateMonitor.<init>(AppStateMonitor.java:98) 
                                                             	at com.google.firebase.perf.application.AppStateMonitor.getInstance(AppStateMonitor.java:87) 
                                                             	at com.google.firebase.perf.metrics.NetworkRequestMetricBuilder.<init>(NetworkRequestMetricBuilder.java:92) 
                                                             	at com.google.firebase.perf.metrics.NetworkRequestMetricBuilder.builder(NetworkRequestMetricBuilder.java:84) 
                                                             	at com.google.firebase.perf.network.FirebasePerfUrlConnection.instrument(FirebasePerfUrlConnection.java:186) 
                                                             	at com.facebook.GraphRequest$Companion.createConnection(GraphRequest.kt:1054) 
                                                             	at com.facebook.GraphRequest$Companion.toHttpConnection(GraphRequest.kt:748) 
                                                             	at com.facebook.GraphRequest$Companion.executeBatchAndWait(GraphRequest.kt:836) 
                                                             	at com.facebook.GraphRequest$Companion.executeBatchAndWait(GraphRequest.kt:811) 
                                                             	at com.facebook.GraphRequest$Companion.executeBatchAndWait(GraphRequest.kt:794) 
                                                             	at com.facebook.GraphRequest$Companion.executeAndWait(GraphRequest.kt:772) 
                                                             	at com.facebook.GraphRequest.executeAndWait(GraphRequest.kt:1456) 
                                                             	at com.facebook.internal.FetchedAppSettingsManager.getAppSettingsQueryResponse(FetchedAppSettingsManager.kt:288) 
                                                             	at com.facebook.internal.FetchedAppSettingsManager.loadAppSettingsAsync$lambda-0(FetchedAppSettingsManager.kt:127) 
                                                             	at com.facebook.internal.FetchedAppSettingsManager.lambda$0Zs5KScD9YcdRdfqSQiSgW_MgdQ(Unknown Source:0) 
                                                             	at com.facebook.internal.-$$Lambda$FetchedAppSettingsManager$0Zs5KScD9YcdRdfqSQiSgW_MgdQ.run(Unknown Source:6) 
                                                             	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) 
                                                             	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) 
                                                             	at java.lang.Thread.run(Thread.java:1012) 
```
