### ISSUE TITLE
Random crash after successful integration tests, Firebase Test Lab on Pixel 5, API 30

### ISSUE THREAD

**Issue by Benetiime** [firebase/firebase-android-sdk#4725]
### [READ] Step 1: Are you in the right place?
I think so.
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Electric Eel | 2022.1.1 Patch 1
  * Firebase Components :
```
com.google.firebase:firebase-bom:31.2.0
com.google.firebase:firebase-core:21.1.1
com.google.firebase:firebase-messaging
com.google.firebase:firebase-config
com.google.firebase:firebase-dynamic-links
com.google.firebase:firebase-perf
com.google.firebase:firebase-crashlytics
com.google.firebase:firebase-crashlytics-ndk
com.google.firebase:firebase-analytics-ktx
```

### [REQUIRED] Step 3: Describe the problem
I've encountered a strange and unusual crash while launching instrumentation tests on an Firebase Test Lab emulator.
Device : Pixel 5, API 30
Tests scenarios are successful. 
`02-28 08:16:06.122: I/TestRunner(24963): run finished: 1 tests, 0 failed, 0 ignored`

However, the test process resulted in a failure. The app has somehow crashed, here is the log of the exception: 
```
................ 
02-28 08:16:18.517: I/Finsky(25626): [2] vfy.s(5): Package no longer installed: ***************
02-28 08:16:18.524: I/RollbackManager(1563): broadcast=ACTION_PACKAGE_FULLY_REMOVED pkg=***************
02-28 08:16:18.525: E/PhoneInterfaceManager(4489): [PhoneIntfMgr] getCarrierPackageNamesForIntentAndPhone: No UICC
02-28 08:16:18.526: D/CarrierSvcBindHelper(4489): No carrier app for: 0

02-28 08:16:18.527: D/AndroidRuntime(27086): --------- beginning of crash
02-28 08:16:18.529: E/AndroidRuntime(27086): FATAL EXCEPTION: main
02-28 08:16:18.529: E/AndroidRuntime(27086): Process: ***************, PID: 27086
02-28 08:16:18.529: E/AndroidRuntime(27086): java.lang.RuntimeException: Unable to instantiate application ***************: java.lang.NullPointerException: Attempt to read from field 'java.lang.String android.content.pm.PackageInfo.sharedUserId' on a null object reference
02-28 08:16:18.529: E/AndroidRuntime(27086): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:1268)
02-28 08:16:18.529: E/AndroidRuntime(27086): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6690)
02-28 08:16:18.529: E/AndroidRuntime(27086): 	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
02-28 08:16:18.529: E/AndroidRuntime(27086): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
02-28 08:16:18.529: E/AndroidRuntime(27086): 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-28 08:16:18.529: E/AndroidRuntime(27086): 	at android.os.Looper.loop(Looper.java:223)
02-28 08:16:18.529: E/AndroidRuntime(27086): 	at android.app.ActivityThread.main(ActivityThread.java:7664)
02-28 08:16:18.529: E/AndroidRuntime(27086): 	at java.lang.reflect.Method.invoke(Native Method)
02-28 08:16:18.529: E/AndroidRuntime(27086): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
02-28 08:16:18.529: E/AndroidRuntime(27086): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
02-28 08:16:18.529: E/AndroidRuntime(27086): Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String android.content.pm.PackageInfo.sharedUserId' on a null object reference
02-28 08:16:18.529: E/AndroidRuntime(27086): 	at android.app.LoadedApk.initializeJavaContextClassLoader(LoadedApk.java:1079)
02-28 08:16:18.529: E/AndroidRuntime(27086): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:1240)
02-28 08:16:18.529: E/AndroidRuntime(27086): 	... 9 more
................
```
If needed I can give more focused logs.

#### Steps to reproduce:
I cannot reproduce it for now...

**Comment by argzdev** [comment]
Hi @Benetiime, thanks for reacting out to us. It seems to me that the main issue is with our test lab devices. That said, I don't think there's anything we can do on the SDK side. Could you reach out to our [Firebase support team](https://firebase.google.com/support)? They'll be able to assist you better with this issue. Thanks!
