### ISSUE TITLE
WakeLockHolder.vdnmuOaWGi ANR triggered by a deadlock involving the main thread

### ISSUE THREAD

**Issue by lovtyagiandroi** [firebase/firebase-android-sdk#4745]
### [READ] Step 1: Are you in the right place?
I am facing below given issue :

main (blocked):tid=1 systid=15970 | waiting to lock <0x0ecc1871> (java.lang.Object) held by thread 55
       at com.google.firebase.messaging.WakeLockHolder.vdnmuOaWGi(WakeLockHolder.java:2)
       at com.google.firebase.messaging.WakeLockHolder.lambda$sendWakefulServiceIntent$0(WakeLockHolder.java:113)
       at com.google.android.gms.tasks.zzi.run(zzi.java:1)
       at com.google.android.gms.iid.zzj.run$bridge(zzj.java:351)
       at com.google.firebase.messaging.FcmBroadcastProcessor$$InternalSyntheticLambda$1$20ad64d025a971aa803b176a540e5710ff1caab22d62957ae57bd1390f50ccfd$0.execute(FcmBroadcastProcessor.java)
       at com.google.android.gms.tasks.zzj.zzd(com.google.android.gms:play-services-tasks@@18.0.2:3)
       at com.google.android.gms.tasks.zzr.zzb(com.google.android.gms:play-services-tasks@@18.0.2:5)
       at com.google.android.gms.tasks.zzw.zze(zzw.java:3)
       at com.google.android.gms.tasks.TaskCompletionSource.trySetResult(com.google.android.gms:play-services-tasks@@18.0.2:1)
       at com.google.firebase.messaging.WithinAppServiceConnection$BindRequest.finish(WithinAppServiceConnection.java:88)
       at com.google.firebase.messaging.WithinAppServiceBinder.lambda$send$0(WithinAppServiceBinder.java:55)
       at com.google.firebase.messaging.WithinAppServiceBinder$$InternalSyntheticLambda$2$28aec3a1d612c50761b821163886dacf3adcb6f56220725f43c11adc87a189da$1.onComplete$bridge(WithinAppServiceBinder.java:13)
       at com.google.android.gms.tasks.zzi.run(zzi.java:1)
       at com.google.android.gms.iid.zzj.run$bridge(zzj.java:351)
       at com.google.firebase.messaging.EnhancedIntentService$$InternalSyntheticLambda$1$92890c4a32262a9c9b389a2f85f5375b6df500be598ce417a2a3acad963477a6$0.execute$bridge(EnhancedIntentService.java)
       at com.google.android.gms.tasks.zzj.zzd(com.google.android.gms:play-services-tasks@@18.0.2:3)
       at com.google.android.gms.tasks.zzr.zzb(com.google.android.gms:play-services-tasks@@18.0.2:5)
       at com.google.android.gms.tasks.zzw.zzi(com.google.android.gms:play-services-tasks@@18.0.2:3)
       at com.google.android.gms.tasks.zzw.addOnCompleteListener(com.google.android.gms:play-services-tasks@@18.0.2:9)
       at com.google.firebase.messaging.WithinAppServiceBinder.send(WithinAppServiceBinder.java:55)
       at com.google.firebase.messaging.WithinAppServiceConnection.flushQueue(WithinAppServiceConnection.java:152)
       at com.google.firebase.messaging.WithinAppServiceConnection.onServiceConnected(WithinAppServiceConnection.java:209)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1991)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2023)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8163)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

### [REQUIRED] Step 2: Describe your environment

implementation platform('com.google.firebase:firebase-bom:31.0.2')
    implementation 'com.google.firebase:firebase-messaging'
    implementation 'com.google.firebase:firebase-perf'
    implementation 'com.google.firebase:firebase-crashlytics'
    implementation 'com.google.firebase:firebase-analytics'

### [REQUIRED] Step 3: Describe the problem

Triggered ANR

#### Steps to reproduce:
there are no particular steps to repro this issue.

**Comment by argzdev** [comment]
Thanks for reporting, @lovtyagiandroi. It looks like the BoM version `31.0.2` that you're using have the equivalent `firebase-messaging` version of `23.1.0`. According to the [release notes](https://firebase.google.com/support/release-notes/android#messaging_v23-1-1), there was a fix relating to ANR issues released on `firebase-messaging` version `23.1.1`. Could you try updating to our latest BoM version `31.2.3` and see if that fixes the issue? Thanks!
