### ISSUE TITLE
Crash in Binary XML file line #31 layout/modal_portrait_inner: Error inflating class android.widget.ImageView.

### ISSUE THREAD

**Issue by vitaliygerasymchuk** [firebase/firebase-android-sdk#4766]
### [REQUIRED] Step 2: Describe your environment

        * Android Studio version: 2022.1.1 Patch 2
        * Firebase Component: _____ firebase-bom:31.2.3, crashlytics, analytics, messaging, firebase-inappmessaging-display
        * Component version: 31.2.3

### [REQUIRED] Step 3: Describe the problem
The Crashlytics contains multiple crashes of this type.
![image](https://user-images.githubusercontent.com/31439136/224250303-2c535f2b-8c57-4391-a0f8-5353fecc2ab5.png)

#### Steps to reproduce:
Caused by android.content.res.Resources$NotFoundException: Drawable (missing name) with resource ID #0x7f0700b1
Caused by android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f0700b1

#### Relevant Code:
This crash event happened in the first 3 seconds of the user's session. The crash event for this issue happened 3 times per user on average. Internal issue. No code.

**Comment by argzdev** [comment]
Hi, @vitaliygerasymchuk. Thanks for reaching out. Looking at the stacktrace, I don't see any indication of Firebase. Can you tell us why you think Firebase is causing the issue here?

**Comment by vitaliygerasymchuk** [comment]
Hi @argzdev. I probably missed to put additional logs. So the crash is caused here:
com.google.firebase.inappmessaging.display.internal.bindingwrappers.ModalBindingWrapper line 31 InAppMessageLayoutConfig. 

Here's the title of the crashs: ModalBindingWrapper.inflate
android.content.res.Resources$NotFoundException - Unable to find resource ID #<address>

Original StackTrace:

`Fatal Exception: android.view.InflateException: Binary XML file line #13 in com.example.test:layout/modal: Binary XML file line #31 in com.example.test:layout/modal_portrait_inner: Error inflating class android.widget.ImageView
`
`Caused by java.lang.reflect.InvocationTargetException:
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
       at android.view.LayoutInflater.createView(LayoutInflater.java:852)
       at android.view.LayoutInflater.createView(LayoutInflater.java:774)
       at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:928)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:948)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1002)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
       at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1261)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:1117)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
       at com.google.firebase.inappmessaging.display.internal.bindingwrappers.ModalBindingWrapper.inflate(ModalBindingWrapper.java:72)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay.inflateBinding(FirebaseInAppMessagingDisplay.java:344)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay.access$000(FirebaseInAppMessagingDisplay.java:79)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay$1.run(FirebaseInAppMessagingDisplay.java:286)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8653)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)`

`Caused by android.content.res.Resources$NotFoundException: Drawable (missing name) with resource ID #0x7f0700b1
`

So basing on that stack trace i assume that there's some error in the InAppMessageLayoutConfig. Correct me if i'm wrong. 
Thank you.

**Comment by argzdev** [comment]
Got it, thanks for the extra details, @vitaliygerasymchuk. I'll notify our engineers.

**Comment by argzdev** [comment]
By the way, while we wait for our engineers to take a look into this. May I ask if there were any specific campaign setup that triggers this issue? Like message layout, or any details you could share with us. It'll help us with our investigation a lot. Thanks!

**Comment by vitaliygerasymchuk** [comment]
@argzdev Sure. We're using the Modal on_foreground. Hope this will help.

**Comment by eldhosembabu** [comment]
Hi @vitaliygerasymchuk, thanks for reporting this issue.

I've tried to reproduce this issue by using the latest github codebase for FIAM SDK on the [Quickstart app](https://github.com/firebase/quickstart-android/tree/master/inappmessaging) and configuring a model message on_foreground on emulator with api level 32 and 33 and i'm not able to see any issues.

- Is this crash consistently reproducible?
- Is it happening for specific device versions?
- Have you tried with the latest FIAM SDK version?

Could you please provide a sample app (preferably the quick start app with FIAM campaign configured) which we can run and reproduce the issue (including steps to repro if any specific steps needed). Also would be great if you could let us know the test device details where you were able to reproduce the crash?

**Comment by vitaliygerasymchuk** [comment]
Hi @eldhosembabu 
* the crash occurred 23 times  for 6 users. 
* 87% Samsung, 13% Vivo
* we are using firebase-bom:31.2.3

I will try my best to reproduce this issue on my side, but there's no guarantee that it will occur. From the logs i can see that there's a problem with this drawable: 
`Caused by android.content.res.Resources$NotFoundException: Drawable (missing name) with resource ID #0x7f0700b1
`
I've tried to get it's content - and here it is: 
![photo_2023-03-16_12-47-46](https://user-images.githubusercontent.com/31439136/225594443-4fe98256-74e0-402c-8e51-833b25048a00.jpg)

**Comment by vitaliygerasymchuk** [comment]
@eldhosembabu here're some more logs:

`Caused by android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f0700b1
       at android.content.res.ResourcesImpl.getResourceName(ResourcesImpl.java:281)
       at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:949)
       at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:724)
       at android.content.res.Resources.loadDrawable(Resources.java:1072)
       at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:1017)
       at android.content.res.TypedArray.getDrawable(TypedArray.java:991)
       at android.widget.ImageView.<init>(ImageView.java:205)
       at android.widget.ImageView.<init>(ImageView.java:191)
       at android.widget.ImageView.<init>(ImageView.java:187)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
       at android.view.LayoutInflater.createView(LayoutInflater.java:876)
       at android.view.LayoutInflater.createView(LayoutInflater.java:798)
       at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:952)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:972)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1026)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:983)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:1145)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1106)
       at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1285)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:1141)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1106)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:692)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:544)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:491)
       at com.google.firebase.inappmessaging.display.internal.bindingwrappers.ModalBindingWrapper.inflate(ModalBindingWrapper.java:72)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay.inflateBinding(FirebaseInAppMessagingDisplay.java:344)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay.access$000(FirebaseInAppMessagingDisplay.java:79)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay$1.run(FirebaseInAppMessagingDisplay.java:286)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8741)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)`
       
       Is there a chance that it fails to find a drawable (even if it exists) for particular density? Please, see getDrawableForDensity.

**Comment by vitaliygerasymchuk** [comment]
@argzdev that was bom of version 31.2.2

**Comment by eldhosembabu** [comment]
hi @vitaliygerasymchuk , I believe you are referring to https://github.com/firebase/firebase-android-sdk/blob/04bbfd74354dbd5618f8a37eac73c5f11d232428/firebase-inappmessaging-display/src/main/res/drawable/image_placeholder.xml placeholder image which is a vector image inside common drawable folder. So i believe it should get rendered without any issues.

What I could suggest is to try create a sample app with this image in a image view and see whether you can load it in those specific devices where crash is reported.
