### ISSUE TITLE
java.lang.NullPointerException: Firebase Database component is not present.

### ISSUE THREAD

**Issue by edwinsong31** [firebase/firebase-android-sdk#4774]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: _____
  * Firebase Component: _____ (Database, Firestore, Storage, Functions, etc)
  * Component version: _____

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

java.lang.NullPointerException: Firebase Database component is not present.
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3654)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3806)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
     Caused by: java.lang.NullPointerException: Firebase Database component is not present.
        at com.google.android.gms.common.internal.Preconditions.checkNotNull(com.google.android.gms:play-services-basement@@18.1.0:2)

On the Activity:

databaseReference = FirebaseDatabase.getInstance().getReference("path")

**Comment by argzdev** [comment]
Hi @edwinsong31, thanks for reporting. This is an odd behavior. Can you answer a few questions for us below:

1. Have you initialized your Firebase Database from the Firebase Console dashboard?
2. What version of `com.google.firebase:firebase-database` are you currently using?
3. Are you initializing your Firebase using `google-services.json` or dynamically using `firebase.initializeApp`?
4. Is this behavior reproducible? If yes, how often?
5. Any chance you could share with us a minimal reproducible behavior?

**Comment by edwinsong31** [comment]
I added on the manifest and solved the issue.

**Comment by thatfiredev** [comment]
@edwinsong31 Can you clarify? What did you add to the manifest?
