### ISSUE TITLE
Firebase RomteConfig lead to crashes on specific devices and Android versions

### ISSUE THREAD

**Issue by WangZhiYao** [firebase/firebase-android-sdk#481]
### Step 1: Describe your environment

  * Device : Xiaomi HM NOTE 1W
  * Anroid OS version : 4.2.2
  * Firebase core version : 16.0.9
  * Firebase Component : RemoteConfig
  * Component version : 17.0.0

### Step 2: Describe the problem
```
Fatal Exception: java.lang.Error: org.json.JSONException: No value for sessions_feature_enabled
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1086)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:838)
Caused by org.json.JSONException: No value for sessions_feature_enabled
       at org.json.JSONObject.get(JSONObject.java:354)
       at org.json.JSONObject.getString(JSONObject.java:510)
       at com.google.android.gms.internal.firebase_remote_config.zzew.zza(Unknown Source:90)
       at com.google.android.gms.internal.firebase_remote_config.zzew.getString(Unknown Source:5)
       at com.google.firebase.remoteconfig.FirebaseRemoteConfig.getString(Unknown Source:47)
       at com.google.firebase.perf.internal.RemoteConfigManager.zzc(Unknown Source:25)
       at com.google.firebase.perf.internal.FeatureControl.zzb(Unknown Source:30)
       at com.google.firebase.perf.internal.FeatureControl.zzap(Unknown Source:11)
       at com.google.firebase.perf.internal.zzc.zzb(Unknown Source:174)
       at com.google.firebase.perf.internal.zzc.zza(Unknown Source:215)
       at com.google.firebase.perf.internal.zzh.run(Unknown Source:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:838)
```
```
Fatal Exception: java.lang.NumberFormatException: Invalid long: ""
       at java.lang.Long.invalidLong(Long.java:125)
       at java.lang.Long.parseLong(Long.java:346)
       at java.lang.Long.parseLong(Long.java:319)
       at com.google.firebase.perf.internal.RemoteConfigManager.zzc(Unknown Source:27)
       at com.google.firebase.perf.internal.FeatureControl.zzb(Unknown Source:30)
       at com.google.firebase.perf.internal.FeatureControl.zzaq(Unknown Source:14)
       at com.google.firebase.perf.internal.GaugeManager.zzbh(Unknown Source:138)
       at com.google.android.gms.internal.firebase-perf.zzau.zzg(Unknown Source:79)
       at com.google.firebase.perf.network.FirebasePerfOkHttpClient.zza(Unknown Source:48)
       at com.google.firebase.perf.network.zzf.onResponse(Unknown Source:21)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:838)
```

**Comment by binbinyYang** [comment]
我这边也遇到这个，一模一样的问题

**Comment by zijianjoy** [comment]
Hello @WangZhiYao and @binbinyYang, we have tried to reproduce this issue but didn't get the error message you had here. Do you have a sample app which can reproduce the issue and can you share it to us? Thank you!

**Comment by WangZhiYao** [comment]
> Hello @WangZhiYao and @binbinyYang, we have tried to reproduce this issue but didn't get the error message you had here. Do you have a sample app which can reproduce the issue and can you share it to us? Thank you!

Sorry, our app has been removed from Google Play and the backend has stopped the service too, so I can't give you the app which produce this issue.  but maybe this app can reproduce this issue on Xiaomi HM NOTE 1W with android version 19. Thank you for your help!
[RemoteConfigTest.zip](https://github.com/firebase/firebase-android-sdk/files/3545686/RemoteConfigTest.zip)

**Comment by WangZhiYao** [comment]
@zijianjoy you can find the source code here https://github.com/WangZhiYao/RemoteConfigTest

**Comment by zijianjoy** [comment]
@WangZhiYao Thank you for the source code. From the build.gradle file, it doesn't implement Firebase Performance Monitoring, example: https://firebase.google.com/docs/perf-mon/get-started-android?authuser=0#add-perfmon-sdk. However, it doesn't align with the error message in this issue description: the stack trace has "com.google.firebase.perf".

Would you like to repro the issue with your sample app and update the configuration accordingly? Thank you!

**Comment by WangZhiYao** [comment]
@zijianjoy Ok I just update the code and make a new release at  https://github.com/WangZhiYao/RemoteConfigTest/releases

**Comment by abn-volk** [comment]
These bug reports might help: https://github.com/NativeScript/android-runtime/issues/404
https://github.com/NativeScript/android-runtime/issues/628
