### ISSUE TITLE
Out of memory error in Firebase Auth

### ISSUE THREAD

**Issue by rahul-a** [firebase/firebase-android-sdk#4827]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Electric Eel | 2022.1.1 Patch 2
  * Firebase Component: Firebase Auth
  * Component version: 21.0.6

### [REQUIRED] Step 3: Describe the problem

Firebase Auth crashes with OutOfMemoryError across OS Versions 9-13

#### Steps to reproduce:

Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 150994952 byte allocation with 25165824 free bytes and 73MB until OOM, target footprint 485073536, growth limit 536870912
       at java.util.Arrays.copyOf(Arrays.java:3766)
       at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:125)
       at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:650)
       at java.lang.StringBuilder.append(StringBuilder.java:203)
       at org.json.JSONStringer.string(JSONStringer.java:354)
       at org.json.JSONStringer.value(JSONStringer.java:261)
       at org.json.JSONArray.writeTo(JSONArray.java:616)
       at org.json.JSONStringer.value(JSONStringer.java:242)
       at org.json.JSONObject.writeTo(JSONObject.java:734)
       at org.json.JSONObject.toString(JSONObject.java:702)
       at com.google.firebase.auth.internal.zzbg.zzd(zzbg.java:27)
       at com.google.firebase.auth.FirebaseAuth.zzG(FirebaseAuth.java:13)
       at com.google.firebase.auth.zzo.zza(zzo.java:1)
       at com.google.android.gms.internal.firebase-auth-api.zzru.zzb(zzru.java:3)
       at com.google.android.gms.internal.firebase-auth-api.zzug.zzj(zzug.java:1)
       at com.google.android.gms.internal.firebase-auth-api.zzud.zzn(zzud.java:2)
       at com.google.android.gms.internal.firebase-auth-api.zztf.zzn(zztf.java:1)
       at com.google.android.gms.internal.firebase-auth-api.zzqd.zzb(zzqd.java:2)
       at com.google.android.gms.internal.firebase-auth-api.zzuo.zza(zzuo.java:24)
       at com.google.android.gms.internal.firebase-auth-api.zztu.zzf(zztu.java:4)
       at com.google.android.gms.internal.firebase-auth-api.zzrk.zzp(zzrk.java:4)
       at com.google.android.gms.internal.firebase-auth-api.zztg.zzj(zztg.java:5)
       at com.google.android.gms.internal.firebase-auth-api.zzru.zzc(zzru.java:1)
       at com.google.android.gms.internal.firebase-auth-api.zzuh.run(zzuh.java:1)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)

#### Relevant Code:

```
    fun authenticate(): Completable {
        return Completable.create { completableEmitter ->
            if (firebaseAuth.currentUser != null) {
                if (!completableEmitter.isDisposed) {
                    completableEmitter.onComplete()
                }
            } else {
                firebaseAuth.signInAnonymously()
                        .addOnCompleteListener { task ->
                            if (!task.isSuccessful) {
                                if (!completableEmitter.isDisposed) {
                                    analyticsHelper.trackFirebaseAutheticationErrorEvent(
                                            FirebaseAuthenticatorEvent.Source.ANONYMOUS_USER_AUTHENTICATION_FAILED,
                                            task.exception?.message
                                    )
                                    Timber.e(task.exception)
                                    completableEmitter.onError(AuthenticationFailureException())
                                }
                            } else {
                                if (!completableEmitter.isDisposed) {
                                    analyticsHelper.trackFirebaseAutheticationErrorEvent(
                                            FirebaseAuthenticatorEvent.Source.ANONYMOUS_USER_SIGN_IN_SUCCESSFUL,
                                            task.exception?.message
                                    )
                                    completableEmitter.onComplete()
                                }
                            }
                        }.addOnFailureListener {
                            if (!completableEmitter.isDisposed) {
                                analyticsHelper.trackFirebaseAutheticationErrorEvent(
                                        FirebaseAuthenticatorEvent.Source.ANONYMOUS_USER_SIGN_IN_FAILURE,
                                        it.message
                                )
                                Timber.e(it)
                                completableEmitter.onError(it)
                            }
                        }
            }
        }
    }
```
It's called from background on cold start and keeps the user stuck in a crash loop, happening only in production so no concrete steps to reproduce

**Comment by argzdev** [comment]
Hi @rahul-a, thanks for reaching out. Could you try using our latest version of the SDK `21.2.0`? We usually suggest this to avoid issues that might've already been fixed in the most recent versions. Thanks!
