### ISSUE TITLE
Lazy.get ANR triggered by a deadlock involving the main thread at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:594)

### ISSUE THREAD

**Issue by chetan-ansel** [firebase/firebase-android-sdk#4873]
In crashlytics Board, I am getting loads of ANR 

main (blocked):tid=1 systid=1347 | waiting to lock <0x0967c3b7> (s9.p) held by thread 29
       at com.google.firebase.components.Lazy.get(Lazy.java:50)
       at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents(ComponentRuntime.java:291)
       at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(ComponentRuntime.java:281)
       at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:594)
       at com.google.firebase.FirebaseApp.access$400(FirebaseApp.java:90)
       at com.google.firebase.FirebaseApp$UserUnlockReceiver.onReceive(FirebaseApp.java:659)
       at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1580)
       at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(lambda)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7664)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
efaultDispatcher-worker-2 (blocked):tid=29 systid=1487 | waiting to lock <0x055a4724> (java.lang.Object) held by thread 1
       at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:201)
       at com.google.firebase.auth.internal.zzbg.zzf(com.google.firebase:firebase-auth@@21.0.6:21)
       at com.google.firebase.auth.internal.zzbg.zza(zzbg.java:7)
       at com.google.firebase.auth.FirebaseAuth.<init>(com.google.firebase:firebase-auth@@21.0.6:14)
       at com.google.firebase.auth.internal.zzv.<init>(com.google.firebase:firebase-auth@@21.0.6:1)
       at com.google.firebase.auth.FirebaseAuthRegistrar.lambda$getComponents$0(com.google.firebase:firebase-auth@@21.0.6:3)
       at com.google.firebase.auth.zzv.create(zzv.java)
       at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0(ComponentRuntime.java:132)
       at com.google.firebase.components.Lazy.get(Lazy.java:53)
       at com.google.firebase.components.AbstractComponentContainer.get(AbstractComponentContainer.java:27)
       at com.google.firebase.FirebaseApp.get(FirebaseApp.java:338)
       at com.google.firebase.auth.FirebaseAuth.getInstance(com.google.firebase:firebase-auth@@21.0.6:2)
       at com.mypackage.FirebaseAuthAsFlow.<clinit>(FirebaseAuthAsFlow.kt:12)
       at com.mypackage.MyApplication$onCreate$2.invokeSuspend(MyApplication.kt:73)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Comment by argzdev** [comment]
Hi @chetan-ansel, thanks for reaching out. Can you help answer a few questions for me:

1. Can you share with us what Firebase version are you currently using? Could you try using the latest version of `com.google.firebase:firebase-bom` (`31.4.0`) and see if that fixes the issue? We usually recommend this to avoid issues that have been fixed in the most recent versions. Let me know if it helps!
2. Just to confirm, since the issue is coming from `FirebaseApp.initializeAllApis `, are you perhaps initializing Firebase using FirebaseOptions or only with `google-services.json`?
3. Can you share with us a minimal reproducible example or code snippets?

Thanks in advance!

**Comment by chetan-ansel** [comment]
Currently, the App uses the 30.3.1(com.google.firebase:firebase-bom) version Thanks, Sure below is a code snippet.
I have created a flow class and used the same in the App application class.
```
object FirebaseAuthAsFlow {
private val firebaseAuth = FirebaseAuth.getInstance()

fun getFirebaseUser(): Flow<FirebaseUser?> =
    callbackFlow {
        val authStateListener = FirebaseAuth.AuthStateListener {
            trySendBlocking(it.currentUser)
        }
        firebaseAuth.addAuthStateListener(authStateListener)
        awaitClose { firebaseAuth.removeAuthStateListener(authStateListener) }
    }
}
```
and from the Application class, I am calling the above code:

   ```
 override fun onCreate() {
        super.onCreate()
        FirebaseApp.initializeApp(this)
CoroutineScope(Dispatchers.Default).launch {
            FirebaseAuthAsFlow.getFirebaseUser().collect{
               it?.let {
                   Log.d("userId","${it.uid}")
            }
        }
}
 }
```

**Comment by prameshj** [comment]
As of Firebase Auth 21.2.0 or BoM 31.4.0, firebase Auth will not initialize as part of eager components. Can you try if this issue occurs in that version?

Tagging this to the core team for more thoughts.

**Comment by prameshj** [comment]
cc @rlazo @emilypgoogle

**Comment by prameshj** [comment]
Are you still seeing the issue with 31.4.0? I meant that Firebase Auth would't automatically initialize as part of at `com.google.firebase.components.ComponentRuntime.initializeEagerComponents(ComponentRuntime.java:281)`,  but you are calling FirebaseAuth.getInstance() which will initialize it.

trySendBlocking blocks until it can send on a channel.. and we run authStateListener callback on the UI thread - https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseAuth.AuthStateListener

Do you see the issue if you replace it with a non-blocking call?
