### ISSUE TITLE
App carsh with  java.util.concurrent.RejectedExecutionException

### ISSUE THREAD

**Issue by rahuldevanavar91** [firebase/firebase-android-sdk#488]
I recently released the app, for all version its working fine for me. but after release on the play store, I am getting a lot of crash report with the following exception I don't have any idea where and why it's crashing.
it's happening only on OS 8.0 & 8.1

firebase dependencies I am using 
  ```
     classpath 'com.google.firebase:firebase-plugins:1.2.0'
 api("com.google.firebase:firebase-core:16.0.7") {
        exclude group: 'com.android.support'
    }

    api("com.google.firebase:firebase-auth:16.1.0") {
        exclude group: 'com.google.android.gms'
        exclude group: 'com.google.firebase:firebase-common'

    }
    api("com.google.firebase:firebase-messaging:17.4.0") {
        exclude group: 'com.google.android.gms'
        exclude group: 'com.google.firebase'
    }
    api("com.google.firebase:firebase-config:16.3.0") {
        ['com.google.android.gms', 'com.google.firebase:firebase-iid', 'com.google.firebase:firebase-common',
         'com.google.firebase:firebase-measurement-connector', 'com.google.android.gms:play-services-basement', 'com.google.android.gms:play-services-tasks'].each {
            exclude group: it
        }
    }
    api("com.google.firebase:firebase-perf:16.2.3") {
        ['com.google.firebase:firebase-common', 'com.google.firebase:firebase-iid', 'com.google.firebase:firebase-analytics',
         'com.google.firebase:firebase-config', 'com.google.android.gms:play-services-base', 'com.google.android.gms:play-services-basement',
         'com.google.android.gms:play-services-tasks'].each {
            exclude group: it
        }
    }

    api('com.google.firebase:firebase-database:16.1.0') {
        exclude group: 'com.google.android.gms'
        exclude group: 'com.google.firebase:firebase-common'
    }
api("com.google.firebase:firebase-crash:16.2.1") {
        exclude group: 'com.google.android.gms'

    }
```

Exception log 

```

java.lang.RuntimeException: 
  at android.app.ActivityThread.installProvider (ActivityThread.java:6398)
  at android.app.ActivityThread.installContentProviders (ActivityThread.java:5900)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:5808)
  at android.app.ActivityThread.-wrap1 (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1685)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:176)
  at android.app.ActivityThread.main (ActivityThread.java:6651)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:547)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:824)
Caused by: java.util.concurrent.RejectedExecutionException: 
  at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution (ThreadPoolExecutor.java:2078)
  at java.util.concurrent.ThreadPoolExecutor.reject (ThreadPoolExecutor.java:843)
  at java.util.concurrent.ThreadPoolExecutor.execute (ThreadPoolExecutor.java:1389)
  at com.google.firebase.crash.FirebaseCrash.<init> (FirebaseCrash.java:22)
  at com.google.firebase.crash.component.zza.create (zza.java:3)
  at com.google.firebase.components.ComponentRuntime.lambda$new$0 (ComponentRuntime.java:66)
  at com.google.firebase.components.ComponentRuntime$$Lambda$1.a (ComponentRuntime.java:4)
  at com.google.firebase.components.Lazy.get (Lazy.java:53)
  at com.google.firebase.components.ComponentRuntime.initializeEagerComponents (ComponentRuntime.java:155)
  at com.google.firebase.FirebaseApp.initializeAllApis (FirebaseApp.java:779)
  at com.google.firebase.FirebaseApp.initializeApp (FirebaseApp.java:369)
  at com.google.firebase.FirebaseApp.initializeApp (FirebaseApp.java:332)
  at com.google.firebase.FirebaseApp.initializeApp (FirebaseApp.java:316)
  at com.google.firebase.provider.FirebaseInitProvider.onCreate (FirebaseInitProvider.java:53)
  at android.content.ContentProvider.attachInfo (ContentProvider.java:1935)
  at android.content.ContentProvider.attachInfo (ContentProvider.java:1910)
  at com.google.firebase.provider.FirebaseInitProvider.attachInfo (FirebaseInitProvider.java:47)
  at android.app.ActivityThread.installProvider (ActivityThread.java:6386)
  at android.app.ActivityThread.installContentProviders (ActivityThread.java:5900)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:5808)
  at android.app.ActivityThread.-wrap1 (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1685)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:176)
  at android.app.ActivityThread.main (ActivityThread.java:6651)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:547)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:824)
```

**Comment by aguatno** [comment]
Hello @rahuldevanavar91 thank you for reporting the issue, sorry for the delayed response. Unfortunately, I'm not able to decipher what is going on. We need more information to debug this issue:

- How easy is it to reproduce this issue? Could you provide steps to replicate or reproduction sample?
- Is it device or OS specific?
- Frequency with which you are able to reproduce the issue (e.g. 3/5 times)
- If you've noticed any patterns as to when you are encountering the issue (and when you're not), please do provide it as well
- Are there any specific steps that trigger the exception?"

Thanks!

**Comment by pratyesh** [comment]
Dear All,,
I have also the same ANR reported in play console.

case 1:-
ANR because of Broadcast of Intent { act=com.google.android.c2dm.intent.RECEIVE in FirebaseInstanceIdReceiver

"main" prio=5 tid=1 Waiting
| group="main" sCount=1 dsCount=0 obj=0x751a5000 self=0xb8d3a630
| sysTid=29578 nice=-4 cgrp=apps sched=0/0 handle=0xb6fb6ec8
| state=S schedstat=( 1264064036 710641375 2251 ) utm=96 stm=30 core=0 HZ=100
| stack=0xbe31d000-0xbe31f000 stackSize=8MB
| held mutexes=
at java.lang.Object.wait! (Native method)

waiting on <0x13be0a86> (a java.lang.Object)
at java.lang.Thread.parkFor (Thread.java:1220)
locked <0x13be0a86> (a java.lang.Object)
at sun.misc.Unsafe.park (Unsafe.java:299)
at java.util.concurrent.locks.LockSupport.park (LockSupport.java:157)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt (AbstractQueuedSynchronizer.java:813)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly (AbstractQueuedSynchronizer.java:973)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly (AbstractQueuedSynchronizer.java:1281)
at java.util.concurrent.CountDownLatch.await (CountDownLatch.java:202)
at android.app.SharedPreferencesImpl$EditorImpl$1.run (SharedPreferencesImpl.java:363)
at android.app.QueuedWork.waitToFinish (QueuedWork.java:88)
at android.app.ActivityThread.handleServiceArgs (ActivityThread.java:3272)
at android.app.ActivityThread.access$2200 (ActivityThread.java:168)
at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1491)
at android.os.Handler.dispatchMessage (Handler.java:102)
at android.os.Looper.loop (Looper.java:135)
at android.app.ActivityThread.main (ActivityThread.java:5753)
at java.lang.reflect.Method.invoke! (Native method)
at java.lang.reflect.Method.invoke (Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1405)
at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1200)

case 2:-
Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.google.firebase.iid.FirebaseInstanceIdReceiver: java.util.concurrent.RejectedExecutionException: Task com.google.firebase.messaging.h@c7b0009 rejected from java.util.concurrent.ThreadPoolExecutor@a57f20e[Shutting down, pool size = 1, active threads = 1, queued tasks = 6, completed tasks = 1]
at android.app.ActivityThread.handleReceiver(ActivityThread.java:3230)
at android.app.ActivityThread.-wrap17()
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1698)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:176)
at android.app.ActivityThread.main(ActivityThread.java:6635)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

//firebase lib
implementation 'com.google.firebase:firebase-messaging:19.0.1'
implementation 'com.google.firebase:firebase-core:17.0.0'
implementation 'com.google.firebase:firebase-appindexing:19.0.0'
implementation 'com.google.firebase:firebase-config:18.0.0'

// sdk version
compileSdkVersion = 28
minSdkVersion = 17
targetSdkVersion = 28

[for more details regard to this ANR please look](https://github.com/firebase/quickstart-android/issues/594)
Please help me on it if anyone of you are having solution of this.
Thanks in advance.
