### ISSUE TITLE
java.lang.SecurityException: Unknown calling package name 'xxx.xxx.xxx'.

### ISSUE THREAD

**Issue by etjson** [firebase/firebase-android-sdk#5022]
```java
java.lang.SecurityException: Unknown calling package name 'xxx.xxx.xxx'.
 at android.os.Parcel.createExceptionOrNull(Parcel.java:2426)
 at android.os.Parcel.createException(Parcel.java:2410)
 at android.os.Parcel.readException(Parcel.java:2393)
 at android.os.Parcel.readException(Parcel.java:2335)
...
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loopOnce(Looper.java:211)
 at android.os.Looper.loop(Looper.java:300)
 at android.app.ActivityThread.main(ActivityThread.java:8298)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
```

classpath 'com.google.gms:google-services:4.3.15'
classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.5'

implementation 'com.google.firebase:firebase-analytics-ktx:21.2.2'
implementation 'com.google.firebase:firebase-crashlytics-ktx:18.3.7'

**Does anyone know what causes this problem?**

**Comment by argzdev** [comment]
Hi @etjson, thanks for reaching out to us. Could you file a new issue with details from our template? This is so that we can conduct an initial investigation with the necessary information from your issue. That said, I'll close this issue now. Thanks!
