### ISSUE TITLE
java.lang.SecurityException: Unknown calling package name 'xxx.xxx.xxx'.

### ISSUE THREAD

**Issue by etjson** [firebase/firebase-android-sdk#5024]
### [READ] Step 1: Are you in the right place?

yes

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Flamingo | 2022.2.1
  * Firebase Component: Analytics, Crashlytics
  * Component version: Firebase Android BoM 32.0.0

#### Steps to reproduce:

I can't reproduce this issue as it was reported to me by users of my product and it happens before initialization

Currently only user-provided exception logs:

```java
java.lang.SecurityException: Unknown calling package name 'xxx.xxx.xxx'.
at android.os.Parcel.createExceptionOrNull(Parcel.java:2426)
at android.os.Parcel.createException(Parcel.java:2410)
at android.os.Parcel.readException(Parcel.java:2393)
at android.os.Parcel.readException(Parcel.java:2335)
...
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:211)
at android.os.Looper.loop(Looper.java:300)
at android.app.ActivityThread.main(ActivityThread.java:8298)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
```

#### Relevant Code:

Without code, as long as the product is integrated without any calls, it will also cause the user to crash abnormally. At present, only one user has reported this problem. I want to know if it is related to the gms environment of the user?

**Comment by argzdev** [comment]
Thanks for filing again, @etjson. Looking at your stacktrace, there's no indication that Firebase is causing the issue. Looking through our [documentation](https://firebase.google.com/docs/android/android-play-services), Crashlytics/Analytics doesn't require Google Play services, so I'm guessing that shouldn't be the problem. 

>  I want to know if it is related to the gms environment of the user?

I'm not sure, this would depend on the package name being called in `Unknown calling package name 'xxx.xxx.xxx'.`, if the error is `package name: com.google.android.gms"`, then that would definitely mean that there's an issue with the gms.

However currently with your given details, can you share with me why you think Firebase is causing the issue?

**Comment by argzdev** [comment]
Hi @etjson, sorry for the delayed response. If changing the integration of `com.google.gms.google-services` is causing the issue. Then one option you could do is use `FirebaseOptions` to instantiate your firebase programmatically instead of using google-services. You can read through our blog [here](https://firebase.blog/posts/2016/12/how-does-firebase-initialize-on-android). Let me know if that helps. Thanks!

**Comment by etjson** [comment]
> Hi @etjson, sorry for the delayed response. If changing the integration of `com.google.gms.google-services` is causing the issue. Then one option you could do is use `FirebaseOptions` to instantiate your firebase programmatically instead of using google-services. You can read through our blog [here](https://firebase.blog/posts/2016/12/how-does-firebase-initialize-on-android). Let me know if that helps. Thanks!

@argzdev 

Yes, currently I am using FirebaseOptions to integrate, but I still need the crash service, because the gradle plug-in is not used, and the obfuscation-related files are not uploaded. How can crash be integrated programmatically?

```text
resValue "string", "com.crashlytics.android.build_id", "${versionCode}"
```

Although doing so can make the application run normally, the crash service does not seem to be correct.

**Comment by argzdev** [comment]
Yeah, unfortunately Crashlytics does not have a way to be integrated programmatically. The way I see it, this is a good way of mitigating the issue, however I don't know why your app would be crashing due to a gradle plugin, could you share with me your project level build.gradle? Maybe we're missing something.

P.S.: Was this happening on an old or newest version of `com.google.firebase:firebase-crashlytics-gradle`. If you haven't already, could you try version `2.9.5` and see if that changes anything? Thanks.

**Comment by etjson** [comment]
> Yeah, unfortunately Crashlytics does not have a way to be integrated programmatically. The way I see it, this is a good way of mitigating the issue, however I don't know why your app would be crashing due to a gradle plugin, could you share with me your project level build.gradle? Maybe we're missing something.
> 
> P.S.: Was this happening on an old or newest version of `com.google.firebase:firebase-crashlytics-gradle`. If you haven't already, could you try version `2.9.5` and see if that changes anything? Thanks.

```text
classpath 'com.google.gms:google-services:4.3.15'
classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.5'
```

```text
plugins {
    ...
    id 'com.google.gms.google-services'
    id 'com.google.firebase.crashlytics'
}
...
implementation 'com.google.firebase:firebase-analytics-ktx:21.2.2'
implementation 'com.google.firebase:firebase-crashlytics-ktx:18.3.7'
```
@argzdev 
This is the version used at that time. I am trying to contact the user to cooperate with me in collecting abnormal information. I will report the latest progress here in time.

**Comment by etjson** [comment]
@argzdev 
crashlytics collected exceptions from several users

```java
Fatal Exception: java.lang.SecurityException: Unknown calling package name 'xxx'.
       at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
       at android.os.Parcel.createException(Parcel.java:2995)
       at android.os.Parcel.readException(Parcel.java:2978)
       at android.os.Parcel.readException(Parcel.java:2920)
       at com.google.android.gms.common.internal.zzac.getService(zzac.java:31)
       at com.google.android.gms.common.internal.BaseGmsClient.getRemoteService(BaseGmsClient.java:109)
       at com.google.android.gms.common.internal.BaseGmsClient$LegacyClientCallbackAdapter.onReportServiceBinding(BaseGmsClient.java:109)
       at com.google.android.gms.common.internal.zzg.zzd(zzg.java:8)
       at com.google.android.gms.common.internal.zza.ʿʽʼˆˈˆ(zza.java:9)
       at com.google.android.gms.common.internal.zzc.zze(zzc.java:342)
       at com.google.android.gms.common.internal.zzb.handleMessage(zzb.java:342)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:210)
       at android.os.Looper.loop(Looper.java:299)
       at android.app.ActivityThread.main(ActivityThread.java:8247)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
```

Redmi K60 Pro / Android 13

stack trace file:
[stacktrace.txt](https://github.com/firebase/firebase-android-sdk/files/12115121/stacktrace.txt)

**Comment by argzdev** [comment]
Hi @etjson, thanks for the stacktrace. It seems that the error is due to an error in the network call. Specifically when Crashlytics calling `at com.google.firebase.sessions.settings.RemoteSettingsFetcher$doConfigFetch$2.invokeSuspend(RemoteSettingsFetcher.java:200)`. I'm thinking that the issue could that the user has unstable internet connectivity or is using a VPN. I'll see what we can do here. Thanks!

**Comment by jrothfeder** [comment]
This was fixed (see mitigation above). Please update to latest version to get these changes and feel free to open a new issue if this problem continues.
