### ISSUE TITLE
Getting StackOverflowError crash when recordException in invoked in crashlytics

### ISSUE THREAD

**Issue by aloysiusralph** [firebase/firebase-android-sdk#5102]
### Environment

  * Android Studio version: Android Studio Dolphin | 2021.3.1 Patch 1
  * Firebase Component: Crashlytics
  * Component version: 18.0.0 +( Firebase BOM 28.0.0+)

#### Steps to reproduce:

We are recording rxjava exceptions using the recordException method in FirebaseCrashlytics class. It is working fine with firebase BOM-27.1.0 (crashlytics 17.4.1).

Recently when we upgraded the firebase BOM to 32.1.0 (crashlytics 18.3.7), when the recordException is invoked, it is resulting in the StackOverflowError crash. With further investigations, we found that it is happening from BOM 28.0.0(crashlytics 18.0.0)

The issue is intermittent and has 8/10 reproducibility.

The crash is happening in TrimmedThrowableData class where it ends up in recursive loop because the exception sent here is having infinite number of causes.

Upon further debugging with the firebase crashlytics source code, we found that the exception has finite causes up until writeNonFatalException method in CrashlyticsController class. Inside the CrashlyticsBackgroundWorker runnable the same exception has infinite causes.

#### Crash Logs:

```
   E  FATAL EXCEPTION: Crashlytics Exception Handler1

                                                                                                   Process: com.mobile.android.dev, PID: 7371

                                                                                                    java.lang.StackOverflowError: stack size 1039KB

                                                                                                    at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:126)

                                                                                                    at java.lang.AbstractStringBuilder.appendNull(AbstractStringBuilder.java:494)

                                                                                                    at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:447)

                                                                                                    at java.lang.StringBuilder.append(StringBuilder.java:137)

                                                                                                    at com.google.firebase.crashlytics.internal.stacktrace.TrimmedThrowableData.<init>(TrimmedThrowableData.java:32)

                                                                                                    at com.google.firebase.crashlytics.internal.stacktrace.TrimmedThrowableData.<init>(TrimmedThrowableData.java:42)

                                                                                                    at com.google.firebase.crashlytics.internal.stacktrace.TrimmedThrowableData.<init>(TrimmedThrowableData.java:42)

                                                                                                    at com.google.firebase.crashlytics.internal.stacktrace.TrimmedThrowableData.<init>(TrimmedThrowableData.java:42)

                                                                                                    at com.google.firebase.crashlytics.internal.stacktrace.TrimmedThrowableData.<init>(TrimmedThrowableData.java:42)

                                                                                                    at com.google.firebase.crashlytics.internal.stacktrace.TrimmedThrowableData.<init>(TrimmedThrowableData.java:42)

                                                                                                    at com.google.firebase.crashlytics.internal.stacktrace.TrimmedThrowableData.<init>(TrimmedThrowableData.java:42)

                                                                                                    at com.google.firebase.crashlytics.internal.stacktrace.TrimmedThrowableData.<init>(TrimmedThrowableData.java:42)

                                                                                                    at com.google.firebase.crashlytics.internal.stacktrace.TrimmedThrowableData.<init>(TrimmedThrowableData.java:42)

                                                                                                    at com.google.firebase.crashlytics.internal.stacktrace.TrimmedThrowableData.<init>(TrimmedThrowableData.java:42)

                                                                                                    at com.google.firebase.crashlytics.internal.stacktrace.TrimmedThrowableData.<init>(TrimmedThrowableData.java:42)

                                                                                                    at com.google.firebase.crashlytics.internal.stacktrace.TrimmedThrowableData.<init>(TrimmedThrowableData.java:42)

                                                                                                    at com.google.firebase.crashlytics.internal.stacktrace.TrimmedThrowableData.<init>(TrimmedThrowableData.java:42)

                                                                                                    at com.google.firebase.crashlytics.internal.stacktrace.TrimmedThrowableData.<init>(TrimmedThrowableData.java:42)

                                                                                                    at com.google.firebase.crashlytics.internal.stacktrace.TrimmedThrowableData.<init>(TrimmedThrowableData.java:42)

                                                                                                    at com.google.firebase.crashlytics.internal.stacktrace.TrimmedThrowableData.<init>(TrimmedThrowableData.java:42)

                                                                                                    at com.google.firebase.crashlytics.internal.stacktrace.TrimmedThrowableData.<init>(TrimmedThrowableData.java:42)

                                                                                                    at com.google.firebase.crashlytics.internal.stacktrace.TrimmedThrowableData.<init>(TrimmedThrowableData.java:42)

                                                                                                    at com.google.firebase.crashlytics.internal.stacktrace.TrimmedThrowableData.<init>(TrimmedThrowableData.java:42)

                                                                                                    at com.google.firebase.crashlytics.internal.stacktrace.TrimmedThrowableData.<init>(TrimmedThrowableData.java:42)

                                                                                                    at com.google.firebase.crashlytics.internal.stacktrace.TrimmedThrowableData.<init>(TrimmedThrowableData.java:42)

                                                                                                    at com.google.firebase.crashlytics.internal.stacktrace.TrimmedThrowableData.<init>(TrimmedThrowableData.java:42)

                                                                                                    at com.google.firebase.crashlytics.internal.stacktrace.TrimmedThrowableData.<init>(TrimmedThrowableData.java:42)

                                                                                                    at com.google.firebase.crashlytics.internal.stacktrace.TrimmedThrowableData.<init>(TrimmedThrowableData.java:42)

                                                                                                    at com.google.firebase.crashlytics.internal.stacktrace.TrimmedThrowableData.<init>(TrimmedThrowableData.java:42)

                                                                                                    at com.google.firebase.crashlytics.internal.stacktrace.TrimmedThrowableData.<init>(TrimmedThrowableData.java:42)

                                                                                                    at com.google.firebase.crashlytics.internal.stacktrace.TrimmedThrowableData.<init>(TrimmedThrowableData.java:42)

                                                                                                    at com.google.firebase.crashlytics.internal.stacktrace.TrimmedThrowableData.<init>(TrimmedThrowableData.java:42)

                                                                                                    at com.google.firebase.crashlytics.internal.stacktrace.TrimmedThrowableData.<init>(TrimmedThrowableData.java:42)

                                                                                                    at com.google.firebase.crashlytics.internal.stacktrace.TrimmedThrowableData.<init>(TrimmedThrowableData.java:42)

                                                                                                    at com.google.firebase.crashlytics.internal.stacktrace.TrimmedThrowableData.<init>(TrimmedThrowableData.java:42)

2023-06-06 05:38:56.586  7371-7406  AndroidRuntime          com.mobile.android.dev         E  at com.google.firebase.crashlytics.internal.stacktrace.TrimmedThrowableData.<init>(TrimmedThrowableData.java:42)

                                                                                                    at com.google.firebase.crashlytics.internal.stacktrace.TrimmedThrowableData.<init>(TrimmedThrowableData.java:42)

                                                                                                    at com.google.firebase.crashlytics.internal.stacktrace.TrimmedThrowableData.<init>(TrimmedThrowableData.java:42)

                                                                                                    at com.google.firebase.crashlytics.internal.stacktrace.TrimmedThrowableData.<init>(TrimmedThrowableData.java:42)

                                                                                                    at com.google.firebase.crashlytics.internal.stacktrace.TrimmedThrowableData.<init>(TrimmedThrowableData.java:42)

                                                                                                    at com.google.firebase.crashlytics.internal.common.CrashlyticsReportDataCapture.captureEventData(CrashlyticsReportDataCapture.java:102)

                                                                                                    at com.google.firebase.crashlytics.internal.common.SessionReportingCoordinator.persistEvent(SessionReportingCoordinator.java:279)

                                                                                                    at com.google.firebase.crashlytics.internal.common.SessionReportingCoordinator.persistNonFatalEvent(SessionReportingCoordinator.java:134)

                                                                                                    at com.google.firebase.crashlytics.internal.common.CrashlyticsController$6.run(CrashlyticsController.java:442)

                                                                                                    at com.google.firebase.crashlytics.internal.common.CrashlyticsBackgroundWorker$2.call(CrashlyticsBackgroundWorker.java:93)

                                                                                                    at com.google.firebase.crashlytics.internal.common.CrashlyticsBackgroundWorker$2.call(CrashlyticsBackgroundWorker.java:90)

                                                                                                    at com.google.firebase.crashlytics.internal.common.CrashlyticsBackgroundWorker$3.then(CrashlyticsBackgroundWorker.java:105)

                                                                                                    at com.google.android.gms.tasks.zzc.run(com.google.android.gms:play-services-tasks@@18.0.2:3)

                                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)

                                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)

                                                                                                    at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:67)

                                                                                                    at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:27)

                                                                                                    at java.lang.Thread.run(Thread.java:1012)

---------------------------- PROCESS ENDED (7371) for package com.mobile.android.dev ----------------------------
```

**Comment by argzdev** [comment]
Hi @aloysiusralph, thanks for reporting this. Is there any chance you could share with us a minimal reproducible example of your issue? That'll help us out a lot. Thanks!

**Comment by mrober** [comment]
This was resolved in a recent version of the Crashlytics SDK. Please try the latest version, and reopen this is the issue persists.

**Comment by LokeshHP** [comment]
@mrober 
Crash occurs even with latest Firebase BOM 32.7.4. But with a different Stacktrace. Can you please re-open this ticket

```
FATAL EXCEPTION: Crashlytics Exception Handler1
Process: con.android.dev, PID:
java.lang.OutOfMemoryError: Failed to allocate a 335544336 byte allocation with 25149440 free bytes and 317MB until  OOM, target footprint 229033128, growth limit 536870912
at java.util.Arrays.copyOf(Arrays.java:3553)
at java.util.Arrays.copyOf(Arrays.java:3522)
at java.util.Vector.grow(Vector.java:262)
at java.util.Vector.grow(Vector.java:266)
at java.util.Vector.add(Vector.java:782)
at java.util.Vector.addElement(Vector.java:617)
at java.util.Stack.push(Stack.java:66)
at com.google.firebase.crashlytics.internal.stacktrace.TrimmedThrowableData.makeTrimmedThrowableData(TrimmedThrowableData.java:47)
at com.google.firebase.crashlytics.internal.common.CrashlyticsReportDataCapture.captureEventsData(CrashlyticsReportDataCapture.java:106)
```
