### ISSUE TITLE
[firebase-crashlytics-ndk] Execution failed for task ':app:injectCrashlyticsBuildIdsDebug'

### ISSUE THREAD

**Issue by sergeiignatov** [firebase/firebase-android-sdk#5105]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Flamingo | 2022.2.1 Patch 2
  * Firebase Component: firebase-crashlytics-ndk
  * Component version: firebase-bom:32.1.1, firebase-crashlytics-gradle:2.9.6

### [REQUIRED] Step 3: Describe the problem

This is a follow-up to #4699 

We have prebuilt .so library built with Go for Android (go version go1.19.5 linux/amd64). With latest firebase updates build fails with "Execution failed for task ':app:injectCrashlyticsBuildIdsDebug'."

#### Steps to reproduce:

Clone https://github.com/sergeiignatov/golangdemo and try to build it

Gradle build fails

```
> Task :app:injectCrashlyticsBuildIdsDebug FAILED
Execution failed for task ':app:injectCrashlyticsBuildIdsDebug'.
> -67

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:injectCrashlyticsBuildIdsDebug'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:149)
	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:147)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:135)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:74)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:42)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:338)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:325)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:318)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:304)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:463)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:380)
	at org.gradle.execution.plan.DefaultPlanExecutor.process(DefaultPlanExecutor.java:116)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph.executeWithServices(DefaultTaskExecutionGraph.java:136)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph.execute(DefaultTaskExecutionGraph.java:121)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:35)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:51)
	at org.gradle.execution.BuildOperationFiringBuildWorkerExecutor$ExecuteTasks.call(BuildOperationFiringBuildWorkerExecutor.java:54)
	at org.gradle.execution.BuildOperationFiringBuildWorkerExecutor$ExecuteTasks.call(BuildOperationFiringBuildWorkerExecutor.java:43)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	at org.gradle.execution.BuildOperationFiringBuildWorkerExecutor.execute(BuildOperationFiringBuildWorkerExecutor.java:40)
	at org.gradle.internal.build.DefaultBuildLifecycleController.lambda$executeTasks$7(DefaultBuildLifecycleController.java:172)
	at org.gradle.internal.model.StateTransitionController.doTransition(StateTransitionController.java:258)
	at org.gradle.internal.model.StateTransitionController.lambda$tryTransition$8(StateTransitionController.java:185)
	at org.gradle.internal.work.DefaultSynchronizer.withLock(DefaultSynchronizer.java:44)
	at org.gradle.internal.model.StateTransitionController.tryTransition(StateTransitionController.java:185)
	at org.gradle.internal.build.DefaultBuildLifecycleController.executeTasks(DefaultBuildLifecycleController.java:172)
	at org.gradle.internal.build.DefaultBuildWorkGraphController$DefaultBuildWorkGraph.runWork(DefaultBuildWorkGraphController.java:209)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:249)
	at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:109)
	at org.gradle.composite.internal.DefaultBuildController.doRun(DefaultBuildController.java:172)
	at org.gradle.composite.internal.DefaultBuildController.access$000(DefaultBuildController.java:47)
	at org.gradle.composite.internal.DefaultBuildController$BuildOpRunnable.run(DefaultBuildController.java:191)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
Caused by: java.lang.NegativeArraySizeException: -67
	at com.google.firebase.crashlytics.buildtools.ndk.internal.dwarf.DebugLineStateMachine.configureContext(DebugLineStateMachine.java:81)
	at com.google.firebase.crashlytics.buildtools.ndk.internal.dwarf.DebugLineStateMachine.runFromCurrentOffset(DebugLineStateMachine.java:43)
	at com.google.firebase.crashlytics.buildtools.ndk.internal.dwarf.DebugLineStateMachine.runForIndex(DebugLineStateMachine.java:68)
	at com.google.firebase.crashlytics.buildtools.ndk.internal.dwarf.DwarfDataParser.readDebugLineDataAtIndex(DwarfDataParser.java:119)
	at com.google.firebase.crashlytics.buildtools.ndk.internal.dwarf.DwarfDataParser.parse(DwarfDataParser.java:84)
	at com.google.firebase.crashlytics.buildtools.ndk.internal.elf.ElfDataParser.parseElf(ElfDataParser.java:152)
	at com.google.firebase.crashlytics.buildtools.ndk.internal.elf.ElfDataParser.parse(ElfDataParser.java:97)
	at com.google.firebase.crashlytics.buildtools.ndk.internal.elf.ElfDataParser.parse(ElfDataParser.java:42)
	at com.google.firebase.crashlytics.buildtools.buildids.BuildIdInfoCollector.getBuildIdInfo(BuildIdInfoCollector.java:34)
	at com.google.firebase.crashlytics.buildtools.buildids.BuildIdInfoCollector.collect(BuildIdInfoCollector.java:25)
	at com.google.firebase.crashlytics.buildtools.Buildtools.injectBuildIdsIntoResource(Buildtools.java:200)
	at com.google.firebase.crashlytics.buildtools.Buildtools$injectBuildIdsIntoResource$4.call(Unknown Source)
	at com.google.firebase.crashlytics.buildtools.gradle.tasks.InjectBuildIdsTask.injectBuildIds(InjectBuildIdsTask.groovy:56)
```

#### Relevant Code:

https://github.com/sergeiignatov/golangdemo
https://github.com/sergeiignatov/golangdemo/blob/main/app/prebuilt/arm64-v8a/libwebrtc_worker.so

**Comment by argzdev** [comment]
Hi @sergeiignatov, thanks for following up. Looking up into the issue, it seems that there's already a fix on the way. While waiting for that, could you try using the fix [uploaded](https://github.com/firebase/firebase-android-sdk/issues/4280#issuecomment-1595201503) by our engineer in the thread and see if that works?

> Hi folks, I have a fix for the issue with large files on Windows. Unfortunately, it didn't make it into this release. I built an artifact you can use for now, please try it and let me know if you have any problems.
> 
> Download and extract [m2repository.zip](https://github.com/firebase/firebase-android-sdk/files/11774265/m2repository.zip), and then add it to your build by doing something like:
> 
> ```
> pluginManagement {
>  repositories {
>    maven { url "/path/to/artifact" }
>     ...
>   }
> }
> ```
> (for kts use maven { url = uri("file:///path/to/artifact") } syntax instead)
>
> And then use the plugin by
> 
> id 'com.google.firebase.crashlytics' version '2.9.7-alpha' apply false

**Comment by sergeiignatov** [comment]
Hi @argzdev, I already tried 2.9.7-alpha and build still fails with -67 error. 

Since #4699 error code was 134, not -67, I suggest it's other issue than #4280.

**Comment by argzdev** [comment]
Got it, thanks for clarifying, @sergeiignatov. Give me a moment to reproduce the issue with your MCVE, then I'll notify our engineers.

**Comment by mrober** [comment]
Thanks for providing the reproducing example @sergeiignatov, it made it very easy for me to fix this issue! The fix that will be included in the next release of the Crashlytics Gradle plug in in a couple weeks. I will update this ticket when it's released.
