### ISSUE TITLE
Uncaught exception in Firebase Database runloop (20.2.1)

### ISSUE THREAD

**Issue by bylowerik** [firebase/firebase-android-sdk#5129]
* Android Studio version: Android Studio Flamingo
  * Firebase Component: Database
  * Component version: 10.2.3 (Flutter)

Since I updated my Flutter app I can see that the app has started to crash for users on Android (primarily Samsung Galaxy). It did not happen before and I have not changed the code for working on the database. I have updated so that all Firebase packages are the latest. I do not have an Android device that my app is crashing on. I can only see it in Firebase Crashlytics. Here is the latest stack trace:

The info I am given in the log is: **Should this problem persist, please file a report at https://github.com/firebase/firebase-android-sdk**

This is my entry point where I enable `persistenceData`

 ```
 try {
    WidgetsFlutterBinding.ensureInitialized();
    cameras = await availableCameras();
  } on CameraException catch (e) {
    print("Could not find cameras: $e");
  }
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  FirebaseDatabase.instance.setPersistenceEnabled(true);
  runApp(const MyApp());
}
```

```
Fatal Exception: java.lang.RuntimeException: Uncaught exception in Firebase Database runloop (20.2.1). If you are not already on the latest version of the Firebase SDKs, try updating your dependencies. Should this problem persist, **please file a report at https://github.com/firebase/firebase-android-sdk**
       at com.google.firebase.database.android.AndroidPlatform$1$1.run(AndroidPlatform.java:6)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8757)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

```
Caused by java.lang.RuntimeException: java.lang.AssertionError: hardAssert failed: listen() called twice for same QuerySpec.
       at com.google.firebase.database.core.persistence.DefaultPersistenceManager.runInTransaction(DefaultPersistenceManager.java:30)
       at com.google.firebase.database.core.SyncTree.addEventRegistration(SyncTree.java:7)
       at com.google.firebase.database.core.SyncTree.keepSynced(SyncTree.java:15)
       at com.google.firebase.database.core.Repo.keepSynced(Repo.java:35)
       at com.google.firebase.database.core.Repo.keepSynced(Repo.java:1)
       at com.google.firebase.database.Query$4.run(Query.java:10)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
       at java.util.concurrent.FutureTask.run(FutureTask.java:264)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)
```

```
Caused by java.lang.AssertionError: hardAssert failed: listen() called twice for same QuerySpec.
       at com.google.firebase.database.connection.ConnectionUtils.hardAssert(ConnectionUtils.java:26)
       at com.google.firebase.database.connection.PersistentConnectionImpl.listen(PersistentConnectionImpl.java:50)
       at com.google.firebase.database.core.Repo$5.startListening(Repo.java:41)
       at com.google.firebase.database.core.SyncTree.setupListener(SyncTree.java:19)
       at com.google.firebase.database.core.SyncTree.access$1000(SyncTree.java)
       at com.google.firebase.database.core.SyncTree$13.call(SyncTree.java:393)
       at com.google.firebase.database.core.SyncTree$13.call(SyncTree.java)
       at com.google.firebase.database.core.persistence.DefaultPersistenceManager.runInTransaction(DefaultPersistenceManager.java:5)
       at com.google.firebase.database.core.SyncTree.addEventRegistration(SyncTree.java:7)
       at com.google.firebase.database.core.SyncTree.keepSynced(SyncTree.java:15)
       at com.google.firebase.database.core.Repo.keepSynced(Repo.java:35)
       at com.google.firebase.database.core.Repo.keepSynced(Repo.java:1)
       at com.google.firebase.database.Query$4.run(Query.java:10)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
       at java.util.concurrent.FutureTask.run(FutureTask.java:264)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)
 ```
#### Steps to reproduce:

Cannot reproduce on my own. Works well on all emulators I have tried. Happens on Android devices only.

**Comment by argzdev** [comment]
Hi @bylowerik, thanks for reaching out. The error `listen() called twice for same QuerySpec.` indicates that the listeners are registering on the same query. I'm guessing that it might be possible that the listeners are re-registered during the redraw cycle or lifecycle change of the app. Could you share with me what was the previous working version of Database where you using before encountering this issue? Also could you try testing if going to the background and then foreground of the app triggers this issue? Thanks!

**Comment by bylowerik** [comment]
Hi thanks for looking into this. The version where I did not see any issues on Firebase Crashlytics was:

`firebase_database: ^9.0.11`

Unfortunately I have not been able to replicate by switching between foreground and background. I have now used 

`fireflutter configure`

and rebuilt the app in a new directory where I created a new flutter project and then copied the source files. We'll see if that works.

**Comment by argzdev** [comment]
I'm trying to figure out what's the equivalent native version of `firebase_database: ^9.0.11` of Flutter in Android. Judging from the release date, the issue might've began on Firebase Android Database versions `20.0.5` onwards. 

Sure, let me know if the rebuilt app works.

**Comment by bylowerik** [comment]
I did not upgrade for quite some time so it can have worked on new versions than `^9.0.11`. No crashes so far since the last update. But I don't have that many users on the week. Hopefully more now over the weekend.

**Comment by teamacco** [comment]
Hi, I have same issue with firebase 10.2.3 and Flutter 3.7.3
and Crashlytics reports currently affect only Samsung Galaxy devices.

**Comment by bylowerik** [comment]
I have not had any crashes since I used the cli and created a new project. I have not had that many users either so maybe that is why! 😜

**Comment by argzdev** [comment]
Just bumping this thread, are you still able to encounter this issue, @bylowerik?

**Comment by bylowerik** [comment]
No since the update with cli it has worked perfectly.  (Or my users disappeared 😉) No crashes though.

**Comment by argzdev** [comment]
That's interesting but also odd. Let's close this thread for now. If ever you or others encounter this issue again feel free to come back here to let me know so I can reopen. Then we can prioritize a more deeper investigation if the issue impacts more developers. Thanks for the quick update!

**Comment by teamacco** [comment]
Hi @argzdev  this issue still exist in my project. 
I had 33 events in Crashlytics the last week with 
Flutter 3.7.3
firebase_core: 2.14.0  
firebase_database: 10.2.4
