### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException: Internal error in Cloud Firestore (24.6.1)

### ISSUE THREAD

**Issue by fanwgwg** [firebase/firebase-android-sdk#5130]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Flamingo | 2022.2.1 Patch 2
  * Firebase Component:  Firestore
  * Component version: 24.6.1

### [REQUIRED] Step 3: Describe the problem

This is the first app release with firestore and I'm seeing this crash on about 2% of users. However, from the stacktrace I can't link it back to my code and the error says Cloud Firestore internal error, so I assumed that this is something internally that's going wrong.

#### Steps to reproduce:

Stack trace: 
```
Fatal Exception: java.lang.RuntimeException: Internal error in Cloud Firestore (24.6.1).
       at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$3(AsyncQueue.java:69)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:211)
       at android.os.Looper.loop(Looper.java:300)
       at android.app.ActivityThread.main(ActivityThread.java:8294)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
```
```
Caused by java.lang.RuntimeException: java.lang.NullPointerException: Attempt to read from field 're.p oe.e0.b' on a null object reference in method 'boolean oe.f0.h(re.h)'
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor.lambda$executeAndReportResult$1(AsyncQueue.java:436)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
       at java.util.concurrent.FutureTask.run(FutureTask.java:264)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:15)
       at java.lang.Thread.run(Thread.java:1012)
```
```
Caused by java.lang.NullPointerException: Attempt to read from field 're.p oe.e0.b' on a null object reference in method 'boolean oe.f0.h(re.h)'
       at com.google.firebase.firestore.core.OrderBy.getField(OrderBy.java:118)
       at com.google.firebase.firestore.core.Query.matchesOrderBy(Query.java:118)
       at com.google.firebase.firestore.core.Query.matches(Query.java:118)
       at com.google.firebase.firestore.local.SQLiteRemoteDocumentCache.lambda$getDocumentsMatchingQuery$3(SQLiteRemoteDocumentCache.java:10)
       at com.google.firebase.firestore.local.SQLiteRemoteDocumentCache.lambda$processRowInBackground$2(SQLiteRemoteDocumentCache.java:40)
       at com.google.firebase.firestore.util.BackgroundQueue.lambda$execute$0(BackgroundQueue.java:50)
       at com.google.firebase.firestore.util.ThrottledForwardingExecutor.execute(ThrottledForwardingExecutor.java:20)
       at com.google.firebase.firestore.util.BackgroundQueue.execute(BackgroundQueue.java:14)
       at com.google.firebase.firestore.local.SQLiteRemoteDocumentCache.processRowInBackground(SQLiteRemoteDocumentCache.java:32)
       at com.google.firebase.firestore.local.SQLiteRemoteDocumentCache.lambda$getAll$1(SQLiteRemoteDocumentCache.java:220)
       at com.google.firebase.firestore.local.SQLitePersistence$Query.forEach(SQLitePersistence.java:220)
       at com.google.firebase.firestore.local.SQLiteRemoteDocumentCache.getAll(SQLiteRemoteDocumentCache.java:220)
       at com.google.firebase.firestore.local.SQLiteRemoteDocumentCache.getDocumentsMatchingQuery(SQLiteRemoteDocumentCache.java:14)
       at com.google.firebase.firestore.local.LocalDocumentsView.getDocumentsMatchingCollectionQuery(LocalDocumentsView.java:18)
       at com.google.firebase.firestore.local.LocalDocumentsView.getDocumentsMatchingCollectionGroupQuery(LocalDocumentsView.java:156)
       at com.google.firebase.firestore.local.LocalDocumentsView.getDocumentsMatchingQuery(LocalDocumentsView.java:156)
       at com.google.firebase.firestore.local.QueryEngine.appendRemainingResults(QueryEngine.java:2)
       at com.google.firebase.firestore.local.QueryEngine.performQueryUsingRemoteKeys(QueryEngine.java:188)
       at com.google.firebase.firestore.local.QueryEngine.getDocumentsMatchingQuery(QueryEngine.java:188)
       at com.google.firebase.firestore.local.LocalStore.executeQuery(LocalStore.java:188)
       at com.google.firebase.firestore.core.SyncEngine.initializeViewAndComputeSnapshot(SyncEngine.java:271)
       at com.google.firebase.firestore.core.SyncEngine.listen(SyncEngine.java:271)
       at com.google.firebase.firestore.core.EventManager.addQueryListener(EventManager.java:271)
       at com.google.firebase.firestore.core.FirestoreClient.lambda$listen$7(FirestoreClient.java:271)
       at com.google.firebase.firestore.util.AsyncQueue.lambda$enqueue$2(AsyncQueue.java:11)
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor.lambda$executeAndReportResult$1(AsyncQueue.java:422)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
       at java.util.concurrent.FutureTask.run(FutureTask.java:264)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:15)
       at java.lang.Thread.run(Thread.java:1012)
```

**Comment by cherylEnkidu** [comment]
Hi @fanwgwg , from the log, we can only tell one `orderBy` class generate null reference. But inside the codebase, it is not obvious which parts leads to the problem. Could you please provide some reproduce code or the query that crashes?

**Comment by cherylEnkidu** [comment]
This issue has been fixed, and it will comes out in the next version: https://github.com/firebase/firebase-android-sdk/pull/5099
