### ISSUE TITLE
com.google.firebase.components.Lazy.get.  CRASH.  

### ISSUE THREAD

**Issue by msoliman22** [firebase/firebase-android-sdk#5134]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: happening on real device Model:Nokia 4.2.  and Pixel 3
  * Firebase Component: Firebase Auth
  * Component version: 'com.google.firebase:firebase-auth:21.0.1'

### [REQUIRED] Step 3: Describe the problem
we got like 9 crashed with these logs and it's all under this title com.google.firebase.components.Lazy.get. 
main (blocked):tid=1 systid=3743 | waiting to lock <0x01a90a51> (com.google.firebase.components.Lazy) held by thread 55
       at com.google.firebase.components.Lazy.get(Lazy.java:50)
       at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents(ComponentRuntime.java:291)
       at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(ComponentRuntime.java:281)
       at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:584)
       at com.google.firebase.FirebaseApp.access$400(FirebaseApp.java:89)
       at com.google.firebase.FirebaseApp$UserUnlockReceiver.onReceive(FirebaseApp.java:648)
       at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1580)
       at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(lambda)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7697)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)

RxCachedThreadScheduler-3 (blocked):tid=55 systid=4613 | waiting to lock <0x01c442b6> (java.lang.Object) held by thread 1
       at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:200)
       at com.google.firebase.auth.internal.zzbg.zzf(com.google.firebase:firebase-auth@@21.0.1:21)
       at com.google.firebase.auth.internal.zzbg.zza(com.google.firebase:firebase-auth@@21.0.1:7)
       at com.google.firebase.auth.FirebaseAuth.<init>(com.google.firebase:firebase-auth@@21.0.1:18)
       at com.google.firebase.auth.internal.zzv.<init>(com.google.firebase:firebase-auth@@21.0.1:1)
       at com.google.firebase.auth.FirebaseAuthRegistrar.lambda$getComponents$0(com.google.firebase:firebase-auth@@21.0.1:2)
       at com.google.firebase.auth.zzv.create(com.google.firebase:firebase-auth@@21.0.1)
       at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0$com-google-firebase-components-ComponentRuntime(ComponentRuntime.java:132)
       at com.google.firebase.components.ComponentRuntime$$ExternalSyntheticLambda1.get(D8$$SyntheticClass)
       at com.google.firebase.components.Lazy.get(Lazy.java:53)
       at com.google.firebase.components.AbstractComponentContainer.get(AbstractComponentContainer.java:27)
       at com.google.firebase.components.ComponentRuntime.get(ComponentRuntime.java:45)
       at com.google.firebase.FirebaseApp.get(FirebaseApp.java:336)
       at com.google.firebase.auth.FirebaseAuth.getInstance(com.google.firebase:firebase-auth@@21.0.1:2)
       at leviathan.inftynet.com.readerapp.repo.InfiReaderRepo.lambda$getToken$7(InfiReaderRepo.java:146)
       at leviathan.inftynet.com.readerapp.repo.InfiReaderRepo$$ExternalSyntheticLambda4.subscribe(D8$$SyntheticClass)
       at io.reactivex.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:39)
       at io.reactivex.Single.subscribe(Single.java:3666)
       at io.reactivex.internal.operators.single.SingleObserveOn.subscribeActual(SingleObserveOn.java:35)
       at io.reactivex.Single.subscribe(Single.java:3666)
       at io.reactivex.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:36)
       at io.reactivex.Single.subscribe(Single.java:3666)
       at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
       at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
#### Steps to reproduce:

it's ANR issue so I don't know exactly the situation 

#### Relevant Code:
  FirebaseAuth.getInstance()
				.getAccessToken(true)

**Comment by argzdev** [comment]
Hi @msoliman22, thanks for reaching out. Any chance you're using any dependency injection manager? If so, could you share a bit of details how you inject Firebase Auth in your app?
