### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by billdizl** [firebase/firebase-android-sdk#5172]
Fatal Exception: java.lang.NoSuchMethodError: No interface method (Ljava/lang/Object;)Z in class Ljava/util/Set; or its super classes (declaration of 'java.util.Set' appears in /apex/com.android.runtime/javalib/core-oj.jar)
       at com.google.firebase.perf.application.AppStateMonitor.unregisterForAppState(AppStateMonitor.java:283)
       at com.google.firebase.perf.application.AppStateUpdateHandler.unregisterForAppState(AppStateUpdateHandler.java:65)
       at com.google.firebase.perf.metrics.Trace.stop(Trace.java:255)
       at com.google.firebase.perf.application.FragmentStateMonitor.onFragmentPaused(FragmentStateMonitor.java:101)
       at androidx.fragment.app.FragmentLifecycleCallbacksDispatcher.dispatchOnFragmentPaused(FragmentLifecycleCallbacksDispatcher.java:222)
       at androidx.fragment.app.FragmentStateManager.pause(FragmentStateManager.java:631)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:293)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1374)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2841)
       at androidx.fragment.app.FragmentManager.dispatchPause(FragmentManager.java:2802)
       at androidx.fragment.app.FragmentController.dispatchPause(FragmentController.java:295)
       at androidx.fragment.app.FragmentActivity.onPause(FragmentActivity.java:366)
       at com.chiquedoll.chiquedoll.view.activity.BaseActivity.onPause(BaseActivity.java:564)
       at com.chiquedoll.chiquedoll.view.activity.MainActivity.onPause(MainActivity.java:1459)
       at android.app.Activity.performPause(Activity.java:8400)
       at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1529)
       at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5415)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5374)
       at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:5314)
       at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:46)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:190)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:105)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:219)
       at android.app.ActivityThread.main(ActivityThread.java:8668)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
```

**Comment by argzdev** [comment]
Hi @billdizl, thanks for reaching out. In order for us to understand the issue better, could you answer a few questions for us:
1. Can you share with us a minimal reproducible example of this issue? Could you also share steps how to reproduce this behavior?
2. Could you share with us what version did you encounter this issue?

Thanks!
