### ISSUE TITLE
NPE in sessions when packageInfo.versionName returns null

### ISSUE THREAD

**Issue by gerbiljames** [firebase/firebase-android-sdk#5195]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 2022.2.1 Patch 2
  * Firebase Component: Analytics, Dynamic Links, Remote Config, Cloud Messaging
  * Component version: BoM 32.2.0

#### Steps to reproduce:

When the Firebase SDK is initialised in an environment where `packageInfo.versionName` returns `null` an NPE is thrown. This is specifically happening for instrumented tests when the testing target is an Android library and not an application.

#### Relevant Code:

Captured stack trace:
```
java.lang.NullPointerException: packageInfo.versionName must not be null
	at com.google.firebase.sessions.SessionEvents.getApplicationInfo(SessionEvents.kt:77)
	at com.google.firebase.sessions.FirebaseSessions.<init>(FirebaseSessions.kt:41)
	at com.google.firebase.sessions.FirebaseSessionsRegistrar.getComponents$lambda-0(FirebaseSessionsRegistrar.kt:48)
	at com.google.firebase.sessions.FirebaseSessionsRegistrar.$r8$lambda$JITndpZCWeA0w9BDlkcI3l22oGY(Unknown Source:0)
	at com.google.firebase.sessions.FirebaseSessionsRegistrar$$ExternalSyntheticLambda0.create(Unknown Source:0)
	at com.google.firebase.tracing.ComponentMonitor.lambda$processRegistrar$0(ComponentMonitor.java:38)
	at com.google.firebase.tracing.ComponentMonitor$$ExternalSyntheticLambda0.create(Unknown Source:4)
	at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0$com-google-firebase-components-ComponentRuntime(ComponentRuntime.java:140)
	at com.google.firebase.components.ComponentRuntime$$ExternalSyntheticLambda1.get(Unknown Source:4)
	at com.google.firebase.components.Lazy.get(Lazy.java:53)
	at com.google.firebase.components.ComponentContainer$-CC.$default$get(ComponentContainer.java:48)
	at com.google.firebase.components.ComponentRuntime.get(Unknown Source:0)
	at com.google.firebase.components.ComponentContainer$-CC.$default$get(ComponentContainer.java:24)
	at com.google.firebase.components.ComponentRuntime.get(Unknown Source:0)
	at com.google.firebase.components.RestrictedComponentContainer.get(RestrictedComponentContainer.java:89)
	at com.google.firebase.crashlytics.CrashlyticsRegistrar.buildCrashlytics(CrashlyticsRegistrar.java:69)
	at com.google.firebase.crashlytics.CrashlyticsRegistrar.$r8$lambda$Pfd5XmDCFzNyAT9o9H6rDnTBQE4(Unknown Source:0)
	at com.google.firebase.crashlytics.CrashlyticsRegistrar$$ExternalSyntheticLambda0.create(Unknown Source:2)
	at com.google.firebase.tracing.ComponentMonitor.lambda$processRegistrar$0(ComponentMonitor.java:38)
	at com.google.firebase.tracing.ComponentMonitor$$ExternalSyntheticLambda0.create(Unknown Source:4)
	at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0$com-google-firebase-components-ComponentRuntime(ComponentRuntime.java:140)
	at com.google.firebase.components.ComponentRuntime$$ExternalSyntheticLambda1.get(Unknown Source:4)
	at com.google.firebase.components.Lazy.get(Lazy.java:53)
	at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents(ComponentRuntime.java:302)
	at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(ComponentRuntime.java:292)
	at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:607)
	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:300)
	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:264)
```

**Comment by gerbiljames** [comment]
@mrober That fixed it thanks. I originally tried to specify it in `build.gradle` for the library but it wasn't being populated in the manifest for some reason.
