### ISSUE TITLE
TOO_MANY_REGISTRATIONS crash

### ISSUE THREAD

**Issue by yunuseker** [firebase/firebase-android-sdk#5253]
I am trying to get Firebase push token in our app. I don't see any problems in my tests. But when I go live the app, I get this problem at odd hours and on strange devices. I'm assuming these devices are the ones google uses for testing. Some SoF(StackOverFlow) answers also confirm this prediction. But a short time ago, this problem started to appear on real devices as well. A developer on SoF said that the device should be reset to factory settings, but I can't ask this from every live user.

 **This is my dependencies**
 implementation platform('com.google.firebase:firebase-bom:32.0.0')
    implementation 'com.google.android.gms:play-services-maps:18.1.0'
    implementation 'com.google.maps.android:android-maps-utils:0.6.2'
    implementation 'com.google.android.gms:play-services-location:21.0.1'
    implementation 'com.google.firebase:firebase-messaging'
    implementation 'com.google.firebase:firebase-analytics-ktx'
    implementation 'com.google.firebase:firebase-crashlytics'
    implementation 'com.google.firebase:firebase-config-ktx'
    implementation 'com.google.firebase:firebase-perf-ktx'

**This is error**
Fatal Exception: com.google.android.gms.tasks.RuntimeExecutionException: java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: TOO_MANY_REGISTRATIONS
       at com.google.android.gms.tasks.zzw.getResult(com.google.android.gms:play-services-tasks@@18.0.2:3)
       at com.xxx.xxx.ui.login.LoginFrg.initListeners$lambda$1$lambda$0(LoginFrg.kt:54)
       at com.xxx.xxx.ui.login.LoginFrg.$r8$lambda$K047hxzQv8WgpLMzzyLMSJ5Xxv0()
       at com.xxx.xxx.ui.login.LoginFrg$$ExternalSyntheticLambda4.onComplete(:4)
       at com.google.android.gms.tasks.zzi.run(com.google.android.gms:play-services-tasks@@18.0.2:1)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7680)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:423)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by argzdev** [comment]
Thanks for reaching out, @yunuseker. So this can happen for 2 reasons:

1. When a client app has a multitude of apps registered with FCM, this would trigger the `TOO_MANY_REGISTRATIONS` error. The problem here is, the only mitigation is for the user to delete some of the other client apps from the device to make room for the new one. 
2. Otherwise, the device is likely "cloned" from another one, so that multiple device have the same identifiers. In this case, the best thing is factory-reset.

Unfortunately, there's nothing we can do on the SDK side since we don't have any visibility on the backend. It'll be best for you to reach out to our [Firebase support](https://firebase.google.com/support/troubleshooter/contact) for better assistance. You'll be able to share your project details and configuration which will allow them to support you better. Thanks!
