### ISSUE TITLE
ANR Firebase-Messaging-Intent-Handle (runnable)  android.os.MessageQueue.nativePollOnce

### ISSUE THREAD

**Issue by hpdx** [firebase/firebase-android-sdk#5258]
use `api 'com.google.firebase:firebase-messaging-ktx:23.1.2'`

Firebase-Messaging-Intent-Handle (runnable):tid=57 systid=32691 
       at android.app.KeyguardManager.<init>(KeyguardManager.java:197)
       at android.app.SystemServiceRegistry$35.createService(SystemServiceRegistry.java:737)
       at android.app.SystemServiceRegistry$35.createService(SystemServiceRegistry.java:734)
       at android.app.SystemServiceRegistry$CachedServiceFetcher.getService(SystemServiceRegistry.java:2496)
       at android.app.SystemServiceRegistry.getSystemService(SystemServiceRegistry.java:2173)
       at android.app.ContextImpl.getSystemService(ContextImpl.java:2202)
       at android.content.ContextWrapper.getSystemService(ContextWrapper.java:917)
       at com.google.firebase.messaging.DisplayNotification.isAppForeground(DisplayNotification.java:62)
       at com.google.firebase.messaging.DisplayNotification.handleNotification(DisplayNotification.java:104)
       at com.google.firebase.messaging.FirebaseMessagingService.dispatchMessage(FirebaseMessagingService.java:221)
       at com.google.firebase.messaging.FirebaseMessagingService.passMessageIntentToSdk(FirebaseMessagingService.java:185)
       at com.google.firebase.messaging.FirebaseMessagingService.handleMessageIntent(FirebaseMessagingService.java:172)
       at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(FirebaseMessagingService.java:161)
       at com.google.firebase.messaging.EnhancedIntentService.lambda$processIntent$0$com-google-firebase-messaging-EnhancedIntentService(EnhancedIntentService.java:78)
       at com.google.firebase.messaging.EnhancedIntentService$$ExternalSyntheticLambda0.run(unavailable:6)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@18.2.0:2)
       at java.lang.Thread.run(Thread.java:1012)

**Comment by argzdev** [comment]
Hi @hpdx, given the nature of ANRs, it's difficult for us to conduct an initial investigation without any code snippets, or steps on how to reproduce this behavior. A stacktrace is not enough for us to investigate this further. That said, could you share details such as:

1. Steps to reproduce this behavior
2. Code snippet or [MCVE](https://stackoverflow.com/help/minimal-reproducible-example)?
