### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/time/DurationUnit;

### ISSUE THREAD

**Issue by hpdx** [firebase/firebase-android-sdk#5259]
at com.google.firebase.sessions.Time.elapsedRealtime-UwyO8pc(Time.kt:37)
                 	at com.google.firebase.sessions.SessionInitiator.<init>(SessionInitiator.kt:40)
                 	at com.google.firebase.sessions.FirebaseSessions.<init>(FirebaseSessions.kt:67)
                 	at com.google.firebase.sessions.FirebaseSessionsRegistrar.getComponents$lambda-0(FirebaseSessionsRegistrar.kt:48)
                 	at com.google.firebase.sessions.FirebaseSessionsRegistrar.$r8$lambda$JITndpZCWeA0w9BDlkcI3l22oGY(Unknown Source:0)
                 	at com.google.firebase.sessions.FirebaseSessionsRegistrar$$ExternalSyntheticLambda0.create(Unknown Source:0)
                 	at com.google.firebase.tracing.ComponentMonitor.lambda$processRegistrar$0(ComponentMonitor.java:38)
                 	at com.google.firebase.tracing.ComponentMonitor$$ExternalSyntheticLambda0.create(Unknown Source:4)
                 	at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0$com-google-firebase-components-ComponentRuntime(ComponentRuntime.java:140)
                 	at com.google.firebase.components.ComponentRuntime$$ExternalSyntheticLambda1.get(Unknown Source:4)
                 	at com.google.firebase.components.Lazy.get(Lazy.java:53)
                 	at com.google.firebase.components.ComponentContainer.get(ComponentContainer.java:48)
                 	at com.google.firebase.components.ComponentContainer.get(ComponentContainer.java:24)
                 	at com.google.firebase.components.RestrictedComponentContainer.get(RestrictedComponentContainer.java:89)
                 	at com.google.firebase.perf.FirebasePerfRegistrar.lambda$getComponents$0(FirebasePerfRegistrar.java:82)
                 	at com.google.firebase.perf.FirebasePerfRegistrar$$ExternalSyntheticLambda1.create(Unknown Source:2)
                 	at com.google.firebase.tracing.ComponentMonitor.lambda$processRegistrar$0(ComponentMonitor.java:38)
                 	at com.google.firebase.tracing.ComponentMonitor$$ExternalSyntheticLambda0.create(Unknown Source:4)
                 	at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0$com-google-firebase-components-ComponentRuntime(ComponentRuntime.java:140)
                 	at com.google.firebase.components.ComponentRuntime$$ExternalSyntheticLambda1.get(Unknown Source:4)
                 	at com.google.firebase.components.Lazy.get(Lazy.java:53)
                 	at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents(ComponentRuntime.java:302)
                 	at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(ComponentRuntime.java:292)
                 	at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:607)
                 	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:300)
                 	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:264)
                 	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:249)
                 	at com.google.firebase.provider.FirebaseInitProvider.onCreate(FirebaseInitProvider.java:69)
                 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2468)
                 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2433)
                 	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(FirebaseInitProvider.java:61)
                 	at android.app.ActivityThread.installProvider(ActivityThread.java:7981)
                 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7492)
                 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7220)
                 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2241)
                 	at android.os.Handler.dispatchMessage(Handler.java:106)
                 	at android.os.Looper.loopOnce(Looper.java:211)
                 	at android.os.Looper.loop(Looper.java:300)
                 	at android.app.ActivityThread.main(ActivityThread.java:8410)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

**Comment by argzdev** [comment]
Hi @hpdx, thanks for reaching out. Unfortunately, just the stacktrace isn't enough for us to investigate this further. That said, could you provide other details such as:

1. What Firebase products and versions are you using?
2. Are you using Firebase BoM versioning?
3. Could you provide steps to reproduce this behavior?
4. Any code snippet or minimal reproducible example you can share with us?

Thanks!
