### ISSUE TITLE
Unable to mockk okhttp3.Call.Factory in Robolectric test when firebase-perf is enabled

### ISSUE THREAD

**Issue by mkubiczek** [firebase/firebase-android-sdk#5260]
### Environment

  * Android Studio version: 
  * Firebase Component: Firebase Performance
  * Component version: >= 20.3.1
  * Firebase performance plugin version: 1.4.2
  * Mockk library version : 1.13.7
  * Robolectric version: 4.10.3

### Problem
Unable to mockk okhttp Call.Factory in a Robolectric test. 

#### Steps to reproduce:

* Add firebase performance to the project
* Have a class `Requester` that takes Call.Factory as an constructor parameter and a method `doRequest` that makes new okhttp3 call and executes it
* In the `Requester` class use the call factory to create a call and execute it
* Make a Robolectric  test that mocks Call.Factory using Mockk library and pass the factory to the new instance of the `Requester` class 
* Invoke the `doRequest` method
* See the exception

#### Relevant Code:

```
class Requester(private val callFactory: Call.Factory) {

    fun doRequest() {
        callFactory.newCall(Request.Builder().url("https://google.com").build())
            .enqueue(object : Callback {
                override fun onFailure(call: Call, e: IOException) {}

                override fun onResponse(call: Call, response: Response) {}
            })
    }
}


@RunWith(RobolectricTestRunner::class)
class ExampleUnitTest {

    @Test
    fun exampleUntTest() {
        val call: Call = mockk(relaxed = true)
        val callFactory: Call.Factory = mockk {
            every { newCall(any()) } returns call
        }

        Requester(callFactory).doRequest()
    }
}
```

Running the test results with the following exception

```
java.lang.ExceptionInInitializerError
	at com.google.firebase.perf.config.ConfigResolver.<init>(ConfigResolver.java:78)
	at com.google.firebase.perf.config.ConfigResolver.getInstance(ConfigResolver.java:86)
	at com.google.firebase.perf.application.AppStateMonitor.<init>(AppStateMonitor.java:98)
	at com.google.firebase.perf.application.AppStateMonitor.getInstance(AppStateMonitor.java:87)
	at com.google.firebase.perf.metrics.NetworkRequestMetricBuilder.<init>(NetworkRequestMetricBuilder.java:92)
	at com.google.firebase.perf.metrics.NetworkRequestMetricBuilder.builder(NetworkRequestMetricBuilder.java:84)
	at com.google.firebase.perf.network.InstrumentOkHttpEnqueueCallback.<init>(InstrumentOkHttpEnqueueCallback.java:42)
	at com.google.firebase.perf.network.FirebasePerfOkHttpClient.enqueue(FirebasePerfOkHttpClient.java:73)
	at com.threekk.firebaseperf.issue.Requester.doRequest(Requester.kt:13)
	at com.threekk.firebaseperf.issue.ExampleUnitTest.exampleUntTest(ExampleUnitTest.kt:21)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:589)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$2(SandboxTestRunner.java:290)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:99)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process null. Make sure to call FirebaseApp.initializeApp(Context) first.
	at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:179)
	at com.google.firebase.perf.config.RemoteConfigManager.getInitialStartupMillis(RemoteConfigManager.java:91)
	at com.google.firebase.perf.config.RemoteConfigManager.<init>(RemoteConfigManager.java:85)
	at com.google.firebase.perf.config.RemoteConfigManager.<clinit>(RemoteConfigManager.java:52)
	... 26 more

```

#### Comments

I believe both firebase perf and mockk are doing bytecode manipulations to instrument the class and either they're executed in wrong order or even mockk is unable to do its job after what firebase perf plugin 

#### Attachments
A toy project that is reproducing the issue
[firebase-perf-issue.zip](https://github.com/firebase/firebase-android-sdk/files/12377013/firebase-perf-issue.zip)
has done.

**Comment by argzdev** [comment]
Hi @mkubiczek, thanks for reaching out. Unfortunately, I'm having problems opening the attached project you've provided. However, I did test the code snippet, but so far I'm not encountering the said issues.

Relevant code:
app/build.gradle
```
    implementation 'com.google.firebase:firebase-perf:20.3.2'
    implementation 'com.google.firebase:firebase-perf-ktx:20.3.2'
    implementation 'com.squareup.okhttp3:okhttp:4.11.0'
    testImplementation 'io.mockk:mockk:1.13.7'
    testImplementation 'org.robolectric:robolectric:4.10.3'
```

project/build.gradle
```
    id 'com.google.firebase.firebase-perf' version '1.4.2' apply false
```

<img width="1207" alt="Screenshot 2023-08-21 at 7 48 12 PM" src="https://github.com/firebase/firebase-android-sdk/assets/93124282/cf1e5355-b122-46d9-bee9-308a51f2198b">

Not sure what I'm missing here to reproduce this behavior.

**Comment by mkubiczek** [comment]
Please find the attached project, not sure what happens with the archive last time.
[firebase-perf-issue.zip](https://github.com/firebase/firebase-android-sdk/files/12397955/firebase-perf-issue.zip)

**Comment by argzdev** [comment]
Okay, I was able to reproduce the same behavior now. Thanks for the extra details. I'll notify our engineers and see what we can do here.

**Comment by mkubiczek** [comment]
Any update on this one? @argzdev

**Comment by mkubiczek** [comment]
Would be good if you could provide something to turn off the `Call.Factory` instrumentation just for the test.
I workarounded it eventually mocking `FirebasePerfOkHttpClient`

```
mockkStatic(FirebasePerfOkHttpClient::class)
every { FirebasePerfOkHttpClient.enqueue(any<Call>(), any<Callback>()) } answers {
    (args[0] as Call).enqueue(args[1] as Callback)
}
 ```

**Comment by MichaelVerdon** [comment]
Are you still experiencing this issue on the latest Firebase versions?

**Comment by mkubiczek** [comment]
yes, although the exception is different now.
```Method elapsedRealtime in android.os.SystemClock not mocked. See https://developer.android.com/r/studio-ui/build/not-mocked for details.```

Still it means FirebasePerfOkHttpClient was used in tests.

**Comment by lehcar09** [comment]
Hi @mkubiczek, I tried reproducing this issue, and I was able to encounter the issue. However, this has been resolved after updating to latest version of dependencies.

Here's the version I used:
```
  implementation("com.squareup.okhttp3:okhttp:5.3.2")
  testImplementation("io.mockk:mockk-jvm:1.14.9")
  implementation("org.robolectric:robolectric:4.16.1")

  implementation(platform("com.google.firebase:firebase-bom:34.9.0"))
  implementation("com.google.firebase:firebase-perf")
```

That said, I'll close this issue now. Please let us know if there's another issue. Thanks!
