### ISSUE TITLE
firebase-auth:22.2.1 - com.google.android.gms.internal.firebase-auth-api.zzwk: java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by DeuceTheCoder** [firebase/firebase-android-sdk#5266]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Giraffe | 2022.3.1
  * Firebase Component: Firebase Auth
  * Component version: 22.2.1

### [REQUIRED] Step 3: Describe the problem
Since upgrading our Firebase BOM from 32.2.0 to 32.2.2, we've received a number of obfuscated crash reports in Firebase Crashlytics that we are unable to reproduce or diagnose.

#### Steps to reproduce:

Have not been able to reproduce. Crashes generally occur within a second of the session start

#### Relevant Code:

```
Fatal Exception: com.google.android.gms.internal.firebase-auth-api.zzwk: java.lang.ArrayIndexOutOfBoundsException: length=2; index=-1
       at com.google.firebase.auth.internal.zzbt.zzd(zzbt.java:38)
       at com.google.firebase.auth.FirebaseAuth.zzT(com.google.firebase:firebase-auth@@22.1.1:14)
       at com.google.firebase.auth.zzx.zza(zzx.java:1)
       at com.google.android.gms.internal.firebase-auth-api.zzzc.zzb(com.google.firebase:firebase-auth@@22.1.1:3)
       at com.google.android.gms.internal.firebase-auth-api.zzabs.zzj(com.google.firebase:firebase-auth@@22.1.1:1)
       at com.google.android.gms.internal.firebase-auth-api.zzabp.zzq(com.google.firebase:firebase-auth@@22.1.1:2)
       at com.google.android.gms.internal.firebase-auth-api.zzaaq.zzq(com.google.firebase:firebase-auth@@22.1.1:1)
       at com.google.android.gms.internal.firebase-auth-api.zzxj.zzb(com.google.firebase:firebase-auth@@22.1.1:2)
       at com.google.android.gms.internal.firebase-auth-api.zzaca.zzc(com.google.firebase:firebase-auth@@22.1.1:12)
       at com.google.android.gms.internal.firebase-auth-api.zzaca.zzb(com.google.firebase:firebase-auth@@22.1.1:14)
       at com.google.android.gms.internal.firebase-auth-api.zzabf.zzf(com.google.firebase:firebase-auth@@22.1.1:4)
       at com.google.android.gms.internal.firebase-auth-api.zzys.zzp(com.google.firebase:firebase-auth@@22.1.1:4)
       at com.google.android.gms.internal.firebase-auth-api.zzaar.zzj(com.google.firebase:firebase-auth@@22.1.1:3)
       at com.google.android.gms.internal.firebase-auth-api.zzzc.zzc(com.google.firebase:firebase-auth@@22.1.1:1)
       at com.google.android.gms.internal.firebase-auth-api.zzabt.run(com.google.firebase:firebase-auth@@22.1.1:1)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at com.google.firebase.concurrent.CustomThreadFactory.lambda$newThread$0(CustomThreadFactory.java:47)
       at java.lang.Thread.run(Thread.java:1012)
```
Caused by:
```
Caused by java.lang.ArrayIndexOutOfBoundsException: length=2; index=-1
       at java.util.ArrayList.get(ArrayList.java:439)
       at com.google.firebase.auth.internal.zzbt.zzd(zzbt.java:19)
       at com.google.firebase.auth.FirebaseAuth.zzT(com.google.firebase:firebase-auth@@22.1.1:14)
       at com.google.firebase.auth.zzx.zza(zzx.java:1)
       at com.google.android.gms.internal.firebase-auth-api.zzzc.zzb(com.google.firebase:firebase-auth@@22.1.1:3)
       at com.google.android.gms.internal.firebase-auth-api.zzabs.zzj(com.google.firebase:firebase-auth@@22.1.1:1)
       at com.google.android.gms.internal.firebase-auth-api.zzabp.zzq(com.google.firebase:firebase-auth@@22.1.1:2)
       at com.google.android.gms.internal.firebase-auth-api.zzaaq.zzq(com.google.firebase:firebase-auth@@22.1.1:1)
       at com.google.android.gms.internal.firebase-auth-api.zzxj.zzb(com.google.firebase:firebase-auth@@22.1.1:2)
       at com.google.android.gms.internal.firebase-auth-api.zzaca.zzc(com.google.firebase:firebase-auth@@22.1.1:12)
       at com.google.android.gms.internal.firebase-auth-api.zzaca.zzb(com.google.firebase:firebase-auth@@22.1.1:14)
       at com.google.android.gms.internal.firebase-auth-api.zzabf.zzf(com.google.firebase:firebase-auth@@22.1.1:4)
       at com.google.android.gms.internal.firebase-auth-api.zzys.zzp(com.google.firebase:firebase-auth@@22.1.1:4)
       at com.google.android.gms.internal.firebase-auth-api.zzaar.zzj(com.google.firebase:firebase-auth@@22.1.1:3)
       at com.google.android.gms.internal.firebase-auth-api.zzzc.zzc(com.google.firebase:firebase-auth@@22.1.1:1)
       at com.google.android.gms.internal.firebase-auth-api.zzabt.run(com.google.firebase:firebase-auth@@22.1.1:1)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at com.google.firebase.concurrent.CustomThreadFactory.lambda$newThread$0(CustomThreadFactory.java:47)
       at java.lang.Thread.run(Thread.java:1012)
```

**Comment by prameshj** [comment]
Thanks for reporting.. we are working on a fix. Meanwhile can you confirm if this is happening for users that are logging in anonymously or using any other provider?

This could happen if the FirebaseUser did not have any provider info or user id associated with them. We will include additional logging along with the fix to help future debugging easier.

**Comment by Vignesh-772** [comment]
@prameshj  This is happening when user are logging in anonymously.

**Comment by argzdev** [comment]
Hi all, if others also encounter this issue, please do leave a thumbs up on the original author's post so we can track the severity of the issue. Thanks!

**Comment by prameshj** [comment]
> @prameshj This is happening when user are logging in anonymously.

Are you seeing this for new users who are logging in anonymously? Or are these previously created users, which are now just reopening the app?

I am asking because this issue can happen only if there is no firebase info associated with the user json, which indicates a malformed representation of the user, that is in persistence.

**Comment by Vignesh-772** [comment]
Not sure about when it is happening. We don't have stack trace for the origin. 
This is how we implemented we will check getCurrentUser() if it is gives null then we are calling signInAnonymously().

**Comment by MarjanaKarzek** [comment]
We are not calling `signInAnonymously()` in our app

**Comment by vashisthg** [comment]
I am also getting a lot of crashes due to this in our production app in play store.

**Comment by prameshj** [comment]
Thanks for the responses. We hope to make the fix available in a following release soon.

As mentioned above, the issue should only happen if the persisted user info was in a malformed state, need not necessarily because of anonymous auth. If you do find a specific repro, please add details here (about the user sign in method, how long the account info was persisted for). This does not block the release of the fix, we are doing that in parallel. Thanks!

**Comment by ShivamGoyal1899** [comment]
@prameshj @NhienLam Any update on the fix for this? By when will this be rolled out?

**Comment by prameshj** [comment]
We will be including the fix in the upcoming release (should happen within the next 2 weeks). We will update here once the release notes are published.

**Comment by argzdev** [comment]
Hi folks, could you try the latest version `22.1.2` and see if the issue still persists? Thanks!

**Comment by argzdev** [comment]
HI folks, since we're no longer receiving any updates related to this. I'll close this for now. Feel free to let me know if we have to reopen this. Thanks!

**Comment by argzdev** [comment]
Hi @AdHrithik, checking the latest [release notes](https://github.com/firebase/flutterfire/blob/master/CHANGELOG.md#firebase_auth---v4100) in the flutterfire repo, it doesn't seem to be included. Please reach out to the [flutterfire](https://github.com/firebase/flutterfire/issues) team to get updates regarding their planned release date with the fix.
