### ISSUE TITLE
Users from China periodically have crashes

### ISSUE THREAD

**Issue by DrAssExplosion** [firebase/firebase-android-sdk#5271]
### ENVIRONMENT

  * Android Studio version: Android Studio Dolphin | 2021.3.1
  * Firebase Component: firebase-messaging
  * Component version: 23.1.1

### DESCRIBE THE PROBLEM

Users from China periodically have crashes, probably due to the fact that Google servers are blocked there or the connection speed is severely limited.

For example - Crash Report.
Time from start: 276 seconds
Device model: Nexus 5
Device manufacturer: LGE
Android version: 5.1.1

#### Steps to reproduce:

Have not been able to reproduce.

#### Relevant Code:

```
java.lang.IllegalStateException: Already connected
at java.net.URLConnection.checkNotConnected(URLConnection.java:463)
at java.net.URLConnection.setUseCaches(URLConnection.java:945)
at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.setUseCaches(DelegatingHttpsURLConnection.java:262)
at com.android.okhttp.internal.http.HttpsURLConnectionImpl.setUseCaches(HttpsURLConnectionImpl.java:25)
at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.openHttpURLConnection(FirebaseInstallationServiceClient.java:476)
at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.createFirebaseInstallation(FirebaseInstallationServiceClient.java:163)
at com.google.firebase.installations.FirebaseInstallations.registerFidWithServer(FirebaseInstallations.java:536)
at com.google.firebase.installations.FirebaseInstallations.doNetworkCallIfNecessary(FirebaseInstallations.java:390)
at com.google.firebase.installations.FirebaseInstallations.lambda$doRegistrationOrRefresh$3$FirebaseInstallations(FirebaseInstallations.java:375)
at com.google.firebase.installations.-$$Lambda$FirebaseInstallations$YC-tlBbbVeA4OFXGfTR3F_IXKyc.run(lambda)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
```

**Comment by argzdev** [comment]
Sorry, Firebase services are occasionally blocked by the firewall from China and it's not something we have any control over. So unfortunately, there's nothing we can do here.
