### ISSUE TITLE
FirebaseCrashlytics.init DiskReadViolation

### ISSUE THREAD

**Issue by nicolaf91** [firebase/firebase-android-sdk#5290]
### Environment

  * Android Studio version: 2022.3.1 RC 1
  * Firebase Component: Bom 32.2.3
  * Tested smartphones: Oppo A91 Android 11, Redmi Note 11 Android 12

### The problem
Upon opening the app I get the following Logs related to the violation of the StrictMode policies and it seems related to the crashlytics initialization:

`StrictMode policy violation; ~duration=1241 ms: android.os.strictmode.DiskReadViolation
                                                                                                    	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1596)
                                                                                                    	at libcore.io.BlockGuardOs.access(BlockGuardOs.java:71)
                                                                                                    	at libcore.io.ForwardingOs.access(ForwardingOs.java:72)
                                                                                                    	at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:8170)
                                                                                                    	at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:281)
                                                                                                    	at java.io.File.exists(File.java:815)
                                                                                                    	at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:700)
                                                                                                    	at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:691)
                                                                                                    	at android.app.ContextImpl.getFilesDir(ContextImpl.java:736)
                                                                                                    	at android.content.ContextWrapper.getFilesDir(ContextWrapper.java:263)
                                                                                                    	at com.google.firebase.crashlytics.internal.persistence.FileStore.<init>(FileStore.java:71)
                                                                                                    	at com.google.firebase.crashlytics.FirebaseCrashlytics.init(FirebaseCrashlytics.java:80)
                                                                                                    	at com.google.firebase.crashlytics.CrashlyticsRegistrar.buildCrashlytics(CrashlyticsRegistrar.java:71)
                                                                                                    	at com.google.firebase.crashlytics.CrashlyticsRegistrar.$r8$lambda$Pfd5XmDCFzNyAT9o9H6rDnTBQE4(Unknown Source:0)
                                                                                                    	at com.google.firebase.crashlytics.CrashlyticsRegistrar$$ExternalSyntheticLambda0.create(Unknown Source:2)
                                                                                                    	at com.google.firebase.tracing.ComponentMonitor.lambda$processRegistrar$0(ComponentMonitor.java:38)
                                                                                                    	at com.google.firebase.tracing.ComponentMonitor$$ExternalSyntheticLambda0.create(Unknown Source:4)
                                                                                                    	at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0$com-google-firebase-components-ComponentRuntime(ComponentRuntime.java:140)
                                                                                                    	at com.google.firebase.components.ComponentRuntime$$ExternalSyntheticLambda1.get(Unknown Source:4)
                                                                                                    	at com.google.firebase.components.Lazy.get(Lazy.java:53)
                                                                                                    	at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents(ComponentRuntime.java:302)
                                                                                                    	at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(ComponentRuntime.java:292)
                                                                                                    	at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:607)
                                                                                                    	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:300)
                                                                                                    	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:264)
                                                                                                    	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:249)
                                                                                                    	at com.google.firebase.provider.FirebaseInitProvider.onCreate(FirebaseInitProvider.java:69)
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2388)
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2358)
                                                                                                    	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(FirebaseInitProvider.java:61)
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:7841)
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7371)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7279)
                                                                                                    	at android.app.ActivityThread.access$1700(ActivityThread.java:299)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2184)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:264)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8312)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)`

[Full log](https://pastebin.com/4CS5E6pZ) 

#### Steps to reproduce:
Just open the app to get the problem.

#### Relevant Code:
The policy for what actions in the VM process:

` StrictMode.setVmPolicy( StrictMode.VmPolicy.Builder()
            .detectLeakedClosableObjects()
            .penaltyLog()
            .build())`

**Comment by argzdev** [comment]
Hi @nicolaf91, thanks for reaching out.

I've tested this by adding the following code and I also changed it to `penaltyDeath()`:
```
class CustomApplication: Application() {
    override fun onCreate() {
        super.onCreate()

        StrictMode.setVmPolicy(
            StrictMode.VmPolicy.Builder()
                .detectLeakedClosableObjects()
                .penaltyDeath()
                .build())
    }
}
```
However, I'm not encountering this in the latest version of `com.google.firebase:firebase-crashlytics-ktx` version `18.4.1` on any emulators. That said, could you answer a few questions below:
1. What version of `com.google.firebase:firebase-crashlytics-ktx` are you using? Could you try this in the latest version and see if the issue is reproducible?
2. Is this issue constantly reproducible?
3. Is this issue reproducible on physical devices only? Or is it reproducible on any emulators?

Any chance you could share code snippets or minimal reproducible example so we can investigate this further? Thanks!

**Comment by nicolaf91** [comment]
Hi, I was able to reproduce it systematically even in emulators by adding the `StrictMode` in the `init` method of the `Application` class.
`class PushApplication : Application() {

    init {
        StrictMode.setVmPolicy( StrictMode.VmPolicy.Builder()
            .detectLeakedClosableObjects()
            .penaltyLog()
            .build())
        StrictMode.enableDefaults()
    }

    override fun onCreate() {
        super.onCreate()
    }
}`

I'm using the following versions:
`implementation(platform("com.google.firebase:firebase-bom:32.2.3"))
    // Firebase Cloud Messaging (Kotlin)
    implementation("com.google.firebase:firebase-messaging-ktx:23.2.1")
    implementation("com.google.firebase:firebase-crashlytics-ktx:18.4.1")
    implementation("com.google.firebase:firebase-analytics-ktx:21.3.0")
`

**Comment by argzdev** [comment]
Hi @nicolaf91, I was able to reproduce the same behavior. Let me inform our engineers and see what we can do.
