### ISSUE TITLE
java.io.FileNotFoundException

### ISSUE THREAD

**Issue by lUjek-Sh** [firebase/firebase-android-sdk#5307]
Describe your environment

  * Android Studio version: Android Studio Giraffe | 2022.3.1 Patch 1
  * Firebase Component: [Analytics, Crashlytics, Messaging]
  * Component version: Bom platform version 32.2.3

Describe the problem

After add Firebase in project i have error

#### Relevant Code:

```
Could not open log file: /data/user/0/org.app.app/files/.com.google.firebase.crashlytics.files.v2:org.app.app/open-sessions/64FAEA18010D00016A299AA8B234273C/userlog
                                                                                                    java.io.FileNotFoundException: /data/user/0/org.app.app/files/.com.google.firebase.crashlytics.files.v2:org.app.app/open-sessions/64FAEA18010D00016A299AA8B234273C/userlog.tmp: open failed: ENOENT (No such file or directory)
                                                                                                    	at libcore.io.IoBridge.open(IoBridge.java:574)
                                                                                                    	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:289)
                                                                                                    	at com.google.firebase.crashlytics.internal.metadata.QueueFile.open(QueueFile.java:221)
                                                                                                    	at com.google.firebase.crashlytics.internal.metadata.QueueFile.initialize(QueueFile.java:202)
                                                                                                    	at com.google.firebase.crashlytics.internal.metadata.QueueFile.<init>(QueueFile.java:117)
                                                                                                    	at com.google.firebase.crashlytics.internal.metadata.QueueFileLogStore.openLogFile(QueueFileLogStore.java:128)
                                                                                                    	at com.google.firebase.crashlytics.internal.metadata.QueueFileLogStore.writeToLog(QueueFileLogStore.java:52)
                                                                                                    	at com.google.firebase.crashlytics.internal.metadata.LogFileManager.writeToLog(LogFileManager.java:64)
                                                                                                    	at com.google.firebase.crashlytics.internal.common.CrashlyticsController$5.call(CrashlyticsController.java:417)
                                                                                                    	at com.google.firebase.crashlytics.internal.common.CrashlyticsController$5.call(CrashlyticsController.java:413)
                                                                                                    	at com.google.firebase.crashlytics.internal.common.CrashlyticsBackgroundWorker$3.then(CrashlyticsBackgroundWorker.java:105)
                                                                                                    	at com.google.android.gms.tasks.zzc.run(com.google.android.gms:play-services-tasks@@18.0.2:3)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                                                    	at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:67)
                                                                                                    	at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:27)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
                                                                                                    	at libcore.io.Linux.open(Native Method)
                                                                                                    	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
                                                                                                    	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
                                                                                                    	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
                                                                                                    	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7758)
                                                                                                    	at libcore.io.IoBridge.open(IoBridge.java:560)
                                                                                                    	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:289) 
                                                                                                    	at com.google.firebase.crashlytics.internal.metadata.QueueFile.open(QueueFile.java:221) 
                                                                                                    	at com.google.firebase.crashlytics.internal.metadata.QueueFile.initialize(QueueFile.java:202) 
                                                                                                    	at com.google.firebase.crashlytics.internal.metadata.QueueFile.<init>(QueueFile.java:117) 
                                                                                                    	at com.google.firebase.crashlytics.internal.metadata.QueueFileLogStore.openLogFile(QueueFileLogStore.java:128) 
                                                                                                    	at com.google.firebase.crashlytics.internal.metadata.QueueFileLogStore.writeToLog(QueueFileLogStore.java:52) 
                                                                                                    	at com.google.firebase.crashlytics.internal.metadata.LogFileManager.writeToLog(LogFileManager.java:64) 
                                                                                                    	at com.google.firebase.crashlytics.internal.common.CrashlyticsController$5.call(CrashlyticsController.java:417) 
                                                                                                    	at com.google.firebase.crashlytics.internal.common.CrashlyticsController$5.call(CrashlyticsController.java:413) 
                                                                                                    	at com.google.firebase.crashlytics.internal.common.CrashlyticsBackgroundWorker$3.then(CrashlyticsBackgroundWorker.java:105) 
                                                                                                    	at com.google.android.gms.tasks.zzc.run(com.google.android.gms:play-services-tasks@@18.0.2:3) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) 
                                                                                                    	at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:67) 
                                                                                                    	at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:27) 
                                                                                                    	at java.lang.Thread.run(Thread.java:1012) 
```

**Comment by argzdev** [comment]
Hi @lUjek-Sh, thanks for reaching out. I tried adding Firebase on a clean project with the version `32.2.3`, I'm not experiencing the said issue. Is this issue consistent?

Also any chance you could share any code snippets or MCVE that you could share with us?
