### ISSUE TITLE
firebase-auth:22.1.1 - com.google.android.gms.internal.firebase-auth-api.zzwk: java.lang.NullPointerException

### ISSUE THREAD

**Issue by ShivamGoyal1899** [firebase/firebase-android-sdk#5311]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Iguana 2023.2.1 Canary 3
  * Firebase Component: Firebase Authentication
  * Component version: 22.1.1

### [REQUIRED] Step 3: Describe the problem

Since upgrading our Firebase BOM to 32.2.2, we've received several obfuscated crash reports in Firebase Crashlytics that we cannot reproduce or diagnose.

#### Steps to reproduce:

Have not been able to reproduce. Crashes generally occur within a second of the session's start.

#### Relevant Code:

```
Fatal Exception: com.google.android.gms.internal.firebase-auth-api.zzwk: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.firebase.auth.internal.zzt.f()' on a null object reference
       at com.google.firebase.auth.internal.zzbt.zzd(com.google.firebase:firebase-auth@@22.1.1:38)
       at com.google.firebase.auth.FirebaseAuth.zzT(com.google.firebase:firebase-auth@@22.1.1:14)
       at com.google.firebase.auth.zzx.zza(com.google.firebase:firebase-auth@@22.1.1:1)
       at com.google.android.gms.internal.firebase-auth-api.zzzc.zzb(com.google.firebase:firebase-auth@@22.1.1:3)
       at com.google.android.gms.internal.firebase-auth-api.zzabs.zzj(com.google.firebase:firebase-auth@@22.1.1:1)
       at com.google.android.gms.internal.firebase-auth-api.zzabp.zzq(com.google.firebase:firebase-auth@@22.1.1:2)
       at com.google.android.gms.internal.firebase-auth-api.zzaaq.zzq(com.google.firebase:firebase-auth@@22.1.1:1)
       at com.google.android.gms.internal.firebase-auth-api.zzxj.zzb(com.google.firebase:firebase-auth@@22.1.1:2)
       at com.google.android.gms.internal.firebase-auth-api.zzaca.zzc(com.google.firebase:firebase-auth@@22.1.1:12)
       at com.google.android.gms.internal.firebase-auth-api.zzaca.zzb(com.google.firebase:firebase-auth@@22.1.1:14)
       at com.google.android.gms.internal.firebase-auth-api.zzabf.zzf(com.google.firebase:firebase-auth@@22.1.1:4)
       at com.google.android.gms.internal.firebase-auth-api.zzys.zzp(com.google.firebase:firebase-auth@@22.1.1:4)
       at com.google.android.gms.internal.firebase-auth-api.zzaar.zzj(com.google.firebase:firebase-auth@@22.1.1:3)
       at com.google.android.gms.internal.firebase-auth-api.zzzc.zzc(com.google.firebase:firebase-auth@@22.1.1:1)
       at com.google.android.gms.internal.firebase-auth-api.zzabt.run(com.google.firebase:firebase-auth@@22.1.1:1)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at com.google.firebase.concurrent.CustomThreadFactory.lambda$newThread$0(CustomThreadFactory.java:47)
       at java.lang.Thread.run(Thread.java:1012)

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.firebase.auth.internal.zzt.f()' on a null object reference
       at com.google.firebase.auth.internal.zzbt.zzd(com.google.firebase:firebase-auth@@22.1.1:16)
       at com.google.firebase.auth.FirebaseAuth.zzT(com.google.firebase:firebase-auth@@22.1.1:14)
       at com.google.firebase.auth.zzx.zza(com.google.firebase:firebase-auth@@22.1.1:1)
       at com.google.android.gms.internal.firebase-auth-api.zzzc.zzb(com.google.firebase:firebase-auth@@22.1.1:3)
       at com.google.android.gms.internal.firebase-auth-api.zzabs.zzj(com.google.firebase:firebase-auth@@22.1.1:1)
       at com.google.android.gms.internal.firebase-auth-api.zzabp.zzq(com.google.firebase:firebase-auth@@22.1.1:2)
       at com.google.android.gms.internal.firebase-auth-api.zzaaq.zzq(com.google.firebase:firebase-auth@@22.1.1:1)
       at com.google.android.gms.internal.firebase-auth-api.zzxj.zzb(com.google.firebase:firebase-auth@@22.1.1:2)
       at com.google.android.gms.internal.firebase-auth-api.zzaca.zzc(com.google.firebase:firebase-auth@@22.1.1:12)
       at com.google.android.gms.internal.firebase-auth-api.zzaca.zzb(com.google.firebase:firebase-auth@@22.1.1:14)
       at com.google.android.gms.internal.firebase-auth-api.zzabf.zzf(com.google.firebase:firebase-auth@@22.1.1:4)
       at com.google.android.gms.internal.firebase-auth-api.zzys.zzp(com.google.firebase:firebase-auth@@22.1.1:4)
       at com.google.android.gms.internal.firebase-auth-api.zzaar.zzj(com.google.firebase:firebase-auth@@22.1.1:3)
       at com.google.android.gms.internal.firebase-auth-api.zzzc.zzc(com.google.firebase:firebase-auth@@22.1.1:1)
       at com.google.android.gms.internal.firebase-auth-api.zzabt.run(com.google.firebase:firebase-auth@@22.1.1:1)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at com.google.firebase.concurrent.CustomThreadFactory.lambda$newThread$0(CustomThreadFactory.java:47)
       at java.lang.Thread.run(Thread.java:1012)
```

**Comment by argzdev** [comment]
Thanks for reaching out, @ShivamGoyal1899. I've notified our engineers regarding the issue. We'll keep you posted once we get updates.

**Comment by 9468lgy** [comment]
After we upgraded from 22.0.0 to 22.1.1, new problems appeared, and they were worse than before. https://github.com/firebase/firebase-android-sdk/issues/5148
`Fatal Exception: com.google.android.gms.internal.firebase-auth-api.zzwk: java.lang.ArrayIndexOutOfBoundsException: length=2; index=-1
       at com.google.firebase.auth.internal.zzbt.zzd(com.google.firebase:firebase-auth@@22.1.1:38)
       at com.google.firebase.auth.FirebaseAuth.zzT(com.google.firebase:firebase-auth@@22.1.1:14)
       at com.google.firebase.auth.zzx.zza(com.google.firebase:firebase-auth@@22.1.1:1)
       at com.google.android.gms.internal.firebase-auth-api.zzzc.zzb(com.google.firebase:firebase-auth@@22.1.1:3)
       at com.google.android.gms.internal.firebase-auth-api.zzabs.zzj(com.google.firebase:firebase-auth@@22.1.1:1)
       at com.google.android.gms.internal.firebase-auth-api.zzabp.zzq(com.google.firebase:firebase-auth@@22.1.1:2)
       at com.google.android.gms.internal.firebase-auth-api.zzaaq.zzq(com.google.firebase:firebase-auth@@22.1.1:1)
       at com.google.android.gms.internal.firebase-auth-api.zzxj.zzb(com.google.firebase:firebase-auth@@22.1.1:2)
       at com.google.android.gms.internal.firebase-auth-api.zzaca.zzc(com.google.firebase:firebase-auth@@22.1.1:12)
       at com.google.android.gms.internal.firebase-auth-api.zzaca.zzb(com.google.firebase:firebase-auth@@22.1.1:14)
       at com.google.android.gms.internal.firebase-auth-api.zzabf.zzf(com.google.firebase:firebase-auth@@22.1.1:4)
       at com.google.android.gms.internal.firebase-auth-api.zzys.zzp(com.google.firebase:firebase-auth@@22.1.1:4)
       at com.google.android.gms.internal.firebase-auth-api.zzaar.zzj(com.google.firebase:firebase-auth@@22.1.1:3)
       at com.google.android.gms.internal.firebase-auth-api.zzzc.zzc(com.google.firebase:firebase-auth@@22.1.1:1)
       at com.google.android.gms.internal.firebase-auth-api.zzabt.run(com.google.firebase:firebase-auth@@22.1.1:1)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.firebase.concurrent.CustomThreadFactory.lambda$newThread$0(CustomThreadFactory.java:47)
       at java.lang.Thread.run(Thread.java:929)`

**Comment by ShivamGoyal1899** [comment]
@9468lgy This is a different issue and is tracked in #5266

**Comment by 9468lgy** [comment]
> @9468lgy This is a different issue and is tracked in #5266

Ok，thanks

**Comment by argzdev** [comment]
Hi folks, could you try the latest version `22.1.2` and see if the issue still persists? Thanks!

**Comment by UKMIITB** [comment]
@argzdev When would this version come as part of firebase BOM ?
Currently we are using BOM, will there be any compatibility issue if BOM 32.3.1 is used but for auth we use 22.1.2 ?

**Comment by argzdev** [comment]
@UKMIITB, the Firebase BoM version `32.3.1` already have the latest version of Firebase Auth `22.1.2`. There shouldn't be any issues using either option (BoM or auth)

**Comment by UKMIITB** [comment]
@argzdev 
Noted. Have updated the version. Will update here once after rollout is increased to a significant number

**Comment by ShivamGoyal1899** [comment]
Public Build with the fix went live yesterday. We are still monitoring the fix if it's working.

Will update here once after rollout is increased to a significant number.

**Comment by argzdev** [comment]
Got it, let's keep this open for now for monitoring. Thanks folks!

**Comment by argzdev** [comment]
Hi all, I'm assuming that the issue has been fixed, since it's been 2 weeks or so. Let me know if the issue is still present in the latest version. Thanks!

**Comment by takashi8** [comment]
Hi,

FirebaseUI issue with SafetyNet API (https://github.com/firebase/FirebaseUI-Android/issues/2133) has keeped https://github.com/firebase/firebase-android-sdk/issues/5148 open as mentioned at https://github.com/firebase/firebase-android-sdk/issues/5148#issuecomment-1658154057, but it has been migrated here and seems lost update.

> Just an update, our engineers are already working to updating the https://github.com/firebase/FirebaseUI-Android/issues/2133. We can wait for the latest version release, and see if that fixes the issue. I'll leave this open for now.

@argzdev  Do you know any update?  Thanks in advance.

**Comment by argzdev** [comment]
Hi @takashi8, it looks like the issue with [FirebaseUI with SafetyNet API](https://github.com/firebase/FirebaseUI-Android/issues/2133) that requires BoM update already has a [committed PR](https://github.com/firebase/FirebaseUI-Android/pull/2136) in another branch ([version-8.1.0-dev](https://github.com/firebase/FirebaseUI-Android/tree/version-8.1.0-dev)). Let me ask our engineer to see if when we'll get this merged to the main branch.
