### ISSUE TITLE
java.net.SocketTimeoutException: Read timed out 

### ISSUE THREAD

**Issue by a8453770** [firebase/firebase-android-sdk#5387]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio version:Android Studio Giraffe | 2022.3.1 Patch 1
  * Firebase Component: Crashlytics
  * Component version: 18.4.3

#### Steps to reproduce:
when i start app get error 

023-10-09 14:00:10.910 18578-18578 FirebaseApp             com.abox.apps                        I  Device unlocked: initializing all Firebase APIs for app [DEFAULT]
2023-10-09 14:00:10.980 18578-18578 FirebaseCrashlytics     com.abox.apps                        I  Initializing Firebase Crashlytics 18.4.3 for com.abox.apps
2023-10-09 14:00:10.997 18578-18578 FirebaseSessions        com.abox.apps                        D  Registering Sessions SDK subscriber with name: CRASHLYTICS, data collection enabled: true
2023-10-09 14:00:10.998 18578-18609 FirebaseSessions        com.abox.apps                        D  Data Collection is enabled for at least one Subscriber
2023-10-09 14:00:11.020 18578-18608 DynamiteModule          com.abox.apps                        I  Considering local module com.google.android.gms.measurement.dynamite:92 and remote module com.google.android.gms.measurement.dynamite:90
2023-10-09 14:00:11.020 18578-18608 DynamiteModule          com.abox.apps                        I  Selected local version of com.google.android.gms.measurement.dynamite
2023-10-09 14:00:11.034 18578-18578 FirebaseInitProvider    com.abox.apps                        I  FirebaseApp initialization successful
2023-10-09 14:00:11.045 18578-18578 System.out              com.abox.apps                        I  try to read channel info from apk : /data/app/~~iP9nAbiQN5Z_y3OMf3uvEA==/com.abox.apps-f7bwT7wqG8HMFyJwp6Z8RQ==/base.apk
2023-10-09 14:00:11.047 18578-18578 System.out              com.abox.apps                        I  find V2 signature block Id : 1896449818
2023-10-09 14:00:11.047 18578-18578 System.out              com.abox.apps                        I  getByteBufferValueById , destApk /data/app/~~iP9nAbiQN5Z_y3OMf3uvEA==/com.abox.apps-f7bwT7wqG8HMFyJwp6Z8RQ==/base.apk IdValueMap = {1896449818=java.nio.HeapByteBuffer[pos=0 lim=1308 cap=1308], 1114793335=java.nio.HeapByteBuffer[pos=0 lim=2732 cap=2732]}
2023-10-09 14:00:11.047 18578-18578 System.out              com.abox.apps                        I  getByteValueById , id = -2012129793 , value = null
2023-10-09 14:00:11.047 18578-18578 ChannelReaderUtil       com.abox.apps                        I  getChannelByV2 , channel = null
2023-10-09 14:00:11.048 18578-18578 System.out              com.abox.apps                        I  APK : /data/app/~~iP9nAbiQN5Z_y3OMf3uvEA==/com.abox.apps-f7bwT7wqG8HMFyJwp6Z8RQ==/base.apk not have channel info from Zip Comment
2023-10-09 14:00:11.048 18578-18578 ChannelReaderUtil       com.abox.apps                        I  getChannelByV1 , channel = null
2023-10-09 14:00:11.098 18578-18578 AppCompatDelegate       com.abox.apps                        D  Checking for metadata for AppLocalesMetadataHolderService : Service not found
2023-10-09 14:00:11.107 18578-18621 FA                      com.abox.apps                        I  App measurement initialized, version: 79000
2023-10-09 14:00:11.107 18578-18621 FA                      com.abox.apps                        I  To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
2023-10-09 14:00:11.107 18578-18621 FA                      com.abox.apps                        I  To enable faster debug mode event logging run:
                                                                                                      adb shell setprop debug.firebase.analytics.app com.abox.apps
2023-10-09 14:00:11.151 18578-18578 com.abox.apps           com.abox.apps                        W  Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
2023-10-09 14:00:11.151 18578-18578 com.abox.apps           com.abox.apps                        W  Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
2023-10-09 14:00:11.184 18578-18621 FA                      com.abox.apps                        I  Tag Manager is not found and thus will not be used
2023-10-09 14:00:11.206 18578-18624 AdrenoGLES-0            com.abox.apps                        I  QUALCOMM build                   : 85da404, I46ff5fc46f
                                                                                                    Build Date                       : 11/30/20
                                                                                                    OpenGL ES Shader Compiler Version: EV031.31.04.01
                                                                                                    Local Branch                     : promo490_3_Google
                                                                                                    Remote Branch                    : 
                                                                                                    Remote Branch                    : 
                                                                                                    Reconstruct Branch               : 
2023-10-09 14:00:11.206 18578-18624 AdrenoGLES-0            com.abox.apps                        I  Build Config                     : S P 10.0.4 AArch64
2023-10-09 14:00:11.206 18578-18624 AdrenoGLES-0            com.abox.apps                        I  Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
2023-10-09 14:00:11.209 18578-18624 AdrenoGLES-0            com.abox.apps                        I  PFP: 0x016ee189, ME: 0x00000000
2023-10-09 14:00:11.211 18578-18624 AdrenoUtils             com.abox.apps                        W  <ReadGpuID_from_sysfs:197>: Failed to open /sys/class/kgsl/kgsl-3d0/gpu_model
2023-10-09 14:00:11.211 18578-18624 AdrenoUtils             com.abox.apps                        W  <ReadGpuID:221>: Failed to read chip ID from gpu_model. Fallback to use the GSL path
2023-10-09 14:00:11.217 18578-18624 Gralloc4                com.abox.apps                        I  mapper 4.x is not supported
2023-10-09 14:00:21.081 18578-18612 FirebaseCrashlytics     com.abox.apps                        E  Settings request failed.
                                                                                                    java.net.SocketTimeoutException: Read timed out
                                                                                                    	at java.net.SocketInputStream.socketRead0(Native Method)
                                                                                                    	at java.net.SocketInputStream.socketRead(SocketInputStream.java:119)
                                                                                                    	at java.net.SocketInputStream.read(SocketInputStream.java:176)
                                                                                                    	at java.net.SocketInputStream.read(SocketInputStream.java:144)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:936)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:900)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:722)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:238)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:217)
                                                                                                    	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:196)
                                                                                                    	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
                                                                                                    	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
                                                                                                    	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
                                                                                                    	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
                                                                                                    	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
                                                                                                    	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
                                                                                                    	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
                                                                                                    	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
                                                                                                    	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
                                                                                                    	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
                                                                                                    	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
                                                                                                    	at com.google.firebase.crashlytics.internal.network.HttpGetRequest.execute(HttpGetRequest.java:78)
                                                                                                    	at com.google.firebase.crashlytics.internal.settings.DefaultSettingsSpiCall.invoke(DefaultSettingsSpiCall.java:112)
                                                                                                    	at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:200)
                                                                                                    	at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:193)
                                                                                                    	at com.google.android.gms.tasks.zzo.run(com.google.android.gms:play-services-tasks@@18.0.2:1)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:67)
                                                                                                    	at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:27)
                                                                                                    	at java.lang.Thread.run(Thread.java:923)
2023-10-09 14:00:21.087 18578-18610 FirebaseCrashlytics     com.abox.apps                        I  No version control information found

#### Relevant Code:

dependencies {

    implementation(platform("com.google.firebase:firebase-bom:32.3.1"))

    implementation("com.google.firebase:firebase-crashlytics-ktx")
    implementation 'com.google.firebase:firebase-analytics-ktx'
    implementation("com.google.android.gms:play-services-base:18.2.0")
}

class MainActivity : AppCompatActivity() {
    private var mFirebaseAnalytics: FirebaseAnalytics? = null

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        mFirebaseAnalytics = FirebaseAnalytics.getInstance(this)

        findViewById<TextView>(R.id.test_crash).setOnClickListener {
            FirebaseCrashlytics.getInstance().log("Crash button clicked.")
            throw RuntimeException("Test Crash"); // Force a crash
        }
        findViewById<TextView>(R.id.test_report).setOnClickListener {

            // [START custom_event]
            val bundle = Bundle()
            bundle.putString(FirebaseAnalytics.Param.METHOD, "abc")
            mFirebaseAnalytics!!.logEvent(FirebaseAnalytics.Event.SIGN_UP, bundle)

        }
    }
}

**Comment by argzdev** [comment]
Thanks for reaching out, @a8453770. Have you tried replacing your `google-services.json` after activating Crashlytics? This error usually happens when there's an inconsistency with your `google-services.json`.

**Comment by a8453770** [comment]
@argzdev 
![image](https://github.com/firebase/firebase-android-sdk/assets/19582195/2e544cce-18b2-4185-9095-c0a2a11fe825)
google sevice.json It was downloaded from the console

![image](https://github.com/firebase/firebase-android-sdk/assets/19582195/00c63e18-0d44-4eb6-a571-90e793f78c75)

**Comment by argzdev** [comment]
Yes, it looks like you've already added the correct `google-services.json`. I'm wondering if we're missing a few things on your crashlytics setup. Could you answer a few questions below:

1. Have you added crashlytics plugin in the **Project** level of your build.gradle?
```
plugins {
    alias(libs.plugins.androidApplication) apply false
    alias(libs.plugins.kotlinAndroid) apply false
    id("com.google.gms.google-services") version "4.4.0" apply false
    id("com.google.firebase.crashlytics") version "2.9.9" apply false
}
```
2. Have you also added this crashlytics plugin in your **module** level of your build.gradle?
```
plugins {
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.kotlinAndroid)
    id("com.google.gms.google-services")
    id("com.google.firebase.crashlytics")
}
```

**Comment by a8453770** [comment]
> Thanks for reaching out, @a8453770. Have you tried replacing your `google-services.json` after activating Crashlytics? This error usually happens when there's an inconsistency with your `google-services.json`.



> version

![image](https://github.com/firebase/firebase-android-sdk/assets/19582195/0a89a199-767c-48cb-8adf-6d9bd05b265d)



![image](https://github.com/firebase/firebase-android-sdk/assets/19582195/a1bb19b5-0a14-4240-9118-1669f2083384)

**Yes  I have added as per the documentation,**

**I kept reporting the problem mentioned above yesterday, and today I saw an error message being reported. It seems that the problem has been solved. Thank you for your help, I will close this problem.**
