### ISSUE TITLE
java.lang.SecurityException: addOnPermissionsChangeListener:  android.permission.OBSERVE_GRANT_REVOKE_PERMISSIONS

### ISSUE THREAD

**Issue by hanchanpo13** [firebase/firebase-android-sdk#5576]
android.os.Parcel.createExceptionOrNull Parcel.java:2443
android.os.Parcel.createException Parcel.java:2427
android.os.Parcel.readException Parcel.java:2410
android.os.Parcel.readException Parcel.java:2352
com.google.android.gms.common.internal.zzac.getService zzac.java:9
com.google.android.gms.common.internal.BaseGmsClient.getRemoteService BaseGmsClient.java:14
com.google.android.gms.common.internal.BaseGmsClient$LegacyClientCallbackAdapter.onReportServiceBinding BaseGmsClient.java:2
com.google.android.gms.common.internal.zzg.zzd zzg.java:1
com.google.android.gms.common.internal.zza.zza zza.java:4
com.google.android.gms.common.internal.zzc.zze zzc.java:3
com.google.android.gms.common.internal.zzb.handleMessage zzb.java:31
android.os.Handler.dispatchMessage Handler.java:117
android.os.Looper.loopOnce Looper.java:205
android.os.Looper.loop Looper.java:293
android.app.ActivityThread.loopProcess ActivityThread.java:9934
android.app.ActivityThread.main ActivityThread.java:9923
java.lang.reflect.Method.invoke Method.java
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run RuntimeInit.java:586
com.android.internal.os.ZygoteInit.main ZygoteInit.java:1240

`com.google.firebase:firebase-messaging:23.1.1
 com.google.firebase:firebase-analytics:21.2.0
`
It only happens on some phones, Android version 12.
![image](https://github.com/firebase/firebase-android-sdk/assets/8656222/609951ae-26ae-4761-ad7d-4a05edd91f5d)

**Comment by hanchanpo13** [comment]
It will be fine after I delete com.google.firebase:firebase-analytics:21.2.0

**Comment by argzdev** [comment]
Hi @hanchanpo13, thanks for reaching out. Any chance you're able to reproduce this behavior? If so, could you share code snippets or minimal reproducible example? Thanks!

**Comment by hanchanpo13** [comment]
com.google.firebase:firebase-analytics:21.5.0  still crashing

**Comment by argzdev** [comment]
Hi @hanchanpo13. As much as we'd like to help, the given stacktrace is not enough for us to investigate this. Could you provide steps to reproduce this behavior?

**Comment by hanchanpo13** [comment]
This can be reproduced on half of the phones. The sdk integration is strictly done according to the documentation. A crash occurred when we integrated firebase-analytic.

**Comment by hanchanpo13** [comment]
At present, the problem of online startup crashes is becoming more and more serious, urgently waiting to be solved[双手合十]

**Comment by ytheekshana** [comment]
I have the same issue. But I don't know if its relevant to Firebase. Its happening on Android 6

Fatal Exception: java.lang.SecurityException: addOnPermissionsChangeListener: Neither user 10065 nor current process has android.permission.OBSERVE_GRANT_REVOKE_PERMISSIONS.
       at android.os.Parcel.readException(Parcel.java:1620)
       at android.os.Parcel.readException(Parcel.java:1573)
       at com.google.android.gms.common.internal.zzad.getService(com.google.android.gms:play-services-basement@@18.2.0:9)
       at com.google.android.gms.common.internal.BaseGmsClient.getRemoteService(com.google.android.gms:play-services-basement@@18.2.0:14)
       at com.google.android.gms.common.internal.BaseGmsClient$LegacyClientCallbackAdapter.onReportServiceBinding(BaseGmsClient.java:2)
       at com.google.android.gms.common.internal.zzg.zzd(com.google.android.gms:play-services-basement@@18.2.0:1)
       at com.google.android.gms.common.internal.zza.zza(com.google.android.gms:play-services-basement@@18.2.0:1)
       at com.google.android.gms.common.internal.zzc.zze(zzc.java:3)
       at com.google.android.gms.common.internal.zzb.handleMessage(com.google.android.gms:play-services-basement@@18.2.0:31)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at com.google.android.gms.internal.ads.zzfps.dispatchMessage(com.google.android.gms:play-services-ads-lite@@22.5.0:6)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5466)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by hanchanpo13** [comment]
java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: SERVICE_NOT_AVAILABLE
	at com.google.firebase.messaging.FirebaseMessaging.blockingGetToken(:628)
	at com.google.firebase.messaging.FirebaseMessaging.lambda$getToken$4(:393)
	at com.google.firebase.messaging.FirebaseMessaging.lambda$getToken$4$FirebaseMessaging(Unknown Source:0)
	at com.google.firebase.messaging.-$$Lambda$FirebaseMessaging$m5Uvt0n8P9zrx-ecASLTQKzoABQ.run(Unknown Source:4)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.android.gms.common.util.concurrent.zza.run(:2)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: SERVICE_NOT_AVAILABLE
	at com.google.android.gms.tasks.Tasks.zza(:5)
	at com.google.android.gms.tasks.Tasks.await(:8)
	at com.google.firebase.messaging.FirebaseMessaging.blockingGetToken(:626)
	... 10 more
Caused by: java.io.IOException: SERVICE_NOT_AVAILABLE
	at com.google.firebase.messaging.GmsRpc.handleResponse(:309)
	at com.google.firebase.messaging.GmsRpc.lambda$extractResponseWhenComplete$0(:320)
	at com.google.firebase.messaging.GmsRpc.lambda$extractResponseWhenComplete$0$GmsRpc(Unknown Source:0)
	at com.google.firebase.messaging.-$$Lambda$GmsRpc$cZg7VRs3aHaJlHVdosXKlJfYwHY.then(Unknown Source:2)
	at com.google.android.gms.tasks.zzc.run(:3)
	at com.google.firebase.messaging.-$$Lambda$PNiE7SuEFxRjAZH7pJpZIFOFjWg.execute(Unknown Source:0)
	at com.google.android.gms.tasks.zzd.zzd(:1)
	at com.google.android.gms.tasks.zzr.zzb(:5)
	at com.google.android.gms.tasks.zzw.zzb(:3)
	at com.google.android.gms.tasks.zzc.run(:8)
	at com.google.android.gms.cloudmessaging.zzz.execute(Unknown Source:0)
	at com.google.android.gms.tasks.zzd.zzd(:1)
	at com.google.android.gms.tasks.zzr.zzb(:5)
	at com.google.android.gms.tasks.zzw.zzb(:3)
	at com.google.android.gms.tasks.TaskCompletionSource.setResult(:1)
	at com.google.android.gms.cloudmessaging.zzp.zzd(:3)
	at com.google.android.gms.cloudmessaging.zzr.zza(:2)
	at com.google.android.gms.cloudmessaging.zzf.handleMessage(:14)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:257)
	at android.app.ActivityThread.main(ActivityThread.java:8393)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1032)

**Comment by yin-haoran** [comment]
I also have the same issue, is there any progress now?
