### ISSUE TITLE
Initializing the SDK programmatically by using FirebaseOptions cause crash when call URLConnection.getInputStream()

### ISSUE THREAD

**Issue by yin-haoran** [firebase/firebase-android-sdk#5584]
Calling `URLConnection.getInputStream()` before `FirebaseApp.initializeApp()` will lead crash. Maybe due to the `Bytecode instrumented functions` `com.google.firebase.perf.network.FirebasePerfUrlConnection#openStream(java.net.URL)`.

stack info as follow:
```
java.lang.ExceptionInInitializerError
	at com.google.firebase.perf.config.RemoteConfigManager.getInstance(RemoteConfigManager.java:119)
	at com.google.firebase.perf.config.ConfigResolver.<init>(ConfigResolver.java:78)
	at com.google.firebase.perf.config.ConfigResolver.getInstance(ConfigResolver.java:86)
	at com.google.firebase.perf.application.AppStateMonitor.<init>(AppStateMonitor.java:98)
	at com.google.firebase.perf.application.AppStateMonitor.getInstance(AppStateMonitor.java:87)
	at com.google.firebase.perf.metrics.NetworkRequestMetricBuilder.<init>(NetworkRequestMetricBuilder.java:92)
	at com.google.firebase.perf.metrics.NetworkRequestMetricBuilder.builder(NetworkRequestMetricBuilder.java:84)
	at com.google.firebase.perf.network.FirebasePerfUrlConnection.openStream(FirebasePerfUrlConnection.java:63)
	at com.google.firebase.perf.network.FirebasePerfUrlConnection.openStream(FirebasePerfUrlConnection.java:47)
	at com.tony.firebasetest.MainActivity.onCreate(MainActivity.kt:38)
	at android.app.Activity.performCreate(Activity.java:8000)
	at android.app.Activity.performCreate(Activity.java:7984)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3600)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
```

I provide a [example](https://github.com/firebase/firebase-android-sdk/files/13522241/firebaseTest.zip) of this issue.

**Comment by yin-haoran** [comment]
Hi @argzdev, could you see this issue please.

**Comment by argzdev** [comment]
Hey @yin-haoran, thanks for bringing this up. I was also able to exhibit the same behavior. Let me reach out to our engineering team and see what we can do here.

**Comment by yin-haoran** [comment]
Hi @argzdev , is there any progress now?
