### ISSUE TITLE
Crashlytics causing Fatal crash on app start

### ISSUE THREAD

**Issue by damionx7** [firebase/firebase-android-sdk#5604]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Hedgehog | 2023.1.1
  * Firebase Component: Crashlytics
  * Component version: `com.google.firebase:firebase-crashlytics:18.6.0`

#### Steps to reproduce:

I upgrade my AGP to 8.2.0 and published a release build with proguard enabled. The app crashes on launch. It does not happen on debug builds with proguard disabled.

#### Relevant Code:

Stack trace for the crash

```
 8633-8633  art                        I  Verification error in java.lang.String ql.b.numberToString(java.lang.Number)
 8633-8633  art                        I  java.lang.String ql.b.numberToString(java.lang.Number) failed to verify: 'this' argument 'Uninitialized
                                          Reference: org.json.JSONException Allocation PC: 61' not instance of 'Reference: java.lang.RuntimeException'
 8633-8633  art                        I  
 8633-8633  art                        I  Verification error in void ql.b.testValidity(java.lang.Object)
 8633-8633  art                        I  void ql.b.testValidity(java.lang.Object) failed to verify: 'this' argument 'Uninitialized
                                          Reference: org.json.JSONException Allocation PC: 23' not instance of 'Reference: java.lang.RuntimeException'
 8633-8633  art                        I  
 8633-8633  art                        I  Verification error in java.io.Writer ql.b.writeValue(java.io.Writer, java.lang.Object, int, int)
 8633-8633  art                        I  java.io.Writer ql.b.writeValue(java.io.Writer, java.lang.Object, int, int) failed to verify: 'this' argument
                                          'Uninitialized Reference: org.json.JSONException Allocation PC: 43' not instance of
                                          'Reference: java.lang.RuntimeException'
 8633-8633  art                        I  
 8633-8633  art                        I  Verification error in java.lang.Object ql.b.get(java.lang.String)
 8633-8633  art                        I  java.lang.Object ql.b.get(java.lang.String) failed to verify: 'this' argument 'Uninitialized
                                          Reference: org.json.JSONException Allocation PC: 9' not instance of 'Reference: java.lang.RuntimeException'
 8633-8633  art                        I  
 8633-8633  art                        I  Verification error in boolean ql.b.getBoolean(java.lang.String)
 8633-8633  art                        I  boolean ql.b.getBoolean(java.lang.String) failed to verify: 'this' argument 'Uninitialized
                                          Reference: org.json.JSONException Allocation PC: 49' not instance of 'Reference: java.lang.RuntimeException'
 8633-8633  art                        I  
 8633-8633  art                        I  Verification error in double ql.b.getDouble(java.lang.String)
 8633-8633  art                        I  double ql.b.getDouble(java.lang.String) failed to verify: 'this' argument 'Uninitialized
                                          Reference: org.json.JSONException Allocation PC: 22' not instance of 'Reference: java.lang.RuntimeException'
 8633-8633  art                        I  
 8633-8633  art                        I  Verification error in int ql.b.getInt(java.lang.String)
 8633-8633  art                        I  int ql.b.getInt(java.lang.String) failed to verify: 'this' argument 'Uninitialized
                                          Reference: org.json.JSONException Allocation PC: 22' not instance of 'Reference: java.lang.RuntimeException'
 8633-8633  art                        I  
 8633-8633  art                        I  Verification error in ql.a ql.b.getJSONArray(java.lang.String)
 8633-8633  art                        I  ql.a ql.b.getJSONArray(java.lang.String) failed to verify: 'this' argument 'Uninitialized
                                          Reference: org.json.JSONException Allocation PC: 11' not instance of 'Reference: java.lang.RuntimeException'
 8633-8633  art                        I  
 8633-8633  art                        I  Verification error in ql.b ql.b.getJSONObject(java.lang.String)
 8633-8633  art                        I  ql.b ql.b.getJSONObject(java.lang.String) failed to verify: 'this' argument 'Uninitialized
                                          Reference: org.json.JSONException Allocation PC: 11' not instance of 'Reference: java.lang.RuntimeException'
 8633-8633  art                        I  
 8633-8633  art                        I  Verification error in long ql.b.getLong(java.lang.String)
 8633-8633  art                        I  long ql.b.getLong(java.lang.String) failed to verify: 'this' argument 'Uninitialized
                                          Reference: org.json.JSONException Allocation PC: 22' not instance of 'Reference: java.lang.RuntimeException'
 8633-8633  art                        I  
 8633-8633  art                        I  Verification error in java.lang.String ql.b.getString(java.lang.String)
 8633-8633  art                        I  java.lang.String ql.b.getString(java.lang.String) failed to verify: 'this' argument 'Uninitialized
                                          Reference: org.json.JSONException Allocation PC: 11' not instance of 'Reference: java.lang.RuntimeException'
 8633-8633  art                        I  
 8633-8633  art                        I  Verification error in ql.b ql.b.putOnce(java.lang.String, java.lang.Object)
 8633-8633  art                        I  ql.b ql.b.putOnce(java.lang.String, java.lang.Object) failed to verify: 'this' argument 'Uninitialized
                                          Reference: org.json.JSONException Allocation PC: 14' not instance of 'Reference: java.lang.RuntimeException'
 8633-8633  art                        I  
 8633-8633  art                        I  Verification error in java.io.Writer ql.b.write(java.io.Writer, int, int)
 8633-8633  art                        I  java.io.Writer ql.b.write(java.io.Writer, int, int) failed to verify: 'this' argument 'Uninitialized
                                          Reference: org.json.JSONException Allocation PC: 132' not instance of 'Reference: java.lang.RuntimeException'
 8633-8633  art                        I  
 8633-8633  art                        E  Verification failed on class ql.b in /data/app/org.eu.thedoc.zettelnotes-1/base.apk:classes3.dex
                                          because: Verifier rejected class ql.b due to bad method java.io.Writer ql.b.write(java.io.Writer, int, int)
 8633-8633  AndroidRuntime             D  Shutting down VM
 8633-8633  AndroidRuntime             E  FATAL EXCEPTION: main
                                          Process: org.eu.thedoc.zettelnotes, PID: 8633
                                          java.lang.VerifyError: Verifier rejected class ql.b due to bad method java.io.Writer
                                          ql.b.write(java.io.Writer, int, int) (declaration of 'ql.b' appears in
                                          /data/app/org.eu.thedoc.zettelnotes-1/base.apk:classes3.dex)
                                          	at
                                          com.google.firebase.crashlytics.internal.settings.CachedSettingsIo.readCachedSettings(CachedSettingsIo.java:32)
                                          	at
                                          com.google.firebase.crashlytics.internal.settings.SettingsController.getCachedSettingsData(SettingsController.java:12)
                                          	at
                                          com.google.firebase.crashlytics.internal.settings.SettingsController.loadSettingsData(SettingsController.java:8)
                                          	at
                                          com.google.firebase.crashlytics.internal.settings.SettingsController.loadSettingsData(SettingsController.java:1)
                                          	at com.google.firebase.crashlytics.FirebaseCrashlytics.init(FirebaseCrashlytics.java:274)
                                          	at com.google.firebase.crashlytics.CrashlyticsRegistrar.buildCrashlytics(CrashlyticsRegistrar.java:35)
                                          	at com.google.firebase.crashlytics.CrashlyticsRegistrar.a(CrashlyticsRegistrar.java:1)
                                          	at g4.a.create(R8$$SyntheticClass:17)
                                          	at com.google.firebase.tracing.ComponentMonitor.lambda$processRegistrar$0(ComponentMonitor.java:8)
                                          	at com.google.firebase.tracing.ComponentMonitor.a(ComponentMonitor.java:1)
                                          	at p4.a.create(R8$$SyntheticClass:12)
                                          	at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0(ComponentRuntime.java:10)
                                          	at com.google.firebase.components.ComponentRuntime.a(ComponentRuntime.java:1)
                                          	at g4.e.get(R8$$SyntheticClass:5)
                                          	at com.google.firebase.components.Lazy.get(Lazy.java:14)
                                          	at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents(ComponentRuntime.java:47)
                                          	at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(ComponentRuntime.java:23)
                                          	at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:67)
                                          	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:20)
                                          	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:9)
                                          	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:7)
                                          	at com.google.firebase.provider.FirebaseInitProvider.onCreate(FirebaseInitProvider.java:12)
                                          	at android.content.ContentProvider.attachInfo(ContentProvider.java:1686)
                                          	at android.content.ContentProvider.attachInfo(ContentProvider.java:1655)
                                          	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(FirebaseInitProvider.java:4)
                                          	at android.app.ActivityThread.installProvider(ActivityThread.java:4964)
                                          	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4559)
                                          	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4499)
                                          	at android.app.ActivityThread.access$1500(ActivityThread.java:144)
                                          	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
                                          	at android.os.Handler.dispatchMessage(Handler.java:102)
                                          	at android.os.Looper.loop(Looper.java:135)
                                          	at android.app.ActivityThread.main(ActivityThread.java:5221)
                                          	at java.lang.reflect.Method.invoke(Native Method)
                                          	at java.lang.reflect.Method.invoke(Method.java:372)
                                          	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                                          	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
 8633-8643  art                        I  Debugger is no longer active
```

**Comment by argzdev** [comment]
Hey @damionx7, thanks for reaching out. I tried creating a clean project with just the dependency for `com.google.firebase:firebase-crashlytics:18.6.0`:
```gradle
dependencies {
    ...
    implementation("com.google.firebase:firebase-crashlytics:18.6.0")
}
```

 and I enabled `isMinifyEnabled`:
```gradle
buildTypes {
        release {
            isMinifyEnabled = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }
```

But after installing the release APK, I'm not encountering the issue you've mentioned. That said, could you answer a few questions below:
1. Is this issue consistently reproducible?
2. Is this happening on a specific Android version?
3. Could you provide a [minimal reproducible example](https://meta.stackoverflow.com/questions/366988/what-does-mcve-mean)? Perhaps there's a difference with our configuration which is causing a different result

**Comment by damionx7** [comment]
I solved it by excluding org.json in proguard. Maybe firebase sdk proguard should exclude it by default.

https://github.com/firebase/firebase-android-sdk/issues/3688#issuecomment-1119494623

**Comment by argzdev** [comment]
Oh interesting, thank you for sharing your investigation and answer @damionx7!
