### ISSUE TITLE
Fatal Exception: java.lang.SecurityException addOnPermissionsChangeListener: Neither user 10144 nor current process has android.permission.OBSERVE_GRANT_REVOKE_PERMISSIONS

### ISSUE THREAD

**Issue by xixiwai111** [firebase/firebase-android-sdk#5606]
observed app crash on Crashlytices, can't reproduce locally
it happened thousand times on single user every one or two days
device is Redmi Note 7 android 10.0

Android Studio version: Android Studio Giraffe | 2022.3.1 Patch 1
Firebase Component: Firestore, Storage
Component version: 
```
com.google.android:gms:play-services-ads:22.0.0
com.google.android:gms:play-services-base:18.0.1
com.google.android:gms:play-services-basement:18.0.1
com.google.android:gms:play-services-measurement:21.1.1
com.google.android:gms:play-services-stats:17.0.2
com.google.android:gms:play-services-tasks:18.0.1
```

```
implementation platform('com.google.firebase:firebase-bom:30.4.1')
```

google services: 
```
classpath 'com.google.gms:google-services:4.3.5'
```

```
Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Ldgou;
       at ajvu.d(:com.google.android.gms@234212015@23.42.12 (040300-574052649):5)
       at agri.<clinit>(:com.google.android.gms@234212015@23.42.12 (040300-574052649):9)
       at com.google.android.gms.chimera.container.DynamiteLoaderImpl.<init>(:com.google.android.gms@234212015@23.42.12 (040300-574052649):54)
       at java.lang.Class.newInstance(Class.java)
       at com.google.android.gms.dynamite.DynamiteModule.zzg(DynamiteModule.java:27)
       at com.google.android.gms.dynamite.DynamiteModule.zza(DynamiteModule.java:6)
       at com.google.android.gms.dynamite.zze.zzb(zze.java)
       at com.google.android.gms.dynamite.zzi.selectModule(zzi.java:12)
       at com.google.android.gms.dynamite.DynamiteModule.d(DynamiteModule.java:50)
       at com.google.android.gms.internal.measurement.zzee.zzf(zzee.java:4)
       at com.google.android.gms.internal.measurement.zzcx.zza(zzcx.java:2)
       at com.google.android.gms.internal.measurement.zzdt.run(:12)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
```

**Comment by argzdev** [comment]
Hey @xixiwai111, thanks for reaching out. It looks like an issue with the GMS Core. Could you reach out to the [Google Play team](https://support.google.com/googleplay/gethelp)? They'll be able to assist you further with this issue. Thanks!
