### ISSUE TITLE
Fatal Exception: java.lang.SecurityException: Not allowed to bind to service Intent

### ISSUE THREAD

**Issue by billdizl** [firebase/firebase-android-sdk#5640]
I  don't know why ,but have this crash.
Wiko - FIH Foxconn  View4 Lite ,Android 10
  implementation platform('com.google.firebase:firebase-bom:32.7.0')
    implementation 'com.google.firebase:firebase-analytics'
    implementation 'com.google.firebase:firebase-crashlytics'
    implementation 'com.google.firebase:firebase-messaging'
    implementation 'com.google.firebase:firebase-core:21.1.1'
    implementation 'com.google.firebase:firebase-perf'
  classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.9'
//        classpath "com.novoda:bintray-release:$versions.bintrayPlugin"
        classpath 'com.google.firebase:perf-plugin:1.4.2'

Fatal Exception: java.lang.SecurityException: Not allowed to bind to service Intent { act=9360 cmp=com.xxx.xxx/com.google.firebase.sessions.SessionLifecycleService (has extras) }
       at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1741)
       at android.app.ContextImpl.bindService(ContextImpl.java:1651)
       at android.content.ContextWrapper.bindService(ContextWrapper.java:705)
       at com.google.firebase.sessions.SessionLifecycleServiceBinderImpl.bindToService(SessionLifecycleServiceBinder.kt:52)
       at com.google.firebase.sessions.SessionLifecycleClient.bindToService(SessionLifecycleClient.kt:104)
       at com.google.firebase.sessions.FirebaseSessions$1.invokeSuspend(FirebaseSessions.kt:53)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.firebase.concurrent.CustomThreadFactory.lambda$newThread$0$com-google-firebase-concurrent-CustomThreadFactory(CustomThreadFactory.java:47)
       at com.google.firebase.concurrent.CustomThreadFactory$$ExternalSyntheticLambda0.run(:4)
       at java.lang.Thread.run(Thread.java:919)

**Comment by lehcar09** [comment]
Hi @billdizl, thank you for reaching out. I tried reproducing the issue using our [quickstart app](https://github.com/firebase/quickstart-android/tree/master), however, I wasn't able to encounter any exception. Can you share an MCVE to help us investigate the issue?

**Comment by billdizl** [comment]
No  , I don't know  why

**Comment by lehcar09** [comment]
It would be helpful that you provide a minimal, reproducible example as this could be used as a baseline for troubleshooting so that we can identify what's causing the issue. If you're unable to provide one, can you try our [quickstart app](https://github.com/firebase/quickstart-android/tree/master) and see if you can reproduce the issue?

Aside from that, are you constantly experiencing this error? Could you provide the steps you've taken when you encountered the issue?

In addition to that, the latest release includes an update in firebase-sessions dependency.
Could you try using the latest SDK version ([32.7.1](https://firebase.google.com/support/release-notes/android#bom_v32-7-1)) and see if the issue persists? The latest release includes an update in firebase-sessions dependency.

**Comment by billdizl** [comment]
ok  i will try , but need long time to find it, because  we next version will be one month late
