### ISSUE TITLE
[firebasebase-auth] firebase-auth-api.zzxw: NullPointerException and ConcurrentModificationException

### ISSUE THREAD

**Issue by 9468lgy** [firebase/firebase-android-sdk#5643]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Flamingo | 2022.2.1 Patch 2
  * Firebase Component: Firebase Auth
  * Component version: 22.3.0

### [REQUIRED] Step 3: Describe the problem
We use firebase-bom:32.6.0, we've received a number of obfuscated crash reports in Firebase Crashlytics that we are unable to reproduce or diagnose.

#### Steps to reproduce:

Have not been able to reproduce. Crashes generally occur within a second of the session start

#### Relevant Code:

```
Fatal Exception: com.google.android.gms.internal.firebase-auth-api.zzxw: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.firebase.auth.internal.zzw.getProviderId()' on a null object reference
       at com.google.firebase.auth.internal.zzbx.zzc(com.google.firebase:firebase-auth@@22.3.0:132)
       at com.google.firebase.auth.internal.zzbx.zzb(com.google.firebase:firebase-auth@@22.3.0:145)
       at com.google.firebase.auth.FirebaseAuth.zza(com.google.firebase:firebase-auth@@22.3.0:461)
       at com.google.firebase.auth.FirebaseAuth.zza(com.google.firebase:firebase-auth@@22.3.0:416)
       at com.google.firebase.auth.zzy.zza(com.google.firebase:firebase-auth@@22.3.0:2)
       at com.google.android.gms.internal.firebase-auth-api.zzaap.zzb(com.google.firebase:firebase-auth@@22.3.0:8)
       at com.google.android.gms.internal.firebase-auth-api.zzacx.zza(com.google.firebase:firebase-auth@@22.3.0:19)
       at com.google.android.gms.internal.firebase-auth-api.zzacz.zza(com.google.firebase:firebase-auth@@22.3.0:110)
       at com.google.android.gms.internal.firebase-auth-api.zzacd.zza(com.google.firebase:firebase-auth@@22.3.0:96)
       at com.google.android.gms.internal.firebase-auth-api.zzym.zza(com.google.firebase:firebase-auth@@22.3.0:6)
       at com.google.android.gms.internal.firebase-auth-api.zzadn.zza(com.google.firebase:firebase-auth@@22.3.0:20)
       at com.google.android.gms.internal.firebase-auth-api.zzadn.zza(com.google.firebase:firebase-auth@@22.3.0:64)
       at com.google.android.gms.internal.firebase-auth-api.zzacu.zza(com.google.firebase:firebase-auth@@22.3.0:48)
       at com.google.android.gms.internal.firebase-auth-api.zzyj.zzb(com.google.firebase:firebase-auth@@22.3.0:110)
       at com.google.android.gms.internal.firebase-auth-api.zzacg.zzb(com.google.firebase:firebase-auth@@22.3.0:91)
       at com.google.android.gms.internal.firebase-auth-api.zzaap.zza(com.google.firebase:firebase-auth@@22.3.0:13)
       at com.google.android.gms.internal.firebase-auth-api.zzadg.run(com.google.firebase:firebase-auth@@22.3.0:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.firebase.concurrent.CustomThreadFactory.lambda$newThread$0(CustomThreadFactory.java:47)
       at java.lang.Thread.run(Thread.java:923)
```
and
```
Fatal Exception: com.google.android.gms.internal.firebase-auth-api.zzxw: java.util.ConcurrentModificationException
       at com.google.firebase.auth.internal.zzbx.zzc(com.google.firebase:firebase-auth@@22.3.0:132)
       at com.google.firebase.auth.internal.zzbx.zzb(com.google.firebase:firebase-auth@@22.3.0:145)
       at com.google.firebase.auth.FirebaseAuth.zza(com.google.firebase:firebase-auth@@22.3.0:461)
       at com.google.firebase.auth.FirebaseAuth.zza(com.google.firebase:firebase-auth@@22.3.0:416)
       at com.google.firebase.auth.zzy.zza(com.google.firebase:firebase-auth@@22.3.0:2)
       at com.google.android.gms.internal.firebase-auth-api.zzaap.zzb(com.google.firebase:firebase-auth@@22.3.0:8)
       at com.google.android.gms.internal.firebase-auth-api.zzacx.zza(com.google.firebase:firebase-auth@@22.3.0:19)
       at com.google.android.gms.internal.firebase-auth-api.zzacz.zza(com.google.firebase:firebase-auth@@22.3.0:110)
       at com.google.android.gms.internal.firebase-auth-api.zzacd.zza(com.google.firebase:firebase-auth@@22.3.0:96)
       at com.google.android.gms.internal.firebase-auth-api.zzym.zza(com.google.firebase:firebase-auth@@22.3.0:6)
       at com.google.android.gms.internal.firebase-auth-api.zzadn.zza(com.google.firebase:firebase-auth@@22.3.0:20)
       at com.google.android.gms.internal.firebase-auth-api.zzadn.zza(com.google.firebase:firebase-auth@@22.3.0:64)
       at com.google.android.gms.internal.firebase-auth-api.zzacu.zza(com.google.firebase:firebase-auth@@22.3.0:48)
       at com.google.android.gms.internal.firebase-auth-api.zzyj.zzb(com.google.firebase:firebase-auth@@22.3.0:110)
       at com.google.android.gms.internal.firebase-auth-api.zzacg.zzb(com.google.firebase:firebase-auth@@22.3.0:91)
       at com.google.android.gms.internal.firebase-auth-api.zzaap.zza(com.google.firebase:firebase-auth@@22.3.0:13)
       at com.google.android.gms.internal.firebase-auth-api.zzadg.run(com.google.firebase:firebase-auth@@22.3.0:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at com.google.firebase.concurrent.CustomThreadFactory.lambda$newThread$0(CustomThreadFactory.java:47)
       at java.lang.Thread.run(Thread.java:1012)
```
```
Caused by java.util.ConcurrentModificationException:
       at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1029)
       at java.util.ArrayList$Itr.next(ArrayList.java:982)
       at com.google.firebase.auth.internal.zzbx.zzc(com.google.firebase:firebase-auth@@22.3.0:110)
       at com.google.firebase.auth.internal.zzbx.zzb(com.google.firebase:firebase-auth@@22.3.0:145)
       at com.google.firebase.auth.FirebaseAuth.zza(com.google.firebase:firebase-auth@@22.3.0:461)
       at com.google.firebase.auth.FirebaseAuth.zza(com.google.firebase:firebase-auth@@22.3.0:416)
       at com.google.firebase.auth.zzy.zza(com.google.firebase:firebase-auth@@22.3.0:2)
       at com.google.android.gms.internal.firebase-auth-api.zzaap.zzb(com.google.firebase:firebase-auth@@22.3.0:8)
       at com.google.android.gms.internal.firebase-auth-api.zzacx.zza(com.google.firebase:firebase-auth@@22.3.0:19)
       at com.google.android.gms.internal.firebase-auth-api.zzacz.zza(com.google.firebase:firebase-auth@@22.3.0:110)
       at com.google.android.gms.internal.firebase-auth-api.zzacd.zza(com.google.firebase:firebase-auth@@22.3.0:96)
       at com.google.android.gms.internal.firebase-auth-api.zzym.zza(com.google.firebase:firebase-auth@@22.3.0:6)
       at com.google.android.gms.internal.firebase-auth-api.zzadn.zza(com.google.firebase:firebase-auth@@22.3.0:20)
       at com.google.android.gms.internal.firebase-auth-api.zzadn.zza(com.google.firebase:firebase-auth@@22.3.0:64)
       at com.google.android.gms.internal.firebase-auth-api.zzacu.zza(com.google.firebase:firebase-auth@@22.3.0:48)
       at com.google.android.gms.internal.firebase-auth-api.zzyj.zzb(com.google.firebase:firebase-auth@@22.3.0:110)
       at com.google.android.gms.internal.firebase-auth-api.zzacg.zzb(com.google.firebase:firebase-auth@@22.3.0:91)
       at com.google.android.gms.internal.firebase-auth-api.zzaap.zza(com.google.firebase:firebase-auth@@22.3.0:13)
       at com.google.android.gms.internal.firebase-auth-api.zzadg.run(com.google.firebase:firebase-auth@@22.3.0:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at com.google.firebase.concurrent.CustomThreadFactory.lambda$newThread$0(CustomThreadFactory.java:47)
       at java.lang.Thread.run(Thread.java:1012)
```

**Comment by lehcar09** [comment]
Hi @9468lgy, thanks for reporting. Does this issue rarely occur? I've tried replicating this issue but wasn't able to as well. Could you share a code snippet or MCVE to help us investigate the issue?

**Comment by 9468lgy** [comment]
It's been two weeks since our app was released, and 7 users are experiencing this problem.

Our auth usage process relies on https://github.com/firebase/FirebaseUI-Android/tree/master/auth to build, and some UI extensions are added, but the specific usage logic is no different from the SDK

According to the reported user usage data, users crash within 1-3 seconds after entering the application and do not enter the login page where the code is used.
```
AuthMethodPickerLayout customLayout = new AuthMethodPickerLayout
                .Builder(R.layout.activity_fauth_login_custom)
                .setGoogleButtonId(R.id.btn_google)
                .setEmailButtonId(R.id.btn_email)
                .setFacebookButtonId(R.id.btn_facebook)
                .setTosAndPrivacyPolicyId(R.id.main_tos_and_pp)
                .setLineButtonId(R.id.btn_line)
                .build();
        
startActivityForResult(
                AuthUI.getInstance()
                        .createSignInIntentBuilder()
                        .setAvailableProviders(getAvailableProviders())
                        .setLogo(R.mipmap.ic_launcher)
                        .setLastMail(UsersManager.getInstance().getLastEmail())
                        .setIdpIndex(UsersManager.getInstance().getIdpIndexInt())
                        .setIsSmartLockEnabled(false)
                        .setTosAndPrivacyPolicyUrls(getSelectedTosUrl(),
                                getSelectedPrivacyPolicyUrl())
                        .setAuthMethodPickerLayout(customLayout)
                        .setTheme(R.style.immersive_theme)
                        .build(),
                RC_SIGN_IN);
```
I tracked the error message and found that the location where NullPointerException occurred may be the three locations circled in red in the screenshot.

![614469696](https://github.com/firebase/firebase-android-sdk/assets/9604541/2ef78b1e-455e-467a-83ff-c66d6d67e346)

The version of firebase-auth:22.1.2 we used in the previous version of our application also had similar problems. It’s just that the number is very small. In the past 30 days since the old version was released, only 2 users had this problem.
```
Fatal Exception: com.google.android.gms.internal.firebase-auth-api.zzzr: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.firebase.auth.internal.zzt.getProviderId()' on a null object reference
       at com.google.firebase.auth.internal.zzbt.zzd(com.google.firebase:firebase-auth@@22.1.2:48)
       at com.google.firebase.auth.FirebaseAuth.zzT(com.google.firebase:firebase-auth@@22.1.2:14)
       at com.google.firebase.auth.zzx.zza(com.google.firebase:firebase-auth@@22.1.2:1)
       at com.google.android.gms.internal.firebase-auth-api.zzacj.zzb(com.google.firebase:firebase-auth@@22.1.2:3)
       at com.google.android.gms.internal.firebase-auth-api.zzaez.zzj(com.google.firebase:firebase-auth@@22.1.2:1)
       at com.google.android.gms.internal.firebase-auth-api.zzaew.zzq(com.google.firebase:firebase-auth@@22.1.2:3)
       at com.google.android.gms.internal.firebase-auth-api.zzadx.zzq(com.google.firebase:firebase-auth@@22.1.2:1)
       at com.google.android.gms.internal.firebase-auth-api.zzaaq.zzb(com.google.firebase:firebase-auth@@22.1.2:2)
       at com.google.android.gms.internal.firebase-auth-api.zzafh.zzc(com.google.firebase:firebase-auth@@22.1.2:12)
       at com.google.android.gms.internal.firebase-auth-api.zzafh.zzb(com.google.firebase:firebase-auth@@22.1.2:14)
       at com.google.android.gms.internal.firebase-auth-api.zzaem.zzf(com.google.firebase:firebase-auth@@22.1.2:4)
       at com.google.android.gms.internal.firebase-auth-api.zzabz.zzp(com.google.firebase:firebase-auth@@22.1.2:4)
       at com.google.android.gms.internal.firebase-auth-api.zzady.zzj(com.google.firebase:firebase-auth@@22.1.2:3)
       at com.google.android.gms.internal.firebase-auth-api.zzacj.zzc(com.google.firebase:firebase-auth@@22.1.2:1)
       at com.google.android.gms.internal.firebase-auth-api.zzafa.run(com.google.firebase:firebase-auth@@22.1.2:1)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.firebase.concurrent.CustomThreadFactory.lambda$newThread$0(CustomThreadFactory.java:47)
       at java.lang.Thread.run(Thread.java:923)
```

**Comment by lehcar09** [comment]
Hi @9468lgy, to confirm, does the issue occur when there's a user that’s already logged in? If not, could you try adding the providers one at a time to check if there's a specific provider that’s returning a null value?

I tried the code snippet below but I did not encounter the issue.

```
class MainActivity : AppCompatActivity() {

    private lateinit var auth: FirebaseAuth
    private lateinit var txtUser: TextView

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        txtUser = findViewById(R.id.txt_user)

        auth = Firebase.auth
    }

    override fun onStart() {
        super.onStart()
        // Check if user is signed in (non-null) and update UI accordingly.
        val currentUser = auth.currentUser
        if (currentUser == null) {
            createSignInIntent()
        } else {
            currentUser.let {
                var providerId = ""
                var uid = ""

                for (profile in it.providerData) {
                    // Id of the provider (ex: google.com)
                    providerId = profile.providerId

                    // UID specific to the provider
                    uid = profile.uid
                }
                txtUser.text = uid
                Log.d(TAG,"User $uid via $providerId")
            }
        }
    }

    // [START auth_fui_create_launcher]
    // See: https://developer.android.com/training/basics/intents/result
    private val signInLauncher = registerForActivityResult(
        FirebaseAuthUIActivityResultContract(),
    ) { res ->
        this.onSignInResult(res)
    }
    // [END auth_fui_create_launcher]

    private fun createSignInIntent() {
        // [START auth_fui_create_intent]
        // Choose authentication providers
        val providers = arrayListOf(
            AuthUI.IdpConfig.EmailBuilder().build(),
            AuthUI.IdpConfig.GoogleBuilder().build(),
        )
        // [END auth_fui_create_intent]

        val customLayout = AuthMethodPickerLayout.Builder(R.layout.custom_layout)
            .setGoogleButtonId(R.id.signInButton)
            .setEmailButtonId(R.id.customButton)
            .build()

        val signInIntent: Intent = AuthUI.getInstance().createSignInIntentBuilder()
            .setAvailableProviders(providers)
            .setLogo(R.mipmap.ic_launcher)
//            .setLastMail(UsersManager.getInstance().getLastEmail())
//            .setIdpIndex(UsersManager.getInstance().getIdpIndexInt())
            .setIsSmartLockEnabled(false)
//            .setTosAndPrivacyPolicyUrls(getSelectedTosUrl(),
//                getSelectedPrivacyPolicyUrl())
            .setAuthMethodPickerLayout(customLayout)
            .build()
        signInLauncher.launch(signInIntent)
    }

    // [START auth_fui_result]
    private fun onSignInResult(result: FirebaseAuthUIAuthenticationResult) {
        val response = result.idpResponse
        if (result.resultCode == RESULT_OK) {
            // Successfully signed in
            val user = FirebaseAuth.getInstance().currentUser
            Log.d(TAG, "User: $user")
        } else {
            // Sign in failed. If response is null the user canceled the
            // sign-in flow using the back button. Otherwise check
            // response.getError().getErrorCode() and handle the error.
            // ...
            Log.d(TAG, "Error: ${response?.error?.errorCode}")
        }
    }

    companion object {
        private const val TAG = "Issue5643"
    }
}
```

**Comment by 9468lgy** [comment]
Hi, @lehcar09 
Sorry, I didn't describe it clearly before. I checked the user login status and these crashes all happened to logged in users.
When these logged-in users use the app again, it will crash within 1-3 seconds after entering the app.

**Comment by lehcar09** [comment]
Hi @9468lgy, thank you for your clarification. I've been trying to reproduce this issue but haven't been successful. Any chance you could provide detailed steps to reproduce the issue or an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) where the issue is reproducible to help investigate the issue?

**Comment by 9468lgy** [comment]
Hi @lehcar09，thank you for your reply.
I have tried this but the problem does not recur.
According to the current crash information analysis, users who experience this crash will only appear once and will not happen again.
Currently, 12 users have this problem, which is within our tolerance range. If you can't find the reason, I'll close the question first. I will try to upgrade the sdk to the next version and see if the problem still occurs.
