### ISSUE TITLE
Firebase Crashlytics: "Cannot send reports. Timed out while fetching settings."

### ISSUE THREAD

**Issue by Leonardo-Fischer** [firebase/firebase-android-sdk#5645]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Giraffe 2022.3.1 Patch 1
  * Firebase Component: Crashlytics, Performance
  * Component version: 2.8.0, 1.4.0
  * Device Android API level: Android 7.1

#### Steps to reproduce:

I performed some crash tests with my `example.com` application and I was able to see the crash reports on Firebase Crashlytics Console. However, after uninstalling and installing the application several times I started to see the following log and then the crashlytics reports stopped to be sent:

```
---------------------------- PROCESS STARTED (3111) for package example.com ----------------------------
2024-01-16 16:52:50.001  3111-3111  art                     example.com          I  Starting a blocking GC HeapTrim
2024-01-16 16:52:50.850  3111-3111  FirebaseApp             example.com          I  Device unlocked: initializing all Firebase APIs for app [DEFAULT]
2024-01-16 16:52:50.906  3111-3111  FirebaseCrashlytics     example.com          I  Initializing Firebase Crashlytics 18.2.12 for example.com
2024-01-16 16:52:50.998  3111-3163  ActivityThread          example.com          E  Failed to find provider info for com.google.android.gms.chimera
2024-01-16 16:52:50.998  3111-3163  DynamiteModule          example.com          W  Failed to retrieve remote module version.
2024-01-16 16:52:50.999  3111-3163  DynamiteModule          example.com          E  Failed to load IDynamiteLoader from GmsCore: Application package com.google.android.gms not found
2024-01-16 16:52:51.000  3111-3163  DynamiteModule          example.com          I  Considering local module com.google.android.gms.measurement.dynamite:78 and remote module com.google.android.gms.measurement.dynamite:0
2024-01-16 16:52:51.000  3111-3163  DynamiteModule          example.com          I  Selected local version of com.google.android.gms.measurement.dynamite
2024-01-16 16:52:51.005  3111-3163  DynamiteModule          example.com          E  Failed to load IDynamiteLoader from GmsCore: Application package com.google.android.gms not found
2024-01-16 16:52:51.089  3111-3172  NetworkSecurityConfig   example.com          D  No Network Security Config specified, using platform default
2024-01-16 16:52:51.174  3111-3169  libc-netbsd             example.com          D  getaddrinfo: firebase-settings.crashlytics.com get result from proxy gai_error = 0
2024-01-16 16:52:51.178  3111-3169  <no-tag>                example.com          D  [Posix_connect Debug]Process example.com :443 
2024-01-16 16:52:51.294  3111-3166  FA                      example.com          I  App measurement initialized, version: 68000
2024-01-16 16:52:51.294  3111-3166  FA                      example.com          I  To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
2024-01-16 16:52:51.295  3111-3166  FA                      example.com          I  To enable faster debug mode event logging run:
                                                                                                      adb shell setprop debug.firebase.analytics.app example.com
2024-01-16 16:52:51.375  3111-3111  FirebaseInitProvider    example.com          I  FirebaseApp initialization successful
2024-01-16 16:52:51.405  3111-3172  libc-netbsd             example.com          D  getaddrinfo: firebaseinstallations.googleapis.com get result from proxy gai_error = 0
2024-01-16 16:52:51.409  3111-3172  <no-tag>                example.com          D  [Posix_connect Debug]Process example.com :443 
2024-01-16 16:52:51.420  3111-3111  WM-WrkMgrInitializer    example.com          D  Initializing WorkManager with default configuration.
2024-01-16 16:52:51.446  3111-3166  OpenSSLLib              example.com          D  OpensslErr:Module:12(175:); file:external/boringssl/src/crypto/asn1/asn1_lib.c ;Line:175;Function:ASN1_get_object
2024-01-16 16:52:51.594  3111-3185  SQLiteConnection        example.com          W  Could not change the database journal as DB was busy. Proceeding...
2024-01-16 16:52:51.612  3111-3166  GooglePlayServicesUtil  example.com          W  example.com requires the Google Play Store, but it is missing.
2024-01-16 16:52:51.614  3111-3166  FA                      example.com          W  Service invalid
2024-01-16 16:52:52.147  3111-3111  AndroidRuntime          example.com          D  Shutting down VM
2024-01-16 16:52:56.149  3111-3111  FirebaseCrashlytics     example.com          E  Cannot send reports. Timed out while fetching settings.
2024-01-16 16:53:01.474  3111-3169  System.out              example.com          I  [socket][2:-1] exception
2024-01-16 16:53:01.475  3111-3169  System.out              example.com          I  Close in OkHttp
2024-01-16 16:53:01.477  3111-3169  FirebaseCrashlytics     example.com          E  Settings request failed.
                                                                                                    java.net.SocketTimeoutException: connect timed out
                                                                                                        at java.net.PlainSocketImpl.socketConnect(Native Method)
                                                                                                        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:341)
                                                                                                        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
                                                                                                        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
                                                                                                        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
                                                                                                        at java.net.Socket.connect(Socket.java:650)
                                                                                                        at com.android.okhttp.internal.Platform.connectSocket(Platform.java:113)
                                                                                                        at com.android.okhttp.Connection.connectSocket(Connection.java:221)
                                                                                                        at com.android.okhttp.Connection.connect(Connection.java:197)
                                                                                                        at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:392)
                                                                                                        at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
                                                                                                        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:373)
                                                                                                        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:273)
                                                                                                        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:478)
                                                                                                        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:126)
                                                                                                        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
                                                                                                        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java)
                                                                                                        at com.google.firebase.crashlytics.internal.network.HttpGetRequest.execute(HttpGetRequest.java:76)
                                                                                                        at com.google.firebase.crashlytics.internal.settings.DefaultSettingsSpiCall.invoke(DefaultSettingsSpiCall.java:112)
                                                                                                        at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:200)
                                                                                                        at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:193)
                                                                                                        at com.google.android.gms.tasks.zzo.run(com.google.android.gms:play-services-tasks@@18.0.1:1)
                                                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                                        at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:64)
                                                                                                        at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:27)
                                                                                                        at java.lang.Thread.run(Thread.java:761)
2024-01-16 16:53:01.481  3111-3164  FirebaseCrashlytics     example.com          W  Skipping session finalization because a crash has already occurred.
2024-01-16 16:53:01.481  3111-3164  FirebaseCrashlytics     example.com          W  Previous sessions could not be finalized.
2024-01-16 16:53:01.671  3111-3172  System.out              example.com          I  [socket][2:-1] exception
2024-01-16 16:53:01.674  3111-3172  <no-tag>                example.com          D  [Posix_connect Debug]Process example.com :443 
2024-01-16 16:53:05.123  3111-3118  art                     example.com          I  Debugger is no longer active
2024-01-16 16:53:05.124  3111-3118  art                     example.com          I  Starting a blocking GC Instrumentation
2024-01-16 16:53:11.684  3111-3172  System.out              example.com          I  [socket][3:-1] exception
2024-01-16 16:53:11.688  3111-3172  <no-tag>                example.com          D  [Posix_connect Debug]Process example.com :443 
2024-01-16 16:53:21.694  3111-3172  System.out              example.com          I  [socket][4:-1] exception
2024-01-16 16:53:21.696  3111-3172  <no-tag>                example.com          D  [Posix_connect Debug]Process example.com :443 
2024-01-16 16:53:31.704  3111-3172  System.out              example.com          I  [socket][5:-1] exception
2024-01-16 16:53:31.707  3111-3172  <no-tag>                example.com          D  [Posix_connect Debug]Process example.com :443 
2024-01-16 16:53:41.714  3111-3172  System.out              example.com          I  [socket][6:-1] exception
2024-01-16 16:53:41.718  3111-3172  <no-tag>                example.com          D  [Posix_connect Debug]Process example.com :443 
```

#### Relevant Code:

I've checked the project `google-services.json` file and it is the same as it is on Firebase console.

I've used the buildscript sintaxe to configure the Firebase plugins as recommended [here](https://firebase.google.com/docs/android/troubleshooting-faq?hl=pt&authuser=0&_gl=1*1w6xafa*_ga*NzMxMjY5NzUyLjE2NDY3NzAwNjc.*_ga_CW55HF8NVT*MTcwNTQ0MzA2NC40MS4xLjE3MDU0NDMxOTYuNjAuMC4w#add-plugins-using-buildscript-syntax)

My `<project>/build.gradle`:
```
buildscript {

    repositories {
        mavenCentral()
        google()
    }

    dependencies {
        classpath "com.android.tools.build:gradle:4.1.3"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.0"
        classpath "com.google.gms:google-services:4.3.10"
        classpath "com.google.firebase:firebase-crashlytics-gradle:2.8.0"
        // Performance Monitoring plugin
        classpath "com.google.firebase:perf-plugin:1.4.0"
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        mavenCentral()
    }
}
```

My `<project>/<app-module>/build.gradle`:
```
plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'com.google.gms.google-services'
    id 'com.google.firebase.crashlytics'
    id 'com.google.firebase.firebase-perf'
}
```

**Comment by Leonardo-Fischer** [comment]
I found what the problem was.. I was using a private APN configuration on my Android device, so the application was not able to reach the Firebase endpoint successfully... I'm closing the issue.
