### ISSUE TITLE
SessionLifecycleServiceBinderImpl.bindToService

### ISSUE THREAD

**Issue by billdizl** [firebase/firebase-android-sdk#5652]
SessionLifecycleServiceBinderImpl.bindToService, I  don't know why have this crash,because  test phone not have this crash,but online phone have this crash

设备
品牌：Wiko - FIH Foxconn
型号：View4 Lite
屏幕方向：纵向
可用 RAM： 749.47 MB
可用磁盘空间： 2.95 GB
操作系统
版本：Android 10
屏幕方向：纵向
是否已取得 root 权限：否

Fatal Exception: java.lang.SecurityException: Not allowed to bind to service Intent { act=31534 cmp=com.xxx.xxxx/com.google.firebase.sessions.SessionLifecycleService (has extras) }
       at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1741)
       at android.app.ContextImpl.bindService(ContextImpl.java:1651)
       at android.content.ContextWrapper.bindService(ContextWrapper.java:705)
       at com.google.firebase.sessions.SessionLifecycleServiceBinderImpl.bindToService(SessionLifecycleServiceBinder.kt:52)
       at com.google.firebase.sessions.SessionLifecycleClient.bindToService(SessionLifecycleClient.kt:104)
       at com.google.firebase.sessions.FirebaseSessions$1.invokeSuspend(FirebaseSessions.kt:53)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.firebase.concurrent.CustomThreadFactory.lambda$newThread$0$com-google-firebase-concurrent-CustomThreadFactory(CustomThreadFactory.java:47)
       at com.google.firebase.concurrent.CustomThreadFactory$$ExternalSyntheticLambda0.run(:4)
       at java.lang.Thread.run(Thread.java:919)

**Comment by lehcar09** [comment]
Hi @billdizl, thank you for reaching. I see that you have filed a similar issue in [#5640](https://github.com/firebase/firebase-android-sdk/issues/5640). To avoid duplicate efforts and better tracking of the issue, I will be closing this ticket. Moving forward, you can reply back to issue [#5640](https://github.com/firebase/firebase-android-sdk/issues/5640) for providing the details and/ or follow ups. I hope for your understanding.
