### ISSUE TITLE
ClassCircularityError: Class imj.fdv.fjo extends itself 

### ISSUE THREAD

**Issue by nithinmurali** [firebase/firebase-android-sdk#5664]
### [REQUIRED] Step 2: Describe your environment

  * Firebase Component: bom:32.7.0

### [REQUIRED] Step 3: Describe the problem
We are getting multiple crash reports in Crashlytics (25 crash events affecting 9 users in the last 30 days). We have been not able to reproduce it. Devices are Samsung, oppo, Xiaomi and Android versions are Android 14, 12, and 9.

```
Fatal Exception: java.lang.ClassCircularityError: Class imj.fdv.fjo extends itself (declaration of 'imj.fdv.fjo' appears in base.apk!classes3.dex)
       at kotlinx.coroutines.sync.SemaphoreImpl.<init>(Semaphore.kt:139)
       at kotlinx.coroutines.sync.MutexImpl.<init>(Mutex.kt)
       at kotlinx.coroutines.sync.MutexKt.Mutex(Mutex.kt:109)
       at com.google.firebase.sessions.api.FirebaseSessionsDependencies.addDependency(FirebaseSessionsDependencies.kt:61)
       at com.google.firebase.crashlytics.CrashlyticsRegistrar.<clinit>(CrashlyticsRegistrar.java:39)
       at java.lang.Class.classForName(Class.java)
       at java.lang.Class.forName(Class.java:453)
       at java.lang.Class.forName(Class.java:378)
       at com.google.firebase.components.ComponentDiscovery.instantiate(ComponentDiscovery.java:6)
       at com.google.firebase.components.ComponentDiscovery.lambda$discoverLazy$0(ComponentDiscovery.java)
       at com.google.firebase.components.ComponentDiscovery$$ExternalSyntheticLambda0.get(R8$$SyntheticClass:16)
       at com.google.firebase.components.ComponentRuntime.discoverComponents(ComponentRuntime.java:155)
       at com.google.firebase.components.ComponentRuntime.<init>(ComponentRuntime.java:113)
       at com.google.firebase.components.ComponentRuntime.<init>(ComponentRuntime.java)
       at com.google.firebase.components.ComponentRuntime$Builder.build(ComponentRuntime.java:407)
       at com.google.firebase.FirebaseApp.<init>(FirebaseApp.java:436)
       at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:58)
       at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:237)
       at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:30)
       at com.google.firebase.provider.FirebaseInitProvider.onCreate(FirebaseInitProvider.java:69)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:1940)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:1915)
       at com.google.firebase.provider.FirebaseInitProvider.attachInfo(FirebaseInitProvider.java:60)
       at android.app.ActivityThread.installProvider(ActivityThread.java:6770)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:6317)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6232)
       at android.app.ActivityThread.access$1200(ActivityThread.java:237)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1792)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7078)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

```

**Comment by lehcar09** [comment]
Hi @nithinmurali, thank you for reaching out. I've tried replicating this issue but wasn't able to as well.

Could you try using the latest version of [Firebase BoM (32.7.1)](https://firebase.google.com/support/release-notes/android#bom_v32-7-1) and see if that helps? Based on [release notes](https://firebase.google.com/support/release-notes/android#crashlytics_v18-6-1), there is an updated version of firebase-sessions dependency for Crashlytics. If you fear that this might introduce more complications, then perhaps you could try releasing this to a small portion of your users first and see if they can still encounter this issue.

**Comment by nithinmurali** [comment]
Hi @lehcar09 , Alright I will try updating to the latest version. I will update here with the results.
