### ISSUE TITLE
🐛[cloud_firestore] RequireNonNull when get documentSnapshot to be reported in crashlytics.

### ISSUE THREAD

**Issue by rikkei-namhs** [firebase/firebase-android-sdk#5683]
I am using firestore in my app, along with crashlytics.
I get error in crashlytics as follows.
`Fatal Exception: java.lang. :
       at java.util.Objects.requireNonNull(Objects.java:203)
       at com.google.protobuf.Internal.checkNotNull(Internal.java:64)
       at com.google.protobuf.MapFieldLite.checkForNullKeysAndValues(MapFieldLite.java:121)
       at com.google.protobuf.MapFieldLite.putAll(MapFieldLite.java:108)
       at com.google.protobuf.MapFieldLite.mergeFrom(MapFieldLite.java:76)
       at com.google.protobuf.MapFieldSchemaLite.mergeFromLite(MapFieldSchemaLite.java:82)
       at com.google.protobuf.MapFieldSchemaLite.mergeFrom(MapFieldSchemaLite.java:71)
       at com.google.protobuf.SchemaUtil.mergeMap(SchemaUtil.java:880)
       at com.google.protobuf.MessageSchema.mergeSingleField(MessageSchema.java:1337)
       at com.google.protobuf.MessageSchema.mergeFrom(MessageSchema.java:1184)
       at com.google.protobuf.GeneratedMessageLite$Builder.mergeFromInstance(GeneratedMessageLite.java:425)
       at com.google.protobuf.GeneratedMessageLite$Builder.mergeFrom(GeneratedMessageLite.java:420)
       at com.google.protobuf.GeneratedMessageLite.toBuilder(GeneratedMessageLite.java:201)
       at com.google.firebase.firestore.model.ObjectValue.applyOverlay(ObjectValue.java:220)
       at com.google.firebase.firestore.model.ObjectValue.buildProto(ObjectValue.java:128)
       at com.google.firebase.firestore.model.ObjectValue.get(ObjectValue.java:102)
       at com.google.firebase.firestore.model.MutableDocument.getField(MutableDocument.java:208)
       at com.google.firebase.firestore.DocumentSnapshot.getInternal(DocumentSnapshot.java:509)
       at com.google.firebase.firestore.DocumentSnapshot.get(DocumentSnapshot.java:259)
       at com.google.firebase.firestore.DocumentSnapshot.get(DocumentSnapshot.java:217)`

My logs for this crash show no adverse behaviour at the application level.

  * Android Studio version :Android Studio Hedgehog | 2023.1.1
  * Firebase Component: Firestore 24.1.2

**Comment by tom-andersen** [comment]
I will inspect the code, and follow up when I better understand how this can happen.

**Comment by rikkei-namhs** [comment]
Thanks for your help! @tom-andersen

**Comment by tom-andersen** [comment]
Reading through the code, I also found a potential race condition.

Can you provide any additional information on circumstances, or even a repro?

**Comment by rikkei-namhs** [comment]
> Reading through the code, I also found a potential race condition.
> 
> Can you provide any additional information on circumstances, or even a repro?

Sorry for the late. That's all the information I can public because this is a private source code
