### ISSUE TITLE
RemoteConfigComponent and FirebaseMessaging return null for some users

### ISSUE THREAD

**Issue by wdziemia** [firebase/firebase-android-sdk#5691]
### Step 2: Describe your environment

  * Android Studio version: Android Studio Iguana
  * Firebase Component: Messaging & Config 
  * Component version: Firebase BOM 32.7.0

### [REQUIRED] Step 3: Describe the problem

https://github.com/firebase/firebase-android-sdk/blob/5ef5cdda14666df3f6727719f4d3344c8286ef32/firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfig.java#L87

The code block above returns null for about ~1,500 users a day when we attempt to configure RemoteConfig. We are forced to check if `RemoteConfigComponent` is available before calling the config-ktx helper function:

```
firebase.get(RemoteConfigComponent::class.java) != null
```

and when we dont we see the following crash in production.

```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'dbxyzptlk.h41.g dbxyzptlk.h41.k.d()' on a null object reference
        at com.google.firebase.remoteconfig.FirebaseRemoteConfig.getInstance(FirebaseRemoteConfig.java:86)
        at com.google.firebase.remoteconfig.ktx.RemoteConfigKt.remoteConfig(RemoteConfig.kt:32)
```

We also see the same behavior when it comes to getting the FirebaseMessaging and do a similar check:

```
firebase.get(FirebaseMessaging::class.java) != null
```

I do see the `ComponentDiscoveryService` have the Registrars populated for Messaging and RemoteConfig as well:

![image](https://github.com/firebase/firebase-android-sdk/assets/3921079/f2aa3ad4-ad1a-41af-9cef-598404f820ad)

**Comment by lehcar09** [comment]
Hi @wdziemia, thank you for reaching out. I've been trying to reproduce this issue but haven't been successful.  Below is how I initialize the RemoteConfig instance.

MainActivity.kt
```
//Initialization
override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.main_layout)

        FirebaseApp.initializeApp(this)
        remoteConfig = FirebaseRemoteConfig.getInstance(FirebaseApp.getInstance())
    }
```

Any chance you could provide detailed steps to reproduce the issue or an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) where the issue is reproducible? Aside from that, does the issue occur on a specific set of users or devices?

**Comment by wdziemia** [comment]
@lehcar09 Hello! Yes we initialize RC similarly. We use dagger though so its a bit more indirect than your example but the calls and flow are the same. I dont know how to reproduce this issue locally but can provide more details:
- Most of our devs run either Emulators or Google Pixels and we did not see any crashes during development (Firebase & RC is initialized on App start) or Alpha users (~100) .
- 75% of users affected are on Samsung devices
- Affects all OS versions we support (Android 8 and above)

We have a more aggressive fetch for Firebase Messaging which uses some exponential backoff with an interval of 10ms delay between checking if Firebase Messaging returns an instance or null. There is a max delay between checks being 1000ms. Ive set up some metrics to track the total duration it takes to return the Messaging component and have some prelim data below. This data should be of Developer & Alpha users (<200). I will update once this build hits beta and prod environments.

![Screenshot 2024-02-09 at 10 55 41 AM](https://github.com/firebase/firebase-android-sdk/assets/3921079/40af4c66-355c-4b88-add2-38db0fde7d67)

**Comment by wdziemia** [comment]
Some data over the last 24 hours - Firebase Messaging shows the following:

- About 96K Samples
- Success rate is virtually 100% - so this looks like its Lazily initialized?

![Screenshot 2024-02-15 at 9 03 46 PM](https://github.com/firebase/firebase-android-sdk/assets/3921079/1d175198-4433-4cf2-9fa8-5d5a80a8b0a9)

**Comment by lehcar09** [comment]
Hi @wdziemia, sorry for the hold up. I can't say for sure if this is due to lazy initialization. Based on your description, it seems like you're using Dagger to initialize Firebase. Something like:
```
@Provides
@Singleton
fun provideFirebaseRC(@ApplicationContext appContext: Context): FirebaseRemoteConfig {
   FirebaseApp.initializeApp(appContext)
   return FirebaseRemoteConfig.getInstance(FirebaseApp.getInstance())
}
```
Just to note, [FirebaseInitProvider](https://firebase.google.com/docs/reference/android/com/google/firebase/provider/FirebaseInitProvider) initializes Firebase APIs at app startup time, not being able to initialize them properly (considering the inter-dependency) might cause conflicts. Also, as per the documentation of [FirebaseApp](https://firebase.google.com/docs/reference/android/com/google/firebase/FirebaseApp):

> Any FirebaseApp initialization must occur only in the main process of the app. Use of Firebase in processes other than the main process is not supported and will likely cause problems related to resource contention.

## Useful References
[Take Control of Your Firebase Init on Android](https://firebase.googleblog.com/2017/03/take-control-of-your-firebase-init-on.html)
[How does Firebase initialize on Android?](https://firebase.googleblog.com/2016/12/how-does-firebase-initialize-on-android.html)

Can you share how and when are you calling `FirebaseApp.initializeApp()` and `FirebaseMessaging.getInstance()`? Is your app a multi process app?

**Comment by wdziemia** [comment]
We are calling it as part of our Dagger object graph creation which is done in Applicaiton.onCreate(), there are no calls to use Firebase / RemoteConfig / Messaging that are outside of dependency injections. 

Messaging shows the following results, with an overall 23.6% success rate in returning an instance, this number is quite a surprise.

![Screenshot 2024-03-11 at 7 33 25 PM](https://github.com/firebase/firebase-android-sdk/assets/3921079/4431e67a-ade7-4707-b9ff-f18644ce32dd)

Remote Config has about 1300 instances of being unavailable during Application.onCreate() - this is a relatively small number compared to the amount of app starts per day we have (~5 million)

**Comment by MichaelVerdon** [comment]
Is this still being experienced on the latest versions?

**Comment by wdziemia** [comment]
👋 This looks to still be an issue with around 2750 (+/- 250) users being returned a null instance of Remote-Config. We have retry logic which will then check if the instance is eventually returned within a 5 minute span but those look to be all consistently failing.

Ive looked to see if there is a correlation between Google Play Services failures (all error codes) but looks like all of those failures are about 1/3rd of remote-config null errors.

I see we are on `33.0.0` firebase-bom where `33.7.0` bumped `firebase-config` from `22.0.0` to `22.0.1` with a [protobuf dep upgrade ](https://firebase.google.com/support/release-notes/android#remote-config_v22-0-1). Ill try updating the BOM to see if anything changes in error count!

For some further context, we've had a similar issue with Firebase Messaging returning null since 2019.

**Comment by lehcar09** [comment]
Thank you for the details @wdziemia. Can you share an MCVE? This would help us to investigate the issue. Thanks!

**Comment by wdziemia** [comment]
@lehcar09 I've never been able to repro this myself so Im unable to provide an MCVE. This is certainly an edge case though as we have around 500,000 cold-starts of our app per day so this only affects 0.25% - 0.50% of our users.

**Comment by lehcar09** [comment]
Hi @wdziemia, sorry for the silence here. Are you still experiencing this issue with the latest SDK version?

**Comment by wdziemia** [comment]
@lehcar09 No worries - will bump to 34.10.0 and report back. The numbers I reported earlier (on 33.0.0) have remained consistent fwiw!

**Comment by wdziemia** [comment]
@lehcar09  Sorry for the delay - Im looking at our data now (w/ 34.12.0) and Im seeing Messaging return 96% of the time successfully (give or take 1%). Remote config returns null around ~2,000 per day, with a 10% - 20% swing in either direction. With our scale, the number of users affected is very very low at around 300 users per day.
