### ISSUE TITLE
Crash during apple login on android

### ISSUE THREAD

**Issue by rajatsharma16** [firebase/firebase-android-sdk#5712]
- **Android Studio version**: Android Studio Giraffe | 2022.3.1 Patch 2
- **Firebase Component**: Authentication
- **Component version**: com.google.firebase:firebase-auth:22.1.2

I have implemented apple login on android, using firebase, based on [this documentation](https://firebase.google.com/docs/auth/android/apple). It is working fine in our testing and by and large in production as well.

However, we are noticing some crash instances of **ActivityNotFoundException**

```
Fatal Exception: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat={REDACTED}/... flg=0x50000000 (has extras) }
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2067)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1727)
       at android.app.Activity.startActivityForResult(Activity.java:5343)
       at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:712)
       at android.app.Activity.startActivityForResult(Activity.java:5278)
       at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:693)
       at android.app.Activity.startActivity(Activity.java:5687)
       at android.app.Activity.startActivity(Activity.java:5640)
       at com.google.firebase.auth.internal.zzay.onComplete(com.google.firebase:firebase-auth@@22.1.2:13)
       at com.google.android.gms.tasks.zzi.run(com.google.android.gms:play-services-tasks@@18.0.2:1)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7695)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
```

**Device details**:
```
Brand:Along - Windriver
Model:T88
Android 11
```

I have checked against this [comment](https://github.com/firebase/firebase-android-sdk/issues/4096#issuecomment-1248036258) and this stackoverflow [link](https://stackoverflow.com/questions/64588281/caused-by-java-lang-classnotfoundexception-didnt-find-class-in-firebase-phone/64597290#64597290). My `androidx browser` seems to be ok. However still once in a while, I observe this crash.

```
+--- com.google.firebase:firebase-auth:22.3.1 // this is the current development version, not live in prod yet.
|    +--- androidx.browser:browser:1.4.0
```

Any help is appreciated thanks.

**Comment by lehcar09** [comment]
Hi @rajatsharma16, thank you for reaching out. I've been trying to reproduce this issue but haven't been successful. Any chance you could provide an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) where the issue is reproducible?

**Comment by rajatsharma16** [comment]
Hi @lehcar09 sorry in this case am unable to think what could the MCVE be. I have pasted the stacktrace of a crash observed in production. I have myself not faced it while debugging, else I would have shared some steps.

What I know is that the user was attempting _Apple login_ on the device mentioned above. It looks like that after successful oauth in an external browser, somehow it threw `ActivityNotFoundException` while trying to return to our app.

**Comment by lehcar09** [comment]
Hi @rajatsharma16, can you share the code snippet of the sign in? Aside from that, can you share more information such as devices android version that are experiencing this behavior, full stacktrace, or anything that you find might be useful, it'll really help us out a lot.
