### ISSUE TITLE
Fatal Exception: java.lang.SecurityException Firebase SDK BOM 32.7.1

### ISSUE THREAD

**Issue by TabassumFatima123** [firebase/firebase-android-sdk#5718]
I have updated to firebase sdk bom to 32.7.1 and after that my got crashes 
due to om.google.firebase.sessions.SessionLifecycleService (has extras) } 
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: _10_
  * Firebase Component: ____FIrebase messaging_ (Database, Firestore, Storage, Functions, etc)
  * Component version: ____32.7.1_

Fatal Exception: java.lang.SecurityException: Not allowed to bind to service Intent { act=9212 cmp=com.bykea.pk/com.google.firebase.sessions.SessionLifecycleService (has extras) }
       at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1741)
       at android.app.ContextImpl.bindService(ContextImpl.java:1651)
       at android.content.ContextWrapper.bindService(ContextWrapper.java:705)
       at com.google.firebase.sessions.SessionLifecycleServiceBinderImpl.bindToService(SessionLifecycleServiceBinder.kt:52)
       at com.google.firebase.sessions.SessionLifecycleClient.bindToService(SessionLifecycleClient.kt:105)
       at com.google.firebase.sessions.FirebaseSessions$1.invokeSuspend(FirebaseSessions.kt:53)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.firebase.concurrent.CustomThreadFactory.lambda$newThread$0(CustomThreadFactory.java:47)
       at java.lang.Thread.run(Thread.java:919)

**Comment by lehcar09** [comment]
Hi @TabassumFatima123, thank you for reaching out. I tried reproducing the issue using our, however, I wasn't able to encounter any exception. Can you share an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) to help us investigate the issue? If you're unable to provide one, can you try our [quickstart app](https://github.com/firebase/quickstart-android/tree/master) and see if you can reproduce the issue?

Aside from that, are you constantly experiencing this error? Could you provide the steps you've taken when you encountered the issue? or does the issue occur on certain devices and/or android versions?

**Comment by TabassumFatima123** [comment]
Hi @lehcar09 , so i am trying to reproduce this issue for last couple of days but it is not reproducing on our testing environment but constantly reporting on production after update to **_firebase bom 32.7.1_** and has higher trend of crashes because of this our Application crash rate has increased i am providing you further details related to the crash 
Android Devices  : 
Q Mobile - FIH Foxconn
Q Mobile - View Max Pro
Q Mobile - View Max

Devices OS :
Android 10

**Comment by YuryPashkov** [comment]
Same crash for our project. Firebase SDK BOM version 32.7.0. 

Device Q Mobile - FIH Foxconn Android 10
Device states: 100% background

**Comment by danotter90** [comment]
It seems like this is very similar or the same to #2062. It also seems to affect devices by the same manufacturers again. Possibly it has regressed? According to [this comment](https://github.com/firebase/firebase-android-sdk/issues/2062#issuecomment-928097262) the original issue was caused by the underlying `play-services-cloud-messaging`. It would be great if someone on the Firebase team could investigate.
