### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.AbstractCollection.size()' on a null object reference

### ISSUE THREAD

**Issue by singh-srikant** [firebase/firebase-android-sdk#5735]
### [READ] Step 1: Are you in the right place?

Yes

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version:  2023.1.1
  * Firebase Component: Database/Storage/Analytics (unknown)
  * Component version: crashlytics = "18.4.1"  crashlyticsPlugin = "2.9.9"

### [REQUIRED] Step 3: Describe the problem
We are getting a playstore crash which occurs during Firebase initialization and is specific to chromebook devices. Most of the occurrences are on Android 11. The library causing the crash is `'com.google.firebase:firebase-ml-vision:24.0.3'`
This crash is a blocker for us and is affecting almost all the Chromebook devices.

Stacktrace from Google Play Console
```
Exception java.lang.ExceptionInInitializerError:
  at com.google.android.gms.internal.firebase_ml.zzmw.zza (com.google.firebase:firebase-ml-common@@22.1.1:18)
  at com.google.firebase.ml.vision.VisionRegistrar.getComponents (com.google.firebase:firebase-ml-vision@@24.0.3:16)
  at com.google.firebase.tracing.ComponentMonitor.processRegistrar (ComponentMonitor.java:28)
  at com.google.firebase.components.ComponentRuntime.discoverComponents (ComponentRuntime.java:117)
  at com.google.firebase.components.ComponentRuntime.<init> (ComponentRuntime.java:99)
  at com.google.firebase.components.ComponentRuntime.<init> (ComponentRuntime.java:46)
  at com.google.firebase.components.ComponentRuntime$Builder.build (ComponentRuntime.java)
  at com.google.firebase.FirebaseApp.<init> (FirebaseApp.java:439)
  at com.google.firebase.FirebaseApp.initializeApp (FirebaseApp.java:296)
  at com.google.firebase.FirebaseApp.initializeApp (FirebaseApp.java:264)
  at com.google.firebase.FirebaseApp.initializeApp (FirebaseApp.java:249)
  at com.adobe.reader.startup.StartupTimeProvider.onCreate (StartupTimeProvider.kt:42)
  at android.content.ContentProvider.attachInfo (ContentProvider.java:2388)
  at android.content.ContentProvider.attachInfo (ContentProvider.java:2358)
  at com.microsoft.intune.mam.client.content.MAMContentProvider.attachInfoReal (MAMContentProvider.java)
  at com.microsoft.intune.mam.client.app.offline.OfflineContentProviderBehavior.attachInfoMAM (OfflineContentProviderBehavior.java)
  at com.microsoft.intune.mam.client.content.MAMContentProvider.attachInfoMAM (MAMContentProvider.java)
  at com.microsoft.intune.mam.client.app.offline.OfflineContentProviderBehavior.attachInfo (OfflineContentProviderBehavior.java)
  at com.microsoft.intune.mam.client.content.MAMContentProvider.attachInfo (MAMContentProvider.java:68)
  at android.app.ActivityThread.installProvider (ActivityThread.java:7268)
  at android.app.ActivityThread.installContentProviders (ActivityThread.java:6809)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:6726)
  at android.app.ActivityThread.access$1400 (ActivityThread.java:237)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1924)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:223)
  at android.app.ActivityThread.main (ActivityThread.java:7741)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:592)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:966)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.AbstractCollection.size()' on a null object reference
  at com.google.android.gms.internal.firebase_ml.zzmz.<init> (com.google.firebase:firebase-ml-common@@22.1.1:1)
  at com.google.android.gms.internal.firebase_ml.zzmw.<clinit> (com.google.firebase:firebase-ml-common@@22.1.1)
```

#### Steps to reproduce:
The crash is device specific and has spiked in the latest Beta.

1. Install Adobe Acrobat (Version 24.2.0.31328.Beta) from Google Playstore on Chromebook device.
2. Click "Open" after app is installed.

ADB logcat from Chromebook device
```
02-22 14:37:19.819 11279 11279 E AndroidRuntime: Process: com.adobe.reader, PID: 11279
02-22 14:37:19.819 11279 11279 E AndroidRuntime: java.lang.ExceptionInInitializerError
02-22 14:37:19.819 11279 11279 E AndroidRuntime:        at com.google.android.gms.internal.firebase_ml.zzmw.zza(SourceFile:3)
02-22 14:37:19.819 11279 11279 E AndroidRuntime:        at com.google.firebase.ml.vision.VisionRegistrar.getComponents(SourceFile:85)
02-22 14:37:19.819 11279 11279 E AndroidRuntime:        at fu.b.a(SourceFile:6)
02-22 14:37:19.819 11279 11279 E AndroidRuntime:        at as.n.m(SourceFile:35)
02-22 14:37:19.819 11279 11279 E AndroidRuntime:        at as.n.<init>(SourceFile:15)
02-22 14:37:19.819 11279 11279 E AndroidRuntime:        at as.n.<init>(SourceFile:1)
02-22 14:37:19.819 11279 11279 E AndroidRuntime:        at as.n$b.e(Unknown Source:12)
02-22 14:37:19.819 11279 11279 E AndroidRuntime:        at com.google.firebase.e.<init>(SourceFile:183)
02-22 14:37:19.819 11279 11279 E AndroidRuntime:        at com.google.firebase.e.t(SourceFile:65)
02-22 14:37:19.819 11279 11279 E AndroidRuntime:        at com.google.firebase.e.s(SourceFile:3)
02-22 14:37:19.819 11279 11279 E AndroidRuntime:        at com.google.firebase.e.r(SourceFile:36)
02-22 14:37:19.819 11279 11279 E AndroidRuntime:        at com.adobe.reader.startup.StartupTimeProvider.onCreate(SourceFile:13)
02-22 14:37:19.819 11279 11279 E AndroidRuntime:        at android.content.ContentProvider.attachInfo(ContentProvider.java:2388)
02-22 14:37:19.819 11279 11279 E AndroidRuntime:        at android.content.ContentProvider.attachInfo(ContentProvider.java:2358)
02-22 14:37:19.819 11279 11279 E AndroidRuntime:        at f70.d.attachInfoReal(Unknown Source:0)
02-22 14:37:19.819 11279 11279 E AndroidRuntime:        at com.microsoft.intune.mam.client.app.offline.OfflineContentProviderBehavior.attachInfoMAM(Unknown Source:2)
02-22 14:37:19.819 11279 11279 E AndroidRuntime:        at f70.d.attachInfoMAM(Unknown Source:2)
02-22 14:37:19.819 11279 11279 E AndroidRuntime:        at com.microsoft.intune.mam.client.app.offline.OfflineContentProviderBehavior.attachInfo(Unknown Source:2)
02-22 14:37:19.819 11279 11279 E AndroidRuntime:        at f70.d.attachInfo(SourceFile:19)
02-22 14:37:19.819 11279 11279 E AndroidRuntime:        at android.app.ActivityThread.installProvider(ActivityThread.java:7268)
02-22 14:37:19.819 11279 11279 E AndroidRuntime:        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6809)
02-22 14:37:19.819 11279 11279 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6726)
02-22 14:37:19.819 11279 11279 E AndroidRuntime:        at android.app.ActivityThread.access$1400(ActivityThread.java:237)
02-22 14:37:19.819 11279 11279 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1924)
02-22 14:37:19.819 11279 11279 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
02-22 14:37:19.819 11279 11279 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
02-22 14:37:19.819 11279 11279 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7741)
02-22 14:37:19.819 11279 11279 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-22 14:37:19.819 11279 11279 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
02-22 14:37:19.819 11279 11279 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:966)
02-22 14:37:19.819 11279 11279 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.AbstractCollection.size()' on a null object reference
02-22 14:37:19.819 11279 11279 E AndroidRuntime:        at com.google.android.gms.internal.firebase_ml.q0.<init>(SourceFile:1)
02-22 14:37:19.819 11279 11279 E AndroidRuntime:        at com.google.android.gms.internal.firebase_ml.zzmw.<clinit>(Unknown Source:5)
02-22 14:37:19.819 11279 11279 E AndroidRuntime:        ... 30 more
02-22 14:37:19.827   393  1696 W ActivityTaskManager:   Force finishing activity com.adobe.reader/.AdobeReader
```

**Comment by lehcar09** [comment]
Hi [@abhishek084](https://github.com/abhishek084), thanks for reaching out. Just for context, the firebase-ml-vision is an old/[deprecated](https://firebase.google.com/docs/ml/android/recognize-text-deprecated) version of the SDK. It is advised to use the more recent/updated version of the SDK. You can either use [Cloud Vision API](https://firebase.google.com/docs/ml/android/recognize-text) where it uses Cloud functions to interpret text from images; or you may also use the on-device text recognition [standalone ML kit library](https://developers.google.com/ml-kit/vision/text-recognition/v2/android). If you choose the latter option, this [quickstart](https://codelabs.developers.google.com/codelabs/mlkit-android#0) will definitely help you get started a lot faster.

I tried reproducing the issue in Android 11, however I did not encounter any issue. Can you share an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) to help us investigate the issue? To clarify, are the steps to reproduce the issue you shared similar for Android 11?

**Comment by singh-srikant** [comment]
@lehcar09 The crash was reproducible on Chromebook devices only in the playstore beta build, and is no longer observed in the latest release build. We don't know how it got fixed automatically. Was there any change in Firebase code recently ?
I will share the Adobe Acrobat Reader app version if the issue starts occurring again.
Sure, we will try to upgrade to the latest version of firebase-ml-vision library in the meantime. Thanks.

**Comment by lehcar09** [comment]
I'm glad the issue seems resolved. You can check this [documentation](https://firebase.google.com/support/release-notes/android#latest_sdk_versions) for Firebase release notes. I'll be closing this case now. Let us know if we need to re-open the investigation. Thanks.
