### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException Existing wake lock uid changed: 10106 to 10197

### ISSUE THREAD

**Issue by ledvance-jason** [firebase/firebase-android-sdk#5754]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Hedgehog | 2023.1.1 Patch 2
  * Firebase Component: Crashlytics、Analytics、Messaging
  * Component version: 32.2.0

#### Steps to reproduce:

Crash reported by firebase.

#### Relevant Code:

```
Device information:
Brand:Jimi - FIH Foxconn
Model:KidzPad Pro
Orientation:Portrait
RAM free: 2.18 GB
Disk free: 41.37 GB
Operating System
Version:Android 13
Orientation:Portrait
Rooted:No

Fatal Exception: java.lang.IllegalStateException: Existing wake lock uid changed: 10106 to 10197
       at android.os.Parcel.createExceptionOrNull(Parcel.java:3025)
       at android.os.Parcel.createException(Parcel.java:3001)
       at android.os.Parcel.readException(Parcel.java:2984)
       at android.os.Parcel.readException(Parcel.java:2926)
       at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:3032)
       at android.app.NotificationManager.notifyAsUser(NotificationManager.java:678)
       at android.app.NotificationManager.notify(NotificationManager.java:628)
       at com.google.firebase.messaging.DisplayNotification.showNotification(DisplayNotification.java:177)
       at com.google.firebase.messaging.DisplayNotification.handleNotification(DisplayNotification.java:111)
       at com.google.firebase.messaging.FirebaseMessagingService.dispatchMessage(FirebaseMessagingService.java:221)
       at com.google.firebase.messaging.FirebaseMessagingService.passMessageIntentToSdk(FirebaseMessagingService.java:185)
       at com.google.firebase.messaging.FirebaseMessagingService.handleMessageIntent(FirebaseMessagingService.java:172)
       at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(FirebaseMessagingService.java:161)
       at com.google.firebase.messaging.EnhancedIntentService.lambda$processIntent$0$com-google-firebase-messaging-EnhancedIntentService(EnhancedIntentService.java:78)
       at com.google.firebase.messaging.EnhancedIntentService$$ExternalSyntheticLambda1.run(:6)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@18.1.0:2)
       at java.lang.Thread.run(Thread.java:1012)
Caused by android.os.RemoteException: Remote stack trace:
	at com.android.server.power.PowerManagerService$WakeLock.updateProperties(PowerManagerService.java:5292)
	at com.android.server.power.PowerManagerService.acquireWakeLockInternal(PowerManagerService.java:1581)
	at com.android.server.power.PowerManagerService.-$$Nest$macquireWakeLockInternal(Unknown Source:0)
	at com.android.server.power.PowerManagerService$BinderService.acquireWakeLock(PowerManagerService.java:5660)
	at android.os.PowerManager$WakeLock.acquireLocked(PowerManager.java:2981)

```

**Comment by gsakakihara** [comment]
Was this a single crash or have there been more reports than this one? If there have been more reports, is it limited to or mostly on a specific Android API level, device type, or device manufacturer?

**Comment by ledvance-jason** [comment]
Only this device appears three times.

**Comment by gsakakihara** [comment]
From what I can tell, that error is internal to the Android platform and there isn't really anything that FCM or your app could do to fix it (or cause it). If it's limited to a single device, it may just be that the device is in a bad state (something may have been corrupted or it may have hit a bug in the platform or manufacturer's customization).

For now I'm going to close this issue, but feel free to reopen or file a new issue if you start seeing this more widely.
