### ISSUE TITLE
java.lang.RuntimeException  com.google.android.gms:play-services-auth@@20.7.0:23

### ISSUE THREAD

**Issue by efstathiosntonas** [firebase/firebase-android-sdk#5768]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Iguana | 2023.2.1
  * Firebase Component: Authentication
  * Component version: 20.7.0

#### Steps to reproduce:

getting this stacktrace: 

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.XXXXX/com.google.android.gms.auth.api.signin.internal.SignInHubActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3635)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7838)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
        at com.google.android.gms.auth.api.signin.internal.SignInHubActivity.onCreate(com.google.android.gms:play-services-auth@@20.7.0:23)
        at android.app.Activity.performCreate(Activity.java:8051)
        at android.app.Activity.performCreate(Activity.java:8031)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7838)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)


```

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by argzdev** [comment]
Hey @efstathiosntonas, thanks for reaching out. I'm guessing this have something to do with the sign ins. Could you share which provider is causing this issue? (e.g. Google Sign In, Email/Password). Also are there any specific steps to reproduce this issue?

**Comment by efstathiosntonas** [comment]
the providers I'm using are Facebook, Phone and Apple Sign in. 

I'm using react-native-firebase@19.0.1 so I'm not quite sure what code might trigger this.

cc: @mikehardy

**Comment by efstathiosntonas** [comment]
I got some users complaining that they never received SMS code and one of them mentioned Facebook wasn't working either.

**Comment by lehcar09** [comment]
Hi @efstathiosntonas, it doesn’t look like a straightforward issue. I’ve tried reproducing this on my side with Firebase Auth in native Android, but no luck. The play-services-auth library is added separately in Firebase [Auth for Google Sign In](https://firebase.google.com/docs/auth/android/google-signin#before_you_begin), unlike with [React Native Firebase Auth for Google Sign In](https://firebase.google.com/docs/auth/android/google-signin#before_you_begin).

I wonder if it’s an issue that’s specific within React Native Firebase and if the issue will be fixed by updating the play-service-auth library version. Looking through our internal bugs, it looks like there was a recent fix that was applied to the latest version of com.google.android.gms:play-services-auth:21.0.0. Maybe the invertase team could update this dependency. Have you tried filing an issue on [their](https://github.com/invertase/react-native-firebase/issues) repository?

**Comment by efstathiosntonas** [comment]
@lehcar09 thanks for looking into it. 

@mikehardy can we bump `play-services-auth` to 21.0.0?

* https://github.com/invertase/react-native-firebase/blob/873130c11595690924cf60feb08b64b3b9421042/packages/app/package.json#L88

**Comment by efstathiosntonas** [comment]
@lehcar09 Since `react-native-firebase` updated to include `play-services-auth:21.0.0` I will close this down, so far no issues on our bug tracker.

Will reopen if I ever see this again. Thank you both guys for looking into this.

**Comment by efstathiosntonas** [comment]
Thanks Mike, in my mind I thought it was a release page but after seing your commit I realized it is an .md 🤦‍♂️, I would have opened a PR instead of nagging you here 😅
