### ISSUE TITLE
FirebaseApp.UserUnlockReceiver.unregister crashes

### ISSUE THREAD

**Issue by consp1racy** [firebase/firebase-android-sdk#5775]
* Firebase Component: Common
  * Component version: 20.4.2

#### Steps to reproduce:

Crashlytics notified us about a crash in `FirebaseApp.UserUnlockReceiver.unregister`. The method is only called from `FirebaseApp.UserUnlockReceiver.onReceive` which in turn only responds to `android.intent.action.USER_UNLOCKED`. I don't know how many times the system sends the broadcast but it apparently isn't just once.

#### Relevant Code:
https://github.com/firebase/firebase-android-sdk/blob/b77c2188e5ec7c53c2a955fc4663b301e6c98c83/firebase-common/src/main/java/com/google/firebase/FirebaseApp.java#L668-L680

`FirebaseApp` initialization may be idempotent but `Context.unregisterReceiver` isn't. The method crashes if the receiver isn't registered.

#### Suggested solution
```java
public void unregister() {
  try {
    applicationContext.unregisterReceiver(this);
  } catch (IllegalArgumentException ignore) {
    // The receiver isn't registered.
  }
}
```

**Comment by lehcar09** [comment]
Hi @consp1racy, thank you for reaching out. We appreciate you investigating the issue and providing the fix. I'll inform our engineers about this with your pull request.

**Comment by rlazo** [comment]
Hi @consp1racy thanks for reaching out, and providing a fix! I'll review the code and run the tests required to include it in the codebase.

**Comment by consp1racy** [comment]
Maybe it won't be that easy. I got this log

>E/FirebaseSessions: Failed to register lifecycle callbacks, unexpected context class ...

**Comment by beaver-android** [comment]
Hi everyone,
As of Firebase 33.6.0, we're still getting dozen of crash events about this issue, usually happens after an app update.
Can a fix be prioritised?
Thanks

Environment:
```
Android 11
98% Galaxy Tab Active3 
1% Galaxy Tab S5e
<1% Galaxy Tab A8
```

Stacktrace:
```
 Fatal Exception: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.USER_UNLOCKED flg=0x50000010 (has extras) } in com.google.firebase.g$c@a99d7a2
       at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1681)
       at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(:2)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:247)
       at android.app.ActivityThread.main(ActivityThread.java:8656)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

 Caused by java.lang.IllegalArgumentException: Receiver not registered: com.google.firebase.g$c@a99d7a2
       at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1524)
       at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1712)
       at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:733)
       at com.google.firebase.FirebaseApp$UserUnlockReceiver.unregister(FirebaseApp.java:679)
       at com.google.firebase.FirebaseApp$UserUnlockReceiver.onReceive(FirebaseApp.java:675)
       at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1671)
       at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(:2)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:247)
       at android.app.ActivityThread.main(ActivityThread.java:8656)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```
