### ISSUE TITLE
FIAM - In-App Messaging Crash

### ISSUE THREAD

**Issue by modsfabio** [firebase/firebase-android-sdk#5780]
* Firebase Component: **In-App Messaging**
* Component version: **firebase-bom:32.7.4**

### Problem
We see a lot of crashes when a new campaign is created. The App crashes with the following stacktrace:

```
Caused by android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
       at android.view.ViewRootImpl.setView(ViewRootImpl.java:1596)
       at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:509)
       at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:133)
       at com.google.firebase.inappmessaging.display.internal.FiamWindowManager.show(FiamWindowManager.java:67)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay$4$4.run(FirebaseInAppMessagingDisplay.java:416)
       at android.app.Activity.runOnUiThread(Activity.java:7258)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay$4.onSuccess(FirebaseInAppMessagingDisplay.java:412)
       at com.google.firebase.inappmessaging.display.internal.FiamImageLoader$Callback.onResourceReady(FiamImageLoader.java:157)
       at com.google.firebase.inappmessaging.display.internal.FiamImageLoader$Callback.onResourceReady(FiamImageLoader.java:135)
       at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:667)
       at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:596)
       at com.bumptech.glide.load.engine.EngineJob.callCallbackOnResourceReady(EngineJob.java:159)
       at com.bumptech.glide.load.engine.EngineJob$CallResourceReady.run(EngineJob.java:428)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8663)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

The issue is similar to #5567, but apparently it's still not fixed.
There is no code from our side.

**Comment by lehcar09** [comment]
Hi @modsfabio, thank you for reaching out and reporting the issue. Somehow, I was able to reproduce the issue when there's a displayed campaign and the orientation changed.

Per checking the issue #5567, there was a submitted PR that might fix the issue. However, this was not yet merged. I'll inform our engineers and see what we can do here.

**Comment by lehcar09** [comment]
Hi @modsfabio, this issue has been resolved in BoM 32.8.1, Firebase In-app Messaging v20.4.2. I'll be closing this issue now. Please feel free to file new issue if there's another problem. Thanks!
