### ISSUE TITLE
Fatal Exception: java.lang.VerifyError: Verifier rejected class kotlinx.coroutines.SupervisorKt

### ISSUE THREAD

**Issue by wezley98** [firebase/firebase-android-sdk#5783]
### Step 2: Describe your environment

  * Android Studio version:
  ```
Android Studio Iguana | 2023.2.1
Build #AI-232.10227.8.2321.11479570, built on February 21, 2024
```
  * Firebase Component:
  ```
firebase-bom = { module = "com.google.firebase:firebase-bom", version = "32.7.4" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-perf = { module = "com.google.firebase:firebase-perf" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging" }
firebase-config = { module = "com.google.firebase:firebase-config" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version = "1.9.22" }
kotlin-coroutines-jvm = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm", version = "1.8.0" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version = "1.8.0" }
```

### Step 3: Describe the problem
Crash seen in app start

```
Fatal Exception: java.lang.VerifyError: Verifier rejected class kotlinx.coroutines.SupervisorKt: kotlinx.coroutines.CompletableJob kotlinx.coroutines.SupervisorKt.SupervisorJob(kotlinx.coroutines.Job) failed to verify: kotlinx.coroutines.CompletableJob kotlinx.coroutines.SupervisorKt.SupervisorJob(kotlinx.coroutines.Job): [0x2] 'this' argument 'Uninitialized Reference: kotlinx.coroutines.y Allocation PC: 0' not instance of 'Reference: kotlinx.coroutines.JobImpl'
 java.lang.Object kotlinx.coroutines.SupervisorKt.supervisorScope(kotlin.jvm.functions.Function2, kotlin.coroutines.Continuation) failed to verify: java.lang.Object kotlinx.coroutines.SupervisorKt.supervisorScope(kotlin.jvm.functions.Function2, kotlin.coroutines.Continuation): [0x6] 'this' argument 'Uninitialized Reference: kotlinx.coroutines.x Allocation PC: 0' not instance of 'Reference: kotlinx.coroutines.internal.ScopeCoroutine' (declaration of 'kotlinx.coroutines.SupervisorKt' appears in /data/app/~~zj8U22kl5n9ByK09SpdkxQ==/com.bskyb.sportnews-Lo_rdc0e3WSUIBrqNGLdBA==/base.apk!classes2.dex)
       at androidx.datastore.preferences.PreferenceDataStoreDelegateKt.preferencesDataStore$default(PreferenceDataStoreDelegate.kt:70)
       at com.google.firebase.sessions.settings.SessionsSettings.<clinit>(SessionsSettings.kt:149)
       at com.google.firebase.sessions.FirebaseSessionsRegistrar.getComponents$lambda-3(FirebaseSessionsRegistrar.kt)
       at com.google.firebase.tracing.ComponentMonitor.lambda$processRegistrar$0(ComponentMonitor.java:38)
       at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0(ComponentRuntime.java:160)
       at com.google.firebase.components.Lazy.get(Lazy.java:53)
       at com.google.firebase.components.ComponentContainer.get(ComponentContainer.java:48)
       at com.google.firebase.components.RestrictedComponentContainer.get(RestrictedComponentContainer.java:105)
       at com.google.firebase.sessions.FirebaseSessionsRegistrar.getComponents$lambda-0(FirebaseSessionsRegistrar.kt:51)
       at com.google.firebase.tracing.ComponentMonitor.lambda$processRegistrar$0(ComponentMonitor.java:38)
       at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0(ComponentRuntime.java:160)
       at com.google.firebase.components.Lazy.get(Lazy.java:53)
       at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents(ComponentRuntime.java:322)
       at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(ComponentRuntime.java:312)
       at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:607)
       at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:300)
       at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:264)
       at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:249)
       at com.google.firebase.provider.FirebaseInitProvider.onCreate(FirebaseInitProvider.java:69)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2619)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2589)
       at com.google.firebase.provider.FirebaseInitProvider.attachInfo(FirebaseInitProvider.java:61)
       at android.app.ActivityThread.installProvider(ActivityThread.java:7836)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:7347)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7042)
       at android.app.ActivityThread.-$$Nest$mhandleBindApplication()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2261)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:205)
       at android.os.Looper.loop(Looper.java:294)
       at android.app.ActivityThread.main(ActivityThread.java:8248)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```
<img width="586" alt="Screenshot 2024-03-14 at 11 07 43" src="https://github.com/firebase/firebase-android-sdk/assets/1488209/948b9b35-6b53-4295-beb9-463c112ecbb9">
<img width="598" alt="Screenshot 2024-03-14 at 11 08 11" src="https://github.com/firebase/firebase-android-sdk/assets/1488209/abc2d52d-8de7-45af-b949-8bcb7a403906">
<img width="586" alt="Screenshot 2024-03-14 at 11 08 32" src="https://github.com/firebase/firebase-android-sdk/assets/1488209/44ec51a4-9122-4356-9f80-c87efb6e0421">

#### Steps to reproduce:

Can't reproduce locally, only seen in firebase.

**Comment by lehcar09** [comment]
Hi @wezley98, thank you for reaching out and reporting the issue. I tried to reproduce the issue, but, I was unsuccessful. Per checking with our Engr, this might be related to R8 full mode. Are you using the R8 full mode?

**Comment by lehcar09** [comment]
Hi @wezley98, thank you for reaching out and reporting the issue. I tried to reproduce the issue, but, I was unsuccessful. Per checking with our Engr, this might be related to R8 full mode. Are you using the R8 full mode? Is there any chance you could share an MCVE to help us investigate the issue?
