### ISSUE TITLE
Fatal Exception: java.lang.IncompatibleClassChangeError SessionsSettings.<clinit>

### ISSUE THREAD

**Issue by b-basoglu** [firebase/firebase-android-sdk#5790]
Step 2: Describe your environment

  * Android Studio version: Android Studio Iguana | 2023.2.1 Build #AI-232.10227.8.2321.11479570
  * Firebase Component:     implementation platform("com.google.firebase:firebase-bom:32.7.4")
    firebaseConfig      : "com.google.firebase:firebase-config",
    firebaseAnalytics   : "com.google.firebase:firebase-analytics",
    firebaseCrashlitics : "com.google.firebase:firebase-crashlytics-ktx",
    firebaseDynamiclinks: "com.google.firebase:firebase-dynamic-links",
    firebaseMessaging   : "com.google.firebase:firebase-messaging",
    firebaseAds: "com.google.firebase:firebase-ads:22.6.0" //I thinl this is not related
  * Component version: '32.7.4' 
  * AGP version: '8.0 
     compileSdkVersion = 34
     buildToolsVersion = '34.0.0'
     targetSdkVersion = 33
     
     
Step 3: Describe the problem

I am getting this error on production for some devices. I could not reproduce it myself. But there are enough number of crash report in Crashlytics dashboard to worry. This happen after increasing firebase version 32.7.1 to 32.7.4.

**SessionsSettings.<clinit>
java.lang.IncompatibleClassChangeError - Class kotlinx.coroutines.JobSupport implements non-interface class kotlinx.coroutines.r (declaration of 'kotlinx.coroutines.JobSupport' appears in /data/app/com.lyrebirdst....**

Fatal Exception: java.lang.IncompatibleClassChangeError
Class kotlinx.coroutines.JobSupport implements non-interface class kotlinx.coroutines.r (declaration of 'kotlinx.coroutines.JobSupport' appears in /data/app/~~iYBbmLJScITu5OZXoGa2eQ==/com.lyrebirdstudio.cartoon-raB_7jOPgBq0pfGpwCev6w==/base.apk!classes4.dex)

Fatal Exception: java.lang.IncompatibleClassChangeError: Class kotlinx.coroutines.JobSupport implements non-interface class kotlinx.coroutines.r (declaration of 'kotlinx.coroutines.JobSupport' appears in /data/app/~~iYBbmLJScITu5OZXoGa2eQ==/com.lyrebirdstudio.cartoon-raB_7jOPgBq0pfGpwCev6w==/base.apk!classes4.dex)
       **at androidx.datastore.preferences.PreferenceDataStoreDelegateKt.a(PreferenceDataStoreDelegate.kt:1)**
       **at com.google.firebase.sessions.settings.SessionsSettings.<clinit>(SessionsSettings.kt:149)**
       at com.google.firebase.sessions.FirebaseSessionsRegistrar.getComponents$lambda-3(FirebaseSessionsRegistrar.kt:85)
       at com.google.firebase.tracing.ComponentMonitor.lambda$processRegistrar$0(ComponentMonitor.java:38)
       at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0(ComponentRuntime.java:160)
       at com.google.firebase.components.Lazy.get(Lazy.java:53)
       at com.google.firebase.components.ComponentContainer.get(ComponentContainer.java:48)
       at com.google.firebase.components.RestrictedComponentContainer.get(RestrictedComponentContainer.java:105)
       at com.google.firebase.sessions.FirebaseSessionsRegistrar.getComponents$lambda-0(FirebaseSessionsRegistrar.kt:51)
       at com.google.firebase.tracing.ComponentMonitor.lambda$processRegistrar$0(ComponentMonitor.java:38)
       at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0(ComponentRuntime.java:160)
       at com.google.firebase.components.Lazy.get(Lazy.java:53)
       at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents(ComponentRuntime.java:322)
       at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(ComponentRuntime.java:312)
       at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:607)
       at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:300)
       at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:264)
       at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:249)
       at com.google.firebase.provider.FirebaseInitProvider.onCreate(FirebaseInitProvider.java:69)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2388)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2358)
       at com.google.firebase.provider.FirebaseInitProvider.attachInfo(FirebaseInitProvider.java:61)
       at android.app.ActivityThread.installProvider(ActivityThread.java:7246)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:6787)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6704)
       at android.app.ActivityThread.access$1300(ActivityThread.java:237)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7664)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by lehcar09** [comment]
Hi @b-basoglu , thank you for reaching out and reporting the issue. I tried to replicate the issue, but, I was unsuccessful. 
There is a another issue (#5783) with almost similar stacktrace. Per checking with our Engr, this might be related to R8 full mode. Are you using the R8 full mode?

Is there any chance you share an MCVE to help us investigate the issue?

**Comment by b-basoglu** [comment]
Hi @lehcar09  I checked my gradle.properties

android.enableR8.fullMode = false

I could not reproduce it myself.

**Issue seems to be regressed in Crashlytics.** If the issue reoccur again I will write. You can close this issue on my side for now.

**Comment by lehcar09** [comment]
I understand. With that, I'll be closing this issue now. Let me know if we need to re-open the issue. Thanks!
