### ISSUE TITLE
java.lang.OutOfMemoryError: after updating to 32.7.4

### ISSUE THREAD

**Issue by LokeshHP** [firebase/firebase-android-sdk#5791]
Initially an issue was created for the StackOverflow exception in the thread  https://github.com/firebase/firebase-android-sdk/issues/5102

It was said that, issue was fixed in the latest version. But unfortunately,  on upgrading to the latest Firebase BOM 32.7.4 version, resulting into another exception with OutOfMemoryError.

java.lang.OutOfMemoryError: Failed to allocate a 335544336 byte allocation with 25149440 free bytes and 317MB until  OOM, target footprint 229033128, growth limit 536870912
at java.util.Arrays.copyOf(Arrays.java:3553)
at java.util.Arrays.copyOf(Arrays.java:3522)
at java.util.Vector.grow(Vector.java:262)
at java.util.Vector.grow(Vector.java:266)
at java.util.Vector.add(Vector.java:782)
at java.util.Vector.addElement(Vector.java:617)
at java.util.Stack.push(Stack.java:66)
at com.google.firebase.crashlytics.internal.stacktrace.TrimmedThrowableData.makeTrimmedThrowableData(TrimmedThrowableData.java:47)

**Comment by lehcar09** [comment]
Hi @LokeshHP, thank you for reaching out. I tried to reproduce the issue, but I was not successful. Is there any chance you could provide an MCVE to help us investigate the issue? Thanks.

**Comment by LokeshHP** [comment]
@lehcar09, I couldn't find time to create a MVCE and replicate this crash. But, it's still occurring on our project..
