### ISSUE TITLE
m.ky.onActivityCreated OOM

### ISSUE THREAD

**Issue by mikelhm** [firebase/firebase-android-sdk#5794]
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 8308486796 byte allocation with 4194304 free bytes and 479MB until OOM
       at android.util.ArrayMap.allocArrays(ArrayMap.java:203)
       at android.util.ArrayMap.ensureCapacity(ArrayMap.java:319)
       at android.os.BaseBundle.unparcel(BaseBundle.java:219)
       at android.os.BaseBundle.getString(BaseBundle.java:918)
       at m.ky.onActivityCreated(:com.google.android.gms.dynamite_measurementdynamite@240812005@24.08.12 (020406-0):44)
       at com.google.android.gms.measurement.internal.AppMeasurementDynamiteService.onActivityCreated(com.google.android.gms:play-services-measurement-sdk@@21.2.0:29)
       at m.cm.a(:com.google.android.gms.dynamite_measurementdynamite@240812005@24.08.12 (020406-0):131)
       at m.s.onTransact(:com.google.android.gms.dynamite_measurementdynamite@240812005@24.08.12 (020406-0):21)
       at android.os.Binder.transact(Binder.java:385)
       at com.google.android.gms.internal.measurement.zzbm.zzc(com.google.android.gms:play-services-measurement-base@@21.2.0:2)
       at com.google.android.gms.internal.measurement.zzca.onActivityCreated(com.google.android.gms:play-services-measurement-base@@21.2.0:5)
       at com.google.android.gms.internal.measurement.zzdx.zza(com.google.android.gms:play-services-measurement-sdk-api@@21.2.0:8)
       at com.google.android.gms.internal.measurement.zzdu.run(com.google.android.gms:play-services-measurement-sdk-api@@21.2.0:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

As the stack above, OOM cause by gms which use in firebase.

![image](https://github.com/firebase/firebase-android-sdk/assets/10327642/b5f615eb-bc0e-4a9e-8f50-4fb65cf33cf0)

 classpath 'com.google.firebase:firebase-crashlytics-gradle:2.8.1'
classpath 'com.google.gms:google-services:4.3.13'

how to fix this problem, can upgrade gms or firebase solve this problem??

**Comment by lehcar09** [comment]
Hi @mikelhm, thank you for reaching out. I tried reproducing the issue using, but I wasn't able to encounter the issue. I recommend updating the Crashytics Gradle version and GMS version to get the latest updates and bug fixes that might have been addressed. 

If the issue persists, can you share an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) to help us investigate the issue? Or could you try to reproduce the issue using our [quickstart app](https://github.com/firebase/quickstart-android/tree/master)? Thanks.
