### ISSUE TITLE
ANR com.google.firebase.perf.metrics.AppStartTrace.registerActivityLifecycleCallbacks

### ISSUE THREAD

**Issue by akshay92** [firebase/firebase-android-sdk#5822]
StackTrace:
main (runnable):tid=1 systid=2455 
       at kotlin.text.StringsKt__StringsKt.indexOf(Strings.kt:1)
       at kotlin.text.StringsKt__StringsJVMKt.replace(StringsJVM.kt:88)
       at kotlin.text.StringsKt__StringsJVMKt.replace$default(StringsKt__StringsJVM.kt:86)
       at androidx.lifecycle.Lifecycling.getAdapterName(Lifecycling.kt:176)
       at androidx.lifecycle.Lifecycling.generatedConstructor(Lifecycling.kt:92)
       at androidx.lifecycle.Lifecycling.resolveObserverCallbackType(Lifecycling.kt:128)
       at androidx.lifecycle.Lifecycling.getObserverConstructorType(Lifecycling.kt:118)
       at androidx.lifecycle.Lifecycling.lifecycleEventObserver(Lifecycling.kt:53)
       at androidx.lifecycle.LifecycleRegistry$ObserverWithState.<init>(LifecycleRegistry.java:307)
       at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.kt:176)
       at com.google.firebase.perf.metrics.AppStartTrace.registerActivityLifecycleCallbacks(AppStartTrace.java:212)
       at com.google.firebase.perf.FirebasePerfEarly.<init>(FirebasePerfEarly.java:50)
       at com.google.firebase.perf.FirebasePerfRegistrar.lambda$getComponents$0(FirebasePerfRegistrar.java:75)
       at com.google.firebase.tracing.ComponentMonitor.lambda$processRegistrar$0(ComponentMonitor.java:38)
       at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0(ComponentRuntime.java:140)
       at com.google.firebase.components.Lazy.get(Lazy.java:53)
       at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents(ComponentRuntime.java:302)
       at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(ComponentRuntime.java:292)
       at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:607)
       at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:300)
       at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:264)
       at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:249)
       at com.google.firebase.provider.FirebaseInitProvider.onCreate(FirebaseInitProvider.java:66)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2404)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2374)
       at com.google.firebase.provider.FirebaseInitProvider.attachInfo(FirebaseInitProvider.java:58)
       at android.app.ActivityThread.installProvider(ActivityThread.java:7500)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:7017)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6766)
       at android.app.ActivityThread.access$1500(ActivityThread.java:257)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2092)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7911)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
       
       firebase_bom = "32.7.2"

**Comment by argzdev** [comment]
Hey @akshay92, thanks for filing. I noticed that you've only supplied a stacktrace and firebase bom version, unfortunately we are unable to investigate this with very little information to go by. Could you file a new issue following our template? Those information(such as what Firebase product are you using, or steps to reproduce the issue) is crucial and will help speed up our process when conducting our initial investigation. I'll go ahead and close this. TIA!
