### ISSUE TITLE
Firestore  Uncaught exception in the SynchronizationContext. Panic! 

### ISSUE THREAD

**Issue by floriangbh** [firebase/firebase-android-sdk#5845]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 2023.2.1 Patch 1
  * Firebase Component: BOM 32.8.0 

#### Steps to reproduce:

Just trying to retrieve Firestore data when the user is authenticated and got an offline error `Failed to get document because the client is offline.`

FirebaseAuth works well, and the network is OK. 

```
2024-04-09 17:27:01.148  8000-8108  ManagedChannelImpl      com.***                E  [Channel<1>: (firestore.googleapis.com)] Uncaught exception in the SynchronizationContext. Panic!
                                                                                                    java.lang.NoSuchMethodError: No virtual method acceptResolvedAddresses(Lio/grpc/LoadBalancer$ResolvedAddresses;)Z in class Lio/grpc/LoadBalancer; or its super classes (declaration of 'io.grpc.LoadBalancer' appears in /data/app/~~WRU1-v6WmX8V-jpQSZI8QQ==/com.***-EfnO3mKIow2wC8g7XdBNuA==/base.apk!classes19.dex)
                                                                                                    	at io.grpc.internal.AutoConfiguredLoadBalancerFactory$AutoConfiguredLoadBalancer.tryAcceptResolvedAddresses(AutoConfiguredLoadBalancerFactory.java:142)
                                                                                                    	at io.grpc.internal.ManagedChannelImpl$NameResolverListener$1NamesResolved.run(ManagedChannelImpl.java:1848)
                                                                                                    	at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:94)
                                                                                                    	at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:126)
                                                                                                    	at io.grpc.internal.ManagedChannelImpl$NameResolverListener.onResult(ManagedChannelImpl.java:1862)
                                                                                                    	at io.grpc.internal.RetryingNameResolver$RetryingListener.onResult(RetryingNameResolver.java:98)
                                                                                                    	at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:333)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
2024-04-09 17:27:01.155  8000-8105  Firestore               com.***                 W  (24.11.0) [WatchStream]: (8a38cb6) Stream closed with status: Status{code=INTERNAL, description=Panic! This is a bug!, cause=java.lang.NoSuchMethodError: No virtual method acceptResolvedAddresses(Lio/grpc/LoadBalancer$ResolvedAddresses;)Z in class Lio/grpc/LoadBalancer; or its super classes (declaration of 'io.grpc.LoadBalancer' appears in /data/app/~~WRU1-v6WmX8V-jpQSZI8QQ==/com.***-EfnO3mKIow2wC8g7XdBNuA==/base.apk!classes19.dex)
                                                                                                    	at io.grpc.internal.AutoConfiguredLoadBalancerFactory$AutoConfiguredLoadBalancer.tryAcceptResolvedAddresses(AutoConfiguredLoadBalancerFactory.java:142)
                                                                                                    	at io.grpc.internal.ManagedChannelImpl$NameResolverListener$1NamesResolved.run(ManagedChannelImpl.java:1848)
                                                                                                    	at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:94)
                                                                                                    	at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:126)
                                                                                                    	at io.grpc.internal.ManagedChannelImpl$NameResolverListener.onResult(ManagedChannelImpl.java:1862)
                                                                                                    	at io.grpc.internal.RetryingNameResolver$RetryingListener.onResult(RetryingNameResolver.java:98)
                                                                                                    	at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:333)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    }.
2024-04-09 17:27:01.159  8000-8105  Firestore               com.***                  W  (24.11.0) [OnlineStateTracker]: Could not reach Cloud Firestore backend. Connection failed 1 times. Most recent error: Status{code=INTERNAL, description=Panic! This is a bug!, cause=java.lang.NoSuchMethodError: No virtual method acceptResolvedAddresses(Lio/grpc/LoadBalancer$ResolvedAddresses;)Z in class Lio/grpc/LoadBalancer; or its super classes (declaration of 'io.grpc.LoadBalancer' appears in /data/app/~~WRU1-v6WmX8V-jpQSZI8QQ==/com.****-EfnO3mKIow2wC8g7XdBNuA==/base.apk!classes19.dex)
                                                                                                    	at io.grpc.internal.AutoConfiguredLoadBalancerFactory$AutoConfiguredLoadBalancer.tryAcceptResolvedAddresses(AutoConfiguredLoadBalancerFactory.java:142)
                                                                                                    	at io.grpc.internal.ManagedChannelImpl$NameResolverListener$1NamesResolved.run(ManagedChannelImpl.java:1848)
                                                                                                    	at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:94)
                                                                                                    	at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:126)
                                                                                                    	at io.grpc.internal.ManagedChannelImpl$NameResolverListener.onResult(ManagedChannelImpl.java:1862)
                                                                                                    	at io.grpc.internal.RetryingNameResolver$RetryingListener.onResult(RetryingNameResolver.java:98)
                                                                                                    	at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:333)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    }
                                                                                                    This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.
2024-04-09 17:27:01.217  8000-8105  Firestore               com.***                 W  (24.11.0) [WatchStream]: (8a38cb6) Stream closed with status: Status{code=INTERNAL, description=Panic! This is a bug!, cause=java.lang.NoSuchMethodError: No virtual method acceptResolvedAddresses(Lio/grpc/LoadBalancer$ResolvedAddresses;)Z in class Lio/grpc/LoadBalancer; or its super classes (declaration of 'io.grpc.LoadBalancer' appears in /data/app/~~WRU1-v6WmX8V-jpQSZI8QQ==/com.***e-EfnO3mKIow2wC8g7XdBNuA==/base.apk!classes19.dex)
                                                                                                    	at io.grpc.internal.AutoConfiguredLoadBalancerFactory$AutoConfiguredLoadBalancer.tryAcceptResolvedAddresses(AutoConfiguredLoadBalancerFactory.java:142)
                                                                                                    	at io.grpc.internal.ManagedChannelImpl$NameResolverListener$1NamesResolved.run(ManagedChannelImpl.java:1848)
                                                                                                    	at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:94)
                                                                                                    	at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:126)
                                                                                                    	at io.grpc.internal.ManagedChannelImpl$NameResolverListener.onResult(ManagedChannelImpl.java:1862)
                                                                                                    	at io.grpc.internal.RetryingNameResolver$RetryingListener.onResult(RetryingNameResolver.java:98)
                                                                                                    	at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:333)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    }.
2024-04-09 17:27:09.905  8000-8105  Firestore               com.***                 W  (24.11.0) [WatchStream]: (8a38cb6) Stream closed with status: Status{code=INTERNAL, description=Panic! This is a bug!, cause=java.lang.NoSuchMethodError: No virtual method acceptResolvedAddresses(Lio/grpc/LoadBalancer$ResolvedAddresses;)Z in class Lio/grpc/LoadBalancer; or its super classes (declaration of 'io.grpc.LoadBalancer' appears in /data/app/~~WRU1-v6WmX8V-jpQSZI8QQ==/com.***-EfnO3mKIow2wC8g7XdBNuA==/base.apk!classes19.dex)
                                                                                                    	at io.grpc.internal.AutoConfiguredLoadBalancerFactory$AutoConfiguredLoadBalancer.tryAcceptResolvedAddresses(AutoConfiguredLoadBalancerFactory.java:142)
                                                                                                    	at io.grpc.internal.ManagedChannelImpl$NameResolverListener$1NamesResolved.run(ManagedChannelImpl.java:1848)
                                                                                                    	at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:94)
                                                                                                    	at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:126)
                                                                                                    	at io.grpc.internal.ManagedChannelImpl$NameResolverListener.onResult(ManagedChannelImpl.java:1862)
                                                                                                    	at io.grpc.internal.RetryingNameResolver$RetryingListener.onResult(RetryingNameResolver.java:98)
                                                                                                    	at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:333)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    }.
2024-04-09 17:27:09.918  8000-8000  com.***     com.***                  E  Failed to get document because the client is offline. com.google.firebase.firestore.FirebaseFirestoreException: Failed to get document because the client is offline.
                                                                                                    	at com.google.firebase.firestore.DocumentReference.lambda$getViaSnapshotListener$1(DocumentReference.java:331)
                                                                                                    	at com.google.firebase.firestore.DocumentReference$$ExternalSyntheticLambda2.onEvent(D8$$SyntheticClass:0)
                                                                                                    	at com.google.firebase.firestore.DocumentReference.lambda$addSnapshotListenerInternal$2$com-google-firebase-firestore-DocumentReference(DocumentReference.java:526)
                                                                                                    	at com.google.firebase.firestore.DocumentReference$$ExternalSyntheticLambda1.onEvent(D8$$SyntheticClass:0)
                                                                                                    	at com.google.firebase.firestore.core.AsyncEventListener.lambda$onEvent$0$com-google-firebase-firestore-core-AsyncEventListener(AsyncEventListener.java:42)
                                                                                                    	at com.google.firebase.firestore.core.AsyncEventListener$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
                                                                                                    	at androidx.media3.exoplayer.offline.DefaultDownloaderFactory$$ExternalSyntheticLambda0.execute(D8$$SyntheticClass:0)
                                                                                                    	at com.google.firebase.firestore.core.AsyncEventListener.onEvent(AsyncEventListener.java:39)
                                                                                                    	at com.google.firebase.firestore.core.QueryListener.raiseInitialEvent(QueryListener.java:196)
                                                                                                    	at com.google.firebase.firestore.core.QueryListener.onOnlineStateChanged(QueryListener.java:127)
                                                                                                    	at com.google.firebase.firestore.core.EventManager.handleOnlineStateChange(EventManager.java:259)
                                                                                                    	at com.google.firebase.firestore.core.SyncEngine.handleOnlineStateChange(SyncEngine.java:422)
                                                                                                    	at com.google.firebase.firestore.core.MemoryComponentProvider$RemoteStoreCallback.handleOnlineStateChange(MemoryComponentProvider.java:145)
                                                                                                    	at com.google.firebase.firestore.remote.RemoteStore$$ExternalSyntheticLambda1.handleOnlineStateChange(D8$$SyntheticClass:0)
                                                                                                    	at com.google.firebase.firestore.remote.OnlineStateTracker.setAndBroadcastState(OnlineStateTracker.java:181)
                                                                                                    	at com.google.firebase.firestore.remote.OnlineStateTracker.handleWatchStreamFailure(OnlineStateTracker.java:154)
                                                                                                    	at com.google.firebase.firestore.remote.RemoteStore.handleWatchStreamClose(RemoteStore.java:509)
                                                                                                    	at com.google.firebase.firestore.remote.RemoteStore.access$200(RemoteStore.java:60)
                                                                                                    	at com.google.firebase.firestore.remote.RemoteStore$1.onClose(RemoteStore.java:188)
                                                                                                    	at com.google.firebase.firestore.remote.AbstractStream.close(AbstractStream.java:356)
                                                                                                    	at com.google.firebase.firestore.remote.AbstractStream.handleServerClose(AbstractStream.java:410)
                                                                                                    	at com.google.firebase.firestore.remote.AbstractStream$StreamObserver.lambda$onClose$3$com-google-firebase-firestore-remote-AbstractStream$StreamObserver(AbstractStream.java:151)
                                                                                                    	at com.google.firebase.firestore.remote.AbstractStream$StreamObserver$$ExternalSyntheticLambda3.run(D8$$SyntheticClass:0)
                                                                                                    	at com.google.firebase.firestore.remote.AbstractStream$CloseGuardedRunner.run(AbstractStream.java:67)
                                                                                                    	at com.google.firebase.firestore.remote.AbstractStream$StreamObserver.onClose(AbstractStream.java:137)
                                                                                                    	at com.google.firebase.firestore.remote.FirestoreChannel$1.onClose(FirestoreChannel.java:151)
                                                                                                    	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:567)
                                                                                                    	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:71)
                                                                                                    	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:735)
                                                                                                    	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:716)
                                                                                                    	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
                                                                                                    	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
                                                                                                    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
                                                                                                    	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
2024-04-09 17:27:09.918  8000-8000  com.***     com.***             E  	at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:235)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
2024-04-09 17:27:09.919  8000-8105  Firestore               com.***             W  (24.11.0) [WatchStream]: (8a38cb6) Stream closed with status: Status{code=INTERNAL, description=Panic! This is a bug!, cause=java.lang.NoSuchMethodError: No virtual method acceptResolvedAddresses(Lio/grpc/LoadBalancer$ResolvedAddresses;)Z in class Lio/grpc/LoadBalancer; or its super classes (declaration of 'io.grpc.LoadBalancer' appears in /data/app/~~WRU1-v6WmX8V-jpQSZI8QQ==/com.***-EfnO3mKIow2wC8g7XdBNuA==/base.apk!classes19.dex)
                                                                                                    	at io.grpc.internal.AutoConfiguredLoadBalancerFactory$AutoConfiguredLoadBalancer.tryAcceptResolvedAddresses(AutoConfiguredLoadBalancerFactory.java:142)
                                                                                                    	at io.grpc.internal.ManagedChannelImpl$NameResolverListener$1NamesResolved.run(ManagedChannelImpl.java:1848)
                                                                                                    	at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:94)
                                                                                                    	at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:126)
                                                                                                    	at io.grpc.internal.ManagedChannelImpl$NameResolverListener.onResult(ManagedChannelImpl.java:1862)
                                                                                                    	at io.grpc.internal.RetryingNameResolver$RetryingListener.onResult(RetryingNameResolver.java:98)
                                                                                                    	at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:333)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    }.
```
#### Relevant Code:

Code to retrieve objects in the database : 
```kotlin
suspend fun getUser(uuid: String): Result<User?> {
        val collection = firestore.collection("Users")
        val userRef = collection.document(uuid)
        return try {
            val snapshot = userRef.get().await()
            val user = snapshot.toObject<User>()
            Success(user)
        } catch (e: FirebaseFirestoreException) {
            Timber.e(e)
            Error(null, e.localizedMessage)
        }
    }
```

Gradle file : 
```
// Firebase
    implementation(platform("com.google.firebase:firebase-bom:32.8.0")) // Update this version to update all firebase dependencies
    implementation 'com.google.firebase:firebase-analytics'
    implementation 'com.google.firebase:firebase-auth'
    implementation 'com.google.firebase:firebase-firestore'
    implementation 'com.google.firebase:firebase-functions'
    implementation 'com.google.firebase:firebase-crashlytics'
    implementation 'com.google.firebase:firebase-storage:'
    implementation 'com.google.firebase:firebase-config'
```

The issue appears after the project update to compileSdk 34, gradle 8.4 and Kotlin 1.9.23.

I've tried some solutions for this SO : https://stackoverflow.com/questions/65927977/android-realtime-database-throws-error-client-is-offline-but-its-not
But without success!

Any idea how to fix it? 

Thanks

**Comment by MarkDuckworth** [comment]
The NoSuchMethodError(s) indicate that you may have an issue with your dependencies. [This thread](https://stackoverflow.com/questions/59880287/nosuchmethodexception-and-noclassdeffounderror-in-grpc-protobuf-java) it a little old, but it may get you on the right path for resolving the issue.

**Comment by floriangbh** [comment]
Thanks for the feedback @MarkDuckworth ! 

I found this : 

```
com.google.http-client:google-http-client-gson:1.44.1 -> 
 +--- io.grpc:grpc-context:1.60.1
|    |    +--- io.opencensus:opencensus-api:0.31.1
|    |    |    \--- io.grpc:grpc-context:1.27.2 -> 1.60.1

+--- com.google.firebase:firebase-firestore -> 24.11.0
|    +--- io.grpc:grpc-android:1.57.2
|    |    \--- io.grpc:grpc-core:1.57.2
|    |         \--- io.grpc:grpc-api:1.57.2 -> 1.60.1
|    |              +--- com.google.code.findbugs:jsr305:3.0.2
|    |              \--- com.google.errorprone:error_prone_annotations:2.20.0 -> 2.23.0
|    +--- io.grpc:grpc-okhttp:1.57.2
|    |    \--- io.grpc:grpc-core:1.57.2 (*)
|    +--- io.grpc:grpc-protobuf-lite:1.57.2
|    |    +--- io.grpc:grpc-api:1.57.2 -> 1.60.1 (*)
|    |    \--- com.google.protobuf:protobuf-javalite:3.22.3
|    +--- io.grpc:grpc-stub:1.57.2
|    |    +--- io.grpc:grpc-api:1.57.2 -> 1.60.1 (*)
|    |    \--- com.google.guava:guava:32.0.1-android (*)

+--- io.grpc:grpc-android:{strictly 1.57.2} -> 1.57.2 (c)
+--- io.grpc:grpc-okhttp:{strictly 1.57.2} -> 1.57.2 (c)
+--- io.grpc:grpc-protobuf-lite:{strictly 1.57.2} -> 1.57.2 (c)
+--- io.grpc:grpc-stub:{strictly 1.57.2} -> 1.57.2 (c)
+--- io.grpc:grpc-core:{strictly 1.57.2} -> 1.57.2 (c)
+--- io.grpc:grpc-api:{strictly 1.60.1} -> 1.60.1 (c)
+--- io.grpc:grpc-context:{strictly 1.60.1} -> 1.60.1 (c)
```

But I'm not unable to find what's wrong :(

**Comment by floriangbh** [comment]
Fixed with : 

```
// Temporary fix to avoid runtime error with firebase storage
configurations.configureEach {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        if (details.requested.group == 'io.grpc') {
            details.useVersion '1.57.2' // specify a consistent version
        }
    }
}
```
