### ISSUE TITLE
Firebase Realtime Remote Config Connection is Causing ANR during Background Launch

### ISSUE THREAD

**Issue by dhruvkaushal11** [firebase/firebase-android-sdk#5883]
Hi Team, we are facing issue while using Firebase realtime remote config is causing an ANR when app launches in 100% Background Launch( SMS Broadcast, Worker)

**We are using 21.4.0 version for Remote Config, and we have written a realtime listener in our application onCreate.**
(Reason for writing in application oncreate() is we should get latest value for any Background worker configuration)

As per documentation it says:

> Although you can manually stop listening for updates, it's often not necessary. Real-time Remote Config automatically stops listening for updates when the app enters the background and restarts when the app is foregrounded.

```
main (runnable):tid=1 systid=17124 
       at com.google.firebase.concurrent.DelegatingScheduledExecutorService.schedule(DelegatingScheduledExecutorService.java:109)
       at com.google.firebase.remoteconfig.internal.ConfigRealtimeHttpClient.makeRealtimeHttpConnection(ConfigRealtimeHttpClient.java:351)
       at com.google.firebase.remoteconfig.internal.ConfigRealtimeHttpClient.startHttpConnection(ConfigRealtimeHttpClient.java:329)
       at com.google.firebase.remoteconfig.internal.ConfigRealtimeHandler.beginRealtime(ConfigRealtimeHandler.java:81)
       at com.google.firebase.remoteconfig.internal.ConfigRealtimeHandler.addRealtimeConfigUpdateListener(ConfigRealtimeHandler.java:89)
       at com.google.firebase.remoteconfig.FirebaseRemoteConfig.addOnConfigUpdateListener(FirebaseRemoteConfig.java:569)
       at net.prod.india.appManager.AppManager.init(AppManager.java:1514)
       at net.prod.india.app.CJRJarvisApplication.initializeModules(CJRJarvisApplication.java:604)
``` 
<img width="1157" alt="image" src="https://github.com/firebase/firebase-android-sdk/assets/16204255/216d0583-73da-4ac6-ba4a-b53f8820061e">

**Comment by lehcar09** [comment]
Hi @dhruvkaushal11, thank you for reaching out. I tried reproducing the issue, but I was unable to encounter the issue. I also tried, running on Android 11, however, I still wasn't able to replicate the issue. Is there any chance you could share an MCVE to help us investigate the issue? or, If you're unable to provide one, can you try our [quickstart app](https://github.com/firebase/quickstart-android/tree/master) and see if you can reproduce the issue?
