### ISSUE TITLE
App crash while launch

### ISSUE THREAD

**Issue by clunyes** [firebase/firebase-android-sdk#5934]
App will crash while launch in device MRD-AL00 android 9.0
```
Failed to find provider info for com.google.android.gsf.gservices
FATAL EXCEPTION: main
Process: com.google.android.gms.persistent, PID: 6033
java.lang.RuntimeException: Unable to create application co.g.App: java.lang.SecurityException: addOnPermissionsChangeListener: Neither user 10172 nor current process has android.permission.OBSERVE_GRANT_REVOKE_PERMISSIONS.
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6737)
	at android.app.ActivityThread.access$2000(ActivityThread.java:273)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2020)
	at android.os.Handler.dispatchMessage(Handler.java:112)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
Caused by: java.lang.SecurityException: addOnPermissionsChangeListener: Neither user 10172 nor current process has android.permission.OBSERVE_GRANT_REVOKE_PERMISSIONS.
	at android.os.Parcel.createException(Parcel.java:1959)
	at android.os.Parcel.readException(Parcel.java:1927)
	at android.os.Parcel.readException(Parcel.java:1877)
	at android.content.pm.IPackageManager$Stub$Proxy.addOnPermissionsChangeListener(IPackageManager.java:6303)
	at android.app.ApplicationPackageManager.addOnPermissionsChangeListener(ApplicationPackageManager.java:1600)
	at swc.a(:com.google.android.gms@19831019@19.8.31 (040400-284611645):12)
	at sfl.onCreate(:com.google.android.gms@19831019@19.8.31 (040400-284611645):167)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1162)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6717)
	... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
	at android.app.ContextImpl.enforce(ContextImpl.java:2046)
	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2074)
	at com.android.server.pm.PackageManagerService.addOnPermissionsChangeListener(PackageManagerService.java:6312)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2357)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4535)
Killing 5925:comxxxx.xxxxx/u0a325 (adj 0): depends on provider com.google.android.gms/.chimera.container.GmsModuleProvider in dying proc com.google.android.gms.persistent (adj 0)
```
```
classpath 'com.google.gms:google-services:4.3.15'
```
firebase version

    api(platform("com.google.firebase:firebase-bom:32.3.1"))
    api 'com.google.firebase:firebase-analytics-ktx'
    api 'com.google.firebase:firebase-messaging-ktx'

anyway to adapt this phone?

**Comment by lehcar09** [comment]
Hi @clunyes, thank you for reaching out. We're you able to reproduce the issue? Is there any chance you can share an MCVE/ code snippet to help us investigate the issue?

I notice that you're not using the latest Firebase SDK version. I would recommend updating to the [latest Firebase SDK version](https://firebase.google.com/support/release-notes/android) to have the latest bug fixes that might be causing the issue and features. 

Aside from that, I also recommend that you [migrate your app to use KTX APIs from the main modules](https://firebase.google.com/docs/android/kotlin-migration#ktx-apis-to-main-how-to-migrate) to ensure that you continue to get fixes and can take advantage of changes and new features when the KTX modules are no longer released. For context,  the Kotlin extension (KTX) APIs in the KTX modules were deprecated. The Kotlin extensions (KTX) APIs were added to their respective main modules. You can now use the KTX APIs directly from the main modules when using [Firebase BoM v32.5.0+](https://firebase.google.com/support/release-notes/android#bom_v32-5-0) or main module versions listed in BoM v32.5.0+.

**Comment by clunyes** [comment]
> reaching out

ok，i'll have a try soon

**Comment by clunyes** [comment]
> Hi @clunyes, thank you for reaching out. We're you able to reproduce the issue? Is there any chance you can share an MCVE/ code snippet to help us investigate the issue?
> 
> I notice that you're not using the latest Firebase SDK version. I would recommend updating to the [latest Firebase SDK version](https://firebase.google.com/support/release-notes/android) to have the latest bug fixes that might be causing the issue and features.
> 
> Aside from that, I also recommend that you [migrate your app to use KTX APIs from the main modules](https://firebase.google.com/docs/android/kotlin-migration#ktx-apis-to-main-how-to-migrate) to ensure that you continue to get fixes and can take advantage of changes and new features when the KTX modules are no longer released. For context, the Kotlin extension (KTX) APIs in the KTX modules were deprecated. The Kotlin extensions (KTX) APIs were added to their respective main modules. You can now use the KTX APIs directly from the main modules when using [Firebase BoM v32.5.0+](https://firebase.google.com/support/release-notes/android#bom_v32-5-0) or main module versions listed in BoM v32.5.0+.



> Hi @clunyes, thank you for reaching out. We're you able to reproduce the issue? Is there any chance you can share an MCVE/ code snippet to help us investigate the issue?
> 
> I notice that you're not using the latest Firebase SDK version. I would recommend updating to the [latest Firebase SDK version](https://firebase.google.com/support/release-notes/android) to have the latest bug fixes that might be causing the issue and features.
> 
> Aside from that, I also recommend that you [migrate your app to use KTX APIs from the main modules](https://firebase.google.com/docs/android/kotlin-migration#ktx-apis-to-main-how-to-migrate) to ensure that you continue to get fixes and can take advantage of changes and new features when the KTX modules are no longer released. For context, the Kotlin extension (KTX) APIs in the KTX modules were deprecated. The Kotlin extensions (KTX) APIs were added to their respective main modules. You can now use the KTX APIs directly from the main modules when using [Firebase BoM v32.5.0+](https://firebase.google.com/support/release-notes/android#bom_v32-5-0) or main module versions listed in BoM v32.5.0+.

i'll try tomorro，thanks
