### ISSUE TITLE
java.lang.IllegalArgumentException: Service not registered

### ISSUE THREAD

**Issue by matteinn** [firebase/firebase-android-sdk#5947]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: N/A
  * Firebase Component: Sessions
  * Component version: BoM 32.8.1

### [REQUIRED] Step 3: Describe the problem

I'm seeing this new crash when using Firebase BoM 32.8.1, 100% of occurrences happen when the app is in background (info taken from Crashlytics).
I'm not using Firebase Sessions directly, I guess it's implicit through Crashlytics or Analytics or Remote Config which I use.

```
Fatal Exception: java.lang.IllegalArgumentException: Service not registered: uq.g0$d@c952b90
       at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1494)
       at android.app.ContextImpl.unbindService(ContextImpl.java:1673)
       at android.content.ContextWrapper.unbindService(ContextWrapper.java:703)
       at com.google.firebase.sessions.SessionLifecycleServiceBinderImpl.bindToService(SessionLifecycleServiceBinder.kt:58)
       at com.google.firebase.sessions.SessionLifecycleClient.bindToService(SessionLifecycleClient.kt:105)
       at com.google.firebase.sessions.FirebaseSessions$1.invokeSuspend(FirebaseSessions.kt:54)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at com.google.firebase.concurrent.CustomThreadFactory.lambda$newThread$0(CustomThreadFactory.java:47)
       at java.lang.Thread.run(Thread.java:764)
```

#### Steps to reproduce:

Unknown

#### Relevant Code:

N/A

**Comment by lehcar09** [comment]
HI @matteinn, thank you for reaching out and reporting the issue. The Firebase Session is used by Crashlytics and Performance internally to measure sessions. We have addressed the issue and the fix (#5884) has been included in the latest Firebase SDK release [version 33.0.0](https://firebase.google.com/support/release-notes/android#bom_v33-0-0). I suggest updating to the latest Firebase SDK version 33.0.0 to get the latest bug fixes.

That said, I'll close the issue for now. Let me know if there's any misunderstanding or we need to reopen the issue for further investigation. Thanks!
