### ISSUE TITLE
[Crash] java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.IllegalArgumentException: Wrong number of arguments; expected 0, got 1 (on Huawei with Android 9, 10)

### ISSUE THREAD

**Issue by kurosaki-tisak** [firebase/firebase-android-sdk#6059]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: _____
  * Firebase Component: `com.google.firebase:firebase-perf`
  * Component version: `com.google.firebase:firebase-bom:33.1.1` (Reproduced since `com.google.firebase:firebase-bom:33.0.0`)

### [REQUIRED] Step 3: Describe the problem
Stack trace:
```
FATAL EXCEPTION: main
Process: com.xxx.xxx, PID: 10249
java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.IllegalArgumentException: Wrong number of arguments; expected 0, got 1
   at android.app.ActivityThread.installProvider(ActivityThread.java:7278)
   at android.app.ActivityThread.installContentProviders(ActivityThread.java:6813)
   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6699)
   at android.app.ActivityThread.access$2000(ActivityThread.java:273)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2020)
   at android.os.Handler.dispatchMessage(Handler.java:112)
   at android.os.Looper.loop(Looper.java:216)
   at android.app.ActivityThread.main(ActivityThread.java:7625)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
Caused by: java.lang.IllegalArgumentException: Wrong number of arguments; expected 0, got 1
   at java.lang.reflect.Method.invoke(Native Method)
   at eiD$TaskDescription.M0s8NeYn(:69)
   at eiD$TaskDescription.N(:1)
   at eiD$TaskDescription.invoke(:65354)
   at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
   at $Proxy3.getRunningAppProcesses(Unknown Source)
   at android.app.ActivityManager.getRunningAppProcesses(ActivityManager.java:3453)
   at com.google.firebase.perf.metrics.AppStartTrace.isAnyAppProcessInForeground(:506)
   at com.google.firebase.perf.metrics.AppStartTrace.registerActivityLifecycleCallbacks(:216)
   at com.google.firebase.perf.FirebasePerfEarly.<init>(:50)
   at com.google.firebase.perf.FirebasePerfRegistrar.lambda$getComponents$0(:75)
   at com.google.firebase.perf.FirebasePerfRegistrar$$ExternalSyntheticLambda1.create(:65353)
   at com.google.firebase.tracing.ComponentMonitor.lambda$processRegistrar$0(:38)
   at com.google.firebase.tracing.ComponentMonitor$$ExternalSyntheticLambda0.create(:65353)
   at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0$com-google-firebase-components-ComponentRuntime(:160)
   at com.google.firebase.components.ComponentRuntime$$ExternalSyntheticLambda1.get(:65353)
   at com.google.firebase.components.Lazy.get(:53)
   at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents(:322)
   at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(:312)
   at com.google.firebase.FirebaseApp.initializeAllApis(:607)
   at com.google.firebase.FirebaseApp.initializeApp(:300)
   at com.google.firebase.FirebaseApp.initializeApp(:264)
   at com.google.firebase.FirebaseApp.initializeApp(:249)
   at com.google.firebase.provider.FirebaseInitProvider.onCreate(:135)
   at android.content.ContentProvider.attachInfo(ContentProvider.java:1949)
   at android.content.ContentProvider.attachInfo(ContentProvider.java:1923)
   at com.google.firebase.provider.FirebaseInitProvider.attachInfo(:61)
   at android.app.ActivityThread.installProvider(ActivityThread.java:7273)
   ... 10 more
Error reporting crash
java.lang.IllegalArgumentException: Wrong number of arguments; expected 2, got 1
   at java.lang.reflect.Method.invoke(Native Method)
   at eiD$TaskDescription.M0s8NeYn(:69)
   at eiD$TaskDescription.N(:1)
   at eiD$TaskDescription.invoke(:65354)
   at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
   at $Proxy3.handleApplicationCrash(Unknown Source)
   at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:173)
   at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
   at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
   at java.lang.Thread.dispatchUncaughtException(Thread.java:1975)
   ```

#### Steps to reproduce:

1. [Add Firebase Perf to project](https://firebase.google.com/docs/perf-mon/get-started-android?hl=en).
2. Open the app.
3. Crash occurs.

Be able to reproduce on the device list as follows;
- Huawei Mate 30 Pro with EMUI 10.0 (Android Q)
- Huawei P20 with EMUI 9.0 (Android P)
- Huawei M5 pro with EMUI 9.1.0 (Android P)

**Comment by lehcar09** [comment]
Hi @kurosaki-tisak, thank you for reaching out. I tried reproducing the issue with an emulator with the same API level, however I did not encounter the issue. Can you share an MCVE to help us investigate the issue?

The `FirebaseInitProvider` is responsible for calling [FirebaseApp.initializeApp](https://firebase.google.com/docs/reference/android/com/google/firebase/FirebaseApp.html#initializeApp(android.content.Context)) in order to initialize the default FirebaseApp instance using the configurations from the project’s [google-services.json file](https://developers.google.com/android/guides/google-services-plugin).

Are you referencing to multiple Firebase projects in one app and initializing the other FirebaseApp instances?
