### ISSUE TITLE
 java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.google.firebase.perf.internal.FeatureControl.zzag()' on a null object reference

### ISSUE THREAD

**Issue by MichaelJokAr** [firebase/firebase-android-sdk#6066]
crash on version 19.0.0

#### Relevant Code:

```
  Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.google.firebase.perf.internal.FeatureControl.zzag()' on a null object reference
       at com.google.firebase.perf.internal.zzc.zzb(com.google.firebase:firebase-perf@@19.0.0:174)
       at com.google.firebase.perf.internal.zzc.zza(com.google.firebase:firebase-perf@@19.0.0:215)
       at com.google.firebase.perf.internal.zzh.run(com.google.firebase:firebase-perf@@19.0.0:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
        
```

**Comment by lehcar09** [comment]
Hi @MichaelJokAr, thank you for reaching out. The version you shared was [released on Aug 8, 2019](https://firebase.google.com/support/release-notes/android#2019-08-16). Currently, the [latest version of Firebase Perf is 21.0.1](https://firebase.google.com/support/release-notes/android#latest_sdk_versions). 

I suggest try reproducing the issue using the [latest SDK version](https://firebase.google.com/support/release-notes/android#latest_sdk_versions) to have the latest bug fixes. If the issue persists, 
please file a new issue thread with the complete details regarding the specific bug and issue that you're referring to so that we may assist you properly. These information will be helpful for us to conduct an initial investigation. Thanks!
