### ISSUE TITLE
Error after building the firestore sdk in grpc

### ISSUE THREAD

**Issue by MrLibya** [firebase/firebase-android-sdk#6088]
Hello, This is not actually bug report but I was trying to debug something in Firestore sdk, I updated the code and build and added to aar to fresh project and getting this error:

in my build gradle:

```gradle
dependencies {
    implementation("com.google.firebase:protolite-well-known-types:18.0.0")
    implementation("com.google.android.gms:play-services-gcm:17.0.0")
    implementation ("com.android.support:multidex:1.0.3")
    implementation(platform("com.google.firebase:firebase-bom:33.1.1"))
    implementation("com.google.firebase:firebase-components:18.0.0")
    implementation("com.google.firebase:firebase-auth:23.0.0")
    implementation("com.google.firebase:firebase-database:21.0.0")

    implementation("io.grpc:grpc-stub:1.65.0")
    implementation("io.grpc:grpc-protobuf-lite:1.65.0")
    implementation("io.grpc:grpc-okhttp:1.65.0")
    compileOnly("org.apache.tomcat:annotations-api:6.0.53")

//    implementation(files("libs/firebase-common-release.aar"))
    implementation(files("libs/firebase-firestore-release.aar"))
}
```

but app crashes with log:

```
Process: com.example.myapplication, PID: 20297
                                                                                                    java.lang.RuntimeException: Internal error in Cloud Firestore (25.0.1).
                                                                                                    	at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$3(AsyncQueue.java:545)
                                                                                                    	at com.google.firebase.firestore.util.AsyncQueue$$ExternalSyntheticLambda6.run(Unknown Source:2)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    Caused by: com.google.android.gms.tasks.RuntimeExecutionException: java.lang.RuntimeException: java.lang.NoClassDefFoundError: Failed resolution of: Lio/grpc/android/AndroidChannelBuilder;
                                                                                                    	at com.google.android.gms.tasks.zzw.getResult(com.google.android.gms:play-services-tasks@@18.1.0:3)
                                                                                                    	at com.google.firebase.firestore.remote.FirestoreChannel.lambda$runBidiStreamingRpc$0$com-google-firebase-firestore-remote-FirestoreChannel(FirestoreChannel.java:138)
                                                                                                    	at com.google.firebase.firestore.remote.FirestoreChannel$$ExternalSyntheticLambda2.onComplete(Unknown Source:6)
                                                                                                    	at com.google.android.gms.tasks.zzi.run(com.google.android.gms:play-services-tasks@@18.1.0:1)
                                                                                                    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
                                                                                                    	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                                                    	at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:235)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: java.lang.RuntimeException: java.lang.NoClassDefFoundError: Failed resolution of: Lio/grpc/android/AndroidChannelBuilder;
                                                                                                    	at com.google.android.gms.tasks.zzz.run(com.google.android.gms:play-services-tasks@@18.1.0:2)
                                                                                                    	at com.google.firebase.firestore.util.ThrottledForwardingExecutor.lambda$execute$0$com-google-firebase-firestore-util-ThrottledForwardingExecutor(ThrottledForwardingExecutor.java:54)
                                                                                                    	at com.google.firebase.firestore.util.ThrottledForwardingExecutor$$ExternalSyntheticLambda0.run(Unknown Source:4)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012) 
                                                                                                    Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lio/grpc/android/AndroidChannelBuilder;
                                                                                                    	at com.google.firebase.firestore.remote.GrpcCallProvider.initChannel(GrpcCallProvider.java:114)
                                                                                                    	at com.google.firebase.firestore.remote.GrpcCallProvider.lambda$initChannelTask$6$com-google-firebase-firestore-remote-GrpcCallProvider(GrpcCallProvider.java:242)
                                                                                                    	at com.google.firebase.firestore.remote.GrpcCallProvider$$ExternalSyntheticLambda1.call(Unknown Source:2)
                                                                                                    	at com.google.android.gms.tasks.zzz.run(com.google.android.gms:play-services-tasks@@18.1.0:1)
                                                                                                    	at com.google.firebase.firestore.util.ThrottledForwardingExecutor.lambda$execute$0$com-google-firebase-firestore-util-ThrottledForwardingExecutor(ThrottledForwardingExecutor.java:54) 
                                                                                                    	at com.google.firebase.firestore.util.ThrottledForwardingExecutor$$ExternalSyntheticLambda0.run(Unknown Source:4) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) 
                                                                                                    	at java.lang.Thread.run(Thread.java:1012) 
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "io.grpc.android.AndroidChannelBuilder" on path: DexPathList[[zip file "/data/app/~~K8cfcog1xOnJLckOUD8S5g==/com.example.myapplication-jy_j2F9QcUeuamDh9v5bpw==/base.apk"],nativeLibraryDirectories=[/data/app/~~K8cfcog1xOnJLckOUD8S5g==/com.example.myapplication-jy_j2F9QcUeuamDh9v5bpw==/lib/arm64, /system/lib64, /system_ext/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
```

What I don't understand is that I keep getting missing class and I manually add them to `dependencies`, Aren't those should be auto loaded in the Firestore sdk ? Or am I missing something here ?

**Comment by MarkDuckworth** [comment]
@daymxn, is this something you can provide guidance on?

**Comment by MrLibya** [comment]
Update: I was able to run it with some more implementation of dependencies:

```gradle
dependencies {
    constraints {
        implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.0") {
            because("kotlin-stdlib-jdk7 is now a part of kotlin-stdlib")
        }
        implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.0") {
            because("kotlin-stdlib-jdk8 is now a part of kotlin-stdlib")
        }
    }
    implementation("androidx.appcompat:appcompat:1.6.1")
    implementation("com.google.android.material:material:1.9.0")
    implementation("androidx.constraintlayout:constraintlayout:2.1.4")
    implementation("androidx.navigation:navigation-fragment:2.6.0")
    implementation("androidx.navigation:navigation-ui:2.6.0")
    testImplementation("junit:junit:4.13.2")
    androidTestImplementation("androidx.test.ext:junit:1.1.5")
    androidTestImplementation("androidx.test.espresso:espresso-core:3.5.1")

    implementation("com.google.firebase:protolite-well-known-types:18.0.0")
    implementation("com.google.android.gms:play-services-gcm:17.0.0")
    implementation ("com.android.support:multidex:1.0.3")
    implementation(platform("com.google.firebase:firebase-bom:33.1.1"))
    implementation("com.google.firebase:firebase-components:18.0.0")
    implementation("com.google.firebase:firebase-auth:23.0.0")
    implementation("com.google.firebase:firebase-database:21.0.0")

    implementation("io.grpc:grpc-stub:1.65.0")
    implementation("io.grpc:grpc-protobuf-lite:1.65.0")
    implementation("io.grpc:grpc-okhttp:1.65.0")
    implementation("io.grpc:grpc-android:1.65.0")
    compileOnly("org.apache.tomcat:annotations-api:6.0.53")

//    implementation(files("libs/firebase-common-release.aar"))
    implementation(files("libs/firebase-firestore-release.aar"))
}
```

With this I was able to run it, So this should be ok now but still I don't understand why I had to implement all of those dependencies ?
