### ISSUE TITLE
[Crash] Caused by java.lang.SecurityException: Package android does not belong to 10307...at com.google.firebase.firestore.remote.AndroidConnectivityMonitor.configureNetworkMonitoring(AndroidConnectivityMonitor.java:87)

### ISSUE THREAD

**Issue by kurosaki-tisak** [firebase/firebase-android-sdk#6117]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: _____
  * Firebase Component: `com.google.firebase:firebase-firestore`
  * Component version: `com.google.firebase:firebase-bom:33.1.1`

#### Steps to reproduce:

Stack trace:

```
Fatal Exception: java.lang.RuntimeException: Internal error in Cloud Firestore (25.0.0).
       at com.google.firebase.firestore.util.AsyncQueue$$ExternalSyntheticLambda6.run(D8$$SyntheticClass:65353)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:264)
       at android.app.ActivityThread.main(ActivityThread.java:8258)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

Caused by java.lang.RuntimeException: java.lang.SecurityException: Package android does not belong to 10307
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$$ExternalSyntheticLambda2.run(D8$$SyntheticClass:65353)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:235)
       at java.lang.Thread.run(Thread.java:923)

Caused by java.lang.SecurityException: Package android does not belong to 10307
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2389)
       at android.os.Parcel.createException(Parcel.java:2373)
       at android.os.Parcel.readException(Parcel.java:2356)
       at android.os.Parcel.readException(Parcel.java:2298)
       at android.net.IConnectivityManager$Stub$Proxy.requestNetwork(IConnectivityManager.java:3820)
       at android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:3780)
       at android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:4283)
       at android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:4250)
       at com.google.firebase.firestore.remote.AndroidConnectivityMonitor.configureNetworkMonitoring(AndroidConnectivityMonitor.java:87)
       at com.google.firebase.firestore.remote.AndroidConnectivityMonitor.<init>(AndroidConnectivityMonitor.java:64)
       at com.google.firebase.firestore.core.MemoryComponentProvider.createConnectivityMonitor(MemoryComponentProvider.java:68)
       at com.google.firebase.firestore.core.ComponentProvider.initialize(ComponentProvider.java:152)
       at com.google.firebase.firestore.core.FirestoreClient.initialize(FirestoreClient.java:296)
       at com.google.firebase.firestore.core.FirestoreClient$$ExternalSyntheticLambda14.run(D8$$SyntheticClass:65353)
       at com.google.firebase.firestore.util.AsyncQueue$$ExternalSyntheticLambda0.call(D8$$SyntheticClass:65353)
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$$ExternalSyntheticLambda2.run(D8$$SyntheticClass:65353)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:235)
       at java.lang.Thread.run(Thread.java:923
```

Steps to reproduce:
- Open the app.
- Crash occurs.

Be able to reproduce on the device list as follows;
- Oppo RMX3231 (Android 11)
- Realme C21-Y (Android 11)
- Vivo 1906 (Android 11)
- Galaxy S20 FE 5G (Android 11)
- Redmi Note 8 (Android 11)

**Comment by lehcar09** [comment]
Hi @kurosaki-tisak, thank you for reaching out and reporting the issue. I tried reproducing the issue using another device but with similar API version (11), however, I did not encounter the issue. 

Can you reproduce this somewhat consistently? If possible can you share an MCVE that can help us investigate the issue? Thanks!

**Comment by mar3kk** [comment]
I think this might be because of the issue in the platform https://issuetracker.google.com/issues/175055271

**Comment by lehcar09** [comment]
Hi @kurosaki-tisak, sorry for the silence here. Just wanted to check if you're still seeing this issue in the latest Firebase SDK version (34.10.0)? 

It looks to me that this is a platform issue as mentioned in the https://github.com/firebase/firebase-android-sdk/issues/6117#issuecomment-2262573787
