### ISSUE TITLE
ANRs after targeting to Anroid 14 - JobInfoSchedulerService.onStartJob

### ISSUE THREAD

**Issue by WaterResistantCoder** [firebase/firebase-android-sdk#6166]
Hi, our apps ANRs were shot up by double after targeting to Android 14, almost half of them are from 
com.google.android.datatransport.runtime.scheduling.jobscheduling.JobInfoSchedulerService.onStartJob

ANR triggered by slow operations in main thread
100% Android 14 & 100% Background

**Stack Trace:**
main (runnable):tid=1 systid=24957
       at com.google.android.datatransport.runtime.scheduling.jobscheduling.JobInfoSchedulerService.onStartJob(JobInfoSchedulerService.java:32)
       at android.app.job.JobService$1.onStartJob(JobService.java:106)
       at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:195)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:257)
       at android.os.Looper.loop(Looper.java:368)
       at android.app.ActivityThread.main(ActivityThread.java:8839)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
       
**Firebase BOM: 32.1.1**

**Comment by lehcar09** [comment]
Hi @WaterResistantCoder, thank you for reaching out. This is similar to issue #6147. 

As mentioned in the description, 

> com.google.android.datatransport/transport-runtime library is using JobScheduler which is not recommended now as mentioned in android documentation: https://developer.android.com/about/versions/14/behavior-changes-14

Our engineers are already working on this along with other improvements for API level 34 (android 14), and it should be rolled out across all Firebase Android SDKs soon.

To streamline the updates, you can follow on the issue #6147. With that, I'll be closing this issue now. Thanks.
