### ISSUE TITLE
A NullPointerException occurs in the background when calling the getPackageName function related to FirebaseSession.

### ISSUE THREAD

**Issue by Dev-Czle** [firebase/firebase-android-sdk#6222]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Koala | 2024.1.1 Patch 1
  * Firebase Component: Authentication, Firestore, FCM, Storage, Crashlytics, Config, FPM, Analytics, and Dynamic Links.
  * Component version: Bom 33.1.1

### [REQUIRED] Step 3: Describe the problem

Hello,

We are currently using Firebase BoM version 33.1.1 and utilizing Authentication, Firestore, FCM, Storage, Crashlytics, Config, FPM, Analytics, and Dynamic Links.

Since the latest version, the following error has suddenly been reported to Crashlytics. Additionally, the error only occurs when the app is in the background.

I have searched for a solution, but the error name itself is too common, making it difficult to find relevant information. However, since we can see that the error occurs in the FirebaseSessions part, we are reaching out with this question. Below is the full error log.

Here's the logs

```
          Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
       at android.content.ComponentName.<init>(ComponentName.java:132)
       at android.content.Intent.<init>(Intent.java:8043)
       at com.google.firebase.sessions.SessionLifecycleServiceBinderImpl.bindToService(SessionLifecycleServiceBinder.kt:40)
       at com.google.firebase.sessions.SessionLifecycleClient.bindToService(SessionLifecycleClient.kt:107)
       at com.google.firebase.sessions.FirebaseSessions$1.invokeSuspend(FirebaseSessions.kt:54)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:30)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at com.google.firebase.concurrent.CustomThreadFactory.lambda$newThread$0(CustomThreadFactory.java:45)
       at java.lang.Thread.run(Thread.java:1012)
```

![image](https://github.com/user-attachments/assets/68b2fed8-95dc-4266-a0f3-d907162a44d3)

**Comment by Dev-Czle** [comment]
@lehcar09 
i found it started Firebase-Messaging-topic IO Thread
<img width="1104" alt="image" src="https://github.com/user-attachments/assets/199559e8-e86c-495a-8fc6-a2c3586a98c8">
i will help you what you need

**Comment by lehcar09** [comment]
Hi @Dev-Czle, sorry for the silence here. Just wanted to check if you're still observing this issue using the latest Firebase SDK version (34.10.1)?
