### ISSUE TITLE
CctTransportBackend.doSend - java.lang.IllegalArgumentException: port out of range

### ISSUE THREAD

**Issue by WaterResistantCoder** [firebase/firebase-android-sdk#6275]
Experiencing crashes from com.google.android.datatransport.cct.CctTransportBackend.doSend
from com.google.firebase.crashlytics.internal.send.ReportQueue.lambda$flushScheduledReportsIfAble$0(ReportQueue.java:138)

**Stack trace:**
Fatal Exception: java.lang.IllegalArgumentException: port out of range:786786
       at java.net.InetSocketAddress.checkPort(InetSocketAddress.java:154)
       at java.net.InetSocketAddress.createUnresolved(InetSocketAddress.java:279)
       at sun.net.spi.DefaultProxySelector$1.run(DefaultProxySelector.java:315)
       at sun.net.spi.DefaultProxySelector$1.run(DefaultProxySelector.java:219)
       at java.security.AccessController.doPrivileged(AccessController.java:46)
       at sun.net.spi.DefaultProxySelector.select(DefaultProxySelector.java:218)
       at com.android.okhttp.internal.http.RouteSelector.resetNextProxy(RouteSelector.java:123)
       at com.android.okhttp.internal.http.RouteSelector.<init>(RouteSelector.java:63)
       at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:172)
       at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
       at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:219)
       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:30)
       at com.google.android.datatransport.cct.CctTransportBackend.doSend(CctTransportBackend.java:303)
       at com.google.android.datatransport.runtime.retries.Retries.retry(Retries.java:54)
       at com.google.android.datatransport.cct.CctTransportBackend.send(CctTransportBackend.java:372)
       at com.google.android.datatransport.runtime.scheduling.jobscheduling.Uploader.logAndUpdateState(Uploader.java:146)
       at com.google.android.datatransport.runtime.ForcedSender.sendBlocking(ForcedSender.java:36)
       at com.google.firebase.crashlytics.internal.send.ReportQueue.lambda$flushScheduledReportsIfAble$0(ReportQueue.java:138)
       at java.lang.Thread.run(Thread.java:1012)
       
**99% Background**
**firebase-bom:32.1.1**

**Comment by lehcar09** [comment]
Hi @WaterResistantCoder, thank you for reaching out. Could you answer a few questions below for us to further investigate this:

- Were you able to reproduce the issue? 
- Does this issue only occurring on the specific devices? or different versions?

I noticed that you're not using the latest version, could you try upgrading to latest release (BOM 33.3. 0) and see if the issue persists?

**Comment by WaterResistantCoder** [comment]
Hi @lehcar09 

- Were you able to reproduce the issue?
No
- Does this issue only occurring on the specific devices? or different versions?
98% from Oppo and 2% from Xiaomi, and 94% Android 13 - 4% Android 11 - 1% Android 12 - 1% Android 14

We are waiting for the Jobscheduler ANR fix for Android 14 devices, currently we cannot update to the latest release (BOM 33.3.0)

**Comment by lehcar09** [comment]
I found a this similar  issue reported in [square/okhttp#6877](https://github.com/square/okhttp/issues/6877).

Looking into it:
>This is a combination of a bug/poor handling of bad proxy config in DefaultProxySelector.select, and obviously the bad proxy config with a dodgy port.
>I don't think we can fix this in OkHttp, apart from maybe making it an IOException. But really the best workaround is probably for you to detect a bad proxy config in your app and override the proxy manually.

I’ll keep this issue open for now and see if the issue persists after you have updated to the latest version. 

I would also suggest raise the issue to the AOSP. The com.android.okhttp.internal.http is part of AOSP.
