### ISSUE TITLE
Firestore crash forcing an uninstallation of the host app: java.lang.IllegalArgumentException: Invalid field path (path.``). Paths must not be empty, begin with '.', end with '.', or contain '..' 

### ISSUE THREAD

**Issue by daviduzan** [firebase/firebase-android-sdk#632]
- Android Studio version: 3.4.1

- Firebase Component: Firestore

- Component version: 20.1.0

Writing to firestore with "set" and "SetOptions.merge()" using a map with an empty key ("" string) will cause the app to crash. Even worse, it will cause the app to crash immediately every time it is opened, forcing the user to uninstall the app.

#### Steps to reproduce:
```
FirebaseFirestore db = FirebaseFirestore.getInstance();
        Map<String, Object> map1 = new HashMap<>();
        map1.put("", "temp");
       db.collection("col").document("doc").set(map1, SetOptions.merge())
```

#### Stack trace:
java.lang.RuntimeException: Internal error in Firestore (20.1.0).
        at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$5(com.google.firebase:firebase-firestore@@20.1.0:379)
        at com.google.firebase.firestore.util.AsyncQueue$$Lambda$5.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Invalid field path (``). Paths must not be empty, begin with '.', end with '.', or contain '..'
        at com.google.firebase.firestore.util.AsyncQueue.lambda$enqueue$3(com.google.firebase:firebase-firestore@@20.1.0:290)
        at com.google.firebase.firestore.util.AsyncQueue$$Lambda$3.run(Unknown Source:4)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.google.firebase.firestore.util.AsyncQueue$DelayedStartFactory.run(com.google.firebase:firebase-firestore@@20.1.0:205)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.IllegalArgumentException: Invalid field path (``). Paths must not be empty, begin with '.', end with '.', or contain '..'
        at com.google.firebase.firestore.model.FieldPath.fromServerFormat(com.google.firebase:firebase-firestore@@20.1.0:90)
        at com.google.firebase.firestore.remote.RemoteSerializer.decodeDocumentMask(com.google.firebase:firebase-firestore@@20.1.0:537)
        at com.google.firebase.firestore.remote.RemoteSerializer.decodeMutation(com.google.firebase:firebase-firestore@@20.1.0:470)
        at com.google.firebase.firestore.local.LocalSerializer.decodeMutationBatch(com.google.firebase:firebase-firestore@@20.1.0:190)
        at com.google.firebase.firestore.local.SQLiteMutationQueue.decodeInlineMutationBatch(com.google.firebase:firebase-firestore@@20.1.0:437)
        at com.google.firebase.firestore.local.SQLiteMutationQueue.lambda$getNextMutationBatchAfterBatchId$4(com.google.firebase:firebase-firestore@@20.1.0:236)
        at com.google.firebase.firestore.local.SQLiteMutationQueue$$Lambda$5.apply(Unknown Source:4)
        at com.google.firebase.firestore.local.SQLitePersistence$Query.firstValue(com.google.firebase:firebase-firestore@@20.1.0:501)
        at com.google.firebase.firestore.local.SQLiteMutationQueue.getNextMutationBatchAfterBatchId(com.google.firebase:firebase-firestore@@20.1.0:236)
        at com.google.firebase.firestore.local.LocalStore.getNextMutationBatch(com.google.firebase:firebase-firestore@@20.1.0:497)
        at com.google.firebase.firestore.remote.RemoteStore.fillWritePipeline(com.google.firebase:firebase-firestore@@20.1.0:574)
        at com.google.firebase.firestore.remote.RemoteStore.enableNetwork(com.google.firebase:firebase-firestore@@20.1.0:240)
        at com.google.firebase.firestore.remote.RemoteStore.start(com.google.firebase:firebase-firestore@@20.1.0:289)
        at com.google.firebase.firestore.core.FirestoreClient.initialize(com.google.firebase:firebase-firestore@@20.1.0:271)
        at com.google.firebase.firestore.core.FirestoreClient.lambda$new$2(com.google.firebase:firebase-firestore@@20.1.0:117)
        at com.google.firebase.firestore.core.FirestoreClient$$Lambda$2.run(Unknown Source:8)
        at com.google.firebase.firestore.util.AsyncQueue.lambda$enqueue$4(com.google.firebase:firebase-firestore@@20.1.0:311)
        at com.google.firebase.firestore.util.AsyncQueue$$Lambda$4.call(Unknown Source:2)
2019-07-18 16:12:27.304 29220-29220/co.blazepod.blazepod E/AndroidRuntime:     at co

**Comment by wilhuff** [comment]
That's very surprising. The same validation logic should have caught this at the API layer and prevented the document from entering the system at all. I'm looking into what's going on.

**Comment by wilhuff** [comment]
Confirmed. We should be validating the keys in the map and we're not doing so. This fails with set+merge because that's a write that includes a string-form field mask, and reading in the field mask does validate.

I'll put together a PR that will reject this on input.

Note that an empty key is not valid so this is still going to throw `IllegalArgumentException`.

**Comment by wilhuff** [comment]
This will go out with the next release.
