### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference

### ISSUE THREAD

**Issue by nubpro** [firebase/firebase-android-sdk#6347]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio 2024.2.1 Patch 1
  * Firebase Component: Firestore
  * Component version: 25.1.0 (it also happened on 24.11.1, hence I upgraded to 25.1.0 but the problem persists)

### [REQUIRED] Step 3: Describe the problem

Crashytics has caught severals crashes of the same error on a user's device. I'm unable to find out what they did prior to the crash.

```
          Fatal Exception: java.lang.RuntimeException: Internal error in Cloud Firestore (25.1.0).
       at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$3(AsyncQueue.java:546)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7680)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:423)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
       
```

```           Caused by com.google.android.gms.tasks.RuntimeExecutionException: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
       at com.google.android.gms.tasks.zzw.getResult(com.google.android.gms:play-services-tasks@@18.1.0:3)
       at com.google.firebase.firestore.remote.FirestoreChannel.lambda$runBidiStreamingRpc$0(FirestoreChannel.java:146)
       at com.google.android.gms.tasks.zzi.run(com.google.android.gms:play-services-tasks@@18.1.0:1)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:235)
       at java.lang.Thread.run(Thread.java:923)
```

```
         Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
       at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:830)
       at android.app.LoadedApk.access$100(LoadedApk.java:104)
       at android.app.LoadedApk$SplitDependencyLoaderImpl.constructSplit(LoadedApk.java:605)
       at android.content.pm.split.SplitDependencyLoader.loadDependenciesForSplit(SplitDependencyLoader.java:70)
       at android.app.LoadedApk$SplitDependencyLoaderImpl.ensureSplitLoaded(LoadedApk.java:640)
       at android.app.LoadedApk$SplitDependencyLoaderImpl.getSplitPathsForSplit(LoadedApk.java:649)
       at android.app.LoadedApk.getSplitPaths(LoadedApk.java:666)
       at android.app.ContextImpl.createResources(ContextImpl.java:2252)
       at android.app.ContextImpl.createPackageContextAsUser(ContextImpl.java:2315)
       at android.app.ContextImpl.createPackageContext(ContextImpl.java:2294)
       at android.content.ContextWrapper.createPackageContext(ContextWrapper.java:927)
       at com.google.android.gms.common.GooglePlayServicesUtilLight.getRemoteContext(GooglePlayServicesUtilLight.java:1)
       at com.google.android.gms.security.ProviderInstaller.installIfNeeded(com.google.android.gms:play-services-basement@@18.3.0:8)
       at com.google.firebase.firestore.remote.GrpcCallProvider.initChannel(GrpcCallProvider.java:85)
       at com.google.firebase.firestore.remote.GrpcCallProvider.lambda$initChannelTask$6(GrpcCallProvider.java:242)
       at com.google.android.gms.tasks.zzz.run(com.google.android.gms:play-services-tasks@@18.1.0:1)
       at com.google.firebase.firestore.util.ThrottledForwardingExecutor.lambda$execute$0(ThrottledForwardingExecutor.java:54)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
```

Here is the dump of the stacktrace:
[com.cwk.dududu_issue_a59038b118b160954ace26481312ad6f_crash_session_671010D7032D000130F9199483CB4C80_DNE_0_v2_stacktrace.txt](https://github.com/user-attachments/files/17254968/com.cwk.dududu_issue_a59038b118b160954ace26481312ad6f_crash_session_671010D7032D000130F9199483CB4C80_DNE_0_v2_stacktrace.txt)

#### Steps to reproduce:

What happened? How can we make the problem occur?
Honestly I have no clue what's happening here, if someone could point out to me how to troubleshoot this, I'd love to make the changes.

#### Relevant Code:
N/A

**Comment by tom-andersen** [comment]
The error seems to come from within the Android SDK. Which version are you running?

**Comment by nubpro** [comment]
> The error seems to come from within the Android SDK. Which version are you running?

The user is running android 11. Oneplus8pro

**Comment by nubpro** [comment]
> The error seems to come from within the Android SDK. Which version are you running?

Hey Tom, do you need any more information from us?

**Comment by tom-andersen** [comment]
At the moment, this seems to be a problem with the customer device. Are you able to reproduce this?

When I looked up the device, I believe an upgrade to Android is available.
