### ISSUE TITLE
Internal error in Cloud Firestore (25.1.0) - TooManyRequestsException

### ISSUE THREAD

**Issue by alimurtaza28** [firebase/firebase-android-sdk#6365]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Koala | 2024.1.1 Patch 1
  * Firebase Component: Firestore
  * Component version: 'com.google.firebase:firebase-bom:33.3.0'

### [REQUIRED] Step 3: Describe the problem
App crashing in production mode with the following error:
Internal error in Cloud Firestore (25.1.0)
Caused by java.lang.RuntimeException: android.net.ConnectivityManager$TooManyRequestsException

#### Steps to reproduce:
It occurs randomly. I have seen this once on these devices : Samsung A32, Oppo A37, Samsung S8

What happened? How can we make the problem occur?

  Fatal Exception: java.lang.RuntimeException: Internal error in Cloud Firestore (25.1.0).
       at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$3(AsyncQueue.java:546)
       at com.google.firebase.firestore.util.AsyncQueue$$ExternalSyntheticLambda3.run(D8$$SyntheticClass)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7941)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:569)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)
       
       
   Caused by java.lang.RuntimeException: android.net.ConnectivityManager$TooManyRequestsException
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor.lambda$executeAndReportResult$1(AsyncQueue.java:333)
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$$ExternalSyntheticLambda2.run(D8$$SyntheticClass)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
       at java.util.concurrent.FutureTask.run(FutureTask.java:264)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:235)
       at java.lang.Thread.run(Thread.java:1012)     

#### Relevant Code:
I don't yet know which code is causing this problem

// TODO(you): code here to reproduce the problem
```

**Comment by alimurtaza28** [comment]
Please address this issue ASAP because it's affecting my google play rankings. Thanks

**Comment by MarkDuckworth** [comment]
@alimurtaza28, we don't have enough information to move forward. It would be useful to know how your app is calling the Firestore API when this occurs. Also, [capturing](https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/FirebaseFirestore.html#setLoggingEnabled(boolean)) and providing us with debug logs from the SDK could help us investigate the issue further.

Have you seen this issue with older versions of the SDK? Did it start occurring after you updated to a specific version of the SDK?

**Comment by fractalbob** [comment]
Also fails the same way when running on an emulated Samsung Tab A.

**Comment by fractalbob** [comment]
Also the problem only occurs in my case during Google signin. After the user has signed in, the app runs without a problem.

**Comment by ricardobegar** [comment]
The same error happens to me too. It started happening to us when we updated the Flutter version to 3.24.3 and updated the Firebase libraries 

firebase_core 3.6.0
cloud_firestore 5.4.4

I really don't know what could cause the error since it happens to me randomly. 

In my particular case it happens to me on a Redmi 11 with Android 13

![Screenshot 2024-10-22 at 2 12 59 PM](https://github.com/user-attachments/assets/b823a16a-0fd5-47b6-b09e-253c78d6008c)

**Comment by malhakeem** [comment]
I'm also facing what seems to be the same error after Flutterflow's update to flutter 3.24.2.
firebase_core 3.6.0
cloud_firestore 5.4.4

The app crashes immediately after startup:

Fatal Exception: java.lang.RuntimeException: Internal error in Cloud Firestore (25.1.0).
       at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$3(AsyncQueue.java:38)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8762)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by NicolasLopezFer** [comment]
Same error

**Comment by lgomeza** [comment]
Same issue here. It doesn't happen all the time, it happens randomly in different sessions and it is becoming such a big issue that we are considering downgrading the Flutter version (it seems to have something to do with both the combination of the Firebase version and the Flutter version)

**Comment by Jhonsebas77** [comment]
Is there any update on this case, it keeps happening to me randomly, I have tried several things mentioned here, however, nothing has worked for me

```
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.6.1 23G93 darwin-arm64, locale en-CO)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0-rc2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.94.2)
```

**Comment by Diegoo3210** [comment]
I am experiencing the same issue intermittently across different sessions, and it's starting to significantly impact our app's functionality. The bug appears to be random, but it's persistent. Im running latest flutter versión.

**Comment by EricLyannaz** [comment]
Same error since the last update of FlutterFlow

**Comment by MarkDuckworth** [comment]
I'm trying to isolate this issue and get the right people involved. 

If you are replying to this thread to report the issue, please include the following information. If you've already replied and can also provide this info, please leave another comment.

1. Are you using Flutter? YES or NO.
    If yes, the report the version of Flutter where you first experienced the issue.
2. Firebase Android SDK version where you first experienced the issue
3. Android Studio version where you first experienced the issue
4. If you started experiencing the issue after updating of these, please let us know the version you were using and if downgrading to the prior version resolves the issue for you?
5. In your stack trace you also seeing `Caused by java.lang.RuntimeException: android.net.ConnectivityManager$TooManyRequestsException`? YES or NO

These stack traces and logs are helpful. Thanks.

**Comment by cynthiajoan** [comment]
One more question to help identify the issue:
If you are using Flutter, what's the version of the following firebase flutter plugins that you first run into the issue
firebase_core
cloud_firestore

**Comment by MarkDuckworth** [comment]
I'm going to limit this thread to `Internal error in Cloud Firestore (25.1.0)` stack trace containing `Caused by java.lang.RuntimeException: android.net.ConnectivityManager$TooManyRequestsException`. Anyone seeing other behavior should open a separate issue. This may apply to @fractalbob and @malhakeem.

**Comment by MarkDuckworth** [comment]
I was able to find a possible cause of the `TooManyRequestsExecption`, which is that your applications are creating more than 100 [FirebaseFirestore](https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/FirebaseFirestore) instances without calling [terminate()](https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/FirebaseFirestore#terminate()) to clean up any of their resources. This then exhausts resources in the ConnectivityMonitor class use by Firestore, and results in the observed error.

Many reports of the error in this thread correlate with an update to Flutter. There may be a change in Flutter or any Flutter libraries you are using that are causing your app to create many `FirebaseFirestore` instances without ever terminating them. I've followed up on this [FlutterFire issue](https://github.com/firebase/flutterfire/issues/13548) to see if that team can investigate the issue.

If there are users that need a large number of `FirebaseFirestore` instances concurrently (~100 or more), can you tell me more about your use case?

**Comment by pranavo72bex** [comment]
I am facing same issue in flutter 3.24.3 
  cloud_firestore: ^5.4.4
 ```
 [✓] Flutter (Channel stable, 3.24.3, on macOS 14.6.1 23G93 darwin-arm64, locale en-CO)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0-rc2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.94.2)
```
  
```
java.lang.RuntimeException: Internal error in Cloud Firestore (25.1.1).
E/AndroidRuntime( 5985): 	at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$3(AsyncQueue.java:546)
E/AndroidRuntime( 5985): 	at com.google.firebase.firestore.util.AsyncQueue.$r8$lambda$jx84dqgUsF4ojecSMurRqFLFD1Y(AsyncQueue.java:0)
E/AndroidRuntime( 5985): 	at com.google.firebase.firestore.util.AsyncQueue$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:0)
E/AndroidRuntime( 5985): 	at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime( 5985): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 5985): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime( 5985): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime( 5985): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/AndroidRuntime( 5985): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5985): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime( 5985): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/AndroidRuntime( 5985): Caused by: com.google.android.gms.tasks.RuntimeExecutionException: java.lang.RuntimeException: java.lang.ExceptionInInitializerError
E/AndroidRuntime( 5985): 	at com.google.android.gms.tasks.zzw.getResult(com.google.android.gms:play-services-tasks@@18.1.0:3)
E/AndroidRuntime( 5985): 	at com.google.firebase.firestore.remote.FirestoreChannel.lambda$runBidiStreamingRpc$0(FirestoreChannel.java:146)
E/AndroidRuntime( 5985): 	at com.google.firebase.firestore.remote.FirestoreChannel.$r8$lambda$ThFui-hvcsrVGYxlBtcTH5vVbvE(FirestoreChannel.java:0)
E/AndroidRuntime( 5985): 	at com.google.firebase.firestore.remote.FirestoreChannel$$ExternalSyntheticLambda0.onComplete(R8$$SyntheticClass:0)
E/AndroidRuntime( 5985): 	at com.google.android.gms.tasks.zzi.run(com.google.android.gms:play-services-tasks@@18.1.0:1)
E/AndroidRuntime( 5985): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
E/AndroidRuntime( 5985): 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
E/AndroidRuntime( 5985): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
E/AndroidRuntime( 5985): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
E/AndroidRuntime( 5985): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
E/AndroidRuntime( 5985): 	at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:235)
```

**Comment by pranavo72bex** [comment]
> I'm also facing what seems to be the same error after Flutterflow's update to flutter 3.24.2. firebase_core 3.6.0 cloud_firestore 5.4.4
> 
> The app crashes immediately after startup:
> 
> Fatal Exception: java.lang.RuntimeException: Internal error in Cloud Firestore (25.1.0). at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$3(AsyncQueue.java:38) at android.os.Handler.handleCallback(Handler.java:942) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loopOnce(Looper.java:226) at android.os.Looper.loop(Looper.java:313) at android.app.ActivityThread.main(ActivityThread.java:8762) at java.lang.reflect.Method.invoke(Method.java) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

In my case, app only crash when it is logged in btw which uses firebase auth. without logged-in it is working fine.

**Comment by pranavo72bex** [comment]
Issue Details:

Are you using Flutter? YES
Flutter version where issue first occurred: 3.24.3
Firebase Android SDK version:
Cloud Firestore: com.google.firebase:firebase-firestore:24.9.1
Crashlytics: 2.9.9
Google Services Plugin: 4.3.0
Android Studio version: 2023.2 (Flamingo)
Gradle version: 7.6.1
Kotlin version: 1.9.10
Other dependencies:
WorkManager: androidx.work:work-runtime-ktx:2.9.0
Play Review: com.google.android.play:review:2.0.1
Play Review KTX: com.google.android.play:review-ktx:2.0.1
Desugaring Library: com.android.tools:desugar_jdk_libs:1.2.0
Did the issue occur after an update? Unclear; please specify if downgrading resolves the issue.
Stack trace includes Caused by java.lang.RuntimeException: android.net.ConnectivityManager$TooManyRequestsException: Not mentioned directly. However, similar exception trace observed:
Key exception trace:
go
Copy code
java.lang.RuntimeException: Internal error in Cloud Firestore (25.1.1)
com.google.firebase.firestore.util.AsyncQueue.lambda$panic$3
...
Caused by: java.lang.RuntimeException: java.lang.ExceptionInInitializerError
Logs: The full trace was shared. Key logs:
Error observed in Firestore channel initialization and AsyncQueue handling.

**Comment by pranavo72bex** [comment]
> I'm having the same error but when trying to run test with detox 20.28.0 on mi emulator with the last version on Android Studio in RN 0.73.8.
> 
> The app has crashed, see the details below:
> 
> ```
> @Thread detox.primary(107):
> java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Internal error in Cloud Firestore (25.1.1).
>     at androidx.test.espresso.Espresso.onIdle(Espresso.java:357)
>     at com.wix.detox.TestEngineFacade.awaitIdle(TestEngineFacade.kt:12)
>     at com.wix.detox.adapters.server.ReadyActionHandler.handle(DetoxActionHandlers.kt:25)
>     at com.wix.detox.DetoxMain$setupActionHandlers$SynchronizedActionHandler.handle(DetoxMain.kt:75)
>     at com.wix.detox.adapters.server.ActionsExecutor.executeAction$lambda$2$lambda$1(DetoxActionsDispatcher.kt:76)
>     at com.wix.detox.adapters.server.ActionsExecutor.$r8$lambda$LZ3KRuVesIYkeXHJoNMi_yqw1HU(Unknown Source:0)
>     at com.wix.detox.adapters.server.ActionsExecutor$$ExternalSyntheticLambda0.run(Unknown Source:8)
>     at android.os.Handler.handleCallback(Handler.java:959)
>     at android.os.Handler.dispatchMessage(Handler.java:100)
>     at android.os.Looper.loopOnce(Looper.java:232)
>     at android.os.Looper.loop(Looper.java:317)
>     at com.wix.detox.adapters.server.ActionsExecutor._init_$lambda$0(DetoxActionsDispatcher.kt:62)
>     at com.wix.detox.adapters.server.ActionsExecutor.$r8$lambda$4eWOlZMqOQq2jbqiFbTCEP-pHOY(Unknown Source:0)
>     at com.wix.detox.adapters.server.ActionsExecutor$$ExternalSyntheticLambda1.run(Unknown Source:4)
>     at java.lang.Thread.run(Thread.java:1012)
> Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Internal error in Cloud Firestore (25.1.1).
>     at java.util.concurrent.FutureTask.report(FutureTask.java:122)
>     at java.util.concurrent.FutureTask.get(FutureTask.java:191)
>     at androidx.test.espresso.Espresso.onIdle(Espresso.java:349)
>     ... 14 more
> Caused by: java.lang.RuntimeException: Internal error in Cloud Firestore (25.1.1).
>     at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$3(AsyncQueue.java:546)
>     at com.google.firebase.firestore.util.AsyncQueue$$ExternalSyntheticLambda6.run(Unknown Source:2)
>     at android.os.Handler.handleCallback(Handler.java:959)
>     at android.os.Handler.dispatchMessage(Handler.java:100)
>     at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:156)
>     at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:510)
>     at androidx.test.espresso.base.UiControllerImpl.loopMainThreadUntilIdle(UiControllerImpl.java:433)
>     at androidx.test.espresso.Espresso.lambda$onIdle$2(Espresso.java:340)
>     at androidx.test.espresso.Espresso$$ExternalSyntheticLambda1.call(Unknown Source:0)
>     at java.util.concurrent.FutureTask.run(FutureTask.java:264)
>     at android.os.Handler.handleCallback(Handler.java:959)
>     at android.os.Handler.dispatchMessage(Handler.java:100)
>     at android.os.Looper.loopOnce(Looper.java:232)
>     at android.os.Looper.loop(Looper.java:317)
>     at android.app.ActivityThread.main(ActivityThread.java:8705)
>     at java.lang.reflect.Method.invoke(Native Method)
>     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
> ```

It will be nicer if you could provide detailed information in this formate https://github.com/firebase/firebase-android-sdk/issues/6365#issuecomment-2447976534

**Comment by Noesersi** [comment]
> * Are you using Flutter? NO.

> * Firebase Android SDK version where you first experienced the issue. 
firebaseMessagingVersion = "21.1.0"
google-services:4.3.10
firebase-analytics:17.3.0
"@react-native-firebase/app": "21.6.1 "

> * Android Studio version where you first experienced the issue
Android Studio Ladybug | 2024.2.1 Patch 2
Build #AI-242.23339.11.2421.12550806, built on October 24, 2024
Runtime version: 21.0.3+-79915917-b509.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 15.0.1
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
  i18n.locale=


> * If you started experiencing the issue after updating of these, please let us know the version you were using and if downgrading to the prior version resolves the issue for you?
I never made it work with detox, I tried in RN 0.73.8 and 0.75.4

> * In your stack trace you also seeing `Caused by java.lang.RuntimeException: android.net.ConnectivityManager$TooManyRequestsException`? YES 
@Thread detox.primary(107):
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Internal error in Cloud Firestore (25.1.1).
    at androidx.test.espresso.Espresso.onIdle(Espresso.java:357)

**Comment by BhavinPI** [comment]
When I using firebase auth for login I got this same error.

FATAL EXCEPTION: main
                                                                                                 Process: com.app, PID: 17090
                                                                                                 java.lang.RuntimeException: Internal error in Cloud Firestore (25.1.1).
                                                                                                 	at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$3(AsyncQueue.java:546)
                                                                                                 	at com.google.firebase.firestore.util.AsyncQueue$$ExternalSyntheticLambda3.run(D8$$SyntheticClass:0)
                                                                                                 	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                 	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                 	at android.os.Looper.loop(Looper.java:313)
                                                                                                 	at android.app.ActivityThread.main(ActivityThread.java:8762)
                                                                                                 	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
                                                                                                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
                                                                                                 Caused by: com.google.android.gms.tasks.RuntimeExecutionException: java.lang.RuntimeException: java.lang.NoClassDefFoundError: Failed resolution of: Lio/grpc/InternalGlobalInterceptors;
                                                                                                 	at com.google.android.gms.tasks.zzw.getResult(com.google.android.gms:play-services-tasks@@18.1.0:3)
                                                                                                 	at com.google.firebase.firestore.remote.FirestoreChannel.lambda$runBidiStreamingRpc$0$com-google-firebase-firestore-remote-FirestoreChannel(FirestoreChannel.java:146)
                                                                                                 	at com.google.firebase.firestore.remote.FirestoreChannel$$ExternalSyntheticLambda0.onComplete(D8$$SyntheticClass:0)
                                                                                                 	at com.google.android.gms.tasks.zzi.run(com.google.android.gms:play-services-tasks@@18.1.0:1)
                                                                                                 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
                                                                                                 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
                                                                                                 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
                                                                                                 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                 	at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:235)
                                                                                                 	at java.lang.Thread.run(Thread.java:1012)
                                                                                                 Caused by: java.lang.RuntimeException: java.lang.NoClassDefFoundError: Failed resolution of: Lio/grpc/InternalGlobalInterceptors;
                                                                                                 	at com.google.android.gms.tasks.zzz.run(com.google.android.gms:play-services-tasks@@18.1.0:2)
                                                                                                 	at com.google.firebase.firestore.util.ThrottledForwardingExecutor.lambda$execute$0$com-google-firebase-firestore-util-ThrottledForwardingExecutor(ThrottledForwardingExecutor.java:54)
                                                                                                 	at com.google.firebase.firestore.util.ThrottledForwardingExecutor$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
                                                                                                 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                 	at java.lang.Thread.run(Thread.java:1012) 
                                                                                                 Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lio/grpc/InternalGlobalInterceptors;
                                                                                                 	at io.grpc.internal.ManagedChannelImplBuilder.getEffectiveInterceptors(ManagedChannelImplBuilder.java:684)
                                                                                                 	at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:672)
                                                                                                 	at io.grpc.ForwardingChannelBuilder2.build(ForwardingChannelBuilder2.java:272)
                                                                                                 	at io.grpc.android.AndroidChannelBuilder.build(AndroidChannelBuilder.java:169)
                                                                                                 	at com.google.firebase.firestore.remote.GrpcCallProvider.initChannel(GrpcCallProvider.java:116)
                                                                                                 	at com.google.firebase.firestore.remote.GrpcCallProvider.lambda$initChannelTask$6$com-google-firebase-firestore-remote-GrpcCallProvider(GrpcCallProvider.java:242)
                                                                                                 	at com.google.firebase.firestore.remote.GrpcCallProvider$$ExternalSyntheticLambda4.call(D8$$SyntheticClass:0)
                                                                                                 	at com.google.android.gms.tasks.zzz.run(com.google.android.gms:play-services-tasks@@18.1.0:1)
                                                                                                 	at com.google.firebase.firestore.util.ThrottledForwardingExecutor.lambda$execute$0$com-google-firebase-firestore-util-ThrottledForwardingExecutor(ThrottledForwardingExecutor.java:54) 
                                                                                                 	at com.google.firebase.firestore.util.ThrottledForwardingExecutor$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0) 
                                                                                                 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
                                                                                                 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) 
                                                                                                 	at java.lang.Thread.run(Thread.java:1012)

**Comment by MarkDuckworth** [comment]
@BhavinPI, `Caused by: java.lang.RuntimeException: java.lang.NoClassDefFoundError: Failed resolution of: Lio/grpc/InternalGlobalInterceptors;`may indicate a different root cause.

**Comment by vijaymsc** [comment]
@MarkDuckworth    

I got same  crash refer below Stack trace 

ConnectivityManager.convertServiceException
android.net.ConnectivityManager$TooManyRequestsException
ConnectivityManager.java:4495

Fatal Exception: android.net.ConnectivityManager$TooManyRequestsException
 Fatal Exception: android.net.ConnectivityManager$TooManyRequestsException:
       at android.net.ConnectivityManager.convertServiceException(ConnectivityManager.java:4495)
       at android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4780)
       at android.net.ConnectivityManager.registerDefaultNetworkCallbackForUid(ConnectivityManager.java:5461)
       at android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:5428)
       at android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:5402)
       at androidx.work.impl.utils.NetworkApi24.registerDefaultNetworkCallbackCompat(NetworkApi24.kt:26)
       at androidx.work.impl.constraints.trackers.NetworkStateTracker24.startTracking(NetworkStateTracker.kt:165)
       at androidx.work.impl.constraints.trackers.ConstraintTracker.addListener(ConstraintTracker.kt:52)
       at androidx.work.impl.constraints.controllers.BaseConstraintController$track$1.invokeSuspend(ContraintControllers.kt:62)
       at androidx.work.impl.constraints.controllers.BaseConstraintController$track$1.invoke(ContraintControllers.kt:2)
       at androidx.work.impl.constraints.controllers.BaseConstraintController$track$1.invoke(ContraintControllers.kt:1)
       at kotlinx.coroutines.flow.ChannelFlowBuilder.collectTo$suspendImpl(Builders.kt:316)
       at kotlinx.coroutines.flow.ChannelFlowBuilder.collectTo(Builders.kt:2)
       at kotlinx.coroutines.flow.CallbackFlowBuilder.collectTo(Builders.kt:330)
       at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.java:56)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
       at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1156)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:651)
       at java.lang.Thread.run(Thread.java:1119)

**Comment by lehcar09** [comment]
Hey folks! sorry for the silence here. Does anyone still seeing this issue in the latest Firebase SDK version (34.11.0)?

As mentioned in https://github.com/firebase/firebase-android-sdk/issues/6365#issuecomment-2448655854

> I was able to find a possible cause of the TooManyRequestsExecption, which is that your applications are creating more than 100 [FirebaseFirestore](https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/FirebaseFirestore) instances without calling [terminate()](https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/FirebaseFirestore#terminate()) to clean up any of their resources. This then exhausts resources in the ConnectivityMonitor class use by Firestore, and results in the observed error.
>
>Many reports of the error in this thread correlate with an update to Flutter. There may be a change in Flutter or any Flutter libraries you are using that are causing your app to create many FirebaseFirestore instances without ever terminating them. I've followed up on this https://github.com/firebase/flutterfire/issues/13548 to see if that team can investigate the issue.
>
>If there are users that need a large number of FirebaseFirestore instances concurrently (~100 or more), can you tell me more about your use case?

In addition to providing your use case, can you also please share the details below to help us move forward in investigating this issue.

* Firebase Android SDK version where you first experienced the issue
* Android Studio version where you first experienced the issue
* If you started experiencing the issue after updating of these, please let us know the version you were using and if downgrading to the prior version resolves the issue for you?
* Please ensure to share your complete stack trace that contains "Caused by java.lang.RuntimeException: android.net.ConnectivityManager$TooManyRequestsException".

Thanks.
