### ISSUE TITLE
UnbufferedIoViolation in Crashlytics

### ISSUE THREAD

**Issue by stanhebben** [firebase/firebase-android-sdk#6391]
### [READ] Step 1: Are you in the right place?

Done

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 2024.1.1
  * Firebase Component: Crashlytics
  * Component version: 19.2.0
  * Device: OnePlus 8 (IN2013)
  * Android version: 13
  * Never seen in the emulator, only an a physical device

#### Steps to reproduce:

* Have an app with crashlytics installed
* Have a crash generated (in my case the crash was generated by a bug in my FirebaseMessagingService.onNewToken implementation)
* Open the app
* The app crashes with the following stack trace:

```
StrictMode policy violation: android.os.strictmode.UnbufferedIoViolation
    at android.os.StrictMode$AndroidBlockGuardPolicy.onUnbufferedIO(StrictMode.java:1647)
    at libcore.io.IoTracker.trackIo(IoTracker.java:35)
    at libcore.io.IoTracker.trackIo(IoTracker.java:45)
    at java.io.FileInputStream.read(FileInputStream.java:350)
    at android.os.ParcelFileDescriptor$AutoCloseInputStream.read(ParcelFileDescriptor.java:1023)
    at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:303)
    at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:210)
    at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:134)
    at java.io.FilterInputStream.read(FilterInputStream.java:107)
    at com.google.firebase.crashlytics.internal.common.SessionReportingCoordinator.convertInputStreamToString(SessionReportingCoordinator.java:425)
    at com.google.firebase.crashlytics.internal.common.SessionReportingCoordinator.convertApplicationExitInfo(SessionReportingCoordinator.java:396)
    at com.google.firebase.crashlytics.internal.common.SessionReportingCoordinator.persistRelevantAppExitInfoEvent(SessionReportingCoordinator.java:152)
    at com.google.firebase.crashlytics.internal.common.CrashlyticsController.writeApplicationExitInfoEventIfRelevant(CrashlyticsController.java:910)
    at com.google.firebase.crashlytics.internal.common.CrashlyticsController.doCloseSessions(CrashlyticsController.java:578)
    at com.google.firebase.crashlytics.internal.common.CrashlyticsController.finalizeSessions(CrashlyticsController.java:506)
    at com.google.firebase.crashlytics.internal.common.CrashlyticsCore.doBackgroundInitialization(CrashlyticsCore.java:250)
    at com.google.firebase.crashlytics.internal.common.CrashlyticsCore.lambda$doBackgroundInitializationAsync$0$com-google-firebase-crashlytics-internal-common-CrashlyticsCore(CrashlyticsCore.java:227)
    at com.google.firebase.crashlytics.internal.common.CrashlyticsCore$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
    at com.google.firebase.crashlytics.internal.concurrency.CrashlyticsWorker.lambda$submit$1(CrashlyticsWorker.java:96)
    at com.google.firebase.crashlytics.internal.concurrency.CrashlyticsWorker$$ExternalSyntheticLambda0.then(D8$$SyntheticClass:0)
    at com.google.android.gms.tasks.zze.run(com.google.android.gms:play-services-tasks@@18.1.0:1)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
    at com.google.firebase.concurrent.CustomThreadFactory.lambda$newThread$0$com-google-firebase-concurrent-CustomThreadFactory(CustomThreadFactory.java:47)
    at com.google.firebase.concurrent.CustomThreadFactory$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
    at java.lang.Thread.run(Thread.java:1012)
```

#### Relevant Code:

N/A

**Comment by stanhebben** [comment]
The issue seems to only occur on one specific device (a OnePlus 8). I don't see it happening on the emulator or the Pixel 3a I have here.

It's on a new app, so no older versions of Crashlytics where it doesn't occur. I will try to make a MCVE for it.

**Comment by lehcar09** [comment]
Hey @stanhebben, I'll mark this as needs-info for now. Don't worry if the issue closes due to stale, we can always reopen this once we have new information. Thanks!

**Comment by stanhebben** [comment]
I didn't reliably reproduce the bug, but I did manage to reliably fix the problem.

Investigation into the bug led to the discovery that something along these lines ended up happening:

```
runBlocking {
  myScope.launch(Dispatchers.IO) {
    ..doing some network requests...
  }
}

```

And coroutines don't seem to like that, causing other unrelated coroutines - such as Crashlytics and GCM - to become stuck.

So I believe this issue can be closed.

**Comment by exaby73** [comment]
Hey @stanhebben. Based on your comment, I feel safe to close this issue. If you feel there is still an issue related to Crashlytics, feel free to comment and we can reopen or open a new issue and we can take a look at it. Thanks for providing valuable information
