### ISSUE TITLE
StrictMode policy violation: `android.os.strictmode.UnbufferedIoViolation` when upgrading to `targetSdkVersion 34`

### ISSUE THREAD

**Issue by gubatron** [firebase/firebase-android-sdk#6564]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Meerkat | 2024.3.1 Canary 3
  * Firebase Component: `com.google.firebase:firebase-bom:33.7.0`, `com.google.firebase:firebase-crashlytics`
  * Component version: 33.7.0

### [REQUIRED] Step 3: Describe the problem

Firebase crashlytics incurrs in an Unbuffered IO Violation when building our app for target SDK 34 upon loading the library on app startup.

#### Steps to reproduce:

Start the app, this comes out in the logs:
```
D  Initializing WorkManager with default configuration.
2024-12-05 12:41:26.080  6029-6062  StrictMode              com.frostwire.android                D  StrictMode policy violation: android.os.strictmode.UnbufferedIoViolation
                                                                                                    	at android.os.StrictMode$AndroidBlockGuardPolicy.onUnbufferedIO(StrictMode.java:1655)
                                                                                                    	at libcore.io.IoTracker.trackIo(IoTracker.java:35)
                                                                                                    	at libcore.io.IoTracker.trackIo(IoTracker.java:45)
                                                                                                    	at java.io.FileInputStream.read(FileInputStream.java:325)
                                                                                                    	at android.os.ParcelFileDescriptor$AutoCloseInputStream.read(ParcelFileDescriptor.java:1032)
                                                                                                    	at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:263)
                                                                                                    	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:178)
                                                                                                    	at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:135)
                                                                                                    	at java.io.FilterInputStream.read(FilterInputStream.java:107)
                                                                                                    	at com.google.firebase.crashlytics.internal.common.SessionReportingCoordinator.convertInputStreamToString(SessionReportingCoordinator.java:425)
                                                                                                    	at com.google.firebase.crashlytics.internal.common.SessionReportingCoordinator.convertApplicationExitInfo(SessionReportingCoordinator.java:396)
                                                                                                    	at com.google.firebase.crashlytics.internal.common.SessionReportingCoordinator.persistRelevantAppExitInfoEvent(SessionReportingCoordinator.java:152)
                                                                                                    	at com.google.firebase.crashlytics.internal.common.CrashlyticsController.writeApplicationExitInfoEventIfRelevant(CrashlyticsController.java:910)
                                                                                                    	at com.google.firebase.crashlytics.internal.common.CrashlyticsController.doCloseSessions(CrashlyticsController.java:578)
                                                                                                    	at com.google.firebase.crashlytics.internal.common.CrashlyticsController.finalizeSessions(CrashlyticsController.java:506)
                                                                                                    	at com.google.firebase.crashlytics.internal.common.CrashlyticsCore.doBackgroundInitialization(CrashlyticsCore.java:250)
                                                                                                    	at com.google.firebase.crashlytics.internal.common.CrashlyticsCore.lambda$doBackgroundInitializationAsync$0(CrashlyticsCore.java:227)
                                                                                                    	at com.google.firebase.crashlytics.internal.common.CrashlyticsCore.$r8$lambda$knH5rP9MzxyK2lsYoMqMtYQH4kA(CrashlyticsCore.java:0)
                                                                                                    	at com.google.firebase.crashlytics.internal.common.CrashlyticsCore$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
                                                                                                    	at com.google.firebase.crashlytics.internal.concurrency.CrashlyticsWorker.lambda$submit$1(CrashlyticsWorker.java:96)
                                                                                                    	at com.google.firebase.crashlytics.internal.concurrency.CrashlyticsWorker.$r8$lambda$QmZlDkBlDR5w6hZfr1BjiCUvNrE(CrashlyticsWorker.java:0)
                                                                                                    	at com.google.firebase.crashlytics.internal.concurrency.CrashlyticsWorker$$ExternalSyntheticLambda1.then(R8$$SyntheticClass:0)
                                                                                                    	at com.google.android.gms.tasks.zze.run(com.google.android.gms:play-services-tasks@@18.1.0:1)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at com.google.firebase.concurrent.CustomThreadFactory.lambda$newThread$0(CustomThreadFactory.java:47)
                                                                                                    	at com.google.firebase.concurrent.CustomThreadFactory.$r8$lambda$XB8AY3Hcio74byWuTzgVEC3Hiek(CustomThreadFactory.java:0)
                                                                                                    	at com.google.firebase.concurrent.CustomThreadFactory$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
```

#### Relevant Code:

In your `SessionReportingCoordinator.java` you're not using Buffered IO:
```java
 @VisibleForTesting
  @RequiresApi(api = Build.VERSION_CODES.KITKAT)
  public static String convertInputStreamToString(InputStream inputStream) throws IOException {
    ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
    byte[] bytes = new byte[DEFAULT_BUFFER_SIZE];
    int length;
    while ((length = inputStream.read(bytes)) != -1) {
      byteArrayOutputStream.write(bytes, 0, length);
    }
    return byteArrayOutputStream.toString(StandardCharsets.UTF_8.name());
  }
```

Your code should be more like this to avoid the triggers in Android 14+

```java
@VisibleForTesting
@RequiresApi(api = Build.VERSION_CODES.KITKAT)
public static String convertInputStreamToString(InputStream inputStream) throws IOException {
    try (BufferedInputStream bufferedInputStream = new BufferedInputStream(inputStream);
         ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream()) {
        byte[] bytes = new byte[DEFAULT_BUFFER_SIZE];
        int length;
        while ((length = bufferedInputStream.read(bytes)) != -1) {
            byteArrayOutputStream.write(bytes, 0, length);
        }
        return byteArrayOutputStream.toString(StandardCharsets.UTF_8.name());
    }
}
```

**Comment by gubatron** [comment]
previously dismissed [here](https://github.com/firebase/firebase-android-sdk/issues/6391), I'm sure you'll get more reports as more developers need to start upgrading target sdk

**Comment by mrober** [comment]
Hi @gubatron, I took a look at this. I am not seeing the strict mode violation in my own test app. I am not sure what conditions are required to reproduce it, could you please provide a MCVE? Your PR looks fine, I will be happy to review it once I can reproduce the issue.

**Comment by gubatron** [comment]
Oh so nice to get a response.

This is how I was setting strictPolicy mode on:
```java
static void setStrictPolicy(boolean enable) {
        LOG.info("RunStrict.setStrictPolicy(" + enable + ") Debug.isEnabled()=" + Debug.isEnabled());
        if (!Debug.isEnabled()) {
            LOG.info("StrictMode is disabled, this is a DEBUG build");
            return; // no debug mode, do nothing
        }

        // by default, the LAX policy
        StrictMode.ThreadPolicy threadPolicy = StrictMode.ThreadPolicy.LAX;
        StrictMode.VmPolicy vmPolicy = StrictMode.VmPolicy.LAX;

        if (enable) {
            threadPolicy = new StrictMode.ThreadPolicy.Builder()
                    .detectAll()
                    .penaltyLog()
                    .penaltyDeath()
                    .build();
            vmPolicy = new StrictMode.VmPolicy.Builder()
                    .detectAll()
                    .penaltyLog()
                    .penaltyDeath()
                    .setClassInstanceLimit(Engine.class, 1)
                    .build();
        }

        StrictMode.setThreadPolicy(threadPolicy);
        StrictMode.setVmPolicy(vmPolicy);
    }
```

If I call `setStrictPolicy(true)` and just start my app, whenever it tries to talk to firebase the violation is fired, **when targeting sdk version 34**

**Comment by mrober** [comment]
I was able to reproduce your issue and review your PR. It LGTM. I am not sure if you'll have to jump through hoops to merge it, let me know if you run into any problems.

> Oh so nice to get a response.

There are only a few of us working on this, relax.

**Comment by lehcar09** [comment]
Hi @gubatron, it looks like there is an issue in the CLA. You would need to accept the CLA to merge the PR. Could you confirm if you have accepted the CLA?

**Comment by lehcar09** [comment]
The CLA you signed is the right one. I'll raise this to our engineer and we can merge the PR on your behalf. Thanks!

**Comment by lehcar09** [comment]
Hey @gubatron, per checking with our Engineers, you need to do some extra steps. Could you try the steps mentioned here https://github.com/firebase/firebase-android-sdk/pull/6565#issuecomment-2734413992?

Also, please update the base branch to align with the current branch. Let me know how it goes.

**Comment by gubatron** [comment]
sorry for the delay, out of the country at the moment on vacation

**Comment by lehcar09** [comment]
Hey @gubatron, the PR (#6822) has been [released](https://firebase.google.com/support/release-notes/android#crashlytics_v19-4-3). 

With that, I'll be closing this issue now. Thanks again for the fix on this issue. Let us know if the issue persists or if there's any misunderstanding so we can reopen the issue.
