### ISSUE TITLE
Problem with migration to Dynamic Feature module of Firebase Messaging

### ISSUE THREAD

**Issue by TAGASK** [firebase/firebase-android-sdk#657]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 3.4.2
  * Firebase Component: com.google.firebase:firebase-messaging
  * Component version: 19.0.1

#### Steps to reproduce:

Add the dependencies to implement firebase messaging
apply plugin google service
implement code to retrieve the token from firebase (crash)

#### Relevant Code:
Either old school :
```java
String refreshedToken = FirebaseInstanceId.getInstance().getToken();
```
Either new school :
```java
 FirebaseApp.initializeApp(this);
        FirebaseInstanceId.getInstance().getInstanceId().addOnSuccessListener(instanceIdResult -> {
            if(instanceIdResult != null) {
                setUserFirebaseToken(instanceIdResult.getToken());
            }
        });
```

crash : 

```
java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: com.google.firebase.components.MissingDependencyException: Unsatisfied dependency for component Component<[class com.google.firebase.remoteconfig.RemoteConfigComponent]>{1, type=0, deps=[Dependency{anInterface=class com.google.firebase.iid.FirebaseInstanceId, type=required, direct=true}, Dependency{anInterface=class com.google.firebase.abt.component.AbtComponent, type=required, direct=true}, Dependency{anInterface=interface com.google.firebase.analytics.connector.AnalyticsConnector, type=optional, direct=true}, Dependency{anInterface=class com.google.firebase.FirebaseApp, type=required, direct=true}, Dependency{anInterface=class android.content.Context, type=required, direct=true}]}: class com.google.firebase.iid.FirebaseInstanceId
        at android.app.ActivityThread.installProvider(ActivityThread.java:6581)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6133)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6043)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: com.google.firebase.components.MissingDependencyException: Unsatisfied dependency for component Component<[class com.google.firebase.remoteconfig.RemoteConfigComponent]>{1, type=0, deps=[Dependency{anInterface=class com.google.firebase.iid.FirebaseInstanceId, type=required, direct=true}, Dependency{anInterface=class com.google.firebase.abt.component.AbtComponent, type=required, direct=true}, Dependency{anInterface=interface com.google.firebase.analytics.connector.AnalyticsConnector, type=optional, direct=true}, Dependency{anInterface=class com.google.firebase.FirebaseApp, type=required, direct=true}, Dependency{anInterface=class android.content.Context, type=required, direct=true}]}: class com.google.firebase.iid.FirebaseInstanceId
        at com.google.firebase.components.ComponentRuntime.validateDependencies(com.google.firebase:firebase-common@@17.1.0:167)
        at com.google.firebase.components.ComponentRuntime.processInstanceComponents(com.google.firebase:firebase-common@@17.1.0:86)
        at com.google.firebase.components.ComponentRuntime.<init>(com.google.firebase:firebase-common@@17.1.0:70)
        at com.google.firebase.FirebaseApp.<init>(com.google.firebase:firebase-common@@17.1.0:421)
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@17.1.0:306)
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@17.1.0:273)
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@17.1.0:257)
        at com.google.firebase.provider.FirebaseInitProvider.onCreate(com.google.firebase:firebase-common@@17.1.0:53)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1927)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1902)
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(com.google.firebase:firebase-common@@17.1.0:47)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6578)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6133) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6043) 
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6944) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
```

**Comment by TAGASK** [comment]
here you can find a sample project. where I reproduced the issue.
https://github.com/TAGASK/messaging
it s base on the sample you gave to use the new version of the firebase messaging library.

**Comment by samtstern** [comment]
The main issue seems to be:
```
Unsatisfied dependency for component Component<[class com.google.firebase.remoteconfig.RemoteConfigComponent]>{1, type=0, deps=[Dependency{anInterface=class com.google.firebase.iid.FirebaseInstanceId, type=required, direct=true}, Dependency{anInterface=class com.google.firebase.abt.component.AbtComponent, type=required, direct=true}, Dependency{anInterface=interface com.google.firebase.analytics.connector.AnalyticsConnector, type=optional, direct=true}, Dependency{anInterface=class com.google.firebase.FirebaseApp, type=required, direct=true}, Dependency{anInterface=class android.content.Context, type=required, direct=true}]}: class com.google.firebase.iid.FirebaseInstanceId
```
@TAGASK thanks for the detailed reproduction.  Could you try adding a dependency on `firebase-remote-config` to each module and see if that changes anything?

**Comment by TAGASK** [comment]
@samtstern the main issue I resolved it by :
apply plugin: 'com.google.gms.google-services' on the main module

but it still not working :
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.firebase.iid.FirebaseInstanceId.getInstanceId()' on a null object reference

Should we be able to use this :
 FirebaseInstanceId.getInstance().getInstanceId()
                .addOnSuccessListener(this, instanceIdResult -> {
                    if (instanceIdResult == null) {
                        Log.w(TAG, "getInstanceId failed");
                        return;
                    }
                    // Get new Instance ID token
                    String token = instanceIdResult.getToken();
                });

please advice to get the token to use firebaseMessaging, thanks.

**Comment by samtstern** [comment]
@TAGASK have you tried something like this?
https://stackoverflow.com/a/54339261/324977

The code you wrote should work without any issues, I have not seen this bug before.
