### ISSUE TITLE
Crashlytics 19.0.3 and higher - unable to report crashes: Could not synthesize final report file

### ISSUE THREAD

**Issue by wd-jacob-kwitkoski** [firebase/firebase-android-sdk#6588]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 
      ```
	Android Studio Ladybug Feature Drop | 2024.2.2 Beta 1
	Build #AI-242.23726.103.2422.12630895, built on November 8, 2024
	Runtime version: 21.0.4+-12422083-b607.1 aarch64
	VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
	Toolkit: sun.lwawt.macosx.LWCToolkit
	macOS 14.7.1
	GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
	Memory: 8192M
	Cores: 12
	Metal Rendering is ON
	Registry:
	  ide.experimental.ui=true
	  i18n.locale=
	Non-Bundled Plugins:
	  String Manipulation (9.15.0)
	  Key Promoter X (2024.2.2)
	  com.intellij.mermaid (0.0.22+IJ.232)
	  org.norbye.tor.kdocformatter (1.6.5)
	  com.jetbrains.kmm (0.8.3(242)-5)
	  com.github.copilot (1.5.29.7524)
	  org.sonarlint.idea (10.12.0.79769)
    ```

  * Firebase Component: `Crashlytics`
  * Component version: `19.0.3`, using BoM version `33.1.2`

### [REQUIRED] Step 3: Describe the problem

When upgrading from:
- Firebase BoM `33.1.1`
- Crashlytics `19.0.2`

to:
- Firebase BoM `33.1.2` (or higher)
- Crashlytics `19.0.3` (or higher)

Crashlytics no longer reports crashes.

#### Prerequisites

1. Have Crashlytics integrated into your app
2. Have a location in app to force a crash to test Crashlytics reporting, [as per the docs](https://firebase.google.com/docs/crashlytics/test-implementation?platform=android#force-test-crash)
3. Enable Crashlytics debug logging [as per the docs](https://firebase.google.com/docs/crashlytics/test-implementation?platform=android#enable-debug-logging)

#### Steps to reproduce:

1. Upgrade from Firebase BoM `33.1.1` & Crashlytics `19.0.2` to Firebase BoM `33.1.2` & Crashlytics `19.0.3`
2. Trigger your force-crash code

#### Expected results

Crashlytics correctly reports the crash

#### Actual results

Crashlytics reports a "warning" log in Logcat:

```
 W  Could not synthesize final report file for /data/user/0/<APPLICATION-ID-REDACTED>/files/.crashlytics.v3/<APPLICATION-ID-REDACTED>/open-sessions/<SESSION-GUID-REDACTED>/report
java.io.FileNotFoundException: /data/user/0/<APPLICATION-ID-REDACTED>/files/.crashlytics.v3/<APPLICATION-ID-REDACTED>/open-sessions/<SESSION-GUID-REDACTED>/report: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.FileInputStream.<init>(FileInputStream.java:160)
	at com.google.firebase.crashlytics.internal.persistence.CrashlyticsReportPersistence.readTextFile(CrashlyticsReportPersistence.java:431)
	at com.google.firebase.crashlytics.internal.persistence.CrashlyticsReportPersistence.synthesizeReportFile(CrashlyticsReportPersistence.java:356)
	at com.google.firebase.crashlytics.internal.persistence.CrashlyticsReportPersistence.synthesizeReport(CrashlyticsReportPersistence.java:322)
	at com.google.firebase.crashlytics.internal.persistence.CrashlyticsReportPersistence.finalizeReports(CrashlyticsReportPersistence.java:195)
	at com.google.firebase.crashlytics.internal.common.SessionReportingCoordinator.finalizeSessions(SessionReportingCoordinator.java:194)
	at com.google.firebase.crashlytics.internal.common.CrashlyticsController.doCloseSessions(CrashlyticsController.java:631)
	at com.google.firebase.crashlytics.internal.common.CrashlyticsController.doCloseSessions(CrashlyticsController.java:585)
	at com.google.firebase.crashlytics.internal.common.CrashlyticsController$2.call(CrashlyticsController.java:218)
	at com.google.firebase.crashlytics.internal.common.CrashlyticsController$2.call(CrashlyticsController.java:199)
	at com.google.firebase.crashlytics.internal.common.CrashlyticsBackgroundWorker$3.then(CrashlyticsBackgroundWorker.java:105)
	at com.google.android.gms.tasks.zze.run(com.google.android.gms:play-services-tasks@@18.1.0:1)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:67)
	at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:27)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8063)
	at libcore.io.IoBridge.open(IoBridge.java:560)
	at java.io.FileInputStream.<init>(FileInputStream.java:160) 
	at com.google.firebase.crashlytics.internal.persistence.CrashlyticsReportPersistence.readTextFile(CrashlyticsReportPersistence.java:431) 
	at com.google.firebase.crashlytics.internal.persistence.CrashlyticsReportPersistence.synthesizeReportFile(CrashlyticsReportPersistence.java:356) 
	at com.google.firebase.crashlytics.internal.persistence.CrashlyticsReportPersistence.synthesizeReport(CrashlyticsReportPersistence.java:322) 
	at com.google.firebase.crashlytics.internal.persistence.CrashlyticsReportPersistence.finalizeReports(CrashlyticsReportPersistence.java:195) 
	at com.google.firebase.crashlytics.internal.common.SessionReportingCoordinator.finalizeSessions(SessionReportingCoordinator.java:194) 
	at com.google.firebase.crashlytics.internal.common.CrashlyticsController.doCloseSessions(CrashlyticsController.java:631) 
	at com.google.firebase.crashlytics.internal.common.CrashlyticsController.doCloseSessions(CrashlyticsController.java:585) 
	at com.google.firebase.crashlytics.internal.common.CrashlyticsController$2.call(CrashlyticsController.java:218) 
	at com.google.firebase.crashlytics.internal.common.CrashlyticsController$2.call(CrashlyticsController.java:199) 
	at com.google.firebase.crashlytics.internal.common.CrashlyticsBackgroundWorker$3.then(CrashlyticsBackgroundWorker.java:105) 
	at com.google.android.gms.tasks.zze.run(com.google.android.gms:play-services-tasks@@18.1.0:1) 
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) 
	at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:67) 
	at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:27) 
	at java.lang.Thread.run(Thread.java:1012) 
```

#### Relevant Code:

N/A, the steps are indicated as above.

I think it might have something to do with this feature, from the [`19.0.3` release notes](https://firebase.google.com/support/release-notes/android#crashlytics_v19-0-3):
>- Updated the internal file system to handle long file names.

**Comment by lehcar09** [comment]
Hi @wd-jacob-kwitkoski, thank you for reaching out. I tried reproducing the issue, however, the reports are uploaded without any issue. Per checking, the Firebase Crashlytics v19.0.2 and v19.0.3 are using the same path for crash reports.

By any chance, can you share an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) to help us investigate the issue? If you're unable to provide one, can you try our [quickstart app](https://github.com/firebase/quickstart-android/tree/master) and see if you can reproduce the issue? 

Aside from that, I would suggest using the latest version of Firebase Crashlytics ([v19.3.0](https://firebase.google.com/support/release-notes/android#bom_v33-7-0)) to ensure that you have the latest bug fixes that might be causing issues.

**Comment by wd-jacob-kwitkoski** [comment]
> By any chance, can you share an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) to help us investigate the issue? If you're unable to provide one, can you try our [quickstart app](https://github.com/firebase/quickstart-android/tree/master) and see if you can reproduce the issue?

I'll try to get an MVCE to reproduce this.

> Aside from that, I would suggest using the latest version of Firebase Crashlytics ([v19.3.0](https://firebase.google.com/support/release-notes/android#bom_v33-7-0)) to ensure that you have the latest bug fixes that might be causing issues.

I have tested on all versions of Crashlytics above `19.0.2` and was able to reproduce the same issue.
| Crashlytics version | BoM version |
|--:|--:|
| `19.3.0` | `33.7.0` |
| `19.2.1` | `33.5.0` |
| `19.2.0` | `33.4.0` |
| `19.1.0` | `33.3.0` |
| `19.0.3` | `33.1.2` |

The AVD tested was on Android 14, API 34:
```
Properties
avd.ini.displayname              Pixel 8 API 34
avd.ini.encoding                 UTF-8
AvdId                            Pixel_8_API_34
disk.dataPartition.size          16G
fastboot.chosenSnapshotFile      
fastboot.forceChosenSnapshotBoot no
fastboot.forceColdBoot           no
fastboot.forceFastBoot           yes
hw.accelerometer                 yes
hw.arc                           false
hw.audioInput                    yes
hw.battery                       yes
hw.camera.back                   virtualscene
hw.camera.front                  emulated
hw.cpu.ncore                     4
hw.device.hash2                  MD5:90973dc6b682b7344df33a6250481866
hw.device.manufacturer           Google
hw.device.name                   pixel_8
hw.dPad                          no
hw.gps                           yes
hw.gpu.enabled                   yes
hw.gpu.mode                      auto
hw.initialOrientation            portrait
hw.keyboard                      yes
hw.lcd.density                   420
hw.lcd.height                    2400
hw.lcd.width                     1080
hw.mainKeys                      no
hw.ramSize                       2048
hw.sdCard                        yes
hw.sensors.orientation           yes
hw.sensors.proximity             yes
hw.trackBall                     no
image.androidVersion.api         34
image.sysdir.1                   system-images/android-34/google_apis_playstore/arm64-v8a/
PlayStore.enabled                true
runtime.network.latency          none
runtime.network.speed            full
showDeviceFrame                  yes
skin.dynamic                     yes
tag.display                      Google Play
tag.displaynames                 Google Play
tag.id                           google_apis_playstore
tag.ids                          google_apis_playstore
vm.heapSize                      228
```

**Comment by lehcar09** [comment]
Hey @wd-jacob-kwitkoski, I'll mark this as needs-info for now. Don't worry if the issue closes due to stale, we can always reopen this once we have new information. Thanks!
