### ISSUE TITLE
FirebaseRemoteConfig.getInstance() throws NPE

### ISSUE THREAD

**Issue by arseniy899** [firebase/firebase-android-sdk#685]
### Step 1: Describe your environment

  * Android device: Xiaomi Redmi 3S
  * Android OS version: 6.1
  * Google Play Services version: 17.7.85
  * Firebase/Play Services SDK version: 16.4.1, 18.0.0 (tried both of version with no success)
  
### Step 2: Describe the problem:
Initilizing Remote Config gives NullPointerException. I have updated project to new gradle version in case of problem with resouces in the old one. Before the update everything worked fine.
#### Steps to reproduce:

  1. Init Firebase App
  2. Try to get instance of Remote Config
  
#### Observed Results:

  Instead of instance, got NPE:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.firebase.remoteconfig.FirebaseRemoteConfig com.google.firebase.remoteconfig.RemoteConfigComponent.get(java.lang.String)' on a null object reference
     at com.google.firebase.remoteconfig.FirebaseRemoteConfig.getInstance(Unknown Source)
     at com.google.firebase.remoteconfig.FirebaseRemoteConfig.getInstance(Unknown Source)

```
  
#### Expected Results:

  * I excpected to get instance to use Remote Config in the future
  
#### Relevant Code:
MyApp (init of Firebase App):
  ```
  public class MyApp extends Application
{
	@Override
	public void onCreate ()
	{
		super.onCreate();
		FirebaseApp.initializeApp(this);
	}

	@Override
	protected void attachBaseContext(Context base) {

		super.attachBaseContext(base);
		MultiDex.install(this);
		SplitCompat.install(this);
	}

}
```
LoginActivty (Launch activity):
```
public class LoginActivity extends ActivityCL //implements Thread.UncaughtExceptionHandler
{

	@Override
	@AddTrace(name = "LoginActivity.onCreate", enabled = true)
	protected void onCreate(Bundle savedInstanceState)
	{
		super.onCreate (savedInstanceState);
		FirebaseRemoteConfig remoteConfig = FirebaseRemoteConfig.getInstance();
	}
}
```
My app module gradle config:
```
apply plugin: 'com.android.application'
apply plugin: 'com.google.firebase.firebase-perf'
apply plugin: 'io.fabric'
apply plugin: 'com.google.gms.google-services'
android {
	compileSdkVersion 28
	useLibrary 'org.apache.http.legacy'
	packagingOptions {
		exclude 'META-INF/DEPENDENCIES'
		exclude 'META-INF/LICENSE'
		exclude 'META-INF/LICENSE.txt'
		exclude 'META-INF/license.txt'
		exclude 'META-INF/NOTICE'
		exclude 'META-INF/NOTICE.txt'
		exclude 'META-INF/notice.txt'
		exclude 'META-INF/androidsupportmultidexversion.txt'
		exclude 'androidsupportmultidexversion.txt'
		exclude 'META-INF/ASL2.0'
		exclude 'project.properties'
		exclude 'META-INF/INDEX.LIST'
	}
	lintOptions {
		checkReleaseBuilds false
		abortOnError false
	}

	defaultConfig {
		applicationId "********"
		minSdkVersion 18
		targetSdkVersion 28
		multiDexEnabled true
		versionCode ****
		versionName "***"
		vectorDrawables.useSupportLibrary true
		testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
	}
	configurations.all {
		resolutionStrategy.force 'com.google.code.findbugs:jsr305:3.0.1'
	}
	buildTypes {
		release {
			minifyEnabled true
			proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
			multiDexEnabled = true
		}
		debug {
			multiDexEnabled = true
			minifyEnabled = false
		}
	}
	compileOptions {
		sourceCompatibility JavaVersion.VERSION_1_7
		targetCompatibility JavaVersion.VERSION_1_7
	}
	dynamicFeatures = [":****", ":****"]
	dexOptions {
		preDexLibraries = true
	}

}
dependencies {
	implementation fileTree(include: ['*.jar'], dir: 'libs')

	repositories {
		maven { url "https://dl.bintray.com/hani-momanii/maven" }
		maven { url "https://github.com/omadahealth/omada-nexus/raw/master/release" }
		mavenCentral()
		google()
		jcenter()
		maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
		maven { url "https://s3.amazonaws.com/repo.commonsware.com" }
		maven { url "http://dl.bintray.com/waynejo/maven" }
		maven { url "https://jitpack.io" }
	}
	//...

	implementation 'com.google.android.gms:play-services-location:17.0.0'
	
	implementation 'com.google.firebase:firebase-core:17.0.1'
	implementation group: 'com.google.firebase', name: 'firebase-iid', version: '19.0.1'
	implementation 'com.google.firebase:firebase-messaging:19.0.1'
	implementation 'com.crashlytics.sdk.android:crashlytics:2.10.1'
	implementation 'com.google.firebase:firebase-perf:18.0.1'
	implementation 'com.google.firebase:firebase-config:16.4.1'

	implementation 'com.google.android.play:core:1.6.1'
	//...
	testImplementation 'junit:junit:4.12'
}
```

**Comment by samtstern** [comment]
@vkryachko can you take a look?  Seems like a component discovery thing with apps that have multiple modules.

**Comment by vkryachko** [comment]
@arseniy899 A few questions to help diagnose the issue:

* Is your app directboot aware? i.e. does it start when the device is still in directboot mode?
* Can you post your AndroidManifest.xml(with any pii removed from it)? I am specifically interested in the full following section tag contents `<service android:name="com.google.firebase.components.ComponentDiscoveryService">`
* The adb startup log of the app startup, specifically log entries tagged with `ComponentDiscovery`

Thanks

**Comment by SilverFoxA** [comment]
@vkryachko I'm not sure if this is the same issue, but let's assume it to be same as you stated in the other issue.

Please find the details you requested listed below:

1. I'm not sure, assuming it to be no. Here's the git repo I'm using: https://github.com/WhatsApp/stickers/tree/master/Android
2. I have made literally no changes to `Androidmanifest.xml` file. You can refer to this https://github.com/WhatsApp/stickers/blob/master/Android/app/src/main/AndroidManifest.xml

**Comment by vkryachko** [comment]
@SilverFoxA The log you provided suggests that the manifest is not correctly merged.
Though I cloned the repo you mentioned, added firebase-config:18.0.0 plus google-services plugin to it and could not repro the issue you're having, namely firebase initializes successfully and RemoteConfig is not null.

I'd need to know more about the modifications you've made to the build

**Comment by SilverFoxA** [comment]
Understood. Please find the `build.gradle` file I'm assuming it has something to do with `product flavor` but I did use `secondary` source, that too didn't work.

```
 apply plugin: 'com.android.application'

android {
    //the compression of webp file during build causes problem with FileDescriptor in ContentProvider.
    aaptOptions {
        noCompress "webp"
    }
    compileSdkVersion 29
    defaultConfig {
        applicationId "com.example.samplestickerapp"
        minSdkVersion 19
        targetSdkVersion 29
        versionCode 2
        versionName "1.0.0.1"
        multiDexEnabled true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

    }
    buildTypes {
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    lintOptions {
        checkReleaseBuilds false
        // Or, if you prefer, you can continue to check for errors in release builds,
        // but continue the build even when errors are found:
        abortOnError false
    }

    flavorDimensions "default"

    productFlavors {
        bengali_superstar_dialouge {
            applicationId "com.silverfoxa.banglamoviestickers"
            versionNameSuffix "-bnglisprstrdlg"
            //signingConfig signingConfigs.bengali_superstar_dialouge

            def contentProviderAuthority = applicationId + ".StickerContentProvider"
            // Creates a placeholder property to use in the manifest.
            manifestPlaceholders =
                    [contentProviderAuthority: contentProviderAuthority]
            // Adds a new field for the authority to the BuildConfig class.
            buildConfigField("String",
                    "CONTENT_PROVIDER_AUTHORITY",
                    "\"${contentProviderAuthority}\"")
        }

       ...
    }
    sourceSets {
        bengali_superstar_dialouge {
            manifest.srcFile('src/bengali_superstar_dialouge/AndroidManifest.xml')
            java.srcDirs('src/bengali_superstar_dialouge/java')
            assets.srcDir('src/bengali_superstar_dialouge/assets')
            res.srcDir('src/bengali_superstar_dialouge/res')
        }

        ...
    }

    signingConfigs {
//        debug {
//            storeFile file("/home/.../debugkeystore.jks")
//            storePassword "..."
//            keyAlias "..."
//            keyPassword "..."
//        }
//        bengali_superstar_dialouge {
//            storeFile file("/home/.../testkeystore1.jks")
//            storePassword "..."
//            keyAlias "..."
//            keyPassword "..."
//        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    packagingOptions {
        exclude 'lib/*/libnative-imagetranscoder.so'
        exclude 'lib/*/libnative-filters.so'
    }

    // Configures multiple APKs based on ABI.
    // see https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
//    splits {
//        abi {
//            enable true // Enables building multiple APKs per ABI.
//            universalApk true // Specifies that we do not want to also generate a universal APK that includes all ABIs.
//        }
//    }
}

task checkDebug {
    doLast {
        println("checkDebug")
        if (android.defaultConfig.applicationId.startsWith("com.whatsapp")) {
            throw new GradleException("applicationId in defaultConfig cannot start with com.whatsapp, please change your applicationId in app/build.gradle")
        }
        checkApplicationIdInDebug()
    }
}

private void checkApplicationIdInDebug() {
    Properties properties = new Properties()
    properties.load(project.rootProject.file('local.properties').newDataInputStream())
    def ignoreApplicationIdCheck = properties.getProperty('ignoreApplicationIdCheck')
    if (ignoreApplicationIdCheck == null) {
        if (android.defaultConfig.applicationId == "com.example.samplestickerapp") {
            throw new GradleException("Your applicationId is currently com.example.samplestickerapp, please change your applicationId to a different string in app/build.gradle in line 10")
        }
    } else {
        println("application id check ignored")
    }
}


task checkRelease {
    doLast {
        println("checkRelease")
        if (android.defaultConfig.applicationId.startsWith("com.example")) {
            throw new GradleException("applicationId in defaultConfig cannot start with com.example, please change your applicationId in app/build.gradle")
        }
    }
}

tasks.whenTaskAdded { task ->
    println(task.name)
    if (task.name.contains("assembleDebug")) {
        task.dependsOn checkDebug
    }
    if (task.name.contains("assembleRelease")) {
        task.dependsOn checkRelease
    }
}


dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:multidex:1.0.3'
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'com.google.android.material:material:1.0.0'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.0.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.2.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    implementation 'androidx.recyclerview:recyclerview:1.0.0'
    implementation 'com.github.piasy:GlideImageLoader:1.5.7'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'

    implementation 'com.google.firebase:firebase-core:17.0.1'
    implementation 'com.google.firebase:firebase-firestore:20.2.0'

    implementation 'com.google.firebase:firebase-analytics:17.0.1'
    implementation 'com.crashlytics.sdk.android:crashlytics:2.10.1'

    implementation 'com.google.firebase:firebase-ads:18.1.1'
    implementation 'com.google.firebase:firebase-messaging:19.0.1'

    implementation "io.karn:notify:1.3.0"

    implementation 'com.facebook.fresco:fresco:2.0.0'
    implementation 'com.facebook.fresco:webpsupport:2.0.0'
    implementation 'com.facebook.fresco:animated-webp:2.0.0'
    implementation 'com.facebook.fresco:animated-base:2.0.0'
}
apply plugin: 'com.google.gms.google-services'
```

**Comment by SilverFoxA** [comment]
@vkryachko do you need any more details to repro the error case?

**Comment by SilverFoxA** [comment]
Hello @vkryachko , our product line up is halted for 30+ days now. Any possibility of getting this fixed this year?

**Comment by SilverFoxA** [comment]
Wasted 30+ days in this just because firebase documentation doesn't detail anything about this.


Seems like `google` has changed the sdk. You need to extend `ComponentDiscoveryService`. Add the below code to the bottom of your android manifest application.

The below configuration will work for the following services 

 1. Firebase Database
 2. Firebase Analytics
 3. Firebase Firestore
 4. Firebase Auth

````
    <service android:name="com.google.firebase.components.ComponentDiscoveryService" >
            <meta-data
                android:name="com.google.firebase.components:com.google.firebase.analytics.connector.internal.AnalyticsConnectorRegistrar"
                android:value="com.google.firebase.components.ComponentRegistrar" />
            <meta-data
                android:name="com.google.firebase.components:com.google.firebase.firestore.FirestoreRegistrar"
                android:value="com.google.firebase.components.ComponentRegistrar"/>
            <meta-data
                android:name="com.google.firebase.components:com.google.firebase.iid.Registrar"
                android:value="com.google.firebase.components.ComponentRegistrar" />
            <meta-data
                android:name="com.google.firebase.components:com.google.firebase.auth.FirebaseAuthRegistrar"
                android:value="com.google.firebase.components.ComponentRegistrar" />
            <meta-data
                android:name="com.google.firebase.components:com.google.firebase.database.DatabaseRegistrar"
                android:value="com.google.firebase.components.ComponentRegistrar"/>
        </service>
````

**Comment by ashwinraghav** [comment]
@SilverFoxA  :  Sorry you had problems integrating with Remote Config.
There is no expectation that developers need to add these entries to the manifest.
They are are intended to live in Firebase libraries and we expect the [manifest merging tooling](https://developer.android.com/studio/build/manifest-merge) in the android toolchain to land these into your final Manifest. For eg, remote config 16.4.1 you are using has the following entry in the manifest present in the .aar.

```xml
        <service android:name="com.google.firebase.components.ComponentDiscoveryService" >
            <meta-data
                android:name="com.google.firebase.components:com.google.firebase.remoteconfig.RemoteConfigRegistrar"
                android:value="com.google.firebase.components.ComponentRegistrar" />
        </service>
```

We could use your help to understand where the merging is going wrong. Particularly with the combination of product flavors and build types indicated by your build.gradle, it is possible that this entry gets squashed in your final Manifest.

[Here]([https://developer.android.com/studio/build/manifest-merge.html#inspect_the_merged_manifest_and_find_conflicts) is some info on how this can be debugged. Please post back if you discover where the merging fails. It could help other developers that may be facing the same issue. 

Thanks for working with us on this.

**Comment by SilverFoxA** [comment]
Hello @ashwinraghav 

Thanks for your support, I partially found the error. As you pointed out it has to do with the "manifest merging tool" but it's not directly linked to the tool rather developer fault i'm assuming.

I had this particular line in my manifest `tools:node="replace"` the reason of adding this was out solve the merge conflicts. I'm assuming this lead to replacing the above scripts that you mentioned. I haven't debugged the entire case in full-depth.

Currently i'm testing with the below manifest merger config, I shall update if I find something useful 

    tools:node="merge"
    tools:replace="android:label,android:name,android:theme"
