### ISSUE TITLE
Bug-SQLite Exception during removeOrphanedDocuments

### ISSUE THREAD

**Issue by highthunder** [firebase/firebase-android-sdk#706]
### [READ] Step 1: Are you in the right place?

Yes, this is an issue with Cloud Firestore's internal on-device sqlite database and this repository appears to contain all of the code required to manage that database.

### [REQUIRED] Step 2: Describe your environment

Android Studio version: 3.4.2
Firebase Component: Cloud Firestore
Component version: 19.0.2 (via firebase-bom:19.0.0)
Compile/Target SDK version: 28

### [REQUIRED] Step 3: Describe the problem

This is probably the same issue that I reported a few months ago where user's with over ~7000 rows crashed during a migration, just with a different query:
https://github.com/firebase/firebase-android-sdk/issues/370

#### Stack trace:

```
# OS Version: 7.1.1
# Device: Galaxy Tab E 8.0
# RAM Free: 32.9%
# Disk Free: 57.6%

#0. Crashed: main
       at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$5 + 379(AsyncQueue.java:379)
       at com.google.firebase.firestore.util.AsyncQueue$$Lambda$5.run(AsyncQueue.java)
       at android.os.Handler.handleCallback + 751(Handler.java:751)
       at android.os.Handler.dispatchMessage + 95(Handler.java:95)
       at android.os.Looper.loop + 154(Looper.java:154)
       at android.app.ActivityThread.main + 6823(ActivityThread.java:6823)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run + 1557(ZygoteInit.java:1557)
       at com.android.internal.os.ZygoteInit.main + 1445(ZygoteInit.java:1445)

--

Fatal Exception: java.lang.RuntimeException: Internal error in Firestore (19.0.2).
       at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$5 + 379(AsyncQueue.java:379)
       at com.google.firebase.firestore.util.AsyncQueue$$Lambda$5.run(AsyncQueue.java)
       at android.os.Handler.handleCallback + 751(Handler.java:751)
       at android.os.Handler.dispatchMessage + 95(Handler.java:95)
       at android.os.Looper.loop + 154(Looper.java:154)
       at android.app.ActivityThread.main + 6823(ActivityThread.java:6823)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run + 1557(ZygoteInit.java:1557)
       at com.android.internal.os.ZygoteInit.main + 1445(ZygoteInit.java:1445)

Caused by java.lang.IllegalStateException: Couldn't read row 6987, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
       at android.database.CursorWindow.nativeGetString(CursorWindow.java)
       at android.database.CursorWindow.getString + 451(CursorWindow.java:451)
       at android.database.AbstractWindowedCursor.getString + 51(AbstractWindowedCursor.java:51)
       at com.google.firebase.firestore.local.SQLiteLruReferenceDelegate.removeOrphanedDocuments + 157(SQLiteLruReferenceDelegate.java:157)
       at com.google.firebase.firestore.local.SQLiteLruReferenceDelegate$$Lambda$3.accept(SQLiteLruReferenceDelegate.java)
       at com.google.firebase.firestore.local.SQLitePersistence$Query.forEach + 456(SQLitePersistence.java:456)
       at com.google.firebase.firestore.local.SQLiteLruReferenceDelegate.removeOrphanedDocuments + 155(SQLiteLruReferenceDelegate.java:155)
       at com.google.firebase.firestore.local.LruGarbageCollector.removeOrphanedDocuments + 226(LruGarbageCollector.java:226)
       at com.google.firebase.firestore.local.LruGarbageCollector.runGarbageCollection + 270(LruGarbageCollector.java:270)
       at com.google.firebase.firestore.local.LruGarbageCollector.collect + 245(LruGarbageCollector.java:245)
       at com.google.firebase.firestore.local.LocalStore.collectGarbage + 621(LocalStore.java:621)
       at com.google.firebase.firestore.local.LocalStore$$Lambda$10.get(LocalStore.java)
       at com.google.firebase.firestore.local.SQLitePersistence.runTransaction + 200(SQLitePersistence.java:200)
       at com.google.firebase.firestore.local.LocalStore.collectGarbage + 621(LocalStore.java:621)
       at com.google.firebase.firestore.local.LruGarbageCollector$Scheduler.lambda$scheduleGC$0 + 144(LruGarbageCollector.java:144)
       at com.google.firebase.firestore.local.LruGarbageCollector$Scheduler$$Lambda$1.run(LruGarbageCollector.java)
       at com.google.firebase.firestore.util.AsyncQueue$DelayedTask.handleDelayElapsed + 129(AsyncQueue.java:129)
       at com.google.firebase.firestore.util.AsyncQueue$DelayedTask.access$lambda$0(AsyncQueue.java:129)
       at com.google.firebase.firestore.util.AsyncQueue$DelayedTask.handleDelayElapsed(AsyncQueue.java:126)
       at com.google.firebase.firestore.util.AsyncQueue$DelayedTask$$Lambda$1.run(AsyncQueue.java)
       at java.util.concurrent.Executors$RunnableAdapter.call + 428(Executors.java:428)
       at java.util.concurrent.FutureTask.run + 237(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run + 272(ScheduledThreadPoolExecutor.java:272)
       at java.util.concurrent.ThreadPoolExecutor.runWorker + 1133(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run + 607(ThreadPoolExecutor.java:607)
       at com.google.firebase.firestore.util.AsyncQueue$DelayedStartFactory.run + 205(AsyncQueue.java:205)
       at java.lang.Thread.run + 762(Thread.java:762)
```

**Comment by highthunder** [comment]
We are still having users suffering from this issue.

**Comment by rsgowman** [comment]
I spoke to @schmidt-sebastian ; he said this *might* be caused by our garbage collection attempting to clean up too many documents at once, which might exceed sqlite's cursorwindow. If this is the case, then it should be possible to apply a similar fix.

In the meantime, you could try disabling garbage collection by setting `FirebaseFirestoreSettings.setCacheSizeBytes` to `FirebaseFirestoreSettings.CACHE_SIZE_UNLIMITED`.

Relevant links:

https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/FirebaseFirestore.html#setFirestoreSettings(com.google.firebase.firestore.FirebaseFirestoreSettings)

https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/FirebaseFirestoreSettings.Builder.html#setCacheSizeBytes(long)

https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/FirebaseFirestoreSettings.html#CACHE_SIZE_UNLIMITED

**Comment by highthunder** [comment]
Looking at the similarity between the two issues makes me suspect it might be an issue with nested queries.
