### ISSUE TITLE
Service not registered: com.google.android.gms.common.internal.zzf@20fb92a

### ISSUE THREAD

**Issue by zhangyubao** [firebase/firebase-android-sdk#804]
Fatal Exception: java.lang.IllegalArgumentException: Service not registered: com.google.android.gms.common.internal.zzf@20fb92a
       at android.app.LoadedApk.forgetServiceDispatcher + 1297(LoadedApk.java:1297)
       at android.app.ContextImpl.unbindService + 1520(ContextImpl.java:1520)
       at android.content.ContextWrapper.unbindService + 658(ContextWrapper.java:658)
       at com.google.android.gms.common.stats.ConnectionTracker.unbindService + 25(ConnectionTracker.java:25)
       at com.google.android.gms.common.internal.zzf.zzf + 41(zzf.java:41)
       at com.google.android.gms.common.internal.zze.handleMessage + 45(zze.java:45)
       at android.os.Handler.dispatchMessage + 98(Handler.java:98)
       at com.google.android.gms.internal.common.zze.dispatchMessage + 8(zze.java:8)
       at android.os.Looper.loop + 163(Looper.java:163)
       at android.app.ActivityThread.main + 6393(ActivityThread.java:6393)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run + 933(ZygoteInit.java:933)
       at com.android.internal.os.ZygoteInit.main + 823(ZygoteInit.java:823)

**Comment by schmidt-sebastian** [comment]
@zhangyubao Can you let us products you are trying to use and what versions and SDKs you are depending on?

**Comment by schmidt-sebastian** [comment]
Over to Messaging team.

**Comment by zhangyubao** [comment]
Any update comment there. Many thanks

**Comment by ciarand** [comment]
Hey @zhangyubao, that stack trace is coming from Firebase InstanceID and play-services-analytics doesn't have a dependency on Firebase InstanceID. Can you add the exact version of Firebase InstanceID (`firebase-iid`) that your project is including? It may be being included by `firebase-messaging` if you've got a dependency on that.

**Comment by NuODaniel** [comment]
I met similar issue
- Logcat
```
java.lang.IllegalArgumentException: Service not registered: com.google.android.gms.common.internal.zzf@1b0e049
    at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1570)
    at android.app.ContextImpl.unbindService(ContextImpl.java:1702)
    at android.content.ContextWrapper.unbindService(ContextWrapper.java:727)
    at com.google.android.gms.common.stats.ConnectionTracker.unbindService(Unknown Source:0)
    at com.google.android.gms.common.internal.zzf.zzf(Unknown Source:24)
    at com.google.android.gms.common.internal.zze.handleMessage(Unknown Source:136)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at com.google.android.gms.internal.common.zze.dispatchMessage(Unknown Source:0)
    at android.os.Looper.loop(Looper.java:201)
    at android.app.ActivityThread.main(ActivityThread.java:6810)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

Gradle setting below.
- app.gradle
```
implement 'com.google.firebase:firebase-analytics:17.2.0'
apply plugin: 'com.google.gms.google-services'
```

- project.gradle
```
classpath 'com.android.tools.build:gradle:3.4.2'
classpath 'com.google.gms:google-services:4.3.2'
```

Any resolution for this plz

**Comment by zhangyubao** [comment]
@NuODaniel I still have any resolution for this error. Need to @ciarand help

**Comment by zhangyubao** [comment]
`Fatal Exception: java.lang.IllegalArgumentException: Service not registered: com.google.firebase.iid.zzac@9470e33
       at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1681)
       at android.app.ContextImpl.unbindService(ContextImpl.java:1781)
       at android.content.ContextWrapper.unbindService(ContextWrapper.java:730)
       at com.google.android.gms.common.stats.ConnectionTracker.unbindService(ConnectionTracker.java:25)
       at com.google.firebase.iid.zzac.zzz(zzac.java:94)
       at com.google.firebase.iid.zzac.zza(zzac.java:39)
       at com.google.firebase.iid.zzaf.handleMessage(zzaf.java:2)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at com.google.android.gms.internal.firebase_messaging.zze.dispatchMessage(zze.java:8)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7285)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)`

**Comment by zhangyubao** [comment]
`Fatal Exception: java.lang.IllegalArgumentException: Service not registered: com.google.firebase.iid.zzac@9470e33
       at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1681)
       at android.app.ContextImpl.unbindService(ContextImpl.java:1781)
       at android.content.ContextWrapper.unbindService(ContextWrapper.java:730)
       at com.google.android.gms.common.stats.ConnectionTracker.unbindService(ConnectionTracker.java:25)
       at com.google.firebase.iid.zzac.zzz(zzac.java:94)
       at com.google.firebase.iid.zzac.zza(zzac.java:39)
       at com.google.firebase.iid.zzaf.handleMessage(zzaf.java:2)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at com.google.android.gms.internal.firebase_messaging.zze.dispatchMessage(zze.java:8)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7285)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)`



`Fatal Exception: java.lang.IllegalArgumentException: Service not registered: com.google.android.gms.common.internal.zzf@43d8ab4
       at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1766)
       at android.app.ContextImpl.unbindService(ContextImpl.java:1810)
       at android.content.ContextWrapper.unbindService(ContextWrapper.java:741)
       at com.google.android.gms.common.stats.ConnectionTracker.unbindService(ConnectionTracker.java:25)
       at com.google.android.gms.common.internal.zzf.zzf(zzf.java:41)
       at com.google.android.gms.common.internal.zze.handleMessage(zze.java:45)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at com.google.android.gms.internal.common.zze.dispatchMessage(zze.java:8)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)`

**Comment by zhangyubao** [comment]
Fatal Exception: java.lang.IllegalArgumentException: Service not registered: com.google.android.gms.common.internal.zzf@43d8ab4
       at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1766)
       at android.app.ContextImpl.unbindService(ContextImpl.java:1810)
       at android.content.ContextWrapper.unbindService(ContextWrapper.java:741)
       at com.google.android.gms.common.stats.ConnectionTracker.unbindService(ConnectionTracker.java:25)
       at com.google.android.gms.common.internal.zzf.zzf(zzf.java:41)
       at com.google.android.gms.common.internal.zze.handleMessage(zze.java:45)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at com.google.android.gms.internal.common.zze.dispatchMessage(zze.java:8)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
