### ISSUE TITLE
Fire base in-app messaging THROWS NULL POINTER EXCEPTION in Card Layout Campaign

### ISSUE THREAD

**Issue by Harishsharma714** [firebase/firebase-android-sdk#897]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: dd.com.myq, PID: 1824
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
        at com.google.firebase.inappmessaging.display.internal.bindingwrappers.CardBindingWrapper.setMessage(com.google.firebase:firebase-inappmessaging-display@@19.0.1:146)
        at com.google.firebase.inappmessaging.display.internal.bindingwrappers.CardBindingWrapper.inflate(com.google.firebase:firebase-inappmessaging-display@@19.0.1:84)
        at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay.inflateBinding(com.google.firebase:firebase-inappmessaging-display@@19.0.1:362)
        at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay.access$400(com.google.firebase:firebase-inappmessaging-display@@19.0.1:83)
        at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay$2.run(com.google.firebase:firebase-inappmessaging-display@@19.0.1:304)
        at android.os.Handler.handleCallback(Handler.java:794)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6651)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)

**Comment by JasonAHeron** [comment]
Looks like this must be coming from 
https://github.com/firebase/firebase-android-sdk/blob/master/firebase-inappmessaging-display/src/main/java/com/google/firebase/inappmessaging/display/internal/bindingwrappers/CardBindingWrapper.java#L146

We don't do SDK level null checks here because the console enforces non-null titles. @Harishsharma714 did you somehow manage to create a card message without a title?

**Comment by Harishsharma714** [comment]
No, didn't create a card message with title.

**Comment by Harishsharma714** [comment]
I am getting following error- 

 java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
        at com.google.firebase.inappmessaging.display.internal.bindingwrappers.CardBindingWrapper.setMessage(com.google.firebase:firebase-inappmessaging-display@@19.0.2:146)
        at com.google.firebase.inappmessaging.display.internal.bindingwrappers.CardBindingWrapper.inflate(com.google.firebase:firebase-inappmessaging-display@@19.0.2:84)
        at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay.inflateBinding(com.google.firebase:firebase-inappmessaging-display@@19.0.2:356)
        at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay.access$000(com.google.firebase:firebase-inappmessaging-display@@19.0.2:83)
        at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay$1.run(com.google.firebase:firebase-inappmessaging-display@@19.0.2:298)
        at android.os.Handler.handleCallback(Handler.java:794)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6651)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)

![image](https://user-images.githubusercontent.com/25315878/68851726-6d177300-06fc-11ea-868f-710f17ec4143.png)

**Comment by Harishsharma714** [comment]
I am getting this error only in card campaign no in any other campaign.
