### ISSUE TITLE
loadedapk.java bug

### ISSUE THREAD

**Issue by hzy87email** [firebase/firebase-android-sdk#901]
1. Fatal Exception: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 } bqHint=1 (has extras) } in com.google.firebase.iid.zzaz@790a33a
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1195)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

2. Caused by java.lang.IllegalArgumentException: Receiver not registered: com.google.firebase.iid.zzaz@790a33a
       at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1054)
       at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1376)
       at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:659)
       at com.google.firebase.iid.zzaz.onReceive(zzaz.java:16)
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1185)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

version:
com.google.firebase:firebase-messaging:17.3.3
com.google.firebase:firebase-core:16.0.7

**Comment by aguatno** [comment]
Hi @hzy87email Thanks for waiting. Can you please provide the actual code to recreate this? It will make it easier to debug. If we can get code that demonstrates the issue, we'd be happy to dig into this. Thanks
